### ISSUE TITLE
Gym battle ability to choose attackers?

### ISSUE THREAD

**Issue by erytcxbv** [Necrobot-Private/NecroBot#1003]
Hello is there a setting I'm not aware of that allows you to choose which Pokemon to use to attack gyms with? I want to attack with nothing but Vaporeon's but my Snorlax have higher CP so the bot defaults to them and it cases my attacks to time out almost all the time. The exclude number of top Pokemon doesn't seem to work and when I add Snorlax to the exempt Pokemon to deploy it still attacks with them.

**Comment by samuraitruong** [comment]
it not hard to implement but it hard to config,  Maybe it only work with combine with GUI.  in the config you have to  put the real pokemon ID, 

Try to make the implement for this weekend.

**Comment by erytcxbv** [comment]
Alright thanks man.

**Comment by hardknoxni69a** [comment]
implemented
