### ISSUE TITLE
pokeballs

### ISSUE THREAD

**Issue by viaduk** [Necrobot-Private/NecroBot#1008]
can somebody help and say what to change in config to farm pokeballs only ? im on 0 pokeballs :<

**Comment by BennettStaley** [comment]
Yep. And i cannot get the bot to gather more.

**Comment by macinmn** [comment]
catch pokemon : false

**Comment by BennettStaley** [comment]
Well yes. That would work. But when you have 0 balls the bot will keep spamming that it has no balls and wont move. It doesn't accept commands either.

**Comment by samuraitruong** [comment]
It may cause by you farm in a low pokestop and with super low speed , the message write out everytime when you encounter pokemon, so if you take 100sec to move to 1 pokestop, you may see that message 20 times, increase your speed and farm in city area

**Comment by viaduk** [comment]
what is safe speed ? i used in necrobot 1 100km per hour and was banned :D, after i use 30km per hour and was banned, now i better use 5 km per hour ? maybe they start to check accounts after 10km per hour. so what is safe speed to dont lost account ?

**Comment by RogueMaster** [comment]
Bot does nothing but say it is out of pokeballs. If I manually set config to not catch pokemon, it will go spin pokestops. Otherwise, it will just not get past not having balls to go get some... it should switch to not catch by itself until it gets more balls...
