### ISSUE TITLE
[Feature Request] "Ultimate Recycle" 

### ISSUE THREAD

**Issue by SLASHLogin** [Necrobot-Private/NecroBot#1009]
Due new berries, evolution items a plenty of people asks for advice how to configure recycle to have balls, so maybe that's will be a good idea to add to config, when 0 pokeballs and no space in inventory then recycle for example 20 berries. Something to stop filling up inventory

**Comment by GrandPaB** [comment]
Would be a really nice one! 
Got the same issue #1010

**Comment by SLASHLogin** [comment]
I were thinking about it and maybe if someone doesn't want this type of recycle so maybe change account.
And maybe telegram message about it, or in WIN window to choose what items recycle if any condition from config isn't achieved.

**Comment by samuraitruong** [comment]
there is percentage config which can be use for this

**Comment by SLASHLogin** [comment]
Oh yea, but it's in my case valid, maybe beacause there's no space for evolution items

**Comment by samuraitruong** [comment]
I don't really understand what you want, since if you said ball = 0 then recycle berries, recycle berries doesn't give you ball, it just give you space

Current config already allow you control max berries, item by type, why just not put berries max 20 items then it solve this problem

**Comment by SLASHLogin** [comment]
My bad, I forget about percentage and all of this, so my first idea in this light is little bit stupid. 
but i didn't notice any line in config for evolution items (like dragon scale etc) so maybe add this in config because it takes some space too

**Comment by samuraitruong** [comment]
No I don't think so, you can use ItemRecycleFilters to set number of Dragon Scale you want to keep

So I closed this issue, if you need reopen just put more comment, thanks
