### ISSUE TITLE
Exception thrown when performing manual switching

### ISSUE THREAD

**Issue by momentosnaps** [Necrobot-Private/NecroBot#1012]
[23:54:59] (ERROR) Exception of type 'PoGo.NecroBot.Logic.Exceptions.ActiveSwitchAccountManualException' was thrown.

**Comment by joe1chen** [comment]
I saw this once before as well.. kind of strange.. but then the next time i tried it, then it worked.  We'll look into this.

**Comment by samuraitruong** [comment]
when it happen again, can you send the full log message, or 20 line before this happen.

**Comment by samuraitruong** [comment]
I thought I fixed it, that error during bot snipe and you switch it.
fix in https://github.com/Necrobot-Private/NecroBot/pull/1024
