### ISSUE TITLE
AutoTransfer Issue

### ISSUE THREAD

**Issue by jokki89** [Necrobot-Private/NecroBot#1014]
Hello guys,

I've the problem that the bot now transfered for the second time ALL of my pokemons...no matter if the pokemons was favored or not. It totally ingnored all conifg rules..

I lost all my best pokemons...so much Snorlax, Lapras, dragonite, All eevee evolutions...everything.. how can this happen...

I'm fully shocked..

Please help.. where is the problem? 

Here my current config;

{
  "ConsoleConfig": {
    "TranslationLanguageCode": "de",
    "StartupWelcomeDelay": false,
    "AmountOfPokemonToDisplayOnStart": 10,
    "DetailedCountsBeforeRecycling": true
  },
  "UpdateConfig": {
    "SchemaVersion": 18,
    "CheckForUpdates": true,
    "AutoUpdate": true
  },
  "WebsocketsConfig": {
    "UseWebsocket": true,
    "WebSocketPort": 14251
  },
  "LocationConfig": {
    "DisableHumanWalking": false,
    "StartFromLastPosition": true,
    "DefaultLatitude": 37.7912015,
    "DefaultLongitude": -122.4376487,
    "WalkingSpeedInKilometerPerHour": 9.0,
    "UseWalkingSpeedVariant": true,
    "WalkingSpeedVariant": 3.0,
    "ShowVariantWalking": false,
    "RandomlyPauseAtStops": true,
    "MaxSpawnLocationOffset": 10,
    "MaxTravelDistanceInMeters": 6000
  },
  "TelegramConfig": {
    "UseTelegramAPI": false,
    "TelegramAPIKey": null,
    "TelegramPassword": null
  },
  "GPXConfig": {
    "UseGpxPathing": false,
    "GpxFile": "GPXPath.GPX"
  },
  "SnipeConfig": {
    "UseSnipeLocationServer": false,
    "SnipeLocationServer": "localhost",
    "SnipeLocationServerPort": 16969,
    "GetSniperInfoFromPokezz": false,
    "GetOnlyVerifiedSniperInfoFromPokezz": true,
    "GetSniperInfoFromPokeSnipers": false,
    "GetSniperInfoFromPokeWatchers": false,
    "GetSniperInfoFromSkiplagged": false,
    "MinPokeballsToSnipe": 20,
    "MinPokeballsWhileSnipe": 0,
    "MinDelayBetweenSnipes": 60000,
    "SnipingScanOffset": 0.005,
    "SnipeAtPokestops": false,
    "SnipeIgnoreUnknownIv": false,
    "UseTransferIvForSnipe": false,
    "SnipePokemonNotInPokedex": false,
    "UseSnipeLimit": true,
    "SnipeRestSeconds": 600,
    "SnipeCountLimit": 39,
    "ActivateMSniper": true,
    "MinIVForAutoSnipe": 100,
    "MinLevelForAutoSnipe": 0,
    "AutosnipeVerifiedOnly": false,
    "DefaultAutoSnipeCandy": 0,
    "SnipePauseOnOutOfBallTime": 5,
    "AutoSnipeMaxDistance": 0.0,
    "AutoSnipeBatchSize": 10
  },
  "HumanWalkSnipeConfig": {
    "Enable": false,
    "DisplayPokemonList": true,
    "MaxDistance": 1500.0,
    "MaxEstimateTime": 900.0,
    "CatchEmAllMinBalls": 50,
    "TryCatchEmAll": true,
    "CatchPokemonWhileWalking": true,
    "SpinWhileWalking": true,
    "AlwaysWalkback": false,
    "SnipingScanOffset": 0.025,
    "WalkbackDistanceLimit": 300.0,
    "IncludeDefaultLocation": true,
    "UseSnipePokemonList": true,
    "MaxSpeedUpSpeed": 60.0,
    "AllowSpeedUp": true,
    "DelayTimeAtDestination": 10000,
    "UsePokeRadar": false,
    "UseSkiplagged": false,
    "UsePokecrew": false,
    "UsePokesnipers": false,
    "UsePokeZZ": false,
    "UsePokeWatcher": false,
    "UseFastPokemap": false,
    "UsePogoLocationFeeder": false,
    "AllowTransferWhileWalking": false
  },
  "DataSharingConfig": {
    "EnableSyncData": false,
    "AutoSnipe": false,
    "DataServiceIdentification": "",
    "SnipeDataAccessKey": "",
    "EnableFailoverDataServers": true,
    "FailoverDataServers": "ws://s1.mypogosnipers.com/socket.io/?EIO=3&transport=websocket;ws://s2.mypogosnipers.com/socket.io/?EIO=3&transport=websocket",
    "DataRecieverURL": "ws://necrosocket.herokuapp.com/socket.io/?EIO=3&transport=websocket"
  },
  "PokeStopConfig": {
    "UsePokeStopLimit": true,
    "PokeStopLimit": 1500,
    "PokeStopLimitMinutes": 1350
  },
  "GymConfig": {
    "NotUsedSkills": [
      {
        "Key": "snorlax",
        "Value": "hyperBeam"
      },
      {
        "Key": "dragonite",
        "Value": "hyperBeam"
      },
      {
        "Key": "lapras",
        "Value": "blizzard"
      },
      {
        "Key": "cloyster",
        "Value": "blizzard"
      },
      {
        "Key": "flareon",
        "Value": "fireBlast"
      }
    ],
    "Enable": false,
    "PrioritizeGymOverPokestop": true,
    "MaxDistance": 500.0,
    "DefaultTeam": "Yellow",
    "MaxCPToDeploy": 1800,
    "MaxLevelToDeploy": 16,
    "VisitTimeout": 60,
    "UseRandomPokemon": false,
    "NumberOfTopPokemonToBeExcluded": 10,
    "CollectCoinAfterDeployed": 1,
    "EnableAttackGym": false,
    "MaxGymLevelToAttack": 3,
    "MaxDefendersToAttack": 3,
    "HealDefendersBeforeApplyToGym": true,
    "DontAttackAfterCoinsLimitReached": true,
    "EnableGymTraining": true,
    "TrainGymWhenMissingMaxPoints": 1000,
    "MaxGymLvlToTrain": 4,
    "TrainAlreadyDefendedGym": true,
    "MinCpToUseInAttack": 1000,
    "ButNotLessThanDefenderPercent": 0.75,
    "UsePokemonToAttackOnlyByCp": true,
    "ExcludeForGyms": [
      "kangaskhan",
      "tauros",
      "mrMime",
      "farfetchd"
    ],
    "DontUseDodge": false,
    "MinRevivePotions": 5,
    "PrioritizeGymWithFreeSlot": true,
    "SaveMaxRevives": true
  },
  "PokemonConfig": {
    "CatchPokemon": true,
    "DelayBetweenPokemonCatch": 1000,
    "UseCatchLimit": false,
    "CatchPokemonLimit": 1000,
    "CatchPokemonLimitMinutes": 1350,
    "UseIncenseConstantly": false,
    "UseEggIncubators": true,
    "UseLimitedEggIncubators": true,
    "UseLuckyEggConstantly": false,
    "UseLuckyEggsMinPokemonAmount": 30,
    "UseLuckyEggsWhileEvolving": false,
    "TransferWeakPokemon": true,
    "TransferDuplicatePokemon": true,
    "TransferDuplicatePokemonOnCapture": true,
    "RenamePokemon": true,
    "RenameOnlyAboveIv": true,
    "RenameTemplate": "{Name}_{IV}_Lv{Level}",
    "FavoriteMinIvPercentage": 80.0,
    "AutoFavoritePokemon": true,
    "MaxPokeballsPerPokemon": 15,
    "UseGreatBallAboveCp": 350,
    "UseUltraBallAboveCp": 800,
    "UseMasterBallAboveCp": 1500,
    "UseGreatBallAboveIv": 70.0,
    "UseUltraBallAboveIv": 80.0,
    "UseGreatBallBelowCatchProbability": 0.5,
    "UseUltraBallBelowCatchProbability": 0.3,
    "UseMasterBallBelowCatchProbability": 0.05,
    "AutomaticallyLevelUpPokemon": false,
    "OnlyUpgradeFavorites": false,
    "UseLevelUpList": true,
    "AmountOfTimesToUpgradeLoop": 5,
    "GetMinStarDustForLevelUp": 5000,
    "LevelUpByCPorIv": "iv",
    "UpgradePokemonCpMinimum": 1000.0,
    "UpgradePokemonIvMinimum": 95.0,
    "UpgradePokemonMinimumStatsOperator": "and",
    "EvolveAboveIvValue": 95.0,
    "EvolveAllPokemonAboveIv": false,
    "EvolveAllPokemonWithEnoughCandy": false,
    "EvolveKeptPokemonsAtStorageUsagePercentage": 90.0,
    "EvolveKeptPokemonIfBagHasOverThisManyPokemon": 120,
    "KeepPokemonsThatCanEvolve": true,
    "KeepMinCp": 400,
    "KeepMinIvPercentage": 80.0,
    "KeepMinLvl": 10,
    "KeepMinOperator": "or",
    "UseKeepMinLvl": false,
    "PrioritizeIvOverCp": true,
    "KeepMinDuplicatePokemon": 1,
    "UsePokemonToNotCatchFilter": true,
    "UsePokemonSniperFilterOnly": false,
    "DumpPokemonStats": false,
    "DelayBetweenPokemonUpgrade": 10000,
    "OutOfBallCatchBlockTime": 5,
    "PokeballToKeepForSnipe": 50,
    "UseBulkTransferPokemon": true,
    "BulkTransferStogareBuffer": 10,
    "BulkTransferSize": 100,
    "UseBallOperator": "or",
    "FavoriteMinCp": 0.0,
    "DefaultBuddyPokemon": "",
    "FavoriteMinLevel": 0,
    "FavoriteOperator": "and",
    "RenamePokemonRespectTransferRule": false,
    "UpgradePokemonLvlMinimum": 30.0,
    "EvolveOperator": "and",
    "EvolveFavoritedOnly": true,
    "EvolveMinIV": 100.0,
    "EvolveMinCP": 2000.0,
    "EvolveMinLevel": 2000.0
  },
  "RecycleConfig": {
    "VerboseRecycling": true,
    "RecycleInventoryAtUsagePercentage": 95.0,
    "RandomizeRecycle": false,
    "RandomRecycleValue": 3,
    "TotalAmountOfPokeballsToKeep": 300,
    "TotalAmountOfPotionsToKeep": 50,
    "TotalAmountOfRevivesToKeep": 50,
    "TotalAmountOfBerriesToKeep": 50,
    "UseRecyclePercentsInsteadOfTotals": false,
    "PercentOfInventoryPokeballsToKeep": 35,
    "PercentOfInventoryPotionsToKeep": 35,
    "PercentOfInventoryRevivesToKeep": 20,
    "PercentOfInventoryBerriesToKeep": 10
  },
  "CustomCatchConfig": {
    "EnableHumanizedThrows": true,
    "EnableMissedThrows": true,
    "ThrowMissPercentage": 5,
    "NiceThrowChance": 10,
    "GreatThrowChance": 30,
    "ExcellentThrowChance": 40,
    "CurveThrowChance": 90,
    "ForceGreatThrowOverIv": 60.0,
    "ForceExcellentThrowOverIv": 80.0,
    "ForceGreatThrowOverCp": 500,
    "ForceExcellentThrowOverCp": 750,
    "UseTransferFilterToCatch": false
  },
  "PlayerConfig": {
    "DelayBetweenPlayerActions": 4000,
    "EvolveActionDelay": 20000,
    "TransferActionDelay": 5000,
    "RecycleActionDelay": 1000,
    "RenamePokemonActionDelay": 2000,
    "UseNearActionRandom": true,
    "RandomizeSettingsByPercent": 5,
    "AutoFinishTutorial": false
  },
  "SoftBanConfig": {
    "FastSoftBanBypass": true,
    "ByPassSpinCount": 45
  },
  "GoogleWalkConfig": {
    "UseGoogleWalk": false,
    "DefaultStepLength": 1.3,
    "GoogleHeuristic": "walking",
    "GoogleAPIKey": null,
    "Cache": true,
    "GoogleElevationAPIKey": null
  },
  "YoursWalkConfig": {
    "UseYoursWalk": false,
    "YoursWalkHeuristic": "bicycle"
  },
  "MapzenWalkConfig": {
    "UseMapzenWalk": false,
    "MapzenTurnByTurnApiKey": null,
    "MapzenWalkHeuristic": "bicycle",
    "MapzenElevationApiKey": null
  },
  "ItemRecycleFilter": [
    {
      "Key": "itemUnknown",
      "Value": 0
    },
    {
      "Key": "itemLuckyEgg",
      "Value": 200
    },
    {
      "Key": "itemIncenseOrdinary",
      "Value": 100
    },
    {
      "Key": "itemIncenseSpicy",
      "Value": 100
    },
    {
      "Key": "itemIncenseCool",
      "Value": 100
    },
    {
      "Key": "itemIncenseFloral",
      "Value": 100
    },
    {
      "Key": "itemTroyDisk",
      "Value": 100
    },
    {
      "Key": "itemXAttack",
      "Value": 100
    },
    {
      "Key": "itemXDefense",
      "Value": 100
    },
    {
      "Key": "itemXMiracle",
      "Value": 100
    },
    {
      "Key": "itemSpecialCamera",
      "Value": 100
    },
    {
      "Key": "itemIncubatorBasicUnlimited",
      "Value": 100
    },
    {
      "Key": "itemIncubatorBasic",
      "Value": 100
    },
    {
      "Key": "itemPokemonStorageUpgrade",
      "Value": 100
    },
    {
      "Key": "itemItemStorageUpgrade",
      "Value": 100
    },
    {
      "Key": "itemPokeBall",
      "Value": 50
    },
    {
      "Key": "itemRevive",
      "Value": 10
    },
    {
      "Key": "itemPotion",
      "Value": 10
    },
    {
      "Key": "itemHyperPotion",
      "Value": 10
    },
    {
      "Key": "itemGreatBall",
      "Value": 100
    },
    {
      "Key": "itemDragonScale",
      "Value": 100
    },
    {
      "Key": "itemUpGrade",
      "Value": 100
    },
    {
      "Key": "itemKingsRock",
      "Value": 100
    },
    {
      "Key": "itemSunStone",
      "Value": 100
    },
    {
      "Key": "itemMetalCoat",
      "Value": 100
    }
  ],
  "PokemonsNotToTransfer": [
    "venusaur",
    "charizard",
    "blastoise",
    "chansey",
    "gyarados",
    "snorlax",
    "articuno",
    "zapdos",
    "moltres",
    "dragonite",
    "mewtwo",
    "mew",
    "lapras",
    "vaporeon",
    "eevee",
    "jolteon",
    "flareon",
    "aerodactyl",
    "pichu",
    "cleffa",
    "igglybuff",
    "togepi",
    "elekid",
    "magby"
  ],
  "PokemonsToEvolve": [
    "caterpie",
    "weedle",
    "pidgey",
    "rattata"
  ],
  "PokemonsToLevelUp": [
    "venusaur",
    "charizard",
    "blastoise",
    "clefable",
    "muk",
    "chansey",
    "gyarados",
    "ditto",
    "snorlax",
    "articuno",
    "zapdos",
    "moltres",
    "dragonite",
    "mewtwo",
    "mew"
  ],

**Comment by garette1** [comment]
set transferweakpokemon false maybe this will help you

**Comment by Lord-Haji** [comment]
@jokki89 try hastebin.com for pasting stuff

**Comment by jokki89** [comment]
@garette1  but transferweakpokemon have to be activated, because otherways it don't transfere anything. or not?

**Comment by garette1** [comment]
@jokki89 no.duplicatepokemon settings is enough.already im using this settings.

**Comment by hardknoxni69a** [comment]
You need to include your configuration especially for transfer settings or we don't know

**Comment by hardknoxni69a** [comment]
settting filters like this will only keep a pikachu if its 100iv and level 25 if i have keep duplicate 1 if would keep 1 of the highest iv or cp depending on your preference even if it doesnt meet requirement
  "Pikachu": {
      "KeepMinCp": 0,
      "KeepMinIvPercentage": 100.0,
      "KeepMinLvl": 25,
      "UseKeepMinLvl": true,
      "KeepMinOperator": "and",
      "KeepMinDuplicatePokemon": 0,
      "Moves": [
        []
      ],
      "DeprecatedMoves": null,
      "MovesOperator": "and",
      "CatchOnlyPokemonMeetTransferCriteria": false,
      "AffectToPokemons": null
