### ISSUE TITLE
use berry issue

### ISSUE THREAD

**Issue by garette1** [Necrobot-Private/NecroBot#1015]
i cant control using berries.i set UseIfExceedBagRecycleFilter false, now never use berries.cant adapt IV,CP or level

**Comment by hardknoxni69a** [comment]
U have to set accordingly  by iv or cp  level etc which pokemon u want to use berries u have to turn them on and should be good take a little time to review config we ask for the configuration file because without it we can't help.much

**Comment by samuraitruong** [comment]
it because you haven't setup IV< CP properly

**Comment by garette1** [comment]
can you give me a suggestion? i cant get it? @samuraitruong @hardknoxni69a 

"ItemUseFilters": {
    "ItemNanabBerry": {
      "UseItemMinIV": 50,
      "UseItemMinLevel": 20,
      "UseItemMinCP": 500,
      "Operator": "and",
      "CatchProbability": 0.3,
      "Pokemons": [
        "abra",
        "dragonite",
        "venusaur",
        "blastoise",
        "charizard"
      ],
      "MaxItemsUsePerPokemon": 20,
      "UseIfExceedBagRecycleFilter": true
    },
    "ItemRazzBerry": {
      "UseItemMinIV": 60,
      "UseItemMinLevel": 20,
      "UseItemMinCP": 500,
      "Operator": "and",
      "CatchProbability": 0.3,
      "Pokemons": [],
      "MaxItemsUsePerPokemon": 3,
      "UseIfExceedBagRecycleFilter": true
    },
    "ItemPinapBerry": {
      "UseItemMinIV": 0,
      "UseItemMinLevel": 0,
      "UseItemMinCP": 0,
      "Operator": "or",
      "CatchProbability": 1.0,
      "Pokemons": [
        "lapras",
        "snorlax",
        "chansey",
        "dratini",
        "porygon",
        "porygon2"
      ],
      "MaxItemsUsePerPokemon": 10,
      "UseIfExceedBagRecycleFilter": true

**Comment by RoskamiesX** [comment]
`  "ItemUseFilters": {
    "ItemNanabBerry": {
      "UseItemMinIV": 100,
      "UseItemMinLevel": 45,
      "UseItemMinCP": 5000,
      "Operator": "and",
      "CatchProbability": 0.01,
      "Pokemons": [
        "ADD MORE POKEMONS HERE",
        "ADD MORE POKEMONS HERE"
       ],
      "MaxItemsUsePerPokemon": 100,
      "UseIfExceedBagRecycleFilter": true
    },
    "ItemRazzBerry": {
      "UseItemMinIV": 70,
      "UseItemMinLevel": 0,
      "UseItemMinCP": 250,
      "Operator": "and",
      "CatchProbability": 0.3,
      "Pokemons": [
        "ADD MORE POKEMONS HERE",
        "ADD MORE POKEMONS HERE"
      ],
      "MaxItemsUsePerPokemon": 10,
      "UseIfExceedBagRecycleFilter": true
    },
    "ItemPinapBerry": {
      "UseItemMinIV": 0,
      "UseItemMinLevel": 0,
      "UseItemMinCP": 0,
      "Operator": "or",
      "CatchProbability": 0.05,
      "Pokemons": [
        "ADD MORE POKEMONS HERE",
        "ADD MORE POKEMONS HERE"
      ],
      "MaxItemsUsePerPokemon": 2,
      "UseIfExceedBagRecycleFilter": true
    }
  },`

Something like this and remember to add pokemons
