### ISSUE TITLE
Necro Bot WIn - still not working

### ISSUE THREAD

**Issue by Koteczek123** [Necrobot-Private/NecroBot#1016]
Since a week I am not able to get the win working :( I start it wheni put the initial data the consol opens but the Win closes and never ever wants to open. I tried reinstall i downloaded new version I copied working config... and still nothing .

On second computer works without an issue. Is there a hidden file I must remove from the comp to make it work again?

**Comment by Koteczek123** [comment]
Found the issue - Windows defender is blocking this program

**Comment by hardknoxni69a** [comment]
Sorry we didn't get back sooner thankfully it was a simple click fix
