### ISSUE TITLE
Bot not farming pokestops

### ISSUE THREAD

**Issue by twincitygamer** [Necrobot-Private/NecroBot#1017]
All of thee sudden I'am not collecting pokestops. this is what my console looks like
https://gyazo.com/48c9445f708be56eb7b0347e264c1ae6

**Comment by hardknoxni69a** [comment]
send an actual log please not much to see wtih that

**Comment by garette1** [comment]
already travelling pokesstop.wait a 2 minute.

**Comment by Patch019** [comment]
I'm having this issue too, it just says it's travelling to a pokestop and for example it gave me nine seconds till it arrived and hasn't arrived for five minutes. Any update on this?

**Comment by hardknoxni69a** [comment]
i take it this has been resolved let us know if you have any qquestions remember always double check config to make sure it works out and allows u to get stops like patch side if you have no balls and dont allow time to build more balls then youll be stuck in a looop
