### ISSUE TITLE
Scyther Evolution

### ISSUE THREAD

**Issue by dougrosa** [Necrobot-Private/NecroBot#1021]
Scyther Evolution to Scizor is not working.

**Comment by samuraitruong** [comment]
more specific?

**Comment by dougrosa** [comment]
The bot check if your have candies OR the evolution item (metal coat). It should check if you have both em. The button to evolve was enabled and I hadn't the candies to evolve, just the metal coat.

**Comment by samuraitruong** [comment]
you mean button enable when you don't have required item?

I not sure what is the issue is, but it should be fixed in - https://github.com/Necrobot-Private/NecroBot/pull/1134
