### ISSUE TITLE
Mapquest Elevation error, My observation

### ISSUE THREAD

**Issue by LobsterX** [Necrobot-Private/NecroBot#103]
**The error:
who else is getting this?
[13:42:42] (ATTENTION) MapQuest Elevation response not reliable: -32768**

I noticed this pops up when i'm over water bodies when elevations are at 0 value.

1)bot went 1/2 way cross a bridge, error pops up[ same spot. am able to replicate]
2) bot walked along the coast into a pier that stretches out into the sea, error pops out [same, able to replicate when bot moved to the same spot where error pops up]

I think it's not google's elevation API at fault.

I've enabled both Google Maps API and Google Elevation API and checked they are all enable and working well.

is there somewhere in necrobot's coding that is bugged?

**Comment by wilsondgonzales** [comment]
i have experienced it intermittently where the bot works fine then that prompt pops up and stops the bot. At that point I wonder if something's wrong with my api setup but no everything is working fine and i haven't reached even a hundred on my quota

**Comment by iwean** [comment]
@LobsterX 
Is there api key on your config.json file? Or just null?

**Comment by LobsterX** [comment]
@iwean Google API key is there. regenerated a new one just to make sure it wasn't cos it's an old 1week key.

I strongly believe somewehere the 0 elevation is causing the error to pop up [for me, not sure about other people's error ovbservations]

@wilsondgonzales i always set my start point to be the same everytime the error pops up and i restart the bot after deleting lastpos.ini. error appears at exactly same spot on the map, on top of a glass helix bridge in the central business district in my country.

**Comment by wilsondgonzales** [comment]
After a few more tests, I can confirm that mapquest prompt happens near bodies of water like @LobsterX says.

**Comment by jjskuld** [comment]
With the new release 0.9.8.9, it will never cause the bot to die now.  When you get an invalid elevation, it will fallback to the next strategy and blacklist the existing strategy for 1 hr.  The last fallback is the random provider, which just generates a random elevation for you.

**Comment by jjskuld** [comment]
Also in 0.9.8.9, it is highly suggested to use the new Mapzen elevation api. You need to get an API key from Mapzen.  This service is fast, reliable, and has no api limits.

**Comment by wilsondgonzales** [comment]
@jjskuld does the mapzen key get placed under google api key instead?

**Comment by kevinronu** [comment]
How to apply mapzen elevation api key?

**Comment by jjskuld** [comment]
The mapzen key gets put under its own section MapzenWalkConfig I believe is
the new section.
