### ISSUE TITLE
Gym strategy idea

### ISSUE THREAD

**Issue by andeomontenegro** [Necrobot-Private/NecroBot#1032]
What if make defenders deploy with Fav + mincp+maxcp criteria?
Example: we have Blissey 2000cp and Dragonite 3000cp
Bot trying to deploy random in mincp option
So we cant deploy Blissey because many bots in multibot pack have different cp Blisseys

through GUI we can easy set favs, so if bot have favs in min-max cp option it can deploy only best defenders of my choice

What do u  think?

**Comment by ziomber** [comment]
Its in progress, I've done defenders and now preparing attackers

**Comment by andeomontenegro** [comment]
great!!!

**Comment by hardknoxni69a** [comment]
implemented
