### ISSUE TITLE
can not evolve pokemon

### ISSUE THREAD

**Issue by garette1** [Necrobot-Private/NecroBot#1034]
cant evolve pokemon with electron GUI.transfer and upgrade is ok but evolve dont do anything

**Comment by hardknoxni69a** [comment]
please make sure you are doiwnloading from our submodule and loading index.html the all the buttons work just fine bot should be port 14251 and gui 14252 and should be goldenbut ultimately elevtron isnt the main GUI check out necro.win and you will have no issues
