### ISSUE TITLE
Could you plz share another way to download necrobot instead of github?

### ISSUE THREAD

**Issue by 234534534** [Necrobot-Private/NecroBot#1035]
Hey guys,

I tried to download necrobot from git hub, but download speed is freakingly slow, It about takes 3hours,
and after 2hours download automatically denied because of 'Request expired'. 

Plz,, Plz could you give me another link for necrobot???

**Comment by jeafke** [comment]
It's already easy for "mainstream" users to obtain and use as such.

[My opinion]Having compiled binaries available isn't something I personally support anyway.[/My opinion]

**Comment by hardknoxni69a** [comment]
im sorry bud but it must be your internet it takes about 20-30 secs to download the largest file
