### ISSUE TITLE
Safe speed in km?

### ISSUE THREAD

**Issue by viaduk** [Necrobot-Private/NecroBot#1037]
what is safe speed ? i used in necrobot 1 100km per hour and was banned :D, after i use 30km per hour and was banned, now i better use 5 km per hour ? maybe they start to check accounts after 10km per hour. so what is safe speed to dont lost account ?

**Comment by garette1** [comment]
you are a human bro :DD you must set 4-5 km per hour

**Comment by samuraitruong** [comment]
i would say as long as bot still work, niantic have no reason to complain you put speed - bus speed or train speed  :D
