### ISSUE TITLE
"MinIVForAutoSnipe" setting without effect

### ISSUE THREAD

**Issue by Chris988** [Necrobot-Private/NecroBot#1038]
After updating yesterday the bot simply ignores the MinIVForAutoSnipe setting. Even if i set it to 10 the autosniper doesn't add a single Pokemon to my AutoSnipingList, with AutoSniper turned on of course.

**Comment by samuraitruong** [comment]
fixed - https://github.com/Necrobot-Private/NecroBot/pull/1039
