### ISSUE TITLE
0.9.8.8 hangs after logging in

### ISSUE THREAD

**Issue by vfuyong** [Necrobot-Private/NecroBot#104]
I experienced the same issue with 0.9.8.7, and tried 0.9.8.8 again the bot still hangs after logging in. (to be more precise, it hangs right after displaying pokedex stats e.g. seen over captured). I am pretty sure config has no issue. 

Anyone experienced the same issue?

**Comment by Pokego0108** [comment]
Yes, same here.
Stopped at "Amount of Pokemon Seen: xxx/151, Amount of Pokemon Caught: xxx/151" every time without anyerror

**Comment by Pokego0108** [comment]
and my issue start from 0.9.8.7 too

**Comment by VBQL** [comment]
Have you tried pressing [Enter] after this shows up? You may have welcome startup delay enabled.

**Comment by Pokego0108** [comment]
Thanks for advice. I tried press [Enter] and checked startup delay is set by "false", still not work.

**Comment by VBQL** [comment]
I will then suggest you to turn Near Random Action on and wait a while after start. It might be your huge player delay, I am not exactly sure. Please tell me the results.

**Comment by bulubebek** [comment]
did you use GUI? I have same problem, and it works fine after I disable websocket.

**Comment by Pokego0108** [comment]
It's weird.  I keep try and error changing the settings, found out

"PlayerConfig": {
"DelayBetweenPlayerActions": 8998,
"EvolveActionDelay": 24998,
"TransferActionDelay": 5998,
"RecycleActionDelay": 4998,
"RenamePokemonActionDelay": 14998,
"UseNearActionRandom": false,
"AutoCompleteTutorial": false,
"DesiredNickname": "Nickname",
"DesiredGender": "Male",
"DesiredStarter": "Charmander"
},= Not Work

 "PlayerConfig": {
    "DelayBetweenPlayerActions": 9000,
    "EvolveActionDelay": 25000,
    "TransferActionDelay": 6000,
    "RecycleActionDelay": 5000,
    "RenamePokemonActionDelay": 15000,
    "UseNearActionRandom": true,
    "AutoCompleteTutorial": false,
    "DesiredNickname": "Nickname",
    "DesiredGender": "Male",
    "DesiredStarter": "Charmander"
  },=Work

 "HumanWalkSnipeConfig": {
    "Enable": true,
    "DisplayPokemonList": true,
    "MaxDistance": 1500.0,
    "MaxEstimateTime": 900.0,
    "CatchEmAllMinBalls": 50,
    "TryCatchEmAll": true,
    "CatchPokemonWhileWalking": true,
    "SpinWhileWalking": true,
    "AlwaysWalkback": false,
    "SnipingScanOffset": 0.025,
    "WalkbackDistanceLimit": 300.0,
    "IncludeDefaultLocation": false,
    "UseSnipePokemonList": false,
    "MaxSpeedUpSpeed": 30.0,
    "AllowSpeedUp": true,
    "DelayTimeAtDestination": 10000,
    "UsePokeRadar": true,
    "UseSkiplagged": true,
    "UsePokecrew": true,
    "UsePokesnipers": true,
    "UsePokeZZ": true,
    "UsePokeWatcher": true,
    "UseFastPokemap": true,
    "UsePogoLocationFeeder": false
  },=Work
But when I enable "UseSnipePokemonList", it not working again.

Seem many option may not cause Program crash or Error after change, but it may cause the bot not working properly.

**Comment by Silph-Road** [comment]
I sometimes run into a similar problem, try turning off autorename = false

Report back and test if it works even with other settings changed to either example you have mentioned.

**Comment by Pokego0108** [comment]
IC, hope the developer will fix it in next patch.

**Comment by Silph-Road** [comment]
Yeah we need to isolate the issue first cuz it happens only sometimes for me turning rename off seems to work.

**Comment by vfuyong** [comment]
Look for infinite loop caused by rename or state machine

**Comment by vfuyong** [comment]
@Silph-Road This is still a problem, do you have time to fix it? Thanks.

**Comment by vfuyong** [comment]
@jjskuld Can you please fix this?

**Comment by Silph-Road** [comment]
https://github.com/Necrobot-Private/NecroBot/issues/194
