### ISSUE TITLE
Politoed evolution

### ISSUE THREAD

**Issue by dougrosa** [Necrobot-Private/NecroBot#1041]
When you click to evolve Poliwhirl to Politoed, no matter if you have the candies and the evolution item, Politoed button to evolve will remain "disabled". But, if you click at the button and restart the bot, the evolution works. 

Can you check? The button to evolve to Politoed should be enabled by default, if you meet the requirements.

**Comment by dougrosa** [comment]
The same happens to Slow King.

Tried to evolve Gloom into Bellossom, evolve not working.

**Comment by samuraitruong** [comment]
should fix in - https://github.com/Necrobot-Private/NecroBot/pull/1134
