### ISSUE TITLE
[BUG REPORT] Sniper (Not in Dex tab)

### ISSUE THREAD

**Issue by Lord-Haji** [Necrobot-Private/NecroBot#1044]
## Not in Dex Tab in sniper is broken !
Although i get to see tons of Pokemon in the Not In Dex Tab After Sniping them and checking the EXP i got 
I realize that i already have them lol.

**Comment by samuraitruong** [comment]
this bug comeback again.

**Comment by hardknoxni69a** [comment]
known issue thank you
