### ISSUE TITLE
i wanna keep from sniping out of canada with auto snipe.

### ISSUE THREAD

**Issue by RicoEdg** [Necrobot-Private/NecroBot#1045]
I wanna keep my bot from sniping out of Canada with autosnipe

**Comment by hardknoxni69a** [comment]
if your sniping at all its all the same may i ask why

**Comment by RicoEdg** [comment]
cause I would like to have my Pokemon to say caught in Canada cause that's where I'm from just to be safe

**Comment by hardknoxni69a** [comment]
Oh u want to stay in Canada got u know it's a big country though is it for
friend purposes or niantic I don't think u can specify what country for
autosnipe but u can monitor your manualsnipes and it'll stay local

**Comment by RicoEdg** [comment]
ok, i'll just use auto snipe to build up candies and stardust and manual for the pokemon I wanna keep.

**Comment by hardknoxni69a** [comment]
u can also check out the autosnipe max distance and if theres something within your country distance it will snipe
