### ISSUE TITLE
[Request] Wiki telegram 

### ISSUE THREAD

**Issue by SLASHLogin** [Necrobot-Private/NecroBot#1046]
During configuration telegram messages I losed myself so I went to the wiki. There I found only in config description link to old NecroBot wiki and maybe someone have still some text from this wiki or just need to do new because this is good feature and I want use it maybe some other people to.

**Comment by samuraitruong** [comment]
http://necrobot2.com/config.json/2017/01/11/telegram-service-configuration-Copy/
hope this is useful for u

**Comment by hardknoxni69a** [comment]
while creating new bot you must name it NecroBot then username can be whatever
