### ISSUE TITLE
[FEATURE SUGGESTION] Show Pokémon Genders

### ISSUE THREAD

**Issue by Lord-Haji** [Necrobot-Private/NecroBot#1050]
Display of Pokémon Genders in Pokémon Tab and Map Will be a thing

**Comment by hardknoxni69a** [comment]
good idea thanks

**Comment by cswxin** [comment]
what's the differents between Pokémon Genders?

**Comment by Lord-Haji** [comment]
@cswxin wut do u actually mean ?

**Comment by hardknoxni69a** [comment]
In future will be breeding so im.guessing he wants to save 1 of each

**Comment by samuraitruong** [comment]
added sex in pokemon list
