### ISSUE TITLE
Add exclusion for Gym battles

### ISSUE THREAD

**Issue by Danny-0815** [Necrobot-Private/NecroBot#1052]
I would like to suggest a feature that allows me to exclude specific Pokémon for attacking a gym.
Currently Blissey is one of my highest, but extremely ineffective when it comes to attacking a gym. So I would like to exclude it.

Another thing is, that my Tyranitar is never chosen when attacking a gym. I think, it is because I set it as a buddy Pokémon. So this needs to be fixed as well...

**Comment by ziomber** [comment]
I have done it partially. When i'll finish you will be able to define attacking team and defenders

**Comment by hardknoxni69a** [comment]
implemented
