### ISSUE TITLE
Telegram notifications

### ISSUE THREAD

**Issue by redking974** [Necrobot-Private/NecroBot#1054]
### Expected Behavior:
In wiki here : http://necrobot2.com/config.json/2017/01/11/telegram-service-configuration-Copy/
It's written that we can receive notifications into Telegram, but after configuration (and confirmation into logs that my bot is connected) I receive 0 notification.
It would be great if I could receive notification like starting, switchs, ...

### Actual Behavior:
No notification

### Your config.json:
```
  "TelegramConfig": {
    "UseTelegramAPI": true,
    "TelegramAPIKey": "4565461:xXxDSxxsddsdxxx",
    "TelegramPassword": null
  },
```

### (OPTIONAL) Your Log:
```
[16:24:46] () Configuration is up-to-date. Schema version: 18
[16:24:46] () Validating config.json...
[16:24:46] () Auth Configuration is up-to-date. Schema version: 18
[16:24:46] () Validating auth.json...
[16:24:48] (MÀJ) NecroBot v1.0.0.121 est à jour.
[16:24:48] (INFO) Connexion via Google
[16:24:48] (INFO) Using TelegramAPI with xxxBot
```

Version: 121
Windows Version: 10
What is affected (catch, transfer, favorite, GPX, evolve, recycle, snipe, human walk snipe, pokestops, powerup/levelup, other): notifications

**Comment by samuraitruong** [comment]
there is a notificationconfig session, you have to enable it

**Comment by redking974** [comment]
```
  "NotificationConfig": {
    "EnablePushBulletNotification": false,
    "EnableEmailNotification": false,
    "PushBulletApiKey": "",
    "GmailUsername": "",
    "GmailPassword": "",
    "Recipients": ""
  },
```

It works with all false into NotificationConfig session.
In fact, we need to go into the bot and enter /start manually (no notifications until this procedure)

Regards
