### ISSUE TITLE
We Need The transfer confirmation for regular button too

### ISSUE THREAD

**Issue by hardknoxni69a** [Necrobot-Private/NecroBot#1058]
when mass transfer you get are you sure you want to transfer we need that button on regular transfer button as well just transferred a 100iv lvl 30poliwrath cuz list moved at last second

**Comment by samuraitruong** [comment]
https://github.com/Necrobot-Private/NecroBot/pull/1134

**Comment by macinmn** [comment]
a short term solution for you:  if you don't release the mouse button, you can quickly visually verify you have clicked on the right one.  if you didn't, you can move the mouse away from the transfer button while still holding down the mouse, then release it when you're clear from the area and it won't select.   same for sniping, etc

**Comment by macinmn** [comment]
also, if you work your way from bottom to top, instead of top to bottom, everything will stay where it started

**Comment by macinmn** [comment]
and @samuraitruong, if you could make it an option maybe, because personally I like to be able to click and keep clicking additional i want to get rid of, and don't want to confirm each one.  thanks!

**Comment by hardknoxni69a** [comment]
Well the basic button is to get rid of just one Pokemon when ur clicking
more and more Pokemon that's what the transfer all button is for u should
be checking the boxes and then mass transfer sounds better for you

**Comment by macinmn** [comment]
@hardknoxni69a    nor sure you understood what I was saying.  I don't see anything wrong with how it is already nor do I need any changes is what I'm implying, so having an option to turn confirmation on/off would be better it can stay the way it is for most people.  while confirm is good for large group, a button for individuals is overkill when my workaround mentioned above is perfectly feasible.  right now if I just want to transfer pokemons 4 6 and 7 for instance, it's only 3 clicks, and doesn't need to be more complicated than that.  grouping, having to hold CTRL for one of them, then navigating to the transfer all, then confirming, isn't efficient.  and neither is having to click twice for each one.
