### ISSUE TITLE
EvolveFilter Is Not Linked To Transfer Code

### ISSUE THREAD

**Issue by hardknoxni69a** [Necrobot-Private/NecroBot#1060]
Bot used to transfer all pokemon that dont meet your keep requirements. If you have evolutions on for a pokemon it will keep 1 that doesnt meet your requirements just to evolve it then it will transfer it but in mean time it will transfer all others. With new evolve filters you can set bot to only evolve over level 20 so it should evolve pokemon over lvl 20 which it does AMAZING and transfer all pokemon under level 20 DOES NOT WORK. So bot follows rules and only evolves level 20 but still saves pokemon under lvl 20 and does nothing at all with them doesnt transfer or evolve

**Comment by hardknoxni69a** [comment]
"Eevee": {
      "KeepMinCp": 0,
      "KeepMinIvPercentage": 100.0,
      "KeepMinLvl": 20,
      "UseKeepMinLvl": true,
      "KeepMinOperator": "and",
      "KeepMinDuplicatePokemon": 0,
      "Moves": [
        []
      ],
      "DeprecatedMoves": null,
      "MovesOperator": "and",
      "CatchOnlyPokemonMeetTransferCriteria": false,
      "AffectToPokemons": null
    },

**Comment by hardknoxni69a** [comment]
"Eevee": {
      "MinIV": 100.0,
      "MinLV": 20.0,
      "MinCP": 0.0,
      "Moves": [],
      "Operator": "and",
      "EvolveTo": "",
      "FavoritedOnly": false,
      "AffectToPokemons": null
    },

**Comment by hardknoxni69a** [comment]
but bot saves eevee lvl 2 10 iv very strange pretty sure the transfer pokemon isnt linked to the new evolve list correctly yet

**Comment by jjskuld** [comment]
Pull #1075 will fix this bug. Transfer logic now properly accounts for PokemonEvolveFilter.

**Comment by hardknoxni69a** [comment]
Sweet jj thanks a ton cleaned up most of the issues so be easier for you
guys to see what actually needs work keep it up
