### ISSUE TITLE
Evolve doesn't work

### ISSUE THREAD

**Issue by FureszOszkar** [Necrobot-Private/NecroBot#1061]
I have 8 swinub and 660 candies...

[22:46:58] (ATTENTION) Pokemon Inventory is full, transferring Pokemon...
[22:46:58] (EVOLVED) Potential Evolutions: 1

Config:
"PokemonConfig": {
    "CatchPokemon": true,
    "DelayBetweenPokemonCatch": 2000,
    "UseCatchLimit": true,
    "CatchPokemonLimit": 700,
    "CatchPokemonLimitMinutes": 1350,
    "UseIncenseConstantly": false,
    "UseEggIncubators": true,
    "UseLimitedEggIncubators": true,
    "UseLuckyEggConstantly": false,
    "UseLuckyEggsMinPokemonAmount": 30,
    "UseLuckyEggsWhileEvolving": false,
    "TransferWeakPokemon": false,
    "TransferDuplicatePokemon": true,
    "TransferDuplicatePokemonOnCapture": true,
    "RenamePokemon": false,
    "RenameOnlyAboveIv": false,
    "RenameTemplate": "{Name}_{IV}_Lv{Level}",
    "FavoriteMinIvPercentage": 100.0,
    "AutoFavoritePokemon": true,
    "MaxPokeballsPerPokemon": 6,
    "UseGreatBallAboveCp": 1000,
    "UseUltraBallAboveCp": 1250,
    "UseMasterBallAboveCp": 1500,
    "UseGreatBallAboveIv": 85.0,
    "UseUltraBallAboveIv": 95.0,
    "UseGreatBallBelowCatchProbability": 0.2,
    "UseUltraBallBelowCatchProbability": 0.1,
    "UseMasterBallBelowCatchProbability": 0.05,
    "AutomaticallyLevelUpPokemon": false,
    "OnlyUpgradeFavorites": true,
    "UseLevelUpList": true,
    "AmountOfTimesToUpgradeLoop": 5,
    "GetMinStarDustForLevelUp": 5000,
    "LevelUpByCPorIv": "iv",
    "UpgradePokemonCpMinimum": 1000.0,
    "UpgradePokemonIvMinimum": 95.0,
    "UpgradePokemonMinimumStatsOperator": "and",
    "EvolveAboveIvValue": 5.0,
    "EvolveAllPokemonAboveIv": true,
    "EvolveAllPokemonWithEnoughCandy": true,
    "EvolveKeptPokemonsAtStorageUsagePercentage": 90.0,
    "EvolveKeptPokemonIfBagHasOverThisManyPokemon": 120,
    "KeepPokemonsThatCanEvolve": false,
    "KeepMinCp": 1250,
    "KeepMinIvPercentage": 90.0,
    "KeepMinLvl": 6,
    "KeepMinOperator": "or",
    "UseKeepMinLvl": false,
    "PrioritizeIvOverCp": true,
    "KeepMinDuplicatePokemon": 1,
    "UsePokemonToNotCatchFilter": true,
    "UsePokemonSniperFilterOnly": false,
    "DumpPokemonStats": false,
    "DelayBetweenPokemonUpgrade": 10000,
    "OutOfBallCatchBlockTime": 5,
    "PokeballToKeepForSnipe": 50,
    "UseBulkTransferPokemon": true,
    "BulkTransferStogareBuffer": 10,
    "BulkTransferSize": 100,
    "UseBallOperator": "or",
    "FavoriteMinCp": 0.0,
    "DefaultBuddyPokemon": "",
    "FavoriteMinLevel": 0,
    "FavoriteOperator": "and",
    "RenamePokemonRespectTransferRule": false,
    "UpgradePokemonLvlMinimum": 30.0,
    "EvolveOperator": "and",
    "EvolveFavoritedOnly": false,
    "EvolveMinIV": 100.0,
    "EvolveMinCP": 2000.0,
    "EvolveMinLevel": 25.0

  "PokemonsToEvolve": [
    "rattata",
    "spearow",
    "drowzee",
    "pidgey",
    "weedle",
    "caterpie",
    "krabby",
    "gastly",
    "shellder",
    "goldeen",
    "paras",
    "staryu",
    "poliwag",
    "krabby",
    "rhyhorn",
    "dratini",
    "swinub",
    "sentret",
    "hoothoot",
    "ledyba",
    "hoppip",
    "wooper",
    "natu",
    "eevee"

**Comment by hardknoxni69a** [comment]
you need to add your pokemon to the pokemontoevolvefilter now 
    "Swinub": {
      "MinIV": 0.0,
      "MinLV": 0.0,
      "MinCP": 0.0,
      "Moves": [],
      "Operator": "and",
      "EvolveTo": "Piloswine",
      "FavoritedOnly": false,
      "AffectToPokemons": null
    },

**Comment by FureszOszkar** [comment]
Thx!

2017. febr. 26. 23:02 ezt írta ("hardknoxni69a" <notifications@github.com>):
