### ISSUE TITLE
WIN.exeGUI swapped sprite/graphic Hyper and Super Potions

### ISSUE THREAD

**Issue by macinmn** [Necrobot-Private/NecroBot#1063]
### Expected Behavior:

Potions match in-game graphic color

### Actual Behavior:

Super potions are pink (like Hyper in-game), Hyper potions are orange (like Super in-game)

### Your config.json:

n/a

### (OPTIONAL) Your Log:

n/a

### Detailed Steps to Reproduce: 

load inventory in Window GUI

### Other Information

attaching screenshot
![121pots](https://cloud.githubusercontent.com/assets/20800607/23344587/1b5f8c12-fc4d-11e6-9908-391861a10107.JPG)

Version: .121
Windows Version: Win7
What is affected ():  WinGUI executable

**Comment by hardknoxni69a** [comment]
i wouldnt really call this a bug quick fix though just give it time
