### ISSUE TITLE
Pokemon transfer enhancement.

### ISSUE THREAD

**Issue by yandrake** [Necrobot-Private/NecroBot#1065]
With this awesome Snipe server, and the new gen with 80 pokemon, is much more common to get the pokemon bag full. I know that there is already a sistem to select wich pokemon you want to keep, and with how much CP and IV you want to keep them, but with the new introduction of the pokemon, there are right now too much pokemon to manually configure them one by one, and even doing that, pokemon bag could get too full.
I have 2 propositions to try to solve this problem.
First one is to make a config similar to this

    "KeepMinCp": 2000,
    "KeepMinIvPercentage": 99.9,
    "KeepMinLvl": 29,
    "KeepMinOperator": "or",

But instead of keep pokemon, transfer. It would make things much more easy, and it would help a lot to not get the pokemon bag full.

The second proposition is to make config that it would automatically transfer the X number of pokemon you set, listed from low to high, in CP or/and IV. For example. You get your pokemon bag full, you set the transfer pokemon by CP in 10, then bot would transfer the lowest 10 of 250 CP pokemon from full bag. In this way you would never get your bag full. 
And if you set it in IV, and your bag is full of 100% IVs pokemon, then transfer the lowest X pokemon listed Via CP and IV. For example, bag full of 100% Ivs, transfer the lowest 10 CP pokemon from the bag full of 100% IVs.
I know that there is the bulk transfer feature now, but is not very clear how to set it to do something like this. WHat you guys think? I know that it would be in low priority, but I think it would be an interesting feature.

**Comment by hardknoxni69a** [comment]
just set keep min cp as 5000 100 iv and operator "and" and keep min duplicate at 1 and the bot will only keep one of each pokemon that has highest iv or cp depending on how you want it
