### ISSUE TITLE
badauthentication

### ISSUE THREAD

**Issue by lorenzoL1** [Necrobot-Private/NecroBot#1066]
i can't login anymore .

google returned an error message ; badauthenaction.
ive changed my settings allow less secure apps on .
but it's still not working
can someone please help me

**Comment by yandrake** [comment]
Looks like account banned. You were using the legacy free version, right?

**Comment by hardknoxni69a** [comment]
please dont just create more issues #1064

**Comment by lorenzoL1** [comment]
yes . i use the free version . and yes i van log in on my phone . 
@hardknoxni69a   you closes the issues . but there not solved yet ?

**Comment by hardknoxni69a** [comment]
We solves this I closedbecause it is Google issue not necrobot
