### ISSUE TITLE
[Request] Gym filtering system

### ISSUE THREAD

**Issue by LakuLakuRuler** [Necrobot-Private/NecroBot#1068]
I have trouble with attacking the Gym with Snorlax and Blissey.
(usually, it gets overtime)
so I hope that if there is a filtering system to skip the gym with specific pokemons.

**Comment by ziomber** [comment]
In progress. Soon will be finished.

**Comment by ziomber** [comment]
it's done in #1089. I missed  this issue in tag

**Comment by hardknoxni69a** [comment]
implemented
