### ISSUE TITLE
[QUESTION] CATCH LIMIT - catch counter multiplies after errors like: Current Operation was canceled

### ISSUE THREAD

**Issue by BoydTM** [Necrobot-Private/NecroBot#107]
I believe it was reported in previous versions ... is there any way to counteract this other than manually deleting PokemonTS & PokestopTS ?

Version:
Windows Version: 0.9.8.8
What is affected (catch, transfer, favorite, GPX, evolve, recycle, snipe, human walk snipe, pokestops, powerup/levelup, other):

**Comment by CreativiTimothy** [comment]
Occasionally, it seems to divide / delete instead of multiply, but most of the time, it does multiply. THe better your Internet connection, the less this will happen. I'd prefer if this was fixed somehow though

**Comment by owenchai1989** [comment]
same here
