### ISSUE TITLE
Verified Pokemon and Pokestop

### ISSUE THREAD

**Issue by Lavitz51** [Necrobot-Private/NecroBot#1074]
Search everywhere but not find the answer.

How must I config my Necrobot 2 - Window GUI to only see "verified" pokemon in the Sniper section?

How must I config my Necrobot 2 - Window GUI to farm pokestop?... My bot take one poke stop every ten minutes!!!!!!

Thanks all ;)

**Comment by samuraitruong** [comment]
please ask on discord, don't ask question here.
