### ISSUE TITLE
WIN GUI Not starting

### ISSUE THREAD

**Issue by DemonKing28** [Necrobot-Private/NecroBot#1078]
![error](http://image.prntscr.com/image/a0e4fca75bca4d238ca629ba9736d5ad.png)
@jjskuld @samuraitruong

**Comment by Lord-Haji** [comment]
@hardknox69a

**Comment by hardknoxni69a** [comment]
u need to load necrobot2.exe before loading and i would recommend just using the all in one solution necrbot2.win as its much better the old GUi/electron isnt really updated anymore but for basic questions help setting up and stuff check out our discord info on the wiki section people are always there to help
