### ISSUE TITLE
can't login with ptc

### ISSUE THREAD

**Issue by pradremsak** [Necrobot-Private/NecroBot#1092]
i have a new ptc account with uppercase and lowercase in password

example: Ptc-1234

bot still say password incorrect and i can't login through necrobot still can login via my phone

**Comment by mcreuter** [comment]
same with google

**Comment by FrankVincent** [comment]
I cannot login with my phone as well, msg written "cannot get account data from server, have I got banned?

**Comment by pokkemonner** [comment]
[19:47:09] (ERROR) User credentials are invalid and login failed.

Goodby all. My 3 accounts got banned in one wave. Back to the XBOX. I have had it with PoGo.

**Comment by jjskuld** [comment]
Looks like new banwave.

**Comment by pradremsak** [comment]
รi have create new account with ptc that have upper case and lower case password can't login with necro bot  that it said wrong password
