### ISSUE TITLE
No foolproof way to keep from getting banned?

### ISSUE THREAD

**Issue by erytcxbv** [Necrobot-Private/NecroBot#1093]
I've literally tried every single setup imaginable yet this is the 4th time I've been banned and this time I made it all the way to level 34! :(

**Comment by erytcxbv** [comment]
I thought I played it as safe as possible with no sniping, Pokestop limit and Catch limit turned on and walking no faster than 4.5KMH with a 1.5KMH variation enabled.

**Comment by adanrs** [comment]
using legacy or ?

**Comment by erytcxbv** [comment]
What do you mean using legacy?

**Comment by erytcxbv** [comment]
Oh no nevermind I've been using the hashing key so it's been running on the current API and I still go banned.

**Comment by yayahai** [comment]
Someone is flagging your account  in the area you are playing.

**Comment by erytcxbv** [comment]
Well the only thing I can think of is that I enabled the gym attack option in the bot but disabled the use of dodging do you think turning on the automatic gym attack option caused someone to report my account and get me banned then? I'll have to stay away from that one option then.

**Comment by yayahai** [comment]
Doesn't seem like it. Just don't level up too fast.

**Comment by erytcxbv** [comment]
Well I'm going to go through it again on a new account but leave every single option on it's default with about a 4-5KMH speed and see what happens and if I get banned again I guess I'll just stop. No use in paying for something that gets you banned anyway no matter how cautious you are.

**Comment by yayahai** [comment]
Seeing your case it seems legacy API is much safer if you keep solving the CAPTCHA on time.

**Comment by erytcxbv** [comment]
If that's the case then it doesn't make much sense since the hashkey uses the current API.

**Comment by mangonzalez00783** [comment]
Sincerely I have only had an account in which I have used many types of bots, at this time necrobot2 and I have never been banned, you must be careful to have the configuration as humanized as possible, use the limits of pokestop and capture pokemon, the Snipe is a risk but you should also have limited it to a small amount, I have also configured the gyms and there is no problem, at this moment I am in level 34 and I have had no problem ...

**Comment by erytcxbv** [comment]
What speed have you had yours set to? Both the speed and the variation if possible thank you :)

**Comment by mangonzalez00783** [comment]
My speed setting is:
     "WalkingSpeedInKilometerPerHour": 3.6,
     "WalkingSpeedVariant": 2.2,
Also be careful with the delay actions, use the logic and think about how long it would take to perform the action and the time that takes the real game in their animations ...

**Comment by erytcxbv** [comment]
If you could post your config it would be extremely helpful, I've never thought about changing the delay times myself I kind of hoped the default values would be good enough haha.

**Comment by mangonzalez00783** [comment]
Mi configuration is:
[config.txt](https://github.com/Necrobot-Private/NecroBot/files/806310/config.txt)
It is very slow progress with this configuration but it is because I tried to do it as humanized as possible.

This configuration has allowed me to get this inventory...
[inventory.xlsx](https://github.com/Necrobot-Private/NecroBot/files/806304/inventory.xlsx)

**Comment by erytcxbv** [comment]
I'm perfectly fine with the slow progress I'm just fed up with getting banned 5 to 6 levels away from max haha. Thanks again you're a lifesaver!!

**Comment by mangonzalez00783** [comment]
I hope it helps you and someone else to see ...

**Comment by FrankVincent** [comment]
I use legacy API but I still got banned, what happened?

**Comment by jjskuld** [comment]
@erytcxbv If you ever get CatchFlee softbanned, then your account is pretty much as good as banned. So stay WAAY below the maximum catch and pokestop limits.  

Walking speed is less of an issue, Niantic doesn't seem to be flagging based on that.

@FrankVincent If you use legacy API, then you have almost 100% chance of ban, it's just a matter of when.

**Comment by dimitris63** [comment]
@mangonzalez00783 I have tried to open your config file and I can not. have you removed it? how can I print it or save it to my computer

**Comment by andeomontenegro** [comment]
I think there 3 reason for ban: overexp (80k per day is safety), softban and flagging.
I have multibot pack and use disabled human walk. Banned only 4, which greatly active in gym battles. Other 2 is alive, but all 6 have same config.
So I must be right.

**Comment by hardknoxni69a** [comment]
I honestly don't think they have a daily xp limit because they have the catch spin limit which restricts ur xp already but as they said more human the better the config is your friend study it learn and adjust so if anyone ever looks at your account it looks like a person actually did it and yes someone could be a hater and flag ur account to have niantic look at it and most bots at this point can be seen because u are religiously doing the same.exact stuff over and over by using ur delays and randomizing the delays it helps though because it's not consistent JJ added a lot of random delays to config check it out makes things much safer

**Comment by dimitris63** [comment]
@mangonzalez00783 I first want to thank you for your config file. I am up to 34 with no problems and will be on 35 very shortly. I have 3 questions and would be grateful if you could help me.
With the new updates I had to disable pokestops as I was getting error. How do you currently have pokestops configured?
Did necrobot automatically auto config our config file for RAIDS? How do you have RAIDS configured?
A several weeks ago there was an issue with Necrobot and or the Hash server and the below message popped up. I got this message before when I was in the teens and it went away automatically. What can I do now
 [11:47:39] (INFO) Your IP is: 24.228.65.94
[11:47:43] (ATTENTION) This account CTitus63 seems to be flagged, it is recommended to not use bot on this account for now!
[11:48:18] (INFO) Playing as CTitus63
[11:48:21] (ATTENTION) Detected realistic Traveling , using Default Settings inside config.json
[11:48:21] (ATTENTION) Make sure Lat & Lng are right. Exit Program if not! Lat: 33.4270628379959 Lng: -117.612351543952
