### ISSUE TITLE
Necrobot doesn't check for the potential evolutions

### ISSUE THREAD

**Issue by ning1002** [Necrobot-Private/NecroBot#1098]
Expected Behavior:

NECROBOT should check for the potential evolves 
Actual Behavior:
necrobot doesn't check for the potential evolves at all

Your config.json:

"PokemonConfig": {
    "CatchPokemon": true,
    "DelayBetweenPokemonCatch": 6100,
    "UseCatchLimit": true,
    "CatchPokemonLimit": 800,
    "CatchPokemonLimitMinutes": 1350,
    "UseIncenseConstantly": false,
    "UseEggIncubators": true,
    "UseLimitedEggIncubators": false,
    "UseLuckyEggConstantly": false,
    "UseLuckyEggsMinPokemonAmount": 70,
    "UseLuckyEggsWhileEvolving": true,
    "TransferWeakPokemon": true,
    "TransferDuplicatePokemon": false,
    "TransferDuplicatePokemonOnCapture": true,
    "RenamePokemon": false,
    "RenameOnlyAboveIv": false,
    "RenameTemplate": "{Name}_{IV}_Lv{Level}",
    "FavoriteMinIvPercentage": 100.0,
    "AutoFavoritePokemon": true,
    "MaxPokeballsPerPokemon": 10,
    "UseGreatBallAboveCp": 760,
    "UseUltraBallAboveCp": 1330,
    "UseMasterBallAboveCp": 4200,
    "UseGreatBallAboveIv": 97.0,
    "UseUltraBallAboveIv": 100.0,
    "UseGreatBallBelowCatchProbability": 0.5,
    "UseUltraBallBelowCatchProbability": 0.3,
    "UseMasterBallBelowCatchProbability": 0.01,
    "AutomaticallyLevelUpPokemon": false,
    "OnlyUpgradeFavorites": true,
    "UseLevelUpList": true,
    "AmountOfTimesToUpgradeLoop": 5,
    "GetMinStarDustForLevelUp": 5000,
    "LevelUpByCPorIv": "iv",
    "UpgradePokemonCpMinimum": 1000.0,
    "UpgradePokemonIvMinimum": 100.0,
    "UpgradePokemonMinimumStatsOperator": "and",
    "EvolveAboveIvValue": 100.0,
    "EvolveAllPokemonAboveIv": false,
    "EvolveAllPokemonWithEnoughCandy": true,
    "EvolveKeptPokemonsAtStorageUsagePercentage": 80.0,
    "EvolveKeptPokemonIfBagHasOverThisManyPokemon": 200,
    "KeepPokemonsThatCanEvolve": true,
    "KeepMinCp": 1850,
    "KeepMinIvPercentage": 90.0,
    "KeepMinLvl": 28,
    "KeepMinOperator": "and",
    "UseKeepMinLvl": false,
    "PrioritizeIvOverCp": true,
    "KeepMinDuplicatePokemon": 1,
    "UsePokemonToNotCatchFilter": true,
    "UsePokemonSniperFilterOnly": true,
    "DumpPokemonStats": false,
    "DelayBetweenPokemonUpgrade": 10000,
    "OutOfBallCatchBlockTime": 5,
    "PokeballToKeepForSnipe": 30,
    "UseBulkTransferPokemon": true,
    "BulkTransferStogareBuffer": 10,
    "BulkTransferSize": 100,
    "UseBallOperator": "or",
    "FavoriteMinCp": 0.0,
    "DefaultBuddyPokemon": "",
    "FavoriteMinLevel": 30,
    "FavoriteOperator": "and",
    "RenamePokemonRespectTransferRule": false,
    "UpgradePokemonLvlMinimum": 30.0,
    "EvolveOperator": "and",
    "EvolveFavoritedOnly": false,
    "EvolveMinIV": 100.0,
    "EvolveMinCP": 1000.0,
    "EvolveMinLevel": 30.0

"PokemonEvolveFilter": {
"Weedle": {
"MinIV": 0.0,
"MinLV": 0.0,
"MinCP": 0.0,
"Moves": [],
"Operator": "or",
"EvolveTo": "",
"AffectToPokemons": [],
"FavoritedOnly": false,
"MinCandiesBeforeEvolve": 0
},
"Pidgey": {
"MinIV": 0.0,
"MinLV": 0.0,
"MinCP": 0.0,
"Moves": [],
"Operator": "or",
"EvolveTo": "",
"AffectToPokemons": [],
"FavoritedOnly": false,
"MinCandiesBeforeEvolve": 1000
},
"Caterpie": {
"MinIV": 0.0,
"MinLV": 0.0,
"MinCP": 0.0,
"Moves": [],
"Operator": "or",
"EvolveTo": "",
"AffectToPokemons": [],
"FavoritedOnly": false,
"MinCandiesBeforeEvolve": 0
},

Logs:
[19:04:28] (EGG) Incubator status update: 1.91km left
[19:04:28] (INFO) Amount of Pokemon Seen: 27/231, Amount of Pokemon Caught: 22/231
[19:04:30] (ATTENTION) No usable PokeStops found in your area. Is your maximum distance too small?
[19:04:30] (EGG) Incubator status update: 1.91km left
[19:04:30] (INFO) Amount of Pokemon Seen: 27/231, Amount of Pokemon Caught: 22/231
[19:04:32] (ATTENTION) No usable PokeStops found in your area. Is your maximum distance too small?
[19:04:32] (EGG) Incubator status update: 1.91km left
[19:04:32] (INFO) Amount of Pokemon Seen: 27/231, Amount of Pokemon Caught: 22/231
[19:04:34] (INFO) Traveling to Pokestop:  (50 m) (9 seconds) (route NecroBot Walk)
[19:04:34] (SNIPER) Sniper count 0
[19:04:35] (SNIPER) Sniper count 0
[19:04:35] (INFO) Skipped Chikorita

**Comment by ning1002** [comment]
"PokemonEvolveFilter": {
    "Weedle": {
      "MinIV": 0.0,
      "MinLV": 0.0,
      "MinCP": 0.0,
      "Moves": [],
      "Operator": "or",
      "EvolveTo": "",
      "AffectToPokemons": [],
      "FavoritedOnly": false,
      "MinCandiesBeforeEvolve": 0
    },
    "Pidgey": {
      "MinIV": 0.0,
      "MinLV": 0.0,
      "MinCP": 0.0,
      "Moves": [],
      "Operator": "or",
      "EvolveTo": "",
      "AffectToPokemons": [],
      "FavoritedOnly": false,
      "MinCandiesBeforeEvolve": 1000
    },
    "Caterpie": {
      "MinIV": 0.0,
      "MinLV": 0.0,
      "MinCP": 0.0,
      "Moves": [],
      "Operator": "or",
      "EvolveTo": "",
      "AffectToPokemons": [],
      "FavoritedOnly": false,
      "MinCandiesBeforeEvolve": 0
    },

**Comment by ning1002** [comment]
it only checks for the item inventory and the amount of pokemon seen
my pokemons are over 250 and there are more than 100 pidgeys with more than 1000 candies.

**Comment by jjskuld** [comment]
What version are you using?  Retry using the latest version and post a log of the evolution behavior. The log you posted doesn't even show evolutions.

This was fixed in #1075, so reopen if you still see this is broken.

**Comment by ning1002** [comment]
that's exactly what Im talking about.
I'm using the latest version 122
I can't see any potential evolutions check!
