### ISSUE TITLE
Issue Logging

### ISSUE THREAD

**Issue by mangonzalez00783** [Necrobot-Private/NecroBot#1106]
I have a problem in version 123...

The fields are filled with the correct data and shows me this error

[22:37:54] (INFO) Logging in using Google 
[22:37:54] (ERROR) You need to fill out Username and Password in auth.json!

Version: 1.0.0.123
Windows Version: Windows 10

**Comment by jjskuld** [comment]
Can you post your auth.json?

**Comment by hardknoxni69a** [comment]
i take it with lack of response this issue has been resolved please let us know if you need assistance

**Comment by rf7991** [comment]
{
  "Bots": [],
  "ProxyConfig": {
    "UseProxy": false,
    "UseProxyHost": null,
    "UseProxyPort": null,
    "UseProxyAuthentication": false,
    "UseProxyUsername": null,
    "UseProxyPassword": null
  },
  "DeviceConfig": {
    "DevicePlatform": "ios",
    "DevicePackageName": "custom",
    "DeviceId": "cb76eb06a3bb250d2d2aaaa2b3b6276112ca8edb",
    "AndroidBoardName": null,
    "AndroidBootloader": null,
    "DeviceBrand": "Apple",
    "DeviceModel": "iPad",
    "DeviceModelIdentifier": null,
    "DeviceModelBoot": "iPad6,8",
    "HardwareManufacturer": "Apple",
    "HardwareModel": "J99aAP",
    "FirmwareBrand": "iPhone OS",
    "FirmwareTags": null,
    "FirmwareType": "9.2.1",
    "FirmwareFingerprint": null,
    "UseRandomDeviceId": false
  },
  "APIConfig": {
    "UsePogoDevAPI": true,
    "AuthAPIKey": "xxx",
    "UseLegacyAPI": false,
    "DiplayHashServerLog": true
  }
}

## *Same case here, have been absent for so long :p . Now i've noticed below lines are not in the new auth.json. Where to add it now?
  
"AuthConfig": {
    "AuthType": "google",
    "GoogleUsername": "holygreymon@gmail.com",
    "GooglePassword": "xxx",
    "PtcUsername": null,
    "PtcPassword": null
