### ISSUE TITLE
Google Walk not working?

### ISSUE THREAD

**Issue by tws101** [Necrobot-Private/NecroBot#111]
### Expected Behavior:
Google walk should be used

### Actual Behavior:
Necrobot Walk is used instead of google. It tries google once.

### Your config.json:
  "GoogleWalkConfig": {
    "UseGoogleWalk": true,
    "DefaultStepLength": 1.3,
    "GoogleHeuristic": "walking",
    "GoogleAPIKey": "MY KEY",
    "Cache": true,
    "GoogleElevationAPIKey": "MY KEY"

*****Please note I removed my API keys....

### (OPTIONAL) Your Log:
[10:07:09] Traveling to Pokestop/Gym: Cool Blue Mural (65m) (18 seconds) (route Google Walk)
[10:07:10] Traveling to Pokestop/Gym: Cool Blue Mural (65m) (18 seconds) (route NecroBot Walk)

Notice it trying google walk once.

### Other Information
(Attach zip files if needed.)

Version:  9.8.9
Windows Version:  10
What is affected (catch, transfer, favorite, GPX, evolve, recycle, snipe, human walk snipe, pokestops, powerup/levelup, other):  WALK

**Comment by ajns73** [comment]
Two botters here experiencing the same thing. Dump to necrowalk after what appears to be a Google walk failure.

**Comment by Pokego0108** [comment]
Same case here

**Comment by LobsterX** [comment]
using mapzen now.

Seems better?


anyways, for google elevation api, is it the same as the google map api?

i ahve both enabled. they are the same key?

**Comment by ajns73** [comment]
@LobsterX As far as I understand, yes. The API is just door, anyone can walk in if they have the key.

**Comment by jjskuld** [comment]
Fix is coded in 4029f56922616c5ba69c68fc6bfe10af680c0209. Look for next release to fix this.

**Comment by ajns73** [comment]
I can confirm this is fixed for me.

**Comment by ikariya69** [comment]
not fixed in 1.0.0.0, cant get update of pah on pokeease qith googlewalk, seems to work with mazpen
