### ISSUE TITLE
GUI problems

### ISSUE THREAD

**Issue by schaf123** [Necrobot-Private/NecroBot#1114]
My GUI PokeEase suddenly stopped working. I can open it, but it's just loading and loading and nothing happening.. It's the GUI Electron. Help?

**Comment by creeperraper1337** [comment]
im having the same issue with the NecroBot2 Fork. I tried to reinstall everything and when i got to the part where i open the GUI (regular GUI--not WIN or ELECTRON). When i clicked install to install the Pokease thingy, it said return status was 404 not found.
( ik "thingy" isnt very descriptive lol)

**Comment by ineswut** [comment]
having exactly the same problem, any help?

**Comment by jjskuld** [comment]
The GUI needs to be removed.. It is no longer maintained. If you wish, use the Electron instead.

**Comment by pangait** [comment]
i can't start the necrobot2.win.exe. before this it works fine. only after a few updates it failed to run. necrobot2.exe works fine tho. downloaded the necrobot2.win.exe 64BIT still have the same issue.
i cant paste any logs cause i cant even run the program. im using win10 64bit. t.q

**Comment by hardknoxni69a** [comment]
please try latest version of necrobot2.win.exe when u load bot click show console and create an issue with the warning please let us know the issue with WIN
