### ISSUE TITLE
Problems with log in WIN

### ISSUE THREAD

**Issue by SpeedSavitar** [Necrobot-Private/NecroBot#1115]
I'm having problems to log in with WIN bot, i use google account, I already checked the password and the email and it's right, but the bot keep trying to log and i can't

**Comment by hardknoxni69a** [comment]
we need to know what it says

**Comment by SpeedSavitar** [comment]
When i try to use Console it appears
![error](https://cloud.githubusercontent.com/assets/26119318/23470140/665a3936-fe84-11e6-80be-9b709eca5e03.png)

**Comment by hardknoxni69a** [comment]
try deleting you .old files in the folders and the accounts,db i think that might help

**Comment by SpeedSavitar** [comment]
When I use WIN and i select Legacy One, the window that i put my name and password don't appear
![win](https://cloud.githubusercontent.com/assets/26119318/23470280/c2a201f6-fe84-11e6-85be-f0358c204aa6.png)

**Comment by SpeedSavitar** [comment]
Where this OLD files are? and this accounb.db? I created a new folder, extracted the Console ZIP and the error continues the same

**Comment by jjskuld** [comment]
This is a bug with accounts.db file. I am working on a fix.
