### ISSUE TITLE
Sniper not Resting

### ISSUE THREAD

**Issue by ajns73** [Necrobot-Private/NecroBot#112]
Sniper will rest 10 minutes between 39 pokemon snipings

![image](https://cloud.githubusercontent.com/assets/21206609/18479658/6a3b88e8-799b-11e6-9b0e-b6fbf0d2ac9c.png)

"SnipeConfig": {
    "UseSnipeLocationServer": false,
    "SnipeLocationServer": "localhost",
    "SnipeLocationServerPort": 16969,
    "GetSniperInfoFromPokezz": true,
    "GetOnlyVerifiedSniperInfoFromPokezz": false,
    "GetSniperInfoFromPokeSnipers": false,
    "GetSniperInfoFromPokeWatchers": false,
    "GetSniperInfoFromSkiplagged": false,
    "MinPokeballsToSnipe": 20,
    "MinPokeballsWhileSnipe": 0,
    "MinDelayBetweenSnipes": 60000,
    "SnipingScanOffset": 0.005,
    "SnipeAtPokestops": true,
    "ActivateMSniper": false,
    "SnipeIgnoreUnknownIv": false,
    "UseTransferIvForSnipe": false,
    "SnipePokemonNotInPokedex": false,
    "UseSnipeLimit": true,
    "SnipeRestSeconds": 600,
    "SnipeCountLimit": 39

Start a sniping session (at pokestops) let it run until it hits 39. Wait and it will start sniping again with only 1 "Sniper need to take a rest before your account is banned" And begins sniping again before 10 minutes (See the image above)

Version: 0.9.8.9
Windows Version: 10 x64
What is affected snipe,

**Comment by NzV** [comment]
Checked it work like excepted
Look in your log the last Pokemon caught by sniper was 10 min ago the reset. (Already 3 min between yours pidgey catch and the reset an i don't know what tour bot did before)

**Comment by ajns73** [comment]
Your right. I jumped the gun. That was the tail end of the 10 minutes. I hit 39 at 09:55, next snipe 10:05. My bad.
