### ISSUE TITLE
Is it a ban ?

### ISSUE THREAD

**Issue by alexdu62150** [Necrobot-Private/NecroBot#1122]
Hello guys, I just get this and I can't connect anymore, hope it can helps you (sorry for my bad english !)

[19:51:45] (ERREUR) Bad Request - If you see this message please copy error log & screenshot send back to dev asap.
[19:51:45] (ERREUR) BAD REQUEST 
{"StatusCode":2,"RequestId":1305362427,"Requests":[{"RequestType":106,"RequestMessage":[10,189,1,128,128,128,128,172,172,181,225,71,128,128,128,128,180,172,181,225,71,128,128,128,128,148,175,181,225,71,128,128,128,128,180,175,181,225,71,128,128,128,128,188,175,181,225,71,128,128,128,128,196,175,181,225,71,128,128,128,128,204,175,181,225,71,128,128,128,128,212,175,181,225,71,128,128,128,128,220,175,181,225,71,128,128,128,128,228,175,181,225,71,128,128,128,128,236,175,181,225,71,128,128,128,128,244,175,181,225,71,128,128,128,128,252,175,181,225,71,128,128,128,128,132,208,202,225,71,128,128,128,128,148,208,202,225,71,128,128,128,128,156,208,202,225,71,128,128,128,128,164,208,202,225,71,128,128,128,128,172,208,202,225,71,128,128,128,128,180,208,202,225,71,128,128,128,128,188,208,202,225,71,128,128,128,128,212,211,202,225,71,18,21,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,25,156,4,29,161,172,81,73,64,33,199,178,145,109,234,91,8,64]},{"RequestType":600,"RequestMessage":[]},{"RequestType":126,"RequestMessage":[]},{"RequestType":4,"RequestMessage":[8,169,215,216,217,168,43]},{"RequestType":129,"RequestMessage":[]},{"RequestType":5,"RequestMessage":[10,40,54,51,97,99,51,102,54,101,100,50,52,102,50,53,102,55,102,57,98,52,54,48,57,101,100,54,52,102,53,98,49,97,98,100,50,102,55,100,49,97]},{"RequestType":153,"RequestMessage":[]}],"PlatformRequests":[{"Type":8,"RequestMessage":[10,40,57,48,102,54,97,55,48,52,53,48,53,98,99,99,97,99,55,51,99,101,99,57,57,98,48,55,55,57,52,57,57,51,101,54,102,100,53,97,49,50]},{"Type":6,"RequestMessage":[10,133,4,138,176,240,207,165,76,208,14,204,118,0,61,21,82,158,42,77,108,176,162,179,0,244,133,9,112,4,247,118,175,250,200,182,100,226,208,225,56,158,125,182,45,97,175,137,41,188,228,94,231,176,80,99,166,225,165,151,134,77,249,223,121,93,178,42,56,241,26,71,140,131,213,42,194,207,20,104,53,60,32,240,185,17,184,51,172,209,36,194,178,114,125,222,133,124,209,2,242,184,230,98,216,48,238,249,192,162,241,207,65,39,23,122,12,45,248,63,183,159,183,101,45,203,179,64,232,235,97,63,243,166,209,39,182,163,162,120,67,62,49,208,121,65,29,168,253,105,164,107,61,209,51,253,21,254,181,249,134,65,88,247,139,115,217,187,32,203,168,28,33,0,45,228,171,35,160,48,237,103,52,86,113,161,37,195,123,192,203,100,153,97,30,22,23,115,13,30,220,215,168,170,188,224,76,210,190,228,139,229,141,88,25,27,126,171,137,157,52,113,169,117,5,223,3,16,21,108,173,27,79,30,250,167,90,255,69,85,37,75,228,234,20,221,106,220,40,178,90,15,76,3,61,133,53,60,27,248,223,255,88,211,246,230,26,0,221,10,236,161,165,63,120,64,130,41,9,118,158,224,91,211,99,148,186,215,251,221,140,71,213,47,45,211,185,58,28,1,76,19,1,72,12,171,195,152,60,155,168,73,144,155,104,240,85,248,127,6,197,244,209,172,45,129,117,60,236,8,253,19,180,52,195,80,25,70,3,18,85,246,172,44,50,183,147,211,73,73,136,11,42,50,162,87,31,86,245,46,116,77,248,187,180,111,174,140,213,111,57,242,82,98,97,224,29,185,145,16,35,179,126,34,32,244,164,94,20,117,97,137,169,208,13,25,73,221,79,190,131,7,141,85,90,14,152,110,224,78,124,105,236,86,231,38,145,203,37,69,101,213,162,53,14,36,244,120,204,84,41,191,152,68,154,239,200,166,46,250,154,137,111,185,97,174,49,179,190,243,34,18,38,98,89,43,249,144,253,77,132,52,84,199,122,82,187,99,247,24,124,182,128,83,190,70,180,155,43,208,137,45,105,65,95,216,237,40,106,62,177,10,37,173,100,241,9,135,14,217,83,139,103,157,161,202,37,111,160,125,160,77,8,142,137,216,86,17,161,113]}],"Latitude":50.638080729645679,"Longitude":3.0448807296837432,"Accuracy":50.0,"AuthInfo":null,"AuthTicket":{"Start":[127,189,192,51,176,214,143,151,121,240,168,218,175,98,11,222,157,205,44,203,140,45,225,162,88,39,129,219,235,66,227,245,253,114,111,241,15,39,244,72,46,17,30,74,228,42,188,41,233,24,208,146,173,226,18,139,157,185,141,55,173,92,203,178,170,88,54,120,230,164,23,252,192,189,24,129,73,187,149,228],"ExpireTimestampMs":1488394554450,"End":[155,40,103,40,152,142,28,253,53,176,144,178,115,100,185,178]},"MsSinceLastLocationfix":16839}
[19:51:45] (ERREUR)    à PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PerformRemoteProcedureCall>d__2`1.MoveNext() dans c:\projects\necrobot2\FeroxRev\Extensions\HttpClientExtensions.cs:ligne 129
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PerformThrottledRemoteProcedureCall>d__8`1.MoveNext() dans c:\projects\necrobot2\FeroxRev\Extensions\HttpClientExtensions.cs:ligne 174
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProtoPayload>d__0`1.MoveNext() dans c:\projects\necrobot2\FeroxRev\Extensions\HttpClientExtensions.cs:ligne 46
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à PokemonGo.RocketAPI.Rpc.BaseRpc.<PostProtoPayload>d__11`1.MoveNext() dans c:\projects\necrobot2\FeroxRev\Rpc\BaseRpc.cs:ligne 130
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à PokemonGo.RocketAPI.Rpc.BaseRpc.<PostProtoPayload>d__10`8.MoveNext() dans c:\projects\necrobot2\FeroxRev\Rpc\BaseRpc.cs:ligne 119
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   à PokemonGo.RocketAPI.Rpc.Map.<GetMapObjects>d__12.MoveNext() dans c:\projects\necrobot2\FeroxRev\Rpc\Map.cs:ligne 116
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à PoGo.NecroBot.Logic.Tasks.CatchNearbyPokemonsTask.<GetNearbyPokemons>d__1.MoveNext() dans c:\projects\necrobot2\PoGo.NecroBot.Logic\Tasks\CatchNearbyPokemonsTask.cs:ligne 183
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   à PoGo.NecroBot.Logic.Tasks.CatchNearbyPokemonsTask.<Execute>d__0.MoveNext() dans c:\projects\necrobot2\PoGo.NecroBot.Logic\Tasks\CatchNearbyPokemonsTask.cs:ligne 53
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à PoGo.NecroBot.Logic.Tasks.UseNearbyPokestopsTask.<OnWalkingToPokeStopOrGym>d__12.MoveNext() dans c:\projects\necrobot2\PoGo.NecroBot.Logic\Tasks\UseNearbyPokestopsTask.cs:ligne 167
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à PoGo.NecroBot.Logic.Tasks.UseNearbyPokestopsTask.<>c__DisplayClass10_0.<<WalkingToPokeStop>b__0>d.MoveNext() dans c:\projects\necrobot2\PoGo.NecroBot.Logic\Tasks\UseNearbyPokestopsTask.cs:ligne 149
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   à PoGo.NecroBot.Logic.Strategies.Walk.BaseWalkStrategy.<DoWalk>d__19.MoveNext() dans c:\projects\necrobot2\PoGo.NecroBot.Logic\Strategies\Walk\BaseWalkStrategy.cs:ligne 222
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à PoGo.NecroBot.Logic.Strategies.Walk.GoogleStrategy.<Walk>d__4.MoveNext() dans c:\projects\necrobot2\PoGo.NecroBot.Logic\Strategies\Walk\GoogleStrategy.cs:ligne 46
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à PoGo.NecroBot.Logic.Navigation.<Move>d__14.MoveNext() dans c:\projects\necrobot2\PoGo.NecroBot.Logic\Navigation.cs:ligne 101
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à PoGo.NecroBot.Logic.Tasks.UseNearbyPokestopsTask.<WalkingToPokeStop>d__10.MoveNext() dans c:\projects\necrobot2\PoGo.NecroBot.Logic\Tasks\UseNearbyPokestopsTask.cs:ligne 145
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   à PoGo.NecroBot.Logic.Tasks.UseNearbyPokestopsTask.<Execute>d__8.MoveNext() dans c:\projects\necrobot2\PoGo.NecroBot.Logic\Tasks\UseNearbyPokestopsTask.cs:ligne 66
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à PoGo.NecroBot.Logic.Tasks.FarmPokestopsTask.<Execute>d__1.MoveNext() dans c:\projects\necrobot2\PoGo.NecroBot.Logic\Tasks\FarmPokestopsTask.cs:ligne 60
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   à PoGo.NecroBot.Logic.State.FarmState.<Execute>d__0.MoveNext() dans c:\projects\necrobot2\PoGo.NecroBot.Logic\State\FarmState.cs:ligne 49
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   à PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext() dans c:\projects\necrobot2\PoGo.NecroBot.Logic\State\StateMachine.cs:ligne 101
[19:51:45] (INFO) Connexion via Google
[19:51:46] (ERREUR) Vos identifiants Google ou Ptc sont invalides. Echec de connexion.
[19:51:48] (ERREUR) The bot will now exit after hitting the enter key.

**Comment by kehrijksen** [comment]
I have the same error.

When I redownload the latest branch the program just crashes.

**Comment by jjskuld** [comment]
The crash is fixed in v125.

**Comment by krishnaraovs** [comment]
Yeah its a ban my 3 accounts at level 31 are banned yesterday and today, I guess it may be due to sniping or quick leveling up

**Comment by krishnaraovs** [comment]
Yeah its a ban my 3 accounts at level 31 are banned yesterday and today, I guess it may be due to sniping or quick leveling up
