### ISSUE TITLE
Log in Error ;/

### ISSUE THREAD

**Issue by kubek1** [Necrobot-Private/NecroBot#1123]
![adsad](https://cloud.githubusercontent.com/assets/26123056/23477248/a9062b30-febd-11e6-8443-ea81fa93a289.jpg)

It means that Necrobot private for pokemon go stopped working 
Can you help me?

**Comment by kehrijksen** [comment]
Same happens to me after I downloaded the latest release. Old one doesnt crash for me.

**Comment by jjskuld** [comment]
Fixed in v125. Just released now.

**Comment by kubek1** [comment]
thanks
