### ISSUE TITLE
Log In Error

### ISSUE THREAD

**Issue by SpeedSavitar** [Necrobot-Private/NecroBot#1126]
I really don't know what can I do, i already deleted the cache, extracted a new folder.
Always when i try to log in it says that the Credentials are invalid but when i try to log in on the PTC Site is works normally...
And the other error continues the same, what can i do to solve both ones?
![error](https://cloud.githubusercontent.com/assets/26119318/23481415/05b6aa76-feaa-11e6-9265-73f13e51dca2.png)
![Uploading Error 2.png…]()

**Comment by samuraitruong** [comment]
Delete cache folder
