### ISSUE TITLE
8.9.8.9 PokeEase does not refresh player position on a map for GoogleWalk,

### ISSUE THREAD

**Issue by BoydTM** [Necrobot-Private/NecroBot#113]
In case of Mapzen works correctly ...

**Comment by LobsterX** [comment]
GoogleWalk - PokeEase/Visualizer player tracking not moving

Mapzen - PokeEase/Visualizer player tracking working fine....

**Comment by jjskuld** [comment]
@BoydTM Thanks for the report.  Found the bug and will make a fix for it asap.

**Comment by jjskuld** [comment]
Dup of #111

**Comment by jjskuld** [comment]
Fixed in next release - v0.9.9.0

**Comment by wilsondgonzales** [comment]
@jjskuld in regards to mapzen. I got an API key.

- do i need to enable mapzenwalk to be able to use the elevation api?
- If I place a mapzen key in the elevations but have it disabled while google is enabled. does the bot fallback to mapzen elevation when google craps out?

thanks
