### ISSUE TITLE
[Feature] Evolution when lucky Egg is active

### ISSUE THREAD

**Issue by ziomber** [Necrobot-Private/NecroBot#1137]
I've in setup:
    "UseLuckyEggConstantly": false,
    "UseLuckyEggsMinPokemonAmount": 70,
    "UseLuckyEggsWhileEvolving": true,
    "EvolveAllPokemonWithEnoughCandy": true,
    "EvolveKeptPokemonsAtStorageUsagePercentage": 90.0,
and everything is just fine, pokemons are stored untill 70 evelution and 90% are true. 
But after that when lucky egg is on and all evolutions are done better would be to any next evolution untill lucky egg is on were done immediatelly, without waiting for next 90% of capacity

**Comment by jjskuld** [comment]
Yes I suppose we should change it so that if lucky egg is active it should just evolve as fast as it can.

**Comment by jjskuld** [comment]
In the meantime, what you can do is set MinCandiesBeforeEvolve to a high value like 900. It keep transferring to keep your inventory clear until you save up to 900 candies before evolving.

```
"PokemonEvolveFilter": {
    "Pidgey": {
      "MinIV": 0.0,
      "MinLV": 0.0,
      "MinCP": 0.0,
      "Moves": [],
      "Operator": "or",
      "EvolveTo": "",
      "AffectToPokemons": null,
      "FavoritedOnly": false,
      "MinCandiesBeforeEvolve": 900
    },
```

**Comment by hardknoxni69a** [comment]
i think this is what we talked about before how after lucky egg is used for evolutions with the time that is left over to evolve once an evolution is available definitely a good idea

**Comment by hardknoxni69a** [comment]
gonna open an issue specifying exactly how this can be done
