### ISSUE TITLE
Evolve button in WIN

### ISSUE THREAD

**Issue by SLASHLogin** [Necrobot-Private/NecroBot#1140]
Button should be greyed when evoluton is impossible, but it's still white. Only grey when we can't evolve to higher evolution.
![przechwytywanie3](https://cloud.githubusercontent.com/assets/24846525/23518791/ee22cb94-ff74-11e6-88ca-b31c8410953a.png)

**Comment by samuraitruong** [comment]
There is wrong check for candy. fixed now
