### ISSUE TITLE
Request) Clone Search&Filter From Pokemon Inventory To Snipe List

### ISSUE THREAD

**Issue by krishnaraovs** [Necrobot-Private/NecroBot#1143]
Is there a way to keep filter of which kind of pokemons to be appear in snipe list. I didn't found any setting. 

If its not available then please add setting like this so that we can only set filter on required pokemons rather than choosing in between among the list.

Looking for the following enhancements:
1) Filter for Snipe list
2) Snipe list clear button or clear snipe list after an interval
3) Automatically remove the pokemon from snipe list after it has been successfully sniped
4) Re-enable snipe button if the pokemon missed
5) Remove pokemons from snipe list when remaining time is < 5 or 0 seconds

**Comment by hardknoxni69a** [comment]
Attaching #885 To Condense Enhancements

**Comment by hardknoxni69a** [comment]
truong is working on this hopefully released soon

**Comment by Lord-Haji** [comment]
No longer needed
