### ISSUE TITLE
Constant retrying on single gym

### ISSUE THREAD

**Issue by nhumber** [Necrobot-Private/NecroBot#1146]
@ziomber new battle configurations are working great, choosing an attack team of 2000cp seems to work fairly well for gaining decent prestige when training friendly gyms, what i dont like is that it will retry on said gym over and over and over again until its max prestige, can we get an adjustable max battle retry on same gym before moving on, so if we visit a gym, it will battle "x" amount of times then move to the next target.?

great work as always.

**Comment by Riccardo75** [comment]
how do you fill them in in the cfg?

**Comment by ziomber** [comment]
I've lost my char (another one banned) so i need some time to make new one to tests. It should be easy to code.

**Comment by nhumber** [comment]
@ziomber isnt Visit timeout doing that? i would like to make it so i can select how many times it battles gym A before heading off to another one but still obey Visit timeout. 

20 battles with 3 minute delay between each is along time, i feel the bot will be more efficient if i can limit it to a say 5 battles on Gym A and then move onto Gym B.

i realize you can set min points to train but i like keeping that one high at 10000 so the bot will push gyms to lvl 10, but not spend hours and hours trying to do it alone.

**Comment by ziomber** [comment]
@nhumber y, i'm on discord with the same nick as here. Sometimes long, sometimes for a few minutes...

**Comment by hardknoxni69a** [comment]
implemented
