### ISSUE TITLE
Any idea about .37 and SafetyNet emulation on PC?

### ISSUE THREAD

**Issue by ValorRed** [Necrobot-Private/NecroBot#115]
I feel anxious. Will this mean the end of bot soon?

**Comment by Silph-Road** [comment]
Yes for now.... .37 not released yet and when it does we will deactivate bot to protect user accounts, as we cannot tell when they will activate new API and force app updates.

**Comment by ValorRed** [comment]
You mean there is no emulation for SafetyNet?

**Comment by Silph-Road** [comment]
Nope safety net checks for root. Root is required to MITM data to decode API. Most if not all emulators are rooted. So emulators won't work.

**Comment by ValorRed** [comment]
Found this:
https://www.reddit.com/r/pokemongodev/comments/52hfcl/opinion_how_safetynet_will_kill_apis_and_possible/?st=it1thztg&sh=88954f25
It seems "3.1.2) Xposed in memory" is a possible for PC.
Anyways, I think it is more infrastructure, out of the Bot's scope. Hope you guys can keep the bot code warm. In case the API is ready we can open again.
