### ISSUE TITLE
Request) Switch To Allow Snipes To Bypass PokeMonNotToCatch List

### ISSUE THREAD

**Issue by hardknoxni69a** [Necrobot-Private/NecroBot#1153]
Before i was able to add pokeimon i wanted to catch locally to the snipe list and it would only catch those locally and if a 100iv came up on snipe list it would still catch it but with the new way of using pokemonnottocatch even if a 100iv version comes up it wont allow to catch it can we have a switch in the snipe section to allow bypassing the not catch list for sniping

**Comment by SoccerCore11** [comment]
+1
Would like to be able to manually snipe pokemon that are in the ignore list.

**Comment by hardknoxni69a** [comment]
we could take the old pokemontosnipelist and rename to pokemontocatchlist and rename the config usepokemontosnipelist to usepokemontocatchlist and will make things much easier the main reason we got rid of that section was people kept confusing its use but if we rename we could bring it back and solve 2 problems

**Comment by hardknoxni69a** [comment]
because the code is still there would be very easy to implement
