### ISSUE TITLE
Cant snipe MrMime and Farfetchd and the program crashes when trying to add/remove them to/from the catch filter.

### ISSUE THREAD

**Issue by J0KERishy** [Necrobot-Private/NecroBot#1154]
When trying to snipe either MrMime or Farfetchd the console says that the pokemon doesn't meet the criterias and skips it. When adding them to the catch list the bot crashes

**Comment by RoskamiesX** [comment]
Are they listed under PokemonsToIgnore?

**Comment by samuraitruong** [comment]
crash because you enter wrong name. it should be mrmine and Farfetchd
