### ISSUE TITLE
Chrome.elf.dll is missing

### ISSUE THREAD

**Issue by LimitedOC** [Necrobot-Private/NecroBot#1155]
### Actual Behavior: the problem is that sometimes i have crash on google chrome, when a captcha pops up it gives me the error that chrome.elf.dll is missing and i have to reinstall it.  i tried anything to fix that for good but the only thing that works best is 1)uninstall chrome 2)restart computer 3)install chrome 4)open the bot. and then it works for some times when captcha comes on but again after that it wont be worked. any1 have the same problem? i also had the same problems with 5 previous versions of necrobot

Windows Version: 10
What is affected (catch, transfer, favorite, GPX, evolve, recycle, snipe, human walk snipe, pokestops, powerup/levelup, other): Nothing from above

**Comment by samuraitruong** [comment]
look weird, have you run chrome.exe 1 time?

**Comment by LimitedOC** [comment]
Of course I have done anything you can think for it even watching videos and trying to put that file but it's not working. Only resolve captcha from mobile and log again to the bot after a restart. I will solve the next 2 maybe captchas from bot and then I get error again

**Comment by samuraitruong** [comment]
what is your window OS?

**Comment by LimitedOC** [comment]
what do you mean with windows os? plus i now saw that my folder with the bot havent auto updated to 31 it still to 28, i downloaded the new version of it from here and i puted my config json to the new and its too slow from my previous bot

**Comment by LimitedOC** [comment]
never mind its not that slow its working fine, the problem is still the chrome.elf.dll and i think it might has to do with the chromedriver.exe that works inside the bot

**Comment by samuraitruong** [comment]
the dll is nothing to do with our bot, it is chrome version install on your pC that why I ask for . chrome driver is running outside that bot ask the driver technique . you need to investigate your PC why it delete that dll or why it missing. My laptop is 5 year old, I can open up to 20 -30 GUI instance without laggy.
