### ISSUE TITLE
matters on priority of snipepokemonfilter

### ISSUE THREAD

**Issue by ning1002** [Necrobot-Private/NecroBot#1168]
## Stop! Before you create this issue (you can delete this section when opening the issue):
1. Have you searched to see if there are other Open/Closed issues for the same issue? If so, comment on that issue instead.
2. Have you validated that your config/auth.json and config/config.json is valid JSON? Use http://jsonlint.com/ to check.
3. If your question is referring to how to set up or use the bot, please join our discord instead of posting an issue: https://discord.gg/7FWyWVp 
4. Always confirm that your issue is reproducible, with the config you provide below.

### Expected Behavior:
priority with lower number should get caught more often

### Actual Behavior:
there is no difference with priority of 10 and 1

### Your config.json:
```
  "SnipePokemonFilter": {
    "Pidgey": {
      "SnipeIV": 0,
      "Moves": null,
      "Operator": "and",
      "VerifiedOnly": true,
      "Priority": 5,
      "AutoSnipeCandy": 0,
      "Level": 0,
      "AllowMultiAccountSnipe": false,
      "AffectToPokemons": []
    },
    "Pidgeotto": {
      "SnipeIV": 80,
      "Moves": null,
      "Operator": "and",
      "VerifiedOnly": true,
      "Priority": 10,
      "AutoSnipeCandy": 300,
      "Level": 20,
      "AllowMultiAccountSnipe": false,
      "AffectToPokemons": []
    },
    "Pidgeot": {
      "SnipeIV": 80,
      "Moves": null,
      "Operator": "and",
      "VerifiedOnly": true,
      "Priority": 1,
      "AutoSnipeCandy": 900,
      "Level": 20,
      "AllowMultiAccountSnipe": false,
      "AffectToPokemons": []
    },

```
### Detailed Steps to Reproduce:
not only used that config above, but I tried to modify in many ways, still it led no difference.
I wonder if it is valid option to use it or how it works...

### Other Information
with that config, it mostly catches pidgeotto and some pidgeys untill 300 candies, but when i see the autosnipe list, i could also see some pidgeots as well. though seems like it just follows the order on autosnipe list, no matter what their priorities are.

Version:
Windows Version:
What is affected (catch, transfer, favorite, GPX, evolve, recycle, snipe, human walk snipe, pokestops, powerup/levelup, other):

**Comment by samuraitruong** [comment]
because you set pidgey 1, pidgey are 1000 per min so it took all priority place

**Comment by ning1002** [comment]
i set pidgey 5 and pidgeot 1 and pidgeotto 10
and it catches pidgeotto a lot
