### ISSUE TITLE
how do i use? QUESTION

### ISSUE THREAD

**Issue by ellywenz** [Necrobot-Private/NecroBot#117]
how do i use:
1.
"GoogleElevationAPIKey": null

2.
  "MapzenWalkConfig": {
    "UseMapzenWalk": false,
    "MapzenTurnByTurnApiKey": null,
    "MapzenWalkHeuristic": "bicycle",
    "MapzenElevationApiKey": null
  },

sorry for the noob question tho

thanks!

**Comment by wilsondgonzales** [comment]
1.  https://developers.google.com/maps/documentation/elevation/start#get-a-key

you'll need to set that up and get an api key

2. go to mapzen and get an api key
mapzen is pretty straight forward

**Comment by jjskuld** [comment]
For Mapzen you need to get 2 separate keys: 1) Turn by turn api (```MapzenTurnByTurnApiKey ```) and 2) Elevation api (```MapzenElevationApiKey```).
