### ISSUE TITLE
Avoid ban

### ISSUE THREAD

**Issue by garette1** [Necrobot-Private/NecroBot#1173]
how can i avoid permanent ban, any advice??? im using 0.45 api key.i have one account.not use multi-bot.

**Comment by andeomontenegro** [comment]
advice 1: buy bossland api
advice 2: use multobit ~20 accounts. 
advice 3: dont make more than 100k exp per day

**Comment by garette1** [comment]
@andeomontenegro i cant buy now :/ anything ? :(

**Comment by andeomontenegro** [comment]
no chance

**Comment by jjskuld** [comment]
0.45 = 100% auto flag for ban. May not be right away ban, but sooner or later.
