### ISSUE TITLE
HELP! Gym Battle Configuration.

### ISSUE THREAD

**Issue by kampfie** [Necrobot-Private/NecroBot#1174]
Just wanted to know if my config for gym battles are fine. Been trying to do gym battles but it always just says:

[20:04:33] (GYM) Visited  Gym : Water Tower | Team Red  | Gym points 2000

and then moves on to the next pokestop

Here's my config:

    "Enable": true,
    "PrioritizeGymOverPokestop": true,
    "MaxDistance": 300.0,
    "DefaultTeam": "Blue",
    "MaxCPToDeploy": 1800,
    "MaxLevelToDeploy": 16,
    "VisitTimeout": 60,
    "UseRandomPokemon": false,
    "NumberOfTopPokemonToBeExcluded": 10,
    "CollectCoinAfterDeployed": 1,
    "EnableAttackGym": true,
    "MaxGymLevelToAttack": 3,
    "MaxDefendersToAttack": 3,
    "HealDefendersBeforeApplyToGym": true,
    "DontAttackAfterCoinsLimitReached": true,
    "EnableGymTraining": true,
    "TrainGymWhenMissingMaxPoints": 1000,
    "MaxGymLvlToTrain": 4,
    "TrainAlreadyDefendedGym": true,
    "MinCpToUseInAttack": 1800,
    "ButNotLessThanDefenderPercent": 0.75,
    "UsePokemonToAttackOnlyByCp": true,

Any help would be appreciated.

**Comment by andeomontenegro** [comment]
"DontAttackAfterCoinsLimitReached": true,

already collected?

**Comment by kampfie** [comment]
Yeah, for one other gym.

Should I not have done that?

**Comment by hardknoxni69a** [comment]
It's good you can adjust the settings just go through each line for u want it exactly the config is your friend. Try doing our discord for basic questions it's on our wiki and we always have people there happy to help in here is more for issues and problems

**Comment by hardknoxni69a** [comment]
If u have it to only.do 1gym then collect it's not gonna do another gym for 21 hours just go over each line and set exactly how u want it because the bot will only do what u set it for
