### ISSUE TITLE
i need help for set  autotrade

### ISSUE THREAD

**Issue by volksboyzz** [Necrobot-Private/NecroBot#1176]
i cant c9nfig my auto trade config can you help me

**Comment by hardknoxni69a** [comment]
please join our discord `and check out necrobot2.com or wiki for basic assistance but your transferfilter is where you can get more detailed but the basic keepmin in pokemonconfig controls what u will keep or u can adjust for each in the transfer fitlers which is more recommended but come to the discord as there is always a ton of people to help with the basic stuff but the wiki and website has the info you are looking for
