### ISSUE TITLE
i need help

### ISSUE THREAD

**Issue by volksboyzz** [Necrobot-Private/NecroBot#1178]
i need help for start system autotransfere pokemon for config that

**Comment by hardknoxni69a** [comment]
In our wiki and necrobot2.com there is info on setting up autotransformer we also have our discord chat in wiki for basic questions there is always members willing to help with basic question. But the transferfilters is what sets each individual Pokemon or the basic keepmin in the Pokemon config section of the config.json is for global that aren't set using transferfilters I recommend going over each line of config for maximum use and safety u wouldn't want to autotransfer ur favorite pokemon
