### ISSUE TITLE
Google Authenication error

### ISSUE THREAD

**Issue by DraxDaMC** [Necrobot-Private/NecroBot#1179]
[10:58:43] (UPDATE) Perfect! You already have the newest Version 1.0.0.132
[10:58:43] (INFO) Logging in using Google "DraxDaMC"
[10:58:44] (INFO) Your IP is: xxx.xxx.xx.xxx
[10:58:45] (ERROR) Google returned an error message: 'BadAuthentication'

I have followed various videos and without fail my account always come up with this error! how do i fix it? (I am not exactly sure what info you need so here is the bulk.... haha

  "AuthConfig": {
    "AuthType": "google",
    "Username": "DraxDaMC",
    "Password": "***********"
  },
  "ProxyConfig": {
    "UseProxy": false,
    "UseProxyHost": null,
    "UseProxyPort": null,
    "UseProxyAuthentication": false,
    "UseProxyUsername": null,
    "UseProxyPassword": null
  },
  "DeviceConfig": {
    "DevicePlatform": "ios",
    "DevicePackageName": "custom",
    "DeviceId": "974d1854eb4682033d2bed211ea20986",
    "AndroidBoardName": null,
    "AndroidBootloader": null,
    "DeviceBrand": "Apple",
    "DeviceModel": "iPhone",
    "DeviceModelIdentifier": null,
    "DeviceModelBoot": "iPhone7,2",
    "HardwareManufacturer": "Apple",
    "HardwareModel": "N61AP",
    "FirmwareBrand": "iPhone OS",
    "FirmwareTags": null,
    "FirmwareType": "9.3.3",
    "FirmwareFingerprint": null
  },
  "APIConfig": {
    "UsePogoDevAPI": false,
    "AuthAPIKey": "",
    "UseLegacyAPI": true,
    "DiplayHashServerLog": true
  },
  "AllowMultipleBot": false,
  "Bots": []
}

### Your config.json:
```
replace this text with the contents of your config.json

```

### (OPTIONAL) Your Log:
```
replace this text with only the "relative" portion of your log. (Remove unnessary lines)

```

### Other Information
(Attach zip files if needed.)

Version:
Windows Version:
What is affected (catch, transfer, favorite, GPX, evolve, recycle, snipe, human walk snipe, pokestops, powerup/levelup, other):

**Comment by yayahai** [comment]
If you have enabled 2 step verification for your Google account you will need to login using your app password.

**Comment by hardknoxni69a** [comment]
try trying your password then change it back if you would like this is a problem with google security itself not necrobot

**Comment by hardknoxni69a** [comment]
editing google settings will fix it
