### ISSUE TITLE
0.9.9.0 There are 2 (INFO) about Traveling to Pokestop

### ISSUE THREAD

**Issue by ValorRed** [Necrobot-Private/NecroBot#118]
![image](https://cloud.githubusercontent.com/assets/20829876/18486355/d3351120-79be-11e6-8f8e-cf1c1a364b53.png)

A small bug? Is the first number direct walk, while the 2nd is the real "route Google Walk"?

**Comment by ajns73** [comment]
Duplicate of #114

**Comment by jjskuld** [comment]
Track this in #114.
