### ISSUE TITLE
version 133 not executing in windows 7

### ISSUE THREAD

**Issue by yayahai** [Necrobot-Private/NecroBot#1181]
In version 127 auto update window is shown but the console is not downloaded. So I manually downloaded v133 and extracted it. Since then this is shown when i execute both console or gui-
![necrobot](https://cloud.githubusercontent.com/assets/25970667/23598872/445c2f3c-0263-11e7-85ad-0cf89a84cc4b.jpg)

**Comment by hardknoxni69a** [comment]
we are using 64 bit now until we get down to the bottom of the issue with virus i can send you a 32 bit version if you would like

**Comment by yayahai** [comment]
That would be nice. Thanks

**Comment by yayahai** [comment]
Just auto updated . Still the same issue. It seems more of a windows 7 issue rather than the 32 or 64 bit one. Suggestions?

**Comment by hardknoxni69a** [comment]
ya we just recently switched to 64 bit if u read the warning it says its because of the architecture but heres a backup of latest http://www.filedropper.com/necrobot2win32bit

**Comment by yayahai** [comment]
Thanks. Hopefully this works

**Comment by yayahai** [comment]
Thanks, this is indeed working 👍
