### ISSUE TITLE
GUI Performance

### ISSUE THREAD

**Issue by LimitedOC** [Necrobot-Private/NecroBot#1185]
can someone tell me how i could setup my GUI visualiser on my necrobot? am using the V2 nicely and i could like to know how to set up my GUI because its performance its not this good, its too laggy and after some seconds it stucks a lot. my pc its 3yo and i can play many games as dota 2 planetside 2 smite etc without lags, am like 8GBs ram and i think thats not normal, maybe am doin something wrong. feel free to tell me which part of my config you need to see or anything else to help me, thanks a lot

**Comment by hardknoxni69a** [comment]
please try using necrobot.win as this is being actively maintained and made for best performance the GUI is part of app now

**Comment by LimitedOC** [comment]
dude thanks you saved me, its really working pretty well and you can do much more things in this way!! thanks i will donate for sure

**Comment by hardknoxni69a** [comment]
I'm glad to help. Supporting necrobot is always appreciated as these guys are pushing the greatest updates pretty much daily and we need to fuel them lol. You can see a donate tab on top of the new GUI I know I never want to lose necrobot as it's superior to all bots out there and donations go a long way. Remember play safe the config is your friend be realistic
