### ISSUE TITLE
necrobot is not working on my 32bit desktop

### ISSUE THREAD

**Issue by 007darklord007** [Necrobot-Private/NecroBot#1188]
i downloaded the latest version of necrobot (necrobot2v1.0.0.133) and when i tried to start it an error message poped up saying :
 "The version of this file is not compatible with the version of windows you are running.Check your computer's system information to see whether you need an x86(32-bit) or x64(64-bit) version of the program, and then contact the software publisher."
My pc is a 32 bit windows 7 desktop

**Comment by mboeder** [comment]
same here :-(

**Comment by jjskuld** [comment]
32bit is disabled for now temporarily. Stay tuned.

**Comment by yayahai** [comment]
Here is the backup of the latest version for 32 bit windows -
http://www.filedropper.com/necrobot2win32bit
Enjoy

Credit- hardknoxni69a

**Comment by 007darklord007** [comment]
thank you :)

**Comment by mboeder** [comment]
@hardknoxni69a will 32 BIT systems no longer be supported /enhanced? Do i have to deactivate auto update ?

**Comment by hardknoxni69a** [comment]
If you are using 32 bit os you can disable for now. 32bit will return once
we come up with a new way to push uploads securely. please contact
me.through discord and will.happily provide you with a 32bit version when
we have updates sorry but safety first and 64bit is safest right now also
try updating system to 64bit as it is latest architecture and pretty much
all.pc now a days support it

**Comment by jalanjalanjalan** [comment]
is there any update for 32 bit users?

**Comment by hardknoxni69a** [comment]
I'm sorry not at at the moment please see if your system is compatible with 64 bit and u might be able to just switch your OS once we resolve the issue it will be released again try contacting me on our github and I'll send u a 32bit version for now as after about 24 hours I had to take down our 32bit releasw
