### ISSUE TITLE
[Suggestion] Queue to manage time intervals for commands from GUI

### ISSUE THREAD

**Issue by BoydTM** [Necrobot-Private/NecroBot#119]
Evolution or transfer may be already managed via GUI(pokeease), but it would be a great to maintain time intervals (delays) between all the actions (also for the ones from GUI)

**Comment by samuraitruong** [comment]
I implement the way to manage it already. but in difference approach to make sure the API call not overlap together. in my case it max upgrade a pokemon which require 2 mins.

**Comment by BoydTM** [comment]
From the log side (sometimes) it looks like 2 actions happening in the same time. What would be the best workaround for that ? Pause Break on console when calling some action from GUI ?

**Comment by BoydTM** [comment]
In my opinion usage of this in current form is pointless (obvious time collisions - easy to detect)
Sample: evolution & spin pokestop during the same second !

[08:33:42] (EVOLVED) Eevee successfully for 500xp
[08:33:42] (POKESTOP) Name: Alcatraz Landing XP: 50, Gems: 0, Items: 1 x ItemUltraBall, 1 x ItemRazzBerry, 1 x ItemPokeBall, Lat: 37.806363, Long: -122.404655, Alt: 4.21502566720127
![necerror 5](https://cloud.githubusercontent.com/assets/21159620/18613440/48d3a40e-7d7b-11e6-830b-8b83d1b6a10e.jpg)
