### ISSUE TITLE
[Suggestion] Any plan to switch to PokeGOAPI-Java by Grover-c13?

### ISSUE THREAD

**Issue by vfuyong** [Necrobot-Private/NecroBot#12]
As PokeGOAPI-Java seems to be actively updated, does it make sense to switch to it and invoke it in runtime? e.g. using Jni4net.

https://github.com/Grover-c13/PokeGOAPI-Java

It is always good to leverage community projects.

**Comment by Silph-Road** [comment]
Yes, it is in the works.
If you are a developer with experience porting other languages to C#, contact us here and post link to your git/repo projects.

**Comment by jjskuld** [comment]
Long term seems best solution. I think I also had mentioned it previously.  For now I am porting over the most important client emulation logic to fix up rocket API as a temporary fix so we are at less risk.

**Comment by jjskuld** [comment]
@NzV FYI the changes made in https://github.com/Necrobot-Private/PokemonGo.RocketAPI/commit/03e6e70a84334fc7f1dbe6ebf02d0a17cdbdcd3e were ported from PokeGOAPI-Java.  
Looks like you just reverted all my changes.  Curious to know why.  These changes are critical fixes to the rocket API.

**Comment by Silph-Road** [comment]
@jjskuld I am gonna mention you in a post with link to the private discord that all the devs are on. Join the chat nzv and all are there. Easier to collaborate in real time.

**Comment by NzV** [comment]
@jjskuld i revert your commit due to this error: 
Severity    Code    Description    Project    File    Line    Suppression State
Error    CS0117    'RequestType' does not contain a definition for 'DownloadSettingsMessage'    PokemonGo.RocketAPI    C:\Users\alessio.rocchi\Documents\GitHub\NecroBot-1\FeroxRev\Rpc\Login.cs    54    Active

also revert one of your commit in necrobot who break submodule.

**Comment by SiBangkotan** [comment]
For such a major change, even better to consider merging this piece of code to a MITM. No more >Unknown6< or whatever in future, as long as base proto is not totally changed.

The catch is that it will eventually require a slim and clean andro stacking, wonder if there is any.

**Comment by jjskuld** [comment]
About 95% done porting the Java API but it may be bad timing because niantic just pushed out 0.37.  Completely different protos, new captcha, and other security features will make it hard to crack.  Unknown6 is gone in 0.37 since they have switched to something else altogether.

**Comment by vfuyong** [comment]
Interesting that the old bot still works with 0.37. Just to share this finding.

**Comment by kuntau** [comment]
Of course they give their player base some grace period for upgrading before dropping the old API

**Comment by vfuyong** [comment]
@kuntau I heard pokemon go actually mandate updating to the latest client before logging in?

**Comment by kuntau** [comment]
Sure, but we don't know yet. I'm still using 0.3.5 and AFAIK iOS version still pending for apple verification

**Comment by Silph-Road** [comment]
Anyone here with android? I need someone to verify something:

trying to test if the .33 api is bait and they forced apps to .35 but left .33 api active
cuz .33 api works, 
but if they forced update, 
all those accounts are not official client as all apps are forced to .35.... easy filter to ban before new update 

If anyone with .33 APK or 1.31 IPA can test, i would appreciate it!! 



what i am trying to test if niantic is forcing:
Android .33 to update to .35 (currently the latest in app stores) before they push 0.37.0 <--- newest 
OR 
iOS 1.31 to update to 1.50 (currently the latest in app stores) before they push 1.70 <--- newest

**Comment by vfuyong** [comment]
There is some chance that the old API does work because the new features in 0.37 do not require changes to existing API.

**Comment by jjskuld** [comment]
I will bet that they will allow 0.35 to connect even after 1.70 comes out..  This is why I suggested kill switch based on checking when the App Stores release the new versions.

**Comment by Silph-Road** [comment]
yeah, they will allow for maybe a day or few hours. 
I have a scanner checking App store and will activate kill switch in 60 seconds of release.

**Comment by Silph-Road** [comment]
@vfuyong they will work until they disable .35 API from their end on the servers, like they did when they released .33 and everyone was forced to update.

**Comment by samuraitruong** [comment]
They not update api. Just update app:)) keep botting

Get Outlook for Android<https://aka.ms/ghei36>



On Tue, Sep 13, 2016 at 9:21 AM +1000, "vfuyong" <notifications@github.com<mailto:notifications@github.com>> wrote:


Interesting that the old bot still works with 0.37. Just to share this finding.

**Comment by vfuyong** [comment]
@samuraitruong May I know how you confirmed these?

**Comment by jjskuld** [comment]
Not sure why I never came across this but AeonLucid has a C# pogolib library in addition to maintaining the pogoprotos!!

https://github.com/AeonLucid/POGOLib

Seems to be actively maintained and they are striving to make it compatible with .net on multiple platforms (mac, android, etc)

I've completed almost all the Grover-c13 API porting from Java for the main classes and only have the lower level networking, sensor info, and device info code left. 

I've looked through the AeonLucid code and it looks well written.  My thinking on this is:

1. Switch out Rocket API and move to pogolib from AeonLucid.  It is much more low level than Grover-c13's code so it actually maps closer to Rocket API than the Java port.
2. Contribute back to AeonLucid the critical bug fixes that we ported into Rocket API from the main Python pogo library.
3. Contribute back to AeonLucid other missing functionality from Grover-c13 (such as iOS client emulation)
4. Contribute back to Grover-c13 the ported .net implementation of his own API for him to maintain if he so wishes.

AeonLucid library has some nice features in it like better handling of oauth token refreshes, auto map refresh, and runs on more than just windows platform.

The change to Grover-c13 port can be done incrementally once we've got pogolib in.

**Comment by jjskuld** [comment]
Of course this is assuming that niantic doesn't force 0.35 update any time soon.

**Comment by holmeschou** [comment]
I also think it is a good idea to use pogolib. POGOLib keeps update.

**Comment by samuraitruong** [comment]
Closed, We will maintain our rocket API keep it sync with Pogolib and any update comming
