### ISSUE TITLE
Run over MaxDistance

### ISSUE THREAD

**Issue by JakeCube** [Necrobot-Private/NecroBot#120]
i had set my "MaxTravelDistanceInMeters": 400
but every time it run out of the distance very far

i also disabled humanwalk snipe, so it won't go back default location most of the time

There is no this bug before when i using from 8 - 9.6 version.

![range](https://cloud.githubusercontent.com/assets/20925630/18486791/1d8c1294-7a25-11e6-8aee-600f264be100.PNG)

Black was the default longitude and latitude, blue was within 400 meter, and last red was outside the range.

**Comment by ajns73** [comment]
@JakeCube Did you shut the bot down and then restart at some point?

**Comment by JakeCube** [comment]
@ajns73 yes i do restart and observe this action several time

**Comment by ajns73** [comment]
@JakeCube There as discussion of this topic a while back. I don't remember exactly what was discussed, you'd have to check the closed issues. Essentially, the thought was that LastPos.ini was used to begin a new 400m track on restart. So, technically after 3 restarts you could end up 1200m from your starting location. That make sense?

**Comment by ajns73** [comment]
here #91
