### ISSUE TITLE
'This app can't run on your PC' dialogue-box

### ISSUE THREAD

**Issue by sakaba001** [Necrobot-Private/NecroBot#1202]
Can't run after updating to 133, having same problem with the version 132.
I can normally run the version 131, but since the API updated seems like it's no longer an option.

My OS Details:
OS Name: Microsoft Windows 10 Enterprise
Version: 10.0.14393 Build 14393

ACER Aspire E1-471G

**Comment by Furtif** [comment]
Dowload Microsoft Frameworks maybe

**Comment by hardknoxni69a** [comment]
necrobot is 64bit until some security concerns are adressed as safety comes first please hold on a little bit and i will attach a 32bit version for you with newest api support
