### ISSUE TITLE
"KeepMinIvPercentage": 100.0 vaildate check error

### ISSUE THREAD

**Issue by tmecwell** [Necrobot-Private/NecroBot#1205]
"PokemonsTransferFilter": {
    "Lapras": {
      "KeepMinCp": 1000,
      "KeepMinIvPercentage": 100.0,
      "KeepMinLvl": 10,
      "UseKeepMinLvl": true,

Look at this part. I don't use ///"KeepMinIvPercentage": 100.0//// It means disable.
"It means disable" ---> I want to transmit IV 100%.

During a initial loading, 101.0 can not be used as validate check error. Plz correct it if time permits.

ex) "MinIVForAutoSnipe": 101, <==== !!!!!!

 "Lapras": {
      "SnipeIV": 0,
      "Moves": [],
      "Operator": "or",
      "VerifiedOnly": false
    },
    "Dragonite": {
      "SnipeIV": 100,
      "Moves": [],
      "Operator": "or",
      "VerifiedOnly": true
    }
Method 2 : Autosnipe all pokemon then exclude those pokemon you don’t want snipe, see config below 
In this case I want to snipe all 100% pokemon and except some crabby pokemon like zubat, pidgey.

Thank you.

**Comment by hardknoxni69a** [comment]
if u want to snipe all just put snipe 100 and it will snipe all 100

**Comment by hardknoxni69a** [comment]
u set 101 if u want to disable all sniping besides what is on your filter

**Comment by tmecwell** [comment]
That's a sample. "MinIVForAutoSnipe" option uses 101, but there is no validate error. 

The important point is that when I use 101 in the "KeepMinIvPercentage": option, I can not run with a validate error.
