### ISSUE TITLE
Issue) API request type: GetPlayer

### ISSUE THREAD

**Issue by hardknoxni69a** [Necrobot-Private/NecroBot#1213]
[13:29:59] (INFO) PokemonGo.RocketAPI.Exceptions.InvalidResponseException: Error with API request type: GetPlayer 

Has Returned With New API Update. Only applies to .45 users. Hopefully you can find a workaround again

**Comment by LEE-BC** [comment]
I want to ask what updates I have.. 
There's nothing else.
Fighting~!  Necrobot

**Comment by pkmjmguillen** [comment]
same problem here. cant log in please respond necrobot!! :D

**Comment by xtonkix** [comment]
can't log in as well.

**Comment by deathclaw123** [comment]
what to do now? buy api?

**Comment by RefinedTsai** [comment]
same problem here.

**Comment by xBattlePigx** [comment]
Its giving me the same error message. I thought I got my account banned but it isn't. There's other error messages under it too. I tried deleting the program and reinstalling it and still nothing. Can anyone explain to me what is going on with the bot? Does anyone think it will be fixed or patched anytime soon? thanks.

**Comment by OrdsonX** [comment]
arghh 0.45 API is outdated, its free but its not used anymore by Pokemon Go and using it will get you 100% banned. This is the easiest way for Niantic to recognize you as a bot. Spend some $ and be more secure.

**Comment by xBattlePigx** [comment]
Do you think anyone is going to update the API so necro will be able to work again?

**Comment by DivineMint** [comment]
I get the same problem, but i have used the api key (expired 3/26).

**Comment by dimitris63** [comment]
Is there a problem with the API key or the Hash server.?

[03:59:59] (ERROR) Your API key 9U5HXXXXXXXXXXXX7M3K is incorrect or expired, please check auth.json (Pokefamer message : Unauthorized)
[03:59:59] (ATTENTION) Hash server being down, Bot will enter IDLE state until service available. Ping interval is 5 sec...

**Comment by DivineMint** [comment]
no.. The Key is correct and the hash server doesn't get error message.

**Comment by GrimmHubber** [comment]
Same here w/ latest update. Tried downgrade and... same too.

**Comment by dimitris63** [comment]
@DivineMint, if the API key is correct and the Hash server does not get messages. why does the log file from say the Hash server is down and why can't i use necro

**Comment by xBattlePigx** [comment]
I found a API key online and the bot is working fine for me now. Im not sure if its safe though.

**Comment by xBattlePigx** [comment]
2F0N1F0P0A5M5E3O1I4X﻿

**Comment by hardknoxni69a** [comment]
only applies to .45 users so feel free to get a key as it has many benefits

**Comment by cswxin** [comment]
I created a new account one month ago and bought a API key, but it still got banned when it reached Lv35 last week :(

**Comment by dimitris63** [comment]
@xBattlePigx thanks for the key, I copied the key
    "AuthAPIKey": "2F0N1F0P0A5M5E3O1I4X﻿",
and I got the below error message
[03:30:45] (INFO) System.NullReferenceException: Object reference not set to an instance of an object.

**Comment by deathclaw123** [comment]
@cswxin is it banned till now? if yes then level35 is the limit!

**Comment by LEE-BC** [comment]
We should go beyond the limit. 
But I do not see any measures coming up yesterday.
All of you.
I always cheer.

**Comment by cswxin** [comment]
@deathclaw123 yeah,it's still banned, and I have nearly 3 accounts banned with lv32~35...

**Comment by pkmjmguillen** [comment]
any update :)?

**Comment by sakaba001** [comment]
Please do not share the hash key if it ain't yours

**Comment by sakaba001** [comment]
0.45 legacy API is down, no ETA

**Comment by dimitris63** [comment]
@deathclaw123 I am currently on my 4th account. Why does Niantic wait until we get to 32 or 34 to ban us. Has anyone gotten past 35 and not been banned?
@sakaba001 is Legacy still down?

**Comment by cj3n** [comment]
I've made it to 38 on my last account before the ban wave. My new account I went to 30 then slowed down on botting, now it's 33 and got the warning from them if I don't stop their gonna ban me. About to go back to spoofing for 100 ivs

**Comment by yayahai** [comment]
Anybody getting that latest notice from Niantic about Botting. Should I refrain from it for a while. Can I GPS spoofing , or is that to dangerous.

**Comment by garette1** [comment]
i banned at lvl 28.i botting like human but get banned :(

**Comment by maxthehacker** [comment]
Guys it seems like the new API has a drastic change and the last time this happened the pokefarmer team cracked it and made us pay for the api hashing service. Hash keys will be down for 1-2 days as they may be updating them to this new API.

**Comment by hardknoxni69a** [comment]
The hashing service has been up and running guys if you want try out the
4$key and u can be botting right now

**Comment by maxthehacker** [comment]
hardknox im new to github but what exactly must i do?

**Comment by LEE-BC** [comment]
NecroBot2 v1.0.0.135  ...  Updated?
I'm really looking forward to it.
Can anyone explain?

**Comment by garette1** [comment]
still have getplyer error...

**Comment by LEE-BC** [comment]
Unfortunately, it's still a step further, right?

**Comment by hardknoxni69a** [comment]
Ya its updated but still cant use legacy if u get the getplayer try using a fresh exe

**Comment by jjskuld** [comment]
Ok, closing this out since we have disabled 0.45 API and are now showing error message if you try to use legacy api.

**Comment by LimitedOC** [comment]
Guys will we have free new API? Cuz we can't buy the key.. I could buy it with sms but this way is not exist

**Comment by hardknoxni69a** [comment]
Umm u can def buy key by following the link when setting up bot visa and
MasterCard accepted everywhere

On Mar 14, 2017 12:43 PM, "LimitedOC" <notifications@github.com> wrote:

Guys will we have free new API? Cuz we can't buy the key.. I could buy it
with sms but this way is not exist

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Necrobot-Private/NecroBot/issues/1213#issuecomment-286482864>,
or mute the thread

**Comment by LimitedOC** [comment]
I don't have any card.. I think I said that above

**Comment by LimitedOC** [comment]
Nope I didn't. I don't have PayPal or cards that's why am asking for sms

**Comment by hardknoxni69a** [comment]
Well my friend prepaid visa are at every corner store u might have to do
that you can go talk to the hashing company but I doubt they will be able
to charge a phone plan to be honest

**Comment by LimitedOC** [comment]
Its easy to have and send money to another country when you don't have capital controls on your banks. Well at my country we have

**Comment by hardknoxni69a** [comment]
The prepaid cards. Don't reslly care how u spend it though prob need 10$ cuz I think they charge like 5 for the card but then u can buy stuff from sites that what I used to do when I had no bank

**Comment by nhswork** [comment]
@xBattlePigx Where did you find the key? it was working but has expired since. Did u find a new one? 

> I found a API key online and the bot is working fine for me now. Im not sure if its safe though.

**Comment by xBattlePigx** [comment]
@nhswork I was looking on YouTube one day and noticed someone posted it in the comments. I guess I locked out with finding it I guess. So that code I have now isn't working? I haven't botted in a week because I've been on vacation. The first time I used the key that's what I thought too because it worked and was worried something was going to happen as well. I'd go on the actual game and I'd get the warning telling me they know I'm Botting and that whole scare but I haven't been banned yet. I mean I assume there's a chance of getting banned but not as much of a ban wave going around now-a-days

**Comment by nhswork** [comment]
@xBattlePigx i read elsewhere all keys have a 31 day expiration. that key was working, but must have expired now, and bot says it's expired. I get the warning message in game as well, but I've also used legacy API before, so I'm not sure if the warning came from that. Hopefully someone else will share a key soon.

**Comment by hardknoxni69a** [comment]
U guys know it's only 4$ a month then u can bot like crazy use multiple
bots off same key up to 3_4
