### ISSUE TITLE
"KeepMinIvPercentage": 101.0 vaildate check error 

### ISSUE THREAD

**Issue by tmecwell** [Necrobot-Private/NecroBot#1214]
"PokemonsTransferFilter": {
"Lapras": {
"KeepMinCp": 1000,
"KeepMinIvPercentage": 101.0,
"KeepMinLvl": 10,
"UseKeepMinLvl": true,
"KeepMinOperator": "or",

Look at this part. I don't use ///"KeepMinIvPercentage": 101.0//// """""I want to transmit IV 100%."""

During a initial loading, 101.0 can not be used as validate check error. Plz correct it if time permits.

**Comment by LEE-BC** [comment]
There was no problem with the old version.
Is the validation added?

**Comment by tmecwell** [comment]
![image](https://cloud.githubusercontent.com/assets/26264653/23695260/975bc75a-0421-11e7-837a-2667210f1d95.png)

**Comment by tmecwell** [comment]
It is my mistake. I'm sorry 101.0 -> 101

**Comment by OrdsonX** [comment]
"PokemonsTransferFilter": {
"Lapras": {
"KeepMinCp": 1000,
"KeepMinIvPercentage": 101.0, should be at 100
"KeepMinLvl": 10, should be at least 30
"UseKeepMinLvl": true, If you use minimum level
"KeepMinOperator": "or",

So with this setup every Lapras with 100IV but below level 30 will be transfered.

**Comment by xBattlePigx** [comment]
is this going to fix the error everyone is getting?

**Comment by tmecwell** [comment]
[17:13:23] () Validating config.json...
[17:13:23] () config.json [Line: 545, Position: 34]: PokemonsTransferFilter.Lapras.KeepMinIvPercentage Float 101.0 exceeds maximum value of 100.
[17:13:23] () config.json [Line: 560, Position: 34]: PokemonsTransferFilter.Umbreon.KeepMinIvPercentage Float 101.0 exceeds maximum value of 100.
[17:13:23] () config.json [Line: 575, Position: 34]: PokemonsTransferFilter.Espeon.KeepMinIvPercentage Float 101.0 exceeds maximum value of 100.
[17:13:23] () config.json [Line: 590, Position: 34]: PokemonsTransferFilter.Vaporeon.KeepMinIvPercentage Float 101.0 exceeds maximum value of 100.

**Comment by tmecwell** [comment]
sample ;;;;;;;

Method 1. Set AutoSnipeMinIV to 101 - Then bot won’t autosnipe any pokemon, you need to overwrite pokemon individual snipe filter . For example, Only want to snipe any Lapras and 100%IV Dragonite and exclude all others pokemon, below is my config

 
"MinIVForAutoSnipe": 101, <====
 
 "Lapras": {
      "SnipeIV": 0,
      "Moves": [],
      "Operator": "or",
      "VerifiedOnly": false
    },
    "Dragonite": {
      "SnipeIV": 100,
      "Moves": [],
      "Operator": "or",
      "VerifiedOnly": true
    }

no vaildate error !!

**Comment by OrdsonX** [comment]
This is not real error, first you about transfer filter abd now sniper filter. This is for serious issues, next time ask on Discord channel.

**Comment by tmecwell** [comment]
I got a problem when I transfer. during a transfering, I just want two option. So, I don't use iv 100% option, but i write 101. then I got a error; vaildate error. do you understand my sentence? plz pix it when you possible. Thank you

**Comment by tmecwell** [comment]
I think so.

This option is a local variable that is used only for transmission. It is not a global variable.

Therefore, I think that there is no reason to check the maximum value when vaildate check at the first run.

It should be decided by the user.

**Comment by kisswell** [comment]
I have a similar problem. I don't want to waste great and ultra balls, but the bot uses up the ultra balls due to this validation.
![capture](https://cloud.githubusercontent.com/assets/26290927/23733568/07f6571e-04bd-11e7-8b3e-a35cd1cd7fb5.JPG)
