### ISSUE TITLE
Problems with nickname (begging tutorial)

### ISSUE THREAD

**Issue by monis1133** [Necrobot-Private/NecroBot#1215]
Hi I have problem with nick name window(begging. Tutorial). The window appears when start the bot or when restart because server go down. I try insert all type of name but server responds "the name isn't correct try again".  How I can fix?or disable begging tutorial?

**Comment by hardknoxni69a** [comment]
The bot is just like game u can only have so many and certain characters

**Comment by monis1133** [comment]
Hi
I tried with any nickname, but he always says that is incorrect, and the bot keeps asking me the nickname

**Comment by monis1133** [comment]
Solve it thanks
