### ISSUE TITLE
Setting priority on autosnipe filter

### ISSUE THREAD

**Issue by Archy12345** [Necrobot-Private/NecroBot#1224]
when setting autosnipe filter is a lower number high priority or higher number higher priority?
    "Lapras": {
      "SnipeIV": 100,
      "Moves": [],
      "Operator": "or",
      "VerifiedOnly": true,
      "Priority": 2, <==========HERE!!!!
      "AutoSnipeCandy": 200,
      "Level": 0,
      "AllowMultiAccountSnipe": true,
      "AffectToPokemons": null
    },

**Comment by jjskuld** [comment]
Lower priority = more important
