### ISSUE TITLE
Farm for specific pokemons in the area

### ISSUE THREAD

**Issue by LobsterX** [Necrobot-Private/NecroBot#1226]
Am looking to farm specific pokemons

is there anyway to configure the bot to do that?

also it seems gen 2 pokemon names arent updated into the bot. error occurs when gen 2 pokemons names are used in filters

**Comment by hardknoxni69a** [comment]
not sure whast version your using but gen 2 has been in bot for a while if you want to catch only pokemon you can adjust your pokemonnottocatch filter and there is also a user friendly update coming for which pokemontocatchlocally
