### ISSUE TITLE
Snipe IV 100 not works!

### ISSUE THREAD

**Issue by mangonzalez00783** [Necrobot-Private/NecroBot#1229]
I config for sniping only pokemons of 100 iv but snipe all pokemons.

my config:
  "SnipeConfig": {
    "UseSnipeLocationServer": false,
    "SnipeLocationServer": "localhost",
    "SnipeLocationServerPort": 16969,
    "MinPokeballsToSnipe": 0,
    "MinPokeballsWhileSnipe": 0,
    "MinDelayBetweenSnipes": 120000,
    "SnipingScanOffset": 0.005,
    "SnipeAtPokestops": true,
    "SnipeIgnoreUnknownIv": false,
    "UseTransferIvForSnipe": false,
    "SnipePokemonNotInPokedex": false,
    "UseSnipeLimit": true,
    "SnipeRestSeconds": 600,
    "SnipeCountLimit": 10,
    "ActivateMSniper": false,
    "MinIVForAutoSnipe": 101,
    "MinLevelForAutoSnipe": 0,
    "AutosnipeVerifiedOnly": false,
    "DefaultAutoSnipeCandy": 0,
    "SnipePauseOnOutOfBallTime": 5,
    "AutoSnipeMaxDistance": 0.0,
    "AutoSnipeBatchSize": 10
  },
  "SnipePokemonFilter": {
    "Eevee": {
      "SnipeIV": 100,
      "Moves": [],
      "Operator": "or",
      "VerifiedOnly": true,
      "Priority": 1,
      "AutoSnipeCandy": 2000,
      "Level": 0,
      "AllowMultiAccountSnipe": false,
      "AffectToPokemons": null
    },
}

log:
[23:06:24] (SNIPER) (InternalSnipe) Sniping a Eevee with 82.22 IV at 55.6300530273379,12.0964623687564...

**Comment by hardknoxni69a** [comment]
u have autosnipecandy on and if u care about candy the bot is gonna catch any iv to get the candy put at 0 and bot will only snipe the 100iv

**Comment by mangonzalez00783** [comment]
Thanks man, I really did't know it was that field and I always left it by default, regards!

**Comment by hardknoxni69a** [comment]
Always happy to help
