### ISSUE TITLE
Pokefarmer key not working

### ISSUE THREAD

**Issue by islc11** [Necrobot-Private/NecroBot#1230]
I bought a key from Pokefarmer but it cannot be used in Necrobot. 

Hash key is not valid, any solution?

**Comment by hardknoxni69a** [comment]
please confirm the way you are entering info as the keys most certainly work
  "APIConfig": {
    "UsePogoDevAPI": true,
    "AuthAPIKey": "WOJFH42JH2OGJFNBOJ2424F",
    "UseLegacyAPI": false,
    "DiplayHashServerLog": true

**Comment by islc11** [comment]
I have exactly the same text.
See the error under:

Hope you can help

[21:06:21] (ERROR) Your API key 0P6JXXXXXXXXXXXX8S9L is incorrect or expired, please check auth.json (Pokefamer message : Unauthorized)
[21:06:21] (ATTENTION) Hash server being down, Bot will enter IDLE state until service available. Ping interval is 5 sec...

**Comment by hardknoxni69a** [comment]
It says your key is expired and service is down this is not an issue with the bot rather your key please purchase a new key if expired

**Comment by islc11** [comment]
The key is brand new And working on Pokefarmer bot. I prefer Necrobot so i want to use this one

Any idea?

**Comment by hardknoxni69a** [comment]
U don't want to send ur config through here because of security so go on our discord and send me ur auth and we will fix it

**Comment by macinmn** [comment]
aren't pokefarmer and pokehash two separate things (their in-house bot program vs stand-alone hashing service)?  ie. keys aren't interchangable

**Comment by hardknoxni69a** [comment]
Very true if ur trying to use the actual PF key that isn't gonna work u need the hashing key. U will.be much happier with necro
