### ISSUE TITLE
Loggin error

### ISSUE THREAD

**Issue by Lyfthrasyxxx** [Necrobot-Private/NecroBot#1232]
Everytime i open my necrobot sends me the follow msj 

[12:43:13] (INFO) PokemonGo.RocketAPI.Exceptions.InvalidResponseException: Error with API request type: GetPlayer
   en PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProtoPayload>d__1`2.MoveNext() en C:\Users\VAPORSS\Documents\NecroBot\FeroxRev\Extensions\HttpClientExtensions.cs:línea 65
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en PokemonGo.RocketAPI.Rpc.BaseRpc.<PostProtoPayload>d__4`2.MoveNext() en C:\Users\VAPORSS\Documents\NecroBot\FeroxRev\Rpc\BaseRpc.cs:línea 0
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en PokemonGo.RocketAPI.Rpc.Player.<GetPlayer>d__9.MoveNext() en C:\Users\VAPORSS\Documents\NecroBot\FeroxRev\Rpc\Player.cs:línea 141
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en PokemonGo.RocketAPI.Rpc.Login.<DoLogin>d__10.MoveNext() en C:\Users\VAPORSS\Documents\NecroBot\FeroxRev\Rpc\Login.cs:línea 172
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   en PoGo.NecroBot.Logic.State.LoginState.<Execute>d__3.MoveNext()

And i can't use it, help me please.

**Comment by garette1** [comment]
@Lyfthrasyxxx  legacyAPI was disabled. we have to wait

**Comment by hardknoxni69a** [comment]
please read announcements in discord for updates
