### ISSUE TITLE
Alert from Niantic

### ISSUE THREAD

**Issue by LimitedOC** [Necrobot-Private/NecroBot#1235]
everytime i open my game from mobile phone i get this message: 

We have detected activity on your account that suggests you or someone accessing your account are using modified client software or unauthorized third party software which accesses Pokemon GO in violation of our Terms of Service. Please be aware that the use of such software can result in the loss of your account. If you have been using such software, we strongly encourage you to stop. 

so what would you do in my possition? use the bot with legacy API? (i cant buy cuz i dont have paypal) stop permanantly the use of the bot? remake the config?

**Comment by garette1** [comment]
you can buy with credit card.

**Comment by hardknoxni69a** [comment]
i mean if your using legacy api thats a reason to get warning and using your config may be the issue so i would do both buy a key to use latest api and adjust config to be more safe but not all users are getting this so has to do with your personal set up

**Comment by yayahai** [comment]
I use a hash service API, but still got this message. Any suggestions as to what not to do to avoid ban.

**Comment by LimitedOC** [comment]
True, I think ill stop using it for some time and I'll feed another account until the message is gone and then I will use bot on main again

**Comment by hardknoxni69a** [comment]
Honestly my best opinion would be to simply go over your config and adjust to be more realistic literally go over every line necro has the most configurations out of any bot if you take advantage of them all u will be golden
