### ISSUE TITLE
Bot does not use unique identification/UDID

### ISSUE THREAD

**Issue by maxthehacker** [Necrobot-Private/NecroBot#1236]
"DataSharingConfig": {
    "EnableSyncData": true,
    "AutoSnipe": true,
    "DataServiceIdentification": "af297103-b3a6-4e8c-9c66-f9242e0ced5c", ==> When i type this ID in msniper web app it doest recognize my bot
    "SnipeDataAccessKey": "",
    "EnableFailoverDataServers": true,
    "FailoverDataServers": "ws://s1.mypogosnipers.com/socket.io/?EIO=3&transport=websocket;ws://s2.mypogosnipers.com/socket.io/?EIO=3&transport=websocket",
    "DataRecieverURL": "ws://necrosocket.herokuapp.com/socket.io/?EIO=3&transport=websocket"

Also im new to github so please mind my noobiness

**Comment by hardknoxni69a** [comment]
im sorry but msniper is completely different app your ID is to use websniping through our websniping site

**Comment by hardknoxni69a** [comment]
i thought something was broken or something but i literaly just tested and successfully sent a snipe to my bot please check out wiki and necrobot2.com or our discord for basic usage questions Ya MSniper is no longer being maintained by any of the developers here and they even had there own website
