### ISSUE TITLE
Multi Account Anomoly

### ISSUE THREAD

**Issue by jaemus** [Necrobot-Private/NecroBot#1237]
### Expected Behavior:
Bot to follow all rules when catching/sniping

### Actual Behavior:
all accounts behave properly except 1 anomoly account. am attaching log file where anomoly can be seen at the end of the log.
[NecroBot2-2017-03-09-11-34-05.txt](https://github.com/Necrobot-Private/NecroBot/files/835530/NecroBot2-2017-03-09-11-34-05.txt)

### Your config.json:
```
replace this text with the contents of your config.json

```

### (OPTIONAL) Your Log:
```
replace this text with only the "relative" portion of your log. (Remove unnessary lines)

```

### Other Information
(Attach zip files if needed.)

Version:
Windows Version:
What is affected (catch, transfer, favorite, GPX, evolve, recycle, snipe, human walk snipe, pokestops, powerup/levelup, other):

**Comment by hardknoxni69a** [comment]
your out of balls you need to set a delay to allow your bot to go and loot stops instead of trying to catch over and over without balls

**Comment by jaemus** [comment]
I have. Timer is set to 20 minutes. All other accounts follow the rules
set. Just that 1 account that keeps trying to catch reguardless.

On 12 Mar. 2017 17:00, "hardknoxni69a" <notifications@github.com> wrote:

your out of balls you need to set a delay to allow your bot to go and loot
stops instead of trying to catch over and over without balls

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Necrobot-Private/NecroBot/issues/1237#issuecomment-285926661>,
or mute the thread

**Comment by hardknoxni69a** [comment]
We fixed on discord
