### ISSUE TITLE
v0.9.9.1 use API 0.37.0?

### ISSUE THREAD

**Issue by tuxfrw** [Necrobot-Private/NecroBot#125]
Hi,

This version is already using the new API 0.37.0?

thx for your jobs!

**Comment by Silph-Road** [comment]
Nope not yet

**Comment by tuxfrw** [comment]
Ah OK thx!! :D

**Comment by GamerHacker96** [comment]
Is it 0.9.9.2 now using the newest api ?

**Comment by moonpyk** [comment]
@GamerHacker96 still nope
