### ISSUE TITLE
Endless battle exp farm

### ISSUE THREAD

**Issue by mura1q** [Necrobot-Private/NecroBot#1252]
Can we make an endless battle mod? It will give around 150k exp/h with no limits. I know that battle is in beta, but I think it is a highly important feature. 
I don't want to promote anything, but I share the link with a guide (http://pokebot.ninja/thread-4426-post-15207.html#pid15207). It would be really awesome if necro2 could do this. 
Thanks

**Comment by jjskuld** [comment]
@mura1q Will look into this. Thanks!
