### ISSUE TITLE
i cannot log in in necrobot console or win

### ISSUE THREAD

**Issue by blackmamba0024** [Necrobot-Private/NecroBot#1253]
is necrobot is down..
i cannot log in my account or use the necrobot..
i downloaded the latest version both win and console..
pls answer me pls..

**Comment by andeomontenegro** [comment]
ban?)

**Comment by blackmamba0024** [comment]
nope..
i can log in in poke ninja or pogo app in my phone

i want necrobot it is better than any bot..

**Comment by Nigromante2004** [comment]
I cant loggin also. I cant loggin in all accounts that i have. I dont know why.

**Comment by jshill103** [comment]
I have the same problem.

**Comment by blackmamba0024** [comment]
same here.. i log in my one acc to console but after i close it icannot log in any of my account..

**Comment by jjskuld** [comment]
Need logs or else I can't help

**Comment by lazaropower** [comment]
I have the same problem.

**Comment by jjskuld** [comment]
@lazaropower go to Logs directory and copy and paste the latest log here

**Comment by jjskuld** [comment]
BTW, if you are using 0.45 API, it has been disabled by Niantic and you won't be able to log in. You need to buy hash key from Bossland now.

**Comment by garette1** [comment]
@jjskuld where can i do safe shopping? buy bossland API on trust?

**Comment by jjskuld** [comment]
https://talk.pogodev.org/d/51-api-hashing-service-by-pokefarmer

**Comment by lazaropower** [comment]
@jjskuld Yes, I'm using 0.45 API. Okey, I'll see the keys, thanks.

**Comment by jjskuld** [comment]
I'm guessing most of these are 0.45 API users. Closing this for now.
