### ISSUE TITLE
Bot always starts at the default location

### ISSUE THREAD

**Issue by mattcall** [Necrobot-Private/NecroBot#1256]
When I start the bot it always starts at the default location and not the last location.
While in the config startfromlastlocation is set true.
I'm using the latest WIN version.

Anyone else experiencing this?

**Comment by macinmn** [comment]
single or multi?

**Comment by mattcall** [comment]
I run a single bot on my system

**Comment by Lord-Haji** [comment]
@mattcall delete temp files. that should work in the mean time
