### ISSUE TITLE
Request) Configurable Random Run Times

### ISSUE THREAD

**Issue by mangonzalez00783** [Necrobot-Private/NecroBot#1258]
Some way to make the bot close the session for a defined time (configurable) and reconnect. I believe that this would serve to give a more real behavior and not that you remain hours running.

**Comment by hardknoxni69a** [comment]
Have A Setting Where You Can Have Bot Login For Say 2 Hours (Random % Time) Then LogOut For Say 2 Hours(Random % Time) As Well So Bot Will Play For 1Hr50Min Then Log Out For 2Hr5Min Then In For 2Hr10Min Out For 1Hr49Min And So On Would Be Pretty Nice

**Comment by macinmn** [comment]
you can schedule and kill executables via Windows Task Scheduler

**Comment by mangonzalez00783** [comment]
Yes, but in the Windows Task Scheduler it is always the same defined time and not a random time, for example, I generated a bat which I define random times of execution and time in which it will be stopped. And I define the number of times in which to stop

Running Time: 40min - 70min
Holding time: 120min - 140min

BAT code

@ECHO OFF

C:
cd\
cd Users\mangonzalez\Desktop\Necrobot2\NecroBot2.WIN
SET /P INTENTOS=CUANTAS EJECUCIONES?:
SET /A CONTADOR=1
SET /A TIEMPOINI=0
SET /A "TIEMPOINI=%RANDOM% %%1800 +2400"
SET /A TIEMPOFIN=0
SET /A "TIEMPOFIN=%RANDOM% %%1200 +7200"

:Inicio
IF %CONTADOR% LEQ %INTENTOS% (
	ECHO EJECUCION #%CONTADOR% DE %INTENTOS% EJECUCIONES.
	ECHO ----------------------------------------------------------------------------------------------------
	SET /A CONTADOR=%CONTADOR% + 1

	SET /A TIEMPOINI=0

	SET /A "TIEMPOINI=%RANDOM% %%1800 +2400"
	ECHO EJECUTANDO NECROBOT2.WIN
	START NecroBot2.Win.exe
	ECHO LA EJECUCION DE NECROBOT2.WIN DURARA %TIEMPOINI% SEGUNDOS.
	PING 127.0.0.1 -n %TIEMPOINI% >NUL

	SET /A TIEMPOFIN=0

	SET /A "TIEMPOFIN=%RANDOM% %%1200 +7200"
	ECHO DETENIENDO NECROBOT2.WIN
	TASKKILL /F /IM NecroBot2.Win.exe
	ECHO NECROBOT2.WIN ESTARA DETENIDO %TIEMPOFIN% SEGUNDOS.
	PING 127.0.0.1 -n %TIEMPOFIN% >NUL

	ECHO ----------------------------------------------------------------------------------------------------
	GOTO Inicio
)

PAUSE

**Comment by hardknoxni69a** [comment]
Damn I wish I understood that because sounds great we see need something
like this though we are talking about it though

**Comment by hardknoxni69a** [comment]
implemented
