### ISSUE TITLE
Please me run porgram

### ISSUE THREAD

**Issue by zsatanxz** [Necrobot-Private/NecroBot#126]
Please me run porgram NecroBot2 v0.9.9.1
![1](https://cloud.githubusercontent.com/assets/21266188/18495889/7dee4550-7a4b-11e6-8205-98dc77ba39ef.jpg)

**Comment by bulubebek** [comment]
read #121

**Comment by jjskuld** [comment]
Killswitch activated

**Comment by jjskuld** [comment]
You can now override the killswitch. Update to v0.9.9.2.  You have been warned!
