### ISSUE TITLE
Error to login in Pokemon GO

### ISSUE THREAD

**Issue by LimitedOC** [Necrobot-Private/NecroBot#1260]
Am telling you guys this for any1 who uses the bot. if u get an error message like: we detected that you are using third party app (...) we are telling you to stop. it means that you will get banned in the next days! i had my 2nd acc 32 lvl (as the first that got banned) and i didnt use the bot from the moment that API stopped working. from that moment i was playing normaly and one or two days later i got the message, 5 days later got the ban so be carefull and if u see this message start your new account and bot from the begin,

**Comment by hardknoxni69a** [comment]
setting your bot safely will avoid this message

**Comment by LimitedOC** [comment]
i will avoid the message even now that am getting it? or in a new account i wont have it?

**Comment by hardknoxni69a** [comment]
Should be both but likely once u set off the warning there watching super close so make sure u set up carefully and safe
