### ISSUE TITLE
Issue) A Lot Of The Time NecroBot Does Not Fully Close

### ISSUE THREAD

**Issue by hardknoxni69a** [Necrobot-Private/NecroBot#1265]
Many Many Times After Closing Necrobot The Process Still Stays Open In Task Manager So Trying To Open Another Copy Will Return Errors Like LastPos.ini Still Being In Use Or Your WebSocket Is Still In Use Only Manually Opening Task Manager And Ending Task Will Kill It Fully This Happens A Few Times A Day Not Sure What Causes It But I Know Users Have Had This Issue As Wel

**Comment by jjskuld** [comment]
I've seen this as well.  I'll try to debug it.

**Comment by hardknoxni69a** [comment]
Thanks it's most annoying when u have multiple bots running and u don't know which process to end because it will end a task that is running fine but it usually happens if there is some other kind of error that makes bot crash

**Comment by CDAGaming** [comment]
This Issue has been Fixed in v148
