### ISSUE TITLE
GUI item, pokemon vs. pages

### ISSUE THREAD

**Issue by garette1** [Necrobot-Private/NecroBot#1267]
GUI pages cant scroll down and up

edit : and pokeease fork by necrobot2 team dont install

**Comment by cocacolabanane** [comment]
thx man

**Comment by Lord-Haji** [comment]
@garette1 please elaborate 
and pokeease fork by necrobot2 team dont install

**Comment by garette1** [comment]
@Lord-Haji after click install, i get an error message : "the remote server returned an eror (404) not found"

**Comment by hardknoxni69a** [comment]
gui has been discontinued a similar map will be incoorporated into the WIN.Gui but no longer maintaining the old GUI and electron please update to WIN.GUI
