### ISSUE TITLE
Free - Paid API's

### ISSUE THREAD

**Issue by LimitedOC** [Necrobot-Private/NecroBot#1268]
Guys i know that u dont sell the API's but i would like to ask 2 things. 

1)will there be a new free API (like the previous one)? because some of us may not have paypal - card to buy
the key.
2)If there will no be a new free API is there any possibility to create a payment method for the cheap ones (3euros etc) with sms?

thanks for your time

**Comment by Lord-Haji** [comment]
@LimitedOC Pokefarmer decides price not us.

**Comment by LimitedOC** [comment]
I know but that's the cheapest price right now and I only ask for another payment method (sms)
