### ISSUE TITLE
how to install NecroBot2.Console v0.9.9.0?

### ISSUE THREAD

**Issue by henbae** [Necrobot-Private/NecroBot#127]
now i'm using Release0.8.8, how to install the new NecroBot2.Console v0.9.9.0?
please advice me, thank you

and is it work for buddy updated ?

**Comment by petpetpetvm** [comment]
Download, extract, run and press N for no, then edit the auth.json and config.json as the way you want

**Comment by jjskuld** [comment]
Killswitch is activated, so at any moment niantic can force 0.37 updates and flag anyone connecting.  It's not recommended to bot with any account that you want to keep.

**Comment by henbae** [comment]
how to download ? i didnt see exe file on Code page

**Comment by jjskuld** [comment]
See releases tab https://github.com/Necrobot-Private/NecroBot/releases
