### ISSUE TITLE
GUI Pokemon storage Tab not Updated

### ISSUE THREAD

**Issue by krishnaraovs** [Necrobot-Private/NecroBot#1270]
My Pokemon Storage & Bag are upgraded to 650 but in GUI only Items Bag Tab got updated where as Pokemon Storage is not updated.

Attached image for reference
![pk_bot_tab](https://cloud.githubusercontent.com/assets/25992303/23918262/4b041a6e-0918-11e7-8583-856a0e9bd6e0.jpg)

Version: 1.0.0.137
Windows Version: WIN 7

**Comment by hardknoxni69a** [comment]
#802 Bug been open for a while now please read open issues before opening more

**Comment by Lord-Haji** [comment]
@hardknoxni69a the Item is always 350 too

**Comment by hardknoxni69a** [comment]
The items gets updated correctly u can see in his picture shows 650 but yes Pokemon doesn't get updated I'll try to see if I can find how to fix. Can close the older one and attach to this issue so we don't have multiple issues for one bug

**Comment by Lord-Haji** [comment]
@krishnaraovs I was working on this. But unfortunately I don't have an account with upgraded Pokemon storage. So u need to help me test it. Reply your discord if ASAP

**Comment by Lord-Haji** [comment]
#1317

**Comment by Lord-Haji** [comment]
Fixed
