### ISSUE TITLE
no free bot??

### ISSUE THREAD

**Issue by blackmamba0024** [Necrobot-Private/NecroBot#1280]
are all free bots down??
aren't they bring back the 0.45 api??
please reply necrobot..
tnx for your reply..

**Comment by Lord-Haji** [comment]
Niantic has disabled 0.45 API. We are working to resolve it and get it to working.

Thanks for your patience :D

**Comment by blackmamba0024** [comment]
okay sir..
i hope you can resolve it because necrobot is the best bot sir..
more powers to necrobot..
