### ISSUE TITLE
Necrobot v2 does not work!

### ISSUE THREAD

**Issue by veli66** [Necrobot-Private/NecroBot#1286]
Hello, my problem is, that when i downloaded any version of necrobot v2, and opened it i cant sign in or somethink like that. When i sign in, it crash or exit it. I almost installed 15 times necrobot v2 in different versions but no one worked for me.
Pls need some help 🗡.

**Comment by jjskuld** [comment]
Are you using 32-bit OS by any chance?

**Comment by veli66** [comment]
No :c

**Comment by veli66** [comment]
I have a windows 10 system with a 64 bit system and i tried 32 and the normla download.

**Comment by jjskuld** [comment]
Any logs in the logs directory?

**Comment by jjskuld** [comment]
Do you have .NET 4.6.2 installed?

**Comment by veli66** [comment]
Yeah i have .NET 4.6.2 and i can send a log.
[NecroBot2-2017-03-15-18-06-31.txt](https://github.com/Necrobot-Private/NecroBot/files/845397/NecroBot2-2017-03-15-18-06-31.txt)

**Comment by veli66** [comment]
Can you see in the txt. file whats wrong?

**Comment by SamMenary** [comment]
Sorry I can't help, but can you please take a look at my issue? I just posted it

**Comment by Lord-Haji** [comment]
@veli66 do u use Legacy API ?

**Comment by veli66** [comment]
Do you mean, that where you must pay?
When yes no.

**Comment by hardknoxni69a** [comment]
please try the latest version as there was alot of fixes with errors and multibot let me know if need to reopen

**Comment by hardknoxni69a** [comment]
its hoOh by the way

**Comment by veli66** [comment]
No it don´t works. Like i said i tried 15 different versions and no one worked. Why was this problem closed?
And do you can help me yes or no, dont just close this issue.

**Comment by hardknoxni69a** [comment]
just because an issue is closed doesnt mean u dont get helped you havent really said what the problem is did u fix hooh because that will cause crash im running 40 bots right now with latest version so i know the bot works

**Comment by hardknoxni69a** [comment]
also try uploading logs in english translation to make it easiest to get help you can see json issues so most likely it is how your config is set i mean i know for fact hoOh is issue

**Comment by veli66** [comment]
[NecroBot2-2017-03-16-18-26-17.txt](https://github.com/Necrobot-Private/NecroBot/files/848535/NecroBot2-2017-03-16-18-26-17.txt)
Here is my Log. When i log in, it says rebuild translation folder and i press Y and then im logging in, then it crash.

**Comment by hardknoxni69a** [comment]
2 things. You still haven't fixed hooh so your going to get an error and
bot won't start the bot works you just have set up indirectly. Join our
discord and I will happily help you After you fix hooh because that is
probably your problem also upload English logs for more help

**Comment by veli66** [comment]
What is a hooh?

**Comment by hardknoxni69a** [comment]
Ho-Oh = "HoOh"

**Comment by veli66** [comment]
What should i fix at a Ho-oh which is a pokemon like google said.

**Comment by hardknoxni69a** [comment]
Join discord you know how to.fix now.go through your config and get rid of ho-oh and replace with "hoOh". if u need more help go to discord we keep github for issues and requests
