### ISSUE TITLE
Catch Attempts in Sniping

### ISSUE THREAD

**Issue by krishnaraovs** [Necrobot-Private/NecroBot#1291]
I searched in config to increase catch attempts while snipe but didn't found any, right now bot is trying only 5 times and leaving the pokemon. When done manually using teleport & joystick hack sometimes its catching pokemon below 5 sometimes 8 or 9 times I need to throw ball at this time either pokemon is caught or its fleeing.

I would like to add an option where we can set no.of attempts to be made in snipe.

**Comment by hardknoxni69a** [comment]
just up your numberofballsusedto catch pokemon

**Comment by krishnaraovs** [comment]
Thanks the string is "MaxPokeballsPerPokemon"

**Comment by hardknoxni69a** [comment]
Sorry was on phone but glad to help enjoy
