### ISSUE TITLE
Autoupdate for win32bit downloads 64bit executables

### ISSUE THREAD

**Issue by ClarkWesterfeld** [Necrobot-Private/NecroBot#1297]
### Expected Behavior:
Autoupdate downloads the newest release for the appropriate architecture.

### Actual Behavior:
In windows 7 pro 32bit: Launching either NecroBot2.exe or NecroBot2.Win.exe after autoupdating results in a windows error message explaining that the executable is compiled for 64bit. Fixed by manually downloading the correct version, which breaks on next autoupdate.

Version: v1.0.0.139 and at least three or four releases prior
Windows Version: Windows 7 32bit
What is affected (catch, transfer, favorite, GPX, evolve, recycle, snipe, human walk snipe, pokestops, powerup/levelup, other): Executing NecroBot.

**Comment by hardknoxni69a** [comment]
We will work on making the autoupdate different for each architecture currently it all pulls necrobor2.win.exe so we need the 32bit to pull necrobot2.win.32bit.exe. please download manually for now

**Comment by jjskuld** [comment]
Next build will be back to "Any CPU" so will work with 32 or 64bit.
