### ISSUE TITLE
hi i need help

### ISSUE THREAD

**Issue by volksboyzz** [Necrobot-Private/NecroBot#1298]
i have buy hask key for necrobo and the support valid to me key is valable so can you help me to setup this plzzz

**Comment by macinmn** [comment]
PORTION OF AUTH.JSON FILE:
  
"APIConfig": {
    "UsePogoDevAPI": true,
    "AuthAPIKey": "YOUR_KEY_HERE",
    "UseLegacyAPI": false,
    "DiplayHashServerLog": true
  }

**Comment by volksboyzz** [comment]
ty and can you help me to
