### ISSUE TITLE
I wanna customize my bot to match my phone,

### ISSUE THREAD

**Issue by RicoEdg** [Necrobot-Private/NecroBot#1300]
"DevicePlatform": "android",
    "DevicePackageName": "custom",
    "DeviceId": "487da3ef3534e841f422515d321f7e9d", What goes here for android is it Product ID? 
    "AndroidBoardName": null, And here?
    "AndroidBootloader": null, Here?
    "DeviceBrand": "sony",
    "DeviceModel": "xperia",
    "DeviceModelIdentifier": null, Here?
    "DeviceModelBoot": "android,7",
    "HardwareManufacturer": "sony",
    "HardwareModel": "E6653",
    "FirmwareBrand": "android",
    "FirmwareTags": null, Here?
    "FirmwareType": "7", Here?
    "FirmwareFingerprint": null, Here?, my phone does have fingerprint
    "UseRandomDeviceId": false

**Comment by hardknoxni69a** [comment]
download a device info app and it will have all the info
