### ISSUE TITLE
Multiple Filters in GUI (request)

### ISSUE THREAD

**Issue by KMSO** [Necrobot-Private/NecroBot#1301]
Greetings,
it would be really usefull and nice, if there would be multiple filters choices in the GUI
for example, i wanna see the highest to the lowest IV, and in the same time the highest CP to lowest, this would be really usefull
thank you

**Comment by Lord-Haji** [comment]
Theres already filter system in win GUI
Please refrain from asking these sorta questions

**Comment by KMSO** [comment]
hi, due to my poor explaining, you didnt get what i mean
what i meant is, that the filters stack together, not just 1 filter applies,   and i clearly said *in the same time* but maybe you missed it
stacking filter like:   Highest to lowest IV   AND SAME TIME highest to lowest CP    , at this time just ONE filter applies

**Comment by hardknoxni69a** [comment]
Like he said this is already implemented just like every single list on every application out there just simply.hold down shift or ctrl some apps while.selcting the 2nd filter please try some research before bashing on the devs that keep this app alive
