### ISSUE TITLE
escape pokemon

### ISSUE THREAD

**Issue by volksboyzz** [Necrobot-Private/NecroBot#1302]
why i cant catch pokemon so all time escape after 3hrs say me escape all the time

**Comment by KMSO** [comment]
dude, here isnt for random questions, you can use discord, and the answer to ur question is,  you are jumping and getting softbanned, means u cant spin pokestops and every pokemon escape after 1 ball
try to stay in one location

**Comment by Lord-Haji** [comment]
Refrain from asking random questions please..

**Comment by hardknoxni69a** [comment]
I hope u have ur limits on too
