### ISSUE TITLE
unable to use bot

### ISSUE THREAD

**Issue by saintv** [Necrobot-Private/NecroBot#1303]
I have no idea what this is. I have been trying to use the bot for couple of days now, and errors after errors occur.
![screenshot_5](https://cloud.githubusercontent.com/assets/20824601/24027013/ee082f42-0a81-11e7-8920-5dea1b17c3f8.png)

**Comment by Lord-Haji** [comment]
0.45 API was disabled by niantic

**Comment by hardknoxni69a** [comment]
Lol so really wish people read the error before making issues it is in the error what is wrong and how you can fix it
