### ISSUE TITLE
Manual snipping is not working. When i am snipping from http://snipe.necrobot2.com/# the website says "The information has been sent to bot". But the bot is not getting the coordinates or any details regarding the snipe 

### ISSUE THREAD

**Issue by venkateshmoganti** [Necrobot-Private/NecroBot#1306]
## Stop! Before you create this issue (you can delete this section when opening the issue):
1. Have you searched to see if there are other Open/Closed issues for the same issue? If so, comment on that issue instead.
2. Have you validated that your config/auth.json and config/config.json is valid JSON? Use http://jsonlint.com/ to check.
3. If your question is referring to how to set up or use the bot, please join our discord instead of posting an issue: https://discord.gg/7FWyWVp 
4. Always confirm that your issue is reproducible, with the config you provide below.

### Your config.json:
```
replace this text with the contents of your config.json

```

### (OPTIONAL) Your Log:
```
replace this text with only the "relative" portion of your log. (Remove unnessary lines)

```

### Other Information
(Attach zip files if needed.)

Version:
Windows Version:
What is affected (catch, transfer, favorite, GPX, evolve, recycle, snipe, human walk snipe, pokestops, powerup/levelup, other):

**Comment by Lord-Haji** [comment]
Manual snipe by win gui

**Comment by hardknoxni69a** [comment]
Using the GUI is always best. But whatever site your bot is connected to is the site that can send it coords. So me I use the VIP server so if i want to websnipe I go to the VIP site and use that page to send it coords. Check your config and use that site

**Comment by venkateshmoganti** [comment]
what is the vip site

**Comment by hardknoxni69a** [comment]
You have to donate to get VIP server

**Comment by venkateshmoganti** [comment]
How much ?

**Comment by hardknoxni69a** [comment]
It's up to you really I would.donate atleast 10 or more because it worth it and saves you hours and hours of time so you can do more important things I did 50$ myself and I help with the team but the other devs are genius and deserve it so whatever u want I think atleast 10 or more but lately alot of people been donating around what I sent

**Comment by venkateshmoganti** [comment]
Now donted to them. How will i get the access key
