### ISSUE TITLE
Snipe List Name Issue

### ISSUE THREAD

**Issue by am3yar0ra** [Necrobot-Private/NecroBot#1307]
How do i add Nidoran Female & Nidoran Male in the snipe list ??

### Your config.json:
```
    }
    "NidoranFemale": {
      "SnipeIV": 100,
      "Moves": [],
      "Operator": "or",
      "VerifiedOnly": false,
      "Priority": 5,
      "AutoSnipeCandy": 2000,
      "Level": 0,
      "AllowMultiAccountSnipe": false,
      "AffectToPokemons": []
    },
    "NidoranMale": {
      "SnipeIV": 100,
      "Moves": [],
      "Operator": "or",
      "VerifiedOnly": false,
      "Priority": 5,
      "AutoSnipeCandy": 2000,
      "Level": 0,
      "AllowMultiAccountSnipe": false,
      "AffectToPokemons": []
    },

```

Version: .39
Windows Version: Windows 7 x64
What is affected (catch, transfer, favorite, GPX, evolve, recycle, snipe, human walk snipe, pokestops, powerup/levelup, other): Snipe

**Comment by Lord-Haji** [comment]
U r only supposed to report bugs and request features on github although you can ask these sorta questions to other users in our discord chat. Please refrain creating issues for these questions. 

Happy Botting!

**Comment by hardknoxni69a** [comment]
U ask a question with the answer in your comment that is what u need to snipe you are good it will snipe nidorans

**Comment by am3yar0ra** [comment]
@Lord-Haji Then it is a bug. Please have a look at it. These names are not being recognized by the bot. I tried with these names written. Also tried "Nidoran Male" with space and apart from this also tried "Nidoran M". These 2 exceptions are also not working. I hope you have a look at it.

**Comment by hardknoxni69a** [comment]
Did u check the schema to see what's acceptable like pretty sure it's nidoranMale and nidoranFemale

**Comment by SirenKing** [comment]
It is case-sensitive. "nidoranMale" and "nidoranFemale" works just fine for me.
