### ISSUE TITLE
Issue) Commit 17f59184 Removed KeepMinDuplicatePokemon

### ISSUE THREAD

**Issue by hardknoxni69a** [Necrobot-Private/NecroBot#1309]
After This Commit KeepMinDuplicatePokemon No Longer Worked Correctly I Believe The Code Was Supposed To Get Moved But Never Did I Am Trying To See If I Can Fix But Any Of You Are Undoubtedly Better With Coding So If You Can Take A Peek Would Be Amazing It Was 2/28 When The AffectToPokemon Was Added.

**Comment by hardknoxni69a** [comment]
Would Be Great To Not Have To BabySit My Bot Again

**Comment by Lord-Haji** [comment]
@17f59184

**Comment by hardknoxni69a** [comment]
Damn I was all excited thought u fixed it and just realized that was old
commit

**Comment by jjskuld** [comment]
@hardknoxni69a I cannot spot the bug by eyeballing this and I don't have a configuration to reproduce this issue. If you suspect @17f5918 is the issue, try to revert that change on top of the current master code, recompile and run the code to see if your issue is resolved.
