### ISSUE TITLE
the security android update

### ISSUE THREAD

**Issue by blackmamba0024** [Necrobot-Private/NecroBot#1310]
good day necrobot 
may i ask about the latest update of android users about the security android
arent are account will be banned by using bot or the gps spoofing only??
thanks for your answer..

**Comment by samuraitruong** [comment]
it is not related, we can't anwser yes or no/ Bot is risk, consider to accept risk when use bot

**Comment by blackmamba0024** [comment]
the reason is that pokemon go will going to update on android users with the security to banned the gps spoofing..
i know that the bot have a risk to be ban, but may i ask if this can affect the bot?
