### ISSUE TITLE
PokeRadar, PokeCrew, and PokeFastMap not available on non-humanwalk

### ISSUE THREAD

**Issue by CreativiTimothy** [Necrobot-Private/NecroBot#132]
### Expected Behavior:
Pokeradar, pokecrew, and pokefastmap sniping should have non-humanwalk options like pokezz and pokesnipers

### Actual Behavior:
It is exclusively for humanwalk sniping which I do not use. They are not consistent with the other sniper infos like pokezz and pokesnipers which are available without using humanwalk snipe

### Your config.json:
  "HumanWalkSnipeConfig": {
    "Enable": false,
    "DisplayPokemonList": true,
    "MaxDistance": 1500.0,
    "MaxEstimateTime": 900.0,
    "CatchEmAllMinBalls": 100,
    "TryCatchEmAll": true,
    "CatchPokemonWhileWalking": true,
    "SpinWhileWalking": true,
    "AlwaysWalkback": false,
    "SnipingScanOffset": 0.025,
    "WalkbackDistanceLimit": 300.0,
    "IncludeDefaultLocation": true,
    "UseSnipePokemonList": true,
    "MaxSpeedUpSpeed": 60.0,
    "AllowSpeedUp": true,
    "DelayTimeAtDestination": 10000,
    "UsePokeRadar": true,
    "UseSkiplagged": true,
    "UsePokecrew": true,
    "UsePokesnipers": true,
    "UsePokeZZ": true,
    "UsePokeWatcher": true,
    "UseFastPokemap": true,
    "UsePogoLocationFeeder": false
  },

**Comment by samuraitruong** [comment]
I don't know what you asking about? please clarify

**Comment by iwean** [comment]
@samuraitruong 
He want you add all location server from HWS to standart sniping function...

**Comment by samuraitruong** [comment]
actually, 1 snipe server is enough for snipe, people so eager. I don't use long distance snipe, i still have 1200 dratini candy and 20 dragonite :)

**Comment by iwean** [comment]
LoL.... couldn't agree more :smile:

**Comment by Yinyinka** [comment]
May I know which snipe server you are using?
And for HumanWalk, which server are you using? Recently, my HumanWalk always gives false location.
I really love this feature, please tell me which server is reliable
@samuraitruong

**Comment by CreativiTimothy** [comment]
@samuraitruong I'm kinda OCD. When things are not symmetrical, I get uneasy. Extra sniper info on human walk but not on the regular snipe bothers me. Not a priority though so fix it later

**Comment by Silph-Road** [comment]
Closing this for now...

**Comment by samuraitruong** [comment]
@Yinyinka  FastPokemap is working, 
FYI , some services is not suitable to add in long distance snip . snipes site already collect those data so we don't need to get data from them, HMW is specially, we need that feed to make function work.

**Comment by Yinyinka** [comment]
So you mean that config like this is the best for now?
    "UsePokeRadar": false,
    "UseSkiplagged": false,
    "UsePokecrew": false,
    "UsePokesnipers": false,
    "UsePokeZZ": false,
    "UsePokeWatcher": false,
    "UseFastPokemap": true,
    "UsePogoLocationFeeder": false
Please kindly advise if i have to change anything. Thanks @samuraitruong
