### ISSUE TITLE
Block the Legacy .45 Error

### ISSUE THREAD

**Issue by mcdeivis** [Necrobot-Private/NecroBot#1321]
Please help me,  when I clicked on the NecroBot2.WIN, I get the error .... what I do me :/  .. please help ....

https://ibb.co/iaOMrF

Best regard, Deividas

**Comment by Lord-Haji** [comment]
0.45 API is disabled by niantic
We have been saying this for a long time.
Do not create issues for these further.

**Comment by mcdeivis** [comment]
please say me, how to run necrobot v2 with API 0.57.4 ??

**Comment by hardknoxni69a** [comment]
U need the api there's a link when u load the bot for first time
