### ISSUE TITLE
"Random" APIBadRequestException

### ISSUE THREAD

**Issue by montolio** [Necrobot-Private/NecroBot#1322]
While farming the bot throws a APIBadRequestException, after that a new login is initialised but then the exeption is thrown again and the loop starts again

The Exception is thrown in \FeroxRev\Extensions\HttpClientExtensions.cs Line 129

But I have no idea why.

Restarting the whole bot fixes is, but after 5-30 min it appears again.

Logs:

[16:10:56] (ERROR) Pokemon Servers might be offline / unstable. Trying again...
[16:10:56] (ERROR) Error: System.AggregateException: Mindestens ein Fehler ist aufgetreten. ---> PokemonGo.RocketAPI.Exceptions.APIBadRequestException: BAD REQUEST 
{"StatusCode":2,"RequestId":1760348639,"Requests":[{"RequestType":134,"RequestMessage":[10,29,78,69,67,82,79,50,95,70,79,82,84,54,51,54,50,53,53,51,54,48,56,55,57,55,54,52,53,53,49,17,119,61,128,215,103,26,72,64,25,49,144,229,87,115,96,48,64,33,54,174,127,215,103,26,72,64,41,227,112,230,87,115,96,48,64]},{"RequestType":600,"RequestMessage":[]},{"RequestType":126,"RequestMessage":[]},{"RequestType":4,"RequestMessage":[8,209,136,252,184,174,43]},{"RequestType":129,"RequestMessage":[]},{"RequestType":5,"RequestMessage":[10,40,55,57,101,48,97,100,55,54,99,101,101,99,54,99,98,56,99,48,101,48,54,51,54,56,56,49,55,50,49,51,101,55,52,50,101,57,100,48,52,53]},{"RequestType":153,"RequestMessage":[]}],"PlatformRequests":[{"Type":8,"RequestMessage":[10,40,57,48,102,54,97,55,48,52,53,48,53,98,99,99,97,99,55,51,99,101,99,57,57,98,48,55,55,57,52,57,57,51,101,54,102,100,53,97,49,50]},{"Type":6,"RequestMessage":[10,133,4,231,19,57,75,238,4,124,4,65,18,147,170,57,10,208,157,192,98,46,23,13,203,103,28,237,253,146,231,124,180,20,154,48,78,77,48,201,5,75,61,133,139,198,167,83,125,239,160,12,67,83,99,186,241,60,104,125,69,94,5,237,173,216,2,197,123,197,224,160,87,168,214,37,100,114,11,199,191,162,248,89,39,46,91,142,71,106,78,142,237,75,96,239,116,230,49,10,193,147,28,11,47,166,243,43,176,54,226,235,86,36,222,64,130,36,189,62,151,167,220,58,137,144,231,215,57,203,201,222,209,80,203,151,211,37,243,84,181,113,11,76,163,81,58,151,233,181,101,16,224,92,149,153,202,186,196,88,92,141,196,179,15,69,35,227,127,210,116,107,186,179,186,60,141,123,251,15,90,82,221,95,129,198,6,123,132,243,46,31,239,135,163,29,103,117,142,181,82,55,53,136,35,90,23,164,201,200,177,143,196,188,13,115,170,110,128,235,200,232,48,157,127,98,219,177,73,72,232,69,75,28,15,216,3,59,177,137,115,120,245,22,174,138,94,73,254,19,186,143,11,216,180,232,65,186,88,175,241,205,26,141,128,3,183,205,10,159,117,209,189,76,80,233,47,157,154,230,170,20,252,4,145,39,140,214,66,12,39,73,69,15,253,161,128,150,77,44,218,52,102,59,167,44,220,208,90,5,2,116,217,107,253,144,72,18,70,213,198,27,197,77,138,192,21,123,78,102,211,4,185,243,66,235,189,29,201,21,41,192,76,193,223,53,91,115,167,160,136,51,29,218,131,73,51,160,121,54,85,129,230,183,253,194,142,196,84,131,227,238,70,173,86,186,251,83,231,74,182,254,130,247,68,10,5,141,212,51,63,27,199,63,2,118,250,225,254,178,227,109,155,22,234,52,237,73,164,31,47,249,60,226,201,255,116,226,230,94,245,8,48,128,119,68,157,57,86,216,72,35,60,187,37,127,232,25,163,53,151,202,74,217,66,205,71,176,190,255,197,4,4,193,200,157,38,236,5,142,153,59,200,90,62,212,22,100,147,54,164,219,19,115,66,42,192,88,129,81,17,168,189,63,45,246,147,114,198,84,38,60,127,60,8,91,138,115,215,200,190,52,141,207,86,156,197,115,21,109,160,198,196,91,65,11,151,239,139,243]}],"Latitude":48.20629,"Longitude":16.37676,"Accuracy":5.0,"AuthInfo":null,"AuthTicket":{"Start":[170,201,127,122,163,169,254,178,7,21,11,18,84,78,219,229,219,176,213,3,100,61,199,140,135,220,6,61,94,236,102,98,198,192,70,199,207,241,37,253,177,158,187,12,211,151,68,209,152,32,83,125,171,61,149,39,249,69,161,161,221,161,232,57,29,63,245,116,181,49,76,46,201,54,194,108,215,106,162,246],"ExpireTimestampMs":1489937284116,"End":[222,205,174,254,64,103,197,4,25,177,38,94,241,181,3,41]},"MsSinceLastLocationfix":16291}
   bei PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PerformRemoteProcedureCall>d__2`1.MoveNext() in c:\projects\necrobot2\FeroxRev\Extensions\HttpClientExtensions.cs:Zeile 129.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PerformThrottledRemoteProcedureCall>d__8`1.MoveNext() in c:\projects\necrobot2\FeroxRev\Extensions\HttpClientExtensions.cs:Zeile 174.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProtoPayload>d__0`1.MoveNext() in c:\projects\necrobot2\FeroxRev\Extensions\HttpClientExtensions.cs:Zeile 46.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei PokemonGo.RocketAPI.Rpc.BaseRpc.<PostProtoPayload>d__11`1.MoveNext() in c:\projects\necrobot2\FeroxRev\Rpc\BaseRpc.cs:Zeile 130.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei PokemonGo.RocketAPI.Rpc.BaseRpc.<PostProtoPayload>d__10`8.MoveNext() in c:\projects\necrobot2\FeroxRev\Rpc\BaseRpc.cs:Zeile 119.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei PokemonGo.RocketAPI.Rpc.Fort.<GetGymDetails>d__7.MoveNext() in c:\projects\necrobot2\FeroxRev\Rpc\Fort.cs:Zeile 266.
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   bei System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   bei PoGo.NecroBot.Logic.State.CachedGymGetails.LoadData(ISession session, FortData fort) in c:\projects\necrobot2\PoGo.NecroBot.Logic\State\GymTeamState.cs:Zeile 276.
   bei PoGo.NecroBot.Logic.State.GymTeamState.getGymDetails(ISession session, FortData fort, Boolean force) in c:\projects\necrobot2\PoGo.NecroBot.Logic\State\GymTeamState.cs:Zeile 94.
   bei PoGo.NecroBot.Logic.Tasks.UseNearbyPokestopsTask.<Execute>d__9.MoveNext() in c:\projects\necrobot2\PoGo.NecroBot.Logic\Tasks\UseNearbyPokestopsTask.cs:Zeile 75.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   bei PoGo.NecroBot.Logic.Tasks.FarmPokestopsTask.<Execute>d__1.MoveNext() in c:\projects\necrobot2\PoGo.NecroBot.Logic\Tasks\FarmPokestopsTask.cs:Zeile 60.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   bei PoGo.NecroBot.Logic.State.FarmState.<Execute>d__0.MoveNext() in c:\projects\necrobot2\PoGo.NecroBot.Logic\State\FarmState.cs:Zeile 57.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   bei PoGo.NecroBot.Logic.State.StateMachine.<Start>d__4.MoveNext() in c:\projects\necrobot2\PoGo.NecroBot.Logic\State\StateMachine.cs:Zeile 116.
---> (Interne Ausnahme #0) PokemonGo.RocketAPI.Exceptions.APIBadRequestException: BAD REQUEST 
{"StatusCode":2,"RequestId":1760348639,"Requests":[{"RequestType":134,"RequestMessage":[10,29,78,69,67,82,79,50,95,70,79,82,84,54,51,54,50,53,53,51,54,48,56,55,57,55,54,52,53,53,49,17,119,61,128,215,103,26,72,64,25,49,144,229,87,115,96,48,64,33,54,174,127,215,103,26,72,64,41,227,112,230,87,115,96,48,64]},{"RequestType":600,"RequestMessage":[]},{"RequestType":126,"RequestMessage":[]},{"RequestType":4,"RequestMessage":[8,209,136,252,184,174,43]},{"RequestType":129,"RequestMessage":[]},{"RequestType":5,"RequestMessage":[10,40,55,57,101,48,97,100,55,54,99,101,101,99,54,99,98,56,99,48,101,48,54,51,54,56,56,49,55,50,49,51,101,55,52,50,101,57,100,48,52,53]},{"RequestType":153,"RequestMessage":[]}],"PlatformRequests":[{"Type":8,"RequestMessage":[10,40,57,48,102,54,97,55,48,52,53,48,53,98,99,99,97,99,55,51,99,101,99,57,57,98,48,55,55,57,52,57,57,51,101,54,102,100,53,97,49,50]},{"Type":6,"RequestMessage":[10,133,4,231,19,57,75,238,4,124,4,65,18,147,170,57,10,208,157,192,98,46,23,13,203,103,28,237,253,146,231,124,180,20,154,48,78,77,48,201,5,75,61,133,139,198,167,83,125,239,160,12,67,83,99,186,241,60,104,125,69,94,5,237,173,216,2,197,123,197,224,160,87,168,214,37,100,114,11,199,191,162,248,89,39,46,91,142,71,106,78,142,237,75,96,239,116,230,49,10,193,147,28,11,47,166,243,43,176,54,226,235,86,36,222,64,130,36,189,62,151,167,220,58,137,144,231,215,57,203,201,222,209,80,203,151,211,37,243,84,181,113,11,76,163,81,58,151,233,181,101,16,224,92,149,153,202,186,196,88,92,141,196,179,15,69,35,227,127,210,116,107,186,179,186,60,141,123,251,15,90,82,221,95,129,198,6,123,132,243,46,31,239,135,163,29,103,117,142,181,82,55,53,136,35,90,23,164,201,200,177,143,196,188,13,115,170,110,128,235,200,232,48,157,127,98,219,177,73,72,232,69,75,28,15,216,3,59,177,137,115,120,245,22,174,138,94,73,254,19,186,143,11,216,180,232,65,186,88,175,241,205,26,141,128,3,183,205,10,159,117,209,189,76,80,233,47,157,154,230,170,20,252,4,145,39,140,214,66,12,39,73,69,15,253,161,128,150,77,44,218,52,102,59,167,44,220,208,90,5,2,116,217,107,253,144,72,18,70,213,198,27,197,77,138,192,21,123,78,102,211,4,185,243,66,235,189,29,201,21,41,192,76,193,223,53,91,115,167,160,136,51,29,218,131,73,51,160,121,54,85,129,230,183,253,194,142,196,84,131,227,238,70,173,86,186,251,83,231,74,182,254,130,247,68,10,5,141,212,51,63,27,199,63,2,118,250,225,254,178,227,109,155,22,234,52,237,73,164,31,47,249,60,226,201,255,116,226,230,94,245,8,48,128,119,68,157,57,86,216,72,35,60,187,37,127,232,25,163,53,151,202,74,217,66,205,71,176,190,255,197,4,4,193,200,157,38,236,5,142,153,59,200,90,62,212,22,100,147,54,164,219,19,115,66,42,192,88,129,81,17,168,189,63,45,246,147,114,198,84,38,60,127,60,8,91,138,115,215,200,190,52,141,207,86,156,197,115,21,109,160,198,196,91,65,11,151,239,139,243]}],"Latitude":48.20629,"Longitude":16.37676,"Accuracy":5.0,"AuthInfo":null,"AuthTicket":{"Start":[170,201,127,122,163,169,254,178,7,21,11,18,84,78,219,229,219,176,213,3,100,61,199,140,135,220,6,61,94,236,102,98,198,192,70,199,207,241,37,253,177,158,187,12,211,151,68,209,152,32,83,125,171,61,149,39,249,69,161,161,221,161,232,57,29,63,245,116,181,49,76,46,201,54,194,108,215,106,162,246],"ExpireTimestampMs":1489937284116,"End":[222,205,174,254,64,103,197,4,25,177,38,94,241,181,3,41]},"MsSinceLastLocationfix":16291}
   bei PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PerformRemoteProcedureCall>d__2`1.MoveNext() in c:\projects\necrobot2\FeroxRev\Extensions\HttpClientExtensions.cs:Zeile 129.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PerformThrottledRemoteProcedureCall>d__8`1.MoveNext() in c:\projects\necrobot2\FeroxRev\Extensions\HttpClientExtensions.cs:Zeile 174.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProtoPayload>d__0`1.MoveNext() in c:\projects\necrobot2\FeroxRev\Extensions\HttpClientExtensions.cs:Zeile 46.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei PokemonGo.RocketAPI.Rpc.BaseRpc.<PostProtoPayload>d__11`1.MoveNext() in c:\projects\necrobot2\FeroxRev\Rpc\BaseRpc.cs:Zeile 130.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei PokemonGo.RocketAPI.Rpc.BaseRpc.<PostProtoPayload>d__10`8.MoveNext() in c:\projects\necrobot2\FeroxRev\Rpc\BaseRpc.cs:Zeile 119.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei PokemonGo.RocketAPI.Rpc.Fort.<GetGymDetails>d__7.MoveNext() in c:\projects\necrobot2\FeroxRev\Rpc\Fort.cs:Zeile 266.<---

[16:10:56] (INFO) Logging in using Google *****@gmail.com
[16:11:02] (INFO) Playing as $username
[16:11:02] (ATTENTION) Make sure Lat & Lng are right. Exit Program if not! Lat: 48.2062940002606 Lng: 16.3767599997956
[16:11:06] (INFO) ====== DisplayHighestsCP ======
[16:11:06] (INFO) # CP 2754/3281 | (97.78% perfect)	| Lvl 30	 NAME: Gyarados  	 MOVE1: BiteFast             MOVE2: DragonPulse          Candy: 184
[16:11:06] (INFO) # CP 2575/3157 | (84.44% perfect)	| Lvl 29	 NAME: Vaporeon  	 MOVE1: WaterGunFast         MOVE2: HydroPump            Candy: 47
[16:11:06] (INFO) ====== DisplayHighestsPerfect ======
[16:11:06] (INFO) # CP  396/2938 | (100.00% perfect)	| Lvl 05	 NAME: Heracross 	 MOVE1: Translation for move CounterFast is missing MOVE2: Megahorn             Candy: 3
[16:11:06] (INFO) # CP 1245/1816 | (100.00% perfect)	| Lvl 24	 NAME: Graveler  	 MOVE1: MudSlapFast          MOVE2: StoneEdge            Candy: 103
[16:11:06] (EGG) Incubator status update: 3.70km left
[16:11:06] (INFO) Amount of Pokemon Seen: 198/231, Amount of Pokemon Caught: 178/231
[16:11:08] (ATTENTION) No usable PokeStops found in your area. Is your maximum distance too small?
[16:11:08] (INFO) Traveling to Pokestop: Your selected location (0 m) (0 seconds) (route Google Walk)
[16:11:09] (ERROR) Pokemon Servers might be offline / unstable. Trying again...
[16:11:09] (ERROR) Error: System.AggregateException: Mindestens ein Fehler ist aufgetreten. ---> PokemonGo.RocketAPI.Exceptions.APIBadRequestException: BAD REQUEST 
{"StatusCode":2,"RequestId":1458777931,"Requests":[{"RequestType":134,"RequestMessage":[10,29,78,69,67,82,79,50,95,70,79,82,84,54,51,54,50,53,53,51,54,48,56,55,57,55,54,52,53,53,49,17,31,50,122,66,102,26,72,64,25,22,160,19,246,112,96,48,64,33,54,174,127,215,103,26,72,64,41,227,112,230,87,115,96,48,64]},{"RequestType":600,"RequestMessage":[]},{"RequestType":126,"RequestMessage":[]},{"RequestType":4,"RequestMessage":[8,159,245,252,184,174,43]},{"RequestType":129,"RequestMessage":[]},{"RequestType":5,"RequestMessage":[10,40,55,57,101,48,97,100,55,54,99,101,101,99,54,99,98,56,99,48,101,48,54,51,54,56,56,49,55,50,49,51,101,55,52,50,101,57,100,48,52,53]},{"RequestType":153,"RequestMessage":[]}],"PlatformRequests":[{"Type":8,"RequestMessage":[10,40,57,48,102,54,97,55,48,52,53,48,53,98,99,99,97,99,55,51,99,101,99,57,57,98,48,55,55,57,52,57,57,51,101,54,102,100,53,97,49,50]},{"Type":6,"RequestMessage":[10,133,4,231,31,13,105,88,110,62,222,30,64,124,215,211,193,66,27,193,190,185,160,97,97,23,28,239,251,103,161,99,232,233,107,56,105,45,51,27,57,91,24,2,195,171,240,230,84,99,182,36,60,241,228,254,103,85,183,111,171,179,193,232,102,164,116,13,87,134,147,108,87,112,179,117,79,179,192,115,125,63,138,111,153,0,131,125,210,209,125,162,72,24,203,244,213,59,86,240,228,37,203,103,176,3,84,71,111,219,229,147,237,146,43,101,22,40,114,35,10,188,222,38,158,144,189,50,164,200,5,38,217,9,16,43,140,35,193,4,174,22,27,180,217,143,165,57,238,77,59,152,133,248,88,30,92,52,43,249,120,0,67,33,191,252,98,96,244,70,190,100,41,96,126,45,31,130,244,89,165,76,201,228,67,211,76,190,204,192,41,140,104,111,19,30,126,206,87,152,77,0,247,29,87,239,1,202,88,64,156,180,72,39,74,9,61,72,126,233,142,226,12,27,142,147,244,196,253,141,209,160,126,253,15,47,211,36,112,239,112,109,82,80,140,149,185,44,104,11,87,135,204,231,130,213,207,223,143,225,56,23,22,31,87,29,224,239,89,143,75,218,75,130,127,53,143,55,50,124,52,1,190,30,152,63,28,106,25,41,168,134,242,48,108,144,107,77,7,217,33,61,246,60,205,169,13,165,166,12,204,163,82,131,129,148,100,26,12,45,9,48,119,237,49,122,244,102,145,225,122,47,175,148,45,2,103,109,80,146,181,82,171,160,215,72,169,243,22,144,242,67,1,5,175,69,45,118,25,170,232,43,144,194,121,215,40,71,159,232,47,57,106,198,111,243,51,47,20,219,106,241,252,214,171,178,74,239,241,210,117,191,243,231,104,230,56,121,146,171,186,217,70,164,151,61,240,211,52,130,188,241,128,212,12,87,2,244,10,239,132,125,128,180,153,88,27,232,125,151,172,236,153,196,191,237,128,137,95,240,33,237,201,97,183,189,51,116,83,141,63,27,8,255,138,66,234,152,96,77,252,196,232,215,32,201,94,35,49,53,153,188,99,42,37,130,24,220,248,187,236,197,159,255,101,247,1,101,222,168,164,244,18,16,157,16,222,5,219,96,206,136,244,70,33,228,29,76,14,5,15,9,197,97,28,253,254,132,89,82]}],"Latitude":48.20625,"Longitude":16.37672,"Accuracy":10.0,"AuthInfo":null,"AuthTicket":{"Start":[237,236,17,237,20,127,26,180,18,63,227,52,218,42,142,164,65,209,49,234,224,4,151,197,0,203,254,9,140,64,123,73,118,190,166,196,36,163,132,129,205,235,239,143,48,18,200,218,199,55,51,255,242,114,113,185,37,99,39,209,193,137,225,97,223,2,28,214,21,123,72,190,119,15,187,194,162,169,219,217],"ExpireTimestampMs":1489938057870,"End":[24,183,20,212,151,221,87,43,166,98,52,34,80,214,93,120]},"MsSinceLastLocationfix":12098}
   bei PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PerformRemoteProcedureCall>d__2`1.MoveNext() in c:\projects\necrobot2\FeroxRev\Extensions\HttpClientExtensions.cs:Zeile 129.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---

**Comment by montolio** [comment]
Has any dev an idea what can result in this error? 
It also seems that more and more people have the problem

Is there any information that I can provide to help investigation the problem

**Comment by montolio** [comment]
One more user with this problem:
https://cdn.discordapp.com/attachments/225828638589714433/293619486769152000/nb2_errorlog.png

**Comment by Lord-Haji** [comment]
This gets fixed after restart :D

**Comment by montolio** [comment]
Thats not a fix! 
Its impossible to run the bot unattended for more than 15 min!!

Thats not a reason for closing the ticket!!
