### ISSUE TITLE
Gym Setup

### ISSUE THREAD

**Issue by LimitedOC** [Necrobot-Private/NecroBot#1327]
Hello there, i just downloaded the newest version of NB2 and i bought the API, everything is fine (with free API i was getting a message in login to the app that they knew that am using program. still i dont have be banned or get a captcha "1:30 hour of botting") and i would appreciate if somebody tell me how to setup the Gym battles so it wont be needed to go right on the gyms to fight with mobile.  thanks for your time

**Comment by Lord-Haji** [comment]
Limit these to our discord.

Thank you :D

**Comment by LimitedOC** [comment]
i did it but no1 is responding.. they just sell accounts there and i think they dont help (from what i saw for other mates that has their own issues)
