### ISSUE TITLE
Catch flee

### ISSUE THREAD

**Issue by izzayaih76** [Necrobot-Private/NecroBot#1333]
I need help to fix catch flee when i use necro bot 2 and i did buy a pogodev api key i play pokemon go normally on my phone at my home and can catch and everything else but whenever i use the bot it always does the catch flee thing and when i try to use the bot i always make sure im not softbanned on mobile first i tried to go to the discord and no body has answered or even showed intrest

**Comment by jjskuld** [comment]
We're going to keep closing this if you keep spamming the Github issues area.
