### ISSUE TITLE
Infected downloads

### ISSUE THREAD

**Issue by Shaglakh** [Necrobot-Private/NecroBot#1334]
I have download the new Realese the Zip is Infected.
from this link
https://bintray.com/necrobot-private/NecroBot2/download_file?file_path=NecroBot2.WIN.1.0.0.143.zip

![kaspk](https://cloud.githubusercontent.com/assets/26149331/24122633/d51fd050-0dbc-11e7-8a2c-9f7537f6c6f4.JPG)

**Comment by montolio** [comment]
Only Kaspersky detects a Virus:
https://www.virustotal.com/de/file/5cbc3b4b2a6671d2cb8f2907cd1ac3db5950db724928acac0145dd3245cd5b64/analysis/1490045773/

So I think its a false positive

**Comment by Shaglakh** [comment]
and 
ZoneAlarm by Check Point 	Trojan.MSIL.Crypt.deqd 	20170320 
How can I bypass Kaspersky when the file is really clean?

**Comment by jjskuld** [comment]
We'll switch back to 64-bit builds to avoid this false positive.  Will be fixed in next release

**Comment by mboeder** [comment]
@jjskuld for those who are not capable updating to 64 Bit OS, is it possible to download 32 Bit compiled versions as well?

**Comment by jjskuld** [comment]
@mboeder Yes, we'll add different versions for 32-bit but first need to figure out why these are getting flagged.

**Comment by jjskuld** [comment]
@mboeder Quick update on this issue.. I just heard back from Kaspersky:

```
Hello,

Sorry, it was a false detection. It will be fixed.
Thank you for your help.

Sincerely yours,
Jessica Winter,
Malware analyst.
```
We're gonna get this fixed so we don't get flagged.

**Comment by hardknoxni69a** [comment]
arent builds anycpu now so 64 and 32

**Comment by hardknoxni69a** [comment]
false positives kaspersky is fixing

**Comment by mboeder** [comment]
Thx for Quickinfo! Since last Friday Symantec is detecting Trojan on 
executable as well L

**Comment by joe1chen** [comment]
AnyCpu still detects as trojan.  I'll contact Symantec now.
