### ISSUE TITLE
login impossible

### ISSUE THREAD

**Issue by tarsinion** [Necrobot-Private/NecroBot#1341]
to make shure i dont make something wrong, i downloadet the newest version.
(tryed 10 times now)
after the first start, where the config was generatet (i always get translation errors for ho-oh)
the bot starts, and cant login, becouse of these error:

[14:09:58] (INFO) xxxxxxxxxx@gmail.com (Level: ??)			Runtime : 00:00:00:00
[14:09:59] (UPDATE) Perfect! You already have the newest Version 1.0.0.144
[14:09:59] (INFO) Logging in using Google xxxxxxxxx@gmail.com
[14:09:59] (INFO) System.MissingMethodException: Methode nicht gefunden: "!!0[] System.Array.Empty()".
   bei PokemonGo.RocketAPI.Rpc.Player.<GetPlayer>d__9.MoveNext()
   bei System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   bei PokemonGo.RocketAPI.Rpc.Player.GetPlayer(Boolean addCommonRequests)
   bei PokemonGo.RocketAPI.Rpc.Login.<DoLogin>d__10.MoveNext() in c:\projects\necrobot2\FeroxRev\Rpc\Login.cs:Zeile 171.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   bei PoGo.NecroBot.Logic.State.LoginState.<Execute>d__3.MoveNext()
[14:09:59] (INFO) Your IP is: xx.xx.xx.xx
[14:10:19] (INFO) Logging in using Google xxxxxxx@gmail.com
[14:10:19] (INFO) System.MissingMethodException: Methode nicht gefunden: "!!0[] System.Array.Empty()".
   bei PokemonGo.RocketAPI.Rpc.Player.<GetPlayer>d__9.MoveNext()
   bei System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   bei PokemonGo.RocketAPI.Rpc.Player.GetPlayer(Boolean addCommonRequests)
   bei PokemonGo.RocketAPI.Rpc.Login.<DoLogin>d__10.MoveNext() in c:\projects\necrobot2\FeroxRev\Rpc\Login.cs:Zeile 171.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   bei PoGo.NecroBot.Logic.State.LoginState.<Execute>d__3.MoveNext()

no matter what i do, every new download and start foes exactly this

Version: 1.0.0.144
Windows Version: win 7
What is affected :

**Comment by andeomontenegro** [comment]
0.45 api? it was disabled..

**Comment by tarsinion** [comment]
the api version is 0.57.4

**Comment by mboeder** [comment]
I know that issue because i am using german tarnslation mode. Go to config\translations and open the corresponding language translation.json. Search for value ho-Oh and replace with hooh.
