### ISSUE TITLE
Error after starting/logging in [german log]

### ISSUE THREAD

**Issue by Croniqq** [Necrobot-Private/NecroBot#1344]
) Error: System.InvalidCastException: Das Objekt des Typs "LiteDB.EmptyPage" kann nicht in Typ "LiteDB.IndexPage" umgewandelt werden.
   bei LiteDB.PageService.GetPage[T](UInt32 pageID, Boolean setDirty)
   bei LiteDB.IndexService.GetNode(PageAddress address)
   bei LiteDB.IndexService.Delete(CollectionIndex index, PageAddress nodeAddress)
   bei LiteDB.DbEngine.<>c__DisplayClass8_0.<Delete>b__0(CollectionPage col)
   bei LiteDB.DbEngine.WriteTransaction[T](String colName, Boolean addIfNotExists, Func`2 action)
   bei LiteDB.LiteCollection`1.Delete(Query query)
   bei PoGo.NecroBot.Logic.State.SessionStats.CleanOutExpiredStats()
   bei PoGo.NecroBot.Logic.State.SessionStats.CatchThresholdExceeds(ISession session, Boolean printMessage)
   bei PoGo.NecroBot.Logic.Tasks.CatchNearbyPokemonsTask.<Execute>d__1.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   bei PoGo.NecroBot.Logic.Tasks.FarmPokestopsTask.<Execute>d__1.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   bei PoGo.NecroBot.Logic.State.FarmState.<Execute>d__0.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   bei PoGo.NecroBot.Logic.State.StateMachine.<Start>d__4.MoveNext()

**Comment by hardknoxni69a** [comment]
sorry but german logs are no good please reopen in english to get help
