### ISSUE TITLE
Bot error when running out of pokeballs.

### ISSUE THREAD

**Issue by Luddlba** [Necrobot-Private/NecroBot#1345]
Well, folks, I use two Pokemon go accounts with Necrobot, using the Pokehash api, both with the same config. It turns out that in only one of the accounts, I notice a bot difficulty, because there comes a time when the account runs out of pokeballs and it can not stop at pokestops. In fact, it does nothing else.

The code that appears on the console is: "(INFO) Out of Pokeballs. Waiting {0} minute (s) until catching again."

please help me. thank you.

**Comment by hardknoxni69a** [comment]
well u need to give it time to loot stops or else  it will attempt to catch the same pokemon over and over with no balls adjust the wait time so it will go get stops
