### ISSUE TITLE
SnipeLocationServer option still has issues

### ISSUE THREAD

**Issue by LSAC-Hao** [Necrobot-Private/NecroBot#1347]
Even though I can turn on SnipeLocationServer and send coords into NecroBot, SnipePokemonTask doesn't seem ever being called any more.

**Comment by LSAC-Hao** [comment]
If there is an issue for SnipeLocations to utilize snipe filters, any chance you can change the code to put snipe info into MSniper collection instead of SnipeLocations collection. This way the coords that sent in via SnipeLocationServer can be sniped as well.

**Comment by Lord-Haji** [comment]
Be clear :)

**Comment by LSAC-Hao** [comment]
Okay. SnipeLocationServer was brought back from here, https://github.com/Necrobot-Private/NecroBot/pull/1160
But the program never snipe those coords. I wouldn't find anywhere it actually calls SnipePokemonTask.Execute. It seems to me only SnipePokemonTask.Start get call to receive coords info but no logic to actually snipe them.

**Comment by hardknoxni69a** [comment]
The snipe location server is to allow it to receive coords to do a snipe from your server I don't believe it sifts through the info to snipe. You need to set your snipe server to send it's snipe to necrobot but necrobot isn't gonna search through the server to get coords it just allows it to receive the snipe command pretty sure. Like the pokesnipers app before u could set it to auto snipe by turning on the server you are just allowing necrobot to receive those Snipes

**Comment by LSAC-Hao** [comment]
Following are some examples that my server sent to necrobot after it connected to my server. How do I make necrobot to snipe them?
{"Id":"129","Latitude":"-33.73963542","Longitude":"151.1525633","IV":"100","ExpirationTimestamp":"Mar 23 2017 19:32:02","TimeStampAdded":"Mar 23 2017 19:08:19"}
{"Id":"124","Latitude":"-33.81841753","Longitude":"151.0739293","IV":"97","ExpirationTimestamp":"Mar 23 2017 19:33:50","TimeStampAdded":"Mar 23 2017 19:08:19"}
{"Id":"121","Latitude":"-33.8911312","Longitude":"151.20145638","IV":"93","ExpirationTimestamp":"Mar 23 2017 19:25:51","TimeStampAdded":"Mar 23 2017 19:08:19"}
{"Id":"36","Latitude":"-33.67124192","Longitude":"151.28862725","IV":"93","ExpirationTimestamp":"Mar 23 2017 19:30:55","TimeStampAdded":"Mar 23 2017 19:08:19"}

**Comment by Lord-Haji** [comment]
Not applicable any more
