### ISSUE TITLE
NecroBot-Private for Pokémon GO not responding

### ISSUE THREAD

**Issue by Acogero** [Necrobot-Private/NecroBot#1348]
I try open the NecroBot.Console (Legacy 0.45 API) and when I pressed OK:

[23:50:11] () Exception caught, writing LogBuffer.

Exceção Sem Tratamento: PokemonGo.RocketAPI.Exceptions.AuthConfigException: No API method being select in your auth.json
   em PokemonGo.RocketAPI.Client..ctor(ISettings settings) na c:\projects\necrobot2\FeroxRev\Client.cs:linha 119
   em PoGo.NecroBot.Logic.State.Session.Reset(ISettings settings, ILogicSettings logicSettings)
   em PoGo.NecroBot.Logic.State.Session..ctor(GlobalSettings globalSettings, ISettings settings, ILogicSettings logicSettings, IElevationService elevationService, ITranslation translation)
   em PoGo.NecroBot.CLI.Program.RunBotWithParameters(Action`2 onBotStarted, String[] args)
   em PoGo.NecroBot.CLI.Program.Main(String[] args)

What I doing wrong ?

**Comment by hardknoxni69a** [comment]
umm the answer is in your post it says u havent selected a method
you need an api key and set it up to use it for basic questions please join our discord
