### ISSUE TITLE
Request -- Switch Account when catch limits reached

### ISSUE THREAD

**Issue by LSAC-Hao** [Necrobot-Private/NecroBot#1357]
In multiple bot situation, when an account reaches pokemon catch limit, necrobot should switch to next account after bag is filled. In present version, I noticed that bot keeps walking through pokestops and recycling without switch to next account. It is not that efficient regarding gaining max xp.

**Comment by Lord-Haji** [comment]
I don't recommend this.
As if the user is already running multiple accounts of bots already. It will get sooftbanned.
