### ISSUE TITLE
necrobot dont work for me [HELP]

### ISSUE THREAD

**Issue by jematierik** [Necrobot-Private/NecroBot#1359]
what does this mean?

[21:11:01] () Configuration is up-to-date. Schema version: 21
[21:11:02] () Validating config.json...
[21:11:03] () Auth Configuration is up-to-date. Schema version: 21
[21:11:03] () Validating auth.json...
[21:11:05] (INFO) Switching to jematie..
[21:11:05] (INFO) jematie (Level: ??)			Runtime : 00:00:00:00
[21:11:06] (INFO) Your IP is: ........
[21:11:06] (UPDATE) Perfect! You already have the newest Version 1.0.0.144
[21:11:06] (INFO) Logging in using Ptc jematie
[21:11:06] (INFO) System.MissingMethodException: Methode niet gevonden: !!0[] System.Array.Empty().
   bij PokemonGo.RocketAPI.Rpc.Player.<GetPlayer>d__9.MoveNext()
   bij System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   bij PokemonGo.RocketAPI.Rpc.Player.GetPlayer(Boolean addCommonRequests)
   bij PokemonGo.RocketAPI.Rpc.Login.<DoLogin>d__10.MoveNext() in c:\projects\necrobot2\FeroxRev\Rpc\Login.cs:regel 171
--- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
   bij System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bij System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   bij PoGo.NecroBot.Logic.State.LoginState.<Execute>d__3.MoveNext()

**Comment by cj3n** [comment]
0.59.1 update was pushed out today.

**Comment by OnePunch87** [comment]
Similar error for me but also before the new 0.59.1 update...is several days that there is login error for me.
I restart many Times but not work 
I ive also buy the key but nothing

**Comment by LimitedOC** [comment]
yeah i have the same problem too! restarts - re/downloads etc. (with a key that i bought 4 days now)

**Comment by OnePunch87** [comment]
Please help us!!

**Comment by LimitedOC** [comment]
Today my problem is solved. The bot is working

**Comment by cj3n** [comment]
Hash server probably needed updated to the latest api

**Comment by OnePunch87** [comment]
For me not working after several and many many times of login....
it's impossible same Bot and release go well only part time or only to lucky guys :((

**Comment by FureszOszkar** [comment]
Yes not working: Your API key ,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,, is incorrect or expired, please check auth.json (Pokefamer message : Unauthorized)

**Comment by cj3n** [comment]
If you want to keep your account I would wait.

**Comment by OnePunch87** [comment]
Guys need the new framework of microsoft(the lady one) , is in the old version of necrofori in a link...but anyone repeat or fix the link in the other new versions...

**Comment by cj3n** [comment]
Latest one I could find: https://www.microsoft.com/en-us/download/details.aspx?id=53344

**Comment by iSporean** [comment]
Bought my 2nd API key and now bot not working because of this
(ERROR) Your API key xxxxxxxxxxxxxxxxxxxxxxx is incorrect or expired, please check auth.json (Pokefamer message : Unauthorized)
Developers can you advise what is wrong ??? TKS

**Comment by FureszOszkar** [comment]
I think its a Pokefarmer hashing problem.

**Comment by weezingrogue** [comment]
I'd love an answer to this issue, all my Google accounts work just fine. My PTC accounts I get this same thing
