### ISSUE TITLE
Not Evolving Pokemon.

### ISSUE THREAD

**Issue by F-22man** [Necrobot-Private/NecroBot#1361]
### Expected Behavior:
Evolve Pokemon, it is set to evolve any Pokemon it has enough candies for or transfer any. It can transfer, just not anymore for some reason. It used to transfer all the time. 

### Actual Behavior:
Doesn't evolve anything, locks up bot because it can not transfer nor evolve any Pokemon (not sure why). Keeps going back and fourth. 
http://imgur.com/a/Z2Rjc
### Your config.json:
```
[config.txt](https://github.com/Necrobot-Private/NecroBot/files/869798/config.txt)


```

### Detailed Steps to Reproduce:
1.) Fill up Pokemon inventory
2.) Watch

### Other Information
(Attach zip files if needed.)

Version:
Windows Version: 10 
What is affected: Everything except navigating via Google Walk.

**Comment by Lord-Haji** [comment]
This is reported.please look through the issues before filing a new one
