### ISSUE TITLE
[BUG] Issue with leveling the first account into a multibot configuration

### ISSUE THREAD

**Issue by redking974** [Necrobot-Private/NecroBot#1363]
### Expected Behavior:
Leveling with equality all accounts

### Actual Behavior:
Necrobot seems to have an issue with a multibor configuration. As the screenshot shows, lvl are less than following accounts, but the running times are much more higher than others.
![nb](https://cloud.githubusercontent.com/assets/23528297/24321908/f7434ad2-1158-11e7-8245-a2321f8e3deb.jpg)

### Your config.json:
```
  "MultipleBotConfig": {
    "RuntimeSwitch": 40,
    "RuntimeSwitchRandomTime": 10,
    "OnLimitPauseTimes": 15,
    "OnRarePokemon": true,
    "MinIVToSwitch": 100.0,
    "EXPSwitch": 20000,
    "PokestopSwitch": 200,
    "PokemonSwitch": 150,
    "PokemonPerHourSwitch": 100,
    "StartFromDefaultLocation": false,
    "PokestopSoftbanCount": 5,
    "DisplayList": true,
    "SelectAccountOnStartUp": false,
    "CatchFleeCount": 5,
    "SwitchOnCatchLimit": true,
    "SwitchOnPokestopLimit": true
  },

```

Version: 144
Windows Version: 10
What is affected (catch, transfer, favorite, GPX, evolve, recycle, snipe, human walk snipe, pokestops, powerup/levelup, other): leveling

**Comment by pisanggeni** [comment]
Yeah... if you setup a multi account for the first time , it will ALWAYS jacked the first account's log hours with exorbitant numbers!

Solution: Delete the SessionStats.db file from the "config - account" folder

**Comment by redking974** [comment]
Thanks @pisanggeni , I thought about this solution too, but it's very annoying :/
Hope that this issue could be fixed.
@hardknoxni69a

**Comment by hardknoxni69a** [comment]
Once u update ur session stats though the issue is gone anytime changing accounts it's good to.delete the sessionstats

**Comment by redking974** [comment]
Yeah, it's a manually fixed @hardknoxni69a . Not very good patch. Better fix will be to make a junk account at the first place, this way I don't have to check progression of the first account...

**Comment by hardknoxni69a** [comment]
You should create a request to have accounts.db deleted automatically upon
adding new account to help with that I wouldn't call it a bug but
inconvenient
