### ISSUE TITLE
Excel export error in version 144, candy value not exported correctly

### ISSUE THREAD

**Issue by Groenselboer** [Necrobot-Private/NecroBot#1364]
When exporting the list of pokemon to excel the candy field shows the following statement instead of the value and this for all the rows

"System.Threading.Task.Task'1[System.int32]"

This was still working in the previous version.

Would it also be possible to add the export of the catch location coordinates to the excel export feature?

**Comment by hardknoxni69a** [comment]
i dont recall there being any changes will try to take a look

**Comment by Lord-Haji** [comment]
Fixed at #1497
