### ISSUE TITLE
UPDATE TO SEE IF SHINY MAGIKARP/GYARADOS

### ISSUE THREAD

**Issue by blackmamba0024** [Necrobot-Private/NecroBot#1365]
PLEASE UPDATE YOUR MAGIKARP AND GYARADOS SO THAT WE CAN NOTICE IF ITS A SHINY ONE PLEASE I SNIPE ALL THE MAGIKARP BUT NONE OF THOSE ARE SHINY..

THANKS FOR THE REPLY..

**Comment by OnePunch87** [comment]
Shiny is random, if is shiny for me it's possibile that Pokémon is not shiny for you.
Niantic do this strategy to avoid that players run all to the same place and take the shiny together

**Comment by blackmamba0024** [comment]
I CAUGHT 200+ MAGIKARPS AND NONE OF THOSE ARE SHINY..
THERE IS ANY WAY TO KNOW HOW TO CAUGHT A SHINY BECAUSE IT WILL END ON MARCH 29 PLS REPLY..

**Comment by OnePunch87** [comment]
Shiny not finish in 29 but if now is difficut with event to bring it, After will be impossible😂

**Comment by nhumber** [comment]
see #1366 

simple integration, 

lets get this merged before event is over

**Comment by hardknoxni69a** [comment]
its getting worked on but without knowing the request response for shinies it hard to implement we need testers that have shinies to help contact haji on discord

**Comment by Lord-Haji** [comment]
Added #1366
