### ISSUE TITLE
When I open Necrobot and choose Legacy 0.45 API, I will have to force close.

### ISSUE THREAD

**Issue by JohndDooee** [Necrobot-Private/NecroBot#1367]
[18:22:03] () Exception caught, writing LogBuffer.

Onverwerkte uitzondering: PokemonGo.RocketAPI.Exceptions.AuthConfigException: No API method being select in your auth.json
   bij PokemonGo.RocketAPI.Client..ctor(ISettings settings) in c:\projects\necrobot2\FeroxRev\Client.cs:regel 119
   bij PoGo.NecroBot.Logic.State.Session.Reset(ISettings settings, ILogicSettings logicSettings)
   bij PoGo.NecroBot.Logic.State.Session..ctor(GlobalSettings globalSettings, ISettings settings, ILogicSettings logicSettings, IElevationService elevationService, ITranslation translation)
   bij PoGo.NecroBot.CLI.Program.RunBotWithParameters(Action`2 onBotStarted, String[] args)
   bij PoGo.NecroBot.CLI.Program.Main(String[] args)

-----------------

What am I doing wrong?

**Comment by Furtif** [comment]
No API method being select in your auth.json or use legacy api change settings

**Comment by JohndDooee** [comment]
Thanks for you fast reply, so how do I select the API method in the auth.json or use legacy API settings?

**Comment by Furtif** [comment]
legacy Is disable, please seek a more help at discord

**Comment by JohndDooee** [comment]
![p1](https://cloud.githubusercontent.com/assets/26692401/24334510/b33f928c-126b-11e7-91d8-3825121da912.png)
![p2](https://cloud.githubusercontent.com/assets/26692401/24334511/b40eb9a4-126b-11e7-94b4-f00532a91a23.png)
![p3](https://cloud.githubusercontent.com/assets/26692401/24334512/b62b5ec2-126b-11e7-8480-96fddb0cbdc8.png)

I made some screenshots, to clear it up :) Maybe this will help.

**Comment by Furtif** [comment]
choice pogodev api
"APIConfig": {
    "UsePogoDevAPI": true,
    "AuthAPIKey": "2F0N1F0P0A5M5E3O1I4X",
    "UseLegacyAPI": false,
    "DiplayHashServerLog": true
  },
