### ISSUE TITLE
need help!

### ISSUE THREAD

**Issue by zadikall** [Necrobot-Private/NecroBot#1369]
[16:36:33] () JSON Exception: Error reading JObject from JsonReader. Path '', line 0, position 0.
[16:36:33] () Exception caught, writing LogBuffer.

Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at PoGo.NecroBot.CLI.Program.RunBotWithParameters(Action`2 onBotStarted, String[] args)
   at PoGo.NecroBot.CLI.Program.Main(String[] args)

**Comment by garette1** [comment]
its a ban, i guess..

**Comment by zadikall** [comment]
but im not banned? how can that be

**Comment by garette1** [comment]
wait a while.if you not banned, you can log in after some time

**Comment by zadikall** [comment]
its been 4 days. and it says this everytime. i can log in to the game on phone but i cant with bot.

**Comment by macinmn** [comment]
looks like a config issue, probably missing a comma somewhere.  rollback to a previous json or start fresh

**Comment by zadikall** [comment]
ill try that, thank you.

**Comment by hardknoxni69a** [comment]
rty deleting your accounts .db we redid auth.json and it causes an issue and restart
