### ISSUE TITLE
[Features] Option to not collecting bonus item when level up

### ISSUE THREAD

**Issue by LSAC-Hao** [Necrobot-Private/NecroBot#1370]
It would be useful if we have an option not to collect bonus item when we level up during botting. This way when you ready to take over your bot account over level 30, 1st time you login on your mobile phone, you will get over 1000 items in your bag even though your bag size is 350.

**Comment by hardknoxni69a** [comment]
its impossible in client to not collect your items which is why we no longer allow not choosing name and collecting items we may add an option though as it seems other bots have no issues with bans for this option
