### ISSUE TITLE
My bot has been unable to work for five days

### ISSUE THREAD

**Issue by dillan88** [Necrobot-Private/NecroBot#1372]
After the start of the run, will continue to repeat the following situation:

 "--- before throwing the exception to the location of the location of the stack tracking end ---

   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   於 PokemonGo.RocketAPI.Helpers.RequestBuilder.<GetRequestEnvelope>d__14.MoveNext() 於 c:\projects\necrobot2\FeroxRev\Helpers\RequestBuilder.cs: 行 332

 "--- before throwing the exception to the location of the location of the stack tracking end ---
   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   於 PokemonGo.RocketAPI.Rpc.Player.<GetPlayer>d__9.MoveNext() 於 c:\projects\necrobot2\FeroxRev\Rpc\Player.cs: 行 140
.............................(Repeated)

How to solve this.

**Comment by hardknoxni69a** [comment]
make sure you are on latest version make sure you have .net 4.6.2 delete any unneccessary files accounts.db cache/temp
