### ISSUE TITLE
Version 144 so that my three computers can not use bot

### ISSUE THREAD

**Issue by dillan88** [Necrobot-Private/NecroBot#1376]
Version 144 so that my three computers can not use bot, all appear the same situation ...

I believe there are other people encounter this situation.

I can not be resolved, can only be forced to give up the game ...

![p_20170328_003137_1](https://cloud.githubusercontent.com/assets/23711348/24384114/23aa6a14-1394-11e7-86b0-f8304fe1cb68.jpg)
![p_20170328_003157_1](https://cloud.githubusercontent.com/assets/23711348/24384121/2e6ab65c-1394-11e7-88a5-25eb32edf642.jpg)

**Comment by hardknoxni69a** [comment]
says ur key is no good this is not an issue with necrobot please look into your hash ley
