### ISSUE TITLE
Shiny Pokemon

### ISSUE THREAD

**Issue by isveryfunny** [Necrobot-Private/NecroBot#1382]
"FavoriteMinIvPercentage": 100.0,
    "AutoFavoritePokemon": false,
    "AutoFavoriteShinyOnCatch": true,

I trun "AutoFavoriteShinyOnCatch" to true.
necrobot didn't favorited shiny Magikarp when I got it.
if I need to trun "AutoFavoritePokemon" to true from false?
but I don't want to favorite other iv100 except Magikarp.

**Comment by cocacolabanane** [comment]
11:36:10] (ERROR) Counld't start socket server at port 14251, this port maybe in use or block, please change config to other port and restart bot if you want to use web gui.

pls fix
