### ISSUE TITLE
Errors at Lauch (still works)

### ISSUE THREAD

**Issue by Experte9** [Necrobot-Private/NecroBot#1384]
### Expected Behavior:
Normal Launch

### Actual Behavior:
Lauch with many errors and need download laguage packs

### Your config.json:
```
[config.txt](https://github.com/Necrobot-Private/NecroBot/files/879742/config.txt)

```

### (OPTIONAL) Your Log:
```
[NecroBot2-2017-03-29-16-21-36.txt](https://github.com/Necrobot-Private/NecroBot/files/879746/NecroBot2-2017-03-29-16-21-36.txt)

```

### Detailed Steps to Reproduce:
I downloaded NecroBot2.Win and Source code (unzip both) and put NecroBot2.Win into Source code and lauch NecroBot2.Win

### Other Information
![unbenannt](https://cloud.githubusercontent.com/assets/20842528/24466209/550148fe-14b0-11e7-9da1-b2703b5252a5.PNG)

Version: v1.0.0.146
Windows Version: 10

**Comment by hardknoxni69a** [comment]
hoOh is how it is registered in necrobot just fix spelling and be fine. Schema is your guide

**Comment by Experte9** [comment]
and how is the correct spelling? Ho-Oh, ho-Oh, HoOh, Hooh?

**Comment by hardknoxni69a** [comment]
Yup u got it already just updating ur config to hoOh does the job
