### ISSUE TITLE
<Feature Request> Ability To Favorite Pokemon In GUI

### ISSUE THREAD

**Issue by TheHern** [Necrobot-Private/NecroBot#1385]
Guys love the app no complaints - mainly because I am so noob. I have noticed a few issues like parameters I have set are being followed but I will search the threads and do my due diligence.

Question: Can we add the ability to favorite a Pokemon from the GUI? I get a perfect Poke (or at least I think it is) and I would like to fave it. Can this be done currently? Am I missing something?

If not - can this be added?

Thanks for reading/replies and please forgive if this has already been posted/answered/fixed.

Cheers,

**Comment by hardknoxni69a** [comment]
you most certainly can 
![image](https://cloud.githubusercontent.com/assets/21132978/24483910/14684bb2-14c9-11e7-980c-94920ccef06a.png)

**Comment by TheHern** [comment]
Thank you for the fast response! Cheers all,
