### ISSUE TITLE
[ENHANCEMENT] Jerky movement imitating human movement pattern (Humanized Walk)

### ISSUE THREAD

**Issue by pisanggeni** [Necrobot-Private/NecroBot#1386]
One of the biggest giveaway for a bot and get banned is to check it's movement pattern. Right now, the bot moves on the map with a straight, sharp & inhuman movement.

### Expected Behavior:
Bot simulated jerky movement on map
![gps](https://cloud.githubusercontent.com/assets/21086147/24488478/53fe790e-1541-11e7-8b59-316008742e44.PNG)

![gps2](https://cloud.githubusercontent.com/assets/21086147/24488515/9161e182-1541-11e7-80c5-346bfaa29dd5.PNG)

### Actual Behavior:
![necro1](https://cloud.githubusercontent.com/assets/21086147/24488487/676e3fec-1541-11e7-9533-423e29e1b4e1.jpg)
![necro2](https://cloud.githubusercontent.com/assets/21086147/24488492/6e020d98-1541-11e7-9b3c-78276256a003.jpg)

**Comment by hardknoxni69a** [comment]
well if you have your bot following street maps its gonna stay on the streets you can set up gpx or not use streets but pokemon monitors yours gps distance not the exact pattern you follow i wouldnt worry but if anything just looks like your in a acar
