### ISSUE TITLE
Loop while attacking / train gym

### ISSUE THREAD

**Issue by cherryblin** [Necrobot-Private/NecroBot#1387]
Both Json validated. Checked for similar issues and none of them are resolved so far. 

### Expected Behavior:
Attack or train gym

### Actual Behavior:
Infinite loop with error, account switch doesn't help.

### Your config.json:
```
https://pastebin.com/WYJDD4qj
```
### (OPTIONAL) Your Log:
```
10:08:00] (GYM) Visited  Gym : Old Water Pump | Team Blue  | Gym points 2000
[10:08:00] (ERROR) Pokemon Servers might be offline / unstable. Trying again...
[10:08:00] (ERROR) Error: System.NullReferenceException: Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.
   w PoGo.NecroBot.Logic.Tasks.UseNearbyPokestopsTask.<Execute>d__9.MoveNext()
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   w PoGo.NecroBot.Logic.Tasks.FarmPokestopsTask.<Execute>d__1.MoveNext()
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   w PoGo.NecroBot.Logic.State.FarmState.<Execute>d__0.MoveNext()
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   w PoGo.NecroBot.Logic.State.StateMachine.<Start>d__4.MoveNext()

```
### Detailed Steps to Reproduce:
Pressed walkhere at map&journey tab on desired gym to attack / train. 

### Other Information
Error occurs also while bot encounter gym by himself (walk)

Version: 1.0.0.146
Windows Version: 7
What is affected: gym attack / train

**Comment by cherryblin** [comment]
Moders - (eg. @Lord-Haji , @nRod91) - DO NOT close the issue and redirect to other unsolved ones, just like you did before in:
#1251 
#1314
#1228
https://github.com/Necrobot-Private/NecroBot/issues/1314
https://github.com/Necrobot-Private/NecroBot/issues/1228
https://github.com/Necrobot-Private/NecroBot/issues/1314
https://github.com/Necrobot-Private/NecroBot/issues/1228

**Comment by hardknoxni69a** [comment]
gym is beta if a mod closes than the issue is being taking care of already in other issues. BETA means proceed with caution. to be honest bot to gain xp taking gyms is just bad for people who play the right way atleast spoof and battle yourself
