### ISSUE TITLE
Help Auto Snipe and Transfer.

### ISSUE THREAD

**Issue by LARaDaR** [Necrobot-Private/NecroBot#1391]
Hi. For the first time I installed NecroBot2 v1.0.0.146 NecroBot2.WinGUI. I just can not figure out how to set up that, the bot caught Pokémon automatically with only 100% IV. And if it catches less than IV to automatically transfer. And for a bot to catch only one Pokemon. How correctly to register settings? Tell me or show. I have not been able to set up 3 days, I'm catching everyone ...

**Comment by andeomontenegro** [comment]
https://github.com/Necrobot-Private/NecroBot/wiki/Config-auto-sniper

**Comment by LARaDaR** [comment]
In the latest version there are more settings. Those that are listed here are only part of the text that is in the config file. And I did as it says there, and still catches all the Pokémon. You can show an example as in the latest necrobot text that you need to write down.

**Comment by LARaDaR** [comment]
"SnipePokemonFilter": {
    "Lapras": {
      "SnipeIV": 100,
      "Moves": [],
      "Operator": "or",
      "VerifiedOnly": true,
      "Priority": 10,
      "AutoSnipeCandy": 2000,
      "Level": 0,
      "AllowMultiAccountSnipe": false,
      "AffectToPokemons": []
    },

вот такой текст у меня. и не хочет ловить 100%iv

**Comment by andeomontenegro** [comment]
"SnipeConfig": {
..
   "MinIVForAutoSnipe": 101,
...
}
  "SnipePokemonFilter": {
"Eevee": {
      "SnipeIV": 100,
      "Moves": null,
      "Operator": "and",
      "VerifiedOnly": false,
      "Priority": 10,
      "AutoSnipeCandy": 0,
      "Level": 20,
      "AllowMultiAccountSnipe": false,
      "AffectToPokemons": [
        "larvitar",
        "machop",
        "charmander",
        "chansey",
        "eevee",
        "bulbasaur",
        "squirtle",
        "poliwag",
        "venusaur",
        "charizard",
        "blastoise",
        "beedrill",
        "raichu",
        "sandslash",
        "nidoking",
        "nidoqueen",
        "clefable",
        "ninetales",
        "golbat",
        "vileplume",
        "golduck",
        "primeape",
        "arcanine",
        "poliwrath",
        "alakazam",
        "machamp",
        "golem",
        "rapidash",
        "slowbro",
        "blissey",
        "muk",
        "cloyster",
        "gengar",
        "exeggutor",
        "marowak",
        "hitmonchan",
        "lickitung",
        "rhydon",
        "chansey",
        "electabuzz",
        "gyarados",
        "lapras",
        "porygon",
        "vaporeon",
        "squirtle",
        "flareon",
        "porygon",
        "kabutops",
        "aerodactyl",
        "snorlax",
        "articuno",
        "zapdos",
        "moltres",
        "dragonite",
        "abra"
      ]
    }
  },

snipe 100iv & 22lv min listed pokemons

**Comment by LARaDaR** [comment]
and Transfer please!!!!!gooooood

**Comment by andeomontenegro** [comment]
set "AutoSnipeCandy": 2000 to 0
а то он конфеты фармит до 2000 и снайпит шлак :)

**Comment by LARaDaR** [comment]
ок. а трансфер как сделать чтобы выкидывал ниже 100 iv

**Comment by andeomontenegro** [comment]
"PokemonsTransferFilter": {

 "Dratini": {
      "KeepMinCp": 1,
      "KeepMinIvPercentage": 90.0,
      "KeepMinLvl": 22,
      "UseKeepMinLvl": true,
      "KeepMinOperator": "and",
      "KeepMinDuplicatePokemon": 3,
      "Moves": [],
      "DeprecatedMoves": null,
      "MovesOperator": "and",
      "CatchOnlyPokemonMeetTransferCriteria": false,
      "AffectToPokemons": [
        "larvitar",
        "magikarp",
        "machop",
        "charmander",
        "chansey",
        "bulbasaur",
        "squirtle",
        "snorlax",
        "eevee",
        "poliwag"
      ]
    }
}

**Comment by andeomontenegro** [comment]
только тут у меня 90 а то ничего не наловит.
