### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by lordxe** [Necrobot-Private/NecroBot#1397]
excepción no controlada: PokemonGo.RocketAPI.Exceptions.AuthConfigException: No API method being select in your auth.json
   en PokemonGo.RocketAPI.Client..ctor(ISettings settings) en c:\projects\necrobot2\FeroxRev\Client.cs:línea 119
   en PoGo.NecroBot.Logic.State.Session.Reset(ISettings settings, ILogicSettings logicSettings)
   en PoGo.NecroBot.Logic.State.Session..ctor(GlobalSettings globalSettings, ISettings settings, ILogicSettings logicSettings, IElevationService elevationService, ITranslation translation)
   en PoGo.NecroBot.CLI.Program.RunBotWithParameters(Action`2 onBotStarted, String[] args)
   en PoGo.NecroBot.CLI.Program.Main(String[] args)

hello i have this error, when select legacy api, this ocurre please help me

**Comment by jjskuld** [comment]
Legacy API is disabled. You need to buy a key now.

**Comment by lordxe** [comment]
ok thanks
