### ISSUE TITLE
Can't see the scroll bar

### ISSUE THREAD

**Issue by mkcs121** [Necrobot-Private/NecroBot#140]
I have already downloaded the latest GUI package, but still the scroll bars are missing in the pokemon, inventory list. Anyone experiencing the same issue?

Environment: Windows 10 64 bit

![bug](https://cloud.githubusercontent.com/assets/20946940/18522479/d0f05f44-7ae2-11e6-9595-9e5588ba6040.png)

**Comment by charilla** [comment]
i use this instead https://codeload.github.com/GediminasMasaitis/PokeEase/zip/master just run launch.bat

source: https://github.com/GediminasMasaitis/PokeEase

**Comment by ajns73** [comment]
@mkcs121 @charilla 's suggestion is great one and will work. This issue has been brought up a few times and closed/invalidated, but their is no discussion (that I can see) of why it was not addressed. They are dropping support for GUI maybe?

**Comment by jjskuld** [comment]
@ajns73 @mcks121 - We'll investigate.. looks like an issue with the embedded browser and PokeEase.

**Comment by ajns73** [comment]
@jjskuld Thanks.

**Comment by Silph-Road** [comment]
Closing Issue Fixed: https://github.com/GediminasMasaitis/PokeEase/issues/61
