### ISSUE TITLE
How to exclude pokemon from ther "Other" tab, in the Sniper Windows?

### ISSUE THREAD

**Issue by Asia81** [Necrobot-Private/NecroBot#1401]
Hi.
I have a lot of pidg shits, as well as Rhynorn and Dratini (I have already the most perfect Dragonite and Rhydon, so I don't care about them).
I also don't care about the catch farm of them for exp, I'm already at lv40.
http://image.noelshack.com/fichiers/2017/13/1491028743-00.png

Seriously, I have 9000 Dratini's candies xD

Do you know how to exclude them from the "Other" tab, in the Sniper Windows?

**Comment by hardknoxni69a** [comment]
there is already an issue open we are working on a filter for the sniping section to exclude results

**Comment by hardknoxni69a** [comment]
hopefully soon one of the main devs doesnt have internet right now so keep your ears open congrats lvl 40!!
