### ISSUE TITLE
Help Transfer

### ISSUE THREAD

**Issue by LARaDaR** [Necrobot-Private/NecroBot#1403]
У меня такая ситуация. я уже спрашивал но почемуто некро не выкидывает дубликаты. Мне нужно чтобы он оставлял только со 100% iv 2 дубликата с высшим lvl. К примеру у меня сейчас 3 покемона Growlithe со 100% iv но lvl 20,15, 23. мне нужно чтобы из этих 3 покемонов он оставил только 2 с высшим lvl. Как правильно прописать?как правильно прописать?И что еще нужно изменить? 

Вот так ничего не происходит:

  "PokemonsTransferFilter": {
    "Growlithe": {
      "KeepMinCp": 1110,
      "KeepMinIvPercentage": 100.0,
      "KeepMinLvl": 20,
      "UseKeepMinLvl": true,
      "KeepMinOperator": "and",
      "KeepMinDuplicatePokemon": 2,
      "Moves": [],
      "DeprecatedMoves": null,
      "MovesOperator": "and",
      "CatchOnlyPokemonMeetTransferCriteria": false,
      "AffectToPokemons": []
    }
  },

**Comment by LARaDaR** [comment]
И как заставить всех остальных покемонов также в трансфер как этого?

**Comment by Lord-Haji** [comment]
No other language except English is allowed on github.
Ask them in our Discord Server :D
