### ISSUE TITLE
Necrobot 2 line 41 position 12 

### ISSUE THREAD

**Issue by jbsior** [Necrobot-Private/NecroBot#1408]
## Stop! Before you create this issue (you can delete this section when opening the issue):
1. Have you searched to see if there are other Open/Closed issues for the same issue? If so, comment on that issue instead.
2. Have you validated that your config/auth.json and config/config.json is valid JSON? Use http://jsonlint.com/ to check.
3. If your question is referring to how to set up or use the bot, please join our discord instead of posting an issue: https://discord.gg/7FWyWVp 
4. Always confirm that your issue is reproducible, with the config you provide below.

### Expected Behavior:
Hey everyone Im new to github 
having a problem with authenticating into necrobot2 
I have a new API key that is authentic .
has anyone encountered this problem before? I have validated my Json config with no problems until booting into the program.

### Actual Behavior:
starts up at start of boot but unable to proceed further into process due to the issue 

### Your config.json:
```
{
  "AuthConfig": {
    "AuthType": "google",
    "GoogleUsername": "",
    "GooglePassword": "",
    "PtcUsername": null,
    "PtcPassword": null
  },
  "ProxyConfig": {
    "UseProxy": false,
    "UseProxyHost": null,
    "UseProxyPort": null,
    "UseProxyAuthentication": false,
    "UseProxyUsername": null,
    "UseProxyPassword": null
  },
  "DeviceConfig": {
    "DevicePlatform": "ios",
    "DevicePackageName": "custom",
    "DeviceId": "67eb849ca4c8c49a0ea50c464a66a241",
    "AndroidBoardName": null,
    "AndroidBootloader": null,
    "DeviceBrand": "Apple",
    "DeviceModel": "iPhone",
    "DeviceModelIdentifier": null,
    "DeviceModelBoot": "iPhone7,1",
    "HardwareManufacturer": "Apple",
    "HardwareModel": "N71AP",
    "FirmwareBrand": "iPhone OS",
    "FirmwareTags": null,
    "FirmwareType": "9.3.4",
    "FirmwareFingerprint": null
  },
  "APIConfig": {
    "UsePogoDevAPI": true,
    "AuthAPIKey": "9C1Z6F8K0P5A0N7R3Q3U",
    "UseLegacyAPI": false,
    "DiplayHashServerLog": false
  },
  "AllowMultipleBot": true,
  "Bots": [2]
}

```

### (OPTIONAL) Your Log
![screenshot 10](https://cloud.githubusercontent.com/assets/26844900/24582978/51b3a8d4-16f1-11e7-909a-6a8c27f7ff3c.png)

### Other Information

Version:
Windows Version:
What is affected (catch, transfer, favorite, GPX, evolve, recycle, snipe, human walk snipe, pokestops, powerup/levelup, other):

**Comment by jjskuld** [comment]
You're using an out of date auth.json file. What version are you using? In the most recent versions, the "AuthConfig" is removed, and the "Bots" is moved up.

Furthermore, the Bots should say:

```
"Bots" : [{
    "AuthType": "google",
    "GoogleUsername": "yourusername",
    "GooglePassword": "yourpassword",
    "PtcUsername": null,
    "PtcPassword": null
  }]

**Comment by jbsior** [comment]
you are right i am using an older version i'll re download the latest version. Thank you
I'll try to see if this would fix the problem
