### ISSUE TITLE
[v147] Necrobot doesn't close properly

### ISSUE THREAD

**Issue by redking974** [Necrobot-Private/NecroBot#1412]
### Actual Behavior:
It seems that Necrobot doesn't close properly with the new version (today's update v 147). After closing all my sessions and wanted to relaunch them, I obtain a lot of errors. So I go to task manager and see that a lot of DotNetBrowserChromium, conhost, and Necrobot2 (Win or CLI) remain active.
![dot](https://cloud.githubusercontent.com/assets/23528297/24585430/425e864e-178a-11e7-955f-b7bdb4186b65.jpg)

### Detailed Steps to Reproduce:
Open, wait & close

### Other Information
(Attach zip files if needed.)

Version: 147 !
Windows Version: 10
What is affected (catch, transfer, favorite, GPX, evolve, recycle, snipe, human walk snipe, pokestops, powerup/levelup, other): close

**Comment by CDAGaming** [comment]
@redking974 This issue has been fixed in the upcoming release of v148

**Comment by jjskuld** [comment]
Please check again if this is resolved in v148 and reopen if not

**Comment by redking974** [comment]
I can't try for now because I revert to 146 (before hash server issues) but I will try as soon as possible.
Thanks.
