### ISSUE TITLE
Necrobot [NecroBot2 v1.0.0.147] dont Start in Windows

### ISSUE THREAD

**Issue by Stancredi** [Necrobot-Private/NecroBot#1413]
Hey People,

i wanted to use Necrobot2 first time on my Comuputer.
After downloading the Console and Electron i started the Necrobot2.

When i use the Legacy Mode the Programm get an Error and i must close it.
Look the my Screenshots pls.

http://imgur.com/a/7FvI8

In the Logfile : [10:49:59] () Exception caught, writing LogBuffer.

I use Win10 and got Microsoft Net 4.6+

**Comment by redking974** [comment]
Legacy API is not support anymore. You have to buy a key here (https://talk.pogodev.org/d/51-api-hashing-service-by-pokefarmer). To be clear, Necrobot remains free, but you need a key.
Please close this issue if you understand the issue.

**Comment by Stancredi** [comment]
okay thanks

**Comment by Stancredi** [comment]
How can i close it? 💃

**Comment by redking974** [comment]
You need to click on the button "Close issue"
![](https://i.stack.imgur.com/vRuSR.png)
