### ISSUE TITLE
Necrobot-Private For Pokemon Go Has Stopped Working

### ISSUE THREAD

**Issue by Yorgito** [Necrobot-Private/NecroBot#1418]
### Your config.json:
```
There are a lot and I am new to this so I didn't know which one to use.

```

### (OPTIONAL) Your Log:
```
[19:33:36] () Exception caught, writing LogBuffer.

```

### Other Information
I downloaded:
NecroBot2.Console
NecroBot2.GUI.Electron
Screenshot of what it looks like
https://gyazo.com/a7b569b449a6ddd77ee492c4119c3591
Version: Latest of this post
Windows Version: 10

**Comment by CDAGaming** [comment]
@Yorgito You did not Select an API Type in APIConfig in auth.json. 

Since PoGoDev is the only api type supported, choose that, and use the following template for APIConfig:

Code:

"APIConfig": {
    "UsePogoDevAPI": true,
    "AuthAPIKey": "XXXXXXXXXXXXXXXXXXXX",
    "UseLegacyAPI": false,
    "DiplayHashServerLog": false
  }

**Comment by Yorgito** [comment]
I have to pay to use?

**Comment by CDAGaming** [comment]
@Yorgito Yes, you can get a key from PogoDev here: https://hashing.pogodev.org/

Legacy 0.45 API is no longer supported, as Niantic has blocked it
