### ISSUE TITLE
(ERROR) Error: SESSION INVALIDATED EXCEPTION (see also issue #1411 Problem with Necrobot)

### ISSUE THREAD

**Issue by cjhart** [Necrobot-Private/NecroBot#1419]
Anyone getting this:

**(ERROR) Error: SESSION INVALIDATED EXCEPTION**

The bots are restarting and resetting location each time.

The hashing server status looks ok: https://status.buddyauth.com/

Number of other people mention the problem in issue #1411 Problem with Necrobot.

**Comment by cherryblin** [comment]
I'm getting this as well since 148 update this morning. Bot is restarting with mentioned error approx once per minute regardless of it's activities, therefore being unable to work at all.

**Comment by CDAGaming** [comment]
This will be fixed soon Guys. PogoDev is working on this

**Comment by cjhart** [comment]
Thanks for the info.

**Comment by Asia81** [comment]
Sometimes, I have the error above, so ok I know I should wait for a fix (even if it wrk fine for now).
[17:02:29] (ERROR) Hashing Servers errors, throttling calls. SESSION INVALIDATED EXCEPTION
[17:02:30] (ERROR) Resetting position before relogging in.


But sometimes, I have also this error, it's the same kind of error ?
[17:02:30] (INFO) Logging in using Google XXXXXX@gmail.com
[17:02:32] (INFO) PokemonGo.RocketAPI.Exceptions.SessionInvalidatedException: SESSION INVALIDATED EXCEPTION
   à PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PerformRemoteProcedureCall>d__2`1.MoveNext() dans c:\projects\necrobot2\FeroxRev\Extensions\HttpClientExtensions.cs:ligne 142
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PerformThrottledRemoteProcedureCall>d__8`1.MoveNext() dans c:\projects\necrobot2\FeroxRev\Extensions\HttpClientExtensions.cs:ligne 173
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProtoPayload>d__0`1.MoveNext() dans c:\projects\necrobot2\FeroxRev\Extensions\HttpClientExtensions.cs:ligne 45
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à PokemonGo.RocketAPI.Rpc.BaseRpc.<PostProtoPayload>d__11`1.MoveNext() dans c:\projects\necrobot2\FeroxRev\Rpc\BaseRpc.cs:ligne 130
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à PokemonGo.RocketAPI.Rpc.BaseRpc.<PostProtoPayload>d__5`3.MoveNext() dans c:\projects\necrobot2\FeroxRev\Rpc\BaseRpc.cs:ligne 49
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à PokemonGo.RocketAPI.Rpc.Player.<GetPlayer>d__9.MoveNext() dans c:\projects\necrobot2\FeroxRev\Rpc\Player.cs:ligne 146
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à PokemonGo.RocketAPI.Rpc.Login.<DoLogin>d__10.MoveNext() dans c:\projects\necrobot2\FeroxRev\Rpc\Login.cs:ligne 171
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   à PoGo.NecroBot.Logic.State.LoginState.<Execute>d__3.MoveNext()
[17:02:53] (INFO) Logging in using Google XXX@gmail.com
