### ISSUE TITLE
PokeEase map doesn't work

### ISSUE THREAD

**Issue by jhellhound666** [Necrobot-Private/NecroBot#1426]
Expected Behavior: A working hub.
Actual Behavior: PokeEase Does not load.

My config.json: 
[config.txt](https://github.com/Necrobot-Private/NecroBot/files/901754/config.txt)

Version: 1.0.0.150
Windows Version: 8.1
What is affected: PokeEase Map

![necro](https://cloud.githubusercontent.com/assets/26820402/24742180/d0e0c42e-1ac6-11e7-9d44-f83c22118b5e.png)

**Comment by Lord-Haji** [comment]
Pretty sure it's coz session invalidation 
The bot gets disconnected again and again

**Comment by redking974** [comment]
Maybe that you've already done this, but have you check your port into the PokeEase GUI ?
I've seen that you config doesn't have the original setup for the port (14251)
