### ISSUE TITLE
Request) Level Limit / Have Bot Stop Botting Once Hit Say Lvl 30

### ISSUE THREAD

**Issue by OrdsonX** [Necrobot-Private/NecroBot#1427]
## **Expected Behavior:**

BOT would STOP when reached certain Level or SWITCH account when certain level reached.

## **Actual Behavior:**

That feature is currently unavaliable.

**Comment by hardknoxni69a** [comment]
likely be an option in player config

**Comment by CDAGaming** [comment]
Temporary implementation is in v153, but will likely change as well as become a config option
