### ISSUE TITLE
New GoogleAccount using bot

### ISSUE THREAD

**Issue by ValorRed** [Necrobot-Private/NecroBot#143]
I think there was a version, maybe 0.9.8.7, allowed me to use newly created Google account to login and choose the NickName, Starter Pokemon, CompleteTutorial all together, without the need to use a device to login to pokemon go first.

New with 0.9.9.2, I created 2 new google accounts, none of them can login, always "User credentials are invalid and login failed".  Do I have to use a mobile device to initial login to pokemon go before using it in bot? I have only 1 device, don't want to be flagged as violate the ToS by login these new account. Heard to change account after a week might be safe.

Is there anyone else tried with brand new Google account and having the same problem?

**Comment by ajns73** [comment]
@ValorRed I can't say for sure as I started botting well after I created my accounts. However, the bot asks, as part of setup, "Would you like to enable the Auto-Complete Tutorial Feature? Y/N" I assume that means that it will "do" the tutorial for you if it is enabled. That is as of 0.9.9.2. So I don't think that is the source of your login trouble unless it is broken.

**Comment by Silph-Road** [comment]
@everyone
Is there anyone else with a similar problem with Google accounts?

**Comment by ValorRed** [comment]
@ajns73 , Just tried start the config process from beginning, it does ask me "Would you like to enable the Auto-Complete Tutorial Feature? Y/N", and I put in everything. Still get "User credentials are invalid and login failed" in the end.

Anyone please try a new Google Account?

**Comment by CreativiTimothy** [comment]
Make sure the IP / proxy you use is the same as when you log into Google Chrome into your account. For example, my IP was 1.3.5.7 when I logged out and logged back in my Google account using a browser, and then I log in with the same IP into Necrobot.

Works for me 50% of the time

**Comment by ValorRed** [comment]
@CreativiTimothy will try. But it is harder for me, as the proxy I am using is keep changing it between 2. 

Will the login to Google has to be in Chrome browser's account setup ? Can I login to Gmail using Incognito Brower?

Can you elaborate what do you mean by 50%? Is it you got 50% chance the same ip, and Initial login to bot will then for sure work? Or even same IP, only 50% of your new account will work?

**Comment by FaruqX** [comment]
new ptc account got same problem

**Comment by hardknoxni69a** [comment]
I am 99% positive this is just a lag on niantic servers catching up with new accounts just verify that u have verified email and that u can login to PTC site and it will let you log in it took me almost 24 hours to login but it let me.login and when i say that i did try i was loggin on real device and bot and it just didnt allow me as if the account wasnt created yet but using same exact auth file it did work soon enough i do not believe this has anything at all to do with bot and would close issue because like i said it wouldnt let me login to real device either so not bots fault niantic servers are just taking a little to allow new accounts for some reason

**Comment by mo0ojava** [comment]
Interesting. Tried to login twice with a brand new **Google-account** but both failed with the same error as the above. Logging in with existing PTC-accounts worked though.

Suspecting this has to do with the account being brand new...

**Comment by ValorRed** [comment]
Ok guys, found the proof. This is definitely a bug. 
Tried my new google account with the latest version 0.9.9.5, still not working. Then, I got back the old version from NoxxDev: 0.9.7. This is probably the first time they introduced "AutoCompleteTutorial". Used it to start the new google account. All successful:
![image](https://cloud.githubusercontent.com/assets/20829876/18572652/06fa5e16-7b8b-11e6-92ee-997d3fbcfb51.png)

Then bring the account back to 0.9.9.5, happy botting. But please resolve the bug.

**Comment by hardknoxni69a** [comment]
It was probably just timing man because it wouldnt let me login in on the actual client either then poof started working out of nowhere and the new version can do tutorial too so if that had to do with it it would have worked too

**Comment by ValorRed** [comment]
It shall not be just timing. It's different with using the actual client. I had that same experience before.
For these new bot accounts (I created 2 for this testing), I had them for 2 days, tried it from time to time, always same error.  Just now, before trying 0.9.7, I used 0.9.9.5, still the same error.

**Comment by CreativiTimothy** [comment]
You have to log out of Chrome and log back in using your proxy IP. That means you'd prob have to go to control panel temporarily. Then, run Necro with the same proxy. You can turn off internet proxy (not bot proxy) once you're able to log in.

by 50% of the time, I mean I have to log out and log in a couple times before it works

**Comment by ValorRed** [comment]
@CreativiTimothy, your explanation cannot explain why I don't need to do anything for 0.9.7.
Unless you mean the newer version's login method is trying to mimic Android device: the login is actually going through Chrome (don't mean it is the true way Android doing things, just based on your explain, my speculation)? While the 0.9.7 stable login is actually flawed, and somehow we suspect Pokemon Go can sense if our login had gone through Chrome or not?

Then it's too dame complex.

**Comment by Silph-Road** [comment]
This is a server issue, not a bot issue, workaround: try the app and it also might give you error, then wait and try later.

**Comment by hardknoxni69a** [comment]
Im glad u guys closed this i said over and over it was server issue. No need to waste your time on something that isnt your fault now u can focus on better things they only listen to the big guys for some reason lol you guys aree the best
