### ISSUE TITLE
32 bits

### ISSUE THREAD

**Issue by andrealves426** [Necrobot-Private/NecroBot#1432]
I would like to know if it will have 32-bit version for download

**Comment by CDAGaming** [comment]
32 Bit Version of Necrobot have a false positive virus warning. It is currently in investigation as of why this occurs

**Comment by markfell** [comment]
Where to get 32 bit verson

**Comment by TriNtoro** [comment]
32 byte please...

**Comment by Furtif** [comment]
@TriNtoro try to compile sources in x86 or try #community_builds in chanel [discord](https://discord.gg/7FWyWVp) or try [rocketbot](https://github.com/TheUnnamedOrganisation/RocketBot/releases) is 32bits

**Comment by Lord-Haji** [comment]
AnyCpu was implemented
