### ISSUE TITLE
Map crashes with v153

### ISSUE THREAD

**Issue by pokegeel1** [Necrobot-Private/NecroBot#1446]
With the newest installation the bot crashes and exits in the WINGUI when opening the 'map' button. This is onl happening with the map button. All other buttons work fine

**Comment by Lord-Haji** [comment]
@pokegeel1 Use PokeEase for the time being while we investigate

**Comment by iSporean** [comment]
Lord-Haji thank you for the speedy updates.
Hv no problems with map but keep having this -
(ATTENTION) Couldn't establish the connection to necrobot socket server : ws://s2.mypogosnipers.com/socket.io/?EIO=3&transport=websocket
Should this be a concern ?

**Comment by pokegeel1** [comment]
Thanks, its is working again :-)
