### ISSUE TITLE
Couldn't estabilish the connection to necrobot socket server

### ISSUE THREAD

**Issue by maini20bg** [Necrobot-Private/NecroBot#1448]
Hi all, I have this error screen since yesterday, the config us default exept the option i added on PokemonNotToTransfer: "magikarp".
could you help me?
sniping is not working

**Comment by BrgyTanod** [comment]
+1 on this

**Comment by BrgyTanod** [comment]
+1 on this.

 [15:47:53] (ATTENTION) Couldn't establish the connection to necrobot socket server : ws://necrosocket.herokuapp.com/socket.io/?EIO=3&transport=websocket

**Comment by nRod91** [comment]
[+1]
[10:09:44] (ATTENTION) Couldn't establish the connection to necrobot socket server : ws://s1.mypogosnipers.com/socket.io/?EIO=3&transport=websocket

**Comment by iSporean** [comment]
Lord-Haji thank you for the speedy updates.
Hv no problems with map but keep having this -
(ATTENTION) Couldn't establish the connection to necrobot socket server : ws://s2.mypogosnipers.com/socket.io/?EIO=3&transport=websocket
Should this be a concern ?

**Comment by nRod91** [comment]
Solved for me!
Thx guys!

**Comment by Groenselboer** [comment]
Service restored, should work fine now. This can be closed

**Comment by iSporean** [comment]
thanks

**Comment by dineshhhh** [comment]
i have this same problem now! can someone help me out pls?

**Comment by Jeshper** [comment]
dineshhhh, I've been having the same issue for a day now.
Anybody know if the service is down?

**Comment by jesvinm** [comment]
me too have the same problem

**Comment by gammaroid** [comment]
Same issue as of yesterday! Is it server issues?

**Comment by djboy1971** [comment]
after updated to 1.0.0.157 yesterday, I still have this error....

**Comment by Ethan-Smith222** [comment]
i have the exact same (issue) although it still runs great

**Comment by zinzin64** [comment]
i have the same problem too !for 2 day now! necrobot snipe nothing just catch standar pokemon in pokestop,and the webpage mypogosniper.com works fine if somebody have a solution !

**Comment by OrdsonX** [comment]
Just to make it clear. Public Sniper Server is recently DDoS`ed by Vietnamise Hackers. Blame them for no access to it. As works will be made, issue investigated, etc etc. Access to it will be limited, unavaliable in upcoming days. Will go back to work eventually and remain free.

**Comment by jesvinm** [comment]
hope the problem will be solved soon

**Comment by zinzin64** [comment]
me too it s a great feature of necrobot!thanks for explain ordsonX !

**Comment by Ethan-Smith222** [comment]
Its fixed many many thanks :)

**Comment by zinzin64** [comment]
another ddos attack? snipe will down again fo all  or it s my config.json is bad configured?

**Comment by Ethan-Smith222** [comment]
another ddos

**Comment by Ethan-Smith222** [comment]
it went back up earlier today, is still working for you guys? (its gone down again for me)

**Comment by iSporean** [comment]
It's not working again.

**Comment by OrdsonX** [comment]
People keep hacking the FREE Public Sniper server causing it to crash.
Please feel free to donate and get access to a dedicated vip servers.
The free server will return shortly, in reasonable time manner.
Sorry for any inconvenience.

**Comment by zinzin64** [comment]
big thanks ordsonX !don t be sorry you re work is amazing and the server free !

**Comment by Ethan-Smith222** [comment]
it must have taken a long time to do all of this, i am defiantly going to donate

**Comment by zinzin64** [comment]
sorry i don t understand,is there a vip server who working?how do for coneect to it?just donate to mypogosniper?

**Comment by zinzin64** [comment]
i donate to mypogosniper for use private server so i have just to change server adress and add access key(when i received it) in config.json and it s ok?
