### ISSUE TITLE
1st Bot not playing and timer is inaccurate.

### ISSUE THREAD

**Issue by sarsjrn** [Necrobot-Private/NecroBot#1451]
I have a bot switch problem. The first account timer is inaccurate, it should read zero. The first account listed does not switch on to play. I am using SuperBuild Beta 5. The accounts.db, sessionstats.db were all deleted before implementating this version.
![capture](https://cloud.githubusercontent.com/assets/26520168/24839044/94bf1006-1d08-11e7-8136-fec997985182.JPG)

{
  "Bots": [
    {
      "AuthType": "ptc",
      "Username": "bot1",
      "Password": "pass1"
    },
    {
      "AuthType": "ptc",
      "Username": "bot2",
      "Password": "pass2"
    },
    {
      "AuthType": "ptc",
      "Username": "bot3",
      "Password": "pass3"
    },
    {
      "AuthType": "ptc",
      "Username": "bot4",
      "Password": "pass4"
    },
    {
      "AuthType": "google",
      "Username": "bot5",
      "Password": "pass5"
    },
    {
      "AuthType": "ptc",
      "Username": "bot6",
      "Password": "pass6"
    }
  ],
------------------------------------------------------------
,
  "MultipleBotConfig": {
    "RuntimeSwitch": 50,
    "RuntimeSwitchRandomTime": 1,
    "OnLimitPauseTimes": 0,
    "OnRarePokemon": false,
    "MinIVToSwitch": 101.0,
    "EXPSwitch": 1995000,
    "PokestopSwitch": 1200,
    "PokemonSwitch": 950,
    "PokemonPerHourSwitch": 40000,
    "StartFromDefaultLocation": true,
    "PokestopSoftbanCount": 100,
    "DisplayList": true,
    "SelectAccountOnStartUp": false,
    "CatchFleeCount": 10,
    "SwitchOnCatchLimit": true,
    "SwitchOnPokestopLimit": true
  }

**Comment by jjskuld** [comment]
Dup of #1392.
