### ISSUE TITLE
Help with key.. please;;

### ISSUE THREAD

**Issue by eversonpiza** [Necrobot-Private/NecroBot#1454]
Hi,

I just bought a key in https://honorbuddy.myshopify.com/

I wanted to bought a pokehash but I just finded pokefarmer, so I bought the pokefarmer, but I think the correct was a pokehash.

Can I change my key?

If not, where I can bought the correct key?

Thanks

**Comment by iSporean** [comment]
They will not change the key but you can ask for a refund and purchase the correct key  from here
https://talk.pogodev.org/d/51-api-hashing-service-by-pokefarmer

**Comment by jjskuld** [comment]
You can talk to the Pokefarmer support and ask them to switch it from a pokefarmer key to a hash key.
