### ISSUE TITLE
Walk Here Coords Incorrect

### ISSUE THREAD

**Issue by TheHern** [Necrobot-Private/NecroBot#1458]
Hi guys,

Looks like alot is going on. Here is a little issue/bug (i think) I have encountered.

When in HUB I click on a Pokestop, click walk here and I get this message: [11:57:33] (INFO) Target location [37.763833,37.763833] has been accepted. Bot will go there soon. But that is the wrong location.

When I do the same thing in MAP I get this: [11:58:43] (INFO) Target location [37.763833,-122.456209] has been accepted. Bot will go there soon. This IS the right location.

Any idea what's up? Hope this was helpful :)

Cheers all,

Version: .153
Windows Version: 10 
What is affected (catch, transfer, favorite, GPX, evolve, recycle, snipe, human walk snipe, pokestops, powerup/levelup, other):

**Comment by macinmn** [comment]
you're correct about this, but PokeEase (map HUB uses)  coords has been bad for a long time, kinda surprised it was never fixed.  lower priority issue I think and WinGUI Map works, thankfully and is a cleaner interface in my opinion.

**Comment by hardknoxni69a** [comment]
This is a bug i thought was fixed it's doing double latitude for some reason will see how to fix for you guys
