### ISSUE TITLE
[Collection] Client 0.37 force update?

### ISSUE THREAD

**Issue by vfuyong** [Necrobot-Private/NecroBot#146]
Can someone notify us that a force update has occurred with the following format. This information is useful for some sort. Thanks.

Region: US/AU/EU/HK/other
Platform: Android/iOS

**Comment by CreativiTimothy** [comment]
Someone mentioned there was a force update on 0.33 -> 0.35/0.37, but not sure about 0.35 -> 0.37

**Comment by erickerich** [comment]
Region: other
Platform: Android
force update on 0.33
but 0.35 still works

**Comment by AndikaTanpaH** [comment]
Region: other/ID
Platform: Android 0.35.0

no force update to 0.37.0

**Comment by evetaku** [comment]
Region: other
Platform: Android 0.35.0
no force update to 0.37.0
0.35 still works

**Comment by xrexmartinus** [comment]
Region: EU
Platform: Android 0.35.0
no force update to 0.37.0
(I'm using Nox App player)

**Comment by FureszOszkar** [comment]
Thx for the fresh infos!

**Comment by ValorRed** [comment]
Sorry a dumb question: Is our bot currently using 0.35 API?

**Comment by vfuyong** [comment]
@ValorRed Yes.

**Comment by jjskuld** [comment]
@vfuyong It 100% will not work if they force 0.37.

**Comment by FureszOszkar** [comment]
How's the force update going?

**Comment by xrexmartinus** [comment]
Region: EU
Platform: Android 0.35.0
still no force update to 0.37.0
(I'm still using Nox App player)

**Comment by FureszOszkar** [comment]
Thx!

**Comment by FureszOszkar** [comment]
How's the force update going?

**Comment by ValorRed** [comment]
Region: CANADA
Platform: Android 0.35.0
still no force update to 0.37.0

**Comment by FureszOszkar** [comment]
thx!

**Comment by FureszOszkar** [comment]
How's the force update going?

**Comment by EyeNS7** [comment]
Region: EU
Platform: Android
Update forced several hours ago

**Comment by Silph-Road** [comment]
@EyeNS7 from what version to what version? .33 to .37.1 or .35 to .37.1 ?

**Comment by Silph-Road** [comment]
@EyeNS7 try rolling back to .35 and see if it lets you play?

**Comment by EyeNS7** [comment]
35 to 37
Happened on NOX.
i was ignoring the update info, then some hours earier it auto updated itself. so i assume it is a force update.
I didnt try to roll back yet.

**Comment by Silph-Road** [comment]
Nah that sounds like an auto update.
A forced update is when after you log in game and it pops up a button telling you to update. 
It won't let you play... And when you click update it takes you to play store to install update.

**Comment by EyeNS7** [comment]
it just updated in the middle of the game earlier, without asking, i dont know ... i didnt expect it to auto update. but yeah, you are right, should have been a button there.
I just rolled back to .35 and it lets me play for now. sorry for the wrong info...

**Comment by xrexmartinus** [comment]
Region: EU
Platform: Android 0.35.0
still no force update to 0.37.0
(I'm using Nox App player without google login so it can't auto update)

**Comment by FureszOszkar** [comment]
Thx!

**Comment by FureszOszkar** [comment]
Pls. post the fresh status!

**Comment by xrexmartinus** [comment]
Region: EU
Platform: Android 0.35.0
still no force update to 0.37.0
(I'm still using Nox App player)

**Comment by FureszOszkar** [comment]
thx!

**Comment by FureszOszkar** [comment]
Pls. post the fresh status!

**Comment by vfuyong** [comment]
Region: AU
Platform: Android 0.35.0
No force update to 0.37 yet

**Comment by FureszOszkar** [comment]
Thx!

**Comment by helpmeplease1** [comment]
Region: ASIAN
Platform: Android 0.35
No force update to 0.37 yet
(I'm still using Nox App player)

**Comment by stefankoerner** [comment]
Region: EU
Platform: Android 0.35
No force update to 0.37 yet

**Comment by FureszOszkar** [comment]
Thank you!

**Comment by FureszOszkar** [comment]
I think Niantic  reconsider the root case...

**Comment by Aras84** [comment]
App update on ios out now....i wonder if they will force update soon!!

**Comment by Silph-Road** [comment]
0.39 still blocks root....

**Comment by helpmeplease1** [comment]
Region: ASIAN
Platform: Android 0.35
No force update to 0.37 yet
(I'm still using Nox App player)

**Comment by vfuyong** [comment]
0.39 is mainly bug fixes. According to software practice, people usually don't add new features in a maintenance release.

**Comment by FureszOszkar** [comment]
0.39 containts the pokemon catch position.....it can be dangerous, because the snipe catch a pokemon on an other continent...

**Comment by iwean** [comment]
Like @vfuyong said... .39 is a patch for bug fixes. The location been there in the first versions (when the transfer button is all the way at the bottom) but not shown up because that bug.

Actually every pokemons have an ID (on code) to identify where it's from.

**Comment by CreativiTimothy** [comment]
Any idea how to hide the location you caught it in your phone? Maybe an iOS or Android tweak? I don't want my friends to ask me where I got my Dragonites and Snorlaxes

**Comment by iwean** [comment]
^ downgrade to .35 or .37

**Comment by FureszOszkar** [comment]
Pls. post the fresh force update status! (0.35->0.39)

**Comment by stefankoerner** [comment]
0.35.0, Android, EU still running

**Comment by FureszOszkar** [comment]
thx!

**Comment by ajns73** [comment]
Region: US
Platform: Android 0.39.1
no force update to 0.39.1

Says: "minor text fixes" Android only. No force.

**Comment by Raverbunny** [comment]
0.35 force updated today (Aus region)

**Comment by stefankoerner** [comment]
0.35.0, Android, EU - FORCE UPDATE!!!

**Comment by zhiwei2017** [comment]
Gemany，ios 1.7.0 force update to 1.9.0

**Comment by Silph-Road** [comment]
Minimum Version .39 NOW, for all apps.

**Comment by jjskuld** [comment]
Closing this now.  See #285
