### ISSUE TITLE
Manual snipe doesn't have the same logic as internal snipe

### ISSUE THREAD

**Issue by redking974** [Necrobot-Private/NecroBot#1464]
### Expected Behavior:
I think that manual snipe should have the same logic as internal snipe.
In my example, I manually enter a command via Telegram to snipe a Snorlax IV93% LVL30. In my config, it have 2 reasons of snipe also on my 2nd account :
- into the snipe section, it's configured to snipe Snorlax > IV90% and LVL28 (my Snorlax meets criterias) and I allow multisnipeaccount
- into the botswitch section, it's configured to switch if Snorlax > IV70% and LVL28 (my Snorlax meets criterias)

### Actual Behavior:
No switch (manual switch is needed), even if Necrobot has the right data after the encounter (and so the catch on the 1st account)
[XX:29:06] (POKEMON) (Capturé) | (Normal) Ronflex Lvl: 30 CP: (2841/3355) IV: 93.00% | Chance: 17.39% | dist 5729002.49m | 194 HyperBall restante(s) | 260XP | 235 Bonbons | lat: 41.386097 long: -73.445414 | Move1: ZenHeadbuttFast Move2: HyperBeam

### Your config.json:
```
    "Dragonite": {
      "SnipeIV": 90,
      "Moves": [],
      "Operator": "or",
      "VerifiedOnly": false,
      "Priority": 1,
      "AutoSnipeCandy": 0,
      "Level": 28,
      "AllowMultiAccountSnipe": true,
      "AffectToPokemons": [
        "snorlax",
        "blissey",
        "tyranitar"
      ]
    },

    "Lapras": {
      "IV": 70,
      "RemainTimes": 0,
      "Operator": "and",
      "AffectToPokemons": [
        "gyarados",
        "aerodactyl",
        "dragonite",
        "snorlax",
        "pupitar",
        "larvitar",
        "tyranitar",
        "blissey"
      ],
      "LV": 28,
      "Moves": []
    },
replace this text with the contents of your config.json

```

### (OPTIONAL) Your Log:
```
[XX:25:44] (INFO) Pokestop Voiture parking Victor Hugo à 1m | 0s (route Google Walk)
[XX:26:24] (INFO) (CATCH LIMIT) 333/624
[XX:26:24] (POKEMON) (Capturé) | (Normal) Ledyba Lvl: 1 CP: (10/664) IV: 22.00% | Chance: 100% | dist 0.00m | 20 SuperBall restante(s) | 260XP | 509 Bonbons | lat: 44.835267 long: -0.572369 | Move1: TackleFast Move2: AerialAce
[XX:26:56] (POKESTOP) La Griolle +50XP | 0 Gems | 1 x ItemPinapBerry, 1 x ItemPokeBall, 1 x ItemGreatBall, 1 x ItemRazzBerry
[XX:26:56] (INFO) (POKESTOP LIMIT) 349/1149
[XX:27:48] (POKESTOP) Voiture parking Victor Hugo +50XP | 0 Gems | 3 x ItemPokeBall, 1 x ItemGreatBall
[XX:27:48] (INFO) (POKESTOP LIMIT) 350/1151
[XX:27:52] (INFO) Pokestop Porte de la Grosse Cloche à 105m | 42s (route Google Walk)
[XX:28:09] (INFO) (MANUAL SNIPER) Pokemon added |  Snorlax [41.38607,-73.44547] IV 0%
[XX:28:20] (SNIPER) (InternalSnipe) [Sniper] Scan d'un Ronflex avec Inconnu% IV à 41.38607,-73.44547...
[XX:28:56] (BAIE) Baie Framby utilisé, 2 restante(s)
[XX:29:06] (INFO) (CATCH LIMIT) 334/633
[XX:29:06] (POKEMON) (Capturé) | (Normal) Ronflex Lvl: 30 CP: (2841/3355) IV: 93.00% | Chance: 17.39% | dist 5729002.49m | 194 HyperBall restante(s) | 260XP | 235 Bonbons | lat: 41.386097 long: -73.445414 | Move1: ZenHeadbuttFast Move2: HyperBeam
[XX:29:58] (POKESTOP) Instrument de Musique +50XP | 0 Gems | 2 x ItemPokeBall, 1 x ItemGreatBall
[XX:29:58] (INFO) (POKESTOP LIMIT) 351/1183
```

### Other Information
(Attach zip files if needed.)

Version: 153
Windows Version: 10
What is affected (catch, transfer, favorite, GPX, evolve, recycle, snipe, human walk snipe, pokestops, powerup/levelup, other): switch

**Comment by hardknoxni69a** [comment]
Bot Should Recognize Multi Bot Switch Settings Even On Manual Snipe

**Comment by redking974** [comment]
Since it have been verified by you, one of hypothesis could be because when you do a manual snipe Necrobot considers the IV and level as unknown. Maybe the logic/conditions could be verified after the encounter (or the catch if bot success it), and it will work for autosnipe and for manual snipe.
Regards.

**Comment by redking974** [comment]
I made some investigations @hardknoxni69a , I think that "AffectToPokemons" is not effective into BotSwitch and/or Snipe sections. Have you feedback about this ?
If I add one filter for snorlax into one config, it will switch whereas it will not switch on the config where snorlax is added into "AffectToPokemons"

**Comment by hardknoxni69a** [comment]
hmm makes sense as i know the affectto wasnt fully configured for each section like the evolve sections wasnt working correctly. tbh im not sure if that ever got fixed

**Comment by redking974** [comment]
I thought for switching that Necrobot will more rely on the botswitch section, but on 2 configs with a snorlax with his own filter, one works the other doesn't switch.
I believe that it use the snipe section to switch instead of botswitch section (seems weird) because if I create a own filter for snorlax in each config (instead of using AffectToPokemons), it will switch but there is another issue because it won't switch on all my account ( #1515 )

I need to make some tests (to check that my 2 configs will switch now) but as you say I know that AffectToPokemons doesn't work on evolve section, so it could be an issue with this feature.

**Comment by redking974** [comment]
Ok @hardknoxni69a I close this issue because after days of logs I guess that it could be fixed by modification of the config.json. **I just recommand to not use AffectToPokemons on the snipe section** (maybe also on botswitch section, but I'm not sure of this).
But there is an issue with switch, it could be related to runtime issue (cf #1392). There is always one account when Necrobot won't never switch, on each of my several instances. I post logs in #1515 (this actual title "Manual snipe doesn't have the same logic as internal snipe" doesn't reflet the new issue). I try to find the logic of why Necrobot doesn't switch to these accounts, but my skills are not enough to find a solution. Hope that devs could be more efficient than me. Regards.
