### ISSUE TITLE
Bug in Bulk Transfer Option

### ISSUE THREAD

**Issue by krishnaraovs** [Necrobot-Private/NecroBot#1465]
After selecting few pokemons and clicked "Transfer All", but instead of "Yes" if we click "No" then manual transfer button text is remaining as "transferring..." and in disable condition even if we reselect the same pokemons transfer option is not working. We need to restart the bot to transfer again.
![pic1](https://cloud.githubusercontent.com/assets/25992303/24963647/cbb3974c-1fbc-11e7-9bba-0d5ce81630d7.jpg)
![pic2](https://cloud.githubusercontent.com/assets/25992303/24963655/d1d2ce9a-1fbc-11e7-889f-1560d6b0b8b0.jpg)

**Comment by redking974** [comment]
It's better than before. I remember than when I tried to make this (click "No" when confirmation box appears) one or 2 months ago Necrobot always crashed :)

**Comment by CDAGaming** [comment]
This Issue has been Officially Resolved as of v170+
