### ISSUE TITLE
Multiple pokemon locations

### ISSUE THREAD

**Issue by madeinlisboa** [Necrobot-Private/NecroBot#1466]
### Expected Behavior:
Pokemon location should be only one

### Actual Behavior:
Multiple countries and cities

### Your config.json:
(unnecessary)

### Detailed Steps to Reproduce:
My pokemon list shows pokemons from multiple countries, but the bot only has been in one city. Is this normal?

Version: 1.0.0.153
Windows Version: Windows 7
What is affected (catch, transfer, favorite, GPX, evolve, recycle, snipe, human walk snipe, pokestops, powerup/levelup, other): Pokemons
![imagem 1](https://cloud.githubusercontent.com/assets/27363132/24967631/ac55a4d6-1fa2-11e7-9bce-0bccff0801c9.jpg)

**Comment by hardknoxni69a** [comment]
this what happens when you snipe turn off sniping and it will only play locally
