### ISSUE TITLE
Servers under maintenance?

### ISSUE THREAD

**Issue by marinilton** [Necrobot-Private/NecroBot#1468]
Are the servers under maintenance?
I am not able to connect this informing that "Attention couldn't establish the connection to necrobot... "

**Comment by Wolfie3335** [comment]
I was having the same issues. Happened a lot yesterday as well. The servers are under maintenance. You can look here     http://necrosocket.herokuapp.com/

**Comment by marinilton** [comment]
nice, tanks!

**Comment by Nizur07** [comment]
17:03:32] (ATENCIÓN) Couldn't establish the connection to necrobot socket server : ws://necrosocket.herokuapp.com/socket.io/?EIO=3&transport=websocket?? Is cus the mant? Sniper will be back up?
