### ISSUE TITLE
How to kill Blissey?

### ISSUE THREAD

**Issue by Dracosha17** [Necrobot-Private/NecroBot#1469]
Tell me how to cope with this task? There is not enough time for destruction. It can be like that you can reduce the time between attacks. Without bot, I destroy without problems the same tyranitors and dragons?

**Comment by redking974** [comment]
You could ask your question into Discord server https://discord.gg/7FWyWVp

The support you use if for issues. Yours isn't issue. You will have more help into the Discord server.
And close the "issue" if you could do it. Regards.
