### ISSUE TITLE
I want my bot to ONLY snipe and not to catch any pokemon he sees

### ISSUE THREAD

**Issue by Tsunamey** [Necrobot-Private/NecroBot#1475]
my bot catches way to many pokemon i don't need like pidgeys or rattatas or pidgeottos or pidgeot or raticates and all that crap.
So my question is if there is some setting that my bot only snipes and not catches random pokemon?
Thanks!

**Comment by krishnaraovs** [comment]
Add the pokemons to "PokemonsToIgnore" filter so that bot will ignore the unwated pokemons, Disable Humanwalksnipeconfig  & Pokemonconfig->catchpokemon.
