### ISSUE TITLE
Skipping the snipe list

### ISSUE THREAD

**Issue by krishnaraovs** [Necrobot-Private/NecroBot#1476]
When a list of pokemons added & when bot started to snipe, if we added few more to that list bot ignoring previous list and continuing from the newly added
![skip_snipe](https://cloud.githubusercontent.com/assets/25992303/24996012/c37c591e-204e-11e7-9b13-9bdc1e46ae12.jpg)

**Comment by Lord-Haji** [comment]
@krishnaraovs I have noticed that you have submitted lots of duplicate bug reports.
**Please stay a bit conscious from the next time before submitting the Issue**

Happy Botting :P
