### ISSUE TITLE
A key problem

### ISSUE THREAD

**Issue by zsatanxz** [Necrobot-Private/NecroBot#148]
@LobsterX 
![4](https://cloud.githubusercontent.com/assets/21266188/18520967/55c109ee-7ad4-11e6-88e2-44bedd3b60ef.jpg)
![5](https://cloud.githubusercontent.com/assets/21266188/18520970/5952da6a-7ad4-11e6-9b65-d5b28546dc65.jpg)

use is key , because in the picture.
mykey1
mykey1agin
mykey2
mykey3
This normal?

  "GoogleWalkConfig": {
    "UseGoogleWalk": true,
    "DefaultStepLength": 1.3,
    "GoogleHeuristic": "walking",
    "GoogleAPIKey": "mykey1",
    "Cache": true,
    "GoogleElevationAPIKey": "mykey1agin"
  },
  "YoursWalkConfig": {
    "UseYoursWalk": false,
    "YoursWalkHeuristic": "bicycle"
  },
  "MapzenWalkConfig": {
    "UseMapzenWalk": true,
    "MapzenTurnByTurnApiKey": "mykey2",
    "MapzenWalkHeuristic": "bicycle",
    "MapzenElevationApiKey": "mykey3"
  },

**Comment by ajns73** [comment]
This looks correct (The Config).

**Comment by zsatanxz** [comment]
@ajns73 The second line walking...?

**Comment by iwean** [comment]
Yeah that's a bug (duplicate pokestop log)... but jjskuld has fixed that.
https://github.com/Necrobot-Private/NecroBot/commits/master

**Comment by zsatanxz** [comment]
I'm use key why second line in cmd dos
That normally

**Comment by ajns73** [comment]
@zsatanxz The config is correct the double readout was a bug. That should be solved, but I don't think the new code was pushed out yet.
