### ISSUE TITLE
[BUG] Catch/Pokestop Limit

### ISSUE THREAD

**Issue by Diegofr104** [Necrobot-Private/NecroBot#1482]
### Expected Behavior:

 When you reach the limit the bot stop to cath or spin pokestops 

### Actual Behavior:

When you reach the limit, the limit change constantly.

What is affected (catch, pokestops)

**Comment by jjskuld** [comment]
Do you have a screenshot or log?

**Comment by redking974** [comment]
I think he speaks about the random limits @jjskuld

**Comment by Zamuzo** [comment]
@jjskuld I have the same issue, the limit change constantly when i catch a new pokemon or spin pokestop. 

<img width="258" alt="capture d ecran 2017-04-14 a 11 23 04" src="https://cloud.githubusercontent.com/assets/14942807/25039655/0e7c7514-2105-11e7-8065-1d8c4853dc22.png">

<img width="174" alt="capture d ecran 2017-04-14 a 11 22 17" src="https://cloud.githubusercontent.com/assets/14942807/25039659/14359b70-2105-11e7-891a-9b8a5f26bcd6.png">

<img width="132" alt="capture d ecran 2017-04-14 a 11 24 21" src="https://cloud.githubusercontent.com/assets/14942807/25039660/161ab100-2105-11e7-876e-41d04719b3e1.png">

**Comment by redking974** [comment]
It's "normal". Necrobot have implemented a feature to random the Catch and Spin limits, to never stop catch and spin at the same number (ie 774 in your example).

**Comment by Zamuzo** [comment]
@redking974 Ok, thanks for your answer :D
