### ISSUE TITLE
(Request) Gym Wiki

### ISSUE THREAD

**Issue by hardknoxni69a** [Necrobot-Private/NecroBot#149]
Sorry To Open An Issue I'm Sure This Will Be Closed Right Away But Could We Add A Wiki For The Gym Config Properties. I Know The Rest Hasn't Been Updated Because You Guys Are Busy But For Newer Additions Could We Please Have A Wiki Category So They Are Configured Properly And We Understand Exactly What Each Property Is Doing. As Always Thank You SOO Much!!!

**Comment by CreativiTimothy** [comment]
Good idea. For the Wiki, let's just focus on vague options. We don't need explanations for every single line of the config yet. We need a wiki for vague options like Transfer"weak"Pokemon, GoogleHeuristic, TryCatchEmAll, AllowSpeedUp, and a couple more

**Comment by langit7** [comment]
Do the bot will collect coin after xtimes deploy ?

**Comment by iwean** [comment]
still progress on that...

**Comment by samuraitruong** [comment]
collect coin is super easy, I will added that in this weekend.

**Comment by FaruqX** [comment]
if possible, collect coin after the bot assign x gym?
