### ISSUE TITLE
Capture Issues

### ISSUE THREAD

**Issue by gabeit** [Necrobot-Private/NecroBot#1495]
I have a problem starting the bot. When it starts and the catch limit is 1000, but I always capture less, around 200 and when I capture those 200 I have to wait 24hs to re-capture. I can not make the most of it, here I make a mistake.
![de655a65c4d4c7f574d3ae99e77f7115](https://cloud.githubusercontent.com/assets/26823340/25061687/5baf0cb0-2192-11e7-8bf9-983de1d82ea9.png)

**Comment by jjskuld** [comment]
Can you post your full log showing this error?

**Comment by gabeit** [comment]
[NecroBot2-2017-04-09-17-41-01.txt](https://github.com/Necrobot-Private/NecroBot/files/923775/NecroBot2-2017-04-09-17-41-01.txt)

@jjskuld this?

**Comment by redking974** [comment]
In your log, you have (almost) reached your catch limit (952/975).

**Comment by jjskuld** [comment]
As redking already said, you caught more than 200 already. The limits are there for your protection, if you exceed the limits you have very high chance of ban.
