### ISSUE TITLE
Missed Pokemon icon in Pokemon List from #1 to #98 or #101 since release 156 GUI

### ISSUE THREAD

**Issue by informer0827** [Necrobot-Private/NecroBot#1498]
I observed there's missed pokemon icon regarding #1 to #101 (I guess) as attached screenshot.  
![image](https://cloud.githubusercontent.com/assets/26746922/25064797/9cf39392-2234-11e7-8dac-25d69cb15d2c.png)

**Comment by Lord-Haji** [comment]
It's already fixed in next version
