### ISSUE TITLE
New Version

### ISSUE THREAD

**Issue by Polytoxic75** [Necrobot-Private/NecroBot#1499]
The new Version is working great but what I don´t like is that you can´t see on the first look anymore how much pokemon/items you have.

**Comment by montolio** [comment]
+1 that is very annoying!

**Comment by eversonpiza** [comment]
+1

**Comment by eversonpiza** [comment]
The new left sidebar is pretty nice. But that info was so helpful.

My suggestion is to put this information in the header panel.

**Comment by nRod91** [comment]
+1

**Comment by pokegeel1** [comment]
+1

**Comment by CDAGaming** [comment]
Will work on this when i have time, am on a family vaca at this time
