### ISSUE TITLE
cannot connect necrobot socket server

### ISSUE THREAD

**Issue by ooctagon** [Necrobot-Private/NecroBot#1501]
The new Version is cannot connect necrobot socket server.

(ATTENTION) Couldn't establish the connection to necrobot socket server : ws://s1.mypogosnipers.com/socket.io/?EIO=3&transport=websocket

**Comment by Dartrixx** [comment]
i have the same issue, mut mister @Lord-Haji decided to remove it

**Comment by Lord-Haji** [comment]
@Dartrixx We are getting constant Reports about this, and we have been constantly telling on discord that the Snipe Data Server is a separate service, and I must take actions against you if u talk this way

Happy Botting :D

**Comment by Dartrixx** [comment]
oh im really sorry, i didnt know, btw i really like that bot, but that kinda bugs me, but discord link? so i can keep up to date? ty
