### ISSUE TITLE
Evolving

### ISSUE THREAD

**Issue by gatesjr83** [Necrobot-Private/NecroBot#1503]
ok so i am trying to make  necro evolve more than just rattata, cause for some reason that is all it is doing here is how i have it setup did i do it right and if so why is it not evolving anything else but rattata

    }
  },
  "PokemonEvolveFilter": {
    "Rattata": {
      "MinIV": 0.0,
      "MinLV": 0.0,
      "MinCP": 0.0,
      "Moves": [],
      "Operator": "or",
      "EvolveTo": "",
      "AffectToPokemons": [
        "zubat",
        "pidgey",
        "caterpie",
        "weedle",
	"hoothoot",
	"ledyba",
	"spinarak",
	"sentret",
	"natu"
      ],
      "FavoritedOnly": false,
      "MinCandiesBeforeEvolve": 0

**Comment by OrdsonX** [comment]
"Operator": "and",
"EvolveTo": "IN WHAT ?",

Bot doesent know in what to evolve unless you tell him.
Questions like that could be resolved in minutes on discord.
Dont post such silly questions over Github in a future.

**Comment by Zamuzo** [comment]
@OrdsonX  It is not mandatory to fill evolveTo field. @gatesjr83 EvolveTo for PokemonEvolveFilter is not implemented. See #1196

**Comment by gatesjr83** [comment]
ahh ok got ya thanks, i just been changing the name for right now since i didn't get a response i appreciate it @Zamuzo

**Comment by OrdsonX** [comment]
Dont you think it is already corrected since 7 March ? A bit outdated.
Will need to clarify with devs.
Im sure "EvolveTo": "", work now, and affect evolving.

**Comment by gatesjr83** [comment]
@OrdsonX so what is the correct aspects to use this then as i am not getting to do with by using and and changing parameters

**Comment by gatesjr83** [comment]
@Zamuzo here is what i did to get it to work

  "PokemonEvolveFilter": {
    "Pidgey": {
      "MinIV": 0.0,
      "MinLV": 0.0,
      "MinCP": 0.0,
      "Moves": [],
      "Operator": "or",
      "EvolveTo": "",
      "AffectToPokemons": [],
      "FavoritedOnly": false,
      "MinCandiesBeforeEvolve": 0
    },
    "Rattata": {
      "MinIV": 0.0,
      "MinLV": 0.0,
      "MinCP": 0.0,
      "Moves": [],
      "Operator": "or",
      "EvolveTo": "",
      "AffectToPokemons": null,
      "FavoritedOnly": false,
      "MinCandiesBeforeEvolve": 0
    },
    "Hoothoot": {
      "MinIV": 0.0,
      "MinLV": 0.0,
      "MinCP": 0.0,
      "Moves": [],
      "Operator": "or",
      "EvolveTo": "",
      "AffectToPokemons": null,
      "FavoritedOnly": false,
      "MinCandiesBeforeEvolve": 0
    },
    "Ledyba": {
      "MinIV": 0.0,
      "MinLV": 0.0,
      "MinCP": 0.0,
      "Moves": [],
      "Operator": "or",
      "EvolveTo": "",
      "AffectToPokemons": null,
      "FavoritedOnly": false,
      "MinCandiesBeforeEvolve": 0
    },
    "Spinarak": {
      "MinIV": 0.0,
      "MinLV": 0.0,
      "MinCP": 0.0,
      "Moves": [],
      "Operator": "or",
      "EvolveTo": "",
      "AffectToPokemons": null,
      "FavoritedOnly": false,
      "MinCandiesBeforeEvolve": 0
    },
    "Sentret": {
      "MinIV": 0.0,
      "MinLV": 0.0,
      "MinCP": 0.0,
      "Moves": [],
      "Operator": "or",
      "EvolveTo": "",
      "AffectToPokemons": null,
      "FavoritedOnly": false,
      "MinCandiesBeforeEvolve": 0
    },
    "Natu": {
      "MinIV": 0.0,
      "MinLV": 0.0,
      "MinCP": 0.0,
      "Moves": [],
      "Operator": "or",
      "EvolveTo": "",
      "AffectToPokemons": null,
      "FavoritedOnly": false,
      "MinCandiesBeforeEvolve": 0
    },
    "Weedle": {
      "MinIV": 0.0,
      "MinLV": 0.0,
      "MinCP": 0.0,
      "Moves": [],
      "Operator": "or",
      "EvolveTo": "",
      "AffectToPokemons": null,
      "FavoritedOnly": false,
      "MinCandiesBeforeEvolve": 0
    }
