### ISSUE TITLE
Items don't recycle

### ISSUE THREAD

**Issue by madeinlisboa** [Necrobot-Private/NecroBot#1505]
### Expected Behavior:
Items should recycle when they reach the limit

### Actual Behavior:
No recycle

### Your config.json:
`  "RecycleConfig": {
    "VerboseRecycling": true,
    "RecycleInventoryAtUsagePercentage": 90.0,
    "RandomizeRecycle": true,
    "RandomRecycleValue": 3,
    "TotalAmountOfPokeballsToKeep": 120,
    "TotalAmountOfPotionsToKeep": 80,
    "TotalAmountOfRevivesToKeep": 60,
    "TotalAmountOfBerriesToKeep": 50,
    "UseRecyclePercentsInsteadOfTotals": false,
    "PercentOfInventoryPokeballsToKeep": 35,
    "PercentOfInventoryPotionsToKeep": 35,
    "PercentOfInventoryRevivesToKeep": 20,
    "PercentOfInventoryBerriesToKeep": 10
  }`

### Detailed Steps to Reproduce:
Items should recycle at 90%. My bag reached 500 for a maximum of 350

### Other Information
(Attach zip files if needed.)

Version: 1.0.0.157
Windows Version: 7
What is affected (catch, transfer, favorite, GPX, evolve, recycle, snipe, human walk snipe, pokestops, powerup/levelup, other): Items

**Comment by OrdsonX** [comment]
You set wrong Logic thats why , you recycling is affected. Dont forget that in config.json , Recycle logic doesent include Evolution items which take inventory space as well.

Basically if you dont use GYM then you can set an procentage values to recycle.
  "RecycleConfig": {
    "VerboseRecycling": false,
    "RecycleInventoryAtUsagePercentage": 50.0,
    "RandomizeRecycle": false,
    "RandomRecycleValue": 10,
    "TotalAmountOfPokeballsToKeep": 230,
    "TotalAmountOfPotionsToKeep": 10,
    "TotalAmountOfRevivesToKeep": 10,
    "TotalAmountOfBerriesToKeep": 100,
    "UseRecyclePercentsInsteadOfTotals": true,
    "PercentOfInventoryPokeballsToKeep": 70,
    "PercentOfInventoryPotionsToKeep": 0,
    "PercentOfInventoryRevivesToKeep": 0,
    "PercentOfInventoryBerriesToKeep": 30
  },

Again, if bot wouldnt Recycle, we would be flooded here with messages.

**Comment by madeinlisboa** [comment]
The values I was using were defaults. I thought that I had nothing to set there. Thanks
