### ISSUE TITLE
 (ATTENTION) Couldn't establish the connection to necrobot socket server

### ISSUE THREAD

**Issue by jaksh345** [Necrobot-Private/NecroBot#1507]
(ATTENTION) Couldn't establish the connection to necrobot socket server : ws://necrosocket.herokuapp.com/socket.io/?EIO=3&transport=websocket
[08:56:02] (INFO) Connecting to ws://s1.mypogosnipers.com/socket.io/?EIO=3&transport=websocket ....
[08:56:24] (ATTENTION) Couldn't establish the connection to necrobot socket server : ws://s1.mypogosnipers.com/socket.io/?EIO=3&transport=websocket

what do i do its keep on saying this when i start the bot and the bot is update

**Comment by gammaroid** [comment]
I'm having the same issue as well!

**Comment by byuntay** [comment]
The app is under maintenance. You can still use Necrobot, just not sniping.
Check http://necrosocket.herokuapp.com/ it says maintenance. When the site is back up, then it means you can use.

**Comment by jaksh345** [comment]
ok thank ill try that

**Comment by jaksh345** [comment]
it still doesnt work

**Comment by jaksh345** [comment]
disabled sniping and auto sniping

**Comment by chrisbirie** [comment]
I disabled everything in DataShareConfig then restarted the bot, that seemed to work
