### ISSUE TITLE
PokemonsToEvolve section constantly gets deleted by the bot

### ISSUE THREAD

**Issue by Xeph20** [Necrobot-Private/NecroBot#1509]
### Your config.json:

  "PokemonConfig": {
    "CatchPokemon": true,
    "DelayBetweenPokemonCatch": 2000,
    "UseCatchLimit": true,
    "CatchPokemonLimit": 700,
    "CatchPokemonLimitMinutes": 1350,
    "UseIncenseConstantly": true,
    "UseEggIncubators": true,
    "UseLimitedEggIncubators": true,
    "UseLuckyEggConstantly": false,
    "UseLuckyEggsMinPokemonAmount": 64,
    "UseLuckyEggsWhileEvolving": true,
    "TransferWeakPokemon": false,
    "TransferDuplicatePokemon": false,
    "TransferDuplicatePokemonOnCapture": false,
    "RenamePokemon": false,
    "RenameOnlyAboveIv": false,
    "RenameTemplate": "{Name}_{IV}_Lv{Level}",
    "FavoriteMinIvPercentage": 95.0,
    "AutoFavoritePokemon": true,
    "AutoFavoriteShinyOnCatch": true,
    "MaxPokeballsPerPokemon": 6,
    "UseGreatBallAboveCp": 1000,
    "UseUltraBallAboveCp": 1250,
    "UseMasterBallAboveCp": 1500,
    "UseGreatBallAboveIv": 85.0,
    "UseUltraBallAboveIv": 95.0,
    "UseGreatBallBelowCatchProbability": 0.2,
    "UseUltraBallBelowCatchProbability": 0.1,
    "UseMasterBallBelowCatchProbability": 0.05,
    "AutomaticallyLevelUpPokemon": false,
    "OnlyUpgradeFavorites": true,
    "UseLevelUpList": true,
    "AmountOfTimesToUpgradeLoop": 5,
    "GetMinStarDustForLevelUp": 5000,
    "LevelUpByCPorIv": "iv",
    "UpgradePokemonCpMinimum": 1000.0,
    "UpgradePokemonIvMinimum": 95.0,
    "UpgradePokemonMinimumStatsOperator": "and",
    "EvolveAboveIvValue": 95.0,
    "EvolveAllPokemonAboveIv": false,
    "EvolveAllPokemonWithEnoughCandy": true,
    "EvolveKeptPokemonsAtStorageUsagePercentage": 95.0,
    "EvolveKeptPokemonIfBagHasOverThisManyPokemon": 120,
    "KeepPokemonsThatCanEvolve": true,
    "KeepMinCp": 1250,
    "KeepMinIvPercentage": 90.0,
    "KeepMinLvl": 6,
    "KeepMinOperator": "or",
    "UseKeepMinLvl": false,
    "PrioritizeIvOverCp": true,
    "KeepMinDuplicatePokemon": 1,
    "KeepMaxDuplicatePokemon": 1000,
    "UsePokemonToNotCatchFilter": true,
    "UsePokemonToCatchLocallyListOnly": false,
    "DumpPokemonStats": false,
    "DelayBetweenPokemonUpgrade": 10000,
    "OutOfBallCatchBlockTime": 5,
    "PokeballToKeepForSnipe": 50,
    "UseBulkTransferPokemon": true,
    "BulkTransferStogareBuffer": 10,
    "BulkTransferSize": 100,
    "UseBallOperator": "or",
    "FavoriteMinCp": 0.0,
    "DefaultBuddyPokemon": "",
    "FavoriteMinLevel": 0,
    "FavoriteOperator": "and",
    "RenamePokemonRespectTransferRule": false,
    "UpgradePokemonLvlMinimum": 30.0,
    "EvolveFavoritedOnly": false,
    "EvolveOperator": "and",
    "EvolveMinIV": 100.0,
    "EvolveMinCP": 2000.0,
    "EvolveMinLevel": 25.0,
    "ByPassCatchFlee": false

### (OPTIONAL) Your Log:

[01:38:27] () Configuration is up-to-date. Schema version: 23
[01:38:27] () Validating config.json...
[01:38:31] () Auth Configuration is up-to-date. Schema version: 23
[01:38:31] () Validating Auth.json...
[01:38:34] (ERROR) Counld't start socket server at port 14251, this port may be in use or blocked, please change your config to another port and restart bot if you want to use web gui.
[01:38:36] (UPDATE) Perfect! You already have the newest Version 1.0.0.157
[01:38:57] (ATTENTION) Detected realistic Traveling , using Default Settings inside config.json
[01:38:57] (ATTENTION) Without a Google Api, you will have 2500 free quota limit, if you reach the maximum quota, try to change your IP. To configure "GoogleAPIKey", get API Key in link: https://developers.google.com/maps/documentation/directions/get-api-key
[01:39:02] (EVOLVED) Potential Evolutions: 0
[01:39:02] (INFO) Amount of Pokemon Seen: 238/231, Amount of Pokemon Caught: 238/231
[01:39:03] (SNIPER) Sniper count 0
[01:39:05] (INFO) Connecting to ws://necrosocket.herokuapp.com/socket.io/?EIO=3&transport=websocket ....
[01:39:22] (ATTENTION) Couldn't establish the connection to necrobot socket server : ws://necrosocket.herokuapp.com/socket.io/?EIO=3&transport=websocket
[01:39:27] (INFO) Connecting to ws://s1.mypogosnipers.com/socket.io/?EIO=3&transport=websocket ....
[01:39:27] (SNIPER) Sniper count 0

Version:
Windows Version: 10
What is affected (catch, transfer, favorite, GPX, evolve, recycle, snipe, human walk snipe, pokestops, powerup/levelup, other): evolve

**Comment by gatesjr83** [comment]
"PokemonEvolveFilter": {
"Pidgey": {
"MinIV": 0.0,
"MinLV": 0.0,
"MinCP": 0.0,
"Moves": [],
"Operator": "or",
"EvolveTo": "",
"AffectToPokemons": [],
"FavoritedOnly": false,
"MinCandiesBeforeEvolve": 0
},
"Rattata": {
"MinIV": 0.0,
"MinLV": 0.0,
"MinCP": 0.0,
"Moves": [],
"Operator": "or",
"EvolveTo": "",
"AffectToPokemons": null,
"FavoritedOnly": false,
"MinCandiesBeforeEvolve": 0
},
"Hoothoot": {
"MinIV": 0.0,
"MinLV": 0.0,
"MinCP": 0.0,
"Moves": [],
"Operator": "or",
"EvolveTo": "",
"AffectToPokemons": null,
"FavoritedOnly": false,
"MinCandiesBeforeEvolve": 0
},
"Ledyba": {
"MinIV": 0.0,
"MinLV": 0.0,
"MinCP": 0.0,
"Moves": [],
"Operator": "or",
"EvolveTo": "",
"AffectToPokemons": null,
"FavoritedOnly": false,
"MinCandiesBeforeEvolve": 0
},
"Spinarak": {
"MinIV": 0.0,
"MinLV": 0.0,
"MinCP": 0.0,
"Moves": [],
"Operator": "or",
"EvolveTo": "",
"AffectToPokemons": null,
"FavoritedOnly": false,
"MinCandiesBeforeEvolve": 0
},
"Sentret": {
"MinIV": 0.0,
"MinLV": 0.0,
"MinCP": 0.0,
"Moves": [],
"Operator": "or",
"EvolveTo": "",
"AffectToPokemons": null,
"FavoritedOnly": false,
"MinCandiesBeforeEvolve": 0
},
"Natu": {
"MinIV": 0.0,
"MinLV": 0.0,
"MinCP": 0.0,
"Moves": [],
"Operator": "or",
"EvolveTo": "",
"AffectToPokemons": null,
"FavoritedOnly": false,
"MinCandiesBeforeEvolve": 0
},
"Weedle": {
"MinIV": 0.0,
"MinLV": 0.0,
"MinCP": 0.0,
"Moves": [],
"Operator": "or",
"EvolveTo": "",
"AffectToPokemons": null,
"FavoritedOnly": false,
"MinCandiesBeforeEvolve": 0
}

**Comment by Xeph20** [comment]
thanks gatesjr83

the text doesnt get deleted but now there is no message about potentiol evolves and no evolves start
or might this be because of the settings that it needs more pokemon or candy? 
but i thought it would give a message saying how much morr i need before lucky egg kicks in ?

**Comment by hardknoxni69a** [comment]
it looks fine can you provide more details of exactly what happens

**Comment by jjskuld** [comment]
PokemonsToEvolve is no longer used, that is why it's removed. The new setting is PokemonEvolveFilter.
