### ISSUE TITLE
Couldn't establish the connection to sniper sites

### ISSUE THREAD

**Issue by ShortPT** [Necrobot-Private/NecroBot#1510]
Just always apear this lines:

http://prntscr.com/ex9eq7
http://prntscr.com/ex9eso

**Comment by shzhhua693** [comment]
Oh, I got the same issue! Who can help me?

**Comment by mavz1001** [comment]
+1 same problem i experience since last 2 days... i guess the site is under maintenance and i dont know when will it back

**Comment by jaksh345** [comment]
same here got the same issues

**Comment by hardknoxni69a** [comment]
site goes down occassionaly feel free to donate and get access to vip server
