### ISSUE TITLE
NEW VERSION NO SNIPE POKEMON?

### ISSUE THREAD

**Issue by blackmamba0024** [Necrobot-Private/NecroBot#1511]
WHY IS THE NEW VERSION IS NO POKEMON ON SNIPING??
NO RARE 100% OR OTHERS??

**Comment by OrdsonX** [comment]
By any chance you using Easter Config ?

**Comment by blackmamba0024** [comment]
THE LATEST VERSION I DOWNLOADED 157?

**Comment by byuntay** [comment]
please check http://necrosocket.herokuapp.com/ it is under maintenance

**Comment by blackmamba0024** [comment]
OKAY WHEN WILL IT BE FIXED?
AND OTHER VERSION ARE DOWN TOO?

**Comment by byuntay** [comment]
the sniping feature isn't part of necrobot so yes, all versions will be the same.
there is  nothing being fixed, just a maintenance. we are not sure when it will be finished so please wait patiently like everyone else.

**Comment by informer0827** [comment]
Well...
If fixed schedule can be estimated, then it won't be an issue.  
If it's an issue, then it couldn't estimated.......

**Comment by mavz1001** [comment]
SNIPING IS STILL ON BUT ONLY MANUAL SNIPING ^_^ I READ EARLIER IN A CLOSED THREAD THAT U NID TO DONATE TO ACCESS VIP TO ACCESS THE STABLE SNIPING TOOL

**Comment by jaksh345** [comment]
i agree with MAVZ1001 THAT U HAVE TO MANUAL SNIP BY UR SELF THATS WHAT IM DOING BUT I GOT THIS MESSAGE 
"The Niantic version check URL (https://pgorelease.nianticlabs.com/plfe/version) is returning an invalid version. This indicates that Niantic has changed something on their server and may indicate a forced API change. You may want to stop botting to be safe." 

I SAY DONT DO MANUAL SNIPING RIGHT NOW WAIT FOR  http://necrosocket.herokuapp.com/ TO GET BACK ON

**Comment by byuntay** [comment]
thank you for being patient everyone the site is back up so it should connect now!
