### ISSUE TITLE
Necrobot has transfered my magikarp Shiny

### ISSUE THREAD

**Issue by paragomba** [Necrobot-Private/NecroBot#1514]
There isnt any rule to avoid that.

**Comment by Maloculus** [comment]
In your Config.json, PokemonConfig section, there is an  AutoFavoriteShinyOnCatch line that is set to false.  Change this to true and that should protect any shinies the bot captures. 


"PokemonConfig": {
    "AutoFavoriteShinyOnCatch": true,

**Comment by hardknoxni69a** [comment]
cant help it if you dont set your config appropriately
