### ISSUE TITLE
Necrobot GUI Pokemon List bug

### ISSUE THREAD

**Issue by popsoda27** [Necrobot-Private/NecroBot#152]
## Stop! Before you create this issue (you can delete this section when opening the issue):
1. Have you searched to see if there are other Open/Closed issues for the same issue? If so, comment on that issue instead.
2. Have you validated that your config/auth.json and config/config.json is valid JSON? Use http://jsonlint.com/ to check.
3. If your question is referring to how to set up or use the bot, please join our discord instead of posting an issue: https://discord.gg/7FWyWVp 
4. Always confirm that your issue is reproducible, with the config you provide below.

### Expected Behavior:
To be able to click on captured pokemons and access the details page to perform actions eg. transfer/evolve/upgrade

### Actual Behavior:
Unable to access details of pokemons that are favourited. Non-favourited pokemons work fine.

### Your config.json:
```
None. Bot config shouldn't affect this feature.

```

### (OPTIONAL) Your Log:
```
replace this text with only the "relative" portion of your log. (Remove unnessary lines)

```

### Detailed Steps to Reproduce:
Click on either favourited or non-favourited pokemons to reproduce example

### Other Information
(Attach zip files if needed.)

Version:
Windows Version: 8.1
What is affected (catch, transfer, favorite, GPX, evolve, recycle, snipe, human walk snipe, pokestops, powerup/levelup, other): Necrobot GUI Pokemon List

**Comment by popsoda27** [comment]
Update: It's so strange, I realised that it's not just those pokemons that I favourited but also random others that I could not view details on. So I'm not really sure the exact steps to reproduce this bug, just that it's there....certain pokemons details screens just do not load at all.

**Comment by Silph-Road** [comment]
Try with latest version and post back with results.
