### ISSUE TITLE
At what level is it safe to evolve in necrobot?

### ISSUE THREAD

**Issue by eversonpiza** [Necrobot-Private/NecroBot#1521]
At what level is it safe to evolve in necrobot?

I'm already at level 36, is it safe to go to 40?

**Comment by OrdsonX** [comment]
Why you couldnt just ask at Discord ? Why create issue here ? Think !

**Comment by eversonpiza** [comment]
Sorry, but I don't know the 'Discord'.

Can you, please, send me the link?
