### ISSUE TITLE
[02:10:24] (FEHLER) Hash API server (https://pokehash.buddyauth.com/api/v131_0/hash) might down!

### ISSUE THREAD

**Issue by cocacolabanane** [Necrobot-Private/NecroBot#1529]
[02:10:24] (FEHLER) Hash API server (https://pokehash.buddyauth.com/api/v131_0/hash) might down!

was heist das

**Comment by hardknoxni69a** [comment]
lol sorry but why do people ask a a question when the answer is the question

**Comment by mavz1001** [comment]
how can i donate to access the VIP server to get a stable Dat Reciever for sniping?
