### ISSUE TITLE
Down

### ISSUE THREAD

**Issue by nscm13** [Necrobot-Private/NecroBot#1536]
The bot has this problem :(

in System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) in System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task) in PokemonGo.RocketAPI.Helpers.RequestBuilder.<GenerateSignature>d__12.MoveNext() in c:\projects\necrobot2\FeroxRev\Helpers\RequestBuilder.cs:riga 221

**Comment by Lord-Haji** [comment]
ur Internet lagged
