### ISSUE TITLE
Request (Always Transfer Pokemon)

### ISSUE THREAD

**Issue by ThatAce** [Necrobot-Private/NecroBot#154]
Requesting for Always Transfer Pokemon Where the feature will always transfer the pokemon regadless of CP or IV after catching it

**Comment by kalamera** [comment]
Never tried that, but would the next setting work?

    "TransferDuplicatePokemon": true,
    "TransferDuplicatePokemonOnCapture": true,
    "KeepMinDuplicatePokemon": 0,

    "KeepMinCp": 5000,
    "KeepMinIvPercentage": 100.0,
    "KeepMinOperator": "and",

**Comment by ajns73** [comment]
@kalamera That was my thought. It would need to be tested, but it should work on the "darkness is just the absence of light" principle.

**Comment by iwean** [comment]
@kalamera 
If you do that.... you will never have a single pokemon on your inventory. All will transfer... :smile: 
Inventory only keep if you catch pokemon with CP 5000 "AND" IV 100
The question is..... WHEN? You can catch that high CP & IV at the same time?

**Comment by kalamera** [comment]
@iwean well I have just give the option with current settings, so the "always transfer pokemon" function is not needed if those settings I have proposed do work :)

I know the "TransferWeakPokemon" does not always work for me well, so not sure if those proposed settings would work correctly.

For example if I set it like this:

    "KeepMinCp": 100,
    "KeepMinIvPercentage": 80.0,
    "KeepMinLvl": 15,
    "KeepMinOperator": "and",
    "UseKeepMinLvl": true,
    "PrioritizeIvOverCp": true,

I would expect to have in the inventory all the pokemons 15+ with 80%+IV and 100+CP, but this combinations seems to not work correctly for me with the "TransferWeakPokemon".
