### ISSUE TITLE
Bot is not collecting level up rewards.

### ISSUE THREAD

**Issue by thrakkorozg** [Necrobot-Private/NecroBot#1540]
### Expected Behavior:
Bot should collect rewards when "skip collect level up rewards" = false

### Actual Behavior:
Bot is skipping level up rewards even when skip is set to false.  
For the last week or two, every time I log into one of my accounts using the phone I get multiple levels worth if items at once. 

### Your config.json:
```
"PlayerConfig": {
    "DelayBetweenPlayerActions": 0,
    "EvolveActionDelay": 22000,
    "TransferActionDelay": 1000,
    "RecycleActionDelay": 1000,
    "RenamePokemonActionDelay": 1000,
    "UseNearActionRandom": true,
    "RandomizeSettingsByPercent": 9,
    "AutoFinishTutorial": true,
    "SkipFirstTimeTutorial": false,
    "SkipCollectingLevelUpRewards": false
  },

```

### (OPTIONAL) Your Log:
```
replace this text with only the "relative" portion of your log. (Remove unnessary lines)

```

### Other Information
(Attach zip files if needed.)

Version:1.0.0.157
Windows Version: Win 10 64-bit
What is affected (other): Level Up Rewards

**Comment by krishnaraovs** [comment]
Try by setting 'true'

**Comment by thrakkorozg** [comment]
When set to "TRUE" it still skips rewards; I also get a message every minute or so in the console indicating that it is skipping rewards:

[08:49:40] (INFO) Current level: 22. Skipped collecting level up rewards.

**Comment by Lord-Haji** [comment]
This was a feature request
