### ISSUE TITLE
HumanWalkSnipeConfig

### ISSUE THREAD

**Issue by gatesjr83** [Necrobot-Private/NecroBot#1545]
Does this not work anymore, i know a few of the sites are down which is why i left them false, but still no luck 

 },
  "HumanWalkSnipeConfig": {
    "Enable": true,
    "DisplayPokemonList": true,
    "MaxDistance": 1500.0,
    "MaxEstimateTime": 900.0,
    "CatchEmAllMinBalls": 50,
    "TryCatchEmAll": true,
    "CatchPokemonWhileWalking": true,
    "SpinWhileWalking": true,
    "AlwaysWalkback": false,
    "SnipingScanOffset": 0.025,
    "WalkbackDistanceLimit": 300.0,
    "IncludeDefaultLocation": true,
    "UseSnipePokemonList": true,
    "MaxSpeedUpSpeed": 60.0,
    "AllowSpeedUp": true,
    "DelayTimeAtDestination": 10000,
    "UsePokeRadar": false,
    "UseSkiplagged": true,
    "UsePokecrew": false,
    "UsePokesnipers": false,
    "UsePokeZZ": true,
    "UsePokeWatcher": false,
    "UseFastPokemap": true,
    "UsePogoLocationFeeder": true,
    "AllowTransferWhileWalking": true
  },

**Comment by babyTO** [comment]
Your HumanWalkSnipeConfig looks ok, try those settings for your Data sharing config:

"DataSharingConfig": {
    "EnableSyncData": true,
    "AutoSnipe": true,
    "DataServiceIdentification": "",
    "SnipeDataAccessKey": "",
    "EnableFailoverDataServers": true,
    "FailoverDataServers": "ws://s1.mypogosnipers.com/socket.io/?EIO=3&transport=websocket;ws://s2.mypogosnipers.com/socket.io/?EIO=3&transport=websocket;ws://necrosocket.herokuapp.com/socket.io/?EIO=3&transport=websocket",
    "DataRecieverURL": "ws://www.mypogosnipers.com/socket.io/?EIO=3&transport=websocket"
  },

**Comment by jjskuld** [comment]
These are all no longer supported:

```
"UsePokeRadar": false,
"UseSkiplagged": true,
"UsePokecrew": false,
"UsePokesnipers": false,
"UsePokeZZ": true,
"UsePokeWatcher": false,
"UseFastPokemap": true,
```

We just never got around to removing those from the config.
