### ISSUE TITLE
Error: System.ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by Dexter145** [Necrobot-Private/NecroBot#155]
### Expected Behavior:
Bot keep running without error.

### Actual Behavior:
After a few minutes of running the bot getting the next error. Happens every time.

[15:04:29] (ERROR) Pokemon Servers might be offline / unstable. Trying again...
[15:04:31] (ERROR) Error: System.ArgumentOutOfRangeException: Toe te voegen waarde ligt buiten de reeks.
Parameternaam: value
   bij System.DateTime.Add(Double value, Int32 scale)
   bij PoGo.NecroBot.Logic.Tasks.HumanWalkSnipeTask.<>c.<ApplyFilter>b__12_0(SnipePokemonInfo p) in C:\projects\necrobot2\PoGo.NecroBot.Logic\Tasks\HumanWalkSnipeTask.cs:regel 134
   bij System.Linq.Enumerable.WhereListIterator`1.MoveNext()
   bij System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   bij System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   bij PoGo.NecroBot.Logic.Tasks.HumanWalkSnipeTask.ApplyFilter(List`1 source) in C:\projects\necrobot2\PoGo.NecroBot.Logic\Tasks\HumanWalkSnipeTask.cs:regel 134
   bij PoGo.NecroBot.Logic.Tasks.HumanWalkSnipeTask.PostProcessDataFetched(IEnumerable`1 pokemons, Boolean displayList) in C:\projects\necrobot2\PoGo.NecroBot.Logic\Tasks\HumanWalkSnipeTask.cs:regel 435
   bij PoGo.NecroBot.Logic.Tasks.HumanWalkSnipeTask.FetchData(Double lat, Double lng, Boolean silent) in C:\projects\necrobot2\PoGo.NecroBot.Logic\Tasks\HumanWalkSnipeTask.cs:regel 373
   bij PoGo.NecroBot.Logic.Tasks.HumanWalkSnipeTask.GetNextSnipeablePokemon(Double lat, Double lng, Boolean refreshData) in C:\projects\necrobot2\PoGo.NecroBot.Logic\Tasks\HumanWalkSnipeTask.cs:regel 305
   bij PoGo.NecroBot.Logic.Tasks.HumanWalkSnipeTask.<Execute>d__13.MoveNext() in C:\projects\necrobot2\PoGo.NecroBot.Logic\Tasks\HumanWalkSnipeTask.cs:regel 163
--- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
   bij System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bij System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   bij PoGo.NecroBot.Logic.Tasks.UseNearbyPokestopsTask.<Execute>d__13.MoveNext() in C:\projects\necrobot2\PoGo.NecroBot.Logic\Tasks\UseNearbyPokestopsTask.cs:regel 149
--- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
   bij System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bij PoGo.NecroBot.Logic.Tasks.FarmPokestopsTask.<Execute>d__1.MoveNext() in C:\projects\necrobot2\PoGo.NecroBot.Logic\Tasks\FarmPokestopsTask.cs:regel 59
--- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
   bij System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bij System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   bij PoGo.NecroBot.Logic.State.FarmState.<Execute>d__0.MoveNext() in C:\projects\necrobot2\PoGo.NecroBot.Logic\State\FarmState.cs:regel 49
--- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
   bij System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bij PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in C:\projects\necrobot2\PoGo.NecroBot.Logic\State\StateMachine.cs:regel 63

### Your config.json:
http://pastebin.com/ithMwtZR

### (OPTIONAL) Your Log:
[15:04:08] Looking for Pokemon...
[15:04:09] Looking for incense Pokemon...
[15:04:11] Naam: G Van Arkel XP: 50, Gems: 0, Items: 1 x ItemPotion, 3 x ItemPokeBall, Lat: 52.370637, Long: 4.893007, Alt: 8.13828549857172
[15:04:11] (POKESTOP LIMIT) 10/1998
[15:04:29] Pokemon Servers might be offline / unstable. Trying again...
[15:04:31] Error: System.ArgumentOutOfRangeException: Toe te voegen waarde ligt buiten de reeks.
Parameternaam: value
   bij System.DateTime.Add(Double value, Int32 scale)
   bij PoGo.NecroBot.Logic.Tasks.HumanWalkSnipeTask.<>c.<ApplyFilter>b__12_0(SnipePokemonInfo p) in C:\projects\necrobot2\PoGo.NecroBot.Logic\Tasks\HumanWalkSnipeTask.cs:regel 134
   bij System.Linq.Enumerable.WhereListIterator`1.MoveNext()
   bij System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   bij System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   bij PoGo.NecroBot.Logic.Tasks.HumanWalkSnipeTask.ApplyFilter(List`1 source) in C:\projects\necrobot2\PoGo.NecroBot.Logic\Tasks\HumanWalkSnipeTask.cs:regel 134
   bij PoGo.NecroBot.Logic.Tasks.HumanWalkSnipeTask.PostProcessDataFetched(IEnumerable`1 pokemons, Boolean displayList) in C:\projects\necrobot2\PoGo.NecroBot.Logic\Tasks\HumanWalkSnipeTask.cs:regel 435
   bij PoGo.NecroBot.Logic.Tasks.HumanWalkSnipeTask.FetchData(Double lat, Double lng, Boolean silent) in C:\projects\necrobot2\PoGo.NecroBot.Logic\Tasks\HumanWalkSnipeTask.cs:regel 373
   bij PoGo.NecroBot.Logic.Tasks.HumanWalkSnipeTask.GetNextSnipeablePokemon(Double lat, Double lng, Boolean refreshData) in C:\projects\necrobot2\PoGo.NecroBot.Logic\Tasks\HumanWalkSnipeTask.cs:regel 305
   bij PoGo.NecroBot.Logic.Tasks.HumanWalkSnipeTask.<Execute>d__13.MoveNext() in C:\projects\necrobot2\PoGo.NecroBot.Logic\Tasks\HumanWalkSnipeTask.cs:regel 163
--- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
   bij System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bij System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   bij PoGo.NecroBot.Logic.Tasks.UseNearbyPokestopsTask.<Execute>d__13.MoveNext() in C:\projects\necrobot2\PoGo.NecroBot.Logic\Tasks\UseNearbyPokestopsTask.cs:regel 149
--- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
   bij System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bij PoGo.NecroBot.Logic.Tasks.FarmPokestopsTask.<Execute>d__1.MoveNext() in C:\projects\necrobot2\PoGo.NecroBot.Logic\Tasks\FarmPokestopsTask.cs:regel 59
--- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
   bij System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bij System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   bij PoGo.NecroBot.Logic.State.FarmState.<Execute>d__0.MoveNext() in C:\projects\necrobot2\PoGo.NecroBot.Logic\State\FarmState.cs:regel 49
--- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
   bij System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bij PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in C:\projects\necrobot2\PoGo.NecroBot.Logic\State\StateMachine.cs:regel 63

### Detailed Steps to Reproduce:
Clean copy, edit new created config.

Version: 0.9.9.4
Windows Version: Windows 10

**Comment by kalamera** [comment]
is that a HumanWalkSnipe error? :)

**Comment by Silph-Road** [comment]
^ update to latest and test again and open new issue if errors repeat.
