### ISSUE TITLE
I received an alert threatening to ban my account

### ISSUE THREAD

**Issue by eversonpiza** [Necrobot-Private/NecroBot#1553]
When I opened the pokemon GO APP, I received the attached threat.

[image](https://1drv.ms/i/s!As0TtVLgKXcMgZxKRd6eKbGuozogJA)

:(

**Comment by babyTO** [comment]
Just received the same warning yesterday. I since turned off sniping and basicly did not interfere with the bot what so ever, like manually evolve or transfer pokemon. I read somewhere here that doing manual stuff through the GUI is very much not "human-like" because it does those things in an instance. I also got a warning a couple of months ago when I was botting without a valid hash key (old API) but I bought a key since then.

**Comment by TheHern** [comment]
Just got a warning today as well.

Once you get this warning is there anything we can do to stay completely under the radar with Necrobot? I must have done something to flag them...Is there something I should change? I have attached a copy of my  config.
[config for 1553.json.txt](https://github.com/Necrobot-Private/NecroBot/files/949173/config.for.1553.json.txt)
Thanks in advance,

**Comment by Furtif** [comment]
This is a niantics warning that you are using third-party software
not a ban ^^
But its can become a ban if we continue to bot ... if we stopped niantics stopped to be behind our ass to watch our conexions.....................
Its me the already done this thing several times, I stop until the message no longer appears in the phone then I returned in the bot (about a week)

**Comment by babyTO** [comment]
> I stop until the message no longer appears in the phone then I returned in the bot (about a week)

I can confirm that the message disappears after about a week of not botting. But I don't know about them not keeping track about the warnings... so yeah.

**Comment by Haydut86** [comment]
I got the same message and I have catch flee ban. Does anyone knows how to get rid of from catch flee ban?

**Comment by KyoshoSon** [comment]
One time I got the catch flee and unable-to-spin pokestop soft ban I was able to get out of it in about 20 mins after repeatedly spinning one same pokestop.  Eventually that pokestop gave in and spin out goodies.
