### ISSUE TITLE
Invaild Markup cant compile window gui

### ISSUE THREAD

**Issue by Nackenschelle** [Necrobot-Private/NecroBot#1554]
bot works fine but the new gui wont work

here are 2 screenshots: 
http://prntscr.com/ezobrd
http://prntscr.com/ezobk8

any solution for me?

**Comment by Nackenschelle** [comment]
#push

**Comment by CDAGaming** [comment]
You might need to repull or restore nuget pakages

**Comment by Nackenschelle** [comment]
thx i will test it

feedback comes in few moments

**Comment by Nackenschelle** [comment]
ok tested but error stays

output writes following text:
Es wurde versucht, eine Assembly von einer Netzwerkadresse zu laden, was in früheren Versionen von .NET Framework zum Ausführen der Assembly als Sandkastenassembly geführt hätte. In dieser Version von .NET Framework wird die CAS-Richtlinie standardmäßig nicht aktiviert, dieser Ladevorgang kann daher gefährlich sein. Wenn Sie nicht beabsichtigen, durch diesen Ladevorgang eine Sandkastenassembly zu erstellen, aktivieren Sie den loadFromRemoteSources-Schalter. Weitere Informationen finden Sie unter "http://go.microsoft.com/fwlink/?LinkId=155569".

**Comment by CDAGaming** [comment]
That error relates to .net framework, which could mean a corrupted install or missing the .net 4.6.2 targeting pack

**Comment by Nackenschelle** [comment]
so what can i do to fix the problem?
reinstall .net framework?

**Comment by CDAGaming** [comment]
You might have to, or install the .net 4.6.2 targeting pack

**Comment by Nackenschelle** [comment]
i also installed the developer pack.

error still the same so i uninstalled all net framework by .net framework cleanup tool
tan reinstall
4.6.2 + dev pack.

at least error stays.

This is frustrating

**Comment by CDAGaming** [comment]
There was a new commit just now, try to pull that and then try rebuilding. If that does not work as well as a reclone, let me know

**Comment by Lord-Haji** [comment]
Should work with .net462 sdk, also there was another fix #1572
