### ISSUE TITLE
Help.. i am newbie

### ISSUE THREAD

**Issue by TriNtoro** [Necrobot-Private/NecroBot#1565]
Hi.
i tried necrobot
got error message

![error](https://cloud.githubusercontent.com/assets/20675907/25414451/b9963728-2a5b-11e7-83d4-f146ceabbe64.png)

please assist me, how to use necrobot. 
thanks

**Comment by jalanjalanjalan** [comment]
you can try read this thread
https://github.com/Necrobot-Private/NecroBot/issues/1188

for now necrobot2 is only compatible with 64 bit

**Comment by TriNtoro** [comment]
Ok.. waiting 32 byte. 
thanks

**Comment by hardknoxni69a** [comment]
please join our necrobot2 discord server and a dev should be able to link you to an anycpu build or 32bit but in meantime i will work on getting our builds released again in both bits for users
