### ISSUE TITLE
[IDEA] stop catching immediately when 'catchflee' happens on 100% chance

### ISSUE THREAD

**Issue by stefanvds1** [Necrobot-Private/NecroBot#1566]
Not an issue per se, but an idea. 
you can set in the config how many flees in a row need to happen for the bot to stop trying and either move on or stop catching for some time.

however, when a CP10 pidgey flee's (which catch chance 100%) the bot should know this means softban/over limit .

(PKMN) (CatchFlee) | (Normal) Pidgey Lvl: 1 CP: (10/581) IV: 53.00% | **Chance: 100%** | 0.00m dist | with a GreatBall (28 left). | lat: xxx long: yyy | Move1: T
ackleFast Move2: AirCutter | Rarity :VeryCommon

**Comment by redking974** [comment]
I think that feature already (Flee limit) implemented do the job. I setup to 5 and after 5 flees, it goes to the next account. Maybe your idea is more accurate, but I let devs think about it (depends on priority of others features) ;)

**Comment by hardknoxni69a** [comment]
a pokemon could flee from moving to fast and honestly i think niantic makes pokemon flee randomly just for the pure enjoyment of upsetting players but as redking says set 5 catchflees to stop your account or 3 if you want to be more safe
