### ISSUE TITLE
snipe

### ISSUE THREAD

**Issue by unknowkir** [Necrobot-Private/NecroBot#1567]
i cant snipe and the snipable menu is always 0

**Comment by redking974** [comment]
You need to provide more infos. Your config and your log for example...

**Comment by unknowkir** [comment]
[NecroBot2-2017-04-26-08-11-12.txt](https://github.com/Necrobot-Private/NecroBot/files/957581/NecroBot2-2017-04-26-08-11-12.txt)

**Comment by unknowkir** [comment]
[NecroBot2-2017-04-26-08-11-12.txt](https://github.com/Necrobot-Private/NecroBot/files/957586/NecroBot2-2017-04-26-08-11-12.txt)
[config.txt](https://github.com/Necrobot-Private/NecroBot/files/957587/config.txt)

**Comment by redking974** [comment]
It's because the snipe server have connexion issues. Try to update to 159.
If it won't work after that, you can go to Discord server to see benefits of VIP snipe server (because public have issues).

**Comment by Poke85** [comment]
How can i be A VIP member and stop this sniple troubles?

**Comment by unknowkir** [comment]
You have to pay for vip server right?

**Comment by Poke85** [comment]
yes have to pay for sure...but i dont find any sections for begin a  VIP member

**Comment by aboyz** [comment]
how do we pay for a vip member for sniper server?

**Comment by zinzin64** [comment]
just donate to mypogosniper.com and they mail you a key.now mypogosniper is down also if you have vip key so no snipe.

**Comment by krishnaraovs** [comment]
Q. Where can i Donate and what is my benefits for Donate? 
A. Benefits of DONATION : 
$5 will give you 
* Green color of nickname at our Discord Channel 
$10 will give you
* All the above 
* API Access to VIP Sniper Server / Uptime 24/7 
* More than 2 Necrobot2 SESSIONS allowed to use sniper at same time. 
* Up to 9 SESSIONS allowed 
$10+ will give you 
* All the above 
* More than 9 SESSIONS allowed 
* 10+ will give life time access - 
PayPal email : samuraitruong@hotmail.com Transaction ID with amount Donated has to sent to Truong ( PM or Email )

**Comment by aboyz** [comment]
is the donation a monthly fee? or is it monthly fee or need to donate?

**Comment by Poke85** [comment]
... and the snipe is still not working :(

**Comment by krishnaraovs** [comment]
Raise your queries at discord 
https://discordapp.com/invite/7FWyWVp

**Comment by andeomontenegro** [comment]
first we pushed to buy api, now we must pay for snipe. lol
