### ISSUE TITLE
[Question] Somebody work on the new API?

### ISSUE THREAD

**Issue by FureszOszkar** [Necrobot-Private/NecroBot#157]
Somebody work on the new API?

**Comment by tws101** [comment]
Lol they are all working on the new API....But I guess have an issue open to track it......

**Comment by DavideRaggi** [comment]
For now it's better not botting i think..

**Comment by Baleki** [comment]
The new bot released 2 hours ago still not have the new api?

**Comment by ajns73** [comment]
@Baleki I am quite certain you will know very clearly when the new API is cracked.

**Comment by wilsondgonzales** [comment]
@ajns73 there a discord where we can get updates on who's working on it? like lastime pogodev?

**Comment by willydk** [comment]
What client is v0.9.9.x using? 0.35?

**Comment by ajns73** [comment]
@wilsondgonzales https://discord.gg/7FWyWVp

**Comment by jjskuld** [comment]
@willydk 0.35 right now

**Comment by willydk** [comment]
@jjskuld thanks

**Comment by Silph-Road** [comment]
> What client is v0.9.9.x using? 0.35?

Only the last few new releases use .35.

.37 is not ready and no ETA.
