### ISSUE TITLE
Pokemon not Transfering - Full

### ISSUE THREAD

**Issue by aboyz** [Necrobot-Private/NecroBot#1586]
This is the message i'm getting. I'm running the latest version 10.0.159
[12:22:34] (ATTENTION) Pokemon Inventory is full, transferring Pokemon...
[12:22:34] (EVOLVED) Potential Evolutions: 0

"PokemonConfig": {
    "CatchPokemon": true,
    "DelayBetweenPokemonCatch": 2000,
    "UseCatchLimit": true,
    "CatchPokemonLimit": 500,
    "CatchPokemonLimitMinutes": 1350,
    "UseIncenseConstantly": false,
    "UseEggIncubators": true,
    "UseLimitedEggIncubators": true,
    "UseLuckyEggConstantly": false,
    "UseLuckyEggsMinPokemonAmount": 30,
    "UseLuckyEggsWhileEvolving": false,
    "TransferWeakPokemon": true,
    "TransferDuplicatePokemon": true,
    "TransferDuplicatePokemonOnCapture": true,
    "RenamePokemon": false,
    "RenameOnlyAboveIv": false,
    "RenameTemplate": "{Name}_{IV}_Lv{Level}",
    "FavoriteMinIvPercentage": 95.0,
    "AutoFavoritePokemon": false,
    "AutoFavoriteShinyOnCatch": false,
    "MaxPokeballsPerPokemon": 6,
    "UseGreatBallAboveCp": 1000,
    "UseUltraBallAboveCp": 1250,
    "UseMasterBallAboveCp": 1500,
    "UseGreatBallAboveIv": 85.0,
    "UseUltraBallAboveIv": 95.0,
    "UseGreatBallBelowCatchProbability": 0.2,
    "UseUltraBallBelowCatchProbability": 0.1,
    "UseMasterBallBelowCatchProbability": 0.05,
    "AutomaticallyLevelUpPokemon": false,
    "OnlyUpgradeFavorites": true,
    "UseLevelUpList": true,
    "AmountOfTimesToUpgradeLoop": 5,
    "GetMinStarDustForLevelUp": 5000,
    "LevelUpByCPorIv": "iv",
    "UpgradePokemonCpMinimum": 1000.0,
    "UpgradePokemonIvMinimum": 95.0,
    "UpgradePokemonMinimumStatsOperator": "and",
    "EvolveAboveIvValue": 95.0,
    "EvolveAllPokemonAboveIv": false,
    "EvolveAllPokemonWithEnoughCandy": true,
    "EvolveKeptPokemonsAtStorageUsagePercentage": 90.0,
    "EvolveKeptPokemonIfBagHasOverThisManyPokemon": 120,
    "KeepPokemonsThatCanEvolve": false,
    "KeepMinCp": 1250,
    "KeepMinIvPercentage": 95.0,
    "KeepMinLvl": 6,
    "KeepMinOperator": "and",
    "UseKeepMinLvl": false,
    "PrioritizeIvOverCp": true,
    "KeepMinDuplicatePokemon": 1,
    "KeepMaxDuplicatePokemon": 1000,
    "UsePokemonToNotCatchFilter": true,
    "UsePokemonToCatchLocallyListOnly": false,
    "DumpPokemonStats": false,
    "DelayBetweenPokemonUpgrade": 10000,
    "OutOfBallCatchBlockTime": 5,
    "PokeballToKeepForSnipe": 50,
    "UseBulkTransferPokemon": true,
    "BulkTransferStogareBuffer": 10,
    "BulkTransferSize": 100,
    "UseBallOperator": "or",
    "FavoriteMinCp": 0.0,
    "DefaultBuddyPokemon": "",
    "FavoriteMinLevel": 0,
    "FavoriteOperator": "and",
    "RenamePokemonRespectTransferRule": false,
    "UpgradePokemonLvlMinimum": 30.0,
    "EvolveFavoritedOnly": true,
    "EvolveOperator": "and",
    "EvolveMinIV": 100.0,
    "EvolveMinCP": 2000.0,
    "EvolveMinLevel": 25.0,
    "ByPassCatchFlee": false
  },

**Comment by hardknoxni69a** [comment]
adjust your keepmin settings and it will resume transferring
