### ISSUE TITLE
MSniper ideas

### ISSUE THREAD

**Issue by msx752** [Necrobot-Private/NecroBot#159]
- [x] priority for snipes(while walking to another pokestops) https://github.com/Necrobot-Private/NecroBot/issues/136
- [x] copy/paste coord (from old version) (issue for msniper)
- [x] sniped pokemon's HP and LVL
- [x] use berry while using msniper
- [x] find rare pokemon
- [x] "Order by IV" in the site msniper.com (issur for msniper.com)

**Comment by iwean** [comment]
- Have a dropdown menu (on the web) to choice high IV or high CP or high LVL

**Comment by tr1p0z** [comment]
Short by IV in the site msniper.com

**Comment by Kduhh** [comment]
"Choose by IV" in the site msniper.com
and by time of despawn

**Comment by msx752** [comment]
@Kduhh already have despawn timer on the website ?

**Comment by msx752** [comment]
@tr1p0z iv filter already has min %50 shows on website , but i can improve

**Comment by Kduhh** [comment]
sorry it's "Order by"

**Comment by msx752** [comment]
👍

**Comment by petpetpetvm** [comment]
get pokemon coord from channels in an discord acc (like i have special channels for donators only, and it use my account to get coords)
example :    
  "ServerChannels": [
    "100_iv",
    "100iv_donor"
  ],
  "DiscordUser": "dfghj@yahoo.com",
  "DiscordPassword": "xcvbn"

**Comment by petpetpetvm** [comment]
scout : a user can put in a scout account (trash account to be a scout), the scout will check and verify the pokemon first then msniper send coord to the bot

**Comment by msx752** [comment]
all coordinates are verified by necrobot2

**Comment by zc3721** [comment]
may I ask what is msniper?
Thx

Mustafa Salih ASLIM <notifications@github.com>于2016年9月17日周六 08:38写道：

**Comment by msx752** [comment]
@zc3721 auto notification from github

**Comment by TanvirYusuf** [comment]
just noticed msniper doesn't give stardust
