### ISSUE TITLE
App crashes after new popup

### ISSUE THREAD

**Issue by redking974** [Necrobot-Private/NecroBot#1598]
### Expected Behavior:
No crash, proper closing

### Actual Behavior:
When we have a flagged account, if we click "Yes" on the popup (aka "Exit bot ?") Necrobot will crash

### Detailed Steps to Reproduce:
Install the new version (161)

Version: 161
Windows Version: 10
What is affected (catch, transfer, favorite, GPX, evolve, recycle, snipe, human walk snipe, pokestops, powerup/levelup, other): close

**Comment by Lord-Haji** [comment]
This was fixed, you might want to check changelog before opening issues

**Comment by redking974** [comment]
I've checked the commits until the last version 161.

**Comment by Lord-Haji** [comment]
@a0e080db9db34f612c8100df5d91225e1e13fe42

**Comment by redking974** [comment]
I'm sorry but since I'm not a dev and there is no description (I saw only "Update RocketAPI") I can't figure that it was a fix for the crash bug.
I've just downloaded the last version, seen that it crashes, double checked that this issue wasn't reported and open a ticket.
