### ISSUE TITLE
NecroBot2.GUI

### ISSUE THREAD

**Issue by Salvationdk** [Necrobot-Private/NecroBot#16]
Version: NecroBot2 v0.9.8.1
Windows Version: 10
Console working
but NecroBot2.GUI wont open.

**Comment by BoydTM** [comment]
I just received info from discord that they already work on that (assuming that you also getting net unhandled exception)

PS. You can edit your issues instead of creating a new ones ... ;)

**Comment by Salvationdk** [comment]
i dont get any exception. But yah regarding the issue opening  i will..

**Comment by IAMPYC** [comment]
GUI NOT WORKING!!!!!   Win7 64bit

**Comment by ntatoo** [comment]
wait , stay tune 
we are working to fix it
thanx

**Comment by NzV** [comment]
fixed : https://github.com/Necrobot-Private/NecroBot/releases/latest
