### ISSUE TITLE
Google Walk Issues

### ISSUE THREAD

**Issue by Ev0luti0n2016** [Necrobot-Private/NecroBot#160]
When following the Trainer with the PokeEase GUI by Necrobot2 Team, it shows that the Trainer is Walking On Water and Through Buildings. How can that be fixed?

Thanks for keeping this alive and for the warnings about the new API that is not yet active. 

-Ev0

**Comment by ajns73** [comment]
That's the whole reason for using google walk (to prevent that). What does your console look like?

**Comment by jjskuld** [comment]
@Ev0luti0n2016 You need to set up Google or Mapzen walk. See this https://github.com/Necrobot-Private/NecroBot/wiki/API-Keys-For-Navigation-and-Elevation
