### ISSUE TITLE
necrobot has stopped working

### ISSUE THREAD

**Issue by ZO0RG** [Necrobot-Private/NecroBot#1600]
![untitled](https://cloud.githubusercontent.com/assets/28256075/25577783/4d8e1958-2e69-11e7-8787-abba13b6075d.jpg)
downloaded and installed this https://www.microsoft.com/en-us/download/details.aspx?id=53321 the same issue
### Expected Behavior:
the bot starts

### Actual Behavior:
the bot crashed

### Your config.json:
 nothing was generated
### Detailed Steps to Reproduce:
Install the new version 1.0.0.161
### Other Information
(Attach zip files if needed.)

Version:1.0.0.161
Windows Version:10
What is affected (catch, transfer, favorite, GPX, evolve, recycle, snipe, human walk snipe, pokestops, powerup/levelup, other):launch

**Comment by CDAGaming** [comment]
Please Read the console error in your screenshot. NO API METHOD SET IN AUTH.JSON

**Comment by ZO0RG** [comment]
![1123](https://cloud.githubusercontent.com/assets/28256075/25578629/e02e1cfc-2e70-11e7-9e74-7a9618e2327c.jpg)

**Comment by CDAGaming** [comment]
Same error, what's your ApiConfig section in auth.json, but blank out your key area to protect that info if you choose to send screenshot

**Comment by CDAGaming** [comment]
Oh, your running legacy API, which is also no longer used. Please buy API Key from PogoDev

**Comment by ZO0RG** [comment]
so there is no any free api

**Comment by ZO0RG** [comment]
so legacy api is the problem if i changed the api it will work or legacy api is not good as the others and i need to buy an api key

**Comment by CDAGaming** [comment]
Yes, on pogodev it should work

**Comment by ZO0RG** [comment]
are sure i am afraid after i buy a key i face the same problem

**Comment by CDAGaming** [comment]
You'd still have to buy a key in order to bot, as legacy is fully outdated and no longer works at all, and will be fully disabled in v162 to prevent future confusion
