### ISSUE TITLE
keep geting api key out of date 

### ISSUE THREAD

**Issue by markfell** [Necrobot-Private/NecroBot#1607]
last night bot working grate 
started with difrent acount and new update but keep geting this                                        
17:54:19] () Configuration is up-to-date. Schema version: 24
[17:54:20] () Validating config.json...
[17:54:22] () Auth Configuration is up-to-date. Schema version: 24
[17:54:22] () Validating Auth.json...
[17:54:22] () The HashKey is invalid or has expired, please press any key to exit and correct you auth.json, 
 The Pogodev API key can be purchased at - https://talk.pogodev.org/d/51-api-hashing-service-by-pokefarmer

**Comment by markfell** [comment]
i just bought key today from bossland gmbh

**Comment by CDAGaming** [comment]
Maybe your key expired and or entered invalidly

**Comment by markfell** [comment]
I bought new key this morning still same

**Comment by CDAGaming** [comment]
Then it might have been entered incorrectly

**Comment by markfell** [comment]
It dose it with both my  keys old one which i have been coping and pasting
it all week

**Comment by informer0827** [comment]
The last way is ask somebody you trusted to test your API key.

**Comment by markfell** [comment]
Would u check it for me

**Comment by informer0827** [comment]
well...you wanna past it here?

**Comment by markfell** [comment]
2M0V5E3Z8Q7H0X3T8T5L

**Comment by informer0827** [comment]
I'm running fine with your key...
What previous version you're using??

**Comment by markfell** [comment]
Im runing lates download


Sent from my HTC

----- Reply message -----

**Comment by markfell** [comment]
Lates verson from this morning

**Comment by informer0827** [comment]
Yeah, I know,  
I want to know the what version you're using before this update?

**Comment by informer0827** [comment]
Okay, no matter what version you're using before.  
I suggest you have a clean "start from scratch" initialize with new version.  
That means you have to extract zip into a new folder.  
And run necrobot directly and interact with necrobot to answer quiz step by step.  
That should be running fine.

**Comment by markfell** [comment]
Necrobot 2.win.1.0.0.160  and
now 1.0.0.161

**Comment by informer0827** [comment]
okay, for you're the HTC user (the phone made from my country).  
I could give you a remote support with teamviewer.  
Just mail me (address in my profile) your teamviewer ID and Password.  
And let me check out what we can do.

**Comment by markfell** [comment]
I dont have teamviewer could u send me a bot all set up and redy for muilty
acounts pleas thank you markfell

**Comment by markfell** [comment]
I woud donate if u could do this for me

**Comment by informer0827** [comment]
Well, don't need your donation at all....
https://www.dropbox.com/s/2ou2o3kv8pqlse0/Necrobot2.zip?dl=0
download it and change id, pw, hash api key, google api key, mapzen api key and you supposed to me running fine.

**Comment by informer0827** [comment]
It's 3 am and i need to fall as sleep now.  
response you later after I wake up or somebody could kindly help you to do trouble shooting.

**Comment by markfell** [comment]
Ok thanks markfell

**Comment by boby360** [comment]
you should really delete that hash key.........

**Comment by markfell** [comment]
How do i do that

**Comment by CDAGaming** [comment]
There is a delete button on each post you make on GitHub...

**Comment by CDAGaming** [comment]
And yeah you should delete that key post

**Comment by markfell** [comment]
How

Sent from my HTC

----- Reply message -----

**Comment by CDAGaming** [comment]
@markfell There is an 'X' Icon on the upper right of your posts

**Comment by CDAGaming** [comment]
If on Computer

**Comment by jjskuld** [comment]
I deleted that key that was posted.

**Comment by markfell** [comment]
Thanks


Sent from my HTC

----- Reply message -----

**Comment by Lord-Haji** [comment]
I am 100 % sure this is not an issue on our end
