### ISSUE TITLE
[Question] The Buddy System

### ISSUE THREAD

**Issue by ajns73** [Necrobot-Private/NecroBot#161]
I am assuming this has been raised already and discussed (I couldn't find anything), but on the off chance that it hasn't....

I was playing with buddies on my iOS device and I thought of a couple of things. Is this a passive user invention feature? i.e. - if you go too fast you get a pop up to not use pokemon while driving if you're on a device. The bot will choke on that I am assuming (which is why we had the captcha freak-out) Although buddies are not forced yet, what happens if you select a buddy on your device (once selected buddies cannot be cleared, only changed), but the bot doesn't have the exact same buddy coding? Has this already been considered? Or what if the buddy info is part of the call?

IDK, just some meandering thoughts.

**Comment by goodguydoll84** [comment]
I have a buddy on mine, and nothing besides the normal "you're going to
fast" pop up

**Comment by ajns73** [comment]
I won't happen, if at all, until the new API is forced

**Comment by hardknoxni69a** [comment]
I think bot bypasses that warning somehow because there are people who bot pretty fast and they dont have issues i would imagine once u set buddy on device it prob carries over automatically to bot so will be earning candies but idk trying logging on .37 and select buddy then walk a few km on .35 and see if you kms change at alll when back on .37

**Comment by ajns73** [comment]
I could care less if the the bot gives me credit for walking with my buddy. My concern is that Niantic can use the fact that I have a buddy or which buddy I have to determine if I have a legit account (and we won't know this for sure until .37 is forced and Niantic EXPECTS buddy info to be pinged back to the server) i.e. - I set a buddy through the official app. How does the bot then accurately reflect that info? Will it be part part of the new API? Will I be screwed? And these questions have no answers now, I realize. But, my point was, if we don't talk about it now, we could trip ourselves up later. Or maybe it is not a concern at all. The devs would have to weigh in on that, which I don't think they can yet until they have seen and cracked the entire new API.

**Comment by teos81** [comment]
I have make a test.. Chosed a buddy into the 0.37. app. start againg botting and return to the app.. 
30km make with the buddy and candy growed.. ;)

I don't know if it's the same also with the 0.37.1

Byee

**Comment by hardknoxni69a** [comment]
this makes it seem like the buddy is just attached to your profile and grows candy as your km go up in your journal so once you choose a buddy you can return to .35 no issue so i need to choose a buddy and start getting them lapras candies
