### ISSUE TITLE
QUESTION Upgrade Pokemon

### ISSUE THREAD

**Issue by pokegeel1** [Necrobot-Private/NecroBot#1612]
I noticed that for several pokemon in necrobot it is possible to upgrade to a higher level than in the mobile official pokemon version.
In the mobile version I have a tyranitar level 37.5. I cannot upgrade this one on my Phone but in necrobot ik can still upgrade to level 38. How is this possible?

**Comment by Lord-Haji** [comment]
Limit these sorta questions to our discord servee
