### ISSUE TITLE
how to download Necrobot ?

### ISSUE THREAD

**Issue by henbae** [Necrobot-Private/NecroBot#162]
i didnt see exe file on Code page

**Comment by efifi** [comment]
on the code page - go to the releases link

**Comment by petpetpetvm** [comment]
https://github.com/Necrobot-Private/NecroBot/releases
and download the console one

**Comment by henbae** [comment]
many thank. do you have good config file ?

**Comment by petpetpetvm** [comment]
no haha, my config is a really unsafe one lmao
