### ISSUE TITLE
GrayscaleEffect Error

### ISSUE THREAD

**Issue by Nackenschelle** [Necrobot-Private/NecroBot#1624]
Schweregrad	Code	Beschreibung	Projekt	Datei	Zeile	Unterdrückungszustand
Fehler		Der Name "GrayscaleEffect" ist im Namespace "clr-namespace:GrayscaleEffect;assembly=GrayscaleEffect" nicht vorhanden.	PoGo.Necrobot.Window

any solution?

**Comment by Lord-Haji** [comment]
English Log please

**Comment by Nackenschelle** [comment]
Screenshot: http://prntscr.com/f40izl

Severity	Code	Description	Project	File	Line	Suppression State
Error		The name "GrayscaleEffect" does not exist in the namespace "clr-namespace:GrayscaleEffect;assembly=GrayscaleEffect".	PoGo.Necrobot.Window

**Comment by CDAGaming** [comment]
You need to Right Click Solution and click Restore NuGet Packages before building

**Comment by Nackenschelle** [comment]
Already tried.

An attempt was made to load an assembly from a network location which would have caused the assembly to be sandboxed in previous versions of the .NET Framework. This release of the .NET Framework does not enable CAS policy by default, so this load may be dangerous. If this load is not intended to sandbox the assembly, please enable the loadFromRemoteSources switch. See http://go.microsoft.com/fwlink/?LinkId=155569 for more information.

**Comment by CDAGaming** [comment]
Could possibly be a corrupt 4.6.2 .net install but I can't verify

**Comment by Nackenschelle** [comment]
everything is fresh reinstalled

visual studio also .net framework

**Comment by Nackenschelle** [comment]
any solutions?

**Comment by informer0827** [comment]
How about build it in a fresh OS in VM + VS + Framework?

**Comment by Nackenschelle** [comment]
ok i will give it a try

**Comment by Lord-Haji** [comment]
There is no issue with this, and GitHub issues are not for support as I have tested the build isn't sticking up neither there is a problem with GrayScale Display
