### ISSUE TITLE
Gym Config if true, bot skips pokestops

### ISSUE THREAD

**Issue by popsoda27** [Necrobot-Private/NecroBot#163]
I realised that if I were to enable the gymconfig, the bot will only travel from gym to gym while skipping all the pokestops along the way. Is it supposed to be like this? There's no proper wiki at all so I don't know what to expect

**Comment by ajns73** [comment]
@popsoda27 Known issue. Try lowering your max distance or disable for now.

**Comment by sheang** [comment]
@ajns73 , now it able to collect item at pokestop while disable gym feature?? 

what version you using now ?

**Comment by ajns73** [comment]
It worked in .9.9.5 for me. The walking behavior got a little wonky around gyms, but it always worked.
