### ISSUE TITLE
Manual snipe doesn't work anymore

### ISSUE THREAD

**Issue by pokemaster974** [Necrobot-Private/NecroBot#1635]
### Expected Behavior:
Necrobot should find the Pokemon and catch it.

### Actual Behavior:
When I launch manual snipe from Telegram (via Telegram bot) or from internal Necrobot GUI, Necrobot doesn't find the Pokémon.
After the error, I've gone (with another account) to the location into the official Pokémon Go app (Android) after spoofing the GPS. The Pokémon wasn't despawned and I success to catch it.
I've tried with coordinates from my local RM map and with coordinates from Discord severs. Each times, Necorobot couldn't find the Pokémon but I've successed to catch them with official app (not despawned).

### Your config.json:
My snipe section wasn't modified, and worked (success to find and catch a Pokémon via manual snipe) with previous versions of Necrobot. I don't know since when it doesn't worked anymore.
```
  "SnipeConfig": {
    "UseSnipeLocationServer": false,
    "SnipeLocationServer": "localhost",
    "SnipeLocationServerPort": 16969,
    "MinPokeballsToSnipe": 25,
    "MinPokeballsWhileSnipe": 0,
    "MinDelayBetweenSnipes": 60000,
    "SnipingScanOffset": 0.01,
    "SnipeAtPokestops": true,
    "SnipeIgnoreUnknownIv": false,
    "UseTransferIvForSnipe": false,
    "SnipePokemonNotInPokedex": false,
    "UseSnipeLimit": true,
    "SnipeRestSeconds": 60,
    "SnipeCountLimit": 100,
    "ActivateMSniper": true,
    "MinIVForAutoSnipe": 101,
    "MinLevelForAutoSnipe": 30,
    "AutosnipeVerifiedOnly": false,
    "DefaultAutoSnipeCandy": 0,
    "SnipePauseOnOutOfBallTime": 50,
    "AutoSnipeMaxDistance": 0.0,
    "AutoSnipeBatchSize": 1
  },
```

### (OPTIONAL) Your Log:
```
[XX:02:42] (INFO) Pokestop L'apôtre à 65m | 14s (route Google Walk)
[XX:02:49] (INFO) (MANUAL SNIPER) Pokemon added |  Snorlax [20.44266,99.89526] IV 0%
[XX:02:51] (SNIPER) (InternalSnipe) [Sniper] Sniping a Snorlax with Unknown% IV at 20.44266,99.89526...
[XX:02:59] (SNIPER) [Sniper] Did not find a Pokemon within the Location, pokemon despawned?
[XX:03:10] (POKESTOP) Muse +50XP | 0 Gems | 3 x ItemPokeBall
[XX:03:10] (INFO) (POKESTOP LIMIT) 138/671
```

### Detailed Steps to Reproduce:
Enter manual snipe via Telegram bot or internal GUI

Version: 164
Windows Version: W10
What is affected (catch, transfer, favorite, GPX, evolve, recycle, snipe, human walk snipe, pokestops, powerup/levelup, other): manual snipe

**Comment by thrakkorozg** [comment]
Can confirm, was having the same problem yesterday.

**Comment by jjskuld** [comment]
Probably due to Niantic's most recent changes that have disabled sniping. See #1649

**Comment by pokemaster974** [comment]
Hi @jjskuld , I don't think this issue is related to the Niantic's encounter change.
This issue came since several days, and with the new Niantic's modification the sniping will made a catch flee. But in my case (and @thrakkorozg I guess) it's simply that Necrobot doesn't find the Pokémon. But if after I receive this error I go to the location with a spoofing app + official app, it worked (before the update) perfectly to find and success to catch it. So the Pokémon wasn't despawned as Necrobot logged it.

**Comment by jjskuld** [comment]
https://github.com/Necrobot-Private/NecroBot/wiki/Local-Sniping
