### ISSUE TITLE
[Feature Request] Force / set probability of small circle throw without bonus

### ISSUE THREAD

**Issue by CreativiTimothy** [Necrobot-Private/NecroBot#164]
About 5 days ago, someone did an analysis on the Silph Road on catch rates. It turns out that the smallest diameter circle possible yields the highest catch rate, regardless of any nice/great/excellent bonuses. Since I don't want to level up fast, but at the same time want a higher chance of catching the Pokemon, can we have an option for "ThrowSmallestDiamChance" and "EnableSmallestDiam"?

ThrowSmallestDiamChance determines the chance you will throw at the smallest diameter of the circle.
EnableSmallestDiam enables it and overrides the nice/great/excellent throw options.

**Comment by iwean** [comment]
Just set like this... and you'll get 210 EXP every catch :smile: 

  "CustomCatchConfig": {
    "EnableHumanizedThrows": true,
    "EnableMissedThrows": true,
    "ThrowMissPercentage": 1,
    "NiceThrowChance": 25,
    "GreatThrowChance": 50,
    "ExcellentThrowChance": 85,
    "CurveThrowChance": 95,
    "ForceGreatThrowOverIv": 25.0,
    "ForceExcellentThrowOverIv": 50.0,
    "ForceGreatThrowOverCp": 250,
    "ForceExcellentThrowOverCp": 300

**Comment by CreativiTimothy** [comment]
@iwean Can you stop trolling me? **Since I don't want to level up fast**

I want 110 XP per catch not 210 XP

**Comment by iwean** [comment]
Hey... I'm not trolling you... just set:
"ExcellentThrowChance": 100,
"CurveThrowChance": 0,

Then you got 100 EXP .... that's it !!!!

**Comment by iwean** [comment]
However... if you catch 100th on a type of pokemon you'll get 100 EXP bonuses...
So yes.... it will repeat.... so you've got 110 + 100 (bonus) = 210 EXP.

Am I trolling you??

**Comment by CreativiTimothy** [comment]
@iwean 100 excellent throw chance = 100 + 100XP = 200XP

and yes i know about the 100 pokemon bonus

**Comment by CreativiTimothy** [comment]
According to https://redd.it/500c3a

Conclusion

    **A smaller radius has a significant effect on your capture chance
    The smaller your radius, the bigger your capture chance
    You don’t need to get a “Nice”, “Great” or “Excellent” to get the increased capture chance (from the radius)
The data doesn't show any significant increase in capture chance from getting a “Nice”, “Great” or “Excellent”, and if there is, it’s a small increase
    Speculation: You might have a X2.0 modifier on your capture chance with the smallest possible circle as opposed to no modifier with the biggest possible circle.**
