### ISSUE TITLE
Sniping is broken by Niantic changes

### ISSUE THREAD

**Issue by jjskuld** [Necrobot-Private/NecroBot#1649]
Well everyone the day finally has come. Niantic has now disabled sniping by enabling new location checks.  So we can no longer snipe without triggering a softban. 👎 

Until we figure out a workaround for this (if at all possible), we will need to disable sniping.

So everyone, turn off `AutoSnipe: "true"` if you are using the auto sniping.

**Comment by bogdaniel** [comment]
Damn after finally i started using a bot =D :((

**Comment by zinzin64** [comment]
really!?snipe is dead forever?also we haven t a little hope to have issue for this incredible necrobot feature ?

**Comment by aboyz** [comment]
is snipping dead? i can't seem to see any dragonite blessy, tryanater, snowlax? anyone having the same issues? or is it just me...

**Comment by zinzin64** [comment]
Yes and if you snipe any pokémon with manuel snipe it s direct softban,i tried yesterday with à dummy account.niantic know when you snipe

**Comment by cjhart** [comment]
Is this related to CatchFlees in the bot?

All 4 of my accounts are getting catch flees on a perm basis. :(

**Comment by aboyz** [comment]
what is catchflees? anyone know when we can catch dragonite blessy, tryanater, snowlax again? I miss them.

**Comment by jesvinm** [comment]
catch flees are a part of soft ban bro dont worry it will be fixed after a few hours. and now you can't snipe anymore because niantic had changed something on their  location settings so try to avoid sniping untill somebody found a solution for this. and i have spotted a new type of ban from niantic that we can spin the poke stops but at the same time we can't catch any pokemon this is happening from 2 days. does anyone have the same problem?

**Comment by jesvinm** [comment]
@aboyz if you are unable to loot from poke stops also then you can try 40 spin at a poke stop to instant unban

**Comment by jjskuld** [comment]
Long distance sniping is now dead.. however we may still be able to implement some sort of short distance sniping where you "walk" to the snipe target if the target is close enough.  This feature was called "Human Walk Sniping" in NecroBot and it was added to the bot originally when Niantic shut down all the big mappers and snipe websites.  After we got our own sniping server, it was de-prioritized since it was no longer needed.  We should be able to update "Human Walk Sniping" and get it working smoothly shortly.

**Comment by informer0827** [comment]
This is a good new for us!!

**Comment by aboyz** [comment]
@jjskuld
Do you know when we can use the human walk snipping this will help alot.. :)

**Comment by cjhart** [comment]
My account was flagged, waited for 2 weeks account was not flagged anymore.

Started using Necrobot 168 yesterday, my config has autosnipe: false.

This morning opened Pokemon Go on my phone and the message is back warning me about using the external software,

Looks like Niantec are onto Necrobot users big time.

Just throwing this out there for the devs to let them know there is some other method that Niantec is using to detect bot use.

**Comment by CDAGaming** [comment]
@cjhart Although it isn't forced(yet), Niantic have updated their API to 0.63.1. Rest assured both PogoDev and Necrobot are working on Supporting and Updating to this new API

**Comment by cjhart** [comment]
#CDAGaming - thanks for the update.

**Comment by jjskuld** [comment]
@aboyz Yes, we will need to update the human walk sniping.  Stay tuned.

**Comment by zinzin64** [comment]
i see necrebot is now compatible with api 0.63.1 is changing something for sniping?thanks

**Comment by CDAGaming** [comment]
Yes it changed the overall method, so it's progress

**Comment by Instinct1** [comment]
is teleport sniping dead FOREVER?

**Comment by aboyz** [comment]
please bring back sniping.. without it is pointless in playing and this game will go dead!!

**Comment by CDAGaming** [comment]
@aboyz v171 does being it back but not in the same way, it's short range now

**Comment by jjskuld** [comment]
Sniping is back with v171. Short range teleport is supported but your mileage may vary depending on teleport distance.  See https://github.com/Necrobot-Private/NecroBot/wiki/Local-Sniping for more info on configuring sniping.
