### ISSUE TITLE
Adding new accounts Issue

### ISSUE THREAD

**Issue by jasontaffy** [Necrobot-Private/NecroBot#165]
When adding new accounts im getting invaild credentials error however once i login app manually and accept terms they work on bot.

I have tried with autocompletetutorial switched on but this has had no effect.

Is accepting terms now forced and can you do anything to make bot auto accept on opening?

**Comment by hardknoxni69a** [comment]
niantic lag on new accounts give a little time

**Comment by jasontaffy** [comment]
It produces an hour of invaild credentials and closes so no option to wait

**Comment by jasontaffy** [comment]
I think it maybe caused by bot fetching stats on account (pokemon, startdust, etc...) before trying to complete the autocompletetutorial

**Comment by langit7** [comment]
Its not just bot, real POGO apps facing the issue as well, i test with 3 account sometimes got fail

**Comment by jasontaffy** [comment]
im getting it every time, only time an account will work is after manually accepting terms on a device

**Comment by hardknoxni69a** [comment]
It wont work on device either just says failure to authenticate at first. Then poof bot works without accepting even those terms

**Comment by ValorRed** [comment]
It's the same with my #143 
I had several Google Accounts created for several days, always Invalid Credential using the bot. As long as I switch back to use the old NoxxDev 0.9.7, it can pass the AutoCompleteTutorial.
 The old 0.9.7 AutoCompleteTutorial setting is not full functional though. It does not have the DesiredGender setting and seems pick randomly.

This looks like a bug in the newest version.

**Comment by jasontaffy** [comment]
ValorRed, any chance you can upload me 0.9.7 please?

**Comment by ValorRed** [comment]
Will source code do? https://github.com/siosios/NoxxDev-necrobot/releases/tag/v0.9.7

**Comment by jasontaffy** [comment]
Yes thank you

**Comment by ValorRed** [comment]
@jasontaffy, if you are a developer familiar with the code, can you try to add the 2 arguments and make them work? I am not a .Net developer. Thanks
    "DesiredGender"    "DesiredStarter"

**Comment by Silph-Road** [comment]
Problem is with servers.

**Comment by hardknoxni69a** [comment]
Im glad u guys closed this i said over and over it was server issue. No need to waste your time on something that isnt your fault now u can focus on better things
