### ISSUE TITLE
[Request] random delay

### ISSUE THREAD

**Issue by Shoro2** [Necrobot-Private/NecroBot#166]
Heya,

what about a random delay instead a static? I cant say if its a issue but if all player actions etc. take exact the same time, cant people see that your using a bot? And what about a feature that the bot fakes the screensaver every few minutes (random). I mean no real person plays some hours without putting the mobile phone in his bag or sth like this.

**Comment by vfuyong** [comment]
It is good feature but not necessary. When the delay is considered static here, but it takes long to reach server. So overall the delay is naturally randomized.

**Comment by Shoro2** [comment]
Well yes but only about 100ms max. If all player actions take 5000 up to 5100 ms its still an obvious bot^^
