### ISSUE TITLE
Console message.

### ISSUE THREAD

**Issue by bogdaniel** [Necrobot-Private/NecroBot#1663]
Hey guys, today i opened my laptop and and reopened the bot. Got it updated to a new version and at some point in the console it showed me this message.

[09:40:08] (ATTENTION) This account M********* seems to be flagged, it is recommended to not use bot on this account for now!

What should i do :D?

**Comment by aboyz** [comment]
that is normal, cuz it detect you are using a bot. just stop using it and play it normaly and it'll go away.. take 1 - 2 weeks.

**Comment by bogdaniel** [comment]
Gonna stay low for a while. logged from my phone and gave me a message that i might be using third party software etc ... :D

**Comment by aboyz** [comment]
stay low my friend before your account is ban!! i'm at level 37 now :).. need to get to level 40..

**Comment by Lord-Haji** [comment]
This is obvious
Github issues are only for bug reports and feature requests not for support
