### ISSUE TITLE
evolutions with lucky egg

### ISSUE THREAD

**Issue by unknowkir** [Necrobot-Private/NecroBot#1664]
it does not use lucky egg while evolving pokemon. evolves one by one and not all together.. 

  },
  "PokemonConfig": {
    "CatchPokemon": true,
    "DelayBetweenPokemonCatch": 200,
    "UseCatchLimit": true,
    "CatchPokemonLimit": 800,
    "CatchPokemonLimitMinutes": 1350,
    "UseIncenseConstantly": false,
    "UseEggIncubators": true,
    "UseLimitedEggIncubators": true,
    "UseLuckyEggConstantly": false,
    "UseLuckyEggsMinPokemonAmount": 30,
    "UseLuckyEggsWhileEvolving": true,
    "TransferWeakPokemon": true,
    "TransferDuplicatePokemon": true,
    "TransferDuplicatePokemonOnCapture": true,
    "RenamePokemon": false,
    "RenameOnlyAboveIv": true,
    "RenameTemplate": "{Name}_{>95}_Lv{Level}",
    "FavoriteMinIvPercentage": 95.0,
    "AutoFavoritePokemon": true,
    "AutoFavoriteShinyOnCatch": false,
    "MaxPokeballsPerPokemon": 6,
    "UseGreatBallAboveCp": 1000,
    "UseUltraBallAboveCp": 1250,
    "UseMasterBallAboveCp": 1500,
    "UseGreatBallAboveIv": 85.0,
    "UseUltraBallAboveIv": 95.0,
    "UseGreatBallBelowCatchProbability": 0.2,
    "UseUltraBallBelowCatchProbability": 0.1,
    "UseMasterBallBelowCatchProbability": 0.05,
    "AutomaticallyLevelUpPokemon": false,
    "OnlyUpgradeFavorites": true,
    "UseLevelUpList": true,
    "AmountOfTimesToUpgradeLoop": 5,
    "GetMinStarDustForLevelUp": 5000,
    "LevelUpByCPorIv": "iv",
    "UpgradePokemonCpMinimum": 1000.0,
    "UpgradePokemonIvMinimum": 95.0,
    "UpgradePokemonMinimumStatsOperator": "and",
    "EvolveAboveIvValue": 95.0,
    "EvolveAllPokemonAboveIv": false,
    "EvolveAllPokemonWithEnoughCandy": true,
    "EvolveKeptPokemonsAtStorageUsagePercentage": 90.0,
    "EvolveKeptPokemonIfBagHasOverThisManyPokemon": 120,
    "KeepPokemonsThatCanEvolve": true,
    "KeepMinCp": 1250,
    "KeepMinIvPercentage": 95.0,
    "KeepMinLvl": 25,
    "KeepMinOperator": "and",
    "UseKeepMinLvl": true,
    "PrioritizeIvOverCp": true,
    "KeepMinDuplicatePokemon": 1,
    "KeepMaxDuplicatePokemon": 4,
    "UsePokemonToNotCatchFilter": false,
    "UsePokemonToCatchLocallyListOnly": false,
    "DumpPokemonStats": false,
    "DelayBetweenPokemonUpgrade": 10000,
    "OutOfBallCatchBlockTime": 5,
    "PokeballToKeepForSnipe": 50,
    "UseBulkTransferPokemon": true,
    "BulkTransferStogareBuffer": 10,
    "BulkTransferSize": 100,
    "UseBallOperator": "or",
    "FavoriteMinCp": 0.0,
    "DefaultBuddyPokemon": "",
    "FavoriteMinLevel": 0,
    "FavoriteOperator": "and",
    "RenamePokemonRespectTransferRule": false,
    "UpgradePokemonLvlMinimum": 30.0,
    "EvolveFavoritedOnly": true,
    "EvolveOperator": "and",
    "EvolveMinIV": 100.0,
    "EvolveMinCP": 2000.0,
    "EvolveMinLevel": 2000.0,
    "ByPassCatchFlee": false
  },

**Comment by hardknoxni69a** [comment]
adjust your settings accordingly for example right now any pokemon over your 120th is being evolved right away please join our discord for basic questions and of course read the wiki
