### ISSUE TITLE
PokeEase Egg images are still broken

### ISSUE THREAD

**Issue by Lord-Haji** [Necrobot-Private/NecroBot#1670]
![scrnsht](http://image.prntscr.com/image/211212d85c9a4f59a83c71fbb34d7c6c.png)
this was fully broken but @jjskuld's PR fixed it partially

**Comment by jjskuld** [comment]
@Lord-Haji I haven't played the official game in a while... so this may sound a little stupid but what's it supposed to look like?

**Comment by jjskuld** [comment]
Oh I see.. there's an incubator inside of an incubator... lol
