### ISSUE TITLE
Lucky eggs constantly problem

### ISSUE THREAD

**Issue by carrysonford** [Necrobot-Private/NecroBot#1674]
I don't want to try it due to I'm flagged right now, but I need to know if the problem of "Not checking if a lucky egg is corrently activated before to trying to activated another one" is still there.

I don't have my old logs because I delete every old version when a new version comes out, but the problem was something like "xpboost item error" and then the bot restart and enters into a infinte loop trying to activate another egg until I change manually "UseLuckyEggConstantly" to false.

Sorry for my bad English, it's not my native language.

**Comment by Lord-Haji** [comment]
Closed due to inappropriate issue formatting
