### ISSUE TITLE
Microsoft.Data.Sqlite.SqliteException: SQLite Error 26: 'file is encrypted or is not a database'.

### ISSUE THREAD

**Issue by pokemaster974** [Necrobot-Private/NecroBot#1680]
### Expected Behavior:
Launch

### Actual Behavior:
I got an error after the new update 168. I guess it's related to change with db (sqlite), but even after delete my accounts.db into the root I got the same error.

### (OPTIONAL) Your Log:
```
[09:41:16] () Configuration is up-to-date. Schema version: 25
[09:41:16] () Validating config.json...
[09:41:17] () Auth Configuration is up-to-date. Schema version: 25
[09:41:17] () Validating Auth.json...
[09:41:18] () Exception caught, writing LogBuffer.

Exception non gérée : Microsoft.Data.Sqlite.SqliteException: SQLite Error 26: 'file is encrypted or is not a database'.
   à Microsoft.Data.Sqlite.Interop.MarshalEx.ThrowExceptionForRC(Int32 rc, Sqlite3Handle db)
   à Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   à Microsoft.Data.Sqlite.SqliteCommand.ExecuteScalar()
   à Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, String executeMethod, IReadOnlyDictionary`2 parameterValues, Boolean closeConnection)
   à Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteScalar(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   à Microsoft.EntityFrameworkCore.Storage.Internal.SqliteDatabaseCreator.HasTables()
   à Microsoft.EntityFrameworkCore.Storage.RelationalDatabaseCreator.EnsureCreated()
   à PoGo.NecroBot.Logic.Model.ElevationConfigContext..ctor()
   à PoGo.NecroBot.Logic.Service.Elevation.ElevationService..ctor(GlobalSettings settings)
   à PoGo.NecroBot.CLI.Program.RunBotWithParameters(Action`2 onBotStarted, String[] args)
   à PoGo.NecroBot.CLI.Program.Main(String[] args)
```

Version: 168
Windows Version: 10
What is affected (catch, transfer, favorite, GPX, evolve, recycle, snipe, human walk snipe, pokestops, powerup/levelup, other): launch

**Comment by jjskuld** [comment]
@pokemaster974 Can you try deleting the accounts.db in the root and then also delete the accounts.db in the config folder as well?

**Comment by jjskuld** [comment]
The accounts.db in the root is the old LiteDB database, and the new location of the accounts.db is in the config folder. That one is the SQLite database.

**Comment by pokemaster974** [comment]
Hi @jjskuld in fact I try this before I post this thread (delete the old account db file in the root directory, and the new account database written into the config directory)
I made more investigations (I delete file one by one) and after delete elevation db (storage) it seems to work.

I had this issue on my 6 folders. The procedure explained above (delete the "Cache" folder) seems to fix the issue for all my folders.
I close this issue, and hope that it could be helpful for other botters.
Regards.

**Comment by pokemaster974** [comment]
I see that someone fixes his issue with the same trick.

**So I guess that if someone have his issue (stuck or error logs) :
- delete all accounts.db
- delete the whole "Config" directory**

After that if you still have issue, feel free to open a ticket :)

**Comment by CDAGaming** [comment]
Will Include this in Discord Chat, thanks pokemaster :)

**Comment by pokemaster974** [comment]
I update my comm because it wasn't the config folder but the cache folder to delete (SessionStats seems to not be a problem with this change of db engine, I success to keep my 24h timespawn stats). Hope that nobody have delete his Config folder :)
