### ISSUE TITLE
Pokestop Loot

### ISSUE THREAD

**Issue by LimitedOC** [Necrobot-Private/NecroBot#1681]
For some reason bot doesnt loot the pokestops, altho i havent change anything in config or get softbanned. if u use my phone to loot i get everything but bot travels to the pokestops and doesnt take any items. does  any1 have the same issue with me? what do i have to do?

**Comment by cjhart** [comment]
Yes.

**Comment by aboyz** [comment]
i think its working again..

**Comment by LimitedOC** [comment]
its not. am like 720xp/h.. it loot some pokestops and then nothing. it goes and aint get anything
