### ISSUE TITLE
[Request] Update the Wiki's Instructions for Mapzen

### ISSUE THREAD

**Issue by greenDarkness** [Necrobot-Private/NecroBot#1684]
The Mapzen website changed and link https://mapzen.com/developers/ under API Keys For Navigation and Elevation just directs you to the dashboard.
The screenshots are also outdated, as the site looks different now. 
Details on how to enable a key for "Turn by Turn", and "Elevation Service" are needed.
Thank you for reading.

**Comment by pokemaster974** [comment]
Mapzen have unified their services last year, so Turn by Turn and Elevation service use now the same key. See https://mapzen.com/blog/unified-api-keys/

But I don't know if this modification have a repercussion into Necrobot. I mean, do devs need to modify their code, or using the "new" unified key work perfectly.
Maybe that @jjskuld could better answer to you, I've not the skills for that :)

**Comment by greenDarkness** [comment]
@pokemaster974 Thank you for the response. 
[22:13:48] (ATTENTION) Mapzen Elevation Service response not reliable and will be blacklisted for one hour.
I keep getting the message above every time I launch Necrobot, so I think some modifications will need to be made.

**Comment by pokemaster974** [comment]
I got exactly the same thing but with Google Elevation :
[10:32:36] (ATTENTION) Google Elevation Service response not reliable and will be blacklisted for one hour.
[10:32:36] (ATTENTION) Falling back to next elevation strategy: Random Elevation Service (Necrobot Default).

**Comment by jjskuld** [comment]
You can now use the same key or different keys in `MapzenTurnByTurnApiKey` and `MapzenElevationApiKey`.

**Comment by Lord-Haji** [comment]
Closing coz it's not bout development
U can get support from discord
