### ISSUE TITLE
Bot freezes with a given GPX File

### ISSUE THREAD

**Issue by mo-mueller** [Necrobot-Private/NecroBot#1689]
### Expected Behavior:

Bot should run with a given GPX file.

### Actual Behavior:

Bot freezes after the "Bot Switching Account..." message is gone. No errors are logged.

### Your config.json:
[https://pastebin.com/iKpHSJHG](https://pastebin.com/iKpHSJHG)
(I have removed my google and mapzen api keys)

### Detailed Steps to Reproduce:

1. `git clone --recursive https://github.com/Necrobot-Private/NecroBot.git`
2. Open project with Visual Studio 2017
3. Run PoGo.Necrobot.Window
4. Add the Auth and Config info
5. Close the bot after the first setup
6. Create GPX file [https://pastebin.com/jbMKUMFs](https://pastebin.com/jbMKUMFs) and place it in PoGo.NecroBot.Window > bin > Debug and name it "route.gpx".
7. Enable GPXPathing in config and set the name of the gpx file
8. Start the Bot again
9. Bot freezes after the "Bot Switching Account..." message is gone

### Other Information

Version: Source Code cloned from github (11.05.2017 17:43)
Windows Version: Windows 10
What is affected: GPX

**Comment by hardknoxni69a** [comment]
@jjskuld may be able to help further if needed but please try a different gpx service as yours may be incompatible and also check config on wiki and make sure you have placed in with your exe the wiki helps build and make your own folder dont just run through VS
