### ISSUE TITLE
v170 does not show "Level", "XP/H", "PKM/H", "Runtime", "Level Up in", "Stardust" ...

### ISSUE THREAD

**Issue by 6Vampire6** [Necrobot-Private/NecroBot#1705]
Keep it simple, use a screenshot. ;-)

![1](https://cloud.githubusercontent.com/assets/20929443/26070425/e2711dc2-39a4-11e7-8a31-72db8c900803.png)

**Comment by CDAGaming** [comment]
We are aware of this already, and looking into this. Confirmed Verified Issue.

**Comment by iSporean** [comment]
issues still exist in V171.

**Comment by CDAGaming** [comment]
This Issue is meant to occur. The Statuses do not update until after a request of its type comes in. We will change the text in player info to better represent this.

**Comment by mboeder** [comment]
@CDAGaming Even after such a request of its type came in the status does not update

**Comment by Lord-Haji** [comment]
This was fixed
