### ISSUE TITLE
V1.70 and 1.71 multibot

### ISSUE THREAD

**Issue by Bullerjmp** [Necrobot-Private/NecroBot#1714]
The new version is not changing between accounts.
Didn't change anything - just stopped worked after auto update

**Comment by jjskuld** [comment]
Dup of #1716. PTC is down

**Comment by Bullerjmp** [comment]
The issue has been there since the 1.70 came out so don't think it's the PTC 
I can shift manual just fine, no errors in login or anything.

Have a correction - it sometimes changes between accounts , other times it  ignores the settings and run many hours on one account, not logging in on the others.
It does it on both PTC and google.
