### ISSUE TITLE
i'm use GymConfig...?

### ISSUE THREAD

**Issue by zsatanxz** [Necrobot-Private/NecroBot#172]
i'm team blue set gymconfig..??
ex..?
  "GymConfig": {
    "Enable": true,
    "MaxDistance": 150.0,
    "DefaultTeam": "Yellow",
    "MaxCPToDeploy": 1000,
    "MaxLevelToDeploy": 16,
    "VisitTimeout": 60,
    "UseRandomPokemon": false,
    "NumberOfTopPokemonToBeExcluded": 10
  },

**Comment by zsatanxz** [comment]
![1111111111111](https://cloud.githubusercontent.com/assets/21266188/18594998/e7a48b6c-7c6c-11e6-9943-f72922602353.jpg)

what????

**Comment by iwean** [comment]
No problem... it's only effect if you have not on a team before (fresh account).

You are on team blue, so your pokemon only deploy on team blue gym (where have a slot)

**Comment by zsatanxz** [comment]
@iwean For example, for me

**Comment by iwean** [comment]
You are on team blue, so your pokemon only deploy on team blue gym (where have a slot)

**Comment by zsatanxz** [comment]
@iwean you help ex. gym config thx

**Comment by iwean** [comment]
There's nothing wrong with your gym config.

**Comment by zsatanxz** [comment]
@iwean 
it's okay ??

  "GymConfig": {
    "Enable": true,
    "MaxDistance": 150.0,
    "DefaultTeam": "Blue",
    "MaxCPToDeploy": 1000,
    "MaxLevelToDeploy": 16,
    "VisitTimeout": 60,
    "UseRandomPokemon": false,
    "NumberOfTopPokemonToBeExcluded": 10
  },

**Comment by iwean** [comment]
Okay... totally okay :smile:

**Comment by tr1p0z** [comment]
Bots are getting money cuz "fight gym option" sadly.

**Comment by zsatanxz** [comment]
@tr1p0z what

**Comment by iwean** [comment]
I don't think so... this forked just for fun. The dev team enjoy working on code. Nothing special.

**Comment by tr1p0z** [comment]
Im speaking about Poke.Ninja bot
