### ISSUE TITLE
New released 0.37.1

### ISSUE THREAD

**Issue by tuxfrw** [Necrobot-Private/NecroBot#175]
New released to 0.37.1 in Pokemon GO

My location: Brazil

**Comment by tuxfrw** [comment]
2016. 9. 16
Trainers, Pokémon GO is being updated to version 0.37.1 for Android and 1.7.1 for iOS with minor fixes for the Pokémon GO Plus.

**Comment by Pinha** [comment]
@tuxfrw também sou do Brasil... cola aqui: https://discord.gg/cj4xa

**Comment by Silph-Road** [comment]
thanks for the update.
