### ISSUE TITLE
Sniping Problem

### ISSUE THREAD

**Issue by bstsxvsbstfr** [Necrobot-Private/NecroBot#1751]
Hi, anyone having issues with manual sniping and sniping in general, most cases i have no sniped any good pokemons. nothing rare has been caught 

mostly catching natu, pidgey, etc, not a single dragonite, lapras, snorlax etc in 2 days, most jumps cannot find a pokemon within location "did not find a pokemonb within the location, pokemon despawned?
  },
  "SnipeConfig": {
    "UseSnipeLocationServer": false,
    "SnipeLocationServer": "localhost",
    "SnipeLocationServerPort": 16969,
    "MinPokeballsToSnipe": 25,
    "MinPokeballsWhileSnipe": 0,
    "MinDelayBetweenSnipes": 60000,
    "SnipingScanOffset": 0.01,
    "SnipeAtPokestops": true,
    "SnipeIgnoreUnknownIv": false,
    "UseTransferIvForSnipe": false,
    "SnipePokemonNotInPokedex": false,
    "UseSnipeLimit": true,
    "SnipeRestSeconds": 60,
    "SnipeCountLimit": 100,
    "ActivateMSniper": true,
    "MinIVForAutoSnipe": 101,
    "MinLevelForAutoSnipe": 30,
    "AutosnipeVerifiedOnly": false,
    "DefaultAutoSnipeCandy": 0,
    "SnipePauseOnOutOfBallTime": 50,
    "AutoSnipeMaxDistance": 0.0,
    "AutoSnipeBatchSize": 1
  },
 },
  "DataSharingConfig": {
    "EnableSyncData": true,
    "AutoSnipe": true,
    "DataServiceIdentification": "uuidcode",
    "SnipeDataAccessKey": "",
    "EnableFailoverDataServers": true,
    "FailoverDataServers": "ws://s1.mypogosnipers.com/socket.io/?EIO=3&transport=websocket;ws://s2.mypogosnipers.com/socket.io/?EIO=3&transport=websocket;ws://necrosocket.herokuapp.com/socket.io/?EIO=3&transport=websocket",
    "DataRecieverURL": "ws://www.mypogosnipers.com/socket.io/?EIO=3&transport=websocket;ws://necrosocket.herokuapp.com/socket.io/?EIO=3&transport=websocket"
  "SnipePokemonFilter": {
    "Lapras": {
      "SnipeIV": 0,
      "Moves": [],
      "Operator": "or",
      "VerifiedOnly": false,
      "Priority": 5,
      "AutoSnipeCandy": 2000,
      "Level": 0,
      "AllowMultiAccountSnipe": false,
      "AffectToPokemons": []
    },
    "Dragonite": {
      "SnipeIV": 0,
      "Moves": [],
      "Operator": "or",
      "VerifiedOnly": false,
      "Priority": 5,
      "AutoSnipeCandy": 2000,
      "Level": 0,
      "AllowMultiAccountSnipe": false,
      "AffectToPokemons": []
    },
    "Snorlax": {
      "SnipeIV": 0,
      "Moves": [],
      "Operator": "or",
      "VerifiedOnly": false,
      "Priority": 5,
      "AutoSnipeCandy": 2000,
      "Level": 0,
      "AllowMultiAccountSnipe": false,
      "AffectToPokemons": []
    },
    "Dratini": {
      "SnipeIV": 0,
      "Moves": [],
      "Operator": "or",
      "VerifiedOnly": false,
      "Priority": 5,
      "AutoSnipeCandy": 2000,
      "Level": 0,
      "AllowMultiAccountSnipe": false,
      "AffectToPokemons": []
    },
    "Rhyhorn": {
      "SnipeIV": 0,
      "Moves": [],
      "Operator": "or",
      "VerifiedOnly": false,
      "Priority": 5,
      "AutoSnipeCandy": 2000,
      "Level": 0,
      "AllowMultiAccountSnipe": false,
      "AffectToPokemons": []
    },
    "Abra": {
      "SnipeIV": 0,
      "Moves": [],
      "Operator": "or",
      "VerifiedOnly": false,
      "Priority": 5,
      "AutoSnipeCandy": 2000,
      "Level": 0,
      "AllowMultiAccountSnipe": false,
      "AffectToPokemons": []
    }
  },
  "PokemonEvolveFilter": {
    "Rattata": {
      "MinIV": 0.0,
      "MinLV": 0.0,
      "MinCP": 0.0,
      "Moves": [],
      "Operator": "or",
      "EvolveTo": "",
      "AffectToPokemons": [
        "zubat",
        "pidgey",
        "caterpie",
        "weedle"
      ],
      "FavoritedOnly": false,
      "MinCandiesBeforeEvolve": 0
    },
    "Porygon": {
      "MinIV": 100.0,
      "MinLV": 28.0,
      "MinCP": 500.0,
      "Moves": [],
      "Operator": "and",
      "EvolveTo": "Porygon2",
      "AffectToPokemons": null,
      "FavoritedOnly": false,
      "MinCandiesBeforeEvolve": 0
    },
    "Gloom": {
      "MinIV": 100.0,
      "MinLV": 28.0,
      "MinCP": 500.0,
      "Moves": [],
      "Operator": "and",
      "EvolveTo": "Bellossom",
      "AffectToPokemons": null,
      "FavoritedOnly": false,
      "MinCandiesBeforeEvolve": 0
    },
    "Sunkern": {
      "MinIV": 100.0,
      "MinLV": 28.0,
      "MinCP": 500.0,
      "Moves": [],
      "Operator": "and",
      "EvolveTo": "Sunflora",
      "AffectToPokemons": null,
      "FavoritedOnly": false,
      "MinCandiesBeforeEvolve": 0
    },
    "Slowpoke": {
      "MinIV": 100.0,
      "MinLV": 28.0,
      "MinCP": 500.0,
      "Moves": [],
      "Operator": "and",
      "EvolveTo": "Slowking",
      "AffectToPokemons": null,
      "FavoritedOnly": false,
      "MinCandiesBeforeEvolve": 0
    },
    "Poliwhirl": {
      "MinIV": 100.0,
      "MinLV": 28.0,
      "MinCP": 500.0,
      "Moves": [],
      "Operator": "and",
      "EvolveTo": "Politoed",
      "AffectToPokemons": null,
      "FavoritedOnly": false,
      "MinCandiesBeforeEvolve": 0
    },
    "Seadra": {
      "MinIV": 100.0,
      "MinLV": 28.0,
      "MinCP": 500.0,
      "Moves": [],
      "Operator": "and",
      "EvolveTo": "Kingdra",
      "AffectToPokemons": null,
      "FavoritedOnly": false,
      "MinCandiesBeforeEvolve": 0
    },
    "Dratini": {
      "MinIV": 100.0,
      "MinLV": 30.0,
      "MinCP": 800.0,
      "Moves": [],
      "Operator": "and",
      "EvolveTo": "",
      "AffectToPokemons": null,
      "FavoritedOnly": false,
      "MinCandiesBeforeEvolve": 0
    }
  },
  "CatchPokemonFilter": {
    "Lapras": {
      "MinIV": 0,
      "MinLV": 0,
      "MinCP": 0,
      "Moves": [],
      "Operator": "or"
    },
    "Dratini": {
      "MinIV": 0,
      "MinLV": 0,
      "MinCP": 0,
      "Moves": [],
      "Operator": "or"
    },
    "Dragonite": {
      "MinIV": 0,
      "MinLV": 0,
      "MinCP": 0,
      "Moves": [],
      "Operator": "or"
    },
    "Snorlax": {
      "MinIV": 0,
      "MinLV": 0,
      "MinCP": 0,
      "Moves": [],
      "Operator": "or"
    },
    "Zubat": {
      "MinIV": 100,
      "MinLV": 100,
      "MinCP": 0,
      "Moves": [],
      "Operator": "and"
    }
  },
  "BotSwitchPokemonFilters": {
    "Lickitung": {
      "IV": 30,
      "RemainTimes": 60,
      "Operator": "or",
      "AffectToPokemons": [],
      "LV": 0,
      "Moves": []
    },
    "Dragonite": {
      "IV": 10,
      "RemainTimes": 60,
      "Operator": "or",
      "AffectToPokemons": [],
      "LV": 0,
      "Moves": []
    },
    "Lapras": {
      "IV": 10,
      "RemainTimes": 60,
      "Operator": "or",
      "AffectToPokemons": [],
      "LV": 0,
      "Moves": []
    },
    "Exeggutor": {
      "IV": 10,
      "RemainTimes": 60,
      "Operator": "or",
      "AffectToPokemons": [],
      "LV": 0,
      "Moves": []
    },
    "Magmar": {
      "IV": 70,
      "RemainTimes": 60,
      "Operator": "or",
      "AffectToPokemons": [],
      "LV": 0,
      "Moves": []
    },
    "Arcanine": {
      "IV": 10,
      "RemainTimes": 60,
      "Operator": "or",
      "AffectToPokemons": [],
      "LV": 0,
      "Moves": []
    },
    "Beedrill": {
      "IV": 10,
      "RemainTimes": 60,
      "Operator": "or",
      "AffectToPokemons": [],
      "LV": 0,
      "Moves": []
    },
    "Blastoise": {
      "IV": 10,
      "RemainTimes": 60,
      "Operator": "or",
      "AffectToPokemons": [],
      "LV": 0,
      "Moves": []
    },
    "Charizard": {
      "IV": 10,
      "RemainTimes": 60,
      "Operator": "or",
      "AffectToPokemons": [],
      "LV": 0,
      "Moves": []
    },
    "Venusaur": {
      "IV": 10,
      "RemainTimes": 60,
      "Operator": "or",
      "AffectToPokemons": [],
      "LV": 100,
      "Moves": []
    },
    "Vileplume": {
      "IV": 10,
      "RemainTimes": 60,
      "Operator": "or",
      "AffectToPokemons": [],
      "LV": 0,
      "Moves": []
    },
    "Vaporeon": {
      "IV": 10,
      "RemainTimes": 60,
      "Operator": "or",
      "AffectToPokemons": [],
      "LV": 0,
      "Moves": []
    },
    "Dragonair": {
      "IV": 70,
      "RemainTimes": 60,
      "Operator": "or",
      "AffectToPokemons": [],
      "LV": 0,
      "Moves": []
    },
    "Dratini": {
      "IV": 90,
      "RemainTimes": 60,
      "Operator": "or",
      "AffectToPokemons": [],
      "LV": 100,
      "Moves": []
    },
    "Snorlax": {
      "IV": 30,
      "RemainTimes": 60,
      "Operator": "or",
      "AffectToPokemons": [],
      "LV": 0,
      "Moves": []
    },
    "Kangaskhan": {
      "IV": 80,
      "RemainTimes": 60,
      "Operator": "or",
      "AffectToPokemons": [],
      "LV": 0,
      "Moves": []
    },
    "Ninetales": {
      "IV": 10,
      "RemainTimes": 60,
      "Operator": "or",
      "AffectToPokemons": [],
      "LV": 0,
      "Moves": []
    },
    "Electabuzz": {
      "IV": 10,
      "RemainTimes": 60,
      "Operator": "or",
      "AffectToPokemons": [],
      "LV": 0,
      "Moves": []
    },
    "Magikarp": {
      "IV": 95,
      "RemainTimes": 60,
      "Operator": "or",
      "AffectToPokemons": [],
      "LV": 0,
      "Moves": []
    }

thats current config, is there a problem with sniping atm or am i doing something wrong?

**Comment by Lord-Haji** [comment]
After recent changes Sniping is detected by Niantic and it flags your account
so original sniping was turned down u only a HumanWalkSniping its likely you'll get much less amount of rare pokemon than before

**Comment by jjskuld** [comment]
https://github.com/Necrobot-Private/NecroBot/wiki/Local-Sniping
