### ISSUE TITLE
AutoSnipe only works within a limit does not work in other countries or states

### ISSUE THREAD

**Issue by cicerocruz** [Necrobot-Private/NecroBot#1754]
After the last updates the autosnipe is only operating within a very small limit ... Something like 1500m from where I am.

**Comment by CDAGaming** [comment]
It's in a small limit because of a new limitation implemented by Niantic @cicerocruz . Going further than the radius would mostly result in a softban or instant flag

**Comment by jjskuld** [comment]
See https://github.com/Necrobot-Private/NecroBot/wiki/Local-Sniping
