### ISSUE TITLE
what 0.9.9.6

### ISSUE THREAD

**Issue by zsatanxz** [Necrobot-Private/NecroBot#176]
"DataSharingConfig": {
    "EnableSyncData": true,
    "DataRecieverURL": "ws://necrosocket.herokuapp.com/socket.io/?EIO=3&transport=websocket"
  },

**Comment by zsatanxz** [comment]
adn not work

**Comment by TakRiuto** [comment]
Im Going to disable this option... Is very rare...

**Comment by zsatanxz** [comment]
i'm not use 0.9.9.6

**Comment by zsatanxz** [comment]
![333333333333333](https://cloud.githubusercontent.com/assets/21266188/18605324/0c7d65f2-7cb9-11e6-9245-02c4588a7ac6.jpg)

**Comment by zsatanxz** [comment]
why close topic

**Comment by Silph-Road** [comment]
It's not an issue or bug :-)
It's only data for sniping Pokemon.
