### ISSUE TITLE
[Announcement] Only use the latest release.

### ISSUE THREAD

**Issue by Silph-Road** [Necrobot-Private/NecroBot#177]
The latest releases have updates to the .35 API that is used by the bot to connect.

**Older releases can have a mix of .35 and .33 API and are not safe at all.**

I read a lot of users talking about using older releases that are so old that they only have .33 API.
If you are using those, you are just wasting time as they are getting flagged immediately since no .33 app is actually allowed to run.

If you have problems logging in the first time, you are not alone...... people with official app also have the same problem. It is not a bot problem, its a server problem.

Please update to the latest release whenever it is made available.

FYI: .37 API is not available.

**Comment by vfuyong** [comment]
@Silph-Road Can you confirm whether 0.9.7 uses 0.33 API?

**Comment by Renton91** [comment]
But is it safe to run bot that uses 0.35 API if I have installed on my phone version 0.37.1?

**Comment by BoydTM** [comment]
as long as 0.35 is allowed by niantic ...

**Comment by Silph-Road** [comment]
@vfuyong no that's really old, I think only the last 4 releases were .35 so like 0.9.9.2 and later and the more newer the better/safer it works with .35

@BoydTM yes more specifically... as long as .35 apps are not forced to update to .37.1

**Comment by jjskuld** [comment]
See #285
