### ISSUE TITLE
French + MaxTravelDistanceInMeters

### ISSUE THREAD

**Issue by gilbert1995** [Necrobot-Private/NecroBot#1775]
When I set language for french, app can't read MaxTravelDistanceInMeters in config.json

If I switch back to english it works well

**Comment by Furtif** [comment]
? c'est le même programme pourtant cela depend du temps et de la position du bot jusq'au trouver un pokestop de depart

**Comment by Furtif** [comment]
If my explanation answers your problem, can you close this issue?

**Comment by gilbert1995** [comment]
Je ne sais pas vraiment, on peut le fermer j'ai cesser d'utiliser le bot, mais je faisais les même manipulation sur le programme FR et EN mais en FR j'avais un bug
