### ISSUE TITLE
Ptc account doesn't work 

### ISSUE THREAD

**Issue by meteoxane** [Necrobot-Private/NecroBot#1781]
Hi dears, 
For my google's pokemon account everything is ok bue, it's been about a week that my ptc accounts (two), do not bot with this message in log...

" [01:52:34] (ERREUR) Unexpected response from Pokemon SSO OAuth Login Url: Status code NotFound" ... 

Plz, have you got any solution ?

**Comment by CDAGaming** [comment]
That status code can mean that it couldn't find an account with that info. Please Verify you entered correct info in auth.json and or verify the account isn't banned by logging into the app or PTC website

**Comment by meteoxane** [comment]
Thanks for your answer dear. 
I did check the auth.json and also the website. It works on both telephone and website. Yet, i've the warning message that appears on my phone telling me they suspected my account of blablabla but not blocked. I'm even used to it ! :D

**Comment by meteoxane** [comment]
[02:37:06] () Configuration is up-to-date. Schema version: 25
[02:37:06] () Validating config.json...
[02:37:06] () Auth Configuration is up-to-date. Schema version: 25
[02:37:06] () Validating Auth.json...
[02:37:06] () Console Layout is now 'Default'
[02:37:07] () Key: XXXYXXXXXXXXXXXX RPM: 150 Expiration Date: 6/4/2017
[02:37:08] (ERREUR) Counld't start socket server at port 14251, this port may be in use or blocked, please change your config to another port and restart bot if you want to use web gui.
[02:37:08] (INFO) Account changed to XXXXXXX.
[02:37:08] (INFO) XXXXXXX (Level: 35)			Runtime : 00:00:00:00
[02:37:09] (MISE A JOUR) NecroBot v1.0.0.176 up to date.
[02:37:09] (INFO)  Votre IP est: 
[02:37:09] (INFO) Connecion via Ptc
[02:37:09] (ERREUR) Unexpected response from Pokemon SSO OAuth Login Url: Status code NotFound

**Comment by CDAGaming** [comment]
Use CMD to check that port to see what's running it(If using Multiple bots, you can't use the same ports on all of them)

**Comment by meteoxane** [comment]
Thanks dear. I stopped websocket for the google's account and enabled it for the PTC buet, yet, the same (Error) Unexpected response from Pokemon SSO OAuth Login Url: Status code NotFound

**Comment by CraigMack69** [comment]
i am also getting the same error. confirmed the info by manually logging into PTC with the very same info.

**Comment by meteoxane** [comment]
It finally worked on a new wifi adresse! 
When i change my connection everything works! I was connected to a new wifi network and bot was doing well. Once home, i shared my phone's 3G connection with my pc and it was ok! 
Strange... still don't know what does that mean.

**Comment by CraigMack69** [comment]
yes i also have changed ip and worked, Forgot to update this post.

**Comment by TheWizard1328** [comment]
If you can’t play on your phone on home wifi then you are IP banned for home wifi IP. Just try to release & renew your home external IP address.

Wizard Worxx
Where the magic of software begins.
Robert Tauber
(780) 236-1542
www.Facebook.com/WizardWorxx13

**Comment by Alfurin** [comment]
My auth file dosnt even have a place to put my login details.

**Comment by TheWizard1328** [comment]
Paste this at line #2 of your Auth File. Remove all after each <--

  "Bots": [
    {
      "AuthType": "",  <--ppc or google
      "Username": "", <--email address used
      "Password": "" <--passcode used
    }, <--if only one bot then remove comma and disregard next 5 lines
    {
      "AuthType": "",
      "Username": "",
      "Password": ""
    }
  ],

Wizard Worxx
Where the magic of software begins.
Robert Tauber
(780) 236-1542
www.Facebook.com/WizardWorxx13

**Comment by LimitedOC** [comment]
im also getting this error and i contacted the niantic (cuz i was already flagged) and i asked them if i got banned and they told me no.. altho i cant play from mobile or botting.

**Comment by tejastadas** [comment]
same here also

**Comment by Furtif** [comment]
Fixed into https://github.com/Necrobot-Private/NecroBot/issues/1825
