### ISSUE TITLE
0.9.9.6 'POGOProtos.Networking.Responses.DiskEncounterResponse' does not contain a definition for 'WildPokemon'

### ISSUE THREAD

**Issue by BoydTM** [Necrobot-Private/NecroBot#179]
Version: 0.9.9.6
Windows Version: 10
![necerror 3](https://cloud.githubusercontent.com/assets/21159620/18606273/55c8a7de-7cab-11e6-85ac-eb45a70742a2.jpg)

What is affected (catch, transfer, favorite, GPX, evolve, recycle, snipe, human walk snipe, pokestops, powerup/levelup, other):

**Comment by BoydTM** [comment]
With some runs it not happens immediately (but after few pokemons caught)
![necerror 4](https://cloud.githubusercontent.com/assets/21159620/18606386/d4a85132-7cae-11e6-8b8f-4a84a18ee49f.jpg)

**Comment by xhaoran06** [comment]
Did you use your config from v0.9.9.5 on this?

**Comment by BoydTM** [comment]
Yeeeep, you think config is causing that ?

**Comment by BoydTM** [comment]
the only difference seems to be:
  "DataSharingConfig": {
    "EnableSyncData": false,
    "DataRecieverURL": "ws://necrosocket.herokuapp.com/socket.io/?EIO=3&transport=websocket"
  },

**Comment by xhaoran06** [comment]
no wonder XD

  "DataSharingConfig": {
    "EnableSyncData": true,
    "DataRecieverURL": "ws://necrosocket.herokuapp.com/socket.io/?EIO=3&transport=websocket"
  },
  "PokeStopConfig": {
    "UsePokeStopLimit": true,
    "PokeStopLimit": 1950,
    "PokeStopLimitMinutes": 1440
  },

**Comment by BoydTM** [comment]
This section (DataSharingConfig) has beed added automatically ... i just changed "EnableSyncData": false (but error appears also with it set to true)

**Comment by BoydTM** [comment]
After moving outside the area with lures - error disappeared for a moment (20 minutes without)

**Comment by iwean** [comment]
@BoydTM 
DataSharing is use to get user data pokemon catch, and sharing it on feeder site:
http://necrosocket.herokuapp.com/

**Comment by mo0ojava** [comment]
Tested a bit. Appears this happens because IncensePokemons show up in CatchPokemon. There doesn't seem to be anything wrong with the response per se.
![skarmklipp](https://cloud.githubusercontent.com/assets/20909700/18610394/a16c37e4-7d1b-11e6-9965-f396e95cb3ae.PNG)

**Comment by erickerich** [comment]
same here with 0.9.9.7.
it won't happen in the area without lures.

**Comment by samuraitruong** [comment]
fixing it now, sorry my bad :dancers:

**Comment by samuraitruong** [comment]
ahh, not my fault. debuging mode

**Comment by jjskuld** [comment]
I'm testing a fix for this as well.  It seems the code needs to differentiate between different response types.

**Comment by CreativiTimothy** [comment]
Same problem. Version number 9.9.7

**Comment by BoydTM** [comment]
If its such problematic and will take a lot of time .... maybe you could consider disabling lured encounters as a temporal workaround ... currently 0.9.9.6 & 0.9.9.7 are useless because this error in loop causing pokemon/pokestops counter achieving limit very fast ...

**Comment by mo0ojava** [comment]
Hey @BoydTM. You know this is a hobby project, right? Its not like the devs are responsible for keeping things running 24/7. Relax.

**Comment by BoydTM** [comment]
Sure.... its not a SLA... and i am not trying to push any of you, it was only a mere suggestion assuming that proper fix may take days or longer ... because there is no point in releasing new versions with this bug unpatched somehow

**Comment by DontNuts** [comment]
The problem may be here in CatchPokemonTask.cs

                var unixTimeStamp = encounter.WildPokemon?.LastModifiedTimestampMs + encounter.WildPokemon?.TimeTillHiddenMs;
                DateTime expiredDate = new DateTime(1970, 1, 1, 0, 0, 0).AddMilliseconds(Convert.ToDouble(unixTimeStamp));

                session.EventDispatcher.Send(new EncounteredEvent()
                {
                    Latitude = latitude,
                    Longitude = longitude,
                    PokemonId = encounteredPokemon.PokemonId,
                    IV = pokemonIv,
                    Level = (int)lv,
                    Expires = expiredDate.ToUniversalTime(),
                    ExpireTimestamp = unixTimeStamp,
                    SpawnPointId = encounter.WildPokemon?.SpawnPointId,
                    EncounterId = encounter.WildPokemon?.EncounterId

                });

As you can see it uses WlldPokemon directly without checking if the "encounter" is EncounterResponse or not
