### ISSUE TITLE
[Feature Request] Snipe by order

### ISSUE THREAD

**Issue by petpetpetvm** [Necrobot-Private/NecroBot#180]
I think that we should have an order for sniping for the bot to follow, like 
local -> pokezz -> pokewatchers.... and if there are 5(example) new pokemons in localhost, then the bot should skip whatever that it's sniping to snipe back to localhost
and
sniperbyiv : snipe pokemons with higher iv first, or auto ignore pokemons with lower iv than ....

**Comment by Silph-Road** [comment]
Tbd
