### ISSUE TITLE
How do you update the bot's location?

### ISSUE THREAD

**Issue by justj0sh** [Necrobot-Private/NecroBot#1801]
I would like to add a telegram command for updating the botting location and it would be appreciated if someone could point me in the right direction instead of having to look through all the lines of code. I've tried updating session.currentLatitude/currentLongitude but it doesn't change the botting location.

**Comment by Lord-Haji** [comment]
Simply change them in config.json

**Comment by justj0sh** [comment]
I know you can change it manually I'm trying to make it process the location change via talking it through telegram. Which value updates the botting location?
