### ISSUE TITLE
AutoSnipe IV Calculator Calculating Wrong IV

### ISSUE THREAD

**Issue by Pomptartbaby** [Necrobot-Private/NecroBot#1806]
So I set up my bot to not catch pokemon and only snipe. I only want it to snipe pokemon that are over 85%IV level, however the bot continues to accept any pokemon rather than just the ones 85%IV and higher. Not only that, but I notice that when reading the logs/snipe info it says for instance its catching a Pidgey at 34%IV. When it actually catches the Pidgey, it will have 18%IV which is  lower than previously stated. So my question is, is it possible to only catch pokemon of the IV I want, or is there some internal issue making that impossible. Just ahead of time, here are the two settings that should effect the issue im having;

"AutoSnipe": true,
"MinIVForAutoSnipe": 85,

I can post my whole config if necessary but I don't think it is. I have also tried to work around this by setting the "MinIVForAutoSnipe":101, and then putting the pokemon's specific name like this in the filter;

"SnipePokemonFilter": {
    "Pidgey": {
      "SnipeIV": 85,
      "Moves": [],
      "Operator": "or",
      "VerifiedOnly": false,
      "Priority": 3,
      "AutoSnipeCandy": 2000,
      "Level": 0,
      "AllowMultiAccountSnipe": false,
      "AffectToPokemons": []
    }

Even doing this it still would go out of its way to catch Pidgey at lower IV's and as stated, when caught they would be even lower than the already low IV they were catching. Is this something Niantic put in place to fight IV Sniping? Thanks in advance for any info.

**Comment by Lord-Haji** [comment]
IVs r now randomized
