### ISSUE TITLE
GUI does not display pokemon details when selected

### ISSUE THREAD

**Issue by popsoda27** [Necrobot-Private/NecroBot#181]
### Expected Behavior:

Display pokemon details when selected so that can perform actions like transfer/upgrade/evolve etc.
### Actual Behavior:

Some can display when clicked, some don't respond at all
### Your config.json:

```
replace this text with the contents of your config.json

```
### (OPTIONAL) Your Log:

```
replace this text with only the "relative" portion of your log. (Remove unnessary lines)

```
### Detailed Steps to Reproduce:

Bot Console Version 0.9.9.6. Bot GUI version 0.9.9.5 since no newer GUI version is released.
### Other Information

http://imgur.com/a/PiF4x

Referring to the pic, the first row doesn't have any response when clicked. 2nd row only the 1st and 3rd pokemons responded when clicked. 3rd row all pokemons responded when clicked.

Version:
Windows Version: 8.1
What is affected (catch, transfer, favorite, GPX, evolve, recycle, snipe, human walk snipe, pokestops, powerup/levelup, other):

**Comment by XurWuy** [comment]
I noticed when you have more than 1 of same pokemon, it will not opened the status of the pokemon.

**Comment by popsoda27** [comment]
Update: I update Necrobot GUI to 0.9.9.7. Same issue. It's always the top few strongest pokemons plus some random lower tier ones that could not display status.

@XurWuy not really bcos i have several pidgeys and could open all but i have 1 lapras that doesn't open

**Comment by popsoda27** [comment]
On those that can display status, I find that there are context errors

http://imgur.com/a/R4lJ6

**Comment by ungz** [comment]
Try to use chrome as default instead of ie or edge.

**Comment by gjimenezf** [comment]
I have the same problem, I am using Chrome. Noticed it have the problem with IV 100  pokemons.

**Comment by Silph-Road** [comment]
Why are you still using the bot?
