### ISSUE TITLE
RPM needed and tips

### ISSUE THREAD

**Issue by InTiime** [Necrobot-Private/NecroBot#1810]
If i used Necrobot every day, all day long, how many accounts could I use with key of 150 RPM?
How could I decrease RPM? Is it possible to keep in contact with a pokemon, without capture it, for decrease the RPM needed?
Thank you to every body

**Comment by TheWizard1328** [comment]
RPM’s is the Requests Per Minute that the bot makes to the hash server.
Every request it makes counts to this RPM.
Are you running multiple bots simultaneously or multiple accounts in one bot?
  -Running multiple Bots with single accounts will increase your RPM’s
  -But running one bot with multiple account’s as I do means that only one account is affecting your RPM’s.
And it is Per Minute  RPM’s, meaning every minute you get another 150RPM’s

Wizard Worxx
Where the magic of software begins.
Robert Tauber
(780) 236-1542
www.Facebook.com/WizardWorxx13

**Comment by InTiime** [comment]
Is possible to run multiple accounts with one bot?
Necrobot allows to keep in touch with a pokemon, without trying to capture it? Or is possibile to keep in touch just with a range of pokemon? E.g Dragonite, Chansey, Blissey, ecc

**Comment by TheWizard1328** [comment]
Do you use discord. If so can you message of there.
TheWizard1328



Sent from my Samsung Galaxy smartphone.


-------- Original message --------

**Comment by InTiime** [comment]
What's your name on discord?

**Comment by TheWizard1328** [comment]
TheWizard1328


Wizard Worxx
Where the magic of software begins.
Robert Tauber
(780) 236-1542
www.Facebook.com/WizardWorxx13

**Comment by InTiime** [comment]
And what's the tag code?

**Comment by TheWizard1328** [comment]
Should be @TheWizard

Wizard Worxx
Where the magic of software begins.
Robert Tauber
(780) 236-1542
www.Facebook.com/WizardWorxx13

**Comment by Lord-Haji** [comment]
Don't make these sort of issues again, Thanks !
