### ISSUE TITLE
Shadow Ban

### ISSUE THREAD

**Issue by amourification** [Necrobot-Private/NecroBot#1813]
I have disabled sniping and local sniping and always keep my configs at the least exp/h and p/h rates to avoid bans. My main account got shadow banned a couple of weeks ago and last week I created a test account with the same configs and today it got shadow banned as well!

I have no idea is it API related issue or bot config issue but this is really annoying.

**Comment by Lord-Haji** [comment]
This isn't our issue its coz Niantic who increased their level of security
