### ISSUE TITLE
login not possible

### ISSUE THREAD

**Issue by Timon1986** [Necrobot-Private/NecroBot#1816]
since 13.06.2017 if i want to login in necrobot with my Ptc account, i get the message: Unexpected response from Pokemon SSO OAuth Login Url: Status code NotFound

The Account isn't banned, i can login with my mobile phone.

btw. with a google account i can login with necrobot. Only with a Ptc account doesn't work

**Comment by Timon1986** [comment]
Ah okay, with a new ip-adress from my internetprovider the bot works again fine ... i don't know ..

**Comment by Timon1986** [comment]
Ah okay, with a new ip-adress from my internetprovider the bot works again fine ... i don't know ..

**Comment by Furtif** [comment]
Not bug of ip the big is fixed wait the new release or visite discord for more info

**Comment by Timon1986** [comment]
ah great okay .. i've the actually release 1.0.0.178 now .. all works fine ... Thank you
