### ISSUE TITLE
1.0.0.134 CLI is a Trojan. 

### ISSUE THREAD

**Issue by yagd** [Necrobot-Private/NecroBot#1817]
Hello all. 

I've tried downloading the CLI for 1.0.0.134 through necrobot2.com but it gets flagged by both google chrome and microsoft edge as a dangerous file. I downloaded it anyway and ran it through bitdefender which confirmed that the CLI is a trojan. Neither the 1.0.0.134 windows GUI nor the 1.0.0.133 CLI is corrupted, which suggests this issue seems to relate specifically to the 1.0.0.134 CLI. Is there an alternative link to download the 1.0.0.134 CLI? 

Thank you

**Comment by Furtif** [comment]
?!?! V1.0.0.177 is out 134 do not works... 

I do not see the interest of downloading an outdated version.

**Comment by Lord-Haji** [comment]
Its false positive thats why we we disabled 32 bit rekease 
Anyways tge version you are using is not supported on 0.63.4 api so stop complaining these type of wrong stuff and download the latest version from GitHub releases Page
Thanks
