### ISSUE TITLE
New error after update

### ISSUE THREAD

**Issue by cmg666** [Necrobot-Private/NecroBot#1821]
Sorry not exactly sure what I'm looking for.  Bot was working fine yesterday, updated it and I can't log in using my assigned API.  This is the error I'm getting

[12:35:50] () config.json [Line: 3, Position: 33]: ConsoleConfig.TranslationLanguageCode String '' does not match regex pattern '^[a-zA-Z]{2}(-[a-zA-Z]{2})*$'.

I just started using the bot yesterday and ran it for about 5 hours.  Not sure if I potentially got banned or something.

**Comment by TheWizard1328** [comment]
That config line is your language preference. Default is:
    "TranslationLanguageCode": "en",
Change to this then select your language in settings in bot.

Wizard Worxx
Where the magic of software begins.
Robert Tauber
(780) 236-1542
www.Facebook.com/WizardWorxx13

**Comment by cmg666** [comment]
ty fixxed lol man i feel silly, ez
