### ISSUE TITLE
Nothing Works!

### ISSUE THREAD

**Issue by omomnom** [Necrobot-Private/NecroBot#1824]
Help! None of the downloads work! Necro wont work! I used to use pokesniper and poke auto and they dont work! but mainly I am trying to gat necro functioning but i cant seem to do it! The necro 2 win says that the bot will launch in 15 seconds then never does it! please help. When I say downloads, I mean programs, sorry!

**Comment by Furtif** [comment]
https://github.com/Necrobot-Private/NecroBot/issues/1825
