### ISSUE TITLE
Exception caught, writing LogBuffer

### ISSUE THREAD

**Issue by Chorry119** [Necrobot-Private/NecroBot#1825]
I can not use it as an exception error after upgrading to NecroBot2 v1.0.0.178. I attached the log file below.

[14:45:49] () Configuration is up-to-date. Schema version: 27
[14:45:49] () Validating config.json...
[14:45:49] () Auth Configuration is up-to-date. Schema version: 27
[14:45:49] () Validating Auth.json...
[14:45:49] () Console Layout is now 'Default'
[14:45:52] () Key: 6R7TXXXXXXXXXXXX7E9Q RPM: 150 Expiration Date: 7/5/2017 (18 Days 9 Hours 42 Minutes)
[14:45:53] (INFO) Account changed to .
[14:45:53] (INFO) userid (Level: ??) | Runtime: 00:00:00
[14:45:53] (BOTSTATS) User: userid | XP:  | SD: 
[14:45:53] (INFO) Exception caught, writing LogBuffer.

**Comment by Jean-Daniel** [comment]
Same here. KeyNotFound exception and crash at startup.

**Comment by Jean-Daniel** [comment]
The ConsoleColors dictionary does not contains entry for LogLevel.BotStats so trying to log using that level crash the app.

**Comment by Furtif** [comment]
Fixes bug v1.0.0.178 Exception caught, writing LogBuffer

missing color dictionary console

https://github.com/Necrobot-Private/NecroBot/commit/d5e4e7ec29d44b78e5a598eb1ba2d24d76cb1153

For uses GUI dowload artifact  into:
https://ci.appveyor.com/project/jjskuld/necrobot/build/0.0.0.1797-fqjldwjv/artifacts
or wait new release.

**Comment by frkwhiteangel** [comment]
@Furtif when launching its auto updating to newest version and crashes again.

**Comment by Furtif** [comment]
change you app exe for https://ci.appveyor.com/project/jjskuld/necrobot/build/0.0.0.1797-fqjldwjv/artifacts
to fix it

**Comment by frkwhiteangel** [comment]
I did that. still forces me to update :/

2017-06-16 11:46 GMT+02:00 --=FurtiF™=-- <notifications@github.com>:

**Comment by Furtif** [comment]
if you uses v1.0.0.178 pr fixes is not present download Any CPU\Release\NecroBot2.WIN.0.0.0.1797-fqjldwjv.zip
Zip archive 88 MB NecroBot2.WIN.0.0.0.1797-fqjldwjv and dezip it remplace you files for new

**Comment by frkwhiteangel** [comment]
When launching after insertingt info:
Updating to v1.0.0.178 downloading from ....
http://i63.tinypic.com/2v3hkhx.png

**Comment by Furtif** [comment]
OKKK
pff normal this look:
![sans titre](https://user-images.githubusercontent.com/11375035/27222831-27c94d02-528e-11e7-931c-71abcb318a7a.png)

Click cancel update this is fixed affter release xx.179

**Comment by Furtif** [comment]
in reality version in appveyor is v1.0.0.178 cannot by updated all artifacts here updated 

All zip of appveyor are updated depending on the pr question, in this case pr to fix the bug of the launching error, this will take place until leaving the version v1.0.0.179 but it is everything
