### ISSUE TITLE
"Try later" Bot works every other day

### ISSUE THREAD

**Issue by Azuma57** [Necrobot-Private/NecroBot#1831]
Hello,
I did not find the answer to my problem so I created this new topic.
I started to bot yesterday, it worked perfectly.
But today since this morning the bot no longer works.

I do not get spin pokestops, the following message appears "try later".

He continued to grab pokemon until I no longer have pokeball (because i can not spin pokestop)

The bot can no longer catch pokemon or spin pokestops. I waited more than 12 hours but it still does not work.

I read that there was a limit of pokestop per day. My problem would come from there?

If so how long to wait? When is the counter reset? Is there a way to avoid this ... because, because of this the bot only works every other day.

Thank you, I am French and I have a little trouble with English can you use simple words to answer me, cordially.

**Comment by Azuma57** [comment]
I  am not banned, I can catch pokemon but i can't spin pokestop. So if i can't spin pokestops i no longer have pokemon and i can't catch pokemon *

**Comment by TheWizard1328** [comment]
Try these line in config,

  "PokeStopConfig": {
    "UsePokeStopLimit": true,
    "PokeStopLimit": 700,
    "PokeStopLimitMinutes": 1440

Change UsePokeStopLimit to false if you don’t want a limit, otherwise set PokeStopLimit to higher ### and PokeStopLimitMinutes is stops per minute. 1440=24 hours.

These settings are same for catching pokemon...

    "UseCatchLimit": true,
    "CatchPokemonLimit": 500,
    "CatchPokemonLimitMinutes": 1440,

Wizard Worxx
Where the magic of software begins.
Robert Tauber
(780) 236-1542
www.Facebook.com/WizardWorxx13

**Comment by Azuma57** [comment]
I already use this type of configuration:
  "PokeStopConfig": {
    "UsePokeStopLimit": false,
    "PokeStopLimit": 1500,
    "PokeStopLimitMinutes": 1350
  }
But the bot can not spin pokestops
Even on my phone on the real application I can catch pokemons but I can not spin pokestops (he said "Try later")

I spined 2500 pokestop in 24Hours
Maybe there is a limit and i must wait tomorrow?

**Comment by TheWizard1328** [comment]
Are you moving too fast while spinning stops. There I. A speed limit for spinning stops



Sent from my Samsung Galaxy smartphone.


-------- Original message --------

**Comment by Azuma57** [comment]
No my bot are config to 10.00 K/h
And when i spin on the phone i am not moving at all

**Comment by TheWizard1328** [comment]
Very strange. It sounds like some kind of soft ban.
Usually you can just sit and spin a stop up to 60 times till unbanned.



Sent from my Samsung Galaxy smartphone.


-------- Original message --------

**Comment by andeomontenegro** [comment]
Have same error. Fixed with right date&time settings.
