### ISSUE TITLE
NecroBot2 dosen't work

### ISSUE THREAD

**Issue by TheVector89** [Necrobot-Private/NecroBot#1832]
Console says: You bot will start after 15 seconds, You are running bot with Legacy API (0.45), but it will increase your risk of being banned and triggering captchas. Config Captchas in config.json to auto-resolve them.     BUT HE DOSEN'T START!

i enclose my config.jseon and auth.jsom
AUTH.JSON : [auth.json.txt](https://github.com/Necrobot-Private/NecroBot/files/1084266/auth.json.txt)

CONFIG.JSON : [config.json.txt](https://github.com/Necrobot-Private/NecroBot/files/1084267/config.json.txt)

**Comment by TheWizard1328** [comment]
The files you sent don’t help. They are the ‘schema’ files.
It’s the other2 json files with bot code that are needed.

Wizard Worxx
Where the magic of software begins.
Robert Tauber
(780) 236-1542
www.Facebook.com/WizardWorxx13

**Comment by TheVector89** [comment]
Oops, sorry. 
i've corrected the mistake.

**Comment by Lord-Haji** [comment]
please close issues if they are resolved
