### ISSUE TITLE
API Needed

### ISSUE THREAD

**Issue by halopeter** [Necrobot-Private/NecroBot#1834]
When I start it up, it asks for an API, and it says that i have to buy it, some kind of RPM thing.
But on the webpage, it said that its Completely free... Maybe I am dumb or something. please help

**Comment by TheWizard1328** [comment]
The Bot is free yes, but you need a hashkey to access the hash servers.
They aren’t that much. Like $10 a month

Wizard Worxx
Where the magic of software begins.
Robert Tauber
(780) 236-1542
www.Facebook.com/WizardWorxx13

**Comment by Lord-Haji** [comment]
discord for theme
