### ISSUE TITLE
We have detected a new API change

### ISSUE THREAD

**Issue by Azuma57** [Necrobot-Private/NecroBot#1837]
I can't bot! This message appear when i try " We have detected a Pokemon API change. The bot emulates API version 0.63.4 wich is no longer supported."
I suppose is just a update of pokemon go and we must wait for the new version of necrobot ?

**Comment by Bellybonez** [comment]
Also received this error, any one know how long it takes to fix? thanks

**Comment by Misc4HD** [comment]
Same problem

**Comment by giboulz** [comment]
same here. 

Is it the hash ? or the bot ?

**Comment by JackDeRipper494** [comment]
Im having the same problem.

**Comment by Shoumil** [comment]
Same, however, I did see this https://github.com/Necrobot-Private/PokemonGo.RocketAPI/pull/136/commits/29c2d19f344474413835064fe1d604fdc27bb0e5

**Comment by Furtif** [comment]
fixes in https://github.com/Necrobot-Private/NecroBot/pull/1833 wait

**Comment by cjhart** [comment]
Any ETA on a release?

**Comment by Darksoul95** [comment]
Same Problem here. Waiting for merge.

Thank you guys.

**Comment by Darksoul95** [comment]
Works again! Thank you guys very much!
