### ISSUE TITLE
Pokemon Go after Update 0.67.1

### ISSUE THREAD

**Issue by Buckrogers81** [Necrobot-Private/NecroBot#1838]
Greetings,
I was forced to install the Update yesterday.  After logging on, I got the Message, that I am Using 3rd. Party Software blablabla, We recomand to Stop using them! So far so good. 
Also I now have some Pokemon scratched out in my inventory. These are some minor Pokemon that I catched in April. Non of the Later Pokemon I was catching this month are "Banned". So the Damage is not Bad. 
Is it Save to use the Bot right now?

**Comment by Furtif** [comment]
fixes in https://github.com/Necrobot-Private/NecroBot/pull/1833
read https://github.com/Necrobot-Private/NecroBot/issues/1837
