### ISSUE TITLE
0.9.9.6 Keep on walking to a pokeshop but it never reach it

### ISSUE THREAD

**Issue by vfuyong** [Necrobot-Private/NecroBot#184]
The log keep on displaying "walking to pokeshop (50m)", but it never reach it, and no loot is acquired.

**Comment by Aras84** [comment]
Same here @vfuyong ....reverted to 0.9.9.3 which worked great

**Comment by FaruqX** [comment]
me too,

**Comment by ValorRed** [comment]
Same here

**Comment by jjskuld** [comment]
I'm seeing this too.. let me check what changed.
