### ISSUE TITLE
Error after Update

### ISSUE THREAD

**Issue by 0quss4n** [Necrobot-Private/NecroBot#1840]
System.Exception: Unexpected inventory error. Could not generate hash code.
   konum: PokemonGo.RocketAPI.Rpc.Inventory.GetInventoryItemHashKey(InventoryItem item)
   konum: PokemonGo.RocketAPI.Rpc.Inventory.AddRemoveOrUpdateItem(InventoryItem item)
   konum: PokemonGo.RocketAPI.Rpc.Inventory.MergeWith(GetInventoryResponse update)
   konum: PokemonGo.RocketAPI.Helpers.CommonRequest.ProcessGetInventoryResponse(Client client, GetInventoryResponse getInventoryResponse)
   konum: PokemonGo.RocketAPI.Rpc.Download.<GetRemoteConfigVersion>d__6.MoveNext()
--- Özel durumun oluşturulduğu önceki konumdan başlayan yığın izlemesinin sonu ---
   konum: System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   konum: System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   konum: PokemonGo.RocketAPI.Rpc.Login.<DoLogin>d__10.MoveNext()
--- Özel durumun oluşturulduğu önceki konumdan başlayan yığın izlemesinin sonu ---
   konum: System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   konum: System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   konum: System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   konum: PoGo.NecroBot.Logic.State.LoginState.<Execute>d__3.MoveNext()

**Comment by Chorry119** [comment]
same here also. I think this is due to the new tool in the inventory, the Raid Pass.

**Comment by 0quss4n** [comment]
Yeah i tought so. I wasted my skill changer item and stil got same problem. But no problem in my 30 level accounts

**Comment by Lazybull** [comment]
same here when login with google accts but PTC accts work just fine.

**Comment by Darksoul95** [comment]
Same problem here.

**Comment by masrudyn** [comment]
I think the issue is when the inventory has new items that includes raid pass and the new items that comes with a successful raid.

**Comment by Furtif** [comment]
gyms not working

**Comment by 6Vampire6** [comment]
Same here for all accounts that fought gyms on a device and got a raid pass.
Unfortunately, now these accounts can't load their items using the bot any more...
Please set prio for fixing to 1.

**Comment by Scorpionarius** [comment]
Same problem, nothing to wrong with the config file. Its about the new items ingame...

**Comment by 0quss4n** [comment]
i wasted my new items to use bot again bot its still not working. The problem could be our scratched pokemons i guess.

**Comment by Furtif** [comment]
fixes https://github.com/Necrobot-Private/NecroBot/pull/1842

**Comment by 0quss4n** [comment]
i couldnt understand that fix. any files to download? or upgrade? Help me please

**Comment by Darksoul95** [comment]
could anybody please deploy the new build as a ready zip for download here on github?

Thanks

**Comment by Darksoul95** [comment]
Wait for upload of the updated version or go to https://ci.appveyor.com/project/jjskuld/necrobot/build/0.0.0.1806-bufbaani/artifacts download the zip and start but skip the update.
