### ISSUE TITLE
One or more errors occured!!

### ISSUE THREAD

**Issue by ZnAladin** [Necrobot-Private/NecroBot#1844]
I download the the files and when i try to launch the app he stops and pop me up "one or more errors occured"what should i do?

**Comment by ZnAladin** [comment]
![default](https://user-images.githubusercontent.com/29681310/27511918-3fe339a8-5931-11e7-9c77-9ff0f7567d52.png)

**Comment by Furtif** [comment]
fixes https://github.com/Necrobot-Private/NecroBot/pull/1842

**Comment by ZnAladin** [comment]
i am not very good with these things and didnt understand what should i
do.thanks anyway!

2017-06-26 2:33 GMT+02:00 Haji Sama <notifications@github.com>:
