### ISSUE TITLE
Necrobot has stopped working

### ISSUE THREAD

**Issue by SimonLyfe** [Necrobot-Private/NecroBot#1852]
Expected Behavior:

Application opens

Actual Behavior:

Application crashes

Your config.json:

Created

![jjcapture](https://user-images.githubusercontent.com/29714495/27555241-00c5234a-5a66-11e7-9498-3a6cce53bd31.png)

This happend when i installed and opened the NecroBot2 v1.0.0.180 (I have already put in key code in config.json)

**Comment by Darksoul95** [comment]
Plz post your config and auth.json

**Comment by SimonLyfe** [comment]
{
  "Bots": [],
  "ProxyConfig": {
    "UseProxy": false,
    "UseProxyHost": null,
    "UseProxyPort": null,
    "UseProxyAuthentication": false,
    "UseProxyUsername": null,
    "UseProxyPassword": null
  },
  "DeviceConfig": {
    "DevicePlatform": "ios",
    "DevicePackageName": "custom",
    "DeviceId": "a90d42078803ab6bb2e6ee9781b8dc3c38475774",
    "AndroidBoardName": null,
    "AndroidBootloader": null,
    "DeviceBrand": "Apple",
    "DeviceModel": "iPad",
    "DeviceModelIdentifier": null,
    "DeviceModelBoot": "iPad3,3",
    "HardwareManufacturer": "Apple",
    "HardwareModel": "J2AAP",
    "FirmwareBrand": "iPhone OS",
    "FirmwareTags": null,
    "FirmwareType": "8.1.2",
    "FirmwareFingerprint": null,
    "UseRandomDeviceId": false
  },
  "APIConfig": {
    "UsePogoDevAPI": true,
    "AuthAPIKey": "",
    "UseLegacyAPI": false,
    "DiplayHashServerLog": true
  }
}





![captdure](https://user-images.githubusercontent.com/29714495/27583767-589f836a-5aea-11e7-89aa-37809c0b5cff.PNG)

**Comment by Darksoul95** [comment]
The first part of your auth.json should look like this (without *...*):

`  "Bots": [
    {
      "AuthType": "*type in if it's a google or ptc account*",
      "Username": "*type in your username*",
      "Password": "*type in your password*",
      "AutoExitBotIfAccountFlagged": true
    },
    {
      "AuthType": "*account2*",
      "Username": "*accountname 2*",
      "Password": "*password 2*",
      "AutoExitBotIfAccountFlagged": true
    }
  ],`

*rest of your auth.json*


and you need to enter your AuthAPIKey under APIConfig.

maybe you also need a DeviceID but idk.

**Comment by SimonLyfe** [comment]
I got it to work bot thanks for your answer :)

**Comment by Lord-Haji** [comment]
Close issues after they are resolved
