### ISSUE TITLE
System.Exception: Unexpected inventory error. Could not generate hash code.

### ISSUE THREAD

**Issue by ChrisFBones** [Necrobot-Private/NecroBot#1854]
## Stop! Before you create this issue (you can delete this section when opening the issue):
1. Have you searched to see if there are other Open/Closed issues for the same issue? If so, comment on that issue instead.
2. Have you validated that your config/auth.json and config/config.json is valid JSON? Use http://jsonlint.com/ to check.
3. If your question is referring to how to set up or use the bot, please join our discord instead of posting an issue: https://discord.gg/7FWyWVp 
4. Always confirm that your issue is reproducible, with the config you provide below.

### Expected Behavior:
The bot starts normally.

### Actual Behavior:
I recently increased my inventory and thus when it goes to log in into my account, the bot keeps saying System.Exception: Unexpected inventory error. Could not generate hash code.

![untitled](https://user-images.githubusercontent.com/29726166/27577280-5b89154c-5b20-11e7-9d33-90409139dd40.png)
![untitled](https://user-images.githubusercontent.com/29726166/27577292-6b4fd9c0-5b20-11e7-824f-6f611974cf8a.png)

### Your config.json:
```
replace this text with the contents of your config.json

```

### (OPTIONAL) Your Log:
```
replace this text with only the "relative" portion of your log. (Remove unnessary lines)

```

### Other Information
(Attach zip files if needed.)

Version: 1.0.0.180
Windows Version: 10
What is affected (catch, transfer, favorite, GPX, evolve, recycle, snipe, human walk snipe, pokestops, powerup/levelup, other): whole bot

**Comment by cjhart** [comment]
I am getting this too.

**Comment by Darksoul95** [comment]
Looks like the same error we had after getting the first Raid-Passes...

Try to download one of these: https://ci.appveyor.com/project/jjskuld/necrobot/build/0.0.0.1806-bufbaani/artifacts
and disable Updates-checking.

**Comment by Furtif** [comment]
fixed in 181 https://github.com/Necrobot-Private/NecroBot/releases/tag/v1.0.0.181
