### ISSUE TITLE
Bot  not transfering pokemon (immediately) 

### ISSUE THREAD

**Issue by NeoNecris** [Necrobot-Private/NecroBot#1860]
Bot is not transfering pokemon at all... have like 30 pidgey and 40 sentret. What is setup wrong?

"PokemonConfig": {
    "CatchPokemon": true,
    "DelayBetweenPokemonCatch": 1990,
    "UseCatchLimit": true,
    "CatchPokemonLimit": 29,
    "CatchPokemonLimitMinutes": 32,
    "UseIncenseConstantly": false,
    "UseEggIncubators": true,
    "UseLimitedEggIncubators": true,
    "UseLuckyEggConstantly": false,
    "UseLuckyEggsMinPokemonAmount": 30,
    "UseLuckyEggsWhileEvolving": false,
    "TransferWeakPokemon": false,
    **"TransferDuplicatePokemon": true,**
    **"TransferDuplicatePokemonOnCapture": true,**
    "RenamePokemon": false,
    "RenameOnlyAboveIv": false,
    "RenameTemplate": "{Name}_{IV}_Lv{Level}",
    "FavoriteMinIvPercentage": 95.0,
    "AutoFavoritePokemon": false,
    "AutoFavoriteShinyOnCatch": false,
    "MaxPokeballsPerPokemon": 6,
    "UseGreatBallAboveCp": 1000,
    "UseUltraBallAboveCp": 1250,
    "UseMasterBallAboveCp": 1500,
    "UseGreatBallAboveIv": 85.0,
    "UseUltraBallAboveIv": 95.0,
    "UseGreatBallBelowCatchProbability": 0.2,
    "UseUltraBallBelowCatchProbability": 0.1,
    "UseMasterBallBelowCatchProbability": 0.05,
    "AutomaticallyLevelUpPokemon": false,
    "OnlyUpgradeFavorites": true,
    "UseLevelUpList": true,
    "AmountOfTimesToUpgradeLoop": 5,
    "GetMinStarDustForLevelUp": 5000,
    "LevelUpByCPorIv": "iv",
    "UpgradePokemonCpMinimum": 1000.0,
    "UpgradePokemonIvMinimum": 95.0,
    "UpgradePokemonMinimumStatsOperator": "and",
    "EvolveAboveIvValue": 95.0,
    "EvolveAllPokemonAboveIv": false,
    "EvolveAllPokemonWithEnoughCandy": true,
    "EvolveKeptPokemonsAtStorageUsagePercentage": 90.0,
    "EvolveKeptPokemonIfBagHasOverThisManyPokemon": 120,
    "KeepPokemonsThatCanEvolve": false,
    "KeepMinCp": 1250,
    "KeepMinIvPercentage": 90.0,
    "KeepMinLvl": 6,
    "KeepMinOperator": "or",
    "UseKeepMinLvl": false,
    "PrioritizeIvOverCp": true,
    "KeepMinDuplicatePokemon": 2,
    "KeepMaxDuplicatePokemon": 990,
    "UsePokemonToNotCatchFilter": true,
    "UsePokemonToCatchLocallyListOnly": false,
    "DumpPokemonStats": false,
    "DelayBetweenPokemonUpgrade": 10000,
    "OutOfBallCatchBlockTime": 5,
    "PokeballToKeepForSnipe": 50,
    "UseBulkTransferPokemon": true,
    "BulkTransferStogareBuffer": 10,
    "BulkTransferSize": 100,
    "UseBallOperator": "or",
    "FavoriteMinCp": 0.0,
    "DefaultBuddyPokemon": "",
    "FavoriteMinLevel": 0,
    "FavoriteOperator": "and",
    "RenamePokemonRespectTransferRule": false,
    "UpgradePokemonLvlMinimum": 30.0,
    "EvolveFavoritedOnly": true,
    "EvolveOperator": "and",
    "EvolveMinIV": 100.0,
    "EvolveMinCP": 2000.0,
    "EvolveMinLevel": 25.0,
    "ByPassCatchFlee": false
  },

**Comment by hardknoxni69a** [comment]
your settings have it to only evolve once it reaches a certain limit the config is your friend please readjust for the desired results
