### ISSUE TITLE
Run Times with Variations **ENHANCEMENT

### ISSUE THREAD

**Issue by boosie212** [Necrobot-Private/NecroBot#1863]
Necrobot should add a Run Time option in the config.json file that allows users to determine how long the bot runs (ex. Running 2-3 hours, Not Running 1-2 hours).  This will help to avoid the softbans for running the bot for too long of a period, especially for people who don't have access to shut or open their bot for long periods of time.  There should also be a variation time so its not the same amount of time running/not running each time.

**Comment by hardknoxni69a** [comment]
check your config file as there is runtime and pause limits and it is randomized as well
