### ISSUE TITLE
I need help (its not an issue)

### ISSUE THREAD

**Issue by 0quss4n** [Necrobot-Private/NecroBot#1868]
I am sorry for this topic but i need really help. My account is 39,5 level. My hash api key is gonna end 19 hours later. I need 4-5 days more. How can i find 4-5 days more? I already bought 2 months, i dont wanna buy 1 months more.
![adsiz](https://user-images.githubusercontent.com/29662989/27711773-dd8abf74-5d2c-11e7-8b61-cbc16472f260.jpg)

**Comment by 0quss4n** [comment]
oguzhan.esen@yahoo.com

**Comment by informer0827** [comment]
you're wasting resources due to you don't wanna pay.....

**Comment by NeoNecris** [comment]
lvl 39 with botting? damn... please share your config file :D I always get flagged :s

**Comment by hardknoxni69a** [comment]
please join our discord for basic chat options
