### ISSUE TITLE
error when start battle.

### ISSUE THREAD

**Issue by zspam1** [Necrobot-Private/NecroBot#1869]
After the 0.67.1 when calling the StartGymBattle, I got APIBadRequestException.
Maybe bossland has not process the message right?

Also I don't think current Fort.GetGymDetails can convert to GetGymDetailsResponse correctly. GymStatus has become GymStatusAndDefenders already. Is it just to make the code compile-able?

Also can any one make the call to ListGymBadges yet?

**Comment by Lord-Haji** [comment]
Gyms are down
