### ISSUE TITLE
Unexpected Response from Pokemon SSO 0auth login url: status code conflict

### ISSUE THREAD

**Issue by daveo3** [Necrobot-Private/NecroBot#1870]
Hello,

For some reason I keep getting this error. My Auth.json is completely fine and has no issues. Is this possibly just a server issue?

http://imgur.com/a/qOrFQ

**Comment by zspam1** [comment]
Is that because your ip is on the blacklist?

**Comment by daveo3** [comment]
Yeah the accounts were banned :/

**Comment by zspam1** [comment]
Not accounts get banned. maybe just the ip is banned.. try another ip.

**Comment by daveo3** [comment]
I tried using a VPN and its the same thing. My accounts are not banned but I can't use it on my wifi. Do I need a different API Key? My VPN did not work :(

**Comment by Lord-Haji** [comment]
hash server unstable
