### ISSUE TITLE
Bot not transferring.  I have changed the config with no luck

### ISSUE THREAD

**Issue by Beachbear1** [Necrobot-Private/NecroBot#1871]
My bot won't transfer not matter what I do. Here is part of the config. I have changed the config with no luck.

{
  "ConsoleConfig": {
    "TranslationLanguageCode": "en",
    "StartupWelcomeDelay": false,
    "AmountOfPokemonToDisplayOnStart": 2,
    "DetailedCountsBeforeRecycling": true
  },
  "UpdateConfig": {
    "SchemaVersion": 27,
    "CheckForUpdates": true,
    "AutoUpdate": true
  },
  "WebsocketsConfig": {
    "UseWebsocket": true,
    "WebSocketPort": 14251
  },
  "LocationConfig": {
    "DisableHumanWalking": false,
    "StartFromLastPosition": false,
    "DefaultLatitude": 40.7551944,
    "DefaultLongitude": -73.9837222,
    "WalkingSpeedInKilometerPerHour": 5.0,
    "UseWalkingSpeedVariant": true,
    "WalkingSpeedVariant": 5.0,
    "ShowVariantWalking": false,
    "RandomlyPauseAtStops": true,
    "MaxSpawnLocationOffset": 10,
    "MaxTravelDistanceInMeters": 1000
  },
  "TelegramConfig": {
    "UseTelegramAPI": false,
    "TelegramAPIKey": null,
    "TelegramPassword": null
  },
  "GPXConfig": {
    "UseGpxPathing": false,
    "GpxFile": "GPXPath.GPX"
  },
  "SnipeConfig": {
    "UseSnipeLocationServer": false,
    "SnipeLocationServer": "localhost",
    "SnipeLocationServerPort": 16969,
    "MinPokeballsToSnipe": 20,
    "MinPokeballsWhileSnipe": 0,
    "MinDelayBetweenSnipes": 60000,
    "SnipingScanOffset": 0.005,
    "SnipeAtPokestops": false,
    "SnipeIgnoreUnknownIv": false,
    "UseTransferIvForSnipe": false,
    "SnipePokemonNotInPokedex": false,
    "UseSnipeLimit": true,
    "SnipeRestSeconds": 600,
    "SnipeCountLimit": 39,
    "ActivateMSniper": true,
    "MinIVForAutoSnipe": 100,
    "MinLevelForAutoSnipe": 0,
    "AutosnipeVerifiedOnly": false,
    "DefaultAutoSnipeCandy": 0,
    "SnipePauseOnOutOfBallTime": 5,
    "AutoSnipeMaxDistance": 0.0,
    "AutoSnipeBatchSize": 10
  },
  "HumanWalkSnipeConfig": {
    "Enable": true,
    "DisplayPokemonList": true,
    "MaxDistance": 1500.0,
    "MaxEstimateTime": 900.0,
    "CatchEmAllMinBalls": 50,
    "TryCatchEmAll": true,
    "CatchPokemonWhileWalking": true,
    "SpinWhileWalking": true,
    "AlwaysWalkback": false,
    "SnipingScanOffset": 0.025,
    "WalkbackDistanceLimit": 300.0,
    "IncludeDefaultLocation": true,
    "UseSnipePokemonList": true,
    "MaxSpeedUpSpeed": 60.0,
    "AllowSpeedUp": true,
    "DelayTimeAtDestination": 10000,
    "UsePokeRadar": false,
    "UseSkiplagged": false,
    "UsePokecrew": false,
    "UsePokesnipers": false,
    "UsePokeZZ": false,
    "UsePokeWatcher": false,
    "UseFastPokemap": false,
    "UsePogoLocationFeeder": false,
    "AllowTransferWhileWalking": false
  },
  "DataSharingConfig": {
    "EnableSyncData": true,
    "AutoSnipe": false,
    "DataServiceIdentification": "",
    "SnipeDataAccessKey": "",
    "EnableFailoverDataServers": true,
    "FailoverDataServers": "ws://s1.mypogosnipers.com/socket.io/?EIO=3&transport=websocket;ws://s2.mypogosnipers.com/socket.io/?EIO=3&transport=websocket;ws://necrosocket.herokuapp.com/socket.io/?EIO=3&transport=websocket",
    "DataRecieverURL": "ws://www.mypogosnipers.com/socket.io/?EIO=3&transport=websocket"
  },
  "PokeStopConfig": {
    "UsePokeStopLimit": true,
    "PokeStopLimit": 700,
    "PokeStopLimitMinutes": 1350
  },
  "GymConfig": {
    "NotUsedSkills": [
      {
        "Key": "snorlax",
        "Value": "hyperBeam"
      },
      {
        "Key": "dragonite",
        "Value": "hyperBeam"
      },
      {
        "Key": "lapras",
        "Value": "blizzard"
      },
      {
        "Key": "cloyster",
        "Value": "blizzard"
      },
      {
        "Key": "flareon",
        "Value": "fireBlast"
      },
      {
        "Key": "gyarados",
        "Value": "hydroPump"
      },
      {
        "Key": "exeggutor",
        "Value": "solarBeam"
      }
    ],
    "Enable": false,
    "PrioritizeGymOverPokestop": true,
    "MaxDistance": 500.0,
    "DefaultTeam": "Yellow",
    "MaxCPToDeploy": 1800,
    "MaxLevelToDeploy": 16,
    "VisitTimeout": 60,
    "UseRandomPokemon": false,
    "NumberOfTopPokemonToBeExcluded": 10,
    "CollectCoinAfterDeployed": 1,
    "EnableAttackGym": false,
    "MaxGymLevelToAttack": 3,
    "MaxDefendersToAttack": 3,
    "HealDefendersBeforeApplyToGym": true,
    "DontAttackAfterCoinsLimitReached": true,
    "EnableGymTraining": true,
    "TrainGymWhenMissingMaxPoints": 1000,
    "MaxGymLvlToTrain": 4,
    "TrainAlreadyDefendedGym": true,
    "MinCpToUseInAttack": 1000,
    "ButNotLessThanDefenderPercent": 0.75,
    "UsePokemonToAttackOnlyByCp": true,
    "ExcludeForGyms": [
      "kangaskhan",
      "tauros",
      "mrMime",
      "farfetchd"
    ],
    "DontUseDodge": false,
    "MinRevivePotions": 5,
    "PrioritizeGymWithFreeSlot": true,
    "SaveMaxRevives": true,
    "MaxTrainingRoundsOnOneGym": 5,
    "Defenders": [
      {
        "Pokemon": "lapras",
        "MinCP": 1000,
        "MaxCP": null,
        "Priority": 5,
        "Moves": null
      },
      {
        "Pokemon": "snorlax",
        "MinCP": 1000,
        "MaxCP": 2400,
        "Priority": 5,
        "Moves": null
      },
      {
        "Pokemon": "vaporeon",
        "MinCP": 2000,
        "MaxCP": null,
        "Priority": 5,
        "Moves": [
          [
            "moveUnset",
            "hydroPump"
          ]
        ]
      },
      {
        "Pokemon": "dragonite",
        "MinCP": 2000,
        "MaxCP": 2499,
        "Priority": 5,
        "Moves": null
      }
    ],
    "Attackers": [
      {
        "Pokemon": "dragonite",
        "MinCP": 2500,
        "MaxCP": null,
        "Priority": 5,
        "Moves": null
      },
      {
        "Pokemon": "vaporeon",
        "MinCP": 2000,
        "MaxCP": null,
        "Priority": 5,
        "Moves": null
      },
      {
        "Pokemon": "gyarados",
        "MinCP": 2000,
        "MaxCP": null,
        "Priority": 5,
        "Moves": null
      },
      {
        "Pokemon": "snorlax",
        "MinCP": 2401,
        "MaxCP": null,
        "Priority": 5,
        "Moves": null
      }
    ],
    "Trainers": [
      {
        "Pokemon": "dragonite",
        "MinCP": null,
        "MaxCP": 2000,
        "Priority": 100,
        "Moves": null
      },
      {
        "Pokemon": "vaporeon",
        "MinCP": null,
        "MaxCP": 2000,
        "Priority": 25,
        "Moves": null
      },
      {
        "Pokemon": "gyarados",
        "MinCP": null,
        "MaxCP": 2000,
        "Priority": 50,
        "Moves": null
      },
      {
        "Pokemon": "snorlax",
        "MinCP": null,
        "MaxCP": 2000,
        "Priority": 10,
        "Moves": null
      }
    ]
  },
  "PokemonConfig": {
    "CatchPokemon": true,
    "DelayBetweenPokemonCatch": 2000,
    "UseCatchLimit": true,
    "CatchPokemonLimit": 500,
    "CatchPokemonLimitMinutes": 1350,
    "UseIncenseConstantly": false,
    "UseEggIncubators": true,
    "UseLimitedEggIncubators": true,
    "UseLuckyEggConstantly": false,
    "UseLuckyEggsMinPokemonAmount": 30,
    "UseLuckyEggsWhileEvolving": false,
    "TransferWeakPokemon": false,
    "TransferDuplicatePokemon": true,
    "TransferDuplicatePokemonOnCapture": true,
    "RenamePokemon": false,
    "RenameOnlyAboveIv": false,
    "RenameTemplate": "{Name}_{IV}_Lv{Level}",
    "FavoriteMinIvPercentage": 95.0,
    "AutoFavoritePokemon": false,
    "AutoFavoriteShinyOnCatch": false,
    "MaxPokeballsPerPokemon": 6,
    "UseGreatBallAboveCp": 1000,
    "UseUltraBallAboveCp": 1250,
    "UseMasterBallAboveCp": 1500,
    "UseGreatBallAboveIv": 85.0,
    "UseUltraBallAboveIv": 95.0,
    "UseGreatBallBelowCatchProbability": 0.2,
    "UseUltraBallBelowCatchProbability": 0.1,
    "UseMasterBallBelowCatchProbability": 0.05,
    "AutomaticallyLevelUpPokemon": false,
    "OnlyUpgradeFavorites": true,
    "UseLevelUpList": true,
    "AmountOfTimesToUpgradeLoop": 5,
    "GetMinStarDustForLevelUp": 5000,
    "LevelUpByCPorIv": "iv",
    "UpgradePokemonCpMinimum": 1000.0,
    "UpgradePokemonIvMinimum": 95.0,
    "UpgradePokemonMinimumStatsOperator": "and",
    "EvolveAboveIvValue": 95.0,
    "EvolveAllPokemonAboveIv": false,
    "EvolveAllPokemonWithEnoughCandy": true,
    "EvolveKeptPokemonsAtStorageUsagePercentage": 90.0,
    "EvolveKeptPokemonIfBagHasOverThisManyPokemon": 120,
    "KeepPokemonsThatCanEvolve": false,
    "KeepMinCp": 1250,
    "KeepMinIvPercentage": 90.0,
    "KeepMinLvl": 6,
    "KeepMinOperator": "or",
    "UseKeepMinLvl": false,
    "PrioritizeIvOverCp": true,
    "KeepMinDuplicatePokemon": 1,
    "KeepMaxDuplicatePokemon": 1000,
    "UsePokemonToNotCatchFilter": true,
    "UsePokemonToCatchLocallyListOnly": false,
    "DumpPokemonStats": false,
    "DelayBetweenPokemonUpgrade": 10000,
    "OutOfBallCatchBlockTime": 5,
    "PokeballToKeepForSnipe": 50,
    "UseBulkTransferPokemon": true,
    "BulkTransferStogareBuffer": 10,
    "BulkTransferSize": 100,
    "UseBallOperator": "or",
    "FavoriteMinCp": 0.0,
    "DefaultBuddyPokemon": "",
    "FavoriteMinLevel": 0,
    "FavoriteOperator": "and",
    "RenamePokemonRespectTransferRule": false,
    "UpgradePokemonLvlMinimum": 30.0,
    "EvolveFavoritedOnly": true,
    "EvolveOperator": "and",
    "EvolveMinIV": 100.0,
    "EvolveMinCP": 2000.0,
    "EvolveMinLevel": 25.0,
    "ByPassCatchFlee": false
  },
  "RecycleConfig": {
    "VerboseRecycling": true,
    "RecycleInventoryAtUsagePercentage": 90.0,
    "RandomizeRecycle": false,
    "RandomRecycleValue": 3,
    "TotalAmountOfPokeballsToKeep": 120,
    "TotalAmountOfPotionsToKeep": 80,
    "TotalAmountOfRevivesToKeep": 60,
    "TotalAmountOfBerriesToKeep": 50,
    "UseRecyclePercentsInsteadOfTotals": false,
    "PercentOfInventoryPokeballsToKeep": 35,
    "PercentOfInventoryPotionsToKeep": 35,
    "PercentOfInventoryRevivesToKeep": 20,
    "PercentOfInventoryBerriesToKeep": 10
  },
  "CustomCatchConfig": {
    "EnableHumanizedThrows": true,
    "EnableMissedThrows": true,
    "ThrowMissPercentage": 25,
    "NiceThrowChance": 40,
    "GreatThrowChance": 30,
    "ExcellentThrowChance": 10,
    "CurveThrowChance": 90,
    "ForceGreatThrowOverIv": 90.0,
    "ForceExcellentThrowOverIv": 95.0,
    "ForceGreatThrowOverCp": 1000,
    "ForceExcellentThrowOverCp": 1500,
    "UseTransferFilterToCatch": true
  },
  "PlayerConfig": {
    "DelayBetweenPlayerActions": 4000,
    "EvolveActionDelay": 20000,
    "TransferActionDelay": 5000,
    "RecycleActionDelay": 1000,
    "RenamePokemonActionDelay": 2000,
    "UseNearActionRandom": true,
    "RandomizeSettingsByPercent": 5,
    "AutoFinishTutorial": false,
    "SkipFirstTimeTutorial": false,
    "SkipCollectingLevelUpRewards": false
  },
  "SoftBanConfig": {
    "FastSoftBanBypass": false,
    "ByPassSpinCount": 1
  },
  "GoogleWalkConfig": {
    "UseGoogleWalk": true,
    "DefaultStepLength": 1.3,
    "GoogleHeuristic": "walking",
    "GoogleAPIKey": "",
    "Cache": true,
    "GoogleElevationAPIKey": null
  },
  "YoursWalkConfig": {
    "UseYoursWalk": false,
    "YoursWalkHeuristic": "bicycle"
  },
  "MapzenWalkConfig": {
    "UseMapzenWalk": true,
    "MapzenTurnByTurnApiKey": "",
    "MapzenWalkHeuristic": "bicycle",
    "MapzenElevationApiKey": null
  },

**Comment by blackms** [comment]
If you have the following configuration:
`"UseBulkTransferPokemon": true,`
`"BulkTransferStogareBuffer": 10,`
`"BulkTransferSize": 100,`

The pokemon transfer will be performed only in when you have the following amount of Pokemons:

```c#
if ((maxStorage - totalEggs.Count() - buff) > totalPokemon.Count()) return;
```
This means 350 - 9 - 10 = 331. You must have more than 331 Pokemons in the inventory in order to start the transfer.

Not a bug.
