### ISSUE TITLE
REQUEST spin gym discs

### ISSUE THREAD

**Issue by ChrisFBones** [Necrobot-Private/NecroBot#1872]

**Comment by Furtif** [comment]
?

**Comment by darkhax** [comment]
I believe they're referring to the photo-disc that was added to every gym in the raid update. Like a pokestop, these give you a bunch of items.

**Comment by Furtif** [comment]
### Fixed into https://github.com/Necrobot-Private/NecroBot/pull/1887

**Comment by Lord-Haji** [comment]
Added
