### ISSUE TITLE
detected a Pokemon API change

### ISSUE THREAD

**Issue by JingkunLi** [Necrobot-Private/NecroBot#1880]
[21:35:04] (ERROR) (KILLSWITCH) We have detected a Pokemon API change. The bot emulates API version 0.67.1, which is no longer supported.  Minimum API version is now 0.67.2.
[21:35:04] (ERROR) The bot will now exit after hitting the enter key.

**Comment by Paasken** [comment]
Just ran into the same problem.

**Comment by Furtif** [comment]
fixed https://github.com/Necrobot-Private/PokemonGo.RocketAPI/pull/144

**Comment by PierrepaulPaquet** [comment]
Hi, I don't know if i should ask it here, but i also ran in the same trouble and i'm not really sure how to fix it. I don't know much about programming so i'm not really sure how i'm supposed to be changing the code.

**Comment by night1245** [comment]
so do we just wait for the bot to be updated or is there something we can manually do to get it to update and on a side not i noticed that bossland api put more days on the existing key we had to i guess make up for the issue the server was having so props to them.

**Comment by drenkromine** [comment]
soooo...no bots today?
damn

**Comment by leriko1024** [comment]
that's not fear with priv members. i both key 2 days ago and now i'm w8 for any updates bcos dev's can't do all in time.WTF? You re-write some mistakes on cfg's rocket api and here you can't do smth with bot? lol kek cheburek. if bot does not work today, you should give back money for api key or paid for lost days....

**Comment by Keexx** [comment]
@leriko1024 You know the product you're using is free right??? The API key isn't related to them. They buy them and give them out for free on the discord but don't bitch when you don't pay.

**Comment by leriko1024** [comment]
@Keexx hahahha seems you're an idiot? did you think that dev's not get money for that(i mean api keys) maybe just half of price but still money!!! if "yep" you 're such stupid boy and you should buy brains but not API keys kek. lol. cheburek. all companies even in "steam" works like that.
