### ISSUE TITLE
[Solved]Necrobot doesn't write logs

### ISSUE THREAD

**Issue by InTiime** [Necrobot-Private/NecroBot#1884]
Since the last update, Necrobot write into log files just 2 lines:
[11:51:15] () Configuration is up-to-date. Schema version: 27
[11:51:15] () Validating config.json...
Is this a bug?

**Comment by InTiime** [comment]
I downloaded again Necrobot and the problem was solved.
Sorry

**Comment by Lord-Haji** [comment]
Don't report worthless issues
