### ISSUE TITLE
Paid for key but no key received 

### ISSUE THREAD

**Issue by ahuby09** [Necrobot-Private/NecroBot#1885]
Hi i have paid for a key but i have not received anything through email except and confirmation. this doesn't have a key on it.

**Comment by hardknoxni69a** [comment]
the hask key services are provided through pogodev not necrobot we just use there service to connect please contact them

**Comment by andeomontenegro** [comment]
create accont here https://na.buddyauth.com/ with email of paypal account which u use for make payment.
there is all your keys!
