### ISSUE TITLE
Building solution got error "The name 'PokemonMoveMetaRegistry' does not exist in the current context".

### ISSUE THREAD

**Issue by Markleeapple** [Necrobot-Private/NecroBot#189]
### Expected Behavior:
Build solution to debug step by step.

### Actual Behavior:
got error.

### Your config.json:
```
none
```

### (OPTIONAL) Your Log:
```
Error	CS0103:The name 'PokemonMoveMetaRegistry' does not exist in the current context	PoGo.NecroBot.Logic. (pgm:\NecroBot\PoGo.NecroBot.Logic\Tasks\UseGymBattleTask.cs	line:496)

```

### Detailed Steps to Reproduce:
Build solution throu MS visual studio 2015.

### Other Information
(Attach zip files if needed.)

Version:0.9.9.6
Windows Version: windows 10
What is affected (catch, transfer, favorite, GPX, evolve, recycle, snipe, human walk snipe, pokestops, powerup/levelup, other):

**Comment by jjskuld** [comment]
Fixed now in master
