### ISSUE TITLE
[00:10:13] (ERROR) You have to log into an browser with the email 'myemailaddress'.

### ISSUE THREAD

**Issue by ztmorris8** [Necrobot-Private/NecroBot#1890]
### Expected Behavior:
Logs into account

### Actual Behavior:
Failing to log in

### Your config.json:
```Nothing in config is different except for email and password. All default.

```

### (OPTIONAL) Your Log:
```The error is in the title
replace this text with only the "relative" portion of your log. (Remove unnessary lines)

```

### Detailed Steps to Reproduce:
Tried logging into google account and got this.

### Other Information
The google email address is through my community college that ends in midmich.edu
(Attach zip files if needed.)

Version:
Windows Version:
What is affected (catch, transfer, favorite, GPX, evolve, recycle, snipe, human walk snipe, pokestops, powerup/levelup, other):

**Comment by Furtif** [comment]
Look https://github.com/Necrobot-Private/NecroBot/issues/1862
