### ISSUE TITLE
For me necrobot have a problem

### ISSUE THREAD

**Issue by luigidanield2** [Necrobot-Private/NecroBot#1891]
Necrobot take more pokestop than Pokémon, has problems with gyms that does not leave a Pokémon in when it conquers, pokestop count counter is never right there is a limit but every time the limit changes, then you can not just capture Pokémon , Then the sniper counter always stays at zero needs some modification for the rest is spectacular another thing i use mapzen and tells me that nn takes the elevation and that in an hour i will be in the black list why?

**Comment by luigidanield2** [comment]
![img_20170711_021845](https://user-images.githubusercontent.com/20739720/28045794-9a07acec-65df-11e7-9647-e413dd5b18b0.jpg)

**Comment by Furtif** [comment]
Gyms do not works :-/

**Comment by Furtif** [comment]
All functions for this is not finalized

**Comment by Furtif** [comment]
Disable option and wait for this.
