### ISSUE TITLE
The HashKey is invalid or has expired, please press any key to exit and correct you auth.json, 

### ISSUE THREAD

**Issue by dimitris63** [Necrobot-Private/NecroBot#1893]
why am I getting the below message has the problem still not been resolved. when will it be resolved

[12:52:46] () The HashKey is invalid or has expired, please press any key to exit and correct you auth.json, 
 The Pogodev API key can be purchased at - https://talk.pogodev.org/d/51-api-hashing-service-by-pokefarmer

**Comment by Dervishi** [comment]
This problem has nothing to do with Necrobot.
Go and ask help from where you bought Your hashkey.

**Comment by Nackenschelle** [comment]
the guys from gaming legion are cracking keys and share it with the users
