### ISSUE TITLE
Bot doesn t work!

### ISSUE THREAD

**Issue by Kremer92** [Necrobot-Private/NecroBot#1895]
## Stop! Before you create this issue (you can delete this section when opening the issue):
1. Have you searched to see if there are other Open/Closed issues for the same issue? If so, comment on that issue instead.
2. Have you validated that your config/auth.json and config/config.json is valid JSON? Use http://jsonlint.com/ to check.
3. If your question is referring to how to set up or use the bot, please join our discord instead of posting an issue: https://discord.gg/7FWyWVp 
4. Always confirm that your issue is reproducible, with the config you provide below.

### Your config.json:
```
replace this text with the contents of your config.json

```

### (OPTIONAL) Your Log:
```
replace this text with only the "relative" portion of your log. (Remove unnessary lines)

```

### Other Information
(Attach zip files if needed.)

Version:
Windows Version:
What is affected (catch, transfer, favorite, GPX, evolve, recycle, snipe, human walk snipe, pokestops, powerup/levelup, other):

**Comment by Kremer92** [comment]
Hello,
i just downloaded the Bot.
There is always the same problem. 
The program tells me: "There is at least one error!"

![bot](https://user-images.githubusercontent.com/30091400/28090887-35071ecc-668e-11e7-8671-32a57212e0dc.jpg)

Can you help me please?...
THX

**Comment by blackuGT** [comment]
Well, download this :
https://ci.appveyor.com/project/jjskuld/necrobot/build/0.0.0.1797-fqjldwjv/artifacts
(console version) and wait for auto-update. For me works well
