### ISSUE TITLE
Status code Forbidden

### ISSUE THREAD

**Issue by Nackenschelle** [Necrobot-Private/NecroBot#1897]
Unexpected response from Pokemon SSO OAuth Login Url: Status code Forbidden
any solutiun?

**Comment by Nackenschelle** [comment]
#push

**Comment by Kagelol** [comment]
Means your IP has been blacklisted.  Get a VPN  (im still blacklisted from back when everyone was botting(first 2 weeks when it was released))

**Comment by Lord-Haji** [comment]
IP blacklist
