### ISSUE TITLE
0.69 Update

### ISSUE THREAD

**Issue by darkhax** [Necrobot-Private/NecroBot#1901]
Update 0.69 is now being enforced. Because of this the NecroBot no longer works. 

```
[13:14:50] (ERROR) (KILLSWITCH) We have detected a Pokemon API change. The bot emulates API version 0.67.2, which is no longer supported.  Minimum API version is now 0.69.0.
```

**Comment by Furtif** [comment]
Fixed into https://github.com/Necrobot-Private/NecroBot/pull/1887

**Comment by Chorry119** [comment]
I am in the same situation. This is a different issue than #1887.

**Comment by darkhax** [comment]
@Chorry119 #1887 is the next update for NecroBot. Everything mentioned and covered in that pull request will be included in the next update.
