### ISSUE TITLE
Can't attack gym

### ISSUE THREAD

**Issue by Alphicus** [Necrobot-Private/NecroBot#1909]
Hello,

I can't attack gym ?! It's normal at time ? and i have a problem with the sniper, i never found 100 IV and other country Pokemon. the sniper list is all time empty.

Here my config is attached
[config.txt](https://github.com/Necrobot-Private/NecroBot/files/1167986/config.txt)

Thanks in advance.

Regards.

**Comment by andeomontenegro** [comment]
snipe is dead by niantic.
gym battles in work.

**Comment by Lord-Haji** [comment]
Gyms down
