### ISSUE TITLE
Cheked mass transfer error

### ISSUE THREAD

**Issue by andeomontenegro** [Necrobot-Private/NecroBot#1911]
WIN gui.
In pokemon list I cheked >5 pokemons and click transfer all button.
Always got an error with relogin. 
![untitled5](https://user-images.githubusercontent.com/25416684/28499080-bde70da6-6fad-11e7-89ec-f85f70656be8.jpg)

BTW, evolve all button and Use lucky egg button also not working (disabled)

**Comment by Kagelol** [comment]
I have noticed this error happen from time to time.
personally it happens only one out of 10 times and the bot will simply start running again.

Also one tip, if you're going to be evolving pokemon from the gui Make sure you wait enough time(5-10sec) before evolving another, when i was evolving them really quickly i got flagged by the system.

**Comment by andeomontenegro** [comment]
Evolving is different issue, know about delays. 
Transfering error is strange, the game have oprion to mass transfer, why bot cant do the same?

**Comment by blackms** [comment]
Because it's not implemented yet.

**Comment by andeomontenegro** [comment]
well, I just notice the issue.
