### ISSUE TITLE
Egg status not refreshing properly.

### ISSUE THREAD

**Issue by Kagelol** [Necrobot-Private/NecroBot#1913]
When you leave the bot running for some time, and it doesn't restart for a bit you will get a weird view on your eggs.
Currently it tells me i have 10 eggs, but of course i can only have 9 eggs in total.
One hatched and I looted a new one.

![untitled](https://user-images.githubusercontent.com/20638091/28511291-d5d15db4-704c-11e7-8a25-921b07e7c000.png)

**Comment by Kagelol** [comment]
![egg2](https://user-images.githubusercontent.com/20638091/28515347-958dbf66-705d-11e7-8520-e6524737e60d.png)

**Comment by Lord-Haji** [comment]
It's not updated on every distance change to replicate the original app (it also updates egg distance at regular intervals) we update it with every API call
