### ISSUE TITLE
When i open necrobot.win I can only choose to pay

### ISSUE THREAD

**Issue by Wdiduud** [Necrobot-Private/NecroBot#1917]
How can i use the free version? Is it still possible to do so? It does not make me select legacy APIs but it puts me the default box where you pay.  
If someone can help me, thank you.

**Comment by andeomontenegro** [comment]
Necrobot is FREE.
Api key u can buy at bossland site

**Comment by ravdesai09** [comment]
with every new update in PoGo or in Necro haveto buy new API or with any update it works for a month??,, actually  i back after long time and many things have changed..

**Comment by andeomontenegro** [comment]
U have to buy Api each month. 
after new game release have to wait bot update. thats all.

**Comment by Wdiduud** [comment]
thanks for the answer
