### ISSUE TITLE
need help snipe

### ISSUE THREAD

**Issue by volksboyzz** [Necrobot-Private/NecroBot#1918]
i cant snipe whit my config someone can help for activate sniping

 "SnipeConfig": {
    "UseSnipeLocationServer": false,
    "SnipeLocationServer": "localhost",
    "SnipeLocationServerPort": 16969,
    "MinPokeballsToSnipe": 20,
    "MinPokeballsWhileSnipe": 0,
    "MinDelayBetweenSnipes": 60000,
    "SnipingScanOffset": 0.005,
    "SnipeAtPokestops": false,
    "SnipeIgnoreUnknownIv": false,
    "UseTransferIvForSnipe": false,
    "SnipePokemonNotInPokedex": false,
    "UseSnipeLimit": true,
    "SnipeRestSeconds": 600,
    "SnipeCountLimit": 39,
    "ActivateMSniper": true,
    "MinIVForAutoSnipe": 100,
    "MinLevelForAutoSnipe": 0,
    "AutosnipeVerifiedOnly": false,
    "DefaultAutoSnipeCandy": 0,
    "SnipePauseOnOutOfBallTime": 5,
    "AutoSnipeMaxDistance": 0.0,
    "AutoSnipeBatchSize": 10

**Comment by andeomontenegro** [comment]
there is NO sniping anymore

**Comment by luigidanield2** [comment]
Cosa vuol dire??che non funziona più? Hanno chiuso i siti???

**Comment by luigidanield2** [comment]
What means this???

**Comment by blackms** [comment]
Vuol dire che non funziona piu`, viene rilevato dalla Niantic. Basta chiedere dello sniping.

Close the ticket please.
