### ISSUE TITLE
Problem necrobot

### ISSUE THREAD

**Issue by luigidanield2** [Necrobot-Private/NecroBot#1925]
Dont know this problem!!!! Why tell this???One in the mapzen elevation !i have configure mapzen and another problem i dont know why!
![img_20170729_223544](https://user-images.githubusercontent.com/20739720/28748177-41a718c2-74b1-11e7-8773-e64ee16b0d91.jpg)
![img_20170729_194601](https://user-images.githubusercontent.com/20739720/28748178-41a78e56-74b1-11e7-93b6-250ea26a1c08.jpg)

**Comment by blackuGT** [comment]
Where is problem?

**Comment by luigidanield2** [comment]
Encounterd closed??
