### ISSUE TITLE
I tester new necrobot version

### ISSUE THREAD

**Issue by luigidanield2** [Necrobot-Private/NecroBot#1926]
Ok good 
![img_20170730_135901](https://user-images.githubusercontent.com/20739720/28753262-32934d84-7532-11e7-8913-fbae28792bd0.jpg)
work but telegramm api dont work because crash and when you install and download new version when you open tell this....so there are a problem......

**Comment by mdbsimo** [comment]
hai il mio stesso problema

**Comment by blackms** [comment]
That without any stacktrace it's practically useless in order to debug the problem.

**Comment by luigidanield2** [comment]
Non so nemmeno cosa sia una stake trace?ho solo segnalato il problema....quando apri necrobot mi esce quello è nn m sembra normale appena scaricata la versione nuova
