### ISSUE TITLE
Export to Excel holds wrong value for candy

### ISSUE THREAD

**Issue by f33stneus** [Necrobot-Private/NecroBot#1928]
### Expected Behavior:
Exporting the pokemon list to Excell should include candy values

### Actual Behavior:
Exporting results in the value: System.Threading.Tasks.Task`1[System.Int32] being reported instead of the candy count

### Your config.json:
Doesn't seem relevant for this issue

### Detailed Steps to Reproduce:
Open the pokemon list in the UI
Click on Export
Verify the value

### Other Information
Appears to have been reported earlier and fixed as per issue: https://github.com/Necrobot-Private/NecroBot/issues/1364

Version: v1.0.0.185
Windows Version: 8.1
What is affected (catch, transfer, favorite, GPX, evolve, recycle, snipe, human walk snipe, pokestops, powerup/levelup, other): Export to Excel

**Comment by Lord-Haji** [comment]
please look for already opened issues before opening one
Dup of #1894
