### ISSUE TITLE
(Crash report) Using incense make the bot crash

### ISSUE THREAD

**Issue by zapahacks** [Necrobot-Private/NecroBot#193]
I am using latest version on windows 10, when I use incense I get this error:

[17:13:27] Error: Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: 'POGOProtos.Networking.Responses.IncenseEncounterResponse' não contém uma definição para 'WildPokemon'
   em CallSite.Target(Closure , CallSite , Object )
   em System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   em PoGo.NecroBot.Logic.Tasks.CatchPokemonTask.<Execute>d__9.MoveNext() na C:\projects\necrobot2\PoGo.NecroBot.Logic\Tasks\CatchPokemonTask.cs:linha 143
--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---
   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   em System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   em PoGo.NecroBot.Logic.Tasks.CatchIncensePokemonsTask.<Execute>d__0.MoveNext() na C:\projects\necrobot2\PoGo.NecroBot.Logic\Tasks\CatchIncensePokemonsTask.cs:linha 59
--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---
   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   em PoGo.NecroBot.Logic.Tasks.UseNearbyPokestopsTask.<OnWalkingToPokeStopOrGym>d__15.MoveNext() na C:\projects\necrobot2\PoGo.NecroBot.Logic\Tasks\UseNearbyPokestopsTask.cs:linha 191
--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---
   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   em PoGo.NecroBot.Logic.Tasks.UseNearbyPokestopsTask.<>c__DisplayClass14_0.<<WalkingToPokeStop>b__0>d.MoveNext() na C:\projects\necrobot2\PoGo.NecroBot.Logic\Tasks\UseNearbyPokestopsTask.cs:linha 177
--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---
   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   em System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   em PoGo.NecroBot.Logic.Strategies.Walk.HumanStrategy.<Walk>d__4.MoveNext() na C:\projects\necrobot2\PoGo.NecroBot.Logic\Strategies\Walk\HumanStrategy.cs:linha 85
--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---
   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   em PoGo.NecroBot.Logic.Navigation.<Move>d__13.MoveNext() na C:\projects\necrobot2\PoGo.NecroBot.Logic\Navigation.cs:linha 98
--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---
   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   em PoGo.NecroBot.Logic.Tasks.UseNearbyPokestopsTask.<WalkingToPokeStop>d__14.MoveNext() na C:\projects\necrobot2\PoGo.NecroBot.Logic\Tasks\UseNearbyPokestopsTask.cs:linha 170
--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---
   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   em System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   em PoGo.NecroBot.Logic.Tasks.UseNearbyPokestopsTask.<Execute>d__13.MoveNext() na C:\projects\necrobot2\PoGo.NecroBot.Logic\Tasks\UseNearbyPokestopsTask.cs:linha 129
--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---
   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   em PoGo.NecroBot.Logic.Tasks.FarmPokestopsTask.<Execute>d__1.MoveNext() na C:\projects\necrobot2\PoGo.NecroBot.Logic\Tasks\FarmPokestopsTask.cs:linha 68
--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---
   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   em System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   em PoGo.NecroBot.Logic.State.FarmState.<Execute>d__0.MoveNext() na C:\projects\necrobot2\PoGo.NecroBot.Logic\State\FarmState.cs:linha 49
--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---
   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   em PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext() na C:\projects\necrobot2\PoGo.NecroBot.Logic\State\StateMachine.cs:linha 63

The bot re-log in, continue working, then crash again with exactly the same error.

My config is the normal one, except that google walk is disabled (necro walk) and human snipe is disabled as well.

Thanks

**Comment by BoydTM** [comment]
https://github.com/Necrobot-Private/NecroBot/issues/179
