### ISSUE TITLE
Set credentials

### ISSUE THREAD

**Issue by boscorelly** [Necrobot-Private/NecroBot#1935]
Hi,

after upgrading from 117 to 186, i have no setting in auth to put credentials.

Looking to scheme don't help me.

Any help ?

**Comment by blackuGT** [comment]
Auth.json
`{
  "Bots": [
    {
      "AuthType": "google",
      "Username": "...",
      "Password": "...",
      "AutoExitBotIfAccountFlagged": false
    }
  ],
  "ProxyConfig": {
    "UseProxy": false,
    "UseProxyHost": null,
    "UseProxyPort": null,
    "UseProxyAuthentication": false,
    "UseProxyUsername": null,
    "UseProxyPassword": null
  },
  "DeviceConfig": {
    "DevicePlatform": "...",
    "DevicePackageName": "...",
    "DeviceId": "...",
    "AndroidBoardName": null,
    "AndroidBootloader": null,
    "DeviceBrand": "...",
    "DeviceModel": "...",
    "DeviceModelIdentifier": null,
    "DeviceModelBoot": "...",
    "HardwareManufacturer": "...",
    "HardwareModel": "...",
    "FirmwareBrand": "...",
    "FirmwareTags": null,
    "FirmwareType": "...",
    "FirmwareFingerprint": null,
    "UseRandomDeviceId": false
  },
  "APIConfig": {
    "UsePogoDevAPI": true,
    "AuthAPIKey": "...",
    "UseLegacyAPI": false,
    "DiplayHashServerLog": true
  }
}`

**Comment by boscorelly** [comment]
hi,

i still have no login...

stuck at auth.json validation
