### ISSUE TITLE
Need to be add more Pokemon to evolve list..

### ISSUE THREAD

**Issue by mucro9** [Necrobot-Private/NecroBot#195]
İ think Need to be add more Pokemont to evolve list..İf we enable evolve all pokemon enoug with candy its should be evolve all pokemon not just rattata pidgey needd to be add all...Thank you....

**Comment by ajns73** [comment]
@mucro9 Just add it in your config file.

**Comment by hardknoxni69a** [comment]
lol the files are able to be edited bud add everything you like your supposed to edit them to your liking

**Comment by hardknoxni69a** [comment]
close issue
