### ISSUE TITLE
Error Fort is full

### ISSUE THREAD

**Issue by luigidanield2** [Necrobot-Private/NecroBot#1957]
Sorry what means failed to deploy .result errore Fort is full ???
![img_20170814_155552](https://user-images.githubusercontent.com/20739720/29274806-5f2e8bf0-8109-11e7-9da9-6e3ee588e08a.jpg)

**Comment by blackuGT** [comment]
Gym is full... lol

**Comment by luigidanield2** [comment]
Ok but dont Attack the Jim???why?

**Comment by Furtif** [comment]
@luigidanield2 no no gyms attaks available and no raids same only spin disk and deploy, deploy is gym as no raid actif, if as slot free etc.. if you have error is no deployed if you have Great!!! you pokemon is deployed

**Comment by sinnx3** [comment]
@luigidanield2 this is what is currently supported  https://github.com/AeonLucid/POGOProtos/blob/master/src/POGOProtos/Networking/Requests/RequestType.proto , attacking gyms is not supported.
