### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by myogui** [Necrobot-Private/NecroBot#1969]
Hi!

could you make a new release with the lastest merges please :D

thanks!

**Comment by CDAGaming** [comment]
I can(and probably will) when I have time to do so.

**Comment by Lord-Haji** [comment]
We are on the latest release

**Comment by andeomontenegro** [comment]
and where is new release? (( my hash api ending soon...

**Comment by dougmaitelli** [comment]
@andeomontenegro Just download the latest beta build on appveyor, link is at the top of the README file in the build status badge.

**Comment by andeomontenegro** [comment]
@dougmaitelli cant find a link(( help me?

**Comment by dougmaitelli** [comment]
@andeomontenegro https://ci.appveyor.com/project/jjskuld/necrobot/branch/master

However some minutes ago the API got updated to 0.75.1 so this build is not working anymore, you can maybe try the one in Latest Build tab. You can find the downloadable files under the Artifacts tab.

**Comment by Furtif** [comment]
https://ci.appveyor.com/project/jjskuld/necrobot/build/0.0.0.1860-xaxvnvde/artifacts 0.75.1 ready

**Comment by andeomontenegro** [comment]
Many thanx guys!!
