### ISSUE TITLE
Pokemon spawn point data service connection established. need help !!

### ISSUE THREAD

**Issue by remuschok** [Necrobot-Private/NecroBot#197]
im stuck on this :(
 (Pokemon spawn point data service connection established.)

**Comment by teos81** [comment]
Same Problem,
plus AM Fatal Webshoket.dohandshacke

**Comment by zc3721** [comment]
same

**Comment by iwean** [comment]
@remuschok @teos81 @zc3721 
Guys... check this out >>> #219

**Comment by remuschok** [comment]
@iwean its means false the sharing data?
