### ISSUE TITLE
API change

### ISSUE THREAD

**Issue by andeomontenegro** [Necrobot-Private/NecroBot#1978]
kill switch stops the bot. 

**[20:45:07] (ERROR) (KILLSWITCH) We have detected a Pokemon API change. The bot emulates API version 0.73.1, which is no longer supported.  Minimum API version is now 0.75.0.**

**Comment by TrollBusterxD** [comment]
i have a 0.75.0 API Key which runned perfect this morning and now i got the same message ....

**Comment by Furtif** [comment]
Fixes into https://github.com/Necrobot-Private/NecroBot/pull/1979
