### ISSUE TITLE
API Change 0.77.1

### ISSUE THREAD

**Issue by cicerocruz** [Necrobot-Private/NecroBot#1988]
Hi, 

Is there any beta with the API change?

**Comment by zebuibui** [comment]
I can't use necrobot. Minimum API version supported is 0.77.1. Do you have any ETA to release API to works ? Thanks

**Comment by Furtif** [comment]
fix at https://github.com/Necrobot-Private/NecroBot/pull/1987

**Comment by zebuibui** [comment]
Hi there. Sorry for dummy question. I'm not programmer. What should i do ?
or how can i fix it ? I need to change and recompile ? Could somebody tell
me ?

Thank you

2017-10-15 16:20 GMT-02:00 Haji Sama <notifications@github.com>:

**Comment by Lord-Haji** [comment]
Just wait for the new version

Pro tip :- it's on current master

**Comment by zebuibui** [comment]
Hi there. I chrcked that u uploaded source codes. Who would compile for
windows executable? I'd like to test it.

Em domingo, 15 de outubro de 2017, Haji Sama <notifications@github.com>
escreveu:
