### ISSUE TITLE
NecroBot2 1.0.0.350 windows

### ISSUE THREAD

**Issue by cicerocruz** [Necrobot-Private/NecroBot#1989]
When is the compiled version for Windows available?
Can you make the link available in the discord or the appveyor?

**Comment by Furtif** [comment]
@cicerocruz release is bloqued dues at changelog_generator https://github.com/skywinder/github-changelog-generator/pull/578 pr to fixes it, if you want uses lasted appveyor check here https://ci.appveyor.com/project/jjskuld/necrobot/build/0.0.0.1865/artifacts or visite discord for more help.

Enjoy

**Comment by zebuibui** [comment]
hi there. Is there a new necrobot compatible with 0.79.3 version?
