### ISSUE TITLE
0.79.3 compatible version

### ISSUE THREAD

**Issue by zebuibui** [Necrobot-Private/NecroBot#1991]
Hi there.

Is there a new version compatible with pokemon go 0.79.3 ?

https://ci.appveyor.com/project/jjskuld/necrobot/build/0.0.0.1865/artifacts no more compatible. 

Thank you

**Comment by Furtif** [comment]
hello fix at https://github.com/Necrobot-Private/NecroBot/pull/1990 appveyor check at https://ci.appveyor.com/project/jjskuld/necrobot/build/0.0.0.1874-kamxflgo/artifacts
