### ISSUE TITLE
API Endpoint question

### ISSUE THREAD

**Issue by kajibug** [Necrobot-Private/NecroBot#1992]
Hello,

What I am seeing is that under APIConfig in the auth.json the line "EndPoint: "api/v147_1/hash"

This might be a Bossland API key issue, but as the newest version of PKG is 1.49.3. it seems like a problem

If anyone can confirm this I would appreciate it and thank you for your time!

**Comment by Furtif** [comment]
End point is good look set usepogodev true and false usecustomapi for uses bossland Defaults
