### ISSUE TITLE
New Bot is doesnt work

### ISSUE THREAD

**Issue by mucro9** [Necrobot-Private/NecroBot#2]
When i comleted all config when i start bot is saying you need auth json but i have already that..İthink short codes..So not working

**Comment by wilddeuces** [comment]
Show ur auth.json

**Comment by mucro9** [comment]
{
  "AuthConfig": {
    "AuthType": "ptc",
    "GoogleUsername": null,
    "GooglePassword": null,
    "PtcUsername": "whatever",
    "PtcPassword": "123456"
  },
  "ProxyConfig": {
    "UseProxy": false,
    "UseProxyHost": null,
    "UseProxyPort": null,
    "UseProxyAuthentication": false,
    "UseProxyUsername": null,
    "UseProxyPassword": null
  },
  "DeviceConfig": {
    "DevicePackageName": "sony-z3-compact",
    "DeviceId": "a815b9de93d24f42",
    "AndroidBoardName": "MSM8974",
    "AndroidBootloader": "s1",
    "DeviceBrand": "docomo",
    "DeviceModel": "SO-02G",
    "DeviceModelIdentifier": "SO-02G",
    "DeviceModelBoot": "qcom",
    "HardwareManufacturer": "Sony",
    "HardwareModel": "SO-02G",
    "FirmwareBrand": "SO-02G",
    "FirmwareTags": "release-keys",
    "FirmwareType": "user",
    "FirmwareFingerprint": "docomo/SO-02G/SO-02G:5.0.2/23.1.B.1.317/2161656255:user/release-keys"
  }
}

**Comment by wilddeuces** [comment]
Seems to be fine, post a screenshot of ur config folder and the bot message

**Comment by msx752** [comment]
i think  mssing file   re-download : https://github.com/Necrobot-Private/NecroBot/releases/download/v0.9.7.2/Release.zip

**Comment by mucro9** [comment]
@msx752 thank you
