### ISSUE TITLE
Pokemon API Change to 0.79.4 - Necrobot only supports 0.79.3

### ISSUE THREAD

**Issue by superchurch** [Necrobot-Private/NecroBot#2001]
Hi All,

Just seeing if there is a fix for this problem (as attached).

Cheers
![botissue](https://user-images.githubusercontent.com/33559894/32682273-9bb283c4-c6c3-11e7-9766-14427d0ca678.PNG)

**Comment by Furtif** [comment]
fix at https://github.com/Necrobot-Private/NecroBot/pull/2000 uses appveyor build check or wait new release https://ci.appveyor.com/project/jjskuld/necrobot/build/0.0.0.1899-rlcfmupo/artifacts

**Comment by superchurch** [comment]
you the man

**Comment by NaxNydr** [comment]
Hi,

Even that I updated mine, still says the same thing. Any ideas?

Thanks

**Comment by Furtif** [comment]
if you uses appveyor builds or check code builds you do not update it ignore update allright

**Comment by Grisl** [comment]
Why is there no compiled version of the console?

**Comment by Furtif** [comment]
Read up zip console is on artifact
