### ISSUE TITLE
please your help me

### ISSUE THREAD

**Issue by zsatanxz** [Necrobot-Private/NecroBot#201]
"ActivateMSniper": true,

program msniper use auto...?
or cilck msniper on website msniper

![555555555555555](https://cloud.githubusercontent.com/assets/21266188/18613342/9923005e-7da2-11e6-8e45-92704652810c.jpg)

**Comment by BoydTM** [comment]
click msniper ... but in order to work you need to run registerProtocol.bat from msniper binaries ...

**Comment by zsatanxz** [comment]
@boydtm okay i'm click registerProtocol.bat
I'm use msniper auto or manual
Set config activemsniper true

**Comment by BoydTM** [comment]
necrobot version ?

**Comment by zsatanxz** [comment]
@BoydTM 0.9.9.7

**Comment by zsatanxz** [comment]
i,m go to click in website msniper
necrobot no work auto msniper

**Comment by zsatanxz** [comment]
![6666666666666666666666](https://cloud.githubusercontent.com/assets/21266188/18613836/be38e50c-7dac-11e6-90e5-e61777f83d50.jpg)

**Comment by BoydTM** [comment]
it should be something like that:
[08:24:16] (SERVICE) Connecting to MSniperService
[08:24:17] (SERVICE) (Identity) [ ba2d24e7-ec9d-4948-ae47-1492def8e3a0 ] connection establisted

looks like in your case you cannot establish connection, you gonna need developer help

**Comment by zsatanxz** [comment]
i'm go to wesite and click pokemon yes or no

**Comment by zsatanxz** [comment]
![777777777777777777777777](https://cloud.githubusercontent.com/assets/21266188/18614169/01214362-7db4-11e6-8e82-8bc8642935a9.jpg)

**Comment by zsatanxz** [comment]
i'm download MSniper.v1.0.6.2 run necrobot and click MSniper.exe and registerProtocol

**Comment by BoydTM** [comment]
its always good to have newest versions ... but in that case seems that your necrobot is having problem with specific connection (maybe its because some forewall ... etc ? )

**Comment by msx752** [comment]
İ think firewall is blocking The Connection. Or you are using more than one bot ??
