### ISSUE TITLE
Bot api change

### ISSUE THREAD

**Issue by cibermen2** [Necrobot-Private/NecroBot#2016]
my bot shows up this message: [20:24:08] (ERROR) (KILLSWITCH) We have detected a Pokemon API change. The bot emulates API version 0.87.5, which is no longer supported.  Minimum API version is now 0.89.0.                                                                   [20:24:08] (ERROR) The bot will now exit after hitting the enter key.

what can I do to fix it?

Necrobot2 on Windows 10

**Comment by CDAGaming** [comment]
Updated Bot is in Discord or on our Appveyor CI

**Comment by cibermen2** [comment]
In what channel in discord? Cant find it

**Comment by cibermen2** [comment]
my necrobot2 is at version 1.0.0.400 already

**Comment by Furtif** [comment]
https://ci.appveyor.com/project/jjskuld/necrobot/build/0.0.0.1924-sopofwtl/artifacts

**Comment by Furtif** [comment]
fix https://github.com/Necrobot-Private/NecroBot/pull/2015
