### ISSUE TITLE
API KEY CHANGE HELP PLEASE!!!

### ISSUE THREAD

**Issue by seasidersmith** [Necrobot-Private/NecroBot#2017]
new to Necrobot and only downloaded it yesterday, bought my key from pokfarmer and everytime i start up it says KIllswitch error "the bot emulates API version 0.87.5 which is no longer supported.

I am a complete novice at things like this so really need help with a work around

**Comment by Furtif** [comment]
see at https://github.com/Necrobot-Private/NecroBot/issues/2016

**Comment by seasidersmith** [comment]
yes followed that path and download the console version ...... it installed then auto updated to the .400 version and said exactly the same

**Comment by seasidersmith** [comment]
should I reinstall and this time cancel the update?

**Comment by Furtif** [comment]
read #2016 use appveyor CI or wait for merge lasted PR actif and new release

**Comment by seasidersmith** [comment]
Sorry really new to this and dont understand .... does that mean i have to change something in the code ? 

if so whats the path and change required ?

Seen the new post at the bottom of that page but not sure what i have to do from that link

**Comment by Furtif** [comment]
is simple current release is outed this need merge current PR https://github.com/Necrobot-Private/NecroBot/pull/2015 and release it.. current release x.400 emulates api 0.87.5 current pr emulates 0.89.1, this is not merged only appveyor CI (check build) is availlable

**Comment by seasidersmith** [comment]
Sorry like i said i dont understand the gargon and Language, New to all this and have no idea how to do that. I have completely deleted the files and am going to reinstall. Should i follow the path on Appveyor Ci link ?

Should i then download the .console or .win (bear in mind I all ready followed this path with the .console) after it installed last time via the Appveyor CI link it auto updated to the .400 version and still said the same error code as in the opening post. 

What is PR??

**Comment by Furtif** [comment]
https://ci.appveyor.com/project/jjskuld/necrobot/build/0.0.0.1924-pdfdflve/artifacts

**Comment by seasidersmith** [comment]
om how do i merge the current pull request on 2015 with the file on CI.appveyor and should i use .console or .win?

**Comment by Furtif** [comment]
all is in ... console wingui rocketbot

**Comment by seasidersmith** [comment]
so i download all three files?? and it should work??

**Comment by seasidersmith** [comment]
Really sorry I am casual user and my kids are trying to get me to do this for them as they have no idea appreciate the help a lot

**Comment by Furtif** [comment]
not dowload only wingui or other usualy ....
gui = necro gui
console = full cmd
rocketbot = ligth gui

**Comment by seasidersmith** [comment]
right i will download .win file now and get back to you shortly to see if it works

**Comment by seasidersmith** [comment]
do i just download the program and start up as usual and it should work?

**Comment by Furtif** [comment]
[RocketBot](https://github.com/TheUnnamedOrganisation/RocketBot/releases) = ligth gui (rocketbot is released to v2.21.1.1 0.89.1 ready)

**Comment by seasidersmith** [comment]
Tried Rocket Bot earlier and it says my Hash Key is completely invalid

**Comment by Furtif** [comment]
hash keys is not issue necro or rocket see side bossland or other service

**Comment by Furtif** [comment]
read readme file on this git hub https://github.com/Necrobot-Private/NecroBot#necrobot2-is-now-compatible-with-0875-api

**Comment by seasidersmith** [comment]
working via the .win download .... i just cancelled the auto update and it seems fine

**Comment by seasidersmith** [comment]
Thankyou so mu9ch for your help

**Comment by Furtif** [comment]
no worries all right 👍

**Comment by megamelon** [comment]
can anyone use the telegrambot?
I create a telegram bot but cant receive any information
