### ISSUE TITLE
API change  0.95.0

### ISSUE THREAD

**Issue by boscorelly** [Necrobot-Private/NecroBot#2024]
Will you support : 

Minimum API version is now 0.95.0.

**Comment by Furtif** [comment]
yep... all stoped for moment....

**Comment by boscorelly** [comment]
why ? :(

**Comment by Potzten** [comment]
So, will we have to fix the issues manually or will there be an update for Necrobot soon?

**Comment by Furtif** [comment]
Hash services is down or outed

**Comment by davi200180** [comment]
<ERROR> <KILLSWITCH> We have detected a Pokemon API change. The bot emulates API version 0.91.1, which is no longer supported. Minimum API version is now 0.97.1.

Please update :(

**Comment by CDAGaming** [comment]
Please wait for an Update, Hashing literally just updated today, be paitient for ours
