### ISSUE TITLE
Error [Question]

### ISSUE THREAD

**Issue by alvin0111** [Necrobot-Private/NecroBot#204]
I got this message. Can you guys help me to fix it? thanks 
![error](https://cloud.githubusercontent.com/assets/21995175/18614625/215d41dc-7dbc-11e6-9b0c-5bc45cac8b0b.png)

## Stop! Before you create this issue (you can delete this section when opening the issue):
1. Have you searched to see if there are other Open/Closed issues for the same issue? If so, comment on that issue instead.
2. Have you validated that your config/auth.json and config/config.json is valid JSON? Use http://jsonlint.com/ to check.
3. If your question is referring to how to set up or use the bot, please join our discord instead of posting an issue: https://discord.gg/7FWyWVp 
4. Always confirm that your issue is reproducible, with the config you provide below.

### Your config.json:
```
replace this text with the contents of your config.json

```

### (OPTIONAL) Your Log:
```
replace this text with only the "relative" portion of your log. (Remove unnessary lines)

```

### Other Information
(Attach zip files if needed.)

Version:
Windows Version:
What is affected (catch, transfer, favorite, GPX, evolve, recycle, snipe, human walk snipe, pokestops, powerup/levelup, other):

**Comment by BoydTM** [comment]
https://github.com/Necrobot-Private/NecroBot/issues/179
