### ISSUE TITLE
Gui not changing bot location

### ISSUE THREAD

**Issue by lito2506** [Necrobot-Private/NecroBot#205]
I was observing the bot for couple of minutes now and my location in the NecroBot2.Gui is not moving. Am I missing something here? Do I need to change something in the config file?

**Comment by BoydTM** [comment]
in my case its sometimes happen when bot is taking shortcuts during humanwalk snipe ( walking on the water or no roads)

**Comment by barthdu09** [comment]
Same here. I think the problem comes from the console program, it doesn't seem to move

**Comment by ajns73** [comment]
Happens to me just before and after a catch and while sniping.
