### ISSUE TITLE
0.9.9.8 Error: Microsoft.CSharp.RuntimeBinder.RuntimeBinderException

### ISSUE THREAD

**Issue by BoydTM** [Necrobot-Private/NecroBot#208]
![necerror 6](https://cloud.githubusercontent.com/assets/21159620/18618320/a648f6fc-7de4-11e6-94b5-b91052315147.jpg)

**Comment by mo0ojava** [comment]
Suspected something regarding MSnipe could break with latest commit. Never thought it would be there... patching up.

**Comment by mo0ojava** [comment]
Set ActivateMSniper to false meanwhile and it will work.

**Comment by BoydTM** [comment]
yep ... with sniper disabled everything seems to work nice ... thx

**Comment by erickerich** [comment]
it seems only appear once while bot start, and won't effect MSniper.
not every bot (only two of mine) has this error. 
and even has this error msg, MSniper work well.

**Comment by mo0ojava** [comment]
Test the new fix. Should start cleanly now. The error happened because MSnipe isn't designed to work with lure or incense pokemons - and don't shield against that happening either. Now there should be no such being fed to MSnipe.

**Comment by BoydTM** [comment]
works like a charm ... that was fast :)
