### ISSUE TITLE
Traveling to Pokestop/Gym didn't show pokestop's name

### ISSUE THREAD

**Issue by erickerich** [Necrobot-Private/NecroBot#210]
![pokestop](https://cloud.githubusercontent.com/assets/21130145/18618615/1bb636a6-7e1d-11e6-94dc-58e753e9d9af.JPG)
Traveling to Pokestop/Gym didn't show pokestop's name.
version: 0.9.9.8

**Comment by jjskuld** [comment]
Dup of #212. Fixed already.
