### ISSUE TITLE
Execcutor with cp 2015 auto transfered after capture!!

### ISSUE THREAD

**Issue by teos81** [Necrobot-Private/NecroBot#211]
The bot have auto transfered an Execcutor with cp 2015 after it was captured!!
 
Bot last version, just updated, this is the config part:

"PokemonConfig": {
    "CatchPokemon": true,
    "DelayBetweenPokemonCatch": 2000,
    "UseCatchLimit": false,
    "CatchPokemonLimit": 998,
    "CatchPokemonLimitMinutes": 1470,
    "UseIncenseConstantly": false,
    "UseEggIncubators": true,
    "UseLimitedEggIncubators": true,
    "UseLuckyEggConstantly": false,
    "UseLuckyEggsMinPokemonAmount": 30,
    "UseLuckyEggsWhileEvolving": false,
    "UseBerriesMinCp": 1000,
    "UseBerriesMinIv": 90.0,
    "UseBerriesBelowCatchProbability": 0.2,
    "UseBerriesOperator": "or",
    "MaxBerriesToUsePerPokemon": 4,
    "TransferWeakPokemon": false,
    "TransferDuplicatePokemon": true,
    "TransferDuplicatePokemonOnCapture": true,
    "RenamePokemon": false,
    "RenameOnlyAboveIv": false,
    "RenameTemplate": "{1}_{0}",
    "FavoriteMinIvPercentage": 95.0,
    "AutoFavoritePokemon": false,
    "MaxPokeballsPerPokemon": 6,
    "UseGreatBallAboveCp": 1000,
    "UseUltraBallAboveCp": 1250,
    "UseMasterBallAboveCp": 1500,
    "UseGreatBallAboveIv": 85.0,
    "UseUltraBallAboveIv": 95.0,
    "UseGreatBallBelowCatchProbability": 0.2,
    "UseUltraBallBelowCatchProbability": 0.1,
    "UseMasterBallBelowCatchProbability": 0.05,
    "AutomaticallyLevelUpPokemon": false,
    "OnlyUpgradeFavorites": true,
    "UseLevelUpList": true,
    "AmountOfTimesToUpgradeLoop": 5,
    "GetMinStarDustForLevelUp": 5000,
    "LevelUpByCPorIv": "iv",
    "UpgradePokemonCpMinimum": 1000.0,
    "UpgradePokemonIvMinimum": 95.0,
    "UpgradePokemonMinimumStatsOperator": "and",
    "EvolveAboveIvValue": 95.0,
    "EvolveAllPokemonAboveIv": false,
    "EvolveAllPokemonWithEnoughCandy": true,
    "EvolveKeptPokemonsAtStorageUsagePercentage": 90.0,
    "KeepPokemonsThatCanEvolve": false,
    "KeepMinCp": 1000,
    "KeepMinIvPercentage": 70.0,
    "KeepMinLvl": 6,
    "KeepMinOperator": "or",
    "UseKeepMinLvl": false,
    "PrioritizeIvOverCp": true,
    "KeepMinDuplicatePokemon": 1,
    "UsePokemonToNotCatchFilter": false,
    "UsePokemonSniperFilterOnly": false,
    "DumpPokemonStats": false,
    "DelayBetweenPokemonUpgrade": 10000
  },

It could be that the "Transfert after capture" option skip the check for Keep pokemon?

Bye

**Comment by wilsondgonzales** [comment]
it's likely you have a filter for eggy down below and you have specified a moves list with an operator 'and'

**Comment by popsoda27** [comment]
yeap, it's likely bcos u have a transfer filter in place. Check towards the bottom of your config

**Comment by teos81** [comment]
Nop,
this is the transfer filter section:
"Exeggutor": {
      "KeepMinCp": 1800,
      "KeepMinIvPercentage": 90.0,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinOperator": "or",
      "KeepMinDuplicatePokemon": 1,
      "Moves": [
        [
          "zenHeadbuttFast",
          "solarBeam"
        ]
      ],
      "DeprecatedMoves": null,
      "MovesOperator": "and"
    },

**Comment by wilsondgonzales** [comment]
Ugh that's exactly what I said. Basically if it doesn't match the move set, it'll get transferred

**Comment by teos81** [comment]
Thanks, i have make confusion With "Moves" and Move alias transfer.."

I have changed it now.. Thanks a lot!!
