### ISSUE TITLE
[Feature request] NO looting, JUST catching

### ISSUE THREAD

**Issue by zapahacks** [Necrobot-Private/NecroBot#215]
Is there anyway I can set the bot to just catch pokemons?
Like, I have 340 pokeballs, I just want it to catch until it run out of pokeballs, with out looting.
It is just because sometimes I reach the pokestop limit too fast but not the catch limit

Something like:

  "PokeStopConfig": {
    "Looting": TRUE/FALSE 
    "UsePokeStopLimit": true,
    "PokeStopLimit": 1998,
    "PokeStopLimitMinutes": 1470

Thanks in advance

**Comment by wilsondgonzales** [comment]
"PokeStopLimit": 0

**Comment by tr1p0z** [comment]
I dont know now but last time I tried "PokeStopLimit" the bot still walking to pokestops.

**Comment by tr1p0z** [comment]
![](https://i.gyazo.com/ee536b23762d308546c29909ecc5cbe2.png)

Should only go for gyms, but is walking to pokestops.

**Comment by zapahacks** [comment]
Thanks @wilsondgonzales, setting the option to 0 makes the bot stop looting, it loots only the firts pokestop, then the kill switch activates BUT unfortunately when this happens the bot just travels between the same two pokestops repeteadly with out catching pokes. I guess the option that I want is to make the bot walk normally (the same directions as it was going to loot) but not to loot the pokestops.

@tr1p0z it walks to pokestops, I checked it in the gui, it doesnt loot them though, BUT in my case it goes back and forth between the same 2 pokestops.

**Comment by tr1p0z** [comment]
@zapahacks try  "UseGoogleWalk": false,

**Comment by zapahacks** [comment]
@tr1p0z I always use it in false, always necro route, so I think it is not related to that option. Perhaps I should try with True, maybe with google walk the bot will continue the normal root eventhough it is not looting. I'll try it later and I will report back.

**Comment by tr1p0z** [comment]
Yes something is buggy

**Comment by zapahacks** [comment]
@tr1p0z, so I gave it a try, and I found this:

1. When google walk is active, the bot wont loot at all (could you give it a try to confirm this bug?) and it will catch pokemons normally BUT the route is kind of crazy, sometimes it goes back and forth between the same pokestops and sometimes it walk normally.

2. If the kill switch for pokestops its activated, the bot will go back and fort between the 2 closests pokestops endlessly.

I am using the latest version 9.9.8.

**Comment by tr1p0z** [comment]
Is happening the same to me, but in one moment the stop just going to gyms like I want but randomly start walking to pokestops again (with GoogleWalk false) i dont know what to think now 👎

**Comment by jjskuld** [comment]
Bouncing between 2 pokestops is a bug that has been fixed (see bug #213).

**Comment by jjskuld** [comment]
Fixed. You can set
```
"PokeStopLimit": 0,
``` 
and it will walk properly.
