### ISSUE TITLE
(Question) Does the speed affects the amount of pokemon caught/encountered?

### ISSUE THREAD

**Issue by zapahacks** [Necrobot-Private/NecroBot#216]
I use the real app on and android phone with a joystick xposed module, I have seen that when the joystick is set to a high speed the pokemons will only appear in the game when I stop. Something similar happens depending on the rarity of the pokemons, for example, pidgeys, weedles, and common pokemons appear when I am walking fast in the game, but the rares pokemon will only appear if I am walking very slow or if I stop. The rare pokemons will also dissapear if I move (a short distance) away from them, but the common pokemons will remain in the screen for longer distances until they dissapear.

I was wondering if the speed of the bot affect this. If the bot goes too fast, will pokemons not appear as it happens in the real phone app? If the bot moves a short distance away, will it still be able to encounter and catch the rare pokemons (that would dissapear naturally in the real app)?

I would appreciate if anybody could share their knowledge about this, maybe, if there is an specific speed that we should aim, or if anybody have tried 2 bots in the exact location with different speeds...like, one walking at 2.5 and the other one at 14, would they catch the same pokemons?

Thanks

**Comment by iwean** [comment]
I think what behavior on phone is same with on the bot, because it use same api from niantic. But if you care about rare pokemon, it has been fill with HumanWalkSnipe function that has 8 site feeders to scan rare pokemon on your location for you.
