### ISSUE TITLE
bypass screen

### ISSUE THREAD

**Issue by TriNtoro** [Necrobot-Private/NecroBot#217]
Dear all

how to bypass " Do you want to Override Killswitch to bot at your own risk"
without enter "Y".

any setting to bypass screen?. on config.json??

thanks

**Comment by jjskuld** [comment]
See https://github.com/Necrobot-Private/NecroBot/wiki/Command-Line-Arguments

**Comment by TriNtoro** [comment]
Thanks.
i made file necroauto.bat 
thanks
