### ISSUE TITLE
[Non Issue] - A very reliable & trusted snipers data 

### ISSUE THREAD

**Issue by samuraitruong** [Necrobot-Private/NecroBot#219]
In past few days, as you guys realize we added new feature in bot call data sharing service. That can toggle on/off update to you but I recommend leave it on by default to feed the rare pokemon to data service that will help other people using it in sharing between us.

We are having 1000+ bot running ATM to feed data about 1000 encounter data every second, then site always have 40+ rare pokemon ready for snipe. that data all come from necrobot so we have IV & Location is 100% true.

Site also have a very nice front-end  (designed by non desinger - it is me). Allow you config desktop notification, toast notification , pushbullet notificaiton (comming ). Also customize the link sniper you want. 

yeah, It here
please visit **# http://necrosocket.herokuapp.com/**
![image](https://cloud.githubusercontent.com/assets/1183138/18623385/bc21e786-7e7f-11e6-85b0-054786bba204.png)

setting screen :+1:
![image](https://cloud.githubusercontent.com/assets/1183138/18623390/d754c906-7e7f-11e6-81e6-ce6dee700b04.png)

Work in progress
- Responsive layouts for mobile /tablet
- move to Angularjs
- Pushbullets notification
- Live data rarity calculation

Welcome all folks to join and enhance project with me at https://github.com/samuraitruong/necro_socket

Cheers

**Comment by REDESTOR** [comment]
well actually there is an issue with this, every time the bot connects, it stops walking

**Comment by REDESTOR** [comment]
is a great idea but, what if you made it connects to location feeder or function like it to enable the bot auto sniping...

**Comment by iwean** [comment]
@REDESTOR 
It will make super duper heavy connection to the server :smile: 
All you guys connected and all you snipe automatically.... server will crash!!

**Comment by samuraitruong** [comment]
@REDESTOR  :  Don't think we have an issue, I will cover code with try catch and kill it if server not respond timely. but atm it work great. it was handle 60k request in few hours.

sniper not make affect on this server. but too many bot..... then i will limit request to send from client. for now every pokemon will be send to server. I going to code data mining to give more accuracy rarity

**Comment by BoydTM** [comment]
More feed for msniper - great, but looks like there is still some work to do ((ERROR) Object reference not set to an instance of an object.)

![necerror 7](https://cloud.githubusercontent.com/assets/21159620/18626049/d101d468-7e52-11e6-8105-ca47e3de6f99.jpg)

**Comment by tr1p0z** [comment]
Same error for me

**Comment by BoydTM** [comment]
Btw, graphic design and funcionality (except error) is beautiful, but may i suggest making creature icon/button smaller ? ... like 50% Current size looks like prepared for mobiles .... not computers

**Comment by samuraitruong** [comment]
that error is not because of this feature. something else.  I will make the icon smaller by a half in 3 sec. thanks for feedback

**Comment by samuraitruong** [comment]
BodyTM : that bug come from msniper, he is working on it. I thought

**Comment by BoydTM** [comment]
understood - however msniper.com seems have the same feed and it works there...

**Comment by samuraitruong** [comment]
msniper sem not give you all feed. I don'tknow how he filter data. if I turn off my filter to allow show some normal pokemon like msniper . I will get 10k+ pokemon show up. he seem has problem with socket server, lot of request be rejected.

**Comment by teos81** [comment]
Hi,
after the last 9.9.9 update, istill have the same Fatal Websocket error if i enable the sharing sevice..

It's normal??
![bot](https://cloud.githubusercontent.com/assets/6795637/18636302/8a5a2106-7e88-11e6-9eb6-b74f4a1c8501.jpg)

**Comment by petpetpetvm** [comment]
Hi, can you add moves in ? it would be helpful + I don't think the LV would be matter (it will be random though)

**Comment by jjskuld** [comment]
@samuraitruong BTW, I just copied this info to the wiki 
https://github.com/Necrobot-Private/NecroBot/wiki/NecroSocket---Reliable-Sniping-Data-Sharing-Site

**Comment by BreakThroughSec** [comment]
I'm not seeing any pokemon on the site (https://necrosocket.herokuapp.com/#). Is it down?

**Comment by iwean** [comment]
It move to the more stable site >>> http://www.mypogosnipers.com/#
