### ISSUE TITLE
Is it an error?

### ISSUE THREAD

**Issue by alvin0111** [Necrobot-Private/NecroBot#220]
Is it an error? I got this message but the bot still running.
![untitled](https://cloud.githubusercontent.com/assets/21995175/18628890/92682d08-7e8c-11e6-8ce7-c9b8a166fbfd.png)

And sometime i got softban
![cb609dac-7e8c-11e6-95b8-0382e7a7ebc1](https://cloud.githubusercontent.com/assets/21995175/18633429/77e4d1c4-7ea6-11e6-8fec-94f68aac98dd.png)

Version:
Windows Version:
What is affected (catch, transfer, favorite, GPX, evolve, recycle, snipe, human walk snipe, pokestops, powerup/levelup, other):

**Comment by iwean** [comment]
Already fixed it: #226 
...wait for the new release.
