### ISSUE TITLE
GPX issue

### ISSUE THREAD

**Issue by zhiwei2017** [Necrobot-Private/NecroBot#221]
I download a gpx file from the website https://wtracks.appspot.com, then I set the necrobot2 wo use it. The gpx file is in the config folder.

### Expected Behavior:
The gpx file should be compatible with necrobot2.

### Actual Behavior:

But when I run Necrobot2, it crashes.

```
  "GPXConfig": {
    "UseGpxPathing": true,
    "GpxFile": "center.gpx"
  }

```

### Detailed Steps to Reproduce:
just in the website generate a path and output it, then put it in the config folder in necrobot2

Version: 0.9.9.9
Windows Version: win 8 pro
What is affected : GPX

Thanks.

**Comment by kalamera** [comment]
you need to put the gpx file next to the necrobot.exe not into the config folder

**Comment by ValorRed** [comment]
Or, in your config.json: config/center.gpx

**Comment by zhiwei2017** [comment]
@kalamera @ValorRed thanks!
