### ISSUE TITLE
NecroBot cannot run on my Lap

### ISSUE THREAD

**Issue by lambeng88** [Necrobot-Private/NecroBot#222]
![image](https://cloud.githubusercontent.com/assets/20960946/18632893/f9f8cfe2-7ea3-11e6-90cc-ddb68d909888.png)

**Comment by sukasuki** [comment]
just rerun back setting .. its normal sometime happen also

**Comment by aryaputrapande** [comment]
In question "Please enter your desired walking speed" just type numberic without type "[max 12]".

**Comment by jjskuld** [comment]
This is not a bug. Just type a number like @aryaputrapande said above.
