### ISSUE TITLE
Know Issue - MSniper link wrong on necrosocket

### ISSUE THREAD

**Issue by samuraitruong** [Necrobot-Private/NecroBot#226]
# Attention

Just realize that the number has been rounded when display in javascript. that make a link to Msniper on necrosocket not working. the fix already here - https://github.com/Necrobot-Private/NecroBot/pull/225

**Comment by iwean** [comment]
Some explanation:
- Necrosocket related to site feeder >>> http://necrosocket.herokuapp.com/
- MSniper related to site feeder >>> http://msniper.com/

Both site were work together with [MSniper App](https://github.com/msx752/MSniper/releases/tag/1.0.6.2)

**Comment by langit7** [comment]
always got [14:50:29] (ERROR) Object reference not set to an instance of an object. when using necrosocket url

**Comment by samuraitruong** [comment]
bug has been fix. wait for release

**Comment by langit7** [comment]
Im not sure its still related or not, 
i test  by clicking the url from necrocket , the result is bot not capture anything
msniper://Lapras/17105511481965361000/601889f3d15/35.632249709958536,139.7801849809378/72.69
[16:18:12] (SNIPER) (MSniperService) Sniping a Lapr
[16:18:18] (SERVICE) Connecting to MSniperService

**When i try copied mannullay the  cords**
[16:18:53] (SERVICE) Connecting to MSniperService
[16:18:53] (SNIPER) (MSniperService) Sniping a Lapras with Unknown IV at 35.6322497099585,139.780184980938...
[16:19:00] (BERRY) Used Razz Berry | 45 remaining
[16:19:01] (INFO) (CATCH LIMIT) 185/998
[16:19:02] (PKMN) (CatchSuccess) | (Normal) Lapras Lvl: 19 CP: (1558/1618) IV: 73.00% | Chance: 13.74% | 10227237.20m dist | with
a GreatBall (26 left). | 210 EXP earned | Candies: 17 | lat: 35.632250 long: 139.780185 | Move1: IceShardFast Move2: IceBeam | Rar
ity :VeryRare

**Comment by samuraitruong** [comment]
most of link now are fixed.

**Comment by langit7** [comment]
links all working fine , if there is option to automate its would be nice

**Comment by msx752** [comment]
is problem still continue ?
