### ISSUE TITLE
[Minor Issue] HumanWalkSnipe Spam on console despite being disabled

### ISSUE THREAD

**Issue by CreativiTimothy** [Necrobot-Private/NecroBot#229]
### Expected Behavior:
if the config `  "HumanWalkSnipeConfig": {
    "Enable": false,` is this,
then,
it doesn't spam the console screen with this: http://prntscr.com/cjxoqd
### Actual Behavior:
It spams the console screen. http://prntscr.com/cjxoqd
"found Pokemon but won't try to catch em all" or something like that
### Your config.json:
  "HumanWalkSnipeConfig": {
    "Enable": false,
    "DisplayPokemonList": true,
    "MaxDistance": 1500.0,
    "MaxEstimateTime": 300.0,
    "CatchEmAllMinBalls": 50,
    "TryCatchEmAll": true,
    "CatchPokemonWhileWalking": true,
    "SpinWhileWalking": true,
    "AlwaysWalkback": false,
    "SnipingScanOffset": 0.025,
    "WalkbackDistanceLimit": 300.0,
    "IncludeDefaultLocation": true,
    "UseSnipePokemonList": true,
    "MaxSpeedUpSpeed": 60.0,
    "AllowSpeedUp": true,
    "DelayTimeAtDestination": 10000,
    "UsePokeRadar": true,
    "UseSkiplagged": true,
    "UsePokecrew": true,
    "UsePokesnipers": true,
    "UsePokeZZ": true,
    "UsePokeWatcher": true,
    "UseFastPokemap": true,
    "UsePogoLocationFeeder": false
  },

Version: 9.9.9

**Comment by samuraitruong** [comment]
did you use any GUI?

**Comment by iwean** [comment]
"UseSnipePokemonList": true, 
...must false because the list from filter list, so log console still use it if it true

**Comment by CreativiTimothy** [comment]
@samuraitruong No. 

@iwean You're missing the point. Instead of taking the easy way out by disabling it, this is a minor bug still.

**Comment by samuraitruong** [comment]
I know why it happen, Will fix it tonight, very easy.

**Comment by samuraitruong** [comment]
Fixed :https://github.com/Necrobot-Private/NecroBot/pull/260
