### ISSUE TITLE
Starting Altitude Value Bug

### ISSUE THREAD

**Issue by BreakThroughSec** [Necrobot-Private/NecroBot#232]
Note: In the process of writing this I think that I got to the root of the issue. However, I do not have the best understanding of the code and don't have a good method to fix it. Here is essentially the fix:

file: "NecroBot\FeroxRev\Client.cs":
++ double altitude = session.ElevationService.GetElevation(Settings.DefaultLatitude, Settings.DefaultLongitude); //session is undefined here so this would cause a compile error.
++ Player.SetCoordinates(Settings.DefaultLatitude, Settings.DefaultLongitude, altitude);
-- Player.SetCoordinates(Settings.DefaultLatitude, Settings.DefaultLongitude, Settings.DefaultAltitude);

--------------

The very first altitude coordinate set is very different from all subsequent altitude positions. This can be a huge red flag for detecting NecroBot bots. For me, the first altitude position that is set is always 7.X and all other altitude positions are 3.X where X is a random 14 digits. It appears that the altitude is set with the following code:
function: "NecroBot\PoGo.NecroBot.Logic\Utils\LocationUtils.cs::UpdatePlayerLocationWithAltitude"
  double altitude = session.ElevationService.GetElevation(position.Latitude, position.Longitude);

It appears that the first time the altitude is set is in Client.cs, it makes the following call: Player.SetCoordinates(Settings.DefaultLatitude, Settings.DefaultLongitude, Settings.DefaultAltitude);
Apparently, the altitude that is being used is a config value and if you do not have it set in the config it chooses a number in the 7.X range.

You can reproduce this and see the changing altitude for yourself by simply adding a print statement in the following function:
"NecroBot\FeroxRev\Rpc\Player.cs::SetCoordinates"
  Console.WriteLine("updating coordinates: " + lat.ToString() + ", " + lng.ToString() + ", " + altitude.ToString() );
  *Note: you may need to include "using System;" at the top of the file

## My Config File:
  "LocationConfig": {
    "DisableHumanWalking": false,
    "StartFromLastPosition": true,
    "DefaultLatitude": 37.810741,
    "DefaultLongitude": -122.407243,
    "WalkingSpeedInKilometerPerHour": 4.1,
    "UseWalkingSpeedVariant": true,
    "WalkingSpeedVariant": 1.4,
    "ShowVariantWalking": false,
    "RandomlyPauseAtStops": true,
    "MaxSpawnLocationOffset": 10,
    "MaxTravelDistanceInMeters": 1000
  },

  "GPXConfig": {
    "UseGpxPathing": true,
    "GpxFile": "San_fran.gpx"
  },

Version: v9.9.9
Windows Version: 7 ultimate
What is affected (catch, transfer, favorite, GPX, evolve, recycle, snipe, human walk snipe, pokestops, powerup/levelup, other): altitude coordinate

**Comment by CreativiTimothy** [comment]
Excellent detailed bug report!
