### ISSUE TITLE
Gym

### ISSUE THREAD

**Issue by kokkie2012** [Necrobot-Private/NecroBot#237]
When the bot walks to a gym he cant take it over, this is what is say:
No action... This gym is defending by other color

Do you know how to fix this?

**Comment by ajns73** [comment]
@kokkie2012 Nothing is broken. All the bot can do is insert one of your pokemon into a gym that has an open slot. It cannot fight....or drive your to work...or make your coffee....or cure cancer.

**Comment by kokkie2012** [comment]
@ajns73 Ah ok, thanks for quik responding, than i will just wait until gym bot's are comming 👍

**Comment by CreativiTimothy** [comment]
@kokkie2012 They kinda break the game. You'll end with bots versus bots in the end
