### ISSUE TITLE
[Minor Feature Request] MinKmLimitedIncubator = value

### ISSUE THREAD

**Issue by CreativiTimothy** [Necrobot-Private/NecroBot#238]
This existed in a previous version of the NoxxDev bot. For some reason, someone removed it. The bot is semi-smart and prioritizes 5 and 10km eggs for limited incubators, but for the best value and efficient playing, it's usually best to only use limited incubators for 10km eggs. So the feature request in the minkm egg to use limited incubators on.

There's a temporary workaround which is to manually go into your account and put the limited incubators on your 10km eggs. Because of this, I suggest fixing all the other bugs before putting this in unless this is very easy to implement

**Comment by mo0ojava** [comment]
I implemented the feature way back, but there was a subsequent discussion against the feature and NoxxDev removed it.

**Comment by CreativiTimothy** [comment]
@mo0ojava Eggs hatch at the level you obtained them instead of level 20, which I believe was the discussion. However, that has nothing to do with using limited incubators for min km. The 10km eggs obtained at lvl 5 are going to stay there forever if the limited incubators aren't used on them. On the other hand, your incubators will disappear quickly if they're used for 2 and 5 km eggs. So the more freedom, the better :) If  could implement it again, that would be really nice. If we want to make everyone happy, maybe you can add an option called "EnableMinKm" = true/false

MinKmLimitedIncubator = x
EnableMinKm = true / false
