### ISSUE TITLE
Can I skip the killswitch message

### ISSUE THREAD

**Issue by alexbaas** [Necrobot-Private/NecroBot#240]
Now I just want to skip the whole killswitch message when starting the bot http://prntscr.com/ckbvgu is this possible, can't seem to find it in the settings. :/

**Comment by Silph-Road** [comment]
Hmm did you search the existing open/closed issues? The answer is out there.....

**Comment by CreativiTimothy** [comment]
This is in the wiki. Make a batch file (.bat)

NecroBot2.exe -killswitch="false"

**Comment by alexbaas** [comment]
@Silph-Road Ye I found it, just used a .bat file to bypass it with NecroBot2.exe -killswitch="false"

**Comment by CreativiTimothy** [comment]
I think we should put this in the README or at least refer to it, because many people have trouble with it. I did too. Or an easier way would be just to make an option instead of having to create a batch file
