### ISSUE TITLE
Still Not Filtering Sniping

### ISSUE THREAD

**Issue by ThatAce** [Necrobot-Private/NecroBot#244]
the bot didnt filter pokemon for sniping and it catches many regional and common pokemon where i didnt want that
can someone fix it 
  "PokemonToSnipe": {
    "Locations": [
      {
        "Latitude": 38.556807486461118,
        "Longitude": -121.2383794784546
      },
      {
        "Latitude": -33.859019,
        "Longitude": 151.213098
      },
      {
        "Latitude": 47.5014969,
        "Longitude": -122.0959568
      },
      {
        "Latitude": 51.5025343,
        "Longitude": -0.2055027
      }
    ],
    "Pokemon": [
      "bulbasaur",
      "ivysaur",
      "venusaur",
      "charmander",
      "charmeleon",
      "charizard",
      "squirtle",
      "wartortle",
      "blastoise",
      "arcanine",
      "poliwrath",
      "machamp",
      "slowbro",
      "chansey",
      "gyarados",
      "lapras",
      "ditto",
      "eevee",
      "vaporeon",
      "jolteon",
      "flareon",
      "porygon",
      "snorlax",
      "articuno",
      "zapdos",
      "moltres",
      "dratini",
      "dragonair",
      "dragonite",
      "mewtwo",
      "mew"
    ]
  },
  "PokemonToUseMasterball": [
    "articuno",
    "zapdos",
    "moltres",
    "mew",
    "mewtwo"
heres the config, and it still catch a fucking regional and Pidgey

**Comment by langit7** [comment]
"UsePokemonToNotCatchFilter": true,

  "PokemonsToIgnore": [
    "tauros",
    "kangaskhan",
    "mrMime"
  ],

or
    "UsePokemonSniperFilterOnly": true,

**Comment by jjskuld** [comment]
@ThatAce - You are correct that by default this should not be happening.  The default settings are not protecting you from sniping regional pokemon.  @langit7 is correct in how to change your settings to prevent this.

We'll change the defaults so this doesn't happen again in the future.
