### ISSUE TITLE
MSniper can't find "Active Necrobot" when use subpath parameter

### ISSUE THREAD

**Issue by Prawith** [Necrobot-Private/NecroBot#246]
I use Necrobot with subpath parameter for multi bot.
When I use this solution MSniper can't find "Active Necobot", 
but when I use Necorbot with no paramter MSniper can find "Active Necrobot".

Version: Necrobot V.1.0.0.0, MSniper V.1.0.6.3
Windows Version: Windows 10

**Comment by Prawith** [comment]
After test solution for this issue, I found if run Necrobot from CMD MSniper can't find "Active Necrobot".
If run Necrobot from double click from windows exploer MSniper can find "Active Necrobot".

**Comment by msx752** [comment]
can you try `start necrobot2.exe` in .bat

**Comment by Prawith** [comment]
Finally, I can find the solution for this issue.
I try start necrobot2.exe in my .cmd, MSniper can find my "Active Necorbot".

Thank @msx752
