### ISSUE TITLE
New Version didnt transfer and evolve pokemon...

### ISSUE THREAD

**Issue by siangs** [Necrobot-Private/NecroBot#25]
please help...its only cacth the pokemon but not transfer and evolve it...the previouse version much stable

**Comment by iwean** [comment]
May I see your config?

**Comment by msx752** [comment]
@siangs can you check your TransferActionDelay and  EvolveActionDelay values

try this one
> "DelayBetweenPlayerActions": 5000,
    "EvolveActionDelay": 300,
    "TransferActionDelay": 400,
    "RecycleActionDelay": 250,

**Comment by god0911** [comment]
I suggest "EvolveActionDelay": 10000.  (ms?)
In app, it shows an animation when user evolve Pokemon.
Keep a longer time is better.

**Comment by msx752** [comment]
@god0911  10000ms, so one evolve action takes 10sec,

**Comment by Silph-Road** [comment]
@siangs post back with feedback or issue will be closed
