### ISSUE TITLE
Can not transfer pokemon. Does power up instead

### ISSUE THREAD

**Issue by MaartenDeen** [Necrobot-Private/NecroBot#250]
Using the latest 1.0.0.2, but this also happened in 0.9.9.8.
When I view a pokemon, there are three buttons: transfer, evolve, upgrade. Above that is a line with Are you sure Are you sure Are you sure Yes Max (see screenshot, it looks like it is wrong).
Whatever I do, Necrobot always maxes the power up and logs this in the console:
[20:35:31] NidoranFemale    - CP: 149  IV: 77.35%   [Best CP: 136  IV: 77.35%]
[20:35:41] NidoranFemale    - CP: 161  IV: 77.35%   [Best CP: 136  IV: 77.35%]
[20:35:52] NidoranFemale    - CP: 174  IV: 77.35%   [Best CP: 136  IV: 77.35%]
I can not press transfer to transfer a pokemon by hand.

![transfererror](https://cloud.githubusercontent.com/assets/1825970/18724130/92cd89ae-803b-11e6-8eac-6a5596edc796.png)

**Comment by ajns73** [comment]
I was going to ask about this as well. I've had issue right along with it doing anything. I like the 3 options and want to use this GUI, but I cannot get to even function. Similar look to what you are seeing with the text overlap but when I click over "yes" and then check the console, nothing has happened. Any help would be appreciated. I can always use regular PokeEase.

**Comment by CreativiTimothy** [comment]
Temporarily, I use PokeNurse on github because it's a lot more reliable

**Comment by jjskuld** [comment]
This is a bug in the PokeEase version we are using. Let me check to see if it has been fixed already.
