### ISSUE TITLE
option of the time delay of potencial evolutions check

### ISSUE THREAD

**Issue by AnthonyWuChen** [Necrobot-Private/NecroBot#256]
so i can make the bot to check for like every 2 seconds of potencial evolutions

**Comment by wilsondgonzales** [comment]
there isn't a parameter to do that, however the scheduled interval is supposed to be every 5 pokestops. And depending on when you have usenearplayeraction to true that number might get randomized. This info is from the time of noxxdev

**Comment by Silph-Road** [comment]
That would lead to a lot of API calls and 2 seconds is rather short. What's the benefit?
