### ISSUE TITLE
Msniper won't create protocol

### ISSUE THREAD

**Issue by shinichi19** [Necrobot-Private/NecroBot#259]
Hi, i was run registerProtocol.bat but when i open msniper.com in browser and click msniper. It won't affect.
when i run registerProtocol.bat as administrator windows cannot find Msniper.

What should i do ?

Thanks
![image](https://cloud.githubusercontent.com/assets/20888035/18746430/83833bea-80f1-11e6-9f6d-58b6fb2398c8.png)

**Comment by msx752** [comment]
is msniper.exe in the same folder with registerProtocol.bat  ?

**Comment by shinichi19** [comment]
Yes, it is in the same folder. This is happen after execute removeProtocol.bat and i want replace the new version.

**Comment by msx752** [comment]
can you edit registerProtocol.bat like `msniper.exe -register`
or you can run msniper.exe with -register parameter

**Comment by shinichi19** [comment]
Protocol was succesfully registerd. But when open msniper.com and click msniper. It won't happen anyting.

**Comment by shinichi19** [comment]
Thanks i works.. i was run browser as administrator. And it's work.

Thank you
