### ISSUE TITLE
Always skip pokemons

### ISSUE THREAD

**Issue by butibitebat** [Necrobot-Private/NecroBot#261]
### Expected Behavior:
catch pokemon if met

### Actual Behavior:
skipped XXXX
eg. 
[23:27:21] (INFO) Skipped Vulpix
[23:27:21] (INFO) Skipped Caterpie
[23:27:29] (INFO) Skipped Vulpix
[23:27:29] (INFO) Skipped Caterpie
[23:27:35] (INFO) Skipped Vulpix
[23:27:35] (INFO) Skipped Caterpie
[23:27:43] (INFO) Skipped Vulpix
[23:27:43] (INFO) Skipped Caterpie
[23:27:50] (INFO) Skipped Vulpix
[23:27:50] (INFO) Skipped Caterpie
[23:27:52] (INFO) Pokemon spawn point data service connection established.
[23:27:55] (INFO) Skipped Vulpix
[23:27:55] (INFO) Skipped Caterpie
[23:28:02] (INFO) Skipped Vulpix
[23:28:02] (INFO) Skipped Caterpie
[23:28:09] (INFO) Skipped Vulpix
[23:28:09] (INFO) Skipped Caterpie
[23:28:09] (INFO) Skipped Poliwag

Version:
Windows Version: 10
What is affected (catch, transfer, favorite, GPX, evolve, recycle, snipe, human walk snipe, pokestops, powerup/levelup, other): catch

**Comment by sheang** [comment]
I have same issue here, is this need to set all pokemon in list ? 

 "Pokemon": [
      "venusaur",
      "charizard",
      "blastoise",
      "raichu",
      "nidoking",
      "nidoqueen",
      "clefable",
      "ninetales",
      "vileplume",
      "golduck",
      "primeape",
      "arcanine",
      "poliwrath",
      "alakazam",
      "machamp",
      "golem",
      "rapidash",
      "slowbro",
      "muk",
      "cloyster",
      "gengar",
      "exeggutor",
      "hitmonchan",
      "lickitung",
      "rhydon",
      "chansey",
      "starmie",
      "scyther",
      "magmar",
      "electabuzz",
      "jynx",
      "gyarados",
      "lapras",
      "vaporeon",
      "jolteon",
      "flareon",
      "porygon",
      "kabutops",
      "aerodactyl",
      "snorlax",
      "articuno",
      "zapdos",
      "moltres",
      "dragonite",
      "mewtwo",
      "mew"
    ]

**Comment by BoydTM** [comment]
check the parameter PokemonsToIgnore, necrobot usually skips the creatures from the list below ... ;)

**Comment by xuninho** [comment]
Me too.

  "PokemonsToLevelUp": [
    "venusaur",
    "charizard",
    "blastoise",
    "clefable",
    "muk",
    "chansey",
    "gyarados",
    "ditto",
    "snorlax",
    "articuno",
    "zapdos",
    "moltres",
    "dragonite",
    "mewtwo",
    "mew"
  ],
  "PokemonsToIgnore": [],
  "PokemonsTransferFilter": {
    "Golduck": {
      "KeepMinCp": 1800,
      "KeepMinIvPercentage": 95.0,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinOperator": "or",
      "KeepMinDuplicatePokemon": 1,
      "Moves": [
        [
          "waterGunFast",
          "hydroPump"

**Comment by BoydTM** [comment]
i believe that instead cleaning the list of PokemonsToIgnore you should try to use
    "UsePokemonToNotCatchFilter": false,

**Comment by kajibug** [comment]
Same issue here, except I have removed all pokemon from the PokemonsToIgnore list and have set UsePokemonToNotCatchFilter to false, just to see what happens.  Unfortunately it is still skipping the default pokemon that were in that list, even after restarting the bot

**Comment by BoydTM** [comment]
in that case its probably a bug, however in my case it always work well... (i never tried with completely cleaned list)

**Comment by kevinronu** [comment]
Me too, I try remove all pokemon from the PokemonsToIgnore list and have set UsePokemonToNotCatchFilter to false it does not work. Fix please.

**Comment by kajibug** [comment]
I was using a GPX path at the time, so I tried it without GPX and I got the same result.  Although its apparently not just the skipping the default list of ignored pokemon.  I did build a new config.json for v1.0.0.5 and I am getting the same result

**Comment by iwean** [comment]
@All 
Search on your config... I see by default 1.0.0.5 set it to true... please change to false
    "UsePokemonSniperFilterOnly": true,

**Comment by kajibug** [comment]
@iwean That seems to be the fix.  Setting UsePokemonSniperFilterOnly to false

**Comment by CreativiTimothy** [comment]
Yes, turn off both nottocatchfilter and sniperfilteronly

**Comment by jjskuld** [comment]
Hi everyone, yes we changed the default for your own safety because the previous defaults were allowing region-specific pokemon to be sniped, which is a big ban flag.

So set `UsePokemonSniperFilterOnly` to `false`.
