### ISSUE TITLE
Command-line shows wrong version

### ISSUE THREAD

**Issue by t0rzz** [Necrobot-Private/NecroBot#262]
As the title says, the command-line version of the app always shows version 1.0.0 although it's updated to v1.0.0.5.
I don't really care about that as I know it's updated, so it's a very minor "bug", or is it wanted as it is a minor update?

**Comment by hardknoxni69a** [comment]
i agree when loggin in it should says full version i was going to create a ticket the other day as it never shows the correct version 1.05 or 04 03 02 01 will always show 1.0 minor bug but its the little things probably just  simple text edit for the devs

THANK YOU DEVS

**Comment by hardknoxni69a** [comment]
1.0.0.6 still shows 1.0.0 by the way

**Comment by jjskuld** [comment]
Found another place we need to change.
