### ISSUE TITLE
(Request) Prioritize Using Up The 2K Eggs To Make Room For Better Eggs

### ISSUE THREAD

**Issue by hardknoxni69a** [Necrobot-Private/NecroBot#263]
Actual Behavior: Bot always uses the highest KM egg

Requested Behavior: I think a setting where we can use the 2K eggs first would be great. At the moment it will always use the 10 or 5KM egg so eventually we end up with nothing but 2K eggs.While walking a 10K egg we could have hatched five 2ks making room for more 10ks and 5Ks current setting makes it so we have nothing but 2ks all my accounts will have one 5k or one 10k and the rest are all 2ks. If we could go the other way we would get rid of the 2ks making our sack pick up the 10ks and 5ks, because we are always full with 2ks we lose out on a ton of better eggs. My friend would always have 10K eggs and i couldnt figure out why and hes like well how do you think your going to get them if your sack is always full with 2ks so I sat there that day and did all my 2Ks and got three 10Ks that day because I hatched five 2ks in the time that it took to hatch one 10K making room for my guy to pick up more eggs raising your chance of receiving better eggs. I really think this option would be great because once you clear out your 2Ks you can set value to High KM true and work off those awesome 10Ks you just collected

PrioritizeHighKMEggs: True (Would Do 10k>5K>2K)
PrioritizeHighKMEggs: False (Would Do 2K>5K>10K)

THANK YOU DEVS!!!

**Comment by CreativiTimothy** [comment]
Bots uses lowest km egg for permanent incubator. I eventually end up with 9 10km eggs just using the permanent incubator.

Bot uses highest km egg for limited incubators. Adding an option to enable / disable prioritize high km eggs would be nice. In addition, I had a feature request about adding min km egg for limited incubators. We can add both this and my feature request to make everyone happy plus an Enable / Disable option

**Comment by hardknoxni69a** [comment]
if this was the case i wouldnt have eight 2ks and one 5ks this is my current incubator settings all my bot accounts are like this they all have 8 2ks by the time i get to level 20 or so
    "UseEggIncubators": true,
    "UseLimitedEggIncubators": true,

**Comment by raquelcesar** [comment]
I'm having the same situation as hardknoxni69a.

Looking at the code (PoGo.NecroBot.Logic/Tasks/UseIncubatorsTask.cs) , I can see that the unlimited incubator indeed prefers the lowers km eggs **unless** it's the only incubator you have. If you only have one incubator (the unlimited one) in your inventory, it will prefer the long distance eggs. Perhaps that explains the different behaviors observed.
