### ISSUE TITLE
http://necrosocket.herokuapp.com/      (Pokemon despawned or wrong link format!)

### ISSUE THREAD

**Issue by BoydTM** [Necrobot-Private/NecroBot#264]
Version: Necro 1.0.0.5, Msniper 1.0.6.3

For every creature with undefined moves receiving "(SERVICE) Pokemon despawned or wrong link format!"

Is there still something wrong with mechanism or i should fix something on my side ?

**Comment by iwean** [comment]
I bet you snipe from mypogosnipers.com? Please ignore pokemon with undefined moves, because their receiving from old version bot.

**Comment by BoydTM** [comment]
undrestood - case closed

**Comment by Jdnp2005** [comment]
hijos de putaaa
