### ISSUE TITLE
NecroGUI UPGRADE -> YES and MAX button dose not work

### ISSUE THREAD

**Issue by xoira** [Necrobot-Private/NecroBot#266]
NecroGUI PokeEase Fork by NecroBot2 Team "UPGRADE -> YES and MAX" button dose not work
I tried to click YES and MAX button, but nothing happens in any case and any version

a)  Open in  NecroGUI
b)  direct open in Chrome  {version}\GUI\WebUi\PokeEase-jjskuld\index.html 
c)  direct open in Firefox {version}\GUI\WebUi\PokeEase-jjskuld\index.html 

Version:0.9.9.4-1.0.0.5
Windows Version: Windows10
![aaa](https://cloud.githubusercontent.com/assets/22394010/18785347/abaf1648-81d2-11e6-83fd-bba5dc01d4a7.png)

**Comment by Silph-Road** [comment]
https://github.com/Necrobot-Private/NecroBot/issues/250

**Comment by xoira** [comment]
Closed? Why?
TRANSFER and EVOLVE button works、but UPGRADE -> YES/MAX button dose not work
