### ISSUE TITLE
[SUGGESTION] - about auto re-login (logout/terminate)

### ISSUE THREAD

**Issue by IAMPYC** [Necrobot-Private/NecroBot#27]
hope add..... 
Tahnks :)

### Expected Behavior

Bot is able to recognize the new ban, and logout/terminate, re-login after a customize time period

### Actual Behavior

The bot failed to recognize the new type of ban, and keeps running even can't catch any pokemon, which might extend the softban time.

**Comment by rjcute123** [comment]
same here waiting for this one!
