### ISSUE TITLE
Capture Location

### ISSUE THREAD

**Issue by ajns73** [Necrobot-Private/NecroBot#273]
I don't remember this being there before (FYI, I have never even travelled to Japan). This is from an update to Android and iOS clients just now, 0.39:

![image](https://cloud.githubusercontent.com/assets/21206609/18805808/07e8dfac-81dd-11e6-8525-6edf175a8dfe.png)

**Comment by iwean** [comment]
Check your version.... is it 0.39 ?

**Comment by ShiroZhuge** [comment]
what version is it?  0.37.1 ?

**Comment by ajns73** [comment]
I am pretty thorough when I post. 0.39 (on iOS. I cannot 100% confirm on Android, but they have updated in lock step through .37)

**Comment by Silph-Road** [comment]
That's 1.90 or 0.39

**Comment by Silph-Road** [comment]
@ajns73 Can you test if .35 forces you to update? Or does it let you play. 
Were you sniping?

**Comment by ajns73** [comment]
![image](https://cloud.githubusercontent.com/assets/21206609/18805875/112019da-81df-11e6-9a55-023916e19bdd.png)

**Comment by ajns73** [comment]
It's not forced on iOS. I could have kept playing with old client.

**Comment by ajns73** [comment]
@Silph-Road More accurate answer to your question: I cannot test that hypothesis since my client was already 0.37.

**Comment by ajns73** [comment]
Every bot I run or influence is now dark and has been for 10 minutes.

**Comment by Silph-Road** [comment]
The first screenshot is from android, can you revert app to .35 and test for us?

**Comment by iwean** [comment]
On .35 (with Nox) still run and not have such a location for pokemon.

**Comment by ajns73** [comment]
@Silph-Road wish I could, but that device is out of my control right now.

**Comment by petpetpetvm** [comment]
the location been there in first versions (when the transfer button is all the way at the bottom)
but i'm not sure if this location thing affect snipping (cuz snipping = take pkm to original place, not sure which location it will show)

**Comment by ajns73** [comment]
I am trying to get that done now, but I am not hopeful at 23:00 local time

**Comment by ajns73** [comment]
I may have a phone (droid) that is still not updated from .35. I'll know in 5 minutes. If so, we'll launch .35 and see what happens.

**Comment by ajns73** [comment]
Sorry guys. Every client I have is .37. I can confirm no force from .37==>.39 yet, but @iwean is the only .35 client I know exists right now.

**Comment by hardknoxni69a** [comment]
.35 works

**Comment by hardknoxni69a** [comment]
i feel like any hour though it will be forced so be very very careful :-(

**Comment by ajns73** [comment]
@ Pardon my French, but it feels like Niantic is fuckin' with us. I think it was @samuraitruong that pointed out they could shut down all bot account now if they really wanted to. They just haven't wanted to. I think maybe they want to now,

**Comment by CreativiTimothy** [comment]
0.39 is the death update for anyone who snipes. Your friends will be able tell if you hacked or not.

I hope someone finds a way to make the text and map fail to load. Maybe an iOS and Android tweak to disable this? Yes, there's an option to just simply downgrade to the previous version, but your friends will be asking why the hell aren't you updating to the newest version? Anyone willing to work on this?
A temporary solution is to actually catch Pokemon in your area, legitimately via Twitter bot or snipe via Twitter bot. And when you friends ask where you caught that 2000CP Snorlax, show them that you caught it via Twitter bot. The problem is that your friends are probably going to ask where you got you perfect 100IV 3000CP Dragonite

**Comment by lllxin037** [comment]
just verified 5 minutes ago. one android wasn't enforced to 0.37. Still 0.35

**Comment by samuraitruong** [comment]
it was there from begining then they has perfomace issue. thay stripped it then now it com back. long distance snipe now should care about this

**Comment by hardknoxni69a** [comment]
I believe every single individual pokemon has a pokemon ID not like #3 venasaur but "97278499wjd7478w" and the map is showing on server that its pokemon ID comes from China. I doubt there will be spoofing capture location. And as of right this second .35 login is still available

**Comment by samuraitruong** [comment]
that what i tell before, they don't need to leaning machine or whatever technique to matching pattern, only 1 single SQL query on database to find out who are bot, but they don't do that, whey will do when they want or you reach level higher. 

0.35 doesn't show that it doesn't mean we safe. data in database and they own that data to analyze.
