### ISSUE TITLE
[request] unfavorite option on transferring

### ISSUE THREAD

**Issue by petpetpetvm** [Necrobot-Private/NecroBot#274]
### Expected Behavior:
transfer pokemons that not meet the minimum to keep

### Actual Behavior:
couldn't transfer pokemons that favorited

I think having an option for this will be great
exp : "unfavoritepokemon" : true/false (only unfavorite pokemons that the bot gonna transfer only and then transfer)

**Comment by vfuyong** [comment]
If this feature request gets implemented and bugged, I am not sure how many people will scream.

**Comment by Silph-Road** [comment]
Nope, this would cause a lot of problems that were fixed some versions ago. Do it manually.
