### ISSUE TITLE
[Bug?] Does not recycle

### ISSUE THREAD

**Issue by wilsondgonzales** [Necrobot-Private/NecroBot#275]
Might be something wrong with the scheduled interval for recycle. Watched the bot run for an hour without any recycle while inventory is full. 

"RecycleConfig": {
    "VerboseRecycling": true,
    "RecycleInventoryAtUsagePercentage": 90.0,
    "RandomizeRecycle": true,
    "RandomRecycleValue": 5,
    "TotalAmountOfPokeballsToKeep": 200,
    "TotalAmountOfPotionsToKeep": 70,
    "TotalAmountOfRevivesToKeep": 5,
    "TotalAmountOfBerriesToKeep": 55,
    "MaxPokeballsToKeep": 50
  },

Version 1.0.0.6

**Comment by Silph-Road** [comment]
Post config....

**Comment by Silph-Road** [comment]
What version? 
(Follow the issue template next time)

**Comment by wilsondgonzales** [comment]
bump

**Comment by Silph-Road** [comment]
cannot replicate issue, post your entire config, and are you still getting the same behavior?

**Comment by wilsondgonzales** [comment]
ill do more tests. i just watched 10 pokestops go by without any recycling happening

**Comment by Silph-Road** [comment]
It will only do a recycle if inventory level is at 90% storage, check your storage levels and if bot never reaches that level it won't recycle anything.
