### ISSUE TITLE
New client 0.39

### ISSUE THREAD

**Issue by tuxfrw** [Necrobot-Private/NecroBot#276]
Region: Brazil
Platform: Android 0.37.1
no force update to 0.39.0

**Comment by Danny-0815** [comment]
> Region: Brazil
> Platform: Android 0.39.0
> no force update to 0.39.0

... Why would get a force update to 0.39, when you're already on 0.39?

**Comment by tuxfrw** [comment]
I was using version 0.37.1. I entered and left the game without any updates. Then I decided to update manually.

**Comment by langit7** [comment]
any changelog for latest vers?

**Comment by iwean** [comment]
Ah... that's not new, remember this map when you want transfered to profesor?
It's already there from the beginning :smile: 
...
![screenshot_226](https://cloud.githubusercontent.com/assets/4365551/18809909/c36b4a14-82b2-11e6-921a-dc975907f014.jpg)

**Comment by ajns73** [comment]
Region: US
Platform: Android 0.39.1
no force update to 0.39.1

Says: "minor text fixes" Android only. No force.

**Comment by kalamera** [comment]
force update from 0.37 to 0.39.1 this morning :(

**Comment by ShiroZhuge** [comment]
[force update from 0.37 to 0.39.1](http://imgur.com/a/zkqb3)

**Comment by jjskuld** [comment]
Thanks for the report. See also #146 and #285
