### ISSUE TITLE
[Feature request]Collect coins after x gym deployed

### ISSUE THREAD

**Issue by sevenzsu** [Necrobot-Private/NecroBot#278]
This has been discussed before but might get drop. With the latest gym deployment feature, it would be nice to collect the coins after x gym deployment if there are coins available to be collected. Taking the gym without collecting the coins make it not so human. When can we have this long waiting feature?

**Comment by PenzRules** [comment]
Yep, and what's also important would be healing of the monsters.
No use of a second bot only account if they're all dead.
And yes, running to the gyms without deploying is also not human like.

**Comment by jambonmcyeah** [comment]
I agree, this should definitely be added

**Comment by samuraitruong** [comment]
implemented in gym part
