### ISSUE TITLE
[Bug] Bot not coming back to farming zone

### ISSUE THREAD

**Issue by Yinyinka** [Necrobot-Private/NecroBot#279]
### Your config.json:
  "LocationConfig": {
    "DisableHumanWalking": false,
    "StartFromLastPosition": false,
    "DefaultLatitude": 10.775274,
    "DefaultLongitude": 106.706289,
    "WalkingSpeedInKilometerPerHour": 39.0,
    "UseWalkingSpeedVariant": true,
    "WalkingSpeedVariant": 10.2,
    "ShowVariantWalking": false,
    "RandomlyPauseAtStops": true,
    "MaxSpawnLocationOffset": 10,
    "MaxTravelDistanceInMeters": 300
  },
  "TelegramConfig": {
    "UseTelegramAPI": false,
    "TelegramAPIKey": null,
    "TelegramPassword": null
  },
  "GPXConfig": {
    "UseGpxPathing": false,
    "GpxFile": "GPXPath.GPX"
  },
  "SnipeConfig": {
    "UseSnipeLocationServer": true,
    "SnipeLocationServer": "localhost",
    "SnipeLocationServerPort": 16969,
    "GetSniperInfoFromPokezz": false,
    "GetOnlyVerifiedSniperInfoFromPokezz": true,
    "GetSniperInfoFromPokeSnipers": false,
    "GetSniperInfoFromPokeWatchers": false,
    "GetSniperInfoFromSkiplagged": false,
    "MinPokeballsToSnipe": 20,
    "MinPokeballsWhileSnipe": 0,
    "MinDelayBetweenSnipes": 1000,
    "SnipingScanOffset": 0.005,
    "SnipeAtPokestops": false,
    "ActivateMSniper": true,
    "SnipeIgnoreUnknownIv": false,
    "UseTransferIvForSnipe": false,
    "SnipePokemonNotInPokedex": false,
    "UseSnipeLimit": false,
    "SnipeRestSeconds": 1,
    "SnipeCountLimit": 39
  },
  "HumanWalkSnipeConfig": {
    "Enable": true,
    "DisplayPokemonList": true,
    "MaxDistance": 1500.0,
    "MaxEstimateTime": 900.0,
    "CatchEmAllMinBalls": 50,
    "TryCatchEmAll": true,
    "CatchPokemonWhileWalking": true,
    "SpinWhileWalking": true,
    "AlwaysWalkback": true,
    "SnipingScanOffset": 0.025,
    "WalkbackDistanceLimit": 3000.0,
    "IncludeDefaultLocation": true,
    "UseSnipePokemonList": true,
    "MaxSpeedUpSpeed": 60.0,
    "AllowSpeedUp": true,
    "DelayTimeAtDestination": 10000,
    "UsePokeRadar": true,
    "UseSkiplagged": true,
    "UsePokecrew": true,
    "UsePokesnipers": true,
    "UsePokeZZ": true,
    "UsePokeWatcher": true,
    "UseFastPokemap": true,
    "UsePogoLocationFeeder": false

Version: 1.0.0.6

**Comment by jjskuld** [comment]
Dup of #91
