### ISSUE TITLE
DeviceConfig in auth.json 

### ISSUE THREAD

**Issue by god0911** [Necrobot-Private/NecroBot#28]
How to set the DeviceConfig for iPhone.
I found some info from other website.
In previous version, It's work well.
In this version, It keeps saying: input GoogleUsername & password.

### My auth.json
```
"DeviceConfig": {
    "DevicePackageName": "iPhone 6 plus",
    "DeviceId": "XXXXXXXXXXXX",
    "DeviceBrand": "apple",
    "DeviceModel": "iPhone",
    "DeviceModelBoot": iPhone7,1", <--------Is it right?
    "HardwareManufacturer": "apple",
    "HardwareModel": "N66AP",
    "FirmwareBrand": "iPhone OS",
    "FirmwareType": "9.3.1",
  }
```

### Other Information
Version: 09811
Windows Version: win81
Can't start after update the new DeviceConfig.

**Comment by iwean** [comment]
"DevicePackageName": "iPhone 6 plus", <<< change to "custom"

**Comment by evetaku** [comment]
change in  "DeviceId": "XXXXXXXXXXXX", you can check with Pok Device Info in play store

**Comment by god0911** [comment]
@evetaku , of cause, I input it.
I use the DeviceConfig then show the message.

###new config
'''
"DeviceConfig": {
    "DevicePackageName": "custom",
    "DeviceId": "XXXXXXXXXXXXX", <~~~I check the device Id of my cell.
    "DeviceBrand": "apple",
    "DeviceModel": "iPhone",
    "DeviceModelBoot": iPhone7,1",  <~~~~I think it's  the problem, but I don't know the right string.
    "HardwareManufacturer": "apple",
    "HardwareModel": "N66AP",
    "FirmwareBrand": "iPhone OS",
    "FirmwareType": "9.3.1",
  }
'''
![screen shot 2016-09-08 at 10 40 57](https://cloud.githubusercontent.com/assets/5134101/18353741/ceadbf78-7615-11e6-931c-0ecf0e581ae0.png)
![screen shot 2016-09-08 at 10 41 13](https://cloud.githubusercontent.com/assets/5134101/18353753/dc0f5f1e-7615-11e6-8dca-0d5eaa2838ac.png)

**Comment by iwean** [comment]
"DeviceModelBoot": iPhone7,1", <<<< change to just "iPhone"

**Comment by jjskuld** [comment]
OK, here's the easiest method with v0.9.8.5. Coincidentally I just put in proper support for this.

1) First set the ```DevicePlatform``` to ```"ios"```

```
  "DeviceConfig": {
    "DevicePlatform": "ios",
    "DevicePackageName": "random"
  }
```

2) This is going to tell the bot to generate your configuration randomly for an iOS device.  After you start the bot up it should look like this:

```
  "DeviceConfig": {
    "DevicePlatform": "ios",
    "DevicePackageName": "random",
    "DeviceId": "7a8ef53ecaddc46f912f20ca32fb2a5512e19a9a",
    "AndroidBoardName": null,
    "AndroidBootloader": null,
    "DeviceBrand": "Apple",
    "DeviceModel": "iPad",
    "DeviceModelIdentifier": null,
    "DeviceModelBoot": "iPad5,3",
    "HardwareManufacturer": "Apple",
    "HardwareModel": "J81AP",
    "FirmwareBrand": "iPhone OS",
    "FirmwareTags": null,
    "FirmwareType": "9.1",
    "FirmwareFingerprint": null
  }
```
3) Now you have an idea of all the fields you need to fill in/customize.
4) Now change your ```DevicePackageName``` to ```"custom"``` and enter your custom data.

**Comment by jjskuld** [comment]
@god0911 Your JSON is malformed and missing a quotation mark

```
"DeviceModelBoot": iPhone7,1"
```

should be
```
"DeviceModelBoot": "iPhone7,1"
```

**Comment by god0911** [comment]
@jjskuld @iwean tks for help.
After update the right deviceConfig, I found the problem is at DeviceId.

I check the id on my cellPhone such as "GL0R67KN4RS".
However, I got the error.
I was wondering if the pattern should be [0-9A-Za-z].

please check.
![screen shot 2016-09-09 at 10 22 35](https://cloud.githubusercontent.com/assets/5134101/18373653/ab5fd016-7678-11e6-826b-806df54e2f53.png)

**Comment by jjskuld** [comment]
It should be a hex string so the existing regex is correct.  I think you don't have the right device id.
