### ISSUE TITLE
(Question) Setting up my own sniper locations

### ISSUE THREAD

**Issue by PenzRules** [Necrobot-Private/NecroBot#281]
Sorry, if this is the wrong place, but https://discord.gg/7FWyWVp gives me only a blank page, tried twice.
What I want to do is let the bot sniper at given locations without asking pokezz first. I've made a decent list of locations where multiple pokemon were catched when found via pokezz. As pokemon often spawn at the same location this should be useful. But the bot doesn't care about the list in the config as shown below. Tested with 0.9.6 and 1.0.0.6. I mean it doesn't even log anything about sniping.
### Expected Behavior:

Check all given Locations for (all pokemon or all pokemon in sniper filter) and snipe all pokemons at only the first location, pause for 20 secs and continue with the next location. After last location, pause sniping for 15 minutes. And most important: continue doing other things.
### Actual Behavior:

No snipes at all, not even trying. What am I missing? Is there a switch to enable the list of locations or is it just a stub?
On the other hand there is human walk sniper:
It seems to only show fake data. I live in Bielefeld, Germany, if that matters. And worst is that the bot stands still for minutes sometimes checking sniper data or something. It never walksniped anything.
It effectively feels like wasting time by hunting pokemon that just aren't there, so I turned it off.
### Your config.json:

  "SnipeConfig": {
    "UseSnipeLocationServer": true,
    the rest is all set to false

```
  "PokemonToSnipe": {
    "Locations": [
      {
        "Latitude": *.********,
        "Longitude": *.********
      },
      {
        "Latitude": *.********,
        "Longitude": *.********
      },
```

**Comment by langit7** [comment]
"SnipeAtPokestops": true,

**Comment by PenzRules** [comment]
Well, thank you, but "SnipeAtPokestops": true still causes no snipes. Glad, I don't want to snipe Pokestops, just Pokemon.
Now I tried it with activating sniper info from pokezz.
Guess, what it does. My settings are:

  "SnipeConfig": {
    "UseSnipeLocationServer": true,
    "SnipeLocationServer": "localhost",
    "SnipeLocationServerPort": 16969,
    "GetSniperInfoFromPokezz": true,
    "GetOnlyVerifiedSniperInfoFromPokezz": true,
    "GetSniperInfoFromPokeSnipers": false,
    "GetSniperInfoFromPokeWatchers": false,
    "GetSniperInfoFromSkiplagged": false,
    "MinPokeballsToSnipe": 20,
    "MinPokeballsWhileSnipe": 0,
    "MinDelayBetweenSnipes": 60000,
    "SnipingScanOffset": 0.005,
    "SnipeAtPokestops": false,
    "ActivateMSniper": false,
    "SnipeIgnoreUnknownIv": false,
    "UseTransferIvForSnipe": false,
    "SnipePokemonNotInPokedex": false,
    "UseSnipeLimit": true,
    "SnipeRestSeconds": 900,
    "SnipeCountLimit": 39

But it snipes again and again and again at different locations WITOUT making pauses AND doing nothing alse till I closed the bot.

I ven looked in the source and I cant remember reading SnipeRestSeconds or MinDelayBetweenSnipes in SnipeTask.

**Comment by PenzRules** [comment]
So, I tried DelayBetweenPlayerActions. It works but slws down everything. Then I found the mistake:
If SnipeCountLimit is set to 1, it will only snipe once every x seconds given by SnipeRestSeconds.
So it walks to the next pokestop and then checks DelayBetweenSnipes before repeating the steps.
Best of that is that it will actually snipe multiple pokemon without mentionig the delay if they are within same location.

So as a summary I must say: Please set the default SnipeCountLimit to 1.
Is this set to 39 because a softban occures at the 40th pokemon or why is this preset so high?

**Comment by jjskuld** [comment]
This is an old bug, but the default snipe limit is definitely too big.. we should decrease it and maybe add more logging so it's clear what's going on.
