### ISSUE TITLE
[Request] easy enable/disable basic options

### ISSUE THREAD

**Issue by Jannetje1972** [Necrobot-Private/NecroBot#282]
I think it would be nice if there would be a easy way to enable or disable basic functions like...
catch pokemon, transfer pokemon, evolve pokemon, recycle items, snipe pokemon, pokestops

atm I would like to disable the snipe option due to current returned function of cought location in the original client ... but no clue how to put that in the current config :(

**Comment by langit7** [comment]
"SnipeAtPokestops": false,
"UsePokemonSniperFilterOnly": true,

**Comment by PenzRules** [comment]
Do disable sniping completely just set this:
  "SnipeConfig": {
    "UseSnipeLocationServer": false,
    "ActivateMSniper": false,

HumanWalkSnipe you can leave on. Don't know if it works, but will definitely not snipe accross continents.

The easiest method to edit the config so far is using Notepad++ with a plugin named JSTool.
This way just open the config and press Strg+Alt+J for a nice tree overwiev. This will not corrupt the file.

**Comment by Jannetje1972** [comment]
thx ... I'll have a go with it
