### ISSUE TITLE
Necrobot2 GUI bug

### ISSUE THREAD

**Issue by gjimenezf** [Necrobot-Private/NecroBot#288]
When I want to check the moveset or upgrade a pokemon with 100 IV renamed, after I click on the pokemon it does not show me anything. If I click into a pokemon with a non 100 IV and default name I  dont have the same issue.

Necrobot GUI and console latest 1.0.6 versions

**Comment by Silph-Road** [comment]
why are you still botting??


__**DO NOT BOT RIGHT NOW**__
__**Why:**__
1. The Official Apps forced to use 0.39.0 API.
2. All bots are .35 API
3. Niantic will let you connect with not authorized .35 API
4. Now they know 100% you are bot account....... BAN.

You are also giving them info that can be used to ban everyone!

**Comment by gjimenezf** [comment]
Not using the bot today, I notice this bug somedays before.
