### ISSUE TITLE
Lmao I wish you good luck cheating in Pokemon Go now SmartPeople!

### ISSUE THREAD

**Issue by Flyingboots2** [Necrobot-Private/NecroBot#291]
Well it looks like we didn't win, all of you will have the satisfaction of cheating in Pokemon Go again thanks to the cracked API update.

I can't take down a gym, cuz my level is too low and I have crap pokemon's. :-(
But as a sore loser that I am.... I will come and complain on GitHub like a true B_____!

**Comment by Raverbunny** [comment]
Hello Mr poor coder 
Can you please fix the memory leak in your crap game, and please bring back all the players that left 
Kthxbai

**Comment by Flyingboots2** [comment]
Rofl see ya don't let the door hit you on the way out you god damn filthy cheater I guarantee no one will miss you and FYI we still make over 2 million dollars a day! ;)

**Comment by Schweng** [comment]
Jep, still no one cares, how much money you make a day.

If the API is cracked, we will bot. If not, we will deinstall the game and play another one. Simple as that. If you feel like the king on the hill, go on. We dont care about you.

**Comment by Necrobotico** [comment]
@Flyingboots2 

PATHETIC.....

This guy must have really crap Pokemons..... can't take down a gym??

He must have just read a news report on captcha popups!
So, uninformed, the new update captcha, was decoded and a bypass was cracked like a month ago......
:-D

Why do you think everything still works!!!! 

Go catch some Pidgeys while you ponder what just happened...
LMAO nice try! :-D

**Comment by Necrobotico** [comment]
@Raverbunny @Schweng @OverlordQ @Flyingboots2  

1. Captcha was discovered and dealt with in .35 update....
2. You can still play on root devices and spoof....
3. This is old news....

But lets all rejoice, know that there is one guy @Flyingboots2 , who is having such a tough time playing, that he has to resort to complaining on Github on a repo that isn't even active.....

Enjoy catching Pidgeys and rattatas.....!!!!!! 

LMAO

See, what must have happened is that, most legit players have now leveled up to 30, so now whenever @Flyingboots2 goes to a gym and see's high level and high CP Pokemons he thinks its cuz of botting, but the funny thing is that those accounts are legit, (game has been out for months now......)

KEEP COMPLAING YOU LITTLE BABY!!!! 
_wahhhh wahhhh_ 
^ that's all I read.... whining.... LMAO
