### ISSUE TITLE
(INFO) Skipped ??

### ISSUE THREAD

**Issue by heroes1412** [Necrobot-Private/NecroBot#298]
What is that? not catch when walking???
[09:41:42] (INFO) Skipped Eevee
[09:41:42] (INFO) Skipped Sandshrew
[09:41:42] (INFO) Skipped Rattata
[09:41:42] (INFO) Skipped Paras
[09:41:42] (INFO) Skipped Rattata
[09:41:42] (INFO) Skipped Spearow
[09:41:42] (INFO) Skipped Pidgey
[09:41:42] (INFO) Skipped Sandshrew

**Comment by jjskuld** [comment]
Change the following
```
"PokemonsToIgnore": [
    "caterpie",
    "weedle",
    "pidgey",
    "rattata",
    "spearow",
    "zubat",
    "doduo"
  ],
``` 
to
```
"PokemonsToIgnore": [],
```

Next release will have this as the default so I don't have to answer this question again lol!

**Comment by heroes1412** [comment]
i changed this value to "PokemonsToIgnore": [],
but, i still see many Skip information???

**Comment by jjskuld** [comment]
Also try setting
```
"UsePokemonToNotCatchFilter": false,
```

**Comment by jjskuld** [comment]
When we get multiple questions about this, it means that this should be treated as a bug. I'm going to change the defaults so that no pokemon are skipped.

**Comment by jjskuld** [comment]
Recommended default config now is:
```
"PokemonsToIgnore": [
  "tauros",
  "mrmime",
  "kangaskhan",
  "farfetchd"
],
```
And
```
"UsePokemonToNotCatchFilter": true,
"UsePokemonSniperFilterOnly": false,
```
This allows all pokemon to be sniped by default, except for the regional pokemon.  Advanced users can customize the snipe list and enable the snipe filter.
