### ISSUE TITLE
2.0.0.12 skipped all pokemons

### ISSUE THREAD

**Issue by god0911** [Necrobot-Private/NecroBot#299]
### Expected Behavior:
pokemon number 145/200
catch pokemon

### Actual Behavior:
skipped all pokemon

### Your config.json:
```
"PokemonConfig": {
    "CatchPokemon": true,

"PokemonsToIgnore": [],
```
Version: 2.0.0.12

any idea what happened?

**Comment by god0911** [comment]
My bad.

"UsePokemonSniperFilterOnly set to false

is OK now.

**Comment by jjskuld** [comment]
Dup #298
