### ISSUE TITLE
0.9.7.2 System.ArgumentNullException: Value cannot be null. Parameter name: ptr

### ISSUE THREAD

**Issue by BoydTM** [Necrobot-Private/NecroBot#3]
Tried to move config from noxx necro. First copy of the config.json and after each parameter value one by one. Same error
### Actual Behavior
(INFO) System.ArgumentNullException: Value cannot be null.
Parameter name: ptr
   at System.Runtime.InteropServices.Marshal.GetDelegateForFunctionPointer(IntPtr ptr, Type t)
   at PokemonGo.RocketAPI.Helpers.Crypt.LoadFunction[T](String dllPath, String functionName) in D:\Github_SourceTree\NecroBot\FeroxRev\PokemonGo.RocketAPI\Helpers\Crypt.cs:line 33
   at PokemonGo.RocketAPI.Helpers.Crypt..ctor() in D:\Github_SourceTree\NecroBot\FeroxRev\PokemonGo.RocketAPI\Helpers\Crypt.cs:line 14
   at PokemonGo.RocketAPI.Helpers.RequestBuilder..ctor(String authToken, AuthType authType, Double latitude, Double longitude, Double altitude, ISettings settings, AuthTicket authTicket) in D:\Github_SourceTree\NecroBot\FeroxRev\PokemonGo.RocketAPI\Helpers\RequestBuilder.cs:line 57
   at PokemonGo.RocketAPI.Rpc.BaseRpc.get_RequestBuilder() in D:\Github_SourceTree\NecroBot\FeroxRev\PokemonGo.RocketAPI\Rpc\BaseRpc.cs:line 14
   at PokemonGo.RocketAPI.Rpc.Login.<SetServer>d__4.MoveNext() in D:\Github_SourceTree\NecroBot\FeroxRev\PokemonGo.RocketAPI\Rpc\Login.cs:line 62
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at PokemonGo.RocketAPI.Rpc.Login.<DoLogin>d__3.MoveNext() in D:\Github_SourceTree\NecroBot\FeroxRev\PokemonGo.RocketAPI\Rpc\Login.cs:line 41
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PoGo.NecroBot.Logic.State.LoginState.<Execute>d__0.MoveNext() in D:\Github_SourceTree\NecroBot\PoGo.NecroBot.Logic\State\LoginState.cs:line 35

### Your config.json
{
  "ConsoleConfig": {
    "TranslationLanguageCode": "en",
    "StartupWelcomeDelay": false,
    "AmountOfPokemonToDisplayOnStart": 10,
    "DetailedCountsBeforeRecycling": true
  },
  "UpdateConfig": {
    "CheckForUpdates": false,
    "AutoUpdate": false,
    "TransferConfigAndAuthOnUpdate": true
  },
  "WebsocketsConfig": {
    "UseWebsocket": true,
    "WebSocketPort": 14251
  },
  "LocationConfig": {
    "DisableHumanWalking": false,
    "StartFromLastPosition": true,
    "DefaultLatitude": 37.80921,
    "DefaultLongitude": -122.409997,
    "WalkingSpeedInKilometerPerHour": 9.16,
    "UseWalkingSpeedVariant": true,
    "WalkingSpeedVariant": 1.2,
    "ShowVariantWalking": false,
    "RandomlyPauseAtStops": true,
    "MaxSpawnLocationOffset": 10,
    "MaxTravelDistanceInMeters": 1000
  },
  "TelegramConfig": {
    "UseTelegramAPI": false,
    "TelegramAPIKey": null,
    "TelegramPassword": null
  },
  "GPXConfig": {
    "UseGpxPathing": false,
    "GpxFile": "GPXPath.GPX"
  },
  "SnipeConfig": {
    "UseSnipeLocationServer": false,
    "SnipeLocationServer": "localhost",
    "SnipeLocationServerPort": 16969,
    "GetSniperInfoFromPokezz": false,
    "GetOnlyVerifiedSniperInfoFromPokezz": false,
    "GetSniperInfoFromPokeSnipers": false,
    "GetSniperInfoFromPokeWatchers": false,
    "GetSniperInfoFromSkiplagged": false,
    "MinPokeballsToSnipe": 20,
    "MinPokeballsWhileSnipe": 0,
    "MinDelayBetweenSnipes": 60000,
    "SnipingScanOffset": 0.005,
    "SnipeAtPokestops": false,
    "SnipeIgnoreUnknownIv": false,
    "UseTransferIvForSnipe": false,
    "SnipePokemonNotInPokedex": false,
    "UseSnipeLimit": true,
    "SnipeRestSeconds": 600,
    "SnipeCountLimit": 39
  },
  "HumanWalkSnipeConfig": {
    "Enable": true,
    "DisplayPokemonList": true,
    "MaxDistance": 1500.0,
    "MaxEstimateTime": 360.0,
    "CatchEmAllMinBalls": 50,
    "TryCatchEmAll": true,
    "CatchPokemonWhileWalking": false,
    "SpinWhileWalking": false,
    "AlwaysWalkback": false,
    "SnipingScanOffset": 0.025,
    "WalkbackDistanceLimit": 1500.0,
    "IncludeDefaultLocation": true,
    "UsePokeRadar": false,
    "UseSkiplagged": false,
    "UseSnipePokemonList": false,
    "MaxSpeedUpSpeed": 60.0,
    "AllowSpeedUp": true,
    "DelayTimeAtDestination": 10000,
    "UseFastPokemap": true,
    "UsePogoLocationFeeder": false
  },
  "PokeStopConfig": {
    "UsePokeStopLimit": true,
    "PokeStopLimit": 1998,
    "PokeStopLimitMinutes": 1470
  },
  "PokemonConfig": {
    "CatchPokemon": true,
    "DelayBetweenPokemonCatch": 8200,
    "UseCatchLimit": true,
    "CatchPokemonLimit": 998,
    "CatchPokemonLimitMinutes": 1470,
    "UseIncenseConstantly": false,
    "UseEggIncubators": true,
    "UseLimitedEggIncubators": false,
    "UseLuckyEggConstantly": false,
    "UseLuckyEggsMinPokemonAmount": 30,
    "UseLuckyEggsWhileEvolving": false,
    "UseBerriesMinCp": 1000,
    "UseBerriesMinIv": 90.0,
    "UseBerriesBelowCatchProbability": 0.2,
    "UseBerriesOperator": "or",
    "MaxBerriesToUsePerPokemon": 6,
    "TransferWeakPokemon": false,
    "TransferDuplicatePokemon": true,
    "TransferDuplicatePokemonOnCapture": false,
    "RenamePokemon": false,
    "RenameOnlyAboveIv": false,
    "RenameTemplate": "{1}_{0}",
    "FavoriteMinIvPercentage": 100.0,
    "AutoFavoritePokemon": true,
    "MaxPokeballsPerPokemon": 6,
    "UseGreatBallAboveCp": 1000,
    "UseUltraBallAboveCp": 1250,
    "UseMasterBallAboveCp": 1500,
    "UseGreatBallAboveIv": 85.0,
    "UseUltraBallAboveIv": 95.0,
    "UseGreatBallBelowCatchProbability": 0.2,
    "UseUltraBallBelowCatchProbability": 0.1,
    "UseMasterBallBelowCatchProbability": 0.05,
    "AutomaticallyLevelUpPokemon": false,
    "OnlyUpgradeFavorites": true,
    "UseLevelUpList": true,
    "AmountOfTimesToUpgradeLoop": 5,
    "GetMinStarDustForLevelUp": 5000,
    "LevelUpByCPorIv": "iv",
    "UpgradePokemonCpMinimum": 1000.0,
    "UpgradePokemonIvMinimum": 100.0,
    "UpgradePokemonMinimumStatsOperator": "and",
    "EvolveAboveIvValue": 100.0,
    "EvolveAllPokemonAboveIv": false,
    "EvolveAllPokemonWithEnoughCandy": true,
    "EvolveKeptPokemonsAtStorageUsagePercentage": 90.0,
    "KeepPokemonsThatCanEvolve": false,
    "KeepMinCp": 300,
    "KeepMinIvPercentage": 100.0,
    "KeepMinLvl": 6,
    "KeepMinOperator": "and",
    "UseKeepMinLvl": false,
    "PrioritizeIvOverCp": false,
    "KeepMinDuplicatePokemon": 1,
    "UsePokemonToNotCatchFilter": true,
    "UsePokemonSniperFilterOnly": false,
    "DumpPokemonStats": true
  },
  "RecycleConfig": {
    "VerboseRecycling": true,
    "RecycleInventoryAtUsagePercentage": 90.0,
    "RandomizeRecycle": false,
    "RandomRecycleValue": 5,
    "TotalAmountOfPokeballsToKeep": 190,
    "TotalAmountOfPotionsToKeep": 10,
    "TotalAmountOfRevivesToKeep": 12,
    "TotalAmountOfBerriesToKeep": 55,
    "MaxPokeballsToKeep": 50
  },
  "CustomCatchConfig": {
    "EnableHumanizedThrows": true,
    "EnableMissedThrows": true,
    "ThrowMissPercentage": 17,
    "NiceThrowChance": 40,
    "GreatThrowChance": 30,
    "ExcellentThrowChance": 10,
    "CurveThrowChance": 90,
    "ForceGreatThrowOverIv": 90.0,
    "ForceExcellentThrowOverIv": 95.0,
    "ForceGreatThrowOverCp": 2000,
    "ForceExcellentThrowOverCp": 2500
  },
  "PlayerConfig": {
    "DelayBetweenPlayerActions": 7650,
    "EvolveActionDelay": 15500,
    "TransferActionDelay": 7000,
    "RecycleActionDelay": 5100,
    "RenamePokemonActionDelay": 600,
    "UseNearActionRandom": true,
    "AutoCompleteTutorial": false,
    "DesiredNickname": "Nickname",
    "DesiredGender": "Male",
    "DesiredStarter": "Squirtle"
  },
  "SoftBanConfig": {
    "FastSoftBanBypass": false
  },
  "GoogleWalkConfig": {
    "UseGoogleWalk": true,
    "DefaultStepLength": 1.3,
    "GoogleHeuristic": "walking",
    "GoogleAPIKey": "XXX",
    "Cache": false
  },
  "YoursWalkConfig": {
    "UseYoursWalk": false,
    "YoursWalkHeuristic": "bicycle"
  },
  "ItemRecycleFilter": [
    {
      "Key": "itemUnknown",
      "Value": 0
    },
    {
      "Key": "itemLuckyEgg",
      "Value": 200
    },
    {
      "Key": "itemIncenseOrdinary",
      "Value": 100
    },
    {
      "Key": "itemIncenseSpicy",
      "Value": 100
    },
    {
      "Key": "itemIncenseCool",
      "Value": 100
    },
    {
      "Key": "itemIncenseFloral",
      "Value": 100
    },
    {
      "Key": "itemTroyDisk",
      "Value": 100
    },
    {
      "Key": "itemXAttack",
      "Value": 100
    },
    {
      "Key": "itemXDefense",
      "Value": 100
    },
    {
      "Key": "itemXMiracle",
      "Value": 100
    },
    {
      "Key": "itemSpecialCamera",
      "Value": 100
    },
    {
      "Key": "itemIncubatorBasicUnlimited",
      "Value": 100
    },
    {
      "Key": "itemIncubatorBasic",
      "Value": 100
    },
    {
      "Key": "itemPokemonStorageUpgrade",
      "Value": 100
    },
    {
      "Key": "itemItemStorageUpgrade",
      "Value": 100
    }
  ],
  "PokemonsNotToTransfer": [
    "ditto",
    "articuno",
    "zapdos",
    "moltres",
    "dragonite",
    "mewtwo",
    "mew"
  ],
  "PokemonsToEvolve": [
    "caterpie",
    "weedle",
    "pidgey",
    "spearow",
    "zubat",
    "psyduck",
    "tentacool",
    "venonat",
    "poliwag",
    "bulbasaur",
    "goldeen",
    "nidoranMale",
    "nidoranFemale",
    "rattata"
  ],
  "PokemonsToLevelUp": [
    "ditto",
    "articuno",
    "zapdos",
    "moltres",
    "dragonite",
    "mewtwo",
    "mew"
  ],
  "PokemonsToIgnore": [
    "golduck",
    "tentacruel",
    "psyduck",
    "tentacool",
    "pidgeotto",
    "pidgeot",
    "raticate",
    "golbat",
    "fearow",
    "seaking",
    "doduo"
  ],
  "PokemonsTransferFilter": {
    "Bulbasaur": {
      "KeepMinCp": 300,
      "KeepMinIvPercentage": 80.0,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinOperator": "and",
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "DeprecatedMoves": null,
      "MovesOperator": "or"
    },
    "Charmander": {
      "KeepMinCp": 300,
      "KeepMinIvPercentage": 80.0,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinOperator": "and",
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "DeprecatedMoves": null,
      "MovesOperator": "or"
    },
    "Pikachu": {
      "KeepMinCp": 300,
      "KeepMinIvPercentage": 80.0,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinOperator": "and",
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "DeprecatedMoves": null,
      "MovesOperator": "or"
    },
    "Squirtle": {
      "KeepMinCp": 300,
      "KeepMinIvPercentage": 80.0,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinOperator": "and",
      "KeepMinDuplicatePokemon": 4,
      "Moves": [],
      "DeprecatedMoves": null,
      "MovesOperator": "or"
    },
    "Magikarp": {
      "KeepMinCp": 100,
      "KeepMinIvPercentage": 100.0,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinOperator": "and",
      "KeepMinDuplicatePokemon": 4,
      "Moves": [],
      "DeprecatedMoves": null,
      "MovesOperator": "or"
    },
    "Gyarados": {
      "KeepMinCp": 1000,
      "KeepMinIvPercentage": 100.0,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinOperator": "and",
      "KeepMinDuplicatePokemon": 4,
      "Moves": [],
      "DeprecatedMoves": null,
      "MovesOperator": "or"
    },
    "Lapras": {
      "KeepMinCp": 1000,
      "KeepMinIvPercentage": 100.0,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinOperator": "and",
      "KeepMinDuplicatePokemon": 4,
      "Moves": [],
      "DeprecatedMoves": null,
      "MovesOperator": "or"
    },
    "Eevee": {
      "KeepMinCp": 300,
      "KeepMinIvPercentage": 100.0,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinOperator": "and",
      "KeepMinDuplicatePokemon": 4,
      "Moves": [],
      "DeprecatedMoves": null,
      "MovesOperator": "or"
    },
    "Vaporeon": {
      "KeepMinCp": 1000,
      "KeepMinIvPercentage": 100.0,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinOperator": "and",
      "KeepMinDuplicatePokemon": 2,
      "Moves": [],
      "DeprecatedMoves": null,
      "MovesOperator": "or"
    },
    "Jolteon": {
      "KeepMinCp": 1000,
      "KeepMinIvPercentage": 100.0,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinOperator": "and",
      "KeepMinDuplicatePokemon": 2,
      "Moves": [],
      "DeprecatedMoves": null,
      "MovesOperator": "or"
    },
    "Flareon": {
      "KeepMinCp": 1000,
      "KeepMinIvPercentage": 100.0,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinOperator": "and",
      "KeepMinDuplicatePokemon": 2,
      "Moves": [],
      "DeprecatedMoves": null,
      "MovesOperator": "or"
    },
    "Snorlax": {
      "KeepMinCp": 1500,
      "KeepMinIvPercentage": 100.0,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinOperator": "and",
      "KeepMinDuplicatePokemon": 4,
      "Moves": [],
      "DeprecatedMoves": null,
      "MovesOperator": "or"
    },
    "Dratini": {
      "KeepMinCp": 300,
      "KeepMinIvPercentage": 100.0,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinOperator": "and",
      "KeepMinDuplicatePokemon": 4,
      "Moves": [],
      "DeprecatedMoves": null,
      "MovesOperator": "or"
    },
    "Dragonair": {
      "KeepMinCp": 500,
      "KeepMinIvPercentage": 100.0,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinOperator": "and",
      "KeepMinDuplicatePokemon": 4,
      "Moves": [],
      "DeprecatedMoves": null,
      "MovesOperator": "or"
    },
    "Dragonite": {
      "KeepMinCp": 1500,
      "KeepMinIvPercentage": 100.0,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinOperator": "and",
      "KeepMinDuplicatePokemon": 8,
      "Moves": [],
      "DeprecatedMoves": null,
      "MovesOperator": "or"
    },
    "Poliwag": {
      "KeepMinCp": 300,
      "KeepMinIvPercentage": 100.0,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinOperator": "and",
      "KeepMinDuplicatePokemon": 4,
      "Moves": [],
      "DeprecatedMoves": null,
      "MovesOperator": "or"
    },
    "Venonat": {
      "KeepMinCp": 300,
      "KeepMinIvPercentage": 100.0,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinOperator": "and",
      "KeepMinDuplicatePokemon": 4,
      "Moves": [],
      "DeprecatedMoves": null,
      "MovesOperator": "or"
    },
    "Staryu": {
      "KeepMinCp": 300,
      "KeepMinIvPercentage": 100.0,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinOperator": "and",
      "KeepMinDuplicatePokemon": 4,
      "Moves": [],
      "DeprecatedMoves": null,
      "MovesOperator": "or"
    },
    "Clefairy": {
      "KeepMinCp": 300,
      "KeepMinIvPercentage": 100.0,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinOperator": "and",
      "KeepMinDuplicatePokemon": 4,
      "Moves": [],
      "DeprecatedMoves": null,
      "MovesOperator": "or"
    },
    "Ekans": {
      "KeepMinCp": 300,
      "KeepMinIvPercentage": 100.0,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinOperator": "and",
      "KeepMinDuplicatePokemon": 4,
      "Moves": [],
      "DeprecatedMoves": null,
      "MovesOperator": "or"
    },
    "Bellsprout": {
      "KeepMinCp": 300,
      "KeepMinIvPercentage": 100.0,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinOperator": "and",
      "KeepMinDuplicatePokemon": 4,
      "Moves": [],
      "DeprecatedMoves": null,
      "MovesOperator": "or"
    },
    "Paras": {
      "KeepMinCp": 300,
      "KeepMinIvPercentage": 100.0,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinOperator": "and",
      "KeepMinDuplicatePokemon": 4,
      "Moves": [],
      "DeprecatedMoves": null,
      "MovesOperator": "or"
    }
  },
  "PokemonToSnipe": {
    "Locations": [
      {
        "Latitude": 38.556807486461118,
        "Longitude": -121.2383794784546
      },
      {
        "Latitude": -33.859019,
        "Longitude": 151.213098
      },
      {
        "Latitude": 47.5014969,
        "Longitude": -122.0959568
      },
      {
        "Latitude": 51.5025343,
        "Longitude": -0.2055027
      }
    ],
    "Pokemon": [
      "venusaur",
      "charizard",
      "blastoise",
      "beedrill",
      "raichu",
      "sandslash",
      "nidoking",
      "nidoqueen",
      "clefable",
      "ninetales",
      "golbat",
      "vileplume",
      "golduck",
      "primeape",
      "arcanine",
      "poliwrath",
      "alakazam",
      "machamp",
      "golem",
      "rapidash",
      "slowbro",
      "muk",
      "cloyster",
      "gengar",
      "exeggutor",
      "marowak",
      "hitmonchan",
      "lickitung",
      "rhydon",
      "chansey",
      "starmie",
      "scyther",
      "magmar",
      "electabuzz",
      "jynx",
      "gyarados",
      "lapras",
      "ditto",
      "vaporeon",
      "jolteon",
      "flareon",
      "porygon",
      "kabutops",
      "aerodactyl",
      "snorlax",
      "articuno",
      "zapdos",
      "moltres",
      "dragonite",
      "mewtwo",
      "mew"
    ]
  },
  "PokemonToUseMasterball": [
    "articuno",
    "zapdos",
    "moltres",
    "mew",
    "mewtwo"
  ],
  "HumanWalkSnipeFilters": {
    "Dratini": {
      "MaxDistance": 1500.0,
      "Priority": 1,
      "MaxWalkTimes": 360.0,
      "CatchPokemonWhileWalking": false,
      "SpinPokestopWhileWalking": true,
      "MaxSpeedUpSpeed": 29.2,
      "AllowSpeedUp": true,
      "DelayTimeAtDestination": 0
    },
    "Dragonair": {
      "MaxDistance": 1500.0,
      "Priority": 2,
      "MaxWalkTimes": 360.0,
      "CatchPokemonWhileWalking": false,
      "SpinPokestopWhileWalking": true,
      "MaxSpeedUpSpeed": 28.7,
      "AllowSpeedUp": true,
      "DelayTimeAtDestination": 0
    },
    "Snorlax": {
      "MaxDistance": 1500.0,
      "Priority": 1,
      "MaxWalkTimes": 360.0,
      "CatchPokemonWhileWalking": false,
      "SpinPokestopWhileWalking": true,
      "MaxSpeedUpSpeed": 27.9,
      "AllowSpeedUp": true,
      "DelayTimeAtDestination": 0
    },
    "Lapras": {
      "MaxDistance": 1500.0,
      "Priority": 1,
      "MaxWalkTimes": 360.0,
      "CatchPokemonWhileWalking": false,
      "SpinPokestopWhileWalking": true,
      "MaxSpeedUpSpeed": 28.9,
      "AllowSpeedUp": true,
      "DelayTimeAtDestination": 0
    },
    "Bulbasaur": {
      "MaxDistance": 1000.0,
      "Priority": 3,
      "MaxWalkTimes": 360.0,
      "CatchPokemonWhileWalking": false,
      "SpinPokestopWhileWalking": true,
      "MaxSpeedUpSpeed": 24.2,
      "AllowSpeedUp": true,
      "DelayTimeAtDestination": 0
    },
    "Charmander": {
      "MaxDistance": 1000.0,
      "Priority": 2,
      "MaxWalkTimes": 360.0,
      "CatchPokemonWhileWalking": false,
      "SpinPokestopWhileWalking": true,
      "MaxSpeedUpSpeed": 25.8,
      "AllowSpeedUp": true,
      "DelayTimeAtDestination": 0
    },
    "Pikachu": {
      "MaxDistance": 1000.0,
      "Priority": 2,
      "MaxWalkTimes": 360.0,
      "CatchPokemonWhileWalking": false,
      "SpinPokestopWhileWalking": true,
      "MaxSpeedUpSpeed": 26.3,
      "AllowSpeedUp": true,
      "DelayTimeAtDestination": 0
    },
    "Abra": {
      "MaxDistance": 1000.0,
      "Priority": 3,
      "MaxWalkTimes": 360.0,
      "CatchPokemonWhileWalking": false,
      "SpinPokestopWhileWalking": true,
      "MaxSpeedUpSpeed": 24.1,
      "AllowSpeedUp": true,
      "DelayTimeAtDestination": 0
    },
    "Kadabra": {
      "MaxDistance": 1000.0,
      "Priority": 3,
      "MaxWalkTimes": 300.0,
      "CatchPokemonWhileWalking": false,
      "SpinPokestopWhileWalking": true,
      "MaxSpeedUpSpeed": 24.1,
      "AllowSpeedUp": true,
      "DelayTimeAtDestination": 0
    },
    "Alakazam": {
      "MaxDistance": 1000.0,
      "Priority": 3,
      "MaxWalkTimes": 360.0,
      "CatchPokemonWhileWalking": false,
      "SpinPokestopWhileWalking": true,
      "MaxSpeedUpSpeed": 24.1,
      "AllowSpeedUp": true,
      "DelayTimeAtDestination": 0
    },
    "Eevee": {
      "MaxDistance": 600.0,
      "Priority": 3,
      "MaxWalkTimes": 360.0,
      "CatchPokemonWhileWalking": false,
      "SpinPokestopWhileWalking": true,
      "MaxSpeedUpSpeed": 24.1,
      "AllowSpeedUp": true,
      "DelayTimeAtDestination": 0
    },
    "Chansey": {
      "MaxDistance": 1000.0,
      "Priority": 2,
      "MaxWalkTimes": 360.0,
      "CatchPokemonWhileWalking": false,
      "SpinPokestopWhileWalking": true,
      "MaxSpeedUpSpeed": 24.1,
      "AllowSpeedUp": true,
      "DelayTimeAtDestination": 0
    }
  },
  "PokemonUpgradeFilters": {
    "Dratini": {
      "LevelUpByCPorIV": "iv",
      "UpgradePokemonCpMinimum": 600.0,
      "UpgradePokemonIvMinimum": 99.0,
      "UpgradePokemonMinimumStatsOperator": "or",
      "OnlyUpgradeFavorites": false
    }
  }
}
your config here
```

### Steps to Reproduce


### Other Information
Version: 0.9.7.2
Windows Version: 10
What is affected (catch, transfer, evolve, recycle, snipe, powerup/levelup, other): ALL

**Comment by msx752** [comment]
missing file or inaccessible "resources\encrypt.dll"

**Comment by BoydTM** [comment]
Works - thx, I just copied one from noxx realease. Zip with 0.9.7.2 does not have it
