### ISSUE TITLE
DumpPokemonStats don't work

### ISSUE THREAD

**Issue by mansellrace** [Necrobot-Private/NecroBot#300]
DumpPokemonStats don't work on newer version

**Comment by ckchiang** [comment]
I also found that evolve pokemon using PokeEase or NecrobotVisualizer always fails.

**Comment by ajns73** [comment]
confirmed here.

**Comment by ajns73** [comment]
PokeNurse is still working it seems

**Comment by ajns73** [comment]
@msx752 After more testing, I can get PokeEase to work if I refresh it after ever action. PokeNurse works, but fails after a time.  Quit/restart cures this, but must be done again after a certain time.

**Comment by holmeschou** [comment]
I have submit a pull request #315 to fix this issue. Please help to review it. Thanks.

**Comment by jjskuld** [comment]
Fixed in latest release. Thanks @holmeschou
