### ISSUE TITLE
(Enhancement) Options For GUI And (Issue)

### ISSUE THREAD

**Issue by hardknoxni69a** [Necrobot-Private/NecroBot#301]
The GUI we use is absolutely gorgeous. I believe if we add the hover option to the pokemon list would streamline the users experience instead of having to fully click into a pokemon when we hover over them a small menu will pop up with Favorite, Transfer, Power Up so we dont have to click into each individual pokemon to transfer. Also I Noticed For Some Reason the GUI doesnt show the pokemon level 1-40. So would be nice to see IV, CP, Level At a glance And With the mouse over Favorite, Transfer, Power Up. Also On issue point the GUI Move Bot Here Option Doesnt work. it would be very helpful for manual human sniping using map services on side

**Comment by ajns73** [comment]
I'd love to use the GUI, but it still has overlay issues for me.

**Comment by seouljah760** [comment]
I would recommend leaving a comment after reading this issue here.

#321
