### ISSUE TITLE
Legacy "4th Party" Helper Apps

### ISSUE THREAD

**Issue by ajns73** [Necrobot-Private/NecroBot#307]
Can a dev weigh in on whether the practice of using these apps is "safe?" I.E. - is there anything about them (PokeEase, PokeNurse, etc.) that will get us flagged as far as we know? They all use our login, so if they accomplish their tasks "the old way", then we are flagging ourselves for study. Should we avoid using them until they have been updated?

**Comment by jjskuld** [comment]
PokeEase is just a GUI for Necrobot so it is safe to use. In fact it is our default GUI.

But the others apps that are not related to Necrobot will need to be updated.  They most likely will connect with 0.35 API, which is immediately flag and almost certain ban.

Unless an app states that they have updated to 0.43 API, then it's not safe to use.

**Comment by jjskuld** [comment]
If there are any tools that you would like to be updated, let me know and I can take a look.  It shouldn't be too hard to update for 0.43.
