### ISSUE TITLE
[Feature Request] Transferring/Evolving GUI (For jjskuld)

### ISSUE THREAD

**Issue by ajns73** [Necrobot-Private/NecroBot#309]
@jjskuld What I am looking for is really just a way of transferring an evolving in a GUI. PokeNurse was the most powerful for this, but I could get used to PokeEase. The official PokeEase release (NecroGUI) has overlay issues for me ("yes" and "no" always visible and neither triggers any action), so I have to use GediminasMasaitis version. Currently that version does NOT evolve, although it does transfer. It also will not refresh at all. So after I transfer pokemon, when I reopen that pokemon windows it just spins.

*EDIT* The refresh issue is just a time thing for me. It WILL update if I let it sit long enough, but it is way longer than before .43.

**Comment by seouljah760** [comment]
I would recommend leaving a comment after reading this issue here.

https://github.com/Necrobot-Private/NecroBot/issues/321

**Comment by ajns73** [comment]
@seouljah760 See closed #307 for why it was done that way.

**Comment by jjskuld** [comment]
This is now fixed with the new wpf gui
