### ISSUE TITLE
GUI Not Working 

### ISSUE THREAD

**Issue by mkroxm** [Necrobot-Private/NecroBot#31]
PokeEase  Is Working But Not Scrolling And Other GUI Are Even not Working It's Showing Connecting but Not Working !!!!

**Comment by BoydTM** [comment]
enable player tracking in settings ...

**Comment by mkroxm** [comment]
it's already On If We Open Manually WebUi\NecrobotJavanHawk-AndikaTanpaH\index.html it's working Fine But iif We try To Open It with NecroBot2.GUI.exe it's Not working it's Stuck at connecting Page 
  
![image](https://cloud.githubusercontent.com/assets/22080561/18361234/b79df240-761e-11e6-88be-2025f73235f9.png)
