### ISSUE TITLE
Not auto transfer week pokemon.

### ISSUE THREAD

**Issue by heroes1412** [Necrobot-Private/NecroBot#314]
i set:
 "KeepMinCp": 1350,
    "KeepMinIvPercentage": 98.0,
    "KeepMinLvl": 20,
    "UseKeepMinLvl": false,
but, my inventory has many pokemon < 500 CP or < 80 IV

**Comment by iwean** [comment]
Can you paste your config to http://pastebin.com/ ?
So we can check it...

**Comment by heroes1412** [comment]
http://pastebin.com/ui5ht5JA

**Comment by iwean** [comment]
Change your keep min operator to "and"

**Comment by heroes1412** [comment]
oh, if i want keep 100IV but < 500 CP?

**Comment by iwean** [comment]
Set it on "PokemonsTransferFilter" for individual filter
