### ISSUE TITLE
necro not connected

### ISSUE THREAD

**Issue by stalskgd** [Necrobot-Private/NecroBot#317]
Hey guys
after the launch of a black screen only http://pix.my/1HaCip
Initializing NecroBot2 logger at time 11/9/2016 10:14:32 AM... in the log file

**Comment by seouljah760** [comment]
Unless you plan on using the template for the issues, and filling it out fully, we cannot help you. Use the discord chat otherwise. If you have fixed your issue, please post your fix as a reply to my comment.
