### ISSUE TITLE
Pokemon API changed, bot API needs an update

### ISSUE THREAD

**Issue by ShadXo** [Necrobot-Private/NecroBot#318]
Bots stopped working with the message:
(KILLSWITCH) We have detected a Pokemon API change. The bot emulates API version 0.43.3, witch is no longer supported. Minimum API is now 0.45.0.
![knipsel](https://cloud.githubusercontent.com/assets/3438421/20149798/1e9eb0f0-a6b3-11e6-92d5-14d540882384.PNG)

**Comment by ajns73** [comment]
Confirmed

**Comment by TheBootsHathReturned** [comment]
So ummm.....What was it exactly that I said would happen right after you cracked the API??? I just can't seem to remember now ;)

**Comment by jjskuld** [comment]
Yeah, the PogoDev community had heard rumors that API change was today, so they already started work on 0.45.  Stay tuned.

**Comment by Furtif** [comment]
Hello teste comit 
https://github.com/Necrobot-Private/POGOProtos/tree/ccc08e2dc025d63fa4704bdd50254e56f7d3bb3c 
and 
https://github.com/Necrobot-Private/PokemonGo.RocketAPI/tree/d0a4447112b89a6abfe2955994822ccd6838f023 (conflits to uint int ) teste ok

**Comment by TriceOne** [comment]
What I have to do with the Links ? :(

**Comment by Furtif** [comment]
New api not conflits here: 
[https://github.com/Necrobot-Private/PokemonGo.RocketAPI/pull/12/commits/bd85f15513539da911c024002720059f35adf4b1](url)

**Comment by TriceOne** [comment]
is the bot working ? i dont understand what i have to do with the links :(

**Comment by Tonisn** [comment]
No it's not. Those are links to other bots.

**Comment by Furtif** [comment]
Hi, will compile all her and create a release or debug ... I do not support this repository, please wait until it is done otherwise could you download the console file in this commentary.

Greetings.
[NecroBot2.zip](https://github.com/Necrobot-Private/NecroBot/files/583463/NecroBot2.zip)

**Comment by Furtif** [comment]
Not if they are not links to other bots are links to source code, so the need to compile with Visual Studio 2015.

Greetings

**Comment by linuxxlager** [comment]
Great news, it works !!

**Comment by TriceOne** [comment]
Nice Support thanks :) !!!!

**Comment by jjskuld** [comment]
@Furtif Please don't do that again. No links to unofficial releases, especially bypassing the killswitch.  Almost 100% chance of ban if you disable the killswitch.

For everyone out there.. be wary of any unofficial releases. Last time someone sent a link out that was a trojan that encrypted your computer.  Not saying @Furtif is sending out trojans but how do you even know that that link is Necrobot?  What if it's logging your password?

Just be patient. It should be back up shortly.

**Comment by Furtif** [comment]
Hi, I am not of the type to use computer viruses, I just modify the code, that is to say official protos and I modify api (the modifications are the on the links) I compile and its march since last night .. no problem for more than 24h. The links involved are commits here in Necro-Private. I feel like a criminal just wanting to help ...

I respect the work of others, and as such I love that respect mine.

Sorry for all.
Greetings

**Comment by jjskuld** [comment]
@Furtif I understand and respect your wish to help. The problem is that you're only helping people get banned.  

Understand that Niantic is allowing 0.43.3 client to connect in order to ban them in the next banwave.  The official 0.43 clients are forced to upgrade now.

**Comment by jjskuld** [comment]
@Furtif One more thing.. I reviewed your fork.  Just changing a few constants does NOT mean it is compatible with 0.45.  There is an entirely new hashing function that has not been reversed yet, so you are sending data to Niantic that tells them you are 100% a bot by using an old hash function.

**Comment by Furtif** [comment]
Ok ok, anyway has to forbid everything and nothing soon POGo will be more than a decoration app seen the weather that makes nobody want to go out to hunt pokemons ... but I did not touch a killswitch jai Just edit 4 lines that's it.

Greetings

**Comment by Furtif** [comment]
Ok I stopped the bot it is still running ... lv 21 !!! Since yesterday yesterday. ^^

**Comment by ajns73** [comment]
If your native language is English, but your learn 2 French words, you cannot claim to be fluent in French. If you were to travel to France, you would be identified by a native as a tourist (and a bad one at that). You could not pass a high school French test. You're about as French as you are Martian. 

I am sure @Furtif meant no harm, but as @jjskuld points out, there are two issues for users to consider: (1) The next person that offers "help" might not be as altruistic as @Furtif. If steps aren't taken to curtail this kind of behavior then this community will be opening itself up to those that do not have our best interests at heart; (2) The system for connecting and issuing commands to Niantics servers is extremely complicated and involves many layers (Forgive my simplification). Getting any of them wrong would be disastrous if you want to run a bot and not be noticed. They might "work" but they are going to be noticed by people whose attention you do not want. Not being part of the dev team and assuming you understand that process is hubris. Patience is a virtue.

**Comment by Furtif** [comment]
Entendu, et pour le "french" oui je suis french désole pour mon anglais ^^

salutations

**Comment by ajns73** [comment]
My point exactly. :)

**Comment by Furtif** [comment]
You too?

**Comment by ajns73** [comment]
No. I just got lucky saying "French." But I understood about as much of that post as I understand the API. ;)

**Comment by Furtif** [comment]
It is complicated in effect all this ...
