### ISSUE TITLE
[Sugestion] Create random default location

### ISSUE THREAD

**Issue by Whistler212** [Necrobot-Private/NecroBot#32]
Why not make random favorite location on first time run bot? 
if new user didn't want to set own location, it always on Central Park NY, why not make for example 3 random default location, say Central Park NY, Disney Land Tokyo or Sydney Harbor Sydney
Dev can make random device, why not make random location?

**Comment by Cyrus-Wong** [comment]
agree, I just thought of this similar issue hours ago. If bot always start at same gps cord, it's might be easily detected as suspicious. would be better bot design in a way like changing the last 1 or 2 number of the gps cord. although I not sure that 1-2 number affect big on real map or not.. maybe the last 1 sufficient?

**Comment by Silph-Road** [comment]
@Whistler212 
If you have a random location, at every start up, you would get softbanned... and potentially flagged.
If you want some randomness increase this value "MaxSpawnLocationOffset": 10, <-- that is meters.

Starting bot at --> Central Park NY, then next time --> Disney Land Tokyo then --> Sydney Harbor Sydney, is very suspicious and you would get softbanned. 
**Real players do not jump countries everyday.**

Adding random locations will only increase softbans and most likely hardbans later on.

@Cyrus-Wong the bot already does that, "MaxSpawnLocationOffset": 10, <-- that is meters. Bot will spawn within 10 meters of default location.

**Comment by Silph-Road** [comment]
This enhancement, might get revisited in later on, closing issue.

**Comment by samuraitruong** [comment]
when i play with r eal app. i ussually open at at home. same coords everytime
