### ISSUE TITLE
Add option deploy Gyms

### ISSUE THREAD

**Issue by htanh034** [Necrobot-Private/NecroBot#325]
Pickup Daily Defender Bonuses ?
 Pokeroadie example config.
.....
<VisitGyms>true</VisitGyms>
  <PrioritizeGyms>true</PrioritizeGyms>
  <AutoDeployAtTeamGyms>true</AutoDeployAtTeamGyms>
  <PickupDailyDefenderBonuses>true</PickupDailyDefenderBonuses>
  <MinGymsBeforeBonusPickup>3</MinGymsBeforeBonusPickup>
....

**Comment by mo0ojava** [comment]
@samuraitruong You were working on the gym-part a while ago. Do you know if the collection of coins ever worked?
