### ISSUE TITLE
Msniper continue trying to snipe without pokeballs

### ISSUE THREAD

**Issue by gjimenezf** [Necrobot-Private/NecroBot#327]
Necrobot 1.0.0.16 with just Msniper activated continue trying to snipe without pokeballs. It should stop trying to snipe and get enough pokeballs on pokestop up to complete the min pokeballs to snipe.

Config:
Min pokeballs to snipe: 20
Min pokeballs while shipping: 5

**Comment by msx752** [comment]
because msniper is manual, so you should break then you will continue.

**Comment by gjimenezf** [comment]
Even using the auto option in msniper?

**Comment by msx752** [comment]
main purpose of msniper is manual work, but i might add in the future like that.
