### ISSUE TITLE
[1.0.0.16] Native sniping feature request 

### ISSUE THREAD

**Issue by 233635151** [Necrobot-Private/NecroBot#329]
I noticed native sniping does not work any more after API changes. Ideally, the bot should be able to retrieve coordinates from MSniper and snipe by itself. The dependency over a MSniper web page does not make the application resilient enough.

**Comment by gjimenezf** [comment]
I agree,  when I had native sniping with skiplagged I could reach up to 420 pokemon/hour, now with msniper auto wich is establish external communication to necrobot I can max get 190 pokemon/hour.

**Comment by jjskuld** [comment]
Yup, we've talked about this.. will be implemented soon.

**Comment by gjimenezf** [comment]
Thanks, having native snipe of msniper in necro allows to implement in necro to not trying to snipe already despawn pokemon based on its despawn  timestamp.
This is important because this issue reduce the pokemon per hour rate a lot.

**Comment by samuraitruong** [comment]
thought all fixes. check our autosnipe /manual snipe in wiki
