### ISSUE TITLE
sniper filter didnt work

### ISSUE THREAD

**Issue by ThatAce** [Necrobot-Private/NecroBot#33]
well in previous version of necrobot that noxxdev have the sniper filter worked where it only catch specific pokemon in the list, but after using the new necro it started to snipe every pokemon avaliable such as region exclusive where i didnt want that

config : 
"UseSnipeLocationServer": true,
    "SnipeLocationServer": "localhost",
    "SnipeLocationServerPort": 16969,
    "GetSniperInfoFromPokezz": true,
    "GetOnlyVerifiedSniperInfoFromPokezz": true,
    "GetSniperInfoFromPokeSnipers": false,
    "GetSniperInfoFromPokeWatchers": false,
    "GetSniperInfoFromSkiplagged": false,
    "MinPokeballsToSnipe": 100,
    "MinPokeballsWhileSnipe": 0,
    "MinDelayBetweenSnipes": 6000,
    "SnipingScanOffset": 0.005,
    "SnipeAtPokestops": false,
    "ActivateMSniper": false,
    "SnipeIgnoreUnknownIv": false,
    "UseTransferIvForSnipe": false,
    "SnipePokemonNotInPokedex": false,
    "UseSnipeLimit": false,
    "SnipeRestSeconds": 600,
    "SnipeCountLimit": 39

**Comment by dlim1126** [comment]
Same issue to me too . keep on sniping unwanted pokemon .

btw , my config .

"SnipeConfig": {
    "UseSnipeLocationServer": true,
    "SnipeLocationServer": "localhost",
    "SnipeLocationServerPort": 16969,
    "GetSniperInfoFromPokezz": true,
    "GetOnlyVerifiedSniperInfoFromPokezz": false,
    "GetSniperInfoFromPokeSnipers": true,
    "GetSniperInfoFromPokeWatchers": false,
    "GetSniperInfoFromSkiplagged": false,
    "MinPokeballsToSnipe": 20,
    "MinPokeballsWhileSnipe": 0,
    "MinDelayBetweenSnipes": 2000,
    "SnipingScanOffset": 0.003,
    "SnipeAtPokestops": false,
    "ActivateMSniper": false,
    "SnipeIgnoreUnknownIv": false,
    "UseTransferIvForSnipe": false,
    "SnipePokemonNotInPokedex": false,
    "UseSnipeLimit": true,
    "SnipeRestSeconds": 600,
    "SnipeCountLimit": 59

**Comment by raymonders** [comment]
@dlim1126  @ThatAce how are you people sniping when the "snipeatpokestops" is set to False?!

**Comment by msx752** [comment]
@dlim1126 @ThatAce of course didn't work first of all, SnipeAtPokestops: set **true**

**Comment by raymonders** [comment]
uhmm... actually @msx752 it DOES work... i copied their settings just to laugh, but it WORKS. here's my config

  "SnipeConfig": {
    "UseSnipeLocationServer": true,
    "SnipeLocationServer": "localhost",
    "SnipeLocationServerPort": 16969,
    "GetSniperInfoFromPokezz": true,
    "GetOnlyVerifiedSniperInfoFromPokezz": true,
    "GetSniperInfoFromPokeSnipers": true,
    "GetSniperInfoFromPokeWatchers": true,
    "GetSniperInfoFromSkiplagged": true,
    "MinPokeballsToSnipe": 99,
    "MinPokeballsWhileSnipe": 50,
    "MinDelayBetweenSnipes": 60000,
    "SnipingScanOffset": 0.003,
    "SnipeAtPokestops": false,
    "ActivateMSniper": false,
    "SnipeIgnoreUnknownIv": false,
    "UseTransferIvForSnipe": false,
    "SnipePokemonNotInPokedex": false,
    "UseSnipeLimit": true,
    "SnipeRestSeconds": 800,
    "SnipeCountLimit": 50

and i'm sniping ONLY the pokemon in my PokemonToSnipe list. so this must really be a bug if it works for some and not for others

i'm using version 9.8.6

**Comment by dlim1126** [comment]
@msx752 it work for me since i use 0.7 ~

@raymonders yup , i also curious about that ~

**Comment by msx752** [comment]
so bug still continue right ?

**Comment by petpetpetvm** [comment]
@msx752 i want to ask if the MSniper works on this version yet ? And if the pokemonsniperfilter works, can i still use it to snipe a pokemon that not in the list

**Comment by msx752** [comment]
@petpetpetvm pokemonsniperfilter didn't work with msniper. it  is manual pokemon sniper.
