### ISSUE TITLE
[1.0.0.16-BUG] MSniper is always on regardless the value of "ActivateMSniper"

### ISSUE THREAD

**Issue by 233635151** [Necrobot-Private/NecroBot#330]
When setting ActivateMSniper = false, MSniper is also enabled.

**Comment by Silph-Road** [comment]
Needs verification, but due to the current nature of spawn data and lack of websites that track pokemon on a sufficient scale, thus in the near future, this feature will probably be hardcoded in order to generate reliable spawn data. Control of sniping captures will of-course be provided.

**Comment by msx752** [comment]
@233635151  impossible because when you set `ActivateMSniper = false` you cant see any service information from bot also bot can not share pokemon with msniperservice,
can you share the screenshot,
