### ISSUE TITLE
after auto-update necrobot2 all configs gone

### ISSUE THREAD

**Issue by msx752** [Necrobot-Private/NecroBot#332]
after auto update necrobot resets all configs.json it is really bad i know it will fix in short time for next release

related with: https://github.com/Necrobot-Private/NecroBot/issues/311

**Comment by ajns73** [comment]
@msx752 I know you verified this yourself, but in the interest of full disclosure, I have not had this problem since Necro2 came back (verified). However, I do know a few that have to do a backup every time to preserve their config.

**Comment by msx752** [comment]
@ajns73  actually old necrobot versions used backupsystem, but now i noticed,it is removed

**Comment by Matteo561** [comment]
Same and when I try to use it is saying you need to fill out googleusername and googlepassword.

**Comment by Dreker** [comment]
[23:57:13] () Validating config.json...
[23:57:14] () Validating auth.json...
[23:57:16] (UPDATE) Perfect! You already have the newest Version 1.0.0.18
[23:57:16] (INFO) Logging in using Ptc
[23:57:16] (INFO) Your IP is: XXXXXX

and freeze...

**Comment by johnnylim78** [comment]
after update i cannot log in why ?
anyone can help

**Comment by OniQ** [comment]
@Dreker , I had the same result after update when I confused google auth fields with ptc and set wrong AuthType. Check yours.

**Comment by johnnylim78** [comment]
Thanks

**Comment by RedDragonx** [comment]
Please fix this issue. After update Necrobot2 reset auth & config to default, and it use all of my limited incubator to 2km egg and transfer all of my high CP (low IV) mon.
