### ISSUE TITLE
skip pokemon

### ISSUE THREAD

**Issue by mharckk** [Necrobot-Private/NecroBot#333]
hi,

downloaded the 1.17 version and it skipped pokemons
this happen also to 1.16 what i did is replaced the config file from 1.15
dont know why does it happen.

Skipped Caterpie
Skipped Spearow
Skipped Pidgey

and so on.

**Comment by msx752** [comment]
set FALSE
` "UsePokemonToNotCatchFilter": false,
    "UsePokemonSniperFilterOnly": false,`

**Comment by mharckk** [comment]
thanks
