### ISSUE TITLE
Msniper 

### ISSUE THREAD

**Issue by Ragepresident** [Necrobot-Private/NecroBot#334]
Hey,
Is an automatic function planned for the MSniper or already in work?

Greetz

**Comment by msx752** [comment]
actually i have an idea for fully automatic snipe but I haven't decided yet

**Comment by Dreker** [comment]
How use to manually use MSniper?
Already set "ActivateMSniper": true,
When i click on pokemons http://msniper.com/ nothing happen

**Comment by msx752** [comment]
@Dreker open the http://msniper.com then click AUTO MSniper as you can see ??

**Comment by Ragepresident** [comment]
@Dreker works great for me with the latest release https://github.com/msx752/MSniper/releases/tag/1.0.6.3
