### ISSUE TITLE
How can I rename Pokemon based on its level?

### ISSUE THREAD

**Issue by RedDragonx** [Necrobot-Private/NecroBot#337]
I want to rename my pokemon like "IV_Level_Name"
Is it possible?

**Comment by jjskuld** [comment]
It is in the config.json.  Just search for rename option.  But I highly discourage you from enabling the option since it is easily detectable and may lead to ban.

**Comment by RedDragonx** [comment]
But it only has template IV_Name
"RenameTemplate": "{1}_{0}",

I want to add Level in the name too, like 60_25_Eevee (Eevee, IV 60, level 25)

**Comment by hardknoxni69a** [comment]
OK if 1=IV 0=Name WHAT equals lvl I would love this option as well I want my poke.on over 85 iv to be name LVL/IV please Respond with correct value for template as the wiki doesn't explain template at all

**Comment by hardknoxni69a** [comment]
Side note the GUI of your desperately needs to display pokemon lvl as well. And the hover options for transfer upgrade evolve at some.point I still use necro visualizer because it's so hard to quickly transfer pokemon and can't see level

**Comment by hardknoxni69a** [comment]
implemented
