### ISSUE TITLE
LastPos not working properly under GPX

### ISSUE THREAD

**Issue by ValorRed** [Necrobot-Private/NecroBot#34]
The original 0.9.7 seems fine with GPX.
The expect logic:
When GPX file presented, if LastPos.ini is provided, start the bot with LastPos (instead of default coordination), then walk to the closest trkpt of the GPX file.

**Comment by Silph-Road** [comment]
Can you elaborate more on the problem. Use the template please. What is expected and what actually happenes. What version are you on
