### ISSUE TITLE
[Feature] Bubblestrat implementation

### ISSUE THREAD

**Issue by gjimenezf** [Necrobot-Private/NecroBot#341]
Since the daily limits to pokemon catch and pokestop spins avoid faster leveling of  a trainer, it could be a nice solution to implement something that does not have limitations to get continuous exp.
One is gym fighting, especially the Bubblestrat gym fighting tricks to get a lot of exp: https://pokemongo.gamepress.gg/bubblestrat-possibilities

Please try to implement this into Necrobot.

**Comment by 233635151** [comment]
Interesting idea...guess it is feasible. Up to 1.5m exp a day. :)

**Comment by hardknoxni69a** [comment]
other people play in gyms as well so hard to do something like this but atleast gym attacking is in place now to grind a little extra xp
