### ISSUE TITLE
Problem with human sniper

### ISSUE THREAD

**Issue by Einlenzer** [Necrobot-Private/NecroBot#342]
I there, to make a long story short :

### Expected Behavior:
Human walk snipe to work.

### Actual Behavior:
Human walk snipe found pokemon, walk to their spot but never encounter them.

Is there a solution to solve that ?

``
  "HumanWalkSnipeConfig": {
    "Enable": true,
    "DisplayPokemonList": true,
    "MaxDistance": 3000.0,
    "MaxEstimateTime": 900.0,
    "CatchEmAllMinBalls": 20,
    "TryCatchEmAll": true,
    "CatchPokemonWhileWalking": true,
    "SpinWhileWalking": true,
    "AlwaysWalkback": false,
    "SnipingScanOffset": 0.025,
    "WalkbackDistanceLimit": 300.0,
    "IncludeDefaultLocation": true,
    "UseSnipePokemonList": true,
    "MaxSpeedUpSpeed": 29.0,
    "AllowSpeedUp": true,
    "DelayTimeAtDestination": 7000,
    "UsePokeRadar": true,
    "UseSkiplagged": false,
    "UsePokecrew": false,
    "UsePokesnipers": true,
    "UsePokeZZ": false,
    "UsePokeWatcher": false,
    "UseFastPokemap": false,
    "UsePogoLocationFeeder": true,
    "AllowTransferWhileWalking": false
``

Version: 1.0.0.19
Windows Version: 10
What is affected (catch, transfer, favorite, GPX, evolve, recycle, snipe, human walk snipe, pokestops, powerup/levelup, other): human walk snipe

Thank you very much !

(i'm french, so be indulgent for my english and my lack of talk ^^")

**Comment by samuraitruong** [comment]
this feature is consider as not working because there no data source atm, please disable it until we have further notice about trusted data source.

**Comment by Einlenzer** [comment]
OK, that's what I thought. Thank you very much for the answer.

**Comment by hardknoxni69a** [comment]
no more good sources for human walk but when you use multibot atleast your results are submitted online and u can snipe your other bots catches
