### ISSUE TITLE
How to Use NecroBot.GUI?

### ISSUE THREAD

**Issue by totengby** [Necrobot-Private/NecroBot#346]
NecroBot.GUI downloaded but i don't know how to use.
could any people create some tutorial how to use it pls.

**Comment by pjpena** [comment]
@totengby you should first open NecroBot Console, have it configured to enable WebSockets (I think it is enabled by default) and after NecroBot Console is running, open NecroBot.GUI. 

Console is the bot itself, the GUI is a visual addon.

**Comment by jambonmcyeah** [comment]
You shouldn't open a issue for a question, if you have a question, go to discord https://discord.gg/7FWyWVp
