### ISSUE TITLE
Error when existing backup config.json file is being backup again

### ISSUE THREAD

**Issue by XurWuy** [Necrobot-Private/NecroBot#351]
## Stop! Before you create this issue (you can delete this section when opening the issue):
1. Have you searched to see if there are other Open/Closed issues for the same issue? If so, comment on that issue instead.
2. Have you validated that your config/auth.json and config/config.json is valid JSON? Use http://jsonlint.com/ to check.
3. If your question is referring to how to set up or use the bot, please join our discord instead of posting an issue: https://discord.gg/7FWyWVp 
4. Always confirm that your issue is reproducible, with the config you provide below.

### Expected Behavior:
Overwrite existing backup file config-0.backup.json or incrementing it like config-1.backup.json

### Actual Behavior:
Can't overwrite

### Your config.json:
```
replace this text with the contents of your config.json

```

### (OPTIONAL) Your Log:
[07:43:22] () Backing up config.json to: -:\----\----\10022\config\config-0.backup.json
[07:43:22] () Exception caught, writing LogBuffer.

### Detailed Steps to Reproduce:
1-Must have existing config-0.backup.json
2-Start bot.
3-Error

### Other Information
(Attach zip files if needed.)

Version:
Windows Version:
Win2k8
What is affected (catch, transfer, favorite, GPX, evolve, recycle, snipe, human walk snipe, pokestops, powerup/levelup, other):
Login/start opreation of bot.

**Comment by XurWuy** [comment]
For workaround, I have to manually deleted the backup file, then it can resume....

**Comment by 233635151** [comment]
When backing up, always do overwrite.

**Comment by jjskuld** [comment]
Yup, I have a fix for this in the next release.

**Comment by jjskuld** [comment]
Fixed by 1.0.0.23
