### ISSUE TITLE
MultiBot/MultiAccount Manager 

### ISSUE THREAD

**Issue by Silph-Road** [Necrobot-Private/NecroBot#353]
So currently, if one has more than one account to bot.
The user has to: 
Maintain separate folders with bot config files and then copy paste them into the config folder -> run bot.
OR 
Maintain separate folders with bot files for each account.

MutiAccount Support
Using settings files with naming pattern/mask.

So:
AccountName/config/config.json --> AccountName/config/config.AccountName.json
AccountName/config/auth.json --> AccountName/config/auth.AccountName.json
AccountName/cache already uses AccountName/cache/AccountName-(accounttype).json   "AccountName-ptc.json.
AccountName/config/LastPos.ini --> AccountName/config/LastPos.AccountName.ini
AccountName/config/SessionStats.db --> AccountName/config/SessionStats.AccountName.db
Log files can be done three ways:
AccountName.NecroBot2-2016-11-17-01-05-43.txt
or 
AccountName/AccountName.NecroBot2-2016-11-17-01-05-43.txt
or
AccountName/Logs/AccountName.NecroBot2-2016-11-17-01-05-43.txt

I like the last one:
AccountName/Logs/AccountName.NecroBot2-2016-11-17-01-05-43.txt

The bot will load and offer various options, to load.
In the Console:
What account do you want to use?
1) AccountNameA
2) AccountNameB
3) AccountNameC
4) AccountNameD
5) AccountNameE
Please enter the appropriate #:
`"1" <enter>`
You selected #1 AccountNameA.
Press enter to continue.

**We can further enhance this, if we have the session.db record total run time for each account in the last 24 hours. This can be offered in the selection menu.** 

What account do you want to use?
1) AccountNameA (Last run: 4 hours ago, Last 24 Hour stats:  Runtime=4.5 hours, 560 Pokemons caught and 500 Pokestops visited)
2) AccountNameB (Last run: 10 hours ago, Last 24 Hour stats:  Runtime=7.5 hours, 800 Pokemons caught and 900 Pokestops visited)
3) AccountNameC
4) AccountNameD
5) AccountNameE
Please enter the appropriate #:
`"1" <enter>`
You selected #1 AccountNameA.
Press enter to continue.

**Command Line:**
necrobot2.exe -account Accountname

**Comment by Silph-Road** [comment]
We can then cycle the accounts at a preset interval (with a notification and pause in between).

**Comment by yandraker** [comment]
That would be great. Also a looping sistem where when it finishes with all accounts, to start again from the first account.

**Comment by jjskuld** [comment]
After thinking about this a bit, I think to make it most flexible, the folder names should not be based on credentials, since you may want multiple profiles using same credentials. For example:

AccountNameA - PokestopFarming
AccountNameA - EvolvingPidgeys
AccountNameA - Sniping
AccountNameB - LowLevelFarming
AccountNameB - GPXLoop1
AccountNameB - GPXLoop2
AccountNameB - SantaMonicaPier
AccountNameB - NewYorkCentralPark

**Comment by Silph-Road** [comment]
Hmm, I see.
So, Each account can have a profile (config) based on the goal. (Farming, catching, sniping, etc)
I do think this is rather advanced account management for majority of users but it is a good idea. Plus we will need to centralize or share and update the sessions db for all profiles, so that they all keep track of key stats like pokestops and pokemons and token.

We can do this:
Allow the player to create as many profiles/config they want.
They will have to follow a naming sequence that allows for custom profile names and easy for the bot to recognize.
So something like:
AccountNameA-01-CustomProfileName
AccountNameA-02-CustomProfileName
AccountNameA-03-CustomProfileName
AccountNameA-04-CustomProfileName

Now to manage the profiles we will probably have to make a master account config that is independent file from the traditional config.json
Maybe:
AccountProfileConfig.json

In this we can have a setting that puts the user in control of the order they want the bot to cycle the account profile.


I think the best way would be to let the user put their order of preference:
ProfileOrder: "1,2,3,4,5"

The user would be best handled to see what profile should run after a specific profile, as they would have to configure it manually and set it in its own profile folder.

Plus we will need a blanket check for pokestop visits per account, that triggers an "exit" or switch to next account and does not move to any new profiles, (I understand the bot will always visit pokestops regardless of any setting, and we can only turn on/off catching Pokemon) (unless they use Gpx in a short loop allowing them to stay away from pokestops and evolve for 30 mins)

I like the idea but I think once we get the multi account fully tuned, we can incorporate multi profiles, (but we can/should keep this feature in mind and code in a way that makes it easy to implement later on)

**Comment by hardknoxni69a** [comment]
implemented
