### ISSUE TITLE
CAN ANYONE INVITE ME IN NECRO BOT 2 PRIVAT?

### ISSUE THREAD

**Issue by Korni1987** [Necrobot-Private/NecroBot#355]
VERY THX I WANT TO BOT TOO;)

**Comment by Korni1987** [comment]
DISCORD CHANNEL I MEAN!!

**Comment by ajns73** [comment]
@Korni1987 It's in the Read Me.

**Comment by Korni1987** [comment]
Need help?
Join our Discord server @ https://discord.gg/b93tZDb

-->THIS DONT WORK.

**Comment by jjskuld** [comment]
@Korni1987 Try https://discord.gg/7FWyWVp
