### ISSUE TITLE
Sequence of sequences after logging in again ...

### ISSUE THREAD

**Issue by PeterLustigatGitHub** [Necrobot-Private/NecroBot#356]
Issue after logging in again ...: (Access Token Expired)

The bot evolve first pokemon and then he sends them.

So it can happen that not wanted pokemon evolve.

In this example, before reconnecting a Bulbasaur was caught with CP 500 which would then evolve.

How can this sequence be changed or is there another possibility?

It is supposed to evolve all Pokemon with enough candy which are not previously send.

Settings for this issue:

  "PokemonConfig": {
    "EvolveAboveIvValue": 95.0,
    "EvolveAllPokemonAboveIv": false,
    "EvolveAllPokemonWithEnoughCandy": true,
    "EvolveKeptPokemonsAtStorageUsagePercentage": 90.0,

  "PokemonsToEvolve": [
    "Bulbasaur",

  "PokemonsTransferFilter": {
    "Bulbasaur": {
      "KeepMinCp": 600,
      "KeepMinIvPercentage": 80.0,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinOperator": "and",
      "KeepMinDuplicatePokemon": 0,
      "Moves": [],
      "DeprecatedMoves": null,
      "MovesOperator": "or",
      "CatchOnlyPokemonMeetTransferCriteria": false
    },

**Comment by hardknoxni69a** [comment]
issue resolved
