### ISSUE TITLE
is your maximun distance too small ?

### ISSUE THREAD

**Issue by raymand1589** [Necrobot-Private/NecroBot#362]
## Stop! Before you create this issue (you can delete this section when opening the issue):
1. Have you searched to see if there are other Open/Closed issues for the same issue? If so, comment on that issue instead.
2. Have you validated that your config/auth.json and config/config.json is valid JSON? Use http://jsonlint.com/ to check.
3. If your question is referring to how to set up or use the bot, please join our discord instead of posting an issue: https://discord.gg/7FWyWVp 
4. Always confirm that your issue is reproducible, with the config you provide below.

### Your config.json:
```
replace this text with the contents of your config.json

```

### (OPTIONAL) Your Log:
```
replace this text with only the "relative" portion of your log. (Remove unnessary lines)

```

### Other Information
(Attach zip files if needed.)

Version:
Windows Version:
What is affected (catch, transfer, favorite, GPX, evolve, recycle, snipe, human walk snipe, pokestops, powerup/levelup, other):

**Comment by raymand1589** [comment]
Hi all master
                   I'm the new member from Malaysia, I have the problem when I open Necro-bot2 and coming out the error : no usabled pokestops found in your area,is your maximun too small?
*the version I use is 1.0.0.24
**forgive my limited english

**Comment by hardknoxni69a** [comment]
sounds like ip ban change ip or use proxy

**Comment by jjskuld** [comment]
Closing this one out since i don't think it's a bug.

**Comment by raymand1589** [comment]
Thanks bro. I find the problem from where and solved it already
