### ISSUE TITLE
Error Notification For Update

### ISSUE THREAD

**Issue by hardknoxni69a** [Necrobot-Private/NecroBot#364]
So even with auto update off if you are using .23 instead of the newest .24 you get an error saying needs google info even if though your auth has nothing wrong with it. So if the bot is not going to allow an outdated version to run i believe the error notification should be corrected as everyone thinks they are doing something wrong "Hello Necrobot2 User We Have Updated Our Application For Great Usability Please Enable Auto Update Or Visit Our Website For The New Download" saying check your google info is very confusing especially when the user was just playing with ptc info and did not change anything

**Comment by jjskuld** [comment]
I think I know what message you are taking about. It will be fixed in the next release. Thanks!

**Comment by jjskuld** [comment]
I happened to the confusing message as part of pull #366.
