### ISSUE TITLE
Autosnipe

### ISSUE THREAD

**Issue by gjimenezf** [Necrobot-Private/NecroBot#365]
Autosnipe does not work unless I set CatchPokemon: True. Snipe should be independent of this because CatchPokemon enables local pokemon catch too which I do not want.
I previously sniped in necro with skipflaged and this option with false.

**Comment by soavarice** [comment]
how to setup autosnipe? i cant find the option on config file.

**Comment by samuraitruong** [comment]
This issue doesn't look right, I have check that event catch = false , pokemon still being sniped.

Closed

**Comment by gjimenezf** [comment]
If you are already sniping and change the CatchPokemon to false in the config while the necrobot is running, it continue sniping because the pokemon were already received from the server and stacked but after some time when the stack empties it stop sniping.
You can check it changing CatchPokemon to false and close necro and open again then you will see no pokemon is sniped.
 I even realized that when you have CatchPokemon True it begin to snipe only after you catch your first local pokemon and send its data to server then you begin receiving feeder from server.

**Comment by samuraitruong** [comment]
I made some change, it you have a very long list, then it only get last 10 data from server. that will fix your issue, but I recommend not to snipe many pokemon because bot will out of ball.

YOu need update your config to avoid that issue
