### ISSUE TITLE
Create config that allows to turn ON/OFF autobot change auth when pokestop softban happens

### ISSUE THREAD

**Issue by yandraker** [Necrobot-Private/NecroBot#367]
Just sugesting to create in config the posibility of configurate if you want to switch accounts when a pokestop softban happens. Because at this moment if you get a pokestop softban, automatically switches to the next account, and sometimes you dont really want to switch, just want to bypass the softban and continue normally in same account. I didnt know what config paste here.

**Comment by jjskuld** [comment]
It will be fixed in the next release.

**Comment by samuraitruong** [comment]
Added PokestopSoftbanCount, if set it to 0 it mean not switch ,

**Comment by samuraitruong** [comment]
https://github.com/Necrobot-Private/NecroBot/pull/377/files

**Comment by samuraitruong** [comment]
fixed in #377
