### ISSUE TITLE
SnipePokemonFilter

### ISSUE THREAD

**Issue by soavarice** [Necrobot-Private/NecroBot#368]
Can you add option to for MinLVL or SnipeLVL. I want to snipe pokemons with Min 25 LVL and Min 90 IV.
I try with "SnipeLVL": 25 or "MinLVL": 25 but after strating the bot the line is auto-deteleted.
Thanks

**Comment by samuraitruong** [comment]
level of pokemon is not accuracy so we can't include in the filter.

**Comment by soavarice** [comment]
At least Min CP?
