### ISSUE TITLE
Bot keeps catching after 998 pokemons

### ISSUE THREAD

**Issue by petpetpetvm** [Necrobot-Private/NecroBot#37]
I saw the bot tried to catch pokemons after 998 pkms (as my setting)
I saw it said pkm catch : 999/998 and after that is whole list of catch flee but not stopping
I couldn't copy the note (because i turned it off asap)
Anyway, its seem like a bug that we need to work on
Thanks

**Comment by Silph-Road** [comment]
post your config and log.
Follow the template provided

**Comment by LobsterX** [comment]
check your logs. its there..... paste it here and let us review it for you.


normally when i hit the 998thj pokemon, i'll let the bot rest for 4-8hrs hrs. then i delete the PokemonTS and PokestopTS files and run necro again. these 2 files are the ones keeping track of the no. of pokemon caught and pokestop farmed.


but if your main error is the catch flee, even when you use a real device and try to catch pokemon and it flees, it means you're soft banned.

Stop playing that account  and login-ing in to see for a few hours....

**Comment by petpetpetvm** [comment]
It's not in the logs :/ i couldn't find it, but i'm sure that it was...
for the config, i use really fast config and it runs only 1hr every 15hrs

**Comment by petpetpetvm** [comment]
![1](https://cloud.githubusercontent.com/assets/20893791/18379366/0e77de98-7627-11e6-84ac-2b5341093563.jpg)

**Comment by petpetpetvm** [comment]
maybe there is a bug on counting, it keeps saying 999/998 over and over again

**Comment by petpetpetvm** [comment]
@LobsterX so i will have to keep delete those files everyday ?
Thanks

**Comment by hardknoxni69a** [comment]
is this bug verified dont want to update if its catching past limit

**Comment by petpetpetvm** [comment]
I think it's the problem on counting only

**Comment by LobsterX** [comment]
@petpetpetvm i do not see any catchflee errors in your SS.

the counting's faulty. just delete the 2 files.

**Comment by petpetpetvm** [comment]
It's not in this one, it happened again, thats why i screenshoted this one
Maybe the other one is real catching ban

**Comment by mo0ojava** [comment]
I have fixed this but saw that there were merge conflicts that I have to solve. Not at home atm but will likely have some time later today.

**Comment by mo0ojava** [comment]
#42

**Comment by CreativiTimothy** [comment]
It happens to me too. Steps ro reproduce: Wait 1470 minutes (or whatever you set it to) after having caught 989 Pokemon, and then it then the counter will show up like that 998/998
