### ISSUE TITLE
Feature Request [Multibot]

### ISSUE THREAD

**Issue by RudeCP** [Necrobot-Private/NecroBot#372]
Currently the bot will switch from account to account based on the settings in the config.  However the Catch Limit and Pokestop limit is combined for all accounts.

Please track Pokemon Caught and PokeStops visited per account so that each account can catch and spin up to the limits rather than combining the stats.

**Comment by jjskuld** [comment]
This is a bug. We are aware of it.

**Comment by samuraitruong** [comment]
fixed,  long long long ago
