### ISSUE TITLE
Feature Request [Multibot]

### ISSUE THREAD

**Issue by RudeCP** [Necrobot-Private/NecroBot#373]
When good Pokemon is encountered the bot cycles through accounts so all catch it.  

**Current**
Account A catches Pokemon
Switch to Account B to catch Pokemon
Switch to Account C to catch Pokemon
Continue to bot on Account C

**Desired**
Account A catches Pokemon
Switch to Account B to catch Pokemon
Switch to Account C to catch Pokemon
Switch back to Account A and continue to bot

**Comment by samuraitruong** [comment]
Since multibot will change in cycle, so why we waste 1 more login time to back to A, I think leave it at C is better

**Comment by RudeCP** [comment]
Because you could have just been botting for 55 minutes on C, got 25K exp on C, etc.  The bot switches to A, runs a few minutes, hits something rare and then you end up botting on C for another 55 minutes.

I would think the goal with the Multibot is to evenly, as much as possible, level up multiple accounts.

**Comment by samuraitruong** [comment]
that why I ask you to make a runtime to 15 min , then after 15 min B will have chat change, event I make it come back to B, it doesn't solve th issue , the better implementation is force switch after hard code time to avoid this issue

**Comment by hardknoxni69a** [comment]
If the time isn't up for a does it go back to a? I would love to use the multi bot but haven't really seen details on how it all works a wiki would b amazing

**Comment by samuraitruong** [comment]
closed, since we control by runtime
