### ISSUE TITLE
Updated pokemon go 0.47.1 careful in the last update many took ban

### ISSUE THREAD

**Issue by AndoridNewUser** [Necrobot-Private/NecroBot#378]
Pokemon Go was updated today. Stop using the bot?

**Comment by exnorlas** [comment]
bot dont work, need a update

**Comment by jjskuld** [comment]
No need to worry, 0.47.1 is not forced at the moment. We are anticipating this change will be forced next Wednesday.  We already have auto killswitch for the moment when they make the change so no need to worry just yet.

**Comment by 3nterprise** [comment]
I suddenly got a problem with a bot, when it loads current pokemon status and how many pokemon i viewed and saw it just stops doing nothing. Anyone else have that problem?

**Comment by ajns73** [comment]
@3nterprise Many having an issue with 29. @samuraitruong was addressing it in discord a few minutes ago.

**Comment by 3nterprise** [comment]
ajns73 Can you give me a link to discord in PM? Thank you

**Comment by ajns73** [comment]
Developers have found the issue in .29. Be patient for a fix release.

**Comment by 3nterprise** [comment]
It's all good and it's working now but I'd really like to get into that discord discussion for future purposes :)

**Comment by ajns73** [comment]
https://discord.gg/7FWyWVp << INVITE LINK This might get deleted. Not sure how they feel about this link getting out.

**Comment by jjskuld** [comment]
Hehe, we have the discord link up on the GitHub page.  But maybe it needs to be made more prominent?

**Comment by hardknoxni69a** [comment]
People don't ready the bug out instead

**Comment by AndoridNewUser** [comment]
today force update 0.47 ,need stop bot ?

**Comment by jjskuld** [comment]
We will track 0.47 API updates in #402
