### ISSUE TITLE
Wont evolve

### ISSUE THREAD

**Issue by edgexzx** [Necrobot-Private/NecroBot#379]
### Expected Behavior:
Check and evolve potential pokemons when the bot has run

### Actual Behavior:
Only evolves in the beginning, but when the bot has run, it doesn't check for further potential evolutions.

### Your config.json:

    "EvolveAllPokemonWithEnoughCandy": true,
    "EvolveKeptPokemonsAtStorageUsagePercentage": 90.0,

### Other Information
I have 5 pokemons right now that can evolve and they are listed in the pokemons to evolve config. I also have 90% pokemon storage. But it's not evolving. It only evolves at the start, sometimes it wont too.

Version: latest, but even recent ones werent evolving properly.
Windows Version: 8
What is affected: evolve

**Comment by mo0ojava** [comment]
This is partly thanks to the randomness of HumanRandomActionTask, which is enabled by default. Currently there's a 50 percent chance of evolutions being started each time we have iterated through a whole set of actions OR hit a random 8 to 15 Pokestops. There's actually a TODO-comment in this section indicating the need to check our Pokebag...

**Comment by mo0ojava** [comment]
I have a fix for this and will commit once we are back up (and I've tested it).
