### ISSUE TITLE
Issues with eggs

### ISSUE THREAD

**Issue by Ev0luti0n2016** [Necrobot-Private/NecroBot#38]
Please add delays for eggs...2 eggs hatch and 2 get put in all at the same exact time.

Thanks for keeping this project alive and updated!!! :)

**Comment by mo0ojava** [comment]
It may look like the eggs hatched and got replaced simultaneously but that is not the case. NB doesn't react on the hatching-event right away. Usually the message is delayed by quite some time. I've seen several minutes pass when looking into this. Perhaps not optimal but at least acceptable for now.

**Comment by Ev0luti0n2016** [comment]
@mo0ojava  Thanks for the response :)

  This occurred a few weeks back and Noxx addressed it. It appears that this is not happening with the new update.

   I will look through my logs and post if it does, but I had 2 eggs hatch at the same time and 2 put in at exactly the same time according to the time on NB. 

   As always, thanks for keeping this project going!!!
