### ISSUE TITLE
GUI Still not working

### ISSUE THREAD

**Issue by TheBlueHand** [Necrobot-Private/NecroBot#388]
I configurated the console version of necrobot but when i started up the GUI version it still didn't do anything.....
![necrobot](https://cloud.githubusercontent.com/assets/23506090/20458241/b631dd40-ae9f-11e6-8484-d1287ba22418.JPG)

**Comment by ajns73** [comment]
@TheBlueHand Make sure that the bot is configured on Websocket port 14251 and the GUI is on 14252.

**Comment by TheBlueHand** [comment]
And where can I see which port the GUI is on?

**Comment by msx752** [comment]
@TheBlueHand in the left side menu, find settings

**Comment by AlexTeixeira** [comment]
I currently have the same issue 👍

**Comment by TheBlueHand** [comment]
The Console version is on 12451 and the GUI is on  12452 but the GUI still doens't work.

**Comment by msx752** [comment]
did you allowed application from firewall, may be it will prevent .

**Comment by ajns73** [comment]
@TheBlueHand Do you have SSL enabled on the GUI?

**Comment by TheBlueHand** [comment]
Yes I do but if i turn it off it also doesn't do anything

**Comment by TheBlueHand** [comment]
Maybe I am just doing something wrong? How are you supposed to setup the GUI?

**Comment by ajns73** [comment]
@TheBlueHand Just to clarify: Bot config set to use Websocket on port 14251. GUI set to use Websocket port 14252 with SSL off. Correct?

**Comment by ajns73** [comment]
There really is no setup beyond Websocket activation and correct port number.

**Comment by TheBlueHand** [comment]
I meant that it doesn't matter if the SSL if on or off it just doesn't do anything. And i have it turned on.

**Comment by TheBlueHand** [comment]
But do i have to do something with the console version first?

**Comment by TheBlueHand** [comment]
Because if you download the GUI version there is no config folder in all of the downloaded items.

**Comment by ajns73** [comment]
Console Config should look like this:
"WebsocketsConfig": {
    "UseWebsocket": true,
    "WebSocketPort": 14251

GUI should look like this:
![image](https://cloud.githubusercontent.com/assets/21206609/20499794/a49dbcd4-aff8-11e6-968b-ecbe3e83dd2c.png)

**Comment by TheBlueHand** [comment]
I have all of that but it doesn't work for some reason. And is the SSL supposed to be off?

**Comment by ajns73** [comment]
SSL OFF if port in GUI is 14252

**Comment by TheBlueHand** [comment]
I turned it off but it still shows those white spinning wheels

![necrobot 1](https://cloud.githubusercontent.com/assets/23506090/20499961/f2fc3fe6-b033-11e6-8737-9dbe7fd486de.JPG)

**Comment by TheBlueHand** [comment]
And things like the bot config don't even work.

![necrobot 3](https://cloud.githubusercontent.com/assets/23506090/20500032/29d6ad94-b034-11e6-99e5-4406251b5c0e.JPG)

**Comment by ajns73** [comment]
@TheBlueHand The bot has been killswitched. You shouldn't be botting right now. I thought we were operating on that assumption already. It is going to fail to connect until the bot is back up.

**Comment by TheBlueHand** [comment]
I know but it did the same thing before when the bot was still operating fine.

**Comment by TheBlueHand** [comment]
I just want to fix it now so that i can bot when everything is updated.

**Comment by ajns73** [comment]
@TheBlueHand Well, there is no way of testing now. Waiting until the bot is back up and report back. Those settings should be correct.

**Comment by TheBlueHand** [comment]
Ok i will wait and try again when everything is updated.

**Comment by hardknoxni69a** [comment]
fixed
