### ISSUE TITLE
DataSharing AutoSnipe does not respect PokemonToSnipe list

### ISSUE THREAD

**Issue by jjskuld** [Necrobot-Private/NecroBot#400]
### Expected Behavior:
Pokemon that I don't want to be sniped (Kangaskhan) should not be sniped.

### Actual Behavior:
Pokemon that I don't want to be sniped is being sniped.

### Your config.json:
```
  "SnipeConfig": {
    "UseSnipeLocationServer": false,
    "SnipeLocationServer": "localhost",
    "SnipeLocationServerPort": 16969,
    "GetSniperInfoFromPokezz": false,
    "GetOnlyVerifiedSniperInfoFromPokezz": false,
    "GetSniperInfoFromPokeSnipers": false,
    "GetSniperInfoFromPokeWatchers": false,
    "GetSniperInfoFromSkiplagged": false,
    "MinPokeballsToSnipe": 20,
    "MinPokeballsWhileSnipe": 0,
    "MinDelayBetweenSnipes": 60000,
    "SnipingScanOffset": 0.005,
    "SnipeAtPokestops": false,
    "SnipeIgnoreUnknownIv": false,
    "UseTransferIvForSnipe": false,
    "SnipePokemonNotInPokedex": false,
    "UseSnipeLimit": true,
    "SnipeRestSeconds": 600,
    "SnipeCountLimit": 39,
    "ActivateMSniper": true,
    "MinIVForAutoSnipe": 0
  },

  "DataSharingConfig": {
    "EnableSyncData": true,
    "AutoSnipe": true,
    "DataServiceIdentification": "",
    "DataRecieverURL": "ws://necrosocket.herokuapp.com/socket.io/?EIO=3&transport=websocket"
  },

   "PokemonToSnipe": {
    "Pokemon": [
      "venusaur",
      "charizard",
      "blastoise",
      "beedrill",
      "raichu",
      "sandslash",
      "nidoking",
      "nidoqueen",
      "clefable",
      "ninetales",
      "golbat",
      "vileplume",
      "golduck",
      "primeape",
      "arcanine",
      "poliwrath",
      "alakazam",
      "machamp",
      "golem",
      "rapidash",
      "slowbro",
      "muk",
      "cloyster",
      "gengar",
      "exeggutor",
      "marowak",
      "hitmonchan",
      "lickitung",
      "rhydon",
      "chansey",
      "starmie",
      "scyther",
      "magmar",
      "electabuzz",
      "jynx",
      "gyarados",
      "lapras",
      "ditto",
      "vaporeon",
      "jolteon",
      "flareon",
      "porygon",
      "kabutops",
      "aerodactyl",
      "snorlax",
      "articuno",
      "zapdos",
      "moltres",
      "dragonite",
      "mewtwo",
      "mew"
    ]
  },
```

### (OPTIONAL) Your Log:
```
[12:57:21] (SNIPER) (MSniperService) Sniping a Kangaskhan with 44.36 IV at -33.8766450427651,151.186613858789...
[12:57:29] (BERRY) Used Razz Berry | 37 remaining
[12:57:31] (PKMN) (CatchEscape) | (Normal) Kangaskhan Lvl: 23 CP: (1222/1342) IV: 44.00% | Chance: 12.49% | 12063819.42m dist | with a UltraBall (0 left). | lat: -33.876645 long: 151.186614 | Move1: MudSlapFast Move2: Earthquake | Rarity :VeryRare
[12:57:32] (PKMN) No Pokeballs - We missed a Kangaskhan with CP 1222

```

Version: 1.0.0.30
Windows Version: win7
What is affected (catch, transfer, favorite, GPX, evolve, recycle, snipe, human walk snipe, pokestops, powerup/levelup, other): snipe

**Comment by Dreker** [comment]
The correct list is:

"SnipePokemonFilter": {
    "Lapras": {
      "EnableSnipe": false,
      "SnipeIV": 0,
      "Moves": []
......

**Comment by jjskuld** [comment]
@Dreker This issue is not related to SnipePokemonFilter actually.  The issue is that in the code the MSniper auto snipe mechanism is totally unrelated to the original snipe mechanism.  But it's a separate bug that `EnableSnipe` is not being auto populated into the config.json so thanks for bringing that up.

@samuraitruong So the MSniper snipe re-implemented portions of the snipe functionality but missed a bunch of other things:

1. MSniper snipe never checks snipe conditions: `UseSnipeLimit`, `SnipeCountLimit`, `SnipeRestSeconds` are ignored. These are for softban protection since i think it used to be that you cannot snipe more than 39 pokemon in 10 minutes (or something like that).
2. MSniper snipe never checks `PokemonToSnipe`.  This is important because it allows whitelist functionality.  Note that `PokemonsToIgnore` is a separate and related featured which is for blacklist functionality.  So both are useful.

**Comment by junreygc** [comment]
Is there any update on this issue?
I would like to snipe just pidgey caterpie and weedle.
I want to focus on trainer level.
Is there a way to make it follow the PokemonToSnipe list or even the PokemonToIgnore list?

**Comment by junreygc** [comment]
Ok I figured it out using Dreker's comment, thanks!

**Comment by samuraitruong** [comment]
PokemonToSnipe is out of date, PokemonSnipeFilter is the better one since it support IV and Moves

**Comment by jjskuld** [comment]
The problem I was trying to solve was sniping only a few specific pokemon, like Lapras and Dragonite, and ignore everything else.  I finally figured out how to do this by reading the wiki page by @samuraitruong.  Looks like you need to set:

```"MinIVForAutoSnipe": 101,```

and then

```
"Lapras": {
      "SnipeIV": 0,
      "Moves": [],
      "Operator": "or",
      "VerifiedOnly": false
    },
    "Dragonite": {
      "SnipeIV": 0,
      "Moves": [],
      "Operator": "or",
      "VerifiedOnly": true
    },
```

Although not super intuitive, it works.  We should probably remove the ```PokemonToSnipe``` list then since it is useless and confusing.

The ```PokemonToSnipe``` also had a list of teleport locations to teleport to for sniping.  The bot would teleport to a location, do a map scan, find pokemon to snipe, and snipe them, then teleport to the next location.  I think this is probably not useful anymore as well since this was added before when teleporting didn't trigger softbans and captcha's like it does today.

Unless there are any objections, I think we can just remove this old setting.

**Comment by momentosnaps** [comment]
I have set it up as mentioned by @jjskuld suggested above but it's still sniping Pokemons below the SnipeIV settings. What could be wrong here? 

    "Dratini": {
      "SnipeIV": 90,
      "Moves": [],
      "Operator": "or",
      "VerifiedOnly": true,
      "Priority": 5,
      "AustoSnipeCandy": 2000
    },

**Comment by hardknoxni69a** [comment]
having a candy value will allow to snipe below value because its for candy and with miniv at 101 and setting snipefilter to the pokemon you want it will only snipe those pokemon on the filter list the pokemontosnipe list is better used for catching filter put the only pokemon you want to catch locally and turn on use pokemontosnipe filter and it will only catch those pokemon locally
