### ISSUE TITLE
[Enhancement] Check For Kill Switch Every Second

### ISSUE THREAD

**Issue by jambonmcyeah** [Necrobot-Private/NecroBot#403]
To prevent people still botting when the api is forced getting banned, check for kill switch every second

**Comment by ajns73** [comment]
huh?

**Comment by 233635151** [comment]
I guess it is by session. So it doesn't help by checking every second.

**Comment by jjskuld** [comment]
Not even the official client does this. We are already emulating client behavior as far as kill switch is concerned.  The official client only checks on login and then periodically after that. 

So if you were to check every second, we would unnecessarily be drawing Nia's attention.  Every necrobot2 client would be acting as a DDOS client against Nia's API!  You would also chew up CPU unnecessarily.

**Comment by jjskuld** [comment]
@233635151 Correct. With the official client, it checks by session, so if you logged in and the api had not been forced yet, but was forced during your current session, the official client would continue to make api calls using the old api.  And then after a certain period of time, it checks and displays a message if it needs an update.   So checking every second isn't necessary and doesn't even help.
