### ISSUE TITLE
(Request) Mass evolving settings (Pidgey Hoarding ((EXP Trick))

### ISSUE THREAD

**Issue by raymonders** [Necrobot-Private/NecroBot#41]
Can you devs add something like "EvolveKeptPokemonsWhenThisManyReady" 
### Expected Behavior:
where basically, the bot will function normally, catching and transferring pokemon, until a certain number of pokemon in the "PokemonsToEvolve" list is achieved. For example, if 

"EvolveKeptPokemonsWhenThisManyReady": 150,
"EvolveAllPokemonWithEnoughCandy": true, 
"KeepPokemonsThatCanEvolve": true,
    and 
"PokemonsToEvolve": [
    "pidgey"

the bot will catch and transfer like normal until 150 pidgeys are caught and 1800 candies are obtained.
and if we add caterpie and weedle to the "PokemonsToEvolve" filter, it will count those pokemon and candies too.

### Actual Behavior:
Bot evolves all kept pokemon when "EvolveKeptPokemonsAtStorageUsagePercentage" is reached

**Comment by samuraitruong** [comment]
We have XP limit per day so that trick doesn't work any more.

**Comment by raymonders** [comment]
@samuraitruong i know about the xp limit. i was planning on running this config only 1 or 2 times per day to still go under the radar

**Comment by hardknoxni69a** [comment]
what is this xp limit you speak of?

**Comment by nullum** [comment]
I agree, much better than the storageusagepercentage thing

**Comment by petpetpetvm** [comment]
how much is the xp limit ?

**Comment by hardknoxni69a** [comment]
@samuraitruong can you please elaborate on the daily xp limit as i have not heard of a specified number and as always would like to be safe as possible

**Comment by vfuyong** [comment]
I don't think there is an explicit XP limit. When having pokemon limit and pokeshop limit, your XP is already limited.

**Comment by Silph-Road** [comment]
Words for the request and pull request.

The issue with this feature is that you are amassing a LOT of XP in a very short amount of time. 
If you want to hoard a set amount of pidgeys you can add pidgey manually to the config in  `"PokemonsTransferFilter": {`
and changing 
`"KeepMinDuplicatePokemon": 60,`

But...."KeepPokemonsThatCanEvolve": true, will do that for pokemon's in that list anyways.

Bigger issue is that.... its a red flag if niantic checks to see who all hit the theoretical xp limit for 30 mins, which is essentially: 500 x 2 x 60 = 60,000 EXP/30mins or 120,000 EXP/hr.
```
500 for evolve
x2 for lucky egg
x 60 for 30 second animation delay (30 mins / 30 seconds.)
```

Evolving 120 pokemons is very unhumanistic, when done back to back, with no variance in wait time in between.

**The original feature mass evolve (w/ lucky egg) feature was added before any ban waves, so.... keep that in mind.**

**Comment by mo0ojava** [comment]
The animation duration was lowered to 18 sec in the October patch.
