### ISSUE TITLE
Pause settings

### ISSUE THREAD

**Issue by boscorelly** [Necrobot-Private/NecroBot#440]
Hi,

i was using previously Pokemongo-F bot.

It has settings to fake pauses : sleep pause, eat pause... After looking in necrobot, there is not this option. 

Is it possible to add this function ?

**Comment by hardknoxni69a** [comment]
i would reccomend making a script for now until the makers incoorparate something like this i currently have 4 bots that run 2 at a time 1 hour on 1 off for 5 hours takes 1 hour brake then repeats

**Comment by MerlionRock** [comment]
@boscorelly 

Clone this for Pokemongo-F bot:  https://github.com/pogarek/PokemonGo-Bot/tree/dev
or you can wait for awhile. It is in the process of merging,

Check also the new requirement for hashing key in auth.json
It should be working for Window users.

**Comment by boscorelly** [comment]
i am no more using pokemongo-f bot.
necro is more user friendly.

where are the infos about the hashing key in necro ? (or i have not understood)

**Comment by samuraitruong** [comment]
@boscorelly  has you find out how to use hash key?

**Comment by hardknoxni69a** [comment]
after you purchase your api key you can enter it when bot first loads

**Comment by boscorelly** [comment]
you mean the hash key to use in config.json to make the bot working ? Yes, this is enabled :)

**Comment by hardknoxni69a** [comment]
:Necro
@echo off
cd C:\Users\X\OneDrive\Public\PokeCracks\X\
start /min C:\Users\XOneDrive\Public\PokeCracks\X\NecroBot2.exe
timeout 21600
taskkill /IM necrobot2.exe
timeout 21600
cd C:\Users\X\OneDrive\Public\PokeCracks\X\
start /min C:\Users\X\OneDrive\Public\PokeCracks\X\NecroBot2.exe
timeout 21600
taskkill /IM necrobot2.exe
timeout 21600
goto Necro
