### ISSUE TITLE
[Discussion] How to play safe with purchased key

### ISSUE THREAD

**Issue by mahavidhan** [Necrobot-Private/NecroBot#445]
Is there a way to disable recycling? 
What settings are needed to tell the bot ONLY to spin and catch? 
in order to play safe, Is google walk better or bot walk?
How much MaxTravelDistance and WalkingSpeed to keep?
While the bot is ON/Walking, can we safely remove items from bag from GUI and transfer pokemons from GUI without any risk of ban or having extra RPM?
Advice any other things to be safe and avoid risk of ban

Thanks

**Comment by junreygc** [comment]
i just comment on trashing while walking, i think there is no extra RPM to trash items while walking because there is already a fix RPM even when you're not doing anything, in the official PoGo app every 30 seconds you will see a white disc spinning on the upper left corner even when you are idle, so that white disc is still a request from the server, so walking or not the same RPM

**Comment by mahavidhan** [comment]
I have few questions if you can answer
1. by trashing while walking you mean trashing through the GUI or is there a setting in config?
2. In the email it was stated that "This Key has 150 sessions and lasts 31 days from the time of first use." Does this means I can use this only 150 times or 31 days whichever is less?
3. (ATTENTION) Encounter problem: EncounterAlreadyHappened. What does this mean?
During initial setup, it asked if I want to set the following
a.Waking speed settings
b.Telegram Feature
c.Proxy Feature
d.WebSocket Feature
I opted No for all above. Is that right?
5. There are few references given to load pokemons from Pokecrew, PokeWatcher, Pokesnipers, Pokeradar etc. Do I set true or false to these items?
6. Is there a setting where a duplicate pokemon is trasferred immediately on catch? In my setting a lot of pokemons are getting transferred in one go which I do not want.
Thanks

**Comment by junreygc** [comment]
1. i don't see an option for trashing while walking in config
2. i understand it as 150 requests per minute for 1 month
3. i understand it as repeating pokemon+coordinates entries gives that error
    i set 20 walk speed and yes to web socket then the rest a no, but i'm on legacy API, did not buy a hashing key
4. i set true to all of them for more supply of pokemon+coordinates
5.  "TransferDuplicatePokemonOnCapture": <-- set to true
     "UseBulkTransferPokemon": <-- set to false

**Comment by mahavidhan** [comment]
I know there is no such option to trash while you walk. I wanted to understand how do you do it. Do you trash it from the GUI?
Where can I get more info on websocket? about how it can be used with necro etc.?
I tried setting true to pokecrew, pokewatcher etc but get an error "error loading ......." any idea why?
Thanks

**Comment by junreygc** [comment]
i haven't tried that on bot, only on official PoGo app, i'mjust having an idea about extra RPM
i get info about WebSocket from Wikipedia, but the guys behind necrobot can explain to you fully
sniping server is currently offline as the bot says, so no feed for our snipers right now that's what i understand

**Comment by junreygc** [comment]
i have heard that latest API is also showing captcha, i can't confirm this though, so this means accounts on paid API are also flagged

**Comment by hardknoxni69a** [comment]
the key itself is from 3rd party so they themselves dont really care how you use your rpm so i wouldnt worry theres 150 request per minute to server so usually good for 3-4 accounts play safe like you would in normal app but every action is going to be a request just like the real app if your asking for info then its a request but with latest api you wont get captchas but anyway please join our discord though great ccommunity to help with basic questions and make sure you have all your answers
