### ISSUE TITLE
Loosing 2 berries after Pokemon escapes

### ISSUE THREAD

**Issue by Danny-0815** [Necrobot-Private/NecroBot#447]
### Expected Behavior:
Bot should throw a
![unbenannt](https://cloud.githubusercontent.com/assets/21310478/21545875/39ea1288-cddb-11e6-87b3-f446b73602f8.PNG)
![unbenannt](https://cloud.githubusercontent.com/assets/21310478/21545885/44088a4c-cddb-11e6-8131-5717c2fdad40.PNG)

 second Berry, after Pokemon had escaped after the first throw.

### Actual Behavior:
Bot seems to throw two(!!!) berries, after Pokemon had escaped after the first throw.

### Your config.json:
```
UseMaxBerries is on the standard value (30).
```
(This is not the same issue as before, when the bot used to throw a second berry after the bot missed a Pokemon... Here, the bot does correctly not throw a second berry after a wild Pokemon had been missed, but seems to throw two when a wild Pokemon had escaped!)

### Other Information
(Attach zip files if needed.)

Version: 1.0.0.42
Windows Version: 10
What is affected (catch, transfer, favorite, GPX, evolve, recycle, snipe, human walk snipe, pokestops, powerup/levelup, other): catch

**Comment by samuraitruong** [comment]
Bot didn't use 2 berry,  just the update on screen wrong, I thought it been fix in release 1.0.0.45

I will close this issue, if you see it in latest release please reopen this, thanks
