### ISSUE TITLE
Console didn't start, stuck after login

### ISSUE THREAD

**Issue by akashgupta0210** [Necrobot-Private/NecroBot#448]
Whenever i start console, it stuck after login. I have waited around 1hour but nothing happens.

Screenshot 
![untitled](https://cloud.githubusercontent.com/assets/14937702/21546988/22c4f658-ce09-11e6-9d2a-b9523624e86d.jpg)

Windows Version: Windows 10

**Comment by mahavidhan** [comment]
Well.. I have limited knowledge but I can suggest something
Are you able to login on your phone?
Try changing IP?
Try configuring for Google API?
Check lat/long coordinates

**Comment by junreygc** [comment]
after you try mahavidhan's suggestions and you can login on your phone there might be a captcha waiting for you,
i have no idea if the auto-resolve feature is working because i turn it off, so better solve the captcha on your phone

**Comment by akashgupta0210** [comment]
@junreygc 
Thanks, i solve the captcha on mobile and then run the console.
It works.
