### ISSUE TITLE
Disabling PogoDev

### ISSUE THREAD

**Issue by SLASHLogin** [Necrobot-Private/NecroBot#452]
After first run, and after my personal configuration I wanted to turn on NecroBot, but I saw this:

  - Configuration is up-to-date. Schema version: 6
  - Validating config.json...
  -  JSON Exception: Unterminated string. Expected delimiter: '. Path 'DeviceConfig.FirmwareType', 
     JSON Exception: Unterminated string. Expected delimiter: '. Path 'DeviceConfig.FirmwareType', line 41,                  position 1.
 - You select pogodev API but not provide API Key, please press any key to exit and correct you auth.json,
    The Pogodev API key call be purchased at - https://talk.pogodev.org/d/51-api-hashing-service-by- pokefarmer

I were trying to fix this in files just like that: "APIConfig": {
    "UsePogoDevAPI": false,
    "AuthAPIKey": null,
    "UseLegacyAPI": false
},

but I still have problem

and with first error I dont know how to deal with, please help me.

And I'm really sorry for my english but I'm not english native speaker.

**Comment by macinmn** [comment]
well you need to run one or the other ( = true). one value needs to be true, and if the first, you need the key populated.

**Comment by samuraitruong** [comment]
if you don't want pogodev api, 

"UseLegacyAPI": true
