### ISSUE TITLE
New pokemons images

### ISSUE THREAD

**Issue by boscorelly** [Necrobot-Private/NecroBot#456]
hi,

it seems that new pokemons (151+) don't have their picture  is it possible to find them somewhere, and add them in the bot ? (and fork necro to add them also)

**Comment by samfloKIT** [comment]
I've found the sprites on a wiki (e.g. Pichu - http://www.pokewiki.de/Datei:Pok%C3%A9monsprite_172_GO.png just change the ID to get the other ones) renamed the files to <ID'>.png and copied it to 'NecroBot2.GUI\WebUi\PokeEase-Necrobot-Private\images\pokemon' That's worked fine for me, but I don't have any clue where to add the files in the repo and do a PR...
The Gen 2 Pokemon that are curently available in Pokemon GO and the wiki are:
\# 172 Pichu, \# 173 Cleffa, \# 174 Igglybuff, \# 175 Togepi, \# 176 Togetic, \# 238 Smoochum, \# 239 Elekid and \# 240 Magby
![172](https://cloud.githubusercontent.com/assets/11162603/21743911/2c741c06-d50c-11e6-9e9a-619985c745e5.png)![173](https://cloud.githubusercontent.com/assets/11162603/21743914/3b099f3e-d50c-11e6-90d2-3d50e0945b8e.png)![175](https://cloud.githubusercontent.com/assets/11162603/21743920/4eb2b232-d50c-11e6-9bf3-02f65424b49f.png)  *...*

**Comment by boscorelly** [comment]
hi,

i use the zipped ui because the installator is unusable.
i don't have this folder :/

**Comment by hardknoxni69a** [comment]
updated
