### ISSUE TITLE
KeepPokemonsThatCanEvolve 

### ISSUE THREAD

**Issue by Ekans1** [Necrobot-Private/NecroBot#457]
First, my understanding of how this feature works, as per the wiki:

Rounddown(Number of candies / Candies per evolution) = Number to keep. 

When transferring, I understand that the numbertokeep (calculation above) of each type are not transferred.  

However, you get a candy for evolving, so if you had 23 pidgey candies you should be keeping 2 pidgeys and would then have 2 potential evolutions. I believe that the current code would determine that only one pidgey should be kept in the case of 23 candies. 

**Could we change the way potential evolutions and number to keep are calculated?** I have an idea of what this calculation could look like. 

As a further build, we could even consider that you then transfer the resulting pidgeotto, so could actually get two evolutions out of 22 candies, but that would require changing the interaction with the transferring algorithm. 

Thanks,

**Comment by hardknoxni69a** [comment]
transferring pokemon candy i dont think should be considered but you are awarded a candy for evolve so 23 candies should keep 2 pidgeys

**Comment by jjskuld** [comment]
This will be fixed when #705 is fixed.
