### ISSUE TITLE
Evolutions carried out every interval

### ISSUE THREAD

**Issue by Ekans1** [Necrobot-Private/NecroBot#458]
Hi All, 

This might be a bug, or simply user error. 

### Detailed Steps to Reproduce:

Key config lines:

    "EvolveKeptPokemonsOverrideStartIfThisManyReady": 50,
    "EvolveAllPokemonAboveIv": false,
    "EvolveAllPokemonWithEnoughCandy": false,

**Comment by hardknoxni69a** [comment]
i figurted this out they worded the explanation and config incorrrectly but "EvolveKeptPokemonsOverrideStartIfThisManyReady" x whatever x equals will trigger evolutions if you have this many pokemon total not total of evolutions but total of bag in general so as long as you have 50 pokemon it will trigger evolutions i had to set to 999

**Comment by hardknoxni69a** [comment]
i fixed this in the latest build please update check EvolveKeptPokemonsOverrideStartIfThisManyReady has been updated to EvolveKeptPokemonIfBagHasOverThisManyPokemon
