### ISSUE TITLE
"EvolveKeptPokemonsOverrideStartIfThisManyReady" ISSUE!!!

### ISSUE THREAD

**Issue by hardknoxni69a** [Necrobot-Private/NecroBot#459]
This setting should start evolving once i reach 300 evolutions but instead it evolves if i have a total of 300 pokemon total please update so it checks correct value

**Comment by pokkemonner** [comment]
I can confirm this issue. Makes using luckyegg's as good as impossible.

**Comment by hardknoxni69a** [comment]
I believe i fixed this problem please check latest hourly build
