### ISSUE TITLE
Its not stopping.. smh

### ISSUE THREAD

**Issue by Lord-Haji** [Necrobot-Private/NecroBot#461]
This is taking pretty much time
its continuously loading 
idk why works fine when i used the electron client 

but when i use both the bot and client together 
some what like  this
![scrnsht](http://image.prntscr.com/image/c143f78eaf0248aaa977ced9d7ea9265.png)

Although i use a 8 mbps network

**Comment by hardknoxni69a** [comment]
we now have updated Electron and now have our own GUI Necrobt.WIN check out the latest builds please you will be pleased :-)
