### ISSUE TITLE
Bot creates new device config after each start

### ISSUE THREAD

**Issue by Danny-0815** [Necrobot-Private/NecroBot#462]
### Expected Behavior:
Bot keeps a set device config within the auth.json, after DevicePackageName is set to "custom".

### Actual Behavior:
Bot creates a new device config after each start, even though DevicePackageName is set to "custom" instead of to "random".
Also worth to mention: The randomly created device is every time a (different) iOS device. The one I want to keep is an android one (see below).

### Your auth.json:
```
{
  "AuthConfig": {
    "AuthType": "google",
    "GoogleUsername": "xyz@gmail.com",
    "GooglePassword": "xyz",
    "PtcUsername": null,
    "PtcPassword": null
  },
  "ProxyConfig": {
    "UseProxy": false,
    "UseProxyHost": null,
    "UseProxyPort": null,
    "UseProxyAuthentication": false,
    "UseProxyUsername": null,
    "UseProxyPassword": null
  },
  "DeviceConfig": {
    "DevicePlatform": "android",
    "DevicePackageName": "custom",
    "DeviceId": "abc123",
    "AndroidBoardName": "abc123",
    "AndroidBootloader": "abc123",
    "DeviceBrand": "samsung",
    "DeviceModel": "SM-N9005",
    "DeviceModelIdentifier": "hltexx",
    "DeviceModelBoot": "qcom",
    "HardwareManufacturer": "samsung",
    "HardwareModel": "SM-N9005",
    "FirmwareBrand": "hltexx",
    "FirmwareTags": "release-keys",
    "FirmwareType": "user",
    "FirmwareFingerprint": "samsung/hltexx/abc123"
  },
  "APIConfig": {
    "UsePogoDevAPI": true,
    "AuthAPIKey": "ABC123",
    "UseLegacyAPI": false
  },
  "AllowMultipleBot": false,
  "Bots": []
}
```

### Detailed Steps to Reproduce:
I want to have device settings of my actual phone, so I used ADB shell to read out all the different settings. In order to keep those settings in the auth.json, I set the DevicePackageName from "random" to "custom".
While in earlier versions of the bot this worked super fine (some months ago), more recent versions and also the current version change my device config anyway after each start of the bot. The randomly created new device config is always one of the iOS devices.
(Unfortunately, I cannot tell in which update it actually started to happen.)

Version: 1.0.0.46
Windows Version: 10
What is affected: auth.json/log in

**Comment by junreygc** [comment]
i also want my phone on device settings, need to get a fix on this

**Comment by jjskuld** [comment]
The problem is that Android device info is not supported.  The API has only been cracked for iOS devices so if you keep re-entering Android device info it will just keep overwriting it with random iOS device.

This will most likely never be fixed since Pogo API cracking teams have already cracked iOS and the chance of cracking Android is very small (with Google SafetyNet protections on Android).
