### ISSUE TITLE
GUI pop-up windows do not scroll

### ISSUE THREAD

**Issue by Jotunblood** [Necrobot-Private/NecroBot#47]
### Expected Behavior:
Pop-up windows in GUI for Pokémon, Items, etc... should allow for scrolling up and down to see all objects in list.

### Actual Behavior:
Pop-up windows do not scroll.

### Detailed Steps to Reproduce:
Click on Pokémon or Backpack from sidebar menu. Opened window does not scroll up or down, when there is more information

### Other Information
(Attach zip files if needed.)

Version: 0.9.8.6
Windows Version: 10
What is affected (other): GUI, ability to see all information

**Comment by nullum** [comment]
Yep, same here

**Comment by hardknoxni69a** [comment]
I noticed this as well fortunately i have surface so dragging it works but there is no slider bar and scrolling doesnt work

**Comment by god0911** [comment]
same here. Can't scroll in menu function views.
