### ISSUE TITLE
Auto transfer favourite pokemon

### ISSUE THREAD

**Issue by yandrake** [Necrobot-Private/NecroBot#471]
It would be great if it could be implemented a function that could be turned true or false, where you can choose if you want to protect favourited pokemon for transfering them or not, because right now it transfers pokemon if they are favourited.

**Comment by jjskuld** [comment]
It should definitely not be auto transferring favorite pokemon. Do you have a log for this?

**Comment by samuraitruong** [comment]
Not, he mean that he want transfer favo pkm

**Comment by suisse5** [comment]
Same problem for me, favourited Pokemon are also transferred according to the transfer rules. 
A "DoNotTransferFavourited: True/False" could be useful.

**Comment by samuraitruong** [comment]
This is an issue both on Necrobot and Niantic :)

Since 1.0.0.53 we has fixed thhe issue, that is bulk transfer with WeakPokemonTransfer work togethers
