### ISSUE TITLE
Fix sniper delays

### ISSUE THREAD

**Issue by yandrake** [Necrobot-Private/NecroBot#473]
It seems like when you snipe a pokemon, it takes between 30 sec to one minute to snipe the pokemon, and it doesnt matter the delays you set to snipe, it always takes that time. I dont know if its posible to touch the amount of time it takes to snipe the pokemon and make it with a fast capture, but It would be great if it could be fixed.

**Comment by junreygc** [comment]
I think it is because of the latest API. When I try to teleport using the official PoGo app there is a delay in loading pokestops, tracker updates and spawns. When you snipe you are teleporting so you experience delays in spawns. Regarding fast capture you can force excellent throws, curved balls and disable missed throws.

**Comment by samuraitruong** [comment]
nop, I turn of snipe when walking, that is reduce change to be softban, I will add config to allow snipe on walking, but then it will trigger lot of softban

**Comment by mahavidhan** [comment]
Is there a setting to snipe while not walking? Is it even possible not to walk, not to spin and just snipe? if yes, what settings are required in config? and in what intervals?

**Comment by junreygc** [comment]
samuraitruong already turned the walking sniper off. So sniping now is on Pokestops if you are not using GPx pathing. Try to lower your Pokestop limit and it will not spin when limit reach. Also try disable wild pokemon catching so no wild pokemon being caught.

**Comment by mahavidhan** [comment]
Great !
There is a "CatchPokemonWhileWalking": true, option under HumanWalkSnipeConfig and "CatchPokemon": true, under PokemonConfig Which one to set it to false to disable wild pokemon catching?
Is there any kind of documentation/wiki somewhere to see how the GPx pathing works?
Also any documentation available to see how multi-botting works with this version of necrobot?
Thanks.

**Comment by junreygc** [comment]
If HumanWalkSnipe is disabled then try the CatchPokemon setting.
For GPX this may help you: [Click Here!](https://github.com/Necrobot-Private/NecroBot/wiki/config.json#location)
For multiple bots: [Click Here!](https://github.com/Necrobot-Private/NecroBot/wiki/Multiple-BOTs-config)

**Comment by mahavidhan** [comment]
Thanks
But I am still confused with the GPX pathing. Where can I download a sample GPX file?

**Comment by samuraitruong** [comment]
Thought it has been fixed in v1.0.0.50
