### ISSUE TITLE
Repeat login and logout

### ISSUE THREAD

**Issue by gokouflash** [Necrobot-Private/NecroBot#474]
Repeat login and logout when starting 100 or more accounts
Is there a way to improve it?

I get errors like this
(error) Pokefamer Hash API (http://pokehash.buddyauth.com/api/v121_2/hash) might down!
[08:28:59] (error) The bot will now exit after hitting the enter key.

**Comment by samuraitruong** [comment]
check you network, seem it not reached to pokefamer api

**Comment by samuraitruong** [comment]
your API has limit, you need 50 key to run 100 acc, how many key you have?

**Comment by gokouflash** [comment]
I solved it, thank you samuraitruong
I was running 100 accounts at 35 key
