### ISSUE TITLE
automatic reconnection

### ISSUE THREAD

**Issue by gokouflash** [Necrobot-Private/NecroBot#477]
Is automatic reconnection possible?

(error) Pokefamer Hash API (http://pokehash.buddyauth.com/api/v121_2/hash) might down!
[08:28:59] (error) The bot will now exit after hitting the enter key.

**Comment by MerlionRock** [comment]
Hashing server not able to cope with the volume....

If you make it reconnect automatically, it will only make it worst....

**Comment by mahavidhan** [comment]
@MerlionRock What do you mean by it will make it worst? will it call for a ban?? I also faced this issue several times today. What could be a workaround for this and what is the right thing to do if this happens?

**Comment by 6Vampire6** [comment]
There should be a possibility to automatically restart the bot / retry login if this occurs. Currently, you can't let the bot run for more than some minutes until it stops and does no reconnect. So what about a configurable reconnect time with minimum 1 minute or so?

**Comment by odhinne** [comment]
ok, so now that we have to pay for this service, and we can't connect with it, what are they going to about it? When it was a free bot, you could say hey, it's free anyway, deal with it, we'll fix it as soon as we can. I've been getting this error for over a day now. when can we expect them to make whatever upgrades are needed to handle the volume?

**Comment by gokouflash** [comment]
I will donate $ 100.Please upgrade.

**Comment by junreygc** [comment]
It is expected like the Niantic servers it can't handle all connections. They need to expand fast because people are paying.

**Comment by samuraitruong** [comment]
yeah, this will release tonight mate,

**Comment by MerlionRock** [comment]
I have nothing against automatic reconnection. I'm just trying to say this is just a hashing server issue. From what I've observed for the past 3 days, At my timezone (Asia), the hashing server throw zero errors in the morning, and once it's night time, it start to throw the hash API might be down error. So I assume there's a increase of calling to hashing server which cause it to go down temporary.

Reconnection is one solution, but I would suggest that it should pause for a much longer period (example an hour) after 3 failed attempts (within a 5 mins window).

**Comment by samuraitruong** [comment]
fixed, https://github.com/Necrobot-Private/NecroBot/pull/481

**Comment by samuraitruong** [comment]
@gokouflash remember your 100$, I will invest that for server cost hosting snipe data :)

**Comment by gokouflash** [comment]
Thank you XD
Where can I make donations?

**Comment by samuraitruong** [comment]
hi @gokouflash  - http://www.mypogosnipers.com/# donate to snipe server , you will find donate button on popup or footer.

**Comment by gokouflash** [comment]
donation error (;ω;)

PayPal does not currently support donation payments from buyers of JP. We apologize for any inconvenience
