### ISSUE TITLE
Visual Studio Warnings And Errors

### ISSUE THREAD

**Issue by hardknoxni69a** [Necrobot-Private/NecroBot#479]
Running The Solution through the most common editor Visual Studio results in many errors and warnings even with all the packages restored. There seems to be many old references that are no longer in service and cause issues. Could a dev review the errors and clear them out so the app is a clean build with no waste. It will make the process much easier for new devs to begin helping and contributing

**Comment by samuraitruong** [comment]
there is no error, warning is just some nice to have not required.

**Comment by jjskuld** [comment]
I fixed a bunch of these errors. Not all of them are gone since I think some of the warnings especially regarding async code is not as easy to get rid of.

**Comment by samuraitruong** [comment]
warning for async just fine for me,
