### ISSUE TITLE
Overlapping Text and "undefined" candies in individual Pokémon info

### ISSUE THREAD

**Issue by Jotunblood** [Necrobot-Private/NecroBot#48]
### Expected Behavior:
Candy count should show the correct number of candies, text should not be obscured or overlapping.

### Actual Behavior:
Candy count is undefined, confirmation text is overlapping and indistinguishable. Seems to be more prominent on 1st and 2nd evolution stages, e.g., Squirtle, Wartortle.

### Detailed Steps to Reproduce:
Click on an individual Pokémon from the list to bring up its stats.

### Other Information
[2016-09-09 15_00_30-NecroBot-Private Team GUI _ PokeEase.zip](https://github.com/Necrobot-Private/NecroBot/files/464632/2016-09-09.15_00_30-NecroBot-Private.Team.GUI._.PokeEase.zip)

Version: 0.9.8.6
Windows Version: 10
What is affected (transfer, favorite, evolve, powerup/levelup, other): Transfer, evolve, powerup

**Comment by petpetpetvm** [comment]
I don't use it, but i think i get it right... I think underfined because of you don't have that pokemon in your inven. and there is no way that it can check it ? Even with the optional app
