### ISSUE TITLE
Filter catch not met

### ISSUE THREAD

**Issue by mahavidhan** [Necrobot-Private/NecroBot#480]
Whenever I manually try to snipe pokemons, I get this error Filter catch not met. Do I need to change some setting in config? 
Thanks

**Comment by junreygc** [comment]
Use default config it won't give that error.

**Comment by mahavidhan** [comment]
You mean the one that comes with the release zip file? But I have made lot of changes to the config and will be difficult to get those changes incorporated again in the default file. Is there a particular setting that is causing this error?

**Comment by junreygc** [comment]
I know only one setting which filters sniping and that is SnipePokemonFilter. Have you made changes in this setting? If yes then copy the default values from the config of release zip.

**Comment by jjskuld** [comment]
https://github.com/Necrobot-Private/NecroBot/wiki/Why-Are-My-Pokemon-Not-Being-Caught
