### ISSUE TITLE
Best Config

### ISSUE THREAD

**Issue by kilado94** [Necrobot-Private/NecroBot#485]
Hi there
Dont knwo if alredy exist this topic but i whant to know if anyone have a nice config for me to catch them fast...thankz

**Comment by macinmn** [comment]
catch them fast so you're at higher risk of ban?  just zero out all timers and delays, 100% excellent curves.  done.

**Comment by samuraitruong** [comment]
basically, reduce delay, increase speed, set to hight population area , don't snipe too eager then it will good

make sure you are setting catch limit as well
