### ISSUE TITLE
Upgrade Electron GUI

### ISSUE THREAD

**Issue by hardknoxni69a** [Necrobot-Private/NecroBot#487]
Hello firstly Electron GUI is AMAZINGLY crisp. I do believe that we could make some improvements to make it the be all end all for GUIs. Here are the suggestions
- When we view pokemon and select its details it should show that pokemons level as well as how many candies it has and how many it takes to evolve( if you want to get really into it you can add there size and weight gender coming soon)
- when we are on the main pokemon screen the pokemon level and candies/evolve cost should now be visible along side the cp and iv
- when our mouse hovers over a pokemon a pop up menu should give us the transfer evolve upgrade buttons like when you are in the pokemon info screen
-optional but would be great check boxes on each pokemon to multiselect and perform mass transfer (once multiple are selected if you click on a pokemon you will get a pop up window with transfer button or cancel and if transfer additional popup confirm action or cancel)
-optional but might as well while working on electron we need a save button for when we are editing the config files through the app currently all you can do is view them but no changes you make can actually be saved after editing 

please contact through discord email or here if you need further explanation

**Comment by samuraitruong** [comment]
I am doing native GUI, Pokesase is nice GUI but user more interesting with BUILTIN gui. this can be close after native GUI release. It is required lots of time to build native guid. I have it working right now, but need time to fix all crab bug before release minimun version
