### ISSUE TITLE
Auto  Captcha

### ISSUE THREAD

**Issue by akashgupta0210** [Necrobot-Private/NecroBot#488]
How to setup auto captcha on bot.
Where should i get the "API key" & "API secret"?

**Comment by boscorelly** [comment]
https://www.captchasolutions.com/pricing/

**Comment by samuraitruong** [comment]
use 2captcha it is better then solutions captcha

2captcha.com

**Comment by articlefr** [comment]
https://www.captchasolutions.com/ is the best captcha solving service I've ever met.. The fastest and most accurate too...
