### ISSUE TITLE
Switching Bot was cancelled

### ISSUE THREAD

**Issue by baomx888** [Necrobot-Private/NecroBot#489]
### Expected Behavior:
Switch bot after certain time

### Actual Behavior:
[12:16:34] (ATTENTION) Switch bot account activated by : Runtime  - 55.5
[12:16:34] (ERROR) Current Operation was canceled.
Swtich bot was cancelled.

### Your config.json:
  "AllowMultipleBot": true,
  "Bots": [
    {
      "AuthType": "ptc",
      "GoogleUsername": null,
      "GooglePassword": null,
      "PtcUsername": "******",
      "PtcPassword": "*****"
    },
    {
      "AuthType": "ptc",
      "GoogleUsername": null,
      "GooglePassword": null,
      "PtcUsername": "******",
      "PtcPassword": "*****"
    }
  ]

```

### (OPTIONAL) Your Log:
```
replace this text with only the "relative" portion of your log. (Remove unnessary lines)

```
[12:16:34] (ATTENTION) Switch bot account activated by : Runtime  - 55.5
[12:16:34] (ERROR) Current Operation was canceled.

### Detailed Steps to Reproduce:


### Other Information
(Attach zip files if needed.)


Version:
Windows Version:
What is affected (catch, transfer, favorite, GPX, evolve, recycle, snipe, human walk snipe, pokestops, powerup/levelup, other):

**Comment by samuraitruong** [comment]
Thought the issue has been fix in 1.0.0.51, what is your version?

**Comment by baomx888** [comment]
upgrade on 1.0.5.1 this morning

**Comment by baomx888** [comment]
still not working after upgrade.

**Comment by hardknoxni69a** [comment]
fxed with latest updates
