### ISSUE TITLE
Bot only works with Google Api enabled.

### ISSUE THREAD

**Issue by mrsell545** [Necrobot-Private/NecroBot#49]
With Google Api disabled the bot will just freeze after start up. Enabling Google api fixes it however for someone like myself that may multibot as I use 10 bots at a time it is not efficient to have to get a new api key after 2500 request. Can we please be able to use necro route like the noxx dev version 9.7?

**Comment by petpetpetvm** [comment]
I dont think my config enabled api but it still working well

{
  "ConsoleConfig": {
    "TranslationLanguageCode": "en",
    "StartupWelcomeDelay": false,
    "AmountOfPokemonToDisplayOnStart": 10,
    "DetailedCountsBeforeRecycling": true
  },
  "UpdateConfig": {
    "CheckForUpdates": false,
    "AutoUpdate": false,
    "TransferConfigAndAuthOnUpdate": true
  },
  "WebsocketsConfig": {
    "UseWebsocket": false,
    "WebSocketPort": 14251
  },
  "LocationConfig": {
    "DisableHumanWalking": true,
    "StartFromLastPosition": false,
    "DefaultLatitude": 34.0092419,
    "DefaultLongitude": -118.49760370000001,
    "WalkingSpeedInKilometerPerHour": 98.92,
    "UseWalkingSpeedVariant": true,
    "WalkingSpeedVariant": 1.3,
    "ShowVariantWalking": false,
    "RandomlyPauseAtStops": true,
    "MaxSpawnLocationOffset": 10,
    "MaxTravelDistanceInMeters": 1370
  },
  "TelegramConfig": {
    "UseTelegramAPI": false,
    "TelegramAPIKey": null,
    "TelegramPassword": "12345"
  },
  "GPXConfig": {
    "UseGpxPathing": false,
    "GpxFile": "GPXPath.GPX"
  },
  "SnipeConfig": {
    "UseSnipeLocationServer": true,
    "SnipeLocationServer": "localhost",
    "SnipeLocationServerPort": 16969,
    "GetSniperInfoFromPokezz": true,
    "GetOnlyVerifiedSniperInfoFromPokezz": false,
    "GetSniperInfoFromPokeSnipers": true,
    "GetSniperInfoFromPokeWatchers": true,
    "GetSniperInfoFromSkiplagged": true,
    "MinPokeballsToSnipe": 0,
    "MinPokeballsWhileSnipe": 0,
    "MinDelayBetweenSnipes": 20000,
    "SnipingScanOffset": 0.013,
    "SnipeAtPokestops": false,
    "ActivateMSniper": true,
    "SnipeIgnoreUnknownIv": false,
    "UseTransferIvForSnipe": false,
    "SnipePokemonNotInPokedex": false,
    "UseSnipeLimit": true,
    "SnipeRestSeconds": 250,
    "SnipeCountLimit": 42
  },
  "HumanWalkSnipeConfig": {
    "Enable": false,
    "DisplayPokemonList": true,
    "MaxDistance": 1500.0,
    "MaxEstimateTime": 900.0,
    "CatchEmAllMinBalls": 50,
    "TryCatchEmAll": true,
    "CatchPokemonWhileWalking": true,
    "SpinWhileWalking": true,
    "AlwaysWalkback": false,
    "SnipingScanOffset": 0.025,
    "WalkbackDistanceLimit": 300.0,
    "IncludeDefaultLocation": true,
    "UsePokeRadar": true,
    "UseSkiplagged": true,
    "UseSnipePokemonList": true,
    "MaxSpeedUpSpeed": 60.0,
    "AllowSpeedUp": true,
    "DelayTimeAtDestination": 10000,
    "UseFastPokemap": true,
    "UsePogoLocationFeeder": false
  },
  "PokeStopConfig": {
    "UsePokeStopLimit": true,
    "PokeStopLimit": 1998,
    "PokeStopLimitMinutes": 1470
  },
  "PokemonConfig": {
    "CatchPokemon": true,
    "DelayBetweenPokemonCatch": 500,
    "UseCatchLimit": true,
    "CatchPokemonLimit": 998,
    "CatchPokemonLimitMinutes": 1470,
    "UseIncenseConstantly": true,
    "UseEggIncubators": true,
    "UseLimitedEggIncubators": true,
    "UseLuckyEggConstantly": true,
    "UseLuckyEggsMinPokemonAmount": 0,
    "UseLuckyEggsWhileEvolving": true,
    "UseBerriesMinCp": 100,
    "UseBerriesMinIv": 90.0,
    "UseBerriesBelowCatchProbability": 0.2,
    "UseBerriesOperator": "and",
    "MaxBerriesToUsePerPokemon": 3,
    "TransferWeakPokemon": true,
    "TransferDuplicatePokemon": true,
    "TransferDuplicatePokemonOnCapture": false,
    "RenamePokemon": false,
    "RenameOnlyAboveIv": false,
    "RenameTemplate": "{0}_{1}",
    "FavoriteMinIvPercentage": 99.0,
    "AutoFavoritePokemon": true,
    "MaxPokeballsPerPokemon": 6,
    "UseGreatBallAboveCp": 750,
    "UseUltraBallAboveCp": 2500,
    "UseMasterBallAboveCp": 1500,
    "UseGreatBallAboveIv": 85.0,
    "UseUltraBallAboveIv": 95.0,
    "UseGreatBallBelowCatchProbability": 0.0,
    "UseUltraBallBelowCatchProbability": 0.0,
    "UseMasterBallBelowCatchProbability": 0.0,
    "AutomaticallyLevelUpPokemon": false,
    "OnlyUpgradeFavorites": true,
    "UseLevelUpList": false,
    "AmountOfTimesToUpgradeLoop": 5,
    "GetMinStarDustForLevelUp": 5000,
    "LevelUpByCPorIv": "iv",
    "UpgradePokemonCpMinimum": 1000.0,
    "UpgradePokemonIvMinimum": 99.0,
    "UpgradePokemonMinimumStatsOperator": "and",
    "EvolveAboveIvValue": 1.0,
    "EvolveAllPokemonAboveIv": false,
    "EvolveAllPokemonWithEnoughCandy": false,
    "EvolveKeptPokemonsAtStorageUsagePercentage": 90.0,
    "KeepPokemonsThatCanEvolve": false,
    "KeepMinCp": 2000,
    "KeepMinIvPercentage": 90.0,
    "KeepMinLvl": 6,
    "KeepMinOperator": "or",
    "UseKeepMinLvl": false,
    "PrioritizeIvOverCp": true,
    "KeepMinDuplicatePokemon": 1,
    "UsePokemonToNotCatchFilter": true,
    "UsePokemonSniperFilterOnly": false,
    "DumpPokemonStats": true
  },
  "RecycleConfig": {
    "VerboseRecycling": true,
    "RecycleInventoryAtUsagePercentage": 90.0,
    "RandomizeRecycle": false,
    "RandomRecycleValue": 5,
    "TotalAmountOfPokeballsToKeep": 270,
    "TotalAmountOfPotionsToKeep": 0,
    "TotalAmountOfRevivesToKeep": 0,
    "TotalAmountOfBerriesToKeep": 50,
    "MaxPokeballsToKeep": 50
  },
  "CustomCatchConfig": {
    "EnableHumanizedThrows": true,
    "EnableMissedThrows": true,
    "ThrowMissPercentage": 14,
    "NiceThrowChance": 40,
    "GreatThrowChance": 30,
    "ExcellentThrowChance": 10,
    "CurveThrowChance": 90,
    "ForceGreatThrowOverIv": 90.0,
    "ForceExcellentThrowOverIv": 95.0,
    "ForceGreatThrowOverCp": 1000,
    "ForceExcellentThrowOverCp": 1500
  },
  "PlayerConfig": {
    "DelayBetweenPlayerActions": 1000,
    "EvolveActionDelay": 200,
    "TransferActionDelay": 100,
    "RecycleActionDelay": 100,
    "RenamePokemonActionDelay": 200,
    "UseNearActionRandom": true,
    "AutoCompleteTutorial": false,
    "DesiredNickname": "Nickname",
    "DesiredGender": "Male",
    "DesiredStarter": "Squirtle"
  },
  "SoftBanConfig": {
    "FastSoftBanBypass": false
  },
  "GoogleWalkConfig": {
    "UseGoogleWalk": false,
    "DefaultStepLength": 1.3,
    "GoogleHeuristic": "walking",
    "GoogleAPIKey": null,
    "Cache": true
  },
  "YoursWalkConfig": {
    "UseYoursWalk": false,
    "YoursWalkHeuristic": "bicycle"
  },

**Comment by mrsell545** [comment]
What version are you using?

**Comment by mrsell545** [comment]
Ok you are using the same version as me i think, here is my config, we have the same delays per actions cause i was testing that.
{
  "ConsoleConfig": {
    "TranslationLanguageCode": "en",
    "StartupWelcomeDelay": false,
    "AmountOfPokemonToDisplayOnStart": 10,
    "DetailedCountsBeforeRecycling": true
  },
  "UpdateConfig": {
    "CheckForUpdates": true,
    "AutoUpdate": true,
    "TransferConfigAndAuthOnUpdate": true
  },
  "WebsocketsConfig": {
    "UseWebsocket": false,
    "WebSocketPort": 14251
  },
  "LocationConfig": {
    "DisableHumanWalking": false,
    "StartFromLastPosition": true,
    "DefaultLatitude": 40.785092,
    "DefaultLongitude": -73.974187,
    "WalkingSpeedInKilometerPerHour": 17.15,
    "UseWalkingSpeedVariant": true,
    "WalkingSpeedVariant": 1.2,
    "ShowVariantWalking": true,
    "RandomlyPauseAtStops": false,
    "MaxSpawnLocationOffset": 10,
    "MaxTravelDistanceInMeters": 1750
  },
  "TelegramConfig": {
    "UseTelegramAPI": false,
    "TelegramAPIKey": null,
    "TelegramPassword": null
  },
  "GPXConfig": {
    "UseGpxPathing": false,
    "GpxFile": "GPXPath.GPX"
  },
  "SnipeConfig": {
    "UseSnipeLocationServer": true,
    "SnipeLocationServer": "localhost",
    "SnipeLocationServerPort": 16969,
    "GetSniperInfoFromPokezz": false,
    "GetOnlyVerifiedSniperInfoFromPokezz": false,
    "GetSniperInfoFromPokeSnipers": false,
    "GetSniperInfoFromPokeWatchers": false,
    "GetSniperInfoFromSkiplagged": false,
    "MinPokeballsToSnipe": 20,
    "MinPokeballsWhileSnipe": 0,
    "MinDelayBetweenSnipes": 30000,
    "SnipingScanOffset": 0.013,
    "SnipeAtPokestops": true,
    "ActivateMSniper": false,
    "SnipeIgnoreUnknownIv": false,
    "UseTransferIvForSnipe": false,
    "SnipePokemonNotInPokedex": false,
    "UseSnipeLimit": true,
    "SnipeRestSeconds": 60,
    "SnipeCountLimit": 3
  },
  "HumanWalkSnipeConfig": {
    "Enable": false,
    "DisplayPokemonList": true,
    "MaxDistance": 1500.0,
    "MaxEstimateTime": 900.0,
    "CatchEmAllMinBalls": 50,
    "TryCatchEmAll": true,
    "CatchPokemonWhileWalking": true,
    "SpinWhileWalking": true,
    "AlwaysWalkback": false,
    "SnipingScanOffset": 0.025,
    "WalkbackDistanceLimit": 300.0,
    "IncludeDefaultLocation": true,
    "UsePokeRadar": true,
    "UseSkiplagged": true,
    "UseSnipePokemonList": true,
    "MaxSpeedUpSpeed": 60.0,
    "AllowSpeedUp": true,
    "DelayTimeAtDestination": 10000,
    "UseFastPokemap": true,
    "UsePogoLocationFeeder": false
  },
  "PokeStopConfig": {
    "UsePokeStopLimit": true,
    "PokeStopLimit": 900,
    "PokeStopLimitMinutes": 720
  },
  "PokemonConfig": {
    "CatchPokemon": true,
    "DelayBetweenPokemonCatch": 2000,
    "UseCatchLimit": true,
    "CatchPokemonLimit": 390,
    "CatchPokemonLimitMinutes": 720,
    "UseIncenseConstantly": false,
    "UseEggIncubators": true,
    "UseLimitedEggIncubators": true,
    "UseLuckyEggConstantly": false,
    "UseLuckyEggsMinPokemonAmount": 0,
    "UseLuckyEggsWhileEvolving": true,
    "UseBerriesMinCp": 1000,
    "UseBerriesMinIv": 90.0,
    "UseBerriesBelowCatchProbability": 0.2,
    "UseBerriesOperator": "or",
    "MaxBerriesToUsePerPokemon": 4,
    "TransferWeakPokemon": false,
    "TransferDuplicatePokemon": true,
    "TransferDuplicatePokemonOnCapture": true,
    "RenamePokemon": true,
    "RenameOnlyAboveIv": true,
    "RenameTemplate": "{1}_{0}",
    "FavoriteMinIvPercentage": 95.0,
    "AutoFavoritePokemon": false,
    "MaxPokeballsPerPokemon": 15,
    "UseGreatBallAboveCp": 1000,
    "UseUltraBallAboveCp": 1250,
    "UseMasterBallAboveCp": 1500,
    "UseGreatBallAboveIv": 90.0,
    "UseUltraBallAboveIv": 95.0,
    "UseGreatBallBelowCatchProbability": 0.2,
    "UseUltraBallBelowCatchProbability": 0.1,
    "UseMasterBallBelowCatchProbability": 0.05,
    "AutomaticallyLevelUpPokemon": false,
    "OnlyUpgradeFavorites": true,
    "UseLevelUpList": true,
    "AmountOfTimesToUpgradeLoop": 5,
    "GetMinStarDustForLevelUp": 5000,
    "LevelUpByCPorIv": "iv",
    "UpgradePokemonCpMinimum": 1000.0,
    "UpgradePokemonIvMinimum": 95.0,
    "UpgradePokemonMinimumStatsOperator": "and",
    "EvolveAboveIvValue": 95.0,
    "EvolveAllPokemonAboveIv": false,
    "EvolveAllPokemonWithEnoughCandy": true,
    "EvolveKeptPokemonsAtStorageUsagePercentage": 95.0,
    "KeepPokemonsThatCanEvolve": true,
    "KeepMinCp": 2000,
    "KeepMinIvPercentage": 95.0,
    "KeepMinLvl": 6,
    "KeepMinOperator": "or",
    "UseKeepMinLvl": false,
    "PrioritizeIvOverCp": true,
    "KeepMinDuplicatePokemon": 1,
    "UsePokemonToNotCatchFilter": false,
    "UsePokemonSniperFilterOnly": false,
    "DumpPokemonStats": false
  },
  "RecycleConfig": {
    "VerboseRecycling": true,
    "RecycleInventoryAtUsagePercentage": 90.0,
    "RandomizeRecycle": false,
    "RandomRecycleValue": 5,
    "TotalAmountOfPokeballsToKeep": 260,
    "TotalAmountOfPotionsToKeep": 10,
    "TotalAmountOfRevivesToKeep": 10,
    "TotalAmountOfBerriesToKeep": 50,
    "MaxPokeballsToKeep": 260
  },
  "CustomCatchConfig": {
    "EnableHumanizedThrows": true,
    "EnableMissedThrows": false,
    "ThrowMissPercentage": 25,
    "NiceThrowChance": 10,
    "GreatThrowChance": 50,
    "ExcellentThrowChance": 60,
    "CurveThrowChance": 90,
    "ForceGreatThrowOverIv": 90.0,
    "ForceExcellentThrowOverIv": 95.0,
    "ForceGreatThrowOverCp": 1000,
    "ForceExcellentThrowOverCp": 1500
  },
  "PlayerConfig": {
    "DelayBetweenPlayerActions": 1000,
    "EvolveActionDelay": 200,
    "TransferActionDelay": 100,
    "RecycleActionDelay": 100,
    "RenamePokemonActionDelay": 200,
    "UseNearActionRandom": true,
    "AutoCompleteTutorial": false,
    "DesiredNickname": "Nickname",
    "DesiredGender": "Male",
    "DesiredStarter": "Squirtle"
  },
  "SoftBanConfig": {
    "FastSoftBanBypass": false
  },
  "GoogleWalkConfig": {
    "UseGoogleWalk": false,
    "DefaultStepLength": 1.3,
    "GoogleHeuristic": "walking",
    "GoogleAPIKey": null,
    "Cache": true
  },
  "YoursWalkConfig": {
    "UseYoursWalk": false,
    "YoursWalkHeuristic": "bicycle"
  },

**Comment by mrsell545** [comment]
Ok very strange I tried your config and I still froze so I apologize its not the google api cause it either freezes right at the start or catches 1-5 pokes and then locks up regardless of the config.

**Comment by petpetpetvm** [comment]
Maybe you can try re-download a brand new one and try with my config, because it's working fine with me

**Comment by niciolaux** [comment]
same problem here, version 0.9.8.6 sometimes the bot freezes after showing the pokemon list, I tried with API key and changing delays but I don't understand where is the problem... maybe the IP?

**Comment by hardknoxni69a** [comment]
i use 9.8.6 and have no issues at all and i do not use a special key so i doubt google api is the issue i would suggest fresh install and update config line by line to not copy over any issues

**Comment by mrsell545** [comment]
I did a fresh install and used his config and still freeze up, the thing is, I can use noxx dev necro 9.7 fine running 10+ accounts and that still even works right now but some reason this version i keep freezing.

**Comment by zc3721** [comment]
same problem with u

niciolaux <notifications@github.com>于2016年9月10日周六 03:07写道：

**Comment by zc3721** [comment]
totally same with u，9.7now

mrsell545 <notifications@github.com>于2016年9月10日周六 11:59写道：

**Comment by mrsell545** [comment]
I'm sorry to see that but at least I'm not alone, I might have to switch to another bot as this is unusable to me and yourself and I can't figure out the solution. Especially since noxx dev 9.7 works fine.

**Comment by petpetpetvm** [comment]
I think we are gonna have to stop botting for few days tooo, cuz there is an update on the offical app coming

**Comment by mrsell545** [comment]
That's true as well! I guess I go back to noxx dev 9.7 until whatever is causing my and the other guys issue is sorted. At least u till update for official app released.

**Comment by mrsell545** [comment]
I've tried changing the config, making a new poke account, using my real ip, using a fresh install with new account, always still locks up. Running 9.7 noxx dev now and that is running fine.

**Comment by hardknoxni69a** [comment]
Have u started a fresh install and not changed any configs just type in some bogus login info and see if it loads theres a good chance something your importing into config is giving you the problem i have been running this version for about 48 hours without a single hiccup

**Comment by hardknoxni69a** [comment]
Send a picture of the error on the console so we can try and see what the console is actually registering

**Comment by mrsell545** [comment]
Ok will do in a bit, thank you.

**Comment by mrsell545** [comment]
latest version now working for me! Awesome! I wonder what the problem was???

**Comment by petpetpetvm** [comment]
great to heard that ;)

**Comment by zc3721** [comment]
I'm going to try when I get home

petpetpetvm <notifications@github.com>于2016年9月11日周日 16:45写道：
