### ISSUE TITLE
Feature Request : Audible Ping on Token Expiry

### ISSUE THREAD

**Issue by aaruni96** [Necrobot-Private/NecroBot#494]
Feature request for the console to sound an audible ping whenever the access token expires and the bot restarts.

**Comment by jjskuld** [comment]
BTW, the access token expiration should be handled transparently.  The bot should not be restarting, so if this is happening it needs to be looked at.

**Comment by aaruni96** [comment]
I'm in my linux box now, but I'll post a screenshot the next time I'm using the bot and this happens.

**Comment by aaruni96** [comment]
![image](https://cloud.githubusercontent.com/assets/7453256/22404421/b4df3fb6-e656-11e6-9059-cf9fcfa27d76.png)

**Comment by hardknoxni69a** [comment]
niantic rthis now after 30 minutes doesnt effect anything
