### ISSUE TITLE
Google Walk Issue

### ISSUE THREAD

**Issue by DepecheMode2017** [Necrobot-Private/NecroBot#496]
Using the latest version with # keys. 

1. Program is happy to walk within a small section to farm .. always back and fro along the same route. It doesn't wanna explore other areas. Have set the distance to different value e.g. 3000, 2000, 1500 .. and it's the same. The route are connected by the way and it will walk to the other end when there is something to snipe. Any help here?

![image 2](https://cloud.githubusercontent.com/assets/25029966/21803812/ca6ed926-d766-11e6-8832-14d45f023969.jpg)

2. What is difference between totalamountofpokeballstokeep and maxpokeballstokeep? Currently I set both to 220 as I am trying to maximize the numbers but it just recycled 80 pokeballs leaving 20 Pokes, 30 Greats and 20 Ultras. Huh? There goes an hour and half of not catching anything ...

**Comment by samuraitruong** [comment]
total amount = all ball, maxpokemon was wrong implement and don't need, but basically that is number of pokeball , that can be setup in recycleitem filter

**Comment by jjskuld** [comment]
This is related to #643.
