### ISSUE TITLE
Error messages

### ISSUE THREAD

**Issue by stikio** [Necrobot-Private/NecroBot#498]
Error loading data from Pokecrew
Error loading data from pokesnipers
Error loading data from PokeWatcher
Error loading data from pokeradar

Bot is still running after these messages pop up, but is there anything to fix this, or can it be ignored?

**Comment by Schweng** [comment]
Edit your config.json to 

    "UsePokeRadar": false,
    "UseSkiplagged": false,
    "UsePokecrew": false,
    "UsePokesnipers": false,
    "UsePokeZZ": false,
    "UsePokeWatcher": false,
    "UseFastPokemap": false,

and the messages will disappear.
