### ISSUE TITLE
Add New Auto Captcha Service

### ISSUE THREAD

**Issue by articlefr** [Necrobot-Private/NecroBot#500]
Is it possible to add this new auto captcha service http://www.solvecaptchas.com/

**Comment by samuraitruong** [comment]
I can add new captcha, however, we need test token, It you can PM me the token to test I can integrated new captcha easy.

**Comment by samuraitruong** [comment]
Just read, it has 1 days free, I will include in future release

**Comment by articlefr** [comment]
Just create an account and send the registered email to me so I can add the
subscription plan.

**Comment by samuraitruong** [comment]
@articlefr  : just created an free account, samuraitruong@hotmail.com, if possible please  add my email to subscription pan then i can start code it. thanks

**Comment by samuraitruong** [comment]
@articlefr supprised me, your are CEO of captchasolutions :+1:

**Comment by articlefr** [comment]
I've just subscribed you as Basic plan member. You may now use the account
to integrate our service. Please see API document at
http://www.solvecaptchas.com/api_document.php

**Comment by articlefr** [comment]
Yes, I am the founder and CEO of CaptchaSolutions.com. Thanks!

**Comment by samuraitruong** [comment]
Sorry @articlefr ,

```noCaptcha Results

noCaptcha results are return as at least two numbers (1 - 9) corresponding to the image you should select. The numbers go from left to right top to bottom. So the top left picture is 1, the top right picture is 3, the bottom left picture is 7 and the bottom right picture is 9.```

It seem only return the square to click, we not going to go that far to implement browser simulation since it take too much efforts. is there anyway the api return the CaptchaResponseCode?

**Comment by articlefr** [comment]
Sorry the noCaptcha API method is not available as of this time.
