### ISSUE TITLE
.53 Transfer Issues

### ISSUE THREAD

**Issue by Kaiswil2** [Necrobot-Private/NecroBot#502]
Version: v1.0.0.53
Windows Version: Win 10
Is it me or has transfer within GUI been disabled? I have tried PokeEase, PokeEaseFork and Electron versions of GUI and no transfers are taking place. I pulled the latest update this morning.

**Comment by Kaiswil2** [comment]
Confirmed, I rolled back to .52 and transfer worked.

**Comment by samuraitruong** [comment]
fixed #507
