### ISSUE TITLE
Error since update 1.0.0.54

### ISSUE THREAD

**Issue by jokki89** [Necrobot-Private/NecroBot#504]
I've get every time an error message since today since i did the update to 1.0.0.54 when i start necrobot. and after that it crashes down.

whats could be the problem, it worked until yesterday perfectly...

![error](https://cloud.githubusercontent.com/assets/24991970/21865785/d53f3814-d847-11e6-84dd-c6bdcd75452a.PNG)

**Comment by samuraitruong** [comment]
that issue usually happen when you have very slow network or bad proxy, try to use better proxy if you are on proxy. restart your ADSL moderm could help

**Comment by jokki89** [comment]
@samuraitruong ok thank you I would try this in the evening when I'm back from work. 
But strange is that it works perfectly 5 days at a strech and now not :/ but ok I hope it will work again after restart my modem.

**Comment by samuraitruong** [comment]
ping me if it still not work.

**Comment by mboeder** [comment]
same problem to me

**Comment by jokki89** [comment]
@samuraitruong @mboeder 
didn't change anything , also work now after update 0.55  ..for now at least ^^

**Comment by mboeder** [comment]
New problems after 0.56 update. Bot is running and login works, but no pokestops or catching pokemon :-(
