### ISSUE TITLE
System.Security.Cryptography.X509Certificates

### ISSUE THREAD

**Issue by pamoy** [Necrobot-Private/NecroBot#506]
No se puede cargar el archivo o ensamblado 'System.Security.Cryptography.X509Certificates, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' ni una de sus dependencias. El sistema no puede encontrar el archivo especificado.

Necro2Win.

Any help..

**Comment by samuraitruong** [comment]
Please delete Necrobot2.win.exe.config in folder
