### ISSUE TITLE
[Feature Request] Sniper info from https://pokedexs.com/

### ISSUE THREAD

**Issue by CreativiTimothy** [Necrobot-Private/NecroBot#51]
Seems like pokezz.com came out with a new snipe website list called https://pokedexs.com/

It would be nice to add in! However, personally, I would put aside all feature requests until we have a more stable and updated API unless it takes very little time to implement.

To clairfy, Pokezz.com still works -- pokedexs.com is their second website

**Comment by petpetpetvm** [comment]
Look like pokewatchers still not working too

**Comment by samuraitruong** [comment]
think we should remove this, if we need support, msniper  & mypogosnipers.com now provide so much quality feed to us already.

**Comment by iwean** [comment]
That's what I mean before! :smile:

**Comment by CreativiTimothy** [comment]
I think we could just leave it here until all other bug fixes, feature requests, and api stuff are fixed/added in/updated

**Comment by petpetpetvm** [comment]
Pokedexs are really good on farming candies, maybe
"Pokedexstosnip":
     Abra
     Dratini
     Eevee

**Comment by Silph-Road** [comment]
TBD
