### ISSUE TITLE
about limits in the bot

### ISSUE THREAD

**Issue by atheist05** [Necrobot-Private/NecroBot#510]
why there are limits to catching ,sniping pokemons and also to pokestops?
catching has a limit of 998 , sniping of 39 .And pokestops has a limit of 1998.

**Comment by Albertus30** [comment]
in order to increase the chance not to get banned

**Comment by stikio** [comment]
What does the reset cycle look like? when will the limits be reseted?

**Comment by samuraitruong** [comment]
Cycel is every time you catch pokemon the rules is 998 in past 24 hours, it mean pro-rata recycle 

For example you start bot and in first 1 hours you catch 200 pkm, then you stop bot for 2 hours.

you reopen bot, then at this time, your limit will be reset to 0.

but if you just stop for 30 min, reopen bot maybe limit will be 100/998 depend on how many pkm you caught in that first 30 min
