### ISSUE TITLE
gym battle error

### ISSUE THREAD

**Issue by odhinne** [Necrobot-Private/NecroBot#511]
first of all, thanks for the update for gym battles, even if I'm having an issue with it, I'm glad it was/is being added! 

I've only used the bot for a few battles so far, mainly because when I get the same error 4 or 5 times in a row, I stop doing it. In each battle, once I get past the first gym pokemon, I get an error message (SHIT) and btw, that's funny as hell the first time I saw it, having the program cuss when it breaks is awesome, and then it gives a message that its skipping the gym and the program keeps running. Is this a settings issue that I need to address or is there a problem with the bot? unfortunately, I had to wait to send this after I got to work, so I don't have my config file with me, although I know most of the settings in the gym portion.

**Comment by samuraitruong** [comment]
sorry Mate, I haven't fully test it then some bad work in code :dagger: 
diable GYM in next release until i fully test it. workload #507 disable gym function
