### ISSUE TITLE
[Optimization] Skip walking to gyms that are full and/or owned by another team

### ISSUE THREAD

**Issue by Axeia** [Necrobot-Private/NecroBot#512]
### Expected Behavior:
When a gym is obviously at its limit say 52k prestige - don't even bother walking to it. Humans wouldn't, why would the bot?

I can think of 3 situations where it shouldn't even bother.

- Gyms of another team - if you're on say Valor and the gym is Mystic. Just don't visit it at all.
- Gyms that capped, if a gym is at 50k or more prestige it's definitely full. 
- Gyms that exceed the level in the config file. You know the gym level ahead of time since it's displayed in the GUI, the level cap in the gym is also known. 

Ideally you of course would just check if it's the right team and has a free slot ahead of time which should be possible to calculate based on the prestige level/how many pokémon are in it? 

### Actual Behavior:
```
[12:52:24] (GYM) Visited  Gym : Valerius | Team Red  | Gym points 52000
[12:52:24] (GYM) No action. No FREE slots in GYM 10/10
```

Version: 1.0.0.54
Windows Version: 10x64

**Comment by hardknoxni69a** [comment]
similiar option shave been implemented
