### ISSUE TITLE
Buggy Pokemon Recycling Due Improper Rounding

### ISSUE THREAD

**Issue by Andi-fr** [Necrobot-Private/NecroBot#515]
**In config.json:**
[...]
"PrioritizeIvOverCp": true
[...]

**Expected Behavior:**
If two Pokemon are shown as IV 100 I expect the Pokemon with lower CP to be transferred. 

**Actual Behavior:**
![grafik](https://cloud.githubusercontent.com/assets/1909724/21910141/16b3f216-d91b-11e6-9545-2be665357c82.png)
The Pokemon with the higher CP was transferred.

**Detailed Steps to Reproduce:**
1) Pokemon to transfer are processed here:
https://github.com/Necrobot-Private/NecroBot/blob/d798bde1d3f2af7ad0c4e3344f6abc5a64329b05/PoGo.NecroBot.Logic/Inventory.cs#L250

2) The piece of code sorts by the perfection of the Pokemon (and then by its CP), which is calculated here (as Double value):
https://github.com/Necrobot-Private/NecroBot/blob/af4b9e99beac12f15acdf18517c9f745a3282b0e/PoGo.NecroBot.Logic/PoGoUtils/PokemonInfo.cs#L82

3) The console messages are formatted here:
https://github.com/Necrobot-Private/NecroBot/blob/e2ea0fb2a06fea54e0b5af5e100b3612505a720b/PoGo.NecroBot.Logic/Service/TelegramCommand/TopCommand.cs#L69

Because of inaccuracies when calculating with Doubles in 2) and the huge amount of digits after the floating point you will never get exactly 100.00%

**Solution:**
Round properly in 2)
-- return (curCp - minCp)/(maxCp - minCp)*100.0;
++ return Math.round((curCp - minCp)/(maxCp - minCp)*100.0,2);

**Further Information:**
You already round the result of 2) **sometimes** - review the usages of 'CalculatePokemonPerfection(...)' maybe you can avoid rounding twice

https://github.com/Necrobot-Private/NecroBot/search?utf8=%E2%9C%93&q=CalculatePokemonPerfection

 **Example:**

> below will yield false:
> ```
> double d1 = 1.000001; double d2 =0.000001;
> Console.WriteLine((d1-d2)==1.0);
> ```
> 
Source: http://stackoverflow.com/questions/5658799/is-it-wrong-to-compare-a-double-to-0-like-this-doublevariable-0

**Comment by jjskuld** [comment]
It's fixed already in latest code.
