### ISSUE TITLE
Inconsistent GUI Messages (Three Issues - @Samuraitruong [DISCORD])

### ISSUE THREAD

**Issue by Andi-fr** [Necrobot-Private/NecroBot#516]
As talked about in Discord with @Samuraitruong here a short reminder:

My STD.OUT (6 Lines):
1) [00:35:30] (PKMN) (Gefangen Versuch #5) | (Wildes) Rattikarl Lvl: 16 CP: (646/660) IV: 53.00% | Chance: 14.97% | 69.49m entfernt | mit Pokeball (2 verbleibend). | 220 EP erhalten | Bonbons: 66 | B: 49.019186 L: 12.082684 | Move1: BiteFast Move2: HyperBeam
2) [00:35:35] (ENTWICKELT) [Entwicklung] Moegliche Entwicklungen: 6
3) [00:35:35] (UPDATE) Warte mit Entwicklungen von 6 Pokemon bis 148 weitere gefangen wurden! (93/241 bis 100% Inventar Auslastung)
4) [00:35:36] (VERSCHICKT) Muschas - WP: 500  IV: 65.62%   [Beste WP: 360  IV: 75.33%] (Bonbons: 114)
5) [12:35:42] (HASH SERVER)  in last 1 minute  16 request/min , AVG: 350.00 ms/request , Fastest : 248, Slowest: 1091
6) [00:35:43] (VERSCHICKT) Rattikarl       - WP: 646  IV: 52.72%   [Beste WP: 612  IV: 93.54%] (Bonbons: 67)

First Issue: look at the timestamp it's 12:35AM for the HASH SERVER Messages and 00:35AM for the other ones

Second Issue: look at lines 1 and 6 CP (= engl. Competition Points) is the same as WP (= german Wettkampf Punkte) <= It's an missing I18N (Internationalization)

Third Issue: look at lines 1 and 6 - the Pokemon that was caught in line 1 (raticate) was transfered in line 6 but the calculated IV values differ

**Comment by Andi-fr** [comment]
FYI - a short summary of the STD.OUT lines above:
1) Catch raticate on fifth attempt
2) Evolve - possible evolution count is 6
3) Update - wait evolving pokemon (catch some more before evolving)
4) transfer shellder
5) Hash Server
6) Transfer the raticate caught in line 1

**Comment by boscorelly** [comment]
for iv, it is rounded when catched. it will always be xx.00%. so it's normal  

open an issue per problem

**Comment by hardknoxni69a** [comment]
newest version dont have these issues
