### ISSUE TITLE
questions about gui

### ISSUE THREAD

**Issue by petpetpetvm** [Necrobot-Private/NecroBot#52]
i'm sorry, it's not a issues, i just want to ask if there is any gui (like pokeEase/necrobotvisualizer) that work on mutiple bots (mutiple tabs....)
which auto turn tabs of when the bot close, and open new tabs when new bots start.

thanks

**Comment by hardknoxni69a** [comment]
Just set different ports for each bot and u could script the link for each different port when different bot loads i suppose
