### ISSUE TITLE
bug with walking time per 24 hours

### ISSUE THREAD

**Issue by boscorelly** [Necrobot-Private/NecroBot#538]
Hi,

yesterday i reached my maximum time to calk per 24 hours. The bot was trying to restart but always the same message.

Quiting and relaunching the bot (to get update) make the bot working again.

**Comment by hardknoxni69a** [comment]
this is not a bug the time limits specifies how long your bot will perform the actions during one period once you restart the time is auto restarted i will update config to better reflect

**Comment by boscorelly** [comment]
thanks !
