### ISSUE TITLE
v62 : no pokedex ?

### ISSUE THREAD

**Issue by boscorelly** [Necrobot-Private/NecroBot#539]
can't find the pokedex in Electron GUI

**Comment by samuraitruong** [comment]
it is in native GUI not in web base GUI or electron GUI

**Comment by boscorelly** [comment]
If the gui has been optimized it will be good. I was unable to use it on my surface 3 (not pro).

**Comment by boscorelly** [comment]
i downloaded the gui zip and tried  there is no pokedex in both ui (poke ease and necro fork)
