### ISSUE TITLE
Candy issue native GUI

### ISSUE THREAD

**Issue by portabili** [Necrobot-Private/NecroBot#540]
### Expected Behavior:
In native GUI, number of candy is updated after each evolvement, so that the evolved pokemon can be evolved.

### Actual Behavior:
Number of candy is not updated in native GUI.
For example, Abra is evolved to Kadabra, number of candy of Kadabra is 0 that it cannot be evolved to Alakazam.
Before Abra 200 candies.
After Abra 200 candies, Kadabra 0 candies and the Evolve button is faded.
The issue is producible easily with every config.json.

### Your config.json:
```

```

### (OPTIONAL) Your Log:
```

```

### Other Information
(Attach zip files if needed.)

Version: 1.0.0.62
Windows Version: 10
What is affected (catch, transfer, favorite, GPX, evolve, recycle, snipe, human walk snipe, pokestops, powerup/levelup, other): evolve, upgrade.

**Comment by samuraitruong** [comment]
noted , will fix soon

**Comment by samuraitruong** [comment]
fixed
