### ISSUE TITLE
Gym

### ISSUE THREAD

**Issue by sammy150681** [Necrobot-Private/NecroBot#541]
My stamdard configuration not fitght against gym..

**Comment by sammy150681** [comment]
"GymConfig": {
"Enable": true,
"PrioritizeGymOverPokestop": false,
"MaxDistance": 500.0,
"DefaultTeam": "yellow",
"MaxCPToDeploy": 2000,
"MaxLevelToDeploy": 28,
"VisitTimeout": 60,
"UseRandomPokemon": true,
"NumberOfTopPokemonToBeExcluded": 10,
"CollectCoinAfterDeployed": 1,
"MaxGymLevelToAttack": 10,
"MaxDefendersToAttack": 10

**Comment by samuraitruong** [comment]
gym is disable for testing, it will re-activate soon
keep update from announcement of release page

**Comment by samuraitruong** [comment]
Fixed
