### ISSUE TITLE
Gui

### ISSUE THREAD

**Issue by sammy150681** [Necrobot-Private/NecroBot#542]
In my gui load nothing,  is empty

**Comment by atheist05** [comment]
same here bro .. :(

**Comment by GlennVandendijk** [comment]
Unfortunately the GUI or the GUI.Electron are both not working for me. 
It does open but it doesn't show any map details and no stats are being loaded as can be seen here:
[https://gyazo.com/2f3c900d18a31b19f702e357892b25ed](url)

**Comment by samuraitruong** [comment]
some change recently break it. I will work on it as priority ,

**Comment by hardknoxni69a** [comment]
#487 could be done at same time please :) 🥇

**Comment by samuraitruong** [comment]
nop, I just check my map, still work fine with web map.

**Comment by mboeder** [comment]
same problem to me

**Comment by sammy150681** [comment]
Webmap?

**Comment by mboeder** [comment]
What do you mean with web map? Neither Gui Electron or GUI Version does work for me. Seems to me, that there is no established account connection.No map details or stats shown.

**Comment by opera200** [comment]
i have this problem too :/

**Comment by samuraitruong** [comment]
ELectron  + GUI is web map version :) ok since it no longer issue, I close this
