### ISSUE TITLE
new feature request to save Berries and UltraBalls

### ISSUE THREAD

**Issue by KakacyOne** [Necrobot-Private/NecroBot#544]
Hi,

in "PokemonConfig": {} we can set such as follows to save berries for Pokemons with high CP and IV in the same time:
    "UseBerriesMinCp": 670,
    "UseBerriesMinIv": 100.0,
    "UseBerriesOperator": "and",
but we cant save Ultraball because of only "UseUltraBallAboveCp" and  "UseUltraBallAboveIv" in the config, pls also add a logic as "UseBerriesOperator" for saving Ultraballs for stronger Pokemons, thx.

If possible, It is better to add new functions "UseBerriesFilter"{} and "UseUltraBallFilter"{} for any pokemon such as Dragonite, Lapras with MinCP, MinIv and MinBerries or MinBalls to use.

**Comment by sackthesack** [comment]
That would be nice! Don't want to lose Ultraballs because of a stupid pidgey with 95 IV :D

**Comment by samuraitruong** [comment]
fixed, 

Introduce "UseballOperator" which is and or "or"

that is logic check for 3 combination , IV, CP, and catchchance. this apply for all kind ofball

expected version : 1.0.0.70
