### ISSUE TITLE
not Transfer: by NB2.WIN v1.0.0.62 "PokemonsTransferFilter": {} doesnt work?

### ISSUE THREAD

**Issue by KakacyOne** [Necrobot-Private/NecroBot#545]
in the "PokemonConfig": {} I set it as follows:
    **"KeepMinCp": 2000,
    "KeepMinIvPercentage": 101, (or 100, or 97)
    "KeepMinLvl": 29,
    "KeepMinOperator": "or",**
and in the  "PokemonsTransferFilter": {} I set it such as follows:
**"Raticate": {
      "KeepMinCp": 1250,
      "KeepMinIvPercentage": 100.0,
      "KeepMinLvl": 29,
      "UseKeepMinLvl": false,
      "KeepMinOperator": "and",
      "KeepMinDuplicatePokemon": 0,
      "Moves": [],
      "DeprecatedMoves": null,
      "MovesOperator": "or",
      "CatchOnlyPokemonMeetTransferCriteria": false
    },**
then after autosniping many Raticates with 100iv but low CP (<1250) are not transfered, for other pokemons with 100iv and low cp against the setting as Raticate in "PokemonsTransferFilter" are also not transfered, so the bag is full of not needed pokemons with 100iv but low cp. 

**!!!!  This config.json (with all same setting) in NB2 V1.0.0.52 works pretty fine, almost of the Pokemons with 100iv but low CP against the setting in the "PokemonsTransferFilter" are transfered after botting !!!!**

Does anyone also have this problem? if yes, pls fix it,  if no, how can I set in the config? thx

**Comment by samuraitruong** [comment]
II don't think it a bug, how many item in your bag and do you have bulk transfer turn on?

**Comment by KakacyOne** [comment]
"PokemonConfig": {
    "CatchPokemon": true,
    "DelayBetweenPokemonCatch": 500,
    "UseCatchLimit": true,
    "CatchPokemonLimit": 985,
    "CatchPokemonLimitMinutes": 1470,
    "UseIncenseConstantly": false,
    "UseEggIncubators": true,
    "UseLimitedEggIncubators": false,
    "UseLuckyEggConstantly": false,
    "UseLuckyEggsMinPokemonAmount": 30,
    "UseLuckyEggsWhileEvolving": false,
    "UseBerriesMinCp": 2500,
    "UseBerriesMinIv": 100.0,
    "UseBerriesBelowCatchProbability": 0.2,
    "UseBerriesOperator": "or",
    "MaxBerriesToUsePerPokemon": 1,
    "TransferWeakPokemon": false,
    "TransferDuplicatePokemon": true,
    "TransferDuplicatePokemonOnCapture": true,
    "RenamePokemon": false,
    "RenameOnlyAboveIv": false,
    "RenameTemplate": "{1}_{0}",
    "FavoriteMinIvPercentage": 97.0,
    "AutoFavoritePokemon": true,
    "MaxPokeballsPerPokemon": 20,
    "UseGreatBallAboveCp": 650,
    "UseUltraBallAboveCp": 1800,
    "UseMasterBallAboveCp": 2500,
    "UseGreatBallAboveIv": 90.0,
    "UseUltraBallAboveIv": 101.0,
    "UseGreatBallBelowCatchProbability": 0.2,
    "UseUltraBallBelowCatchProbability": 0.1,
    "UseMasterBallBelowCatchProbability": 0.05,
    "AutomaticallyLevelUpPokemon": false,
    "OnlyUpgradeFavorites": false,
    "UseLevelUpList": false,
    "AmountOfTimesToUpgradeLoop": 5,
    "GetMinStarDustForLevelUp": 5000,
    "LevelUpByCPorIv": "iv",
    "UpgradePokemonCpMinimum": 1000.0,
    "UpgradePokemonIvMinimum": 95.0,
    "UpgradePokemonMinimumStatsOperator": "and",
    "EvolveAboveIvValue": 95.0,
    "EvolveAllPokemonAboveIv": false,
    "EvolveAllPokemonWithEnoughCandy": true,
    "EvolveKeptPokemonsAtStorageUsagePercentage": 90.0,
    "EvolveKeptPokemonIfBagHasOverThisManyPokemon": 120,
    "KeepPokemonsThatCanEvolve": false,
    **"KeepMinCp": 2000,
    "KeepMinIvPercentage": 97.0,
    "KeepMinLvl": 29,
    "KeepMinOperator": "or",
    "UseKeepMinLvl": false,**
    "PrioritizeIvOverCp": true,
    "KeepMinDuplicatePokemon": 1,
    "UsePokemonToNotCatchFilter": false,
    "UsePokemonSniperFilterOnly": false,
    "DumpPokemonStats": false,
    "DelayBetweenPokemonUpgrade": 500,
    "OutOfBallCatchBlockTime": 7,
    "PokeballToKeepForSnipe": 100,
    **"UseBulkTransferPokemon": false,
    "BulkTransferStogareBuffer": 5,
    "BulkTransferSize": 5**
  },
i set always "UseBulkTransferPokemon": false, because it is very strange no matter how many i set for  "BulkTransferStogareBuffer" and "BulkTransferSize", the pokemons will be transfered in the same time until almost full of the bag, but still some pokemons with high iv (>97iv) and low CP are not transfered by V1.0.0.52, especially many Pidgeotto and Raticate after autoevolvtion stay in the bag. But even worse by V1.0.0.62 ful und alll of pokemons with 100iv but low CP are not be transfered, no matter how i  set in the PokemonTransferFilter. 

pls check it and fix it if it is ture for all the users, thx.

**Comment by atheist05** [comment]
yeah i too need a config to transfer 100iv pokemons of low cp.It keeps all pokemons of 100 iv . My keepMinDuplicatePokemon is 1 ,still it keeps all pidgeys of 100iv's.My bag is full .

**Comment by samuraitruong** [comment]
It not a bug, cause by you have full bag 100% IV PKM

"KeepMinOperator": "or" with this config your bot will keep all pkm> 97%, with autosnipe that you will fullbag in 2 hours.
close as invalid bug

**Comment by KakacyOne** [comment]
yeh i know, in Pokemonconfig i set"KeepMinOperator": "or", but look at above what i made this issue, i set in the Transferfilter always **"KeepMinOperator": "and"** as follows, so all the pokemons with **"and"** should be transfered if against mincp and miniv, but it doesnt, it means Transferfilter works not fine

"Raticate": {
"KeepMinCp": 1250,
"KeepMinIvPercentage": 100.0,
"KeepMinLvl": 29,
"UseKeepMinLvl": false,
**"KeepMinOperator": "and",**
"KeepMinDuplicatePokemon": 0,
"Moves": [],

**Comment by samuraitruong** [comment]
i reopen it and double check, But seem only your filter issue since

**Comment by samuraitruong** [comment]
check again, still works fine as designed

**Comment by KakacyOne** [comment]
finally i know what is error now, i set in the "PokemonConfig": {} as follows:
**"FavoriteMinIvPercentage": 97.0,
"AutoFavoritePokemon": true,**

For the logic u define the bot that the pkms will be favorited at first, then transfered. By v52 the pkms can be transfered no matter they are already favorited, look follows from Consol by V52:
**[17:57:09] (INFO) 100% perfect Eevee (CP 636) *Favorited*.
[17:57:09] (EVOLVED) Potential Evolutions: 0
[17:57:15] (TRANSFERRED) Eevee	- CP: 636  IV: 100.00%   [Best CP: 636  IV: 100.00%] (Candies: 518)**

But by from V53 to V66 the pkms will not be transfered **because they are often(not always) favorited at first before transfered**, so the bag will be full of pkms with 100iv and low cp. Pls check this and fix it agai, thx.
