### ISSUE TITLE
Understanding the difference in release files

### ISSUE THREAD

**Issue by mahavidhan** [Necrobot-Private/NecroBot#546]
What is the difference between NecroBot2 in the Console folder and NecroBot2 in the NecroBot2.WIN folder. There are two exe files in the NecroBot2.WIN folder NecroBot2.Win.exe and NecroBot2.exe. I wanted some clarity on which one to use.

Also What is the difference between NecroBot2.GUI folder and NecroBot2.GUI.Electron folder?

Thanks

**Comment by samuraitruong** [comment]
NEcrobot2.win.exe is the GUI version, Necrobot2.exe is console version

GUI & Electron is 2 other web base GUI which is old and not maintian
