### ISSUE TITLE
Recycles pokeballs, hits pokestops more than attempts to catch pokemon

### ISSUE THREAD

**Issue by blackbird171151** [Necrobot-Private/NecroBot#547]
I have been going thru the code and settings but i am having trouble configuring it to not recycle pokeballs and try to catch pokemon first and then hit pokestops for pokeballs. bot runs great i just want to set it to catch more pokemon than hit stops so please help me if there is certain settings to obtain this. Thank You

## Stop! Before you create this issue (you can delete this section when opening the issue):
1. Have you searched to see if there are other Open/Closed issues for the same issue? If so, comment on that issue instead.
2. Have you validated that your config/auth.json and config/config.json is valid JSON? Use http://jsonlint.com/ to check.
3. If your question is referring to how to set up or use the bot, please join our discord instead of posting an issue: https://discord.gg/7FWyWVp 
4. Always confirm that your issue is reproducible, with the config you provide below.

### Your config.json:
```
replace this text with the contents of your config.json

```

### (OPTIONAL) Your Log:
```
replace this text with only the "relative" portion of your log. (Remove unnessary lines)

```

### Other Information
(Attach zip files if needed.)

Version:
Windows Version:
What is affected (catch, transfer, favorite, GPX, evolve, recycle, snipe, human walk snipe, pokestops, powerup/levelup, other):

**Comment by samuraitruong** [comment]
what you want to archive here?

**Comment by thephuong** [comment]
he proprably wants something like focusing on pokemon catch and only spinning pokestop when balls are run out. Not sure how this trick can help catching more pokemon.
