### ISSUE TITLE
Human Snipe Walk - TELEPORTS back to GPX track after catching target. Newest Source ATM.

### ISSUE THREAD

**Issue by DragonBlazer** [Necrobot-Private/NecroBot#55]
### Expected Behavior:

1. Bot walks to catch snipe target pokemon.
2. Bot will spin pokestops
3. Bot will catch pokemon at destination.
4. Bot will walk back to next GPX or origin.

### Actual Behavior:

1. Bot walks to catch snipe target pokemon.
2. Bot will spin pokestops
3. Bot will catch pokemon at destination.
4. Bot will **TELEPORT** back to next GPX or origin..

### Your config.json:
```
  "HumanWalkSnipeConfig": {
    "Enable": true,
    "DisplayPokemonList": true,
    "MaxDistance": 2000.0,
    "MaxEstimateTime": 900.0,
    "CatchEmAllMinBalls": 50,
    "TryCatchEmAll": false,
    "CatchPokemonWhileWalking": true,
    "SpinWhileWalking": true,
    "AlwaysWalkback": false,
    "SnipingScanOffset": 0.025,
    "WalkbackDistanceLimit": 5000.0,
    "IncludeDefaultLocation": true,
    "UsePokeRadar": true,
    "UseSkiplagged": true,
    "UseSnipePokemonList": true,
    "MaxSpeedUpSpeed": 60.0,
    "AllowSpeedUp": false,
    "DelayTimeAtDestination": 10000,
    "UseFastPokemap": true,
    "UsePogoLocationFeeder": false
```

### (OPTIONAL) Your Log:
```
replace this text with only the "relative" portion of your log. (Remove unnessary lines)

```

### Detailed Steps to Reproduce:
Run bot with above config
    "AlwaysWalkback": false, 
OR 
    "AlwaysWalkback": true, 

Both will make bot teleport.
In last release bot did not teleport back if it was set to false.

### Other Information
(Attach zip files if needed.)

Once bot teleports back, it sometimes gets softbanned/catch flee, if the distance back was too much.

Version: **Latest Source**. Includes all commits before and including: https://github.com/Necrobot-Private/NecroBot/commit/f9d79b4897b07335e359b5dcd5a60f30acb37170 
Windows Version: 10
What is affected (catch, transfer, favorite, GPX, evolve, recycle, snipe, human walk snipe, pokestops, powerup/levelup, other): GPX, human walk snipe.

**Comment by Silph-Road** [comment]
@samuraitruong 
Just tested with latest source, bot does indeed teleport back. 
Spin poke stops on way is working.

**Comment by Silph-Road** [comment]
@DragonBlazer what was the last version you tested that the bot did not teleport back?

**Comment by Silph-Road** [comment]
Or commit?
