### ISSUE TITLE
[Feature request] setting maximum radius

### ISSUE THREAD

**Issue by sackthesack** [Necrobot-Private/NecroBot#550]
Hello,

I don't know if it's possible but setting a max radius would be helpful if you want to stay in a specified location for a pokemon nest or something else. If the nest is a park which has a radius of 500m you can set maxRadius to 500m so you always stay in the nest.

Thanks

**Comment by joe1chen** [comment]
This is a dup of #91

**Comment by jjskuld** [comment]
Fixed now
