### ISSUE TITLE
[FeatureRequest] Alternating MaxTravelDistance [Relates To Issue #91]

### ISSUE THREAD

**Issue by Andi-fr** [Necrobot-Private/NecroBot#555]
**Problem:**
As mentioned in issue #91 
When MaxTravelDistance is activated and configurated the bot will 'draw / fill' circles on the map.

**Idea:**
The idea is to add an option that makes the bot leave this area sometimes. This could be realized by adding a similar setting to 'WalkingSpeedVariant' - e.g. by scaling / shrinking the walking distance (for n meters or percent) in relation to the bots runtime.
OR:
By moving the circles center on every 'n'-th 'next move' calculation to the current player position. And a few calculations later setting the position back to the configured one.
- As long the player is inside the configured circle nothing will change.
- When the player is next to the circles border he has a chance to leave the circle until the circles center is reset.

**Benefit:**
Such an option would concentrate the bots moves to the configured MaxTravelDistance but simulate a human like behaviour much better, if MaxTravelDistance is active.

**Comment by hardknoxni69a** [comment]
the bot is set to always goto the next avavilable pokestop that is closest. setting a wide area is likely not going to change the route that the bot actually takes as within the 5 minutes something closer to your center will be available but you can adjust your maxdistance to allow it to go out more plus with human walk it allows you to go outside for pokemon and it will return after so no worries
