### ISSUE TITLE
telegram display total exp wrong

### ISSUE THREAD

**Issue by samuraitruong** [Necrobot-Private/NecroBot#556]
![image](https://cloud.githubusercontent.com/assets/1183138/22011097/4155d10a-dce1-11e6-9ae3-6cf5472dd866.png)

**Comment by Andi-fr** [comment]
Its no bug just an different representation...

Level | XP Needed To Reach Level | Total XP
------------ | -------------| -------------
29 | 300,000 | 1,650,000
30 | 350,000 | 2,000,000
31 | 500,000 | 2,500,000

**For /status:**
It shows ~163500 / ~500000 XP to reach Level 31

**For /status:**
It shows (2)163500 / ~(2)500000 XP to reach Level 31
