### ISSUE TITLE
IV Accuracy

### ISSUE THREAD

**Issue by mahavidhan** [Necrobot-Private/NecroBot#557]
I have set "DumpPokemonStats": true, which gave me a file where all my pokemons are listed with their perfection (IV). I found difference in the IV that I got from necrobot and after appraising it manually in the app. For example in the app when I use appraisal system, I get "“Overall, your Pokemon is strong" which means it is definitely less than 82.2% but when I check IV of the same pokemon in the dumpstats, I see a different value which is higher than 83%. I wish to know how is this calculated and its accuracy if someone can shed some light on it. Thanks

**Comment by samuraitruong** [comment]
if you have dump, then don't need to ask, you can check (attack + defense + stamina)/45 = %IV

can you post you those attribute here?

**Comment by mahavidhan** [comment]
Chansey - HP 305 CP 807 Stardust 2500
The dump that I get from Necrobot says 83.43% IV with 13 Att 12 Def & 11 Sta

When I appraise, it says:
Overall, your Chansey is really strong!
Its best quality is its Attack
Its stats are really strong! Impressive
Thats what I think! See ya!

According to the sites given below, "Overall, your Chansey is really strong!" means its IV should be in the range of 66.7% to 80% but the necrobot dump shows it as 83.43%. If it was 83.43% as per the bot then appraisal should have said "Overall, your Chansey looks like it can really battle with the best of them!"
https://pokemongo.gamepress.gg/pokemon-appraisal
http://www.howtogeek.com/268616/how-to-calculate-your-pokemon%E2%80%99s-exact-ivs-with-pokemon-go%E2%80%99s-new-appraisal-system/
https://rankedboost.com/pokemon-go/appraisal/

Thanks for looking into it.

**Comment by hardknoxni69a** [comment]
i had a similar issue with ivs not reflecting correctly i think maybe it has to do with the update that happened a while back to pokemon being nerfed and buffed not sure if necro was ever updating to reflect correct values now

**Comment by samuraitruong** [comment]
the current fomular quite complicated, I make it to simple now (S + A +D)/45. I believe niantic ignore all other base value and only use individual value.  fixed in #575

**Comment by mahavidhan** [comment]
Thanks
