### ISSUE TITLE
[bug] NecroBot2.Win UI viewport sizing out of whack for the Pokedex and Pokémon/Eggs tabs

### ISSUE THREAD

**Issue by Axeia** [Necrobot-Private/NecroBot#563]
### Expected Behavior:
Normal screen filling viewports with the scrollbars in logical positions.

### Actual Behavior:
Scrollbars in odd places

Easier to show with screenshots so I added those below :). I assume this is due to using some weird size unit to position things on the screen which probably works on lower resolutions but I use a 2560x1440 screen and on it the UI looks rather weird.

### Other Information
(Attach zip files if needed.)
![image](https://cloud.githubusercontent.com/assets/1092845/22027828/54561b86-dcd5-11e6-8f37-3e2b5bd1afe8.png)
![image](https://cloud.githubusercontent.com/assets/1092845/22027634/be0fecd8-dcd4-11e6-96c8-ec03c12b70ad.png)
![image](https://cloud.githubusercontent.com/assets/1092845/22027867/855cef48-dcd5-11e6-8015-56a984e03d2d.png)

Version:
Windows Version:
What is affected (catch, transfer, favorite, GPX, evolve, recycle, snipe, human walk snipe, pokestops, powerup/levelup, other):

**Comment by samuraitruong** [comment]
yeah, i saw it, I going to fix it soon

**Comment by samuraitruong** [comment]
fixed
