### ISSUE TITLE
HELP please...Every pokemon flee...

### ISSUE THREAD

**Issue by jokki89** [Necrobot-Private/NecroBot#566]
Hello again

Could someone help me please.
I have the problem that today the whole day, for the first time ,that really EVERY pokemon flees.. :(
What should I do? 
Normally I would say it's a softban, but in this case i also couldn't spin the pokestops. However I can spin pokestops but it don't catches any pokemon...

Do someone know where the problem is please..

I get the whole day this messages

![unbenannt](https://cloud.githubusercontent.com/assets/24991970/22043548/68a4e00a-dd10-11e6-9b18-2b333543523b.PNG)

**Comment by samuraitruong** [comment]
you caught more than 1000 pkm in past 24h ,you got softban then you have to wait until is unban
or throw 200 ball miss

**Comment by jokki89** [comment]
@samuraitruong Ok , thanks :+1:
