### ISSUE TITLE
Bug - duplicate pokemon display in snipe GUI

### ISSUE THREAD

**Issue by samuraitruong** [Necrobot-Private/NecroBot#569]
![image](https://cloud.githubusercontent.com/assets/1183138/22048074/d9d6ecaa-dd7e-11e6-88f5-4d2ebd4642fa.png)

![image](https://cloud.githubusercontent.com/assets/1183138/22048080/e3121e66-dd7e-11e6-8f38-6df30f967e08.png)

**Comment by boscorelly** [comment]
which gui it is ?! i have never seen this !

**Comment by samuraitruong** [comment]
fixed
