### ISSUE TITLE
Sniping 

### ISSUE THREAD

**Issue by gatesjr** [Necrobot-Private/NecroBot#571]
still cannot get sniper to work, i changed everything in as it is in the link provided nothing, because those sites for sniping is not returning anything, can i ahve some assistance with this please, for one pokesnipers is no long available as well checked all sites set in sniping section

"SnipeConfig": {
    "UseSnipeLocationServer": true,
    "SnipeLocationServer": "localhost",
    "SnipeLocationServerPort": 16969,
    "GetSniperInfoFromPokezz": false,
    "GetOnlyVerifiedSniperInfoFromPokezz": true,
    "GetSniperInfoFromPokeSnipers": true,
    "GetSniperInfoFromPokeWatchers": false,
    "GetSniperInfoFromSkiplagged": false,
    "MinPokeballsToSnipe": 20,
    "MinPokeballsWhileSnipe": 0,
    "MinDelayBetweenSnipes": 60000,
    "SnipingScanOffset": 0.005,
    "SnipeAtPokestops": false,
    "SnipeIgnoreUnknownIv": false,
    "UseTransferIvForSnipe": false,
    "SnipePokemonNotInPokedex": false,
    "UseSnipeLimit": true,
    "SnipeRestSeconds": 600,
    "SnipeCountLimit": 39,
    "ActivateMSniper": true,
    "MinIVForAutoSnipe": 100,
    "AutosnipeVerifiedOnly": false,
    "DefaultAutoSnipeCandy": 0,
    "SnipePauseOnOutOfBallTime": 5

**Comment by atheist05** [comment]
Is your AutoSnipe turned false? Turn it to true if yes in DataSharingConfig as follows.:
"DataSharingConfig": {
    "EnableSyncData": true,
    "AutoSnipe": true,
    "DataServiceIdentification": "",
    "DataRecieverURL": "ws://necrosocket.herokuapp.com/socket.io/?EIO=3&transport=websocket"
  },

**Comment by samuraitruong** [comment]
:) closed. seem that you not check document, please check detail document at http://necrobot2.com

**Comment by gatesjr** [comment]
Thanks for the reply ok now it is working, but once you edit config to stop from sniping it still continues to snipe, is the sniping gonna cause a much higher change of getting banned without and with your API

**Comment by samuraitruong** [comment]
one pokemon has been select for snipe, it will still running until empty, that could be a enhancement
