### ISSUE TITLE
New API 0.65

### ISSUE THREAD

**Issue by DepecheMode2017** [Necrobot-Private/NecroBot#585]
Bot prompting that new API is in operation and will exit .. using latest version 0.65

[11:32:54] (ERROR) (KILLSWITCH) We have detected a Pokemon API change. The bot emulates API version 0.51.2, which is no longer supported.  Minimum API version is now 0.53.0.
[11:32:54] (ERROR) The bot will now exit after hitting the enter key.

**Comment by momentosnaps** [comment]
Perhaps it's time to play Pokemon Go manually for a few weeks. Wonders what happens to the API hash key that we have paid for.

**Comment by DepecheMode2017** [comment]
I do farm manually when I have the time though. True .. hoping the hash key will still be working.

**Comment by samuraitruong** [comment]
hash key is down too, just wait until hash key coming back

**Comment by atheist05** [comment]
Can I play using fake GPS apps on my phone?Is it risky?

**Comment by momentosnaps** [comment]
@samuraitruong , https://status.buddyauth.com/ says everything is working fine. :(

**Comment by momentosnaps** [comment]
@samuraitruong , I'm replying my own post so here goes. :)

Found this on the discord server from Pogodev.

So @everyone ,
Pokemon GO is in the process of being updated to version 0.53.1 (Android) and 1.23.1 for iOS. This means, that at some point Niantic will switch the version (noted above) to be the "minimum version". (usually this happens a few days after release).

As usual you get your keys extended with the exact amount of days you loose while our hashing service has a downtime. We start counting with the first day of that forced version change.

Kind Regards,
Eggie

**Comment by DepecheMode2017** [comment]
So it's not mandatory yet. Hash key is still working .. I got a secure connection. Anyway to bypass the killswitch?

**Comment by thelemonenergy** [comment]
It will work like forever, but you will be flagged as soon as 0.53 API is forced. 
They can force it at any moment from now on, so the killswitch is better not to be bypassed.

**Comment by juliansong62** [comment]
I have switched back to Legacy API (0.45) by changing the auth.json with my own risk about 30 minutes ago and it is still running without ban so far.

"APIConfig": {
    "UsePogoDevAPI": false,
    "AuthAPIKey": "****************",
    "UseLegacyAPI": true,
    "DiplayHashServerLog": false
  },

**Comment by thelemonenergy** [comment]
please report in 4 weeks if you were still not banned then, would be interesting.

**Comment by juliansong62** [comment]
By then, hoping the hash key will be up and running again.
Time to time, I am getting softban and captcha but as mentioned before it is my own risk.

[11:19:38] (SOFTBAN) Name: Carriage Fountain INFO: Looting failed, possible softban. Unban in: 1/40

[11:42:47] (INFO) Captcha is being show in separate thread window, please check your chrome browser and resolve it before 120 seconds
[11:43:01] (INFO) (CAPTCHA) Great!!! Captcha has been by passed

**Comment by juliansong62** [comment]
By setting the CaptchaConfig, there will be a Captcha window popped up in your browser.

  "CaptchaConfig": {
    "AllowManualCaptchaResolve": true,
    "ManualCaptchaTimeout": 120,
    "PlaySoundOnCaptcha": false,
    "DisplayOnTop": true,

**Comment by sammy150681** [comment]
I dont have any key, i always pass captcha manually..

**Comment by crwys123** [comment]
What website do I check waiting for the details of when/where the new hash keys are ready to be purchased?

**Comment by samuraitruong** [comment]
bot should work now, update 1.0.0.68 but please carefull since banwave still going on
