### ISSUE TITLE
GUI is showing 0/250 pokemon

### ISSUE THREAD

**Issue by jagauthier** [Necrobot-Private/NecroBot#598]
Seems to have started with .66

I see the console catching pokemon, but there are non showing in the inventory.
Restarting client did not help.

**Comment by mboeder** [comment]
same problem and stardust value is frozen

**Comment by boscorelly** [comment]
v67 bug here too.

**Comment by samuraitruong** [comment]
actually, the list will display after 1st pokestop hit, Not a big issue, I will fix it later

**Comment by mboeder** [comment]
@samuraitruong No, pokemon and egg list stays empty even after collecting several pokemon stops.

**Comment by boscorelly** [comment]
after 15 hours, still empty

**Comment by 6Vampire6** [comment]
This is correct for the items - they show up after the first stop. But the pokemon are not shown at all.

**Comment by boscorelly** [comment]
same problem in v68

**Comment by jjskuld** [comment]
Fixed in v1.0.0.69
