### ISSUE TITLE
[request] gui translation

### ISSUE THREAD

**Issue by boscorelly** [Necrobot-Private/NecroBot#600]
is it possible to translate gui ?
i can translatz it in french if you provide informations about it (maybe a language file to create from the english one ?)

**Comment by samuraitruong** [comment]
consider as feature request, I will added I18N support later

**Comment by samuraitruong** [comment]
pretty much done quite lot of text, need community contribute to translate. there is the ui.en.json generate for default english

**Comment by boscorelly** [comment]
i don't find the file in the repo :/
