### ISSUE TITLE
Pokemon should heal also after attacking gym

### ISSUE THREAD

**Issue by RikudouSage** [Necrobot-Private/NecroBot#601]
### Expected Behavior:

Healing after attacking gym

### Actual Behavior:

Not healing after attacking gym

### Detailed info

I find it logical that you deploy your strongest Pokémon to gym after you take it down. This is not possible since they are not healed after attack and so it will print the error **Deploy pokemon failed with results: ErrorPokemonNotFullHp**. There should be an option to also heal after attacking gym.

Version: 1.0.0.67
Windows Version: 10
What is affected: Deploying to gym after attacking it

**Comment by macinmn** [comment]
do you have
"HealDefendersBeforeApplyToGym": true,
?

**Comment by ziomber** [comment]
they are always healed before attack not after. I can add such config but why???
@macinmn that option tels to heal defender before apply to gym, if is set to false it takes first pokemon with full hp and aplies him to gym, This is to leave potions for attackers

**Comment by RikudouSage** [comment]
Well I like to put the strongest one to gym, which is not possible because he does not have full HP. I'd like to set the exclude rule to 0 so the first strongest is put into gym.

**Comment by ziomber** [comment]
so, like @macinmn said, use HealDefendersBeforeApplyToGym and set it to true

**Comment by RikudouSage** [comment]
Ok, thanks.
