### ISSUE TITLE
Pokémon tab slow to sort and can't be scrolled with the scroll wheel 

### ISSUE THREAD

**Issue by Axeia** [Necrobot-Private/NecroBot#603]
Since running the latest updated I've noticed that the bug I reported previously of the list not taking up the entire screen was fixed, however I think this may have introduced 2 new problem 

- Sorting the list by clicking on a header is much slower than it previously was. This used to be instant, now it takes about 3 seconds. (also feature request: Make it stick to the top so it's visible at all times even when scrolling down)
- I can't scroll down the list using the scrollwheel on my mouse

Maybe just copy/paste whatever the sniper tab is using(?) as that works fast with sorting, has a sticky header and can be scrolled with the scroll wheel.

Version:  v1.0.0.67

**Comment by samuraitruong** [comment]
how many you have in your bag? 1000 PKM

**Comment by samuraitruong** [comment]
fixed in 1.0.0.68

**Comment by Axeia** [comment]
222 / 250, I don't think this should be due to numbers or hardware limitations. This is on a 3Ghz Core i5-4590S with 16GB of RAM. I have noticed this is not just sorting that is slow - simply clicking the tab and loading the list is very slow as well.

**Comment by Axeia** [comment]
![ezgif com-ae5bb7d71e](https://cloud.githubusercontent.com/assets/1092845/22174181/6c151302-dfd8-11e6-811d-95e02bb9cf86.gif)

Seems to be a lot of CPU-power going into something.
