### ISSUE TITLE
farmPokestopsNoUsableFound

### ISSUE THREAD

**Issue by Malitomen** [Necrobot-Private/NecroBot#608]
Hello, I have this problem:
No Pokestop's available in your area. Have you set a maximum distance too small?
I get this error, and I have already configured the distance several times. Or am I doing something wrong?

**Comment by thelemonenergy** [comment]
Is the problem persistent or does it work after a while?
Are you using the hash server? If so, hoow many bots are you running with one hash key and how many rpm did you buy?

**Comment by samuraitruong** [comment]
look like pokestop softban, ip softban or he jump to fast

**Comment by crwys123** [comment]
Probably soft ban, I am getting the same results. Tried reverting to older version did not fix. I play very safe other than doing auto snipe for about 10 minutes once a week or so. Guess i'll wait 24 hours and hope for the best.

**Comment by dbottroff** [comment]
I'm receiving the same error.
I'm using only one bot with 3 accounts.
No account works locally.
2 accounts created specifically for this work in NYC. 
1 account used primarily locally works nowhere, ive left it alone for 24 hours. Verified all accounts are not softbanned locally.

**Comment by jjskuld** [comment]
@dbottroff This is a new IP softban that Nia started doing more in 0.53.  You need to get a new IP if you are on a dynamic IP, otherwise try to wait it out.

**Comment by dbottroff** [comment]
Well I just got home to test this theory and despite changing IPs still no Pokestops when near home on 2 accounts. The only account I didn't touch today continues to work in NYC.

**Comment by Malitomen** [comment]
Which version works best?
