### ISSUE TITLE
pogodev api 

### ISSUE THREAD

**Issue by sammy150681** [Necrobot-Private/NecroBot#611]
some question:
1 - pogodev api works good or in this period dont work?
i have no risk ban?
2 - snipe is safe ?
thanks

**Comment by momentosnaps** [comment]
There is always a risk with sniping but the way it works minimize the factor. Been running the latest release since yesterday (18 hours so far) without any problems but the risk is still there. 

The Pogodev hash has been updated to comply to the latest
