### ISSUE TITLE
Risk in using bot now

### ISSUE THREAD

**Issue by atheist05** [Necrobot-Private/NecroBot#619]
I have not been botting since the last update to play safe.But i see people still botting .I just wanna know that how risky is it to start botting now?In what circumstances is a player permanent banned?Shouid I bot ?

**Comment by jokki89** [comment]
I don't know but I think it is a higher risk now.. my main account doesn't work until 3 days now.. and i can't even log in on the iphone.. i think its banned :(  Is there any option to get unbaned?

**Comment by hykilpikonna** [comment]
You will get banned if you just start it once before updating.

**Comment by hykilpikonna** [comment]
ONCE

**Comment by coco73** [comment]
jokki89, also my account is not working from 3 days ago, but if we did not receive the email of ban from google, i dont think is much problem. I have sent them and email , and the answer is "

Trainer,

We have received your appeal. Our goal is to provide a fair, fun and legitimate game experience for everyone. Use of any other third-party software or app, including but not limited to scripts/apps, applications used to falsify your location, emulators, modified or unofficial software and/or accessing Pokémon GO clients or backends in an unauthorized manner is considered cheating.

We are reviewing all account termination appeals. If our system determines that your account was terminated in error, we will send an email to confirm that your account has been reinstated.

If you have not received an email stating your account was terminated, but are experiencing login issues or map loading errors it may just be a temporary server issue. Please try to login again in a few hours.

-NianticOps."

And i am still trying to connect, i will wait, tha's it.

**Comment by jokki89** [comment]
Hy @coco73 , okay... I hope u're right... 
So do you think i sould also write an e-mail to niantic too or should i still wait and try to log in? 
I didn't get any mail from niantic that the account is banned but I get everytime when I log in the message :  "authentication faild, try it again"
