### ISSUE TITLE
(Doubt) Option to not touch pokestops

### ISSUE THREAD

**Issue by tr1p0z** [Necrobot-Private/NecroBot#63]
There is an option to not get pokestops in the configuration? Like capturePokemons off but with pokestops

**Comment by CreativiTimothy** [comment]
You can set Pokestops limit to 0 or 1 and it will work. But I would like this feature as well without having to work around and set a limit. Just a simple "LootPokestops": true/false

**Comment by tr1p0z** [comment]
Apparently it works, thanks.

**Comment by tr1p0z** [comment]
Maybe not correctly, also not try to go to gyms.

**Comment by tr1p0z** [comment]
![truy](https://cloud.githubusercontent.com/assets/6554123/18413881/fd6668e0-77b6-11e6-86e5-f09d266b2fc3.png)

**Comment by tr1p0z** [comment]
The option should completely ignore the "pokestops" not also gyms

**Comment by tr1p0z** [comment]
I would like to have it checked by a developer, it would be good to have this option as soon as possible and be able to choose what to visit. Thanks a lot.

**Comment by Brazuca87** [comment]
The bot will always walk towards Pokestops, as Pokestops is what makes your pathing (and checking for lured pokemons)

**Comment by CreativiTimothy** [comment]
@Brazuca87 Gyms can also make your pathing as well. If Pokestops and gyms are disabled, maybe we can make the player wander around in an egg hatching circle within specificed meter distance

**Comment by tr1p0z** [comment]
Other bots have the option to ignore, I think it is also possible to go only for gyms without having to go through the pokestops.

**Comment by tr1p0z** [comment]
Something new?
