### ISSUE TITLE
gim problem when finish battle

### ISSUE THREAD

**Issue by sammy150681** [Necrobot-Private/NecroBot#635]
:
10:04:48] (GYM) Great!!! Your Seaking now is defending for GYM Monumento ad Alessandro Farnese
[10:04:48] (GYM) You have only 2 defenders deployed but 3 required to get reward
[10:04:48] (ERRORE) Pokemon Servers might be offline / unstable. Trying again...
[10:04:48] (ERRORE) Error: System.NullReferenceException: Riferimento a un oggetto non impostato su un'istanza di oggetto.
   in PoGo.NecroBot.Logic.Tasks.UseGymBattleTask.<>c__DisplayClass21_0.<CanTrainGym>b__0(PokemonData a) in c:\projects\necrobot2\PoGo.NecroBot.Logic\Tasks\UseGymBattleTask.cs:riga 946
   in System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   in PoGo.NecroBot.Logic.Tasks.UseGymBattleTask.CanTrainGym(ISession session, FortData fort, GetGymDetailsResponse gymDetails, IEnumerable`1 deployedPokemons) in c:\projects\necrobot2\PoGo.NecroBot.Logic\Tasks\UseGymBattleTask.cs:riga 946
   in PoGo.NecroBot.Logic.Tasks.UseGymBattleTask.<Execute>d__2.MoveNext() in c:\projects\necrobot2\PoGo.NecroBot.Logic\Tasks\UseGymBattleTask.cs:riga 81
--- Fine traccia dello stack da posizione precedente dove è stata generata l'eccezione ---
   in System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   in System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   in PoGo.NecroBot.Logic.Tasks.UseGymBattleTask.<StartGymAttackLogic>d__3.MoveNext() in c:\projects\necrobot2\PoGo.NecroBot.Logic\Tasks\UseGymBattleTask.cs:riga 250
--- Fine traccia dello stack da posizione precedente dove è stata generata l'eccezione ---
   in System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   in System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   in PoGo.NecroBot.Logic.Tasks.UseGymBattleTask.<Execute>d__2.MoveNext() in c:\projects\necrobot2\PoGo.NecroBot.Logic\Tasks\UseGymBattleTask.cs:riga 87
--- Fine traccia dello stack da posizione precedente dove è stata generata l'eccezione ---
   in System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   in System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   in PoGo.NecroBot.Logic.Tasks.UseNearbyPokestopsTask.<Execute>d__8.MoveNext() in c:\projects\necrobot2\PoGo.NecroBot.Logic\Tasks\UseNearbyPokestopsTask.cs:riga 68
--- Fine traccia dello stack da posizione precedente dove è stata generata l'eccezione ---
   in System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   in System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   in PoGo.NecroBot.Logic.Tasks.FarmPokestopsTask.<Execute>d__1.MoveNext() in c:\projects\necrobot2\PoGo.NecroBot.Logic\Tasks\FarmPokestopsTask.cs:riga 60
--- Fine traccia dello stack da posizione precedente dove è stata generata l'eccezione ---
   in System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   in System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   in PoGo.NecroBot.Logic.State.FarmState.<Execute>d__0.MoveNext() in c:\projects\necrobot2\PoGo.NecroBot.Logic\State\FarmState.cs:riga 51
--- Fine traccia dello stack da posizione precedente dove è stata generata l'eccezione ---
   in System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   in System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   in PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.Mo

**Comment by ziomber** [comment]
forget it. will be fixed asap
