### ISSUE TITLE
Some help whit config need config plz

### ISSUE THREAD

**Issue by xRpwn** [Necrobot-Private/NecroBot#637]
Hello Everyone.

My problem its simple. I know is probably one post here with the same problem but i want to know if someone have one good config to not be banned plz because it's the 3rd time i need to make a new acc. all the time i get lvl 30 i got banned :S

**Comment by samuraitruong** [comment]
this banwave quite hard for all bot, no config safe

**Comment by xRpwn** [comment]
ye i know But my config only lasts about 1 month

**Comment by xRpwn** [comment]
If someone has a config that I can test to see if it lasts longer than the ones I have used I would be very grateful

**Comment by andeomontenegro** [comment]
just try NOT train higher than 80k exp at 24h.
