### ISSUE TITLE
Connection (???) problem during evolution.

### ISSUE THREAD

**Issue by SLASHLogin** [Necrobot-Private/NecroBot#647]
it's happening from ...0.71 after message about evolution.

[20:29:25] (WYEWOLUOWAŁ) Pokemon'y oczekujące na ewolucje: 10
[20:29:25] (AKTUALIZACJA) Pokemonów oczekujących na ewolucje: 10 | Możesz złapać ich jeszcze: 53 | 67/120 dla 99% ekwipunku
[20:29:26] (BŁĄD) Pokemon Servers might be offline / unstable. Trying again...
[20:29:26] (BŁĄD) Error: System.NullReferenceException: Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.
   w PoGo.NecroBot.Logic.Tasks.TransferDuplicatePokemonTask.d__1.MoveNext() w c:\projects\necrobot2\PoGo.NecroBot.Logic\Tasks\TransferDuplicatePokemonTask.cs:wiersz 107
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   w PoGo.NecroBot.Logic.Tasks.TransferDuplicatePokemonTask.d__0.MoveNext() w c:\projects\necrobot2\PoGo.NecroBot.Logic\Tasks\TransferDuplicatePokemonTask.cs:wiersz 88
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   w PoGo.NecroBot.Logic.Tasks.CatchPokemonTask.d__4.MoveNext() w c:\projects\necrobot2\PoGo.NecroBot.Logic\Tasks\CatchPokemonTask.cs:wiersz 468
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   w PoGo.NecroBot.Logic.Tasks.CatchNearbyPokemonsTask.d__0.MoveNext() w c:\projects\necrobot2\PoGo.NecroBot.Logic\Tasks\CatchNearbyPokemonsTask.cs:wiersz 125
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w PoGo.NecroBot.Logic.Tasks.UseNearbyPokestopsTask.d__12.MoveNext() w c:\projects\necrobot2\PoGo.NecroBot.Logic\Tasks\UseNearbyPokestopsTask.cs:wiersz 156
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w PoGo.NecroBot.Logic.Tasks.UseNearbyPokestopsTask.<>c__DisplayClass10_0.<b__0>d.MoveNext() w c:\projects\necrobot2\PoGo.NecroBot.Logic\Tasks\UseNearbyPokestopsTask.cs:wiersz 138
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   w PoGo.NecroBot.Logic.Strategies.Walk.BaseWalkStrategy.d__19.MoveNext() w c:\projects\necrobot2\PoGo.NecroBot.Logic\Strategies\Walk\BaseWalkStrategy.cs:wiersz 220
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w PoGo.NecroBot.Logic.Strategies.Walk.MapzenNavigationStrategy.d__4.MoveNext() w c:\projects\necrobot2\PoGo.NecroBot.Logic\Strategies\Walk\MapzenNavigationStrategy.cs:wiersz 52
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w PoGo.NecroBot.Logic.Navigation.d__14.MoveNext() w c:\projects\necrobot2\PoGo.NecroBot.Logic\Navigation.cs:wiersz 100
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w PoGo.NecroBot.Logic.Tasks.UseNearbyPokestopsTask.d__10.MoveNext() w c:\projects\necrobot2\PoGo.NecroBot.Logic\Tasks\UseNearbyPokestopsTask.cs:wiersz 134
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   w PoGo.NecroBot.Logic.Tasks.UseNearbyPokestopsTask.d__8.MoveNext() w c:\projects\necrobot2\PoGo.NecroBot.Logic\Tasks\UseNearbyPokestopsTask.cs:wiersz 64
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   w PoGo.NecroBot.Logic.Tasks.FarmPokestopsTask.d__1.MoveNext() w c:\projects\necrobot2\PoGo.NecroBot.Logic\Tasks\FarmPokestopsTask.cs:wiersz 60
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   w PoGo.NecroBot.Logic.State.FarmState.d__0.MoveNext() w c:\projects\necrobot2\PoGo.NecroBot.Logic\State\FarmState.cs:wiersz 51
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   w PoGo.NecroBot.Logic.State.StateMachine.d__3.MoveNext() w c:\projects\necrobot2\PoGo.NecroBot.Logic\State\StateMachine.cs:wiersz 97

**Comment by samuraitruong** [comment]
fixed ,
