### ISSUE TITLE
Accounts.db gets appended when accounts switches

### ISSUE THREAD

**Issue by momentosnaps** [Necrobot-Private/NecroBot#654]
When running multibots, accounts.db gets appended to which creates more accounts to select to start from when SelectAccountOnStartUp is set to True.

It should update the running time of the previous account instead of just appending to the list.

**Comment by samuraitruong** [comment]
I didn't see this issue, can you clarify what was the issue you have?

**Comment by momentosnaps** [comment]
I have set "SelectAccountOnStartUp" to true. The list for selection gets
longer and longer as time goes on. I have to delete accounts.db for it to
be normal again.

**Comment by samuraitruong** [comment]
is it still happening in 0.78?

**Comment by momentosnaps** [comment]
Running 0.79 now and it's still giving the same errors.

**Comment by samuraitruong** [comment]
I think you solve your issued, close
