### ISSUE TITLE
Looking for relevant settings for maximizing lucky eggs / redesign

### ISSUE THREAD

**Issue by pokkemonner** [Necrobot-Private/NecroBot#655]
For some reason I am not able to use lucky eggs on mass evolving properly.
The issues I face:
1. At some point I end up with a sh*tload of pidgey candy (2000 +) not seen by the code,
even when I manually transfer all pidgeottos an restart the bot
 
2. Lucky egg threshold is not respected.   

[06:58:23] (EVOLVED) Potential Evolutions: 2
[06:58:23] (INFO) Catch 28 more Pokemon to use a Lucky Egg!
[06:58:32] (EVOLVED) 1. Pidgey successfully for 500xp
[06:58:53] (EVOLVED) 2. Pidgey successfully for 500xp
[06:58:53] (INFO) Amount of Pokemon Seen: 139/151, Amount of Pokemon Caught: 84/151

I have tried all combinations on the countless combinations to make. What I am looking for is a set of options that should guaranty a respected lucky egg threshold or a code redesign

**Comment by hardknoxni69a** [comment]
by the looks of it you have minium 30 evolutions so lucky egg will not be used unless you have 30 pokemon ready to evolve you need to set keeppokemon that can evolve to true and what percent of inventory you want it to try to start evolutions so if you have 30 ready when bag is at say 100% it will use egg
