### ISSUE TITLE
Hash API Server Might Be Down/API Key Might Be Wrong Or Expired.

### ISSUE THREAD

**Issue by GetShwiffty** [Necrobot-Private/NecroBot#656]
Hello everyone I just recently purchased a key about 2 days ago and on the first day everything worked perfectly fine but then on the second when I got home from work I noticed this error coming up quite a bit. First it would say API Key Might Be Wrong Or Expired but then it would relog in and everything would work again for a minute or two but then a really long error would come up like 3 or 4 times in a row and then it would keep saying Hash API Server Might Be Down like 20 or 30 times before it would start working again. Is the API Key Wrong message just a side effect of the server acting up?

**Comment by GetShwiffty** [comment]
![capture](https://cloud.githubusercontent.com/assets/25382683/22364990/1c8c3792-e443-11e6-80d9-4aa96b2277cd.PNG)

**Comment by momentosnaps** [comment]
It's an issue with Pokefarmer API hash server. Nothing to do with Necrobot.

**Comment by GetShwiffty** [comment]
Ok thanks for letting me know, it seems to be working fine now. If anyone is willing to answer what is the max speed you can go before pokemon stop spawning?

**Comment by momentosnaps** [comment]
A normal human walking speed is about 4-6 km/hr. I found that if you don't snipe, any settings beyond 11 km/hr seems to grab less spawns. YMMV.

**Comment by GetShwiffty** [comment]
Alright cool thanks again!
