### ISSUE TITLE
[Announcement] In The 0.37 New API Will Change , AND BOT WILL DOWN

### ISSUE THREAD

**Issue by Silph-Road** [Necrobot-Private/NecroBot#66]
As the title says, bot will go down soon.
New API changes coming.

Please don't blow up Issues page, when it happens. 
Just check discord or wait for announcement.

**Comment by petpetpetvm** [comment]
is there any reason for closing this ? no new api incoming ?

**Comment by Silph-Road** [comment]
nope, sadly new API still coming.... just don't want to start a panic :-)

**Comment by Silph-Road** [comment]
within 24-48 hours new API will be active = bots down.

**Comment by Silph-Road** [comment]
Do not poke gentle into that good night,
Old l33t should burn and rave at close of day;
Reverse, engineer against the dying of the light.

Though wise devs at their end know dark is right,
Because their code had forked no github they
Do not poke gentle into that good night.

Good devs, the last banwave by, crying how bright
Their frail pokemon might have danced in a green bay,
Reverse, engineer against the dying of the light.

Wild devs who caught and sang the dratini in flight,
And learn, too late, they grieved it on its way,
Do not poke gentle into that good night.

Grave men, near death, who see with blinding sight
Blind eyes could blaze like meteors and be gay,
Reverse, engineer against the dying of the light.

And you, Niantic, there on the sad height,
Curse, bless, me now with your fierce tears, I pray.
Do not poke gentle into that good night.
Reverse, engineer against the dying of the light.


Credit: ChthulhuLovesAllHisChildren

**Comment by tr1p0z** [comment]
@Silph-Road go to sleep now

**Comment by Silph-Road** [comment]
That time is an estimate of when the app will be released in the app and play store, followed by a forced update. :-(
