### ISSUE TITLE
Continue from last position doesn't seem to be working.

### ISSUE THREAD

**Issue by GetShwiffty** [Necrobot-Private/NecroBot#662]
Hello again the continue from last position doesn't seem to be working I have it enabled but when I close out of the bot my guy starts back from the default lat,long setting I have.

**Comment by saldotman** [comment]
me too. 
every time I close my bot, and start it again. I see from the GUI, the location will always be in the same location. I use gpx path

**Comment by pokkemonner** [comment]
same here. no more lastpos.ini is generated.

**Comment by hardknoxni69a** [comment]
currenty at the moment the moment lastpos.ini is tied directly to necrobot2.exe i take it you are using the WinGui and that will need to be updated to record lastpos.ini on close as well

**Comment by jjskuld** [comment]
Ok, i've fixed it. Will be in the next release.
