### ISSUE TITLE
Won't reach Pokemon Catch/Stop limit with default settings?

### ISSUE THREAD

**Issue by GetShwiffty** [Necrobot-Private/NecroBot#675]
If I leave the config file with the default settings will I be able to effectively run the bot all day and night without having to worry about hitting the daily limit of caught Pokemon or spun Pokestops? I just want to let it run all day and night without having to worry about reaching the point of all the Pokemon fleeing from reaching the daily limit.

**Comment by samuraitruong** [comment]
make config by your self, necrobot can hit to limit after 3 hours, how could you want it run 24h with default config

**Comment by GetShwiffty** [comment]
Did you even understand what I was asking before you closed the issue? Preventing anyone else from providing an answer who understands English fluently?
