### ISSUE TITLE
snipe stop

### ISSUE THREAD

**Issue by pizzafight** [Necrobot-Private/NecroBot#676]
when I activate an 40account with a proxy Snipe does not activate.
It will not resume even after 10 hours. It is not IPBAN and blacklist
what is the cause?

**Comment by samuraitruong** [comment]
it be block for sure.

**Comment by pizzafight** [comment]
What should I do if there is no IP on blacklist?

Can you put it in the whitelist if you write IP here?

**Comment by hardknoxni69a** [comment]
this is actually a good idea for your loyal people perhaps there is a way to add accounts to the site and the person can register there ip so it is automatically added

**Comment by samuraitruong** [comment]
the new version now allow you to use private key to whitelist your IP. check 1.0.0.83
