### ISSUE TITLE
Hyper Beam

### ISSUE THREAD

**Issue by nhumber** [Necrobot-Private/NecroBot#678]
ill reference issue #602 , im experiencing this same bug on the latest version as of today .80

i see it was fixed with version .67 

has something been re introduced that is causing the bug again?

i reverted back to version .67 and the bug is still present.

anyone have this issue still? or it just me?

**Comment by ziomber** [comment]
it's problem with many special attacks, not only hyper beam. There is a lot of errors :( be patient, work is in progress

**Comment by ziomber** [comment]
Hyper beam is not fixed but there is place in config to block using it. I've put there by default dragonite's and snorlax's hyper beam and lapras's blizzard.
The attack is going out but with no effect and wastes time. I thing it's some api issue...

**Comment by nhumber** [comment]
i built your pull last night and tested a bit, i notice that dragonite hyperbeam doesn't work but continues on with regular attacking.. Huge improvement over stalling out like it was. there are a few other moves i've noticed it affecting, ill go ahead and norrow it down using the list in the config.. if its an API issue, i guess we just live with it.. 

can we get a flag for max CP of attacker? Something like min CP of attacker: XX and max CP to use either in a number or percentage of first defenders CP.

biggest issue i see is no matter what gym is visited, first choice is always 3250cp dragonite.. which makes essentially every single training battle worth only 100 prestige. also it seems to only get to defender/attacker #3 and then ends the gyms battle, resulting in error on next gym battle. can we add a toggle for training to only train against X amount of defenders then run from battle regardless of gym lvl or defender numbers

training is just so much more efficient, even if it takes 3 attackers with 50% less CP than the first defender to get the win, if the bot would just run from battle after first fight and redo it twice, it opens a spot in less than 180 seconds rather than the time it takes to defeat 20 defenders @ 100 presteige..

A different approach that would probably require a full rework but could simplify things in the long run would be to assign flags to specific pokemon and make groups Defender/Attacker/Prestiger . the bot would then select the best choice/type advantage from the list of Attackers before starting an attack, and also would do the same based on type and cp limits for training,, then insert a "defender" into the gym.

dont take any of that as being critical, the work your doing here is awesome, what you've accomplished so far is great and nothing short of amazing work.

thanks again.

**Comment by sammy150681** [comment]
i have the same problem, hyperbeam dont work

**Comment by ziomber** [comment]
I've mage some sort of pokemon factor to get best attacker only (as for now). Maybe to much points is going for CP (one point for each 5% CP more than defender). For attack with low lvl trainer is good (i'm low lvl becouse i've lost my account and was forced to make new one, so now i'm 25lvl only). For training i'll make another factor profile where CP over defender CP will get points on minus.
> also it seems to only get to defender/attacker #3 and then ends the gyms battle, resulting in error on next gym battle

Tell me more. I've noticed such behaviour but without any error message so I didn't had a point to start dig around.
Now i'm working on dodge. Function is working but in current scenario is hard to find right time to make it happend.
Switching pokemon is also working and not. Call to api is going out and even sometimes is realy swithing but in most of cases is not...
@sammy150681 hyper beam and blizzard as for now will be not working. API call is going out without errors, i've getting right responce, everything is just fine except of that it's not working at all. I've tried to wait more time before and after call, but without any positive results.

**Comment by sammy150681** [comment]
Earthqake dont work too

**Comment by sammy150681** [comment]
I m positive, but before this update all movest work

**Comment by nhumber** [comment]
Heres where im at currently for non working moves. im 95% sure that solarbeam is broken on all attackers, as with hydropump but i cant confirm until i see them actually fail in battle. Heat wave is also not working but ill get confirmation on that.

today ill try and norrow it down further.. 

ill also start logging gameplay to see if we can get some error messages for you to look at.


  "GymConfig": {
    "NotUsedSkills": [
      {
        "Key": "snorlax",
        "Value": "hyperBeam"
      },
      {
        "Key": "dragonite",
        "Value": "hyperBeam"
      },
      {
        "Key": "venusaur",
        "Value": "solarBeam"
      },
      {
        "Key": "poliwrath",
        "Value": "hydroPump"
      },
      {
        "Key": "vaporeon",
        "Value": "hydroPump"
      },
      {
        "Key": "lapras",
        "Value": "blizzard"
      }
    ],

**Comment by ziomber** [comment]
hmm, strange, my vaporeon hydroPump is working fine...

**Comment by nhumber** [comment]
ill try again, its possible its not always failing..

**Comment by nhumber** [comment]
hydropump on vap is hit or miss.. it works on 2 of 3 vaperions.. not sure why.. 
any chance u can work on adding train with CP below first defender if over defender is over XXCP
bots are doing well at holding gyms.. it'd be nice if they could be slightly more efficient at opening spots for actual players

**Comment by andeomontenegro** [comment]
how to exclude hyperbeam-pokemons from attacker list?

**Comment by hardknoxni69a** [comment]
exclude list has been implemented for moves that dont work in gym
