### ISSUE TITLE
AutoSnipe Issues! Asking For A Ban?!?!?!?

### ISSUE THREAD

**Issue by hardknoxni69a** [Necrobot-Private/NecroBot#679]
Currently AutoSnipe Limits Are Not Working And Filters Are Not Working!
AutoSniping should only snipe pokemon that are in our pokemon to snipe list or in the snipe filter list. I also have it set to snipe at pokestops and take a 1 minute break between snipes but the bot will just snipe multiple pokemon back to back instead of sniping and taking a 1 minute walk catching local mon and stops. Say i only have chancey on my lists the bot will go to a stop spin then snipe a pidgey, dratini, dratini, pidgey,etc back to back. it should go to a stop autosnipe 1 chancey then during the 60 sec break catch local mon or spin local stops once 60 secs is up at the next stop it will try to snipe another chancey if none are on snipesite contine as normal

**Comment by samuraitruong** [comment]
actually, I run with this and no ban at all, filter are working, make sure you are not setup candy snipe mode.

**Comment by andeomontenegro** [comment]
need a WIKI update with new filters FAQ...

**Comment by hardknoxni69a** [comment]
i only have certain pokemon on my list and pidgey is not one of them i would love to use autosnipe but it needs to be set up correctly or atleast have the filters and limits work my bot will sit there and snipe over and over this is very unsafe the bot should follow the limits if people want to back to back snipe let them set the rest to 0 but with the way its set it should only snipe 1 pokemon after a stop then continue locally please fix 
    "UseSnipeLimit": true,  = i have this on to make it follow limits
    "SnipeRestSeconds": 60,  = after a snipe the bot should not snipe till after 60 seconds
    "SnipeCountLimit": 1,  = this should be how many it auto snipes throughout use or in a row
    "ActivateMSniper": true,
    "MinIVForAutoSnipe": 0,
    "AutosnipeVerifiedOnly": true,
    "DefaultAutoSnipeCandy": 0,
    "SnipePauseOnOutOfBallTime": 5,
    "AutoSnipeMaxDistance": 0.0
  "PokemonToSnipe": {  these are the only pokemon i should snipe but it snipes pidgeys as well
    "Locations": [],
    "Pokemon": [
      "lapras",
      "dragonite",
      "snorlax",
      "dratini",
      "dragonair",
      "abra",
      "machop",
      "charmander",
      "bulbasaur",
      "squirtle"

**Comment by andeomontenegro** [comment]
same problem

**Comment by hardknoxni69a** [comment]
when it comes to sniping i believe the key is to catch local and spin locals between snipes this would be much safer it it worked the right way please help @samuraitruong i know your the snipe master

**Comment by hardknoxni69a** [comment]
this issue is in the code as a batch to snipe 10 pokemon in row making new issue to be more direct
