### ISSUE TITLE
New Version Pokemon Go was arrived!

### ISSUE THREAD

**Issue by aryaputrapande** [Necrobot-Private/NecroBot#68]
Pokemon Go v0.37.0 has released. What is Necrobot2 support it? Must we stop bot for a while until new version of Necrobot2 release?

**Comment by petpetpetvm** [comment]
i think we should stop botting for a day lol :3 and maybe wait for a new version

**Comment by vfuyong** [comment]
If someone tested botting with 0.37 please update here. Thanks.

**Comment by tr1p0z** [comment]
**_Soon there will be ban wave, everyone is going to fall, you can be sure of that. I'm currently using the bot, but I guess everyone has been flagged. For greater security stop using it temporarily until the release of the new API._**

**Comment by vfuyong** [comment]
The API may not change for the release notes I have read so far. But there is no guarantee.

**Comment by msx752** [comment]
please don't use bot for a while, **ban wave is coming**

**Comment by Delta1977** [comment]
on IOS ( APP Store ) is still the Version 1.5.0 from 24.8. active

**Comment by p3monty** [comment]
the banwave gets everyone nevermind if we keep botting now lol

**Comment by yohudood** [comment]
still 0.35.0 in eu

**Comment by zc3721** [comment]
still 0.35

yohudood <notifications@github.com>于2016年9月11日周日 09:16写道：

**Comment by vfuyong** [comment]
0.35 still in Australia.

**Comment by p3monty** [comment]
in germany already 0.37

**Comment by zc3721** [comment]
san francisco no 0.37

p3monty <notifications@github.com>于2016年9月11日周日 15:40写道：

**Comment by vfuyong** [comment]
@p3monty Can you do a test to see whether bot can log in?

**Comment by vaca1** [comment]
still 0.35 in taiwan..

**Comment by Prawith** [comment]
still 0.35 in Thailand.

**Comment by ntatoo** [comment]
The Bot Still Work ,
The Server On Most Country Still 0.35
