### ISSUE TITLE
Get running with wine

### ISSUE THREAD

**Issue by jagauthier** [Necrobot-Private/NecroBot#682]
Any tips on how to get this running with wine? 

I guess since it's .NET, you must use mono.
My first interaction results in this error:

System.IO.FileNotFoundException: Could not load file or assembly 'PoGo.NecroBot.Logic, Version=1.0.0.81, Culture=neutral, PublicKeyToken=null' or one of its dependencies.

I compiled from source, and copied the DLLs from PoGo.NecroBot.Logic/bin/Debug/ to PoGo.NecroBot.CLI/bin/Debug/, but that didn't help either:

System.TypeInitializationException: An exception was thrown by the type initializer for PoGo.NecroBot.CLI.Program ---> System.InvalidProgramException: Invalid IL code in System.Uri:.ctor (string): method body is empty.

Thanks!

**Comment by samuraitruong** [comment]
maybe wine doesn't understand IL merge, you need to distable IL merge (Fody) then it will copy all file your need for wine
