### ISSUE TITLE
Pokestop/Catch limits

### ISSUE THREAD

**Issue by SLASHLogin** [Necrobot-Private/NecroBot#683]
It happens for some version. I were thinking it will be fixed but it still happens. When my bot works I noticed that number of pokestops/catch limits changes every time. In my conf I set 1500 for pokestop and 1598 for catch. And like in attached photo it changes during work. 

![przechwytywanie](https://cloud.githubusercontent.com/assets/24846525/22472381/bd0827ae-e7d5-11e6-8392-5c6b1b863871.PNG)

**Comment by jjskuld** [comment]
This is the new randomization logic to try to thwart Niantic's ban flagging. 

Imagine that you always catch 1500 pokemon and stop every day for an entire month .  That pattern will show up pretty easily in niantic's data analysis.  Now every time the limits are checked, they are slightly randomized.

So one day you may stop at 1492, then the next time it checks it's at 1457, etc.

**Comment by jjskuld** [comment]
For reference https://github.com/Necrobot-Private/NecroBot/wiki/Why-are-my-Pokemon-Pokestop-Limits-Jumping-Around%3F
