### ISSUE TITLE
rocket api?

### ISSUE THREAD

**Issue by sammy150681** [Necrobot-Private/NecroBot#695]
[19:18:38] (INFO) Login tramite Google
[19:18:42] (INFO) PokemonGo.RocketAPI.Exceptions.InvalidResponseException: Error with API request type: DownloadRemoteConfigVersion
   in PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProtoPayload>d__0`1.MoveNext() in c:\projects\necrobot2\FeroxRev\Extensions\HttpClientExtensions.cs:riga 48
--- Fine traccia dello stack da posizione precedente dove è stata generata l'eccezione ---
   in System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   in PokemonGo.RocketAPI.Rpc.BaseRpc.<PostProtoPayload>d__11`1.MoveNext() in c:\projects\necrobot2\FeroxRev\Rpc\BaseRpc.cs:riga 131
--- Fine traccia dello stack da posizione precedente dove è stata generata l'eccezione ---
   in System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   in PokemonGo.RocketAPI.Rpc.BaseRpc.<PostProtoPayload>d__9`7.MoveNext() in c:\projects\necrobot2\FeroxRev\Rpc\BaseRpc.cs:riga 102
--- Fine traccia dello stack da posizione precedente dove è stata generata l'eccezione ---
   in System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   in PokemonGo.RocketAPI.Rpc.Download.<GetRemoteConfigVersion>d__6.MoveNext() in c:\projects\necrobot2\FeroxRev\Rpc\Download.cs:riga 64
--- Fine traccia dello stack da posizione precedente dove è stata generata l'eccezione ---
   in System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   in PokemonGo.RocketAPI.Rpc.Login.<DoLogin>d__9.MoveNext() in c:\projects\necrobot2\FeroxRev\Rpc\Login.cs:riga 152
--- Fine traccia dello stack da posizione precedente dove è stata generata l'eccezione ---
   in System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   in System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   in PoGo.NecroBot.Logic.State.LoginState.<Execute>d__2.MoveNext() in c:\projects\necrobot2\PoGo.NecroBot.Logic\State\LoginState.cs:riga 48
[19:19:02] (INFO) Login tramite Google

**Comment by jjskuld** [comment]
Not able to reproduce. Maybe a temporary network issue. Please reopen if you see it again
