### ISSUE TITLE
set attack?

### ISSUE THREAD

**Issue by sammy150681** [Necrobot-Private/NecroBot#698]
I can choose the strikers list?
thanks

**Comment by ziomber** [comment]
@sammy150681 I don't understand a question.

**Comment by andeomontenegro** [comment]
set pokemons for assault a gim

**Comment by sammy150681** [comment]
How can i set pokemons for assault?

**Comment by andeomontenegro** [comment]
im just fixin your question)
interesting too

**Comment by ziomber** [comment]
there a two ways, 
if UsePokemonToAttackOnlyByCp is true it will take 6 best by CP
if is false bot computes "factor" points and takes best mostly by skills (but cp also) to avoid using water agains grass etc.
you want to make a fixed team to attack any gym?

**Comment by sammy150681** [comment]
I want hiper work 😄

**Comment by samuraitruong** [comment]
He meant a defined fix team to attack gym.

**Comment by nhumber** [comment]
yes, probably the easiest way to go about gym battles to start off, defined teams of attackers, defenders, and trainers.

this would be a nice addititon

**Comment by andeomontenegro** [comment]
will be perfect add new filters for attack&defence team similar to any pokemon filter,
for example:

"attackPokemonFilter": {
    "Lapras": {
      "MinIV": 0,
      "MinLV": 0,
      "MinCP": 0,
      "Moves": [],
      "Operator": "or"
    },
}
:)

**Comment by samuraitruong** [comment]
I am still stuck with the best option to make a team, actually it not easy

**Comment by hardknoxni69a** [comment]
implemented
