### ISSUE TITLE
NecroBot2 v1.0.0.88 App crash

### ISSUE THREAD

**Issue by N1jada** [Necrobot-Private/NecroBot#700]
### Expected Behavior:

Application opens

### Actual Behavior:

Application crashes

### Your config.json:

None - clean install - config not yet created

After upgrading from 1.0.085 to 1.0.0.88 and with a clean install of v1.0.0.88

![nb88](https://cloud.githubusercontent.com/assets/25505063/22548882/8a52ad4a-e940-11e6-8c4e-ea4d303f9d71.JPG)

**Comment by andeomontenegro** [comment]
same shit

**Comment by bulubebek** [comment]
delete Necrobot2.exe.config file if its exist. ;)

**Comment by N1jada** [comment]
Thanks @bulubebek that worked
