### ISSUE TITLE
Updating to version 1.0.88 will not work

### ISSUE THREAD

**Issue by dillan88** [Necrobot-Private/NecroBot#702]
When I automatically update the latest version,
"Can not print out-of-print status string because Exception.Tostring () failed"
Then there ~ forced to stop the operation, and then to close the program,
This situation can not be resolved, so I continue to use BOT.

**Comment by RicoEdg** [comment]
I got the same problem but I replace NecroBot2.exe.config with the old one, now its working.

**Comment by andeomontenegro** [comment]
delete Necrobot2.exe.config file if its exist.

**Comment by dillan88** [comment]
Thank you for your instructions, has been successfully resolved.

**Comment by jjskuld** [comment]
Yes, sorry about this file which is causing issues. We'll try to fix it asap.
