### ISSUE TITLE
Snipe

### ISSUE THREAD

**Issue by RicoEdg** [Necrobot-Private/NecroBot#703]
Unable to snipe, Error message saying
(ERROR)  (Pokezz.com)  Connection  error
(ERROR)  (Pokesnipe.com)  One or more errors Occurred
(ERROR)  Error loading data from pokesnipers

**Comment by andeomontenegro** [comment]
to enable autosnipe:

"DataSharingConfig": {
    "EnableSyncData": true,
    "AutoSnipe": **true**,
    "DataServiceIdentification": "",
    "SnipeDataAccessKey": "",
    "DataRecieverURL": "ws://necrosocket.herokuapp.com/socket.io/?EIO=3&transport=websocket"
  },

**Comment by RicoEdg** [comment]
That's what I have but still not working, it stopped working last night

**Comment by andeomontenegro** [comment]
simple download clean new version and add your config

**Comment by RicoEdg** [comment]
What if I told you that seems like a pain and I was trying to avoid that. 👍

**Comment by andeomontenegro** [comment]
sniping 100iv but catch is another iv

whats a problem?

[13:33:59] (SNIPER) (InternalSnipe) Sniping a Snorlax with 100 IV at 24.0807708087275,120.644212326534...
[13:34:22] (PKMN) (CatchSuccess) | (Normal) Snorlax Lvl: 18 CP: (1684/3355) IV: 73.00% | Chance: 17.95% | 9158695.99m dist | with a GreatBall (8 left). | 210 EXP earned | Candies: 143 | lat: 24.080771 long: 120.644212 | Move1: ZenHeadbuttFast Move2: HyperBeam | Rarity :Rare

**Comment by samuraitruong** [comment]
some crown data source wasn't correct, if you want you can set it to VerifyOnly then it will never catch pokemon which not been confirmed

**Comment by samuraitruong** [comment]
your IP maybe automatically block by server it cause autosnipe not working, you need go to #ipblacklist to unblock it.
