### ISSUE TITLE
Pokemon Evolution Count Bug

### ISSUE THREAD

**Issue by hardknoxni69a** [Necrobot-Private/NecroBot#705]
Bot reads incorrect amount of available evolutions and varies geatly one moment i have 170 evolutions then the next it says 187 while only catching 1 pokemon then back to 173 it is all over place

**Comment by jjskuld** [comment]
Randomness will now be configurable, so if you don't want it to jump around you can set the new PlayerConfig -> RandomizeSettingsByPercent to 0.

**Comment by jjskuld** [comment]
New setting is now in NecroBot2 v1.0.0.89.  it still randomizes every time it is read, to change it to load only once will  take a little bit longer to fix.

**Comment by hardknoxni69a** [comment]
@jjskuld i am referring to the bot saying we have 10 evolutions available when there is really close to 50

**Comment by ziomber** [comment]
check you have all pokemons to envolve in list PokemonsToEvolve. bot counts only from this list

**Comment by jjskuld** [comment]
@hardknoxni69a Ok, i see that the evolution fix that we discussed is not correct. I'm working on a fix.

**Comment by hardknoxni69a** [comment]
thank you jj waiting for test and merge

**Comment by jjskuld** [comment]
Sorry had to redo the pull request due to some weird Github merge issues.

**Comment by hardknoxni69a** [comment]
theres a bug here bot reads over 200 evos when i only had like 75

**Comment by jjskuld** [comment]
Related to #457

**Comment by jjskuld** [comment]
Related to #379
