### ISSUE TITLE
gui order the bot to move to is not working properly

### ISSUE THREAD

**Issue by ziomber** [Necrobot-Private/NecroBot#707]
### Actual Behavior:
when you click on pokestop or gym and then click on "order the bot to move to"  location has two times latitude except of latitude, longitude

**Comment by macinmn** [comment]
would be great if you can fix this, as it's been an issue for some time.  (only impacts objects, stops and gyms, not free pin place target)  right now must close and restart bot to remedy if you forget you should not do this

**Comment by hardknoxni69a** [comment]
has been fixed let us know if u have issues with latest version GUI
