### ISSUE TITLE
 () Exception caught, writing LogBuffer. 

### ISSUE THREAD

**Issue by HeJerry** [Necrobot-Private/NecroBot#710]
[09:08:37] () Exception caught, writing LogBuffer.

 由于 Exception.ToString() 失败，因此无法打印异常字符串。

Version:
Windows Version: windows 10

**Comment by pluspsh** [comment]
i have a same issue.
my info : window 7 pro / 
exe_path : d:\poketgo\NecroBot2.exe

**Comment by samuraitruong** [comment]
it doesn't help with this info, if you still have issue, please post more info to troubleshooting
