### ISSUE TITLE
[feature request] Time, date and location sort in native GUI

### ISSUE THREAD

**Issue by portabili** [Necrobot-Private/NecroBot#712]
### Expected Behavior:
Pokemon sorting by time/date and/or location of catch in native GUI.

### Actual Behavior:
No time, date or location sort.

### Your config.json:
```
```

### (OPTIONAL) Your Log:
```
```

### Other Information
(Attach zip files if needed.)

Version:
Windows Version:
What is affected (catch, transfer, favorite, GPX, evolve, recycle, snipe, human walk snipe, pokestops, powerup/levelup, other):

**Comment by samuraitruong** [comment]
you mean in inventory list?

**Comment by samuraitruong** [comment]
implemented in #718

**Comment by portabili** [comment]
yes, I meant in inventory. Seems it has been implemented. Thanks

**Comment by portabili** [comment]
Hi,
Catching date is well implemented, but it would be very nice if you could include catch location too.
