### ISSUE TITLE
Allow User To Set AutoSnipe Batching! Currently 10 In A Row Is Asking For A Ban?

### ISSUE THREAD

**Issue by hardknoxni69a** [Necrobot-Private/NecroBot#719]
Currently The Bot Snipes 10 Random Pokemon From All Over The World In A Row It Would Be Much Safer If We Could Create A Setting To Allow The User To Make It Only Snipe 1 At A Time Or Whatever The User Chooses Necro Is The Most Configurable So Let The User Choose How Many They Want To Snipe In A Row Im Sure Most People Will Choose 1 So It Will Snipe 1 Then Continue Local Till There Delay Is Up Then Snipe 1 More Or 5 Or Whatever They Choose This Will Be Much Safer 
The File Holding These Values Is Here:
NecroBot\PoGo.NecroBot.Logic\Tasks\MSniperServeTasks.cs
The Code That Needs A Switch Is Here I Have Edited Mine Manually To 1 But This Was 10 Originally Line 651
 var batch = autoSnipePokemons.Take(1);
//mSniperLocation2.AddRange(autoSnipePokemons.Take(1));

Could Be Like 
 var batch = autoSnipePokemons.Take(_session.LogicSettings.SnipeInARow);
//mSniperLocation2.AddRange(autoSnipePokemons.Take(_session.LogicSettings.SnipeInARow));

I Dont Know Coding Very Well I Will Try To Add This Setting But Honestly Still Learning And The Big Boys Could Tackle This Quickly

**Comment by samuraitruong** [comment]
#718
