### ISSUE TITLE
Crashing Messsage

### ISSUE THREAD

**Issue by kilado94** [Necrobot-Private/NecroBot#726]
My necro is crashing what i need to do?
![screenshot_2](https://cloud.githubusercontent.com/assets/21318770/22618689/33ebbfe0-eadb-11e6-8d62-bd645a297c1e.png)

**Comment by hardknoxni69a** [comment]
please attach english errors

**Comment by hardknoxni69a** [comment]
and please include version info

**Comment by kilado94** [comment]
what u mean?

**Comment by hardknoxni69a** [comment]
what version of necro are you using and please attach errors in english

**Comment by kilado94** [comment]
last one

**Comment by samuraitruong** [comment]
delete *.config in necrobot folder
