### ISSUE TITLE
Bot Working Extremely Slow

### ISSUE THREAD

**Issue by hardknoxni69a** [Necrobot-Private/NecroBot#727]
Bot Is Taking 45 Seconds To Reach A Pokestop That Is 2 Seconds Away Even With Hashing Check It Shouldnt Take This Long And Delay Is Currently Set At Only 1 Second

**Comment by andeomontenegro** [comment]
"DisableHumanWalking": true,

**Comment by bulubebek** [comment]
I also noticed this, but it seems caused by the hashing processes. Hashing server is really unstable - in my case,  it giving really slow http/https responses for hashing process. 

disablehumanwalking = teleporting to the next pokestops. not recommended!

**Comment by jjskuld** [comment]
Just to correct a misunderstanding about DisableHumanWalking, it doesn't teleport you to the next poke stop.  It still walks you to the stop using the speed that you have configured.  However it will just move in a straight line.

This is how Pokefarmer currently moves and there is no evidence that disabling human walking will lead to a ban.

**Comment by bulubebek** [comment]
@jjskuld thank you for your correction. 😃

**Comment by jjskuld** [comment]
Please re-open if you see this is still an issue.
