### ISSUE TITLE
Hash API server might down

### ISSUE THREAD

**Issue by grigoriystavr** [Necrobot-Private/NecroBot#728]
NecroBot gives an error message: Pokefamer Hash API server might down. 
Please help to solve the problem.

**Comment by hardknoxni69a** [comment]
unfortunately the PF Hash server is not in our hands please refer to your email from Hashing service for contact info sorry bud

**Comment by bulubebek** [comment]
AFAIK, there is only single hashing server that is managed and owned by PF. too much API subscribers will definitely overkill it.

**Comment by hardknoxni69a** [comment]
yes unfortunately i think they are greedy with the money they charge us then dont upgrade the servers to keep up with the demand it is sad i miss the good old days when it was free and fast
