### ISSUE TITLE
Crash on clicking new settings button in WIN version

### ISSUE THREAD

**Issue by nhumber** [Necrobot-Private/NecroBot#729]
Crash on clicking new settings button in WIN version.

crashes on updated instance .89 to .90

crash on clean install of .90

**Comment by hardknoxni69a** [comment]
thank you for your feedback we will take care of this asap please refer to your config/config.json for same settings just have to do it manually for now

**Comment by nhumber** [comment]
I figured it must have been a known issue but thought creating an issue here was a good idea just incase. Thanks for the work you guys are doing.. its great.

**Comment by samuraitruong** [comment]
FIXED /
