### ISSUE TITLE
Request) Have KeepMaxDuplicatePokemon As An Option

### ISSUE THREAD

**Issue by hardknoxni69a** [Necrobot-Private/NecroBot#730]
When It Comes To Botting And Leaving It Running All The Time You May End Up With Multiple Exact Duplicates That Meet Your Required Settings But Eventually Hvaings 20 Of 1 Pokemon All 100IV Is A Little Ridiculous So I Like To Recommend Having A KeepMaxDuplicatePokemon As Well As Our Current KeepMinDuplicate Pokemon So Once The Users Reaches Say 5 Of The Same Pokemon It Will Keep The Top 5 And Transfer Rest

**Comment by samuraitruong** [comment]
DO YOU NEED IT, JUST SET YOUR KEEP MIN  & MAXcp = 5000 FOR EVERY POKEMON, THEN USING AND LOGIC, SOLVE PROBLEM WITH EXISTING CONFIG AND EVEN MORE EFFICIENT

ANOTHER WAY IF YOU SET

MINIV = 101
MINCP = 5000
LOGIC = AND
KEEP MIN = 5 => THAT WILL ALWAYS KEEP MAX 5 POKEMON . IS THAT KEEP MAX YOU WANT, SO EASY DONT NEED TO ADD NEW CONFIG FOR THAT

**Comment by hardknoxni69a** [comment]
Im sorry maybe I didn't explain it the right way in the wild the best you can catch is lvl 30 pokemon with 100iv after leaving bot running all day every day your going to end up with 100 100iv lvl30 dratini or whoever I am saying give us an option so once u reach the say 5 lvl 30 100iv of a pokemon that it's OK to start transferring them

**Comment by samuraitruong** [comment]
so that what i told above , the config above will do that for u. try to setup it in your config and you will se it only keep 5 100%

**Comment by hardknoxni69a** [comment]
what you say does work to keep a max of pokemon but then it bypasses transfer filters it would be nice to have a settings so it still respects the transfer filters then allows up to only 3 of your requirements so i have setting to only keep lvl 25 100iv and above but it will keep 100 of them if i apply your setting it will allow lvl 24 90iv the keepmax will work with the transfer filters instead of bypassing them with that other way
