### ISSUE TITLE
AutoSnipe Bypasses CatchPokemon:False

### ISSUE THREAD

**Issue by hardknoxni69a** [Necrobot-Private/NecroBot#731]
As Title Says If AutoSnipe Is Enabled It Will Bypass The Default CatchPokemon Filter Selecting False Should Stop All Poke Farming

**Comment by samuraitruong** [comment]
if you not catch pokemon arround, it will caused lot of softban. if you wait for next version, autosnipe with work wihtout catch Pokmeon set to true

**Comment by samuraitruong** [comment]
fixed in https://github.com/Necrobot-Private/NecroBot/pull/725
