### ISSUE TITLE
Error -  BAD REQUEST 

### ISSUE THREAD

**Issue by Finfinder** [Necrobot-Private/NecroBot#733]
During the game just 3 times I received the following error.
On error, an attempt to re-log-in and the situation repeats itself.
I'm using version v1.0.0.90.

[21:46:30] (BŁĄD) Bad Request - If you see this message please copy error log & screenshot send back to dev asap.
[21:46:30] (BŁĄD) BAD REQUEST 
{"StatusCode":2,"RequestId":1458777931,"Requests":[{"RequestType":103,"RequestMessage":[9,9,159,238,146,222,231,195,235,16,1,25,51,51,51,51,51,51,255,63,34,11,52,55,49,97,51,53,54,101,101,102,100,40,1,57,0,0,0,0,0,0,240,63]},{"RequestType":600,"RequestMessage":[]},{"RequestType":126,"RequestMessage":[]},{"RequestType":4,"RequestMessage":[8,209,182,131,215,160,43]},{"RequestType":129,"RequestMessage":[]},{"RequestType":5,"RequestMessage":[10,40,49,100,101,51,48,50,100,98,97,50,101,53,52,50,98,56,100,98,56,50,53,48,52,53,53,102,97,51,101,51,52,48,100,55,56,99,56,54,102,51]},{"RequestType":153,"RequestMessage":[]}],"PlatformRequests":[{"Type":8,"RequestMessage":[10,40,57,48,102,54,97,55,48,52,53,48,53,98,99,99,97,99,55,51,99,101,99,57,57,98,48,55,55,57,52,57,57,51,101,54,102,100,53,97,49,50]},{"Type":6,"RequestMessage":[10,133,4,10,224,156,134,90,146,30,207,116,217,89,208,205,206,25,183,165,208,60,123,132,172,237,191,41,51,199,220,107,240,226,39,67,93,236,196,107,173,90,207,114,253,187,204,101,232,223,235,179,48,233,28,113,98,0,29,55,227,57,135,246,195,63,82,112,204,212,163,83,181,249,35,60,194,50,64,9,207,89,160,222,161,23,97,52,165,122,91,38,96,5,200,17,114,225,94,149,16,96,85,11,94,122,59,72,64,25,92,177,154,125,34,75,181,214,37,240,23,191,164,4,136,228,59,241,140,100,203,36,57,76,50,35,38,228,81,138,98,100,26,126,28,102,7,25,33,128,185,30,74,237,80,84,197,81,64,206,242,6,114,221,100,112,52,94,176,155,194,221,190,172,158,231,65,139,109,254,63,106,78,29,217,132,69,156,227,135,46,44,82,25,120,73,238,201,180,123,145,209,85,137,243,211,49,69,57,146,150,225,134,204,188,232,136,112,38,5,34,94,177,182,180,182,126,187,198,171,178,139,66,31,54,73,197,29,223,5,191,146,131,143,194,197,144,248,198,191,93,0,209,77,131,144,209,5,17,186,174,138,66,244,169,123,1,145,62,160,159,160,197,242,20,111,4,59,127,129,138,24,226,185,20,4,231,107,146,205,126,207,177,219,236,204,21,93,18,239,212,243,122,190,187,93,42,122,148,134,220,23,249,188,89,154,240,212,64,125,247,52,247,62,5,167,6,162,184,212,97,99,31,119,94,48,45,235,56,110,101,13,188,235,184,93,56,19,85,168,92,85,131,52,226,246,132,183,249,150,215,50,211,7,140,217,141,14,243,219,101,52,122,145,211,83,131,57,111,10,186,13,128,106,47,149,76,110,169,137,174,214,142,104,68,137,63,16,122,50,90,192,100,102,141,161,190,234,120,168,38,78,125,211,31,110,13,21,238,83,111,190,60,88,14,188,106,24,159,217,78,25,172,116,25,96,119,194,98,92,159,59,61,54,95,31,27,3,239,77,71,179,172,61,29,143,26,116,116,96,91,222,195,145,199,158,59,22,124,255,139,229,83,126,142,31,243,78,13,109,216,204,2,55,252,208,234,243,239,86,23,1,171,0,78,103,190,101,189,109,249,122,190,9,52,208,169,153,96,70,62,252,188,171,212,26,74,171,102,241]}],"Latitude":51.745934268838383,"Longitude":19.398364859713762,"Accuracy":10.0,"AuthInfo":null,"AuthTicket":{"Start":[27,186,1,239,93,159,44,166,204,142,135,212,150,92,107,101,224,190,126,129,72,66,42,219,113,244,23,45,69,113,222,2,27,113,50,99,177,154,122,33,232,150,166,136,69,76,218,181,71,163,123,121,72,3,43,215,79,219,220,110,222,15,149,172],"ExpireTimestampMs":1486242980720,"End":[139,196,254,173,166,145,213,189,21,196,164,97,250,52,181,109]},"MsSinceLastLocationfix":12013}
[21:46:30] (BŁĄD)    w PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PerformRemoteProcedureCall>d__2`1.MoveNext() w C:\NecroBot\Source\FeroxRev\Extensions\HttpClientExtensions.cs:wiersz 117
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   w PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PerformThrottledRemoteProcedureCall>d__8`1.MoveNext() w C:\NecroBot\Source\FeroxRev\Extensions\HttpClientExtensions.cs:wiersz 162
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   w PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProtoPayload>d__0`1.MoveNext() w C:\NecroBot\Source\FeroxRev\Extensions\HttpClientExtensions.cs:wiersz 45
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   w PokemonGo.RocketAPI.Rpc.BaseRpc.<PostProtoPayload>d__11`1.MoveNext() w C:\NecroBot\Source\FeroxRev\Rpc\BaseRpc.cs:wiersz 130
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   w PokemonGo.RocketAPI.Rpc.BaseRpc.<PostProtoPayload>d__10`8.MoveNext() w C:\NecroBot\Source\FeroxRev\Rpc\BaseRpc.cs:wiersz 119
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   w PokemonGo.RocketAPI.Rpc.Encounter.<CatchPokemon>d__3.MoveNext() w C:\NecroBot\Source\FeroxRev\Rpc\Encounter.cs:wiersz 111
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   w PoGo.NecroBot.Logic.Tasks.CatchPokemonTask.<Execute>d__4.MoveNext() w C:\NecroBot\Source\PoGo.NecroBot.Logic\Tasks\CatchPokemonTask.cs:wiersz 321
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   w PoGo.NecroBot.Logic.Tasks.CatchNearbyPokemonsTask.<Execute>d__0.MoveNext() w C:\NecroBot\Source\PoGo.NecroBot.Logic\Tasks\CatchNearbyPokemonsTask.cs:wiersz 125
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   w PoGo.NecroBot.Logic.Tasks.FarmPokestopsTask.<Execute>d__1.MoveNext() w C:\NecroBot\Source\PoGo.NecroBot.Logic\Tasks\FarmPokestopsTask.cs:wiersz 56
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   w PoGo.NecroBot.Logic.State.FarmState.<Execute>d__0.MoveNext() w C:\NecroBot\Source\PoGo.NecroBot.Logic\State\FarmState.cs:wiersz 51
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   w PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext() w C:\NecroBot\Source\PoGo.NecroBot.Logic\State\StateMachine.cs:wiersz 100
[21:46:30] (INFO) Logujesz się przy użyciu: Konta Ptc

**Comment by hardknoxni69a** [comment]
deleting your cache and accounts.db should resolve this as well as latest issue of course let us know if you need to reopen
