### ISSUE TITLE
autosnipe ignore custom filters

### ISSUE THREAD

**Issue by andeomontenegro** [Necrobot-Private/NecroBot#737]
after update few days ago

config:

   "MinIVForAutoSnipe": 101,
   "AutosnipeVerifiedOnly": true,

///

"SnipePokemonFilter": {
    "Blastoise": {
      "SnipeIV": 95,
      "Moves": [],
      "Operator": "and",
      "VerifiedOnly": true,
      "Priority": 5,
      "AutoSnipeCandy": 3
    },

...

log:

[14:13:56] (SNIPER) (InternalSnipe) Sniping a Blastoise with 53.33 IV at 40.8011610221962,-73.9155446997568...

and snipes other garbage :(

**Comment by andeomontenegro** [comment]
trying to use clean config from wiki - same problem

**Comment by hardknoxni69a** [comment]
you need to set the pokemon you want it to snipe in the pokemon to snipe filter

  "PokemonToSnipe": {
    "Locations": [],
    "Pokemon": [
      "lapras",
      "dragonite",
      "snorlax",
      "dratini",
      "dragonair",
      "abra",
      "machop",
      "charmander",
      "bulbasaur",
      "squirtle",
      "pidgey"

then you can also put more details or add more pokemon in the snipepokemonfilter

      "machop",
      "charmander",
      "bulbasaur",
      "squirtle",
      "pidgey"

then you can also put what more detaails in the snipe pokemon filterthere is 2

**Comment by jjskuld** [comment]
@hardknoxni69a unless I'm mistaken it doesn't look at PokemonToSnipe.

See #400. I still think we should fix this to work like we expect it to, otherwise we should get rid of SnipePokemonFilter

**Comment by samuraitruong** [comment]
"AutoSnipeCandy": 3 explain why it snipe that 53% IV

I use snipe filters and snipe about 20k pokemon a day. it definitely works as expected.  many snipe options and you have to learn how to control your bot

@jjskuld  the think need get rid is PokemonToSnipe (which is old and not fit with new snipe config)
