### ISSUE TITLE
[Feature Request] Selecting buddy.

### ISSUE THREAD

**Issue by SLASHLogin** [Necrobot-Private/NecroBot#738]
I suggest add changing buddies option in GUI and automatic changes. ex. I have 2 dittos and to get candy I have to walk 37km with first one and with second only 5 km, so bot will change buddy to this second one pokemon. And maybe in config option to choose which pokemon ex "PokemonBuddy": "Ditto".

**Comment by hardknoxni69a** [comment]
right clicking a pokemon will allow changing of buddy all buddy candies go to the eachother so you dont have to switch pokemon

**Comment by SLASHLogin** [comment]
oh really I don't ever wondering about right-click
Thanks but auto changing is good idea

**Comment by SLASHLogin** [comment]
Closed

**Comment by SLASHLogin** [comment]
close

**Comment by portabili** [comment]
I dont get it. How did you have to walk up to 37km to get a candy for Ditto ?

**Comment by SLASHLogin** [comment]
Hmh I analysed that and for ditto only 3km per candy but gui showes "24/49.35" what I understand like 24 kilometeres already walked but this 49.35 is unclear. I were thinking this 49.35 is just new point to get candy. Sorry for my mistake.

**Comment by jjskuld** [comment]
This is now implemented
