### ISSUE TITLE
Gym Battle Message

### ISSUE THREAD

**Issue by SLASHLogin** [Necrobot-Private/NecroBot#739]
During gym battle massages uptading in console after some time starting to going back when enemy lost HP and deletes earlier messages. 
btw Every time, every battle ends "Our attack timed out..." and never succesful battle.

**Comment by ziomber** [comment]
This is quite normal when attacker is to weak to do his job in 90s. I've tunned it a bit, maybe it works better now, maybe you just need to snipe better pokemons...

**Comment by redking974** [comment]
Yes I have a similar issue. My Pokemon doesn't have enough time to finish the battle. I think that IRL I could finish it, but I need to made more advanced tests (not using Ultrabeam for example) to tell that delays are longer than in official app.
But thanks to @ziomber and all Necrobot team the gym feature begins to be powerful :)

**Comment by hardknoxni69a** [comment]
better pokemon better results lol keep it upo ziomber battling getting better and better
