### ISSUE TITLE
Request) Search bar/tab in sniper section

### ISSUE THREAD

**Issue by hardknoxni69a** [Necrobot-Private/NecroBot#744]
a new tab in snipe section so say a user could choose a pokemon and will all the snipe results for that specific pokemon so someone want to only snipe pikachu candies they punch in pikachu and all the results will be getting loaded into that tab once they farmed enough candy they can choose another pokemon and that tab will be loaded with all those coordinates that way the user doesnt have to change config file every time they want to snipe candy for a specific pokemon

**Comment by jjskuld** [comment]
Search in pokemon inventory would also be handy.

**Comment by samuraitruong** [comment]
implemented in v94 then reverted, I need to make a filter form for this

**Comment by samuraitruong** [comment]
move to WIP

**Comment by samuraitruong** [comment]
fixed #864
