### ISSUE TITLE
(bug) GUI allows transferring of favorites

### ISSUE THREAD

**Issue by hardknoxni69a** [Necrobot-Private/NecroBot#747]
GUI will bypass favorite setting and allow transfer

**Comment by jjskuld** [comment]
Actually it should not be doing this. The transfer button should be greyed out when it is favorited.  Do you have a log for this?

**Comment by hardknoxni69a** [comment]
the log shows nothing specific the button is greyed out but say we do the select all it will bypass favorite and transfer anyone it doesnt even show it unfavoriting in the log

**Comment by jjskuld** [comment]
This will be fixed in the next release.
