### ISSUE TITLE
[feature request] location info and sorting in native GUI inventory

### ISSUE THREAD

**Issue by portabili** [Necrobot-Private/NecroBot#755]
### Expected Behavior:
beside of catch date in inventory, it would be nice having catch location of pokemon in GUI inventory.
Date display has been implemented in #712 

### Your config.json:
```
```

### (OPTIONAL) Your Log:
```
```

### Other Information
(Attach zip files if needed.)

Version:
Windows Version:
What is affected (catch, transfer, favorite, GPX, evolve, recycle, snipe, human walk snipe, pokestops, powerup/levelup, other):

**Comment by samuraitruong** [comment]
unfortunately, Niantic only give us the spawnpoinid which is random string in their system, we don't have info about location. I will look in data if they still give us Lat, Lng, but seem we did have those info.

**Comment by jjskuld** [comment]
We have the location information in the form of the captured_cell_id, which can be converted back to latitude and longitude and then reverse geocoded to a user friendly location.
