### ISSUE TITLE
(suggestion) random trainer name

### ISSUE THREAD

**Issue by petpetpetvm** [Necrobot-Private/NecroBot#76]
:) the topic say everything already lol

**Comment by CreativiTimothy** [comment]
Do you run like 60 accounts or something at the same time? You need to buy private proxies for that lol

**Comment by vfuyong** [comment]
Are you against FBI or something?

**Comment by petpetpetvm** [comment]
lol :)) there are thousands things different than proxies lol

**Comment by CreativiTimothy** [comment]
vpn, proxies, or what? What do you use?

**Comment by petpetpetvm** [comment]
other :)
