### ISSUE TITLE
API key is incorrect or expired (Pokefamer message: Unauthorized)

### ISSUE THREAD

**Issue by kkrukmukk** [Necrobot-Private/NecroBot#767]
Hi

I just bought a API key from pokefarmer and I get this message: Your API key is incorrect or expired, please check auth.json (Pokefamer message: Unauthorized). I use the same key with success on pokefamer.

Someone have an idea ?

**Comment by macinmn** [comment]
did you buy a pokehash key, or pokefarmer?  my understanding is they do not work on both.

**Comment by macinmn** [comment]
when you visit https://na.buddyauth.com/User/Keys   type should be Pokehash

**Comment by kkrukmukk** [comment]
Thank you so much macinmn... I bought a pokefamer key. I will need a Pokehash ;-0
