### ISSUE TITLE
access token expired 

### ISSUE THREAD

**Issue by gatesjr** [Necrobot-Private/NecroBot#770]
every time i run bot now it will try traveling to pokestop then access token expired and it just keeps looping over and over will not get to pokestop, do we know why this is, everything was working fine now i have this issue

**Comment by bulubebek** [comment]
this is a bit similar to issue #765

**Comment by samuraitruong** [comment]
in this case, please delete cache folder, we will try to fix it asap

**Comment by gatesjr** [comment]
yes i it worked for about a few pokestop and then back to doing the same thing, it seems to only be a big issues when just walking spinning stops if you are catch and spinning works fine and only every 10-20 minutes it need to refresh access token

**Comment by jjskuld** [comment]
Fixed with v1.0.0.98
