### ISSUE TITLE
Snipe below iv 80

### ISSUE THREAD

**Issue by pizzafight** [Necrobot-Private/NecroBot#771]
Snipe below iv 80 Why?
Sorry I'm not good in English.

    "Dratini": {
      "SnipeIV": 80,
      "Moves": [ ],
      "Operator": "and",
      "VerifiedOnly": true,
      "Priority": 5,
      "AutoSnipeCandy": 99999

**Comment by samuraitruong** [comment]
"AutoSnipeCandy": 99999
