### ISSUE TITLE
Hope you can help after update the bot now crashes with this exception report have checked config file on Json Lint and it passes ok please help [07:53:31] () config.json [Line: 144, Position: 20]: PokemonConfig Required properties are missing from object: DefaultBuddyPokemon.

### ISSUE THREAD

**Issue by cosmickcan** [Necrobot-Private/NecroBot#772]
## Stop! Before you create this issue (you can delete this section when opening the issue):
1. Have you searched to see if there are other Open/Closed issues for the same issue? If so, comment on that issue instead.
2. Have you validated that your config/auth.json and config/config.json is valid JSON? Use http://jsonlint.com/ to check.
3. If your question is referring to how to set up or use the bot, please join our discord instead of posting an issue: https://discord.gg/7FWyWVp 
4. Always confirm that your issue is reproducible, with the config you provide below.

### Your config.json:
```
replace this text with the contents of your config.json

```

### (OPTIONAL) Your Log:
```
replace this text with only the "relative" portion of your log. (Remove unnessary lines)

```

### Other Information
(Attach zip files if needed.)

Version:
Windows Version:
What is affected (catch, transfer, favorite, GPX, evolve, recycle, snipe, human walk snipe, pokestops, powerup/levelup, other):

**Comment by bulubebek** [comment]
Inside `PokemonConfig` section, add this line:

`"DefaultBuddyPokemon": "Flareon"`

Change "Flareon" to your buddy pokemon. Please close this ticket if your problem solved.

**Comment by samuraitruong** [comment]
need to somehow fix the code too. I don't know why config is not generated

**Comment by samuraitruong** [comment]
https://github.com/Necrobot-Private/NecroBot/pull/773

**Comment by cosmickcan** [comment]
Hi I did what you suggested but it did not solve my problem, someone has now closed the thread any idea what I should do many thanks for your help

________________________________

**Comment by bulubebek** [comment]
copy and paste your config.json to pastebin.com then put its link here so we can check it.

**Comment by cosmickcan** [comment]
Hi thanks for your help hope I have done this right

http://pastebin.com/BjNs31rs

[http://pastebin.com/i/facebook.png]<http://pastebin.com/BjNs31rs>

cosmickcan - Pastebin.com<http://pastebin.com/BjNs31rs>
pastebin.com




________________________________

**Comment by cosmickcan** [comment]
hope you get this


________________________________

**Comment by bulubebek** [comment]
My recommendation is try to download latest version of necrobot private, run it and generate new configuration files, then finally makes adjustments to the new configs to suite your needs. 

Latest version using `"SchemaVersion": 11`, yours still using `"SchemaVersion": 6` - I think its kinda outdated. And you might change `"DefaultBuddyPokemon": "eevee"`  to more powerful poke buddy. 😃

**Comment by cosmickcan** [comment]
Thanks very much for all your help it is greatly appreciated [😊]

________________________________
