### ISSUE TITLE
Not sniping

### ISSUE THREAD

**Issue by gatesjr** [Necrobot-Private/NecroBot#779]
my config for sniping is configured below no matter me saving and shutting down bot will not snipe anything at all

 "SnipeConfig": {
    "UseSnipeLocationServer": false,
    "SnipeLocationServer": "localhost",
    "SnipeLocationServerPort": 16969,
    "GetSniperInfoFromPokezz": false,
    "GetOnlyVerifiedSniperInfoFromPokezz": false,
    "GetSniperInfoFromPokeSnipers": false,
    "GetSniperInfoFromPokeWatchers": false,
    "GetSniperInfoFromSkiplagged": false,
    "MinPokeballsToSnipe": 10,
    "MinPokeballsWhileSnipe": 0,
    "MinDelayBetweenSnipes": 60000,
    "SnipingScanOffset": 0.005,
    "SnipeAtPokestops": true,
    "SnipeIgnoreUnknownIv": false,
    "UseTransferIvForSnipe": false,
    "SnipePokemonNotInPokedex": false,
    "UseSnipeLimit": true,
    "SnipeRestSeconds": 600,
    "SnipeCountLimit": 39,
    "ActivateMSniper": false,
    "MinIVForAutoSnipe": 97,
    "AutosnipeVerifiedOnly": false,
    "DefaultAutoSnipeCandy": 0,
    "SnipePauseOnOutOfBallTime": 5,
    "AutoSnipeMaxDistance": 0.0,
    "AutoSnipeBatchSize": 10

 "DataSharingConfig": {
    "EnableSyncData": true,
    "AutoSnipe": true,
    "DataServiceIdentification": "",
    "SnipeDataAccessKey": "",
    "EnableFailoverDataServers": true,
    "FailoverDataServers": "ws://s1.mypogosnipers.com/socket.io/?EIO=3&transport=websocket;ws://s2.mypogosnipers.com/socket.io/?EIO=3&transport=websocket",
    "DataRecieverURL": "ws://necrosocket.herokuapp.com/socket.io/?EIO=3&transport=websocket"

**Comment by hardknoxni69a** [comment]
please check the sites to make sure they are up unforunately people keep spamming the site trying to make it crash and it causes no results till server is reset we do our best but because were the best there are haters lol
