### ISSUE TITLE
rename bug

### ISSUE THREAD

**Issue by pizzafight** [Necrobot-Private/NecroBot#782]
The language is changed to Japanese but the name after change is English + IV

**Comment by bulubebek** [comment]
Changing language is intended as UI translation only. Its not affecting core processes, including pokemons renaming. So, its definitely not a bug. :)

**Comment by pizzafight** [comment]
It was applied in version one month ago

**Comment by samuraitruong** [comment]
nothing change, code still using the language translation, could ou please check if your jp has properly translation

**Comment by pizzafight** [comment]
I solved it, thank you.
