### ISSUE TITLE
(Request Enhancement) PokeCatch Limit Will Temporaily Disable Human Sniping

### ISSUE THREAD

**Issue by hardknoxni69a** [Necrobot-Private/NecroBot#79]
Hello Devs.
Currently when the PokeCatch limit is reached the bot will continue to go off course Human Sniping for pokemon that are not able to be caught due to the limit being in place. With this happening the bot is slowing way down and not focusing on maximizing the xp by just focusing on the available pokestops. I would like to see if you could implement the switch so once our CatchLimit is reached it temporarily disbales Human Sniping And Reenables Once Our Clock Has Been Reset. As Always THANK YOU SO MUCH!!

**Comment by CreativiTimothy** [comment]
Agree, but not just Human Sniping. It should disable all snipe servers (pokezz etc.) and human sniping temporarily once catchlimit is  reached and then re-enables after time reset yeah

**Comment by ntatoo** [comment]
Working On It

**Comment by hardknoxni69a** [comment]
Thank You So Much please reference this issue once commited so i can re build YOU GUYS ARE AMAZING

**Comment by samuraitruong** [comment]
what i suggest for this fix is change bot to IdleState, IdelState will return FarmState.

**Comment by samuraitruong** [comment]
set as very low priority since HMW sniper is dead :)
