### ISSUE TITLE
not catch snipe filter pokemon

### ISSUE THREAD

**Issue by pizzafight** [Necrobot-Private/NecroBot#797]
From today's morning only the snipe filter Pokemon not catch.
Is it because the configuration is old? Snipe URL is vip

I get this error when trying to catch the filter's Pokemon
[09:39:10] (SERVICE) pokemon despawned or wrong link foemat!
[17:11:31] (警告) Couldn't establish the connection to necro socket server
[17:11:36] (情報) Connecting to ws://

{
  "ConsoleConfig": {
    "TranslationLanguageCode": "ja-JP",
    "StartupWelcomeDelay": false,
    "AmountOfPokemonToDisplayOnStart": 2,
    "DetailedCountsBeforeRecycling": true
  },
  "UpdateConfig": {
    "SchemaVersion": 9,
    "CheckForUpdates": false,
    "AutoUpdate": false
  },
  "WebsocketsConfig": {
    "UseWebsocket": true,
    "WebSocketPort": 14251
  },
  "LocationConfig": {
    "DisableHumanWalking": false,
    "StartFromLastPosition": true,
    "DefaultLatitude": 35.6965388,
    "DefaultLongitude": 139.8048367,
    "WalkingSpeedInKilometerPerHour": 10.0,
    "UseWalkingSpeedVariant": true,
    "WalkingSpeedVariant": 1.2,
    "ShowVariantWalking": false,
    "RandomlyPauseAtStops": true,
    "MaxSpawnLocationOffset": 10,
    "MaxTravelDistanceInMeters": 500
  },
  "TelegramConfig": {
    "UseTelegramAPI": false,
    "TelegramAPIKey": null,
    "TelegramPassword": null
  },
  "GPXConfig": {
    "UseGpxPathing": false,
    "GpxFile": "GPXPath.GPX"
  },
  "SnipeConfig": {
    "UseSnipeLocationServer": false,
    "SnipeLocationServer": "localhost",
    "SnipeLocationServerPort": 16969,
    "GetSniperInfoFromPokezz": false,
    "GetOnlyVerifiedSniperInfoFromPokezz": true,
    "GetSniperInfoFromPokeSnipers": false,
    "GetSniperInfoFromPokeWatchers": false,
    "GetSniperInfoFromSkiplagged": false,
    "MinPokeballsToSnipe": 20,
    "MinPokeballsWhileSnipe": 0,
    "MinDelayBetweenSnipes": 60000,
    "SnipingScanOffset": 0.005,
    "SnipeAtPokestops": false,
    "SnipeIgnoreUnknownIv": false,
    "UseTransferIvForSnipe": false,
    "SnipePokemonNotInPokedex": true,
    "UseSnipeLimit": true,
    "SnipeRestSeconds": 600,
    "SnipeCountLimit": 39,
    "ActivateMSniper": true,
    "MinIVForAutoSnipe": 100,
    "AutosnipeVerifiedOnly": false,
    "DefaultAutoSnipeCandy": 0,
    "SnipePauseOnOutOfBallTime": 5,
    "AutoSnipeMaxDistance": 0.0
  },
  "HumanWalkSnipeConfig": {
    "Enable": false,
    "DisplayPokemonList": true,
    "MaxDistance": 300.0,
    "MaxEstimateTime": 180.0,
    "CatchEmAllMinBalls": 50,
    "TryCatchEmAll": true,
    "CatchPokemonWhileWalking": true,
    "SpinWhileWalking": true,
    "AlwaysWalkback": false,
    "SnipingScanOffset": 0.002,
    "WalkbackDistanceLimit": 100.0,
    "IncludeDefaultLocation": true,
    "UseSnipePokemonList": true,
    "MaxSpeedUpSpeed": 60.0,
    "AllowSpeedUp": true,
    "DelayTimeAtDestination": 10000,
    "UsePokeRadar": false,
    "UseSkiplagged": false,
    "UsePokecrew": false,
    "UsePokesnipers": false,
    "UsePokeZZ": false,
    "UsePokeWatcher": false,
    "UseFastPokemap": false,
    "UsePogoLocationFeeder": false,
    "AllowTransferWhileWalking": false
  },
  "DataSharingConfig": {
    "EnableSyncData": true,
    "AutoSnipe": true,
    "DataServiceIdentification": "",
    "SnipeDataAccessKey": "",
    "DataRecieverURL": ""
  },
  "PokeStopConfig": {
    "UsePokeStopLimit": true,
    "PokeStopLimit": 1500,
    "PokeStopLimitMinutes": 1200
  },
  "GymConfig": {
    "NotUsedSkills": [
      {
        "Key": "snorlax",
        "Value": "hyperBeam"
      },
      {
        "Key": "dragonite",
        "Value": "hyperBeam"
      },
      {
        "Key": "lapras",
        "Value": "blizzard"
      }
    ],
    "Enable": false,
    "PrioritizeGymOverPokestop": true,
    "MaxDistance": 1500.0,
    "DefaultTeam": "Red",
    "MaxCPToDeploy": 1000,
    "MaxLevelToDeploy": 16,
    "VisitTimeout": 60,
    "UseRandomPokemon": false,
    "NumberOfTopPokemonToBeExcluded": 10,
    "CollectCoinAfterDeployed": 1,
    "EnableAttackGym": false,
    "MaxGymLevelToAttack": 3,
    "MaxDefendersToAttack": 3,
    "HealDefendersBeforeApplyToGym": true,
    "DontAttackAfterCoinsLimitReached": true,
    "EnableGymTraining": true,
    "TrainGymWhenMissingMaxPoints": 1000,
    "MaxGymLvlToTrain": 4,
    "TrainAlreadyDefendedGym": true,
    "MinCpToUseInAttack": 1000,
    "ButNotLessThanDefenderPercent": 0.75,
    "UsePokemonToAttackOnlyByCp": true
  },
  "PokemonConfig": {
    "CatchPokemon": true,
    "DelayBetweenPokemonCatch": 5000,
    "UseCatchLimit": true,
    "CatchPokemonLimit": 700,
    "CatchPokemonLimitMinutes": 1200,
    "UseIncenseConstantly": true,
    "UseEggIncubators": true,
    "UseLimitedEggIncubators": true,
    "UseLuckyEggConstantly": false,
    "UseLuckyEggsMinPokemonAmount": 30,
    "UseLuckyEggsWhileEvolving": true,
    "UseBerriesMinCp": 1000,
    "UseBerriesMinIv": 90.0,
    "UseBerriesBelowCatchProbability": 0.2,
    "UseBerriesOperator": "or",
    "MaxBerriesToUsePerPokemon": 1,
    "TransferWeakPokemon": false,
    "TransferDuplicatePokemon": true,
    "TransferDuplicatePokemonOnCapture": true,
    "RenamePokemon": true,
    "RenameOnlyAboveIv": true,
    "RenameTemplate": "{Name}{IV}",
    "FavoriteMinIvPercentage": 80.0,
    "AutoFavoritePokemon": false,
    "MaxPokeballsPerPokemon": 20,
    "UseGreatBallAboveCp": 1000,
    "UseUltraBallAboveCp": 1250,
    "UseMasterBallAboveCp": 1500,
    "UseGreatBallAboveIv": 85.0,
    "UseUltraBallAboveIv": 95.0,
    "UseGreatBallBelowCatchProbability": 0.2,
    "UseUltraBallBelowCatchProbability": 0.1,
    "UseMasterBallBelowCatchProbability": 0.05,
    "AutomaticallyLevelUpPokemon": false,
    "OnlyUpgradeFavorites": true,
    "UseLevelUpList": true,
    "AmountOfTimesToUpgradeLoop": 5,
    "GetMinStarDustForLevelUp": 5000,
    "LevelUpByCPorIv": "iv",
    "UpgradePokemonCpMinimum": 1000.0,
    "UpgradePokemonIvMinimum": 95.0,
    "UpgradePokemonMinimumStatsOperator": "and",
    "EvolveAboveIvValue": 95.0,
    "EvolveAllPokemonAboveIv": false,
    "EvolveAllPokemonWithEnoughCandy": true,
    "EvolveKeptPokemonsAtStorageUsagePercentage": 20.0,
    "EvolveKeptPokemonIfBagHasOverThisManyPokemon": 10,
    "KeepPokemonsThatCanEvolve": false,
    "KeepMinCp": 5000,
    "KeepMinIvPercentage": 99.0,
    "KeepMinLvl": 6,
    "KeepMinOperator": "and",
    "UseKeepMinLvl": false,
    "PrioritizeIvOverCp": true,
    "KeepMinDuplicatePokemon": 0,
    "UsePokemonToNotCatchFilter": false,
    "UsePokemonSniperFilterOnly": true,
    "DumpPokemonStats": false,
    "DelayBetweenPokemonUpgrade": 5000,
    "OutOfBallCatchBlockTime": 5,
    "PokeballToKeepForSnipe": 50,
    "UseBulkTransferPokemon": true,
    "BulkTransferStogareBuffer": 10,
    "BulkTransferSize": 100,
    "UseBallOperator": "or",
    "FavoriteMinCp": 0.0
  },
  "RecycleConfig": {
    "VerboseRecycling": true,
    "RecycleInventoryAtUsagePercentage": 90.0,
    "RandomizeRecycle": false,
    "RandomRecycleValue": 5,
    "TotalAmountOfPokeballsToKeep": 180,
    "TotalAmountOfPotionsToKeep": 30,
    "TotalAmountOfRevivesToKeep": 30,
    "TotalAmountOfBerriesToKeep": 50,
    "UseRecyclePercentsInsteadOfTotals": false,
    "PercentOfInventoryPokeballsToKeep": 35,
    "PercentOfInventoryPotionsToKeep": 35,
    "PercentOfInventoryRevivesToKeep": 20,
    "PercentOfInventoryBerriesToKeep": 10
  },
  "CustomCatchConfig": {
    "EnableHumanizedThrows": true,
    "EnableMissedThrows": true,
    "ThrowMissPercentage": 25,
    "NiceThrowChance": 5,
    "GreatThrowChance": 15,
    "ExcellentThrowChance": 80,
    "CurveThrowChance": 90,
    "ForceGreatThrowOverIv": 90.0,
    "ForceExcellentThrowOverIv": 95.0,
    "ForceGreatThrowOverCp": 1000,
    "ForceExcellentThrowOverCp": 1500,
    "UseTransferFilterToCatch": true
  },
  "PlayerConfig": {
    "DelayBetweenPlayerActions": 5000,
    "EvolveActionDelay": 1000,
    "TransferActionDelay": 1000,
    "RecycleActionDelay": 1000,
    "RenamePokemonActionDelay": 1000,
    "UseNearActionRandom": true
  },
  "SoftBanConfig": {
    "FastSoftBanBypass": false,
    "ByPassSpinCount": 1
  },
  "GoogleWalkConfig": {
    "UseGoogleWalk": false,
    "DefaultStepLength": 1.3,
    "GoogleHeuristic": "walking",
    "GoogleAPIKey": null,
    "Cache": true,
    "GoogleElevationAPIKey": null
  },
  "YoursWalkConfig": {
    "UseYoursWalk": false,
    "YoursWalkHeuristic": "bicycle"
  },
  "MapzenWalkConfig": {
    "UseMapzenWalk": false,
    "MapzenTurnByTurnApiKey": null,
    "MapzenWalkHeuristic": "bicycle",
    "MapzenElevationApiKey": null
  },
  "ItemRecycleFilter": [
    {
      "Key": "itemUnknown",
      "Value": 0
    },
    {
      "Key": "itemLuckyEgg",
      "Value": 200
    },
    {
      "Key": "itemIncenseOrdinary",
      "Value": 100
    },
    {
      "Key": "itemIncenseSpicy",
      "Value": 100
    },
    {
      "Key": "itemIncenseCool",
      "Value": 100
    },
    {
      "Key": "itemIncenseFloral",
      "Value": 100
    },
    {
      "Key": "itemTroyDisk",
      "Value": 100
    },
    {
      "Key": "itemXAttack",
      "Value": 100
    },
    {
      "Key": "itemXDefense",
      "Value": 100
    },
    {
      "Key": "itemXMiracle",
      "Value": 100
    },
    {
      "Key": "itemSpecialCamera",
      "Value": 100
    },
    {
      "Key": "itemIncubatorBasicUnlimited",
      "Value": 100
    },
    {
      "Key": "itemIncubatorBasic",
      "Value": 100
    },
    {
      "Key": "itemPokemonStorageUpgrade",
      "Value": 100
    },
    {
      "Key": "itemItemStorageUpgrade",
      "Value": 100
    }
  ],
  "PokemonsNotToTransfer": [
    "articuno",
    "zapdos",
    "moltres",
    "mewtwo",
    "mew"
  ],
  "PokemonsToEvolve": [
    "eevee",
    "caterpie",
    "weedle",
    "pidgey",
    "rattata"
  ],
  "PokemonsToLevelUp": [
    "lapras",
    "snorlax",
    "dragonite"
  ],
  "PokemonsToIgnore": [],
  "CaptchaConfig": {
    "AllowManualCaptchaResolve": true,
    "ManualCaptchaTimeout": 120,
    "PlaySoundOnCaptcha": true,
    "DisplayOnTop": true,
    "Enable2Captcha": true,
    "EnableAntiCaptcha": false,
    "AntiCaptchaAPIKey": "",
    "ProxyHost": "",
    "ProxyPort": 3128,
    "EnableCaptchaSolutions": false,
    "CaptchaSolutionAPIKey": "",
    "CaptchaSolutionsSecretKey": "",
    "AutoCaptchaTimeout": 120,
    "AutoCaptchaRetries": 3,
    "TwoCaptchaAPIKey": ""
  },
  "PokemonsTransferFilter": {
      "Ditto": {
      "KeepMinCp": 100,
      "KeepMinIvPercentage": 90.0,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinOperator": "or",
      "KeepMinDuplicatePokemon": 5,
        "Moves": [
          [
          ]
        ],
      "DeprecatedMoves": null,
      "MovesOperator": "and",
      "CatchOnlyPokemonMeetTransferCriteria": false
    },
    "Vaporeon": {
      "KeepMinCp": 100,
      "KeepMinIvPercentage": 90.0,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinOperator": "or",
      "KeepMinDuplicatePokemon": 20,
      "Moves": [
        [
          "waterGun",
          "hydroPump"
        ]
      ],
      "DeprecatedMoves": null,
      "MovesOperator": "and",
      "CatchOnlyPokemonMeetTransferCriteria": false
    },
    "Lapras": {
      "KeepMinCp": 100,
      "KeepMinIvPercentage": 90.0,
      "KeepMinLvl": 1,
      "UseKeepMinLvl": true,
      "KeepMinOperator": "and",
      "KeepMinDuplicatePokemon": 30,
      "Moves": [
        [
          "dragonBreath",
          "blizzard"
        ]
      ],
      "DeprecatedMoves": null,
      "MovesOperator": "and",
      "CatchOnlyPokemonMeetTransferCriteria": false
    },
    "Dratini": {
      "KeepMinCp": 100,
      "KeepMinIvPercentage": 99.0,
      "KeepMinLvl": 1,
      "UseKeepMinLvl": true,
      "KeepMinOperator": "and",
      "KeepMinDuplicatePokemon": 50,
      "Moves": [
        [ ]
      ],
      "DeprecatedMoves": null,
      "MovesOperator": "and",
      "CatchOnlyPokemonMeetTransferCriteria": false
    },
    "Dragonite": {
      "KeepMinCp": 200,
      "KeepMinIvPercentage": 100.0,
      "KeepMinLvl": 1,
      "UseKeepMinLvl": true,
      "KeepMinOperator": "and",
      "KeepMinDuplicatePokemon": 6,
      "Moves": [
        [
          "dragonBreath",
          "dragonClaw"
        ]
      ],
      "DeprecatedMoves": null,
      "MovesOperator": "and",
      "CatchOnlyPokemonMeetTransferCriteria": false
    },
    "MrMime": {
      "KeepMinCp": 200,
      "KeepMinIvPercentage": 100.0,
      "KeepMinLvl": 1,
      "UseKeepMinLvl": true,
      "KeepMinOperator": "and",
      "KeepMinDuplicatePokemon": 3,
      "Moves": [
        [
        ]
      ],
      "DeprecatedMoves": null,
      "MovesOperator": "and",
      "CatchOnlyPokemonMeetTransferCriteria": false
    },
      "Kangaskhan": {
      "KeepMinCp": 200,
      "KeepMinIvPercentage": 100.0,
      "KeepMinLvl": 1,
      "UseKeepMinLvl": true,
      "KeepMinOperator": "and",
      "KeepMinDuplicatePokemon": 3,
      "Moves": [
        [
        ]
      ],
      "DeprecatedMoves": null,
      "MovesOperator": "and",
      "CatchOnlyPokemonMeetTransferCriteria": false
    },
    "Tauros": {
      "KeepMinCp": 200,
      "KeepMinIvPercentage": 100.0,
      "KeepMinLvl": 1,
      "UseKeepMinLvl": true,
      "KeepMinOperator": "and",
      "KeepMinDuplicatePokemon": 3,
      "Moves": [
        [
        ]
      ],
      "DeprecatedMoves": null,
      "MovesOperator": "and",
      "CatchOnlyPokemonMeetTransferCriteria": false
    },
    "Rhydon": {
      "KeepMinCp": 200,
      "KeepMinIvPercentage": 100.0,
      "KeepMinLvl": 1,
      "UseKeepMinLvl": true,
      "KeepMinOperator": "and",
      "KeepMinDuplicatePokemon": 10,
      "Moves": [
        [
        ]
      ],
      "DeprecatedMoves": null,
      "MovesOperator": "and",
      "CatchOnlyPokemonMeetTransferCriteria": false
    },
      "Arcanine": {
      "KeepMinCp": 200,
      "KeepMinIvPercentage": 100.0,
      "KeepMinLvl": 1,
      "UseKeepMinLvl": true,
      "KeepMinOperator": "and",
      "KeepMinDuplicatePokemon": 10,
      "Moves": [
        [
        ]
      ],
      "DeprecatedMoves": null,
      "MovesOperator": "and",
      "CatchOnlyPokemonMeetTransferCriteria": false
    },
    "Snorlax": {
      "KeepMinCp": 99,
      "KeepMinIvPercentage": 90.0,
      "KeepMinLvl": 1,
      "UseKeepMinLvl": true,
      "KeepMinOperator": "and",
      "KeepMinDuplicatePokemon": 30,
      "Moves": [
        [
          "lick",
          "bodySlam"
        ]
      ],
      "DeprecatedMoves": null,
      "MovesOperator": "and",
      "CatchOnlyPokemonMeetTransferCriteria": false
    }
  },
  "PokemonToSnipe": {
    "Locations": [
      {
        "Latitude": -33.860063648003653,
        "Longitude": 151.20049953460693
      }
    ],
    "Pokemon": [
      "rhydon",
      "arcanine",
      "kangaskhan",
      "tauros",
      "mrmime",
      "vaporeon",
      "ditto",
      "lapras",
      "ditto",
      "eevee",
      "snorlax",
      "dratini",
      "dragonair",
      "dragonite",
      "mewtwo",
      "mew"
    ]
  },
  "PokemonToUseMasterball": [
    "articuno",
    "zapdos",
    "moltres",
    "mew",
    "mewtwo"
  ],
  "HumanWalkSnipeFilters": {},
  "PokemonUpgradeFilters": {},
  "MultipleBotConfig": {
    "RuntimeSwitch": 55,
    "OnLimitPauseTimes": 15,
    "OnRarePokemon": true,
    "MinIVToSwitch": 95.0,
    "EXPSwitch": 25000,
    "PokestopSwitch": 500,
    "PokemonSwitch": 200,
    "PokemonPerHourSwitch": 100,
    "StartFromDefaultLocation": true,
    "PokestopSoftbanCount": 5,
    "DisplayList": true,
    "SelectAccountOnStartUp": false,
    "CatchFleeCount": 5,
    "SwitchOnCatchLimit": true,
    "SwitchOnPokestopLimit": true
  },
  "NotificationConfig": {
    "EnablePushBulletNotification": false,
    "EnableEmailNotification": false,
    "PushBulletApiKey": "",
    "GmailUsername": "",
    "GmailPassword": "",
    "Recipients": ""
  },
  "SnipePokemonFilter": {
      "Arcanine": {
      "SnipeIV": 60,
      "Moves": [ ],
      "Operator": "or",
      "VerifiedOnly": true,
      "Priority": 5,
      "AutoSnipeCandy": 2000
    },
    "Rhydon": {
      "SnipeIV": 60,
      "Moves": [ ],
      "Operator": "or",
      "VerifiedOnly": true,
      "Priority": 5,
      "AutoSnipeCandy": 2000
    },
    "Eevee": {
      "SnipeIV": 60,
      "Moves": [ ],
      "Operator": "or",
      "VerifiedOnly": true,
      "Priority": 5,
      "AutoSnipeCandy": 2000
    },
    "MrMime": {
      "SnipeIV": 60,
      "Moves": [ ],
      "Operator": "or",
      "VerifiedOnly": true,
      "Priority": 5,
      "AutoSnipeCandy": 2000
    },
    "Kangaskhan": {
      "SnipeIV": 60,
      "Moves": [ ],
      "Operator": "or",
      "VerifiedOnly": true,
      "Priority": 5,
      "AutoSnipeCandy": 2000
    },
    "Tauros": {
      "SnipeIV": 60,
      "Moves": [ ],
      "Operator": "or",
      "VerifiedOnly": true,
      "Priority": 5,
      "AutoSnipeCandy": 2000
    },
    "Lapras": {
      "SnipeIV": 10,
      "Moves": [ ],
      "Operator": "or",
      "VerifiedOnly": true,
      "Priority": 5,
      "AutoSnipeCandy": 10000
    },
    "Snorlax": {
      "SnipeIV": 10,
      "Moves": [ ],
      "Operator": "or",
      "VerifiedOnly": true,
      "Priority": 5,
      "AutoSnipeCandy": 10000
    },
    "Dratini": {
      "SnipeIV": 60,
      "Moves": [ ],
      "Operator": "or",
      "VerifiedOnly": true,
      "Priority": 5,
      "AutoSnipeCandy": 90000
    },
    "Ditto": {
      "SnipeIV": 100,
      "Moves": [ ],
      "Operator": "or",
      "VerifiedOnly": true,
      "Priority": 5,
      "AutoSnipeCandy": 2000
    },
    "Vaporeon": {
      "SnipeIV": 100,
      "Moves": [ ],
      "Operator": "or",
      "VerifiedOnly": true,
      "Priority": 5,
      "AutoSnipeCandy": 2000
    },
    "Dragonair": {
      "SnipeIV": 100,
      "Moves": [ ],
      "Operator": "or",
      "VerifiedOnly": true,
      "Priority": 5,
      "AutoSnipeCandy": 2000
    },
    "Dragonite": {
      "SnipeIV": 100,
      "Moves": [ ],
      "Operator": "or",
      "VerifiedOnly": true,
      "Priority": 5,
      "AutoSnipeCandy": 2000
    }
  },
  "EvolvePokemonFilter": {
    "Eevee": {
      "EnableEvolve": true,
      "MinIV": 100,
      "MinLV": 1,
      "MinCP": 100,
      "Moves": [],
      "Operator": "and"
    },
    "Dragonair": {
      "EnableEvolve": true,
      "MinIV": 100,
      "MinLV": 1,
      "MinCP": 100,
      "Moves": [],
      "Operator": "or"
    },
    "Dratini": {
      "EnableEvolve": true,
      "MinIV": 100,
      "MinLV": 1,
      "MinCP": 100,
      "Moves": [],
      "Operator": "or"
    },
    "Zubat": {
      "EnableEvolve": true,
      "MinIV": 0,
      "MinLV": 0,
      "MinCP": 0,
      "Moves": [],
      "Operator": "or"
    },
    "Pidgey": {
      "EnableEvolve": true,
      "MinIV": 0,
      "MinLV": 0,
      "MinCP": 0,
      "Moves": [],
      "Operator": "or"
    },
    "Weedle": {
      "EnableEvolve": true,
      "MinIV": 0,
      "MinLV": 0,
      "MinCP": 0,
      "Moves": [],
      "Operator": "or"
    },
    "Caterpie": {
      "EnableEvolve": true,
      "MinIV": 0,
      "MinLV": 0,
      "MinCP": 0,
      "Moves": [],
      "Operator": "or"
    }
  },
  "CatchPokemonFilter": {
    "Lapras": {
      "MinIV": 0,
      "MinLV": 0,
      "MinCP": 0,
      "Moves": [],
      "Operator": "or"
    },
    "Dratini": {
      "MinIV": 0,
      "MinLV": 0,
      "MinCP": 0,
      "Moves": [],
      "Operator": "or"
    },
    "Dragonite": {
      "MinIV": 0,
      "MinLV": 0,
      "MinCP": 0,
      "Moves": [],
      "Operator": "or"
    },
    "Snorlax": {
      "MinIV": 0,
      "MinLV": 0,
      "MinCP": 0,
      "Moves": [],
      "Operator": "or"
    },
    "Zubat": {
      "MinIV": 100,
      "MinLV": 100,
      "MinCP": 0,
      "Moves": [],
      "Operator": "and"
    }
  },
  "BotSwitchPokemonFilters": {
    "Dragonite": {
      "IV": 10,
      "RemainTimes": 99,
      "Operator": "or",
      "LV": 0,
      "Moves": []
    },
    "Lapras": {
      "IV": 10,
      "RemainTimes": 90,
      "Operator": "or",
      "LV": 0,
      "Moves": []
    },
    "Exeggutor": {
      "IV": 10,
      "RemainTimes": 99,
      "Operator": "or",
      "LV": 0,
      "Moves": []
    },
    "Arcanine": {
      "IV": 10,
      "RemainTimes": 99,
      "Operator": "or",
      "LV": 0,
      "Moves": []
    },
    "Blastoise": {
      "IV": 10,
      "RemainTimes": 99,
      "Operator": "or",
      "LV": 0,
      "Moves": []
    },
    "Charizard": {
      "IV": 10,
      "RemainTimes": 99,
      "Operator": "or",
      "LV": 0,
      "Moves": []
    },
    "Venusaur": {
      "IV": 10,
      "RemainTimes": 99,
      "Operator": "or",
      "LV": 100,
      "Moves": []
    },
    "Vaporeon": {
      "IV": 10,
      "RemainTimes": 99,
      "Operator": "or",
      "LV": 0,
      "Moves": []
    },
    "Dragonair": {
      "IV": 70,
      "RemainTimes": 99,
      "Operator": "or",
      "LV": 0,
      "Moves": []
    },
    "Dratini": {
      "IV": 90,
      "RemainTimes": 99,
      "Operator": "or",
      "LV": 100,
      "Moves": []
    },
    "Snorlax": {
      "IV": 30,
      "RemainTimes": 90,
      "Operator": "or",
      "LV": 0,
      "Moves": []
    },
    "Magikarp": {
      "IV": 99,
      "RemainTimes": 60,
      "Operator": "or",
      "LV": 0,
      "Moves": []
    }
  }
}

**Comment by hardknoxni69a** [comment]
some of the pokemon we show are from public sources so sometimes the pokemon will not be available but nothing is wrong with your config or the snipe server please try again i am sure you will be ok that is not an error its just letting you know there wasnt a pokemon in that location please set as unverified and you will get more results
