### ISSUE TITLE
Necrobot evolves all my Pokemons

### ISSUE THREAD

**Issue by redking974** [Necrobot-Private/NecroBot#799]
### Expected Behavior:
I want to evolve none of my Pokemons

### Actual Behavior:
Necrobot has evolved all of my Pokemons

### Your config.json:
```
    "EvolveAboveIvValue": 95.0,
    "EvolveAllPokemonAboveIv": false,
    "EvolveAllPokemonWithEnoughCandy": false,
    "EvolveKeptPokemonsAtStorageUsagePercentage": 90.0,
    "EvolveKeptPokemonIfBagHasOverThisManyPokemon": 999,
    "KeepPokemonsThatCanEvolve": true,
...
  "PokemonsToEvolve": [ ],
...
  "EvolvePokemonFilter": { },
```

### (OPTIONAL) Your Log:
```
[13:29:31] (EVOLUTION) [Evolution] Disponible : 118
[13:29:31] (MÀJ) Encore 8 Pokémon à capturer pour en évoluer 118 d'un coup ! (201/209 pour 88.3908269796012% de votre inventaire)
...
[13:40:18] (EVOLUTION) [Evolution] Disponible : 129
[13:40:19] (EVOLUTION) 1. Krabby +1000XP
[13:40:44] (EVOLUTION) 2. Krabby +500XP
...
```

### Detailed Steps to Reproduce:

Version: 1.0.0.99
Windows Version: Windows 10
What is affected: evolve

**Comment by samuraitruong** [comment]
why don't turn off envolve instead of set list to empty, but it need to fix anyway

**Comment by redking974** [comment]
I though I turned off @samuraitruong with
"EvolveAllPokemonAboveIv": false,
"EvolveAllPokemonWithEnoughCandy": false,

but obviously it wasn't. What do I have to change into config to turn off ?

Regards

**Comment by hardknoxni69a** [comment]
take the pokemon off the list andset 
    "KeepMinCp": 0,
    "KeepMinIvPercentage": 0,,
    "KeepMinLvl": 0,
    "KeepMinOperator": "and",
    "UseKeepMinLvl": true,
and it will keep all pokemon without evolving them

**Comment by redking974** [comment]
Hello @hardknoxni69a in fact the only fix that I found is to let at least one pokemon (Mew in my case) because when filter is empty Necrobot will evolve all Pokemons. Maybe it's just for my config that this issue comes but with at least one Pokemon it fixes it. Regards.

**Comment by hardknoxni69a** [comment]
Good to know will keep unown in there for people that dont want to evolve
thanks
