### ISSUE TITLE
GUI Doesnt Reflect Correct Bag Sizes

### ISSUE THREAD

**Issue by hardknoxni69a** [Necrobot-Private/NecroBot#802]
GUI Doesnt Show Correct Pokemon Bag Or Item Bag If You Have Upgrades

**Comment by samuraitruong** [comment]
more detail?

**Comment by momentosnaps** [comment]
One of my accounts Pokemon bag limit is upgraded to 500 but GUI still shows xxx/250. Items bag limit is shown correctly.

**Comment by redking974** [comment]
Yes, I have the same "issue" @samuraitruong , the number remains to 250 even if you upgrade your bag.

**Comment by hardknoxni69a** [comment]
looks like items shows right bag size but pokemon shows 400/250

**Comment by redking974** [comment]
There is no issue with bag size @hardknoxni69a , it's just about Pokemon inventory :)

**Comment by hardknoxni69a** [comment]
That's what I said the inventory is good but poke bag is off

**Comment by hardknoxni69a** [comment]
closed for newer issue #1270
