### ISSUE TITLE
(Request) Button To Clear Map And Zoom In And Out

### ISSUE THREAD

**Issue by hardknoxni69a** [Necrobot-Private/NecroBot#803]
(Request) Button To Clear Map And Zoom In And Out
Zooming In And Out Is Difficult Without Buttons And The Map Gets Very Clustered Because The Map Saves Everything So A Clear All Button Would Be Nice And Possibly A GUI Setting That Auto Clears After X:Time

**Comment by samuraitruong** [comment]
you can scroll mouse to zoom, however, I will add zoom bar tonight

**Comment by samuraitruong** [comment]
#814  fixed
