### ISSUE TITLE
Request GUI Sniper lists: slow down frequency of changes, refresh button, or make update speed user-selectable

### ISSUE THREAD

**Issue by macinmn** [Necrobot-Private/NecroBot#804]
### Expected Behavior:
list is slower to update, or is refreshed manually by button, or option to set frequency of list update,  so that you can click on a specific pokemon before it changes position in the list

### Actual Behavior:
Sniper lists in GUI interface have additions and removals too quickly to successfully click on a specific pokemon with reliable success

### Your config.json:
```
n/a

```

### (OPTIONAL) Your Log:
```
while trying to click on Porygon at ~[40,-74]:

[15:32:17] (INFO) (MANUAL SNIPER) Pokemon added |  Lickitung [40.81351285,-73.96275416] IV 46.67%
[15:32:18] (SNIPER) (InternalSnipe) Sniping a Lickitung with 46.67 IV at 40.81351285,-73.96275416...
[15:32:28] (INFO) (MANUAL SNIPER) Pokemon added |  Lickitung [35.528646852,139.696362431] IV 0.71%

```

### Detailed Steps to Reproduce:

open Sniper tab in GUI, wait until list populates, try to click on monster and you frequently click on another that has taken its physical position on the list instead

### Other Information
(Attach zip files if needed.)

Version:  all since introduction of feature
Windows Version: Windows 7
What is affected ():  GUI client, Sniper tab lists

**Comment by hardknoxni69a** [comment]
I think A pause list status will be good and it can update in background still just unpause to see additions

**Comment by hardknoxni69a** [comment]
a pause button would be great before selecting what you want to snipe as list is updated quickly and with the lag u click on a magikarp but snipe an eevee because list has moved so quickly just a freeze results would be good it can refresh still in background but freezes list momentarily to choose manual snipe would be great

**Comment by samuraitruong** [comment]
#1134

**Comment by hardknoxni69a** [comment]
He's on a roll ladies and gents killing it with the updates!!! So pumped
for the update
