### ISSUE TITLE
request: auto ThrowMissPercentage based on Catch Chance Pokemon

### ISSUE THREAD

**Issue by saldotman** [Necrobot-Private/NecroBot#805]
Can we have option to automate ThrowMissPercentage, calculated based on Catch Chance for each pokemon?

ThrowMissPercentage then should be: 1 - CatchChancePct

may be with additional option: Max ThrowMissPercentage to increase possibilities catching rare pokemon

**Comment by samuraitruong** [comment]
throw miss and catch chance are not related, why we need this option?

**Comment by hardknoxni69a** [comment]
You can miss 100 throws and all it does is lower your count of pokeballs it doesnt effect how likely the pokemon is to flee so i wouldnt worry honestly the throw miss percentage is just an extra feature for human like settings but it has no effect on your catch rate so i wouldnt worry if a dragonite is going to run after 6 escapes it will still escape after the 6th breakout even if you threw 15 missed balls as well the only time the pokemon itself has interaction is if he is actually in the ball so no need to worry about miss throw percentage on rares

**Comment by saldotman** [comment]
Just a thought that configure ThrowMissPercentage based on CatchChancePct may make bot more 'human'

**Comment by SLASHLogin** [comment]
I understand this now, when you trying catch pkmn with 90% chance so you will miss 4, but when catching 20% and miss 0 but pkmn broke pkball and you will lose 4 balls also. 
Numbers are random :p

**Comment by saldotman** [comment]
I cancel my request.

thx
