### ISSUE TITLE
Delay of sneding the data from MSniper to Necrobot

### ISSUE THREAD

**Issue by kje999** [Necrobot-Private/NecroBot#82]
Hi, I suggest to prioritize the data first that has been sent from MSniper to Necrobot as soon as possible. Or Snipe whenever my character walks if it is possible added to the feature.

### Expected Behavior:
Catches the pokemon that I snipe before it will despawned. Snipe as soon as possible.

### Actual Behavior:
It snipes until I reach a pokestop(what if the pokestop is too far away=Pokemon Despawned). Sometimes the Pokemon to be snipe is despawned because of that delay.

**Comment by ntatoo** [comment]
@kje999 working on that

**Comment by samuraitruong** [comment]
Dont need to do that because you will alway reach poketop in 15 min. If you missed, you can try different pokemon later. I

**Comment by msx752** [comment]
it may async sender,but now it isn't priority,  i aggre with @samuraitruong
