### ISSUE TITLE
Pokemon bag not being update timely cause full bag

### ISSUE THREAD

**Issue by samuraitruong** [Necrobot-Private/NecroBot#821]
Actually bot doing transfer but bot stil full.

I think that is because inventory not get update, when I check the log, right after evolve action then bot start work well with out full bag issue, but evolve is 1=1 nore add, no remove bag, so that is code issue

**Comment by firies1** [comment]
(iphone7+) ->i already upgrade(+50) my poke inventory for pokemon. but  neacro program didn't work on expansion inventory.

**Comment by samuraitruong** [comment]
the bag update is good, not an issue
