### ISSUE TITLE
(ERROR) Niantic Servers unstable, throttling API Calls.

### ISSUE THREAD

**Issue by organicbetty** [Necrobot-Private/NecroBot#823]
Please can someone clarify the meaning of this error? I cannot log in to the bot, the following message comes up every time:

Log:

[13:07:29] (ERROR) Niantic Servers unstable, throttling API Calls. Error with API request type: PlayerUpdate

**Comment by anoop95g** [comment]
Same error. Downloaded the new version and tried re installing. But the error pops up.

**Comment by cswxin** [comment]
Same

**Comment by Arun12121** [comment]
Same here

**Comment by plpsh1105** [comment]
me too

**Comment by mcreuter** [comment]
same

**Comment by firies1** [comment]
me too!

**Comment by mcy710** [comment]
me too !!!

**Comment by saldotman** [comment]
another trap from niantic?

because i can still play via mobile

**Comment by firies1** [comment]
umm by mobile, it's still work , but by pc(necrobot2) haven't been work.

along side :(ERROR) Niantic Servers unstable, throttling API Calls. Error with API request type: PlayerUpdate

**Comment by wangki90** [comment]
me too~_~

**Comment by samuraitruong** [comment]
they removed PlayerUpdate api called, we need update bot

**Comment by samuraitruong** [comment]
fixed #825 825
