### ISSUE TITLE
manual powerup through win GUI not working

### ISSUE THREAD

**Issue by illusive87** [Necrobot-Private/NecroBot#824]
### Expected Behavior:
In the Win GUI, when clicking upgrade it shows the popup window giving you a choice between normal power up or max power up. Clicking one will perform the action or request input variables. 

### Actual Behavior:
The popup window shows but click either choice has no effect. No confirmation and no actions performed (checked by monitoring console)

### Your config.json:
Manual overrides config so not needed

Version: v100
Windows Version: 10
What is affected (catch, transfer, favorite, GPX, evolve, recycle, snipe, human walk snipe, pokestops, powerup/levelup, other): powerup

**Comment by hardknoxni69a** [comment]
should be working with latest version as long as u have the candies and dust just did a few max poweruprs enjoy
