### ISSUE TITLE
GUI unresponsive / broken

### ISSUE THREAD

**Issue by organicbetty** [Necrobot-Private/NecroBot#826]
GUI no longer functions correctly since the latest update: 1.0.0.102
Client freezes and stops working after initial loading, buttons cannot be clicked etc.

**Comment by samuraitruong** [comment]
that is new feature make GUI slow, it display location which require long time to load, I made new card to solve this issue

**Comment by samuraitruong** [comment]
https://github.com/Necrobot-Private/NecroBot/issues/815

**Comment by organicbetty** [comment]
It's not slow, it doesn't work at all? The screen is frozen (no movement)
