### ISSUE TITLE
My walkin speed is like im teleporting to a stop to an other it's because of my config ot it is just a global problem? I would be thankfull if someone cloud help me .

### ISSUE THREAD

**Issue by trez22** [Necrobot-Private/NecroBot#828]
## Stop! Before you create this issue (you can delete this section when opening the issue):
1. Have you searched to see if there are other Open/Closed issues for the same issue? If so, comment on that issue instead.
2. Have you validated that your config/auth.json and config/config.json is valid JSON? Use http://jsonlint.com/ to check.
3. If your question is referring to how to set up or use the bot, please join our discord instead of posting an issue: https://discord.gg/7FWyWVp 
4. Always confirm that your issue is reproducible, with the config you provide below.

### Your config.json:
```
replace this text with the contents of your config.json

```

### (OPTIONAL) Your Log:
```
replace this text with only the "relative" portion of your log. (Remove unnessary lines)

```

### Other Information
(Attach zip files if needed.)

Version:
Windows Version:
What is affected (catch, transfer, favorite, GPX, evolve, recycle, snipe, human walk snipe, pokestops, powerup/levelup, other):

**Comment by organicbetty** [comment]
Maybe if you posted the actual config someone could help you...

**Comment by ghkvert** [comment]
Maybe if you opened the bot you would see the issue....fucker

**Comment by organicbetty** [comment]
Well I've opened the bot and I don't see the issue. So maybe you should post the config like I suggested? Hilarious

**Comment by hardknoxni69a** [comment]
disbalehumanwalking needs to be false or it pretty muchs teleports you determined on the speed set and please if you need help or you have questions about config attach the config or cant help as much
