### ISSUE TITLE
MapQuest Elevation response not reliable

### ISSUE THREAD

**Issue by petpetpetvm** [Necrobot-Private/NecroBot#83]
[00:04:25] (ATTENTION) MapQuest Elevation response not reliable: -32768
[00:04:25] (ATTENTION) Continuing without elevation-readings not recommended. Press any key to stop.

so i have to use the google api now ?

config:
{
  "ConsoleConfig": {
    "TranslationLanguageCode": "en",
    "StartupWelcomeDelay": false,
    "AmountOfPokemonToDisplayOnStart": 10,
    "DetailedCountsBeforeRecycling": true
  },
  "UpdateConfig": {
    "CheckForUpdates": false,
    "AutoUpdate": false,
    "TransferConfigAndAuthOnUpdate": true
  },
  "WebsocketsConfig": {
    "UseWebsocket": false,
    "WebSocketPort": 14251
  },
  "LocationConfig": {
    "DisableHumanWalking": true,
    "StartFromLastPosition": false,
    "DefaultLatitude": 34.0092419,
    "DefaultLongitude": -118.49760370000001,
    "WalkingSpeedInKilometerPerHour": 98.92,
    "UseWalkingSpeedVariant": true,
    "WalkingSpeedVariant": 1.3,
    "ShowVariantWalking": false,
    "RandomlyPauseAtStops": true,
    "MaxSpawnLocationOffset": 10,
    "MaxTravelDistanceInMeters": 1370
  },
  "TelegramConfig": {
    "UseTelegramAPI": false,
    "TelegramAPIKey": null,
    "TelegramPassword": "12345"
  },
  "GPXConfig": {
    "UseGpxPathing": false,
    "GpxFile": "GPXPath.GPX"
  },
  "SnipeConfig": {
    "UseSnipeLocationServer": true,
    "SnipeLocationServer": "localhost",
    "SnipeLocationServerPort": 16969,
    "GetSniperInfoFromPokezz": true,
    "GetOnlyVerifiedSniperInfoFromPokezz": false,
    "GetSniperInfoFromPokeSnipers": true,
    "GetSniperInfoFromPokeWatchers": true,
    "GetSniperInfoFromSkiplagged": true,
    "MinPokeballsToSnipe": 0,
    "MinPokeballsWhileSnipe": 0,
    "MinDelayBetweenSnipes": 20000,
    "SnipingScanOffset": 0.013,
    "SnipeAtPokestops": false,
    "ActivateMSniper": true,
    "SnipeIgnoreUnknownIv": false,
    "UseTransferIvForSnipe": false,
    "SnipePokemonNotInPokedex": false,
    "UseSnipeLimit": true,
    "SnipeRestSeconds": 250,
    "SnipeCountLimit": 42
  },
  "HumanWalkSnipeConfig": {
    "Enable": false,
    "DisplayPokemonList": true,
    "MaxDistance": 1500.0,
    "MaxEstimateTime": 900.0,
    "CatchEmAllMinBalls": 50,
    "TryCatchEmAll": true,
    "CatchPokemonWhileWalking": true,
    "SpinWhileWalking": true,
    "AlwaysWalkback": false,
    "SnipingScanOffset": 0.025,
    "WalkbackDistanceLimit": 300.0,
    "IncludeDefaultLocation": true,
    "UsePokeRadar": true,
    "UseSkiplagged": true,
    "UseSnipePokemonList": true,
    "MaxSpeedUpSpeed": 60.0,
    "AllowSpeedUp": true,
    "DelayTimeAtDestination": 10000,
    "UseFastPokemap": true,
    "UsePogoLocationFeeder": false
  },
  "PokeStopConfig": {
    "UsePokeStopLimit": true,
    "PokeStopLimit": 1998,
    "PokeStopLimitMinutes": 1470
  },
  "PokemonConfig": {
    "CatchPokemon": true,
    "DelayBetweenPokemonCatch": 500,
    "UseCatchLimit": true,
    "CatchPokemonLimit": 998,
    "CatchPokemonLimitMinutes": 1470,
    "UseIncenseConstantly": true,
    "UseEggIncubators": true,
    "UseLimitedEggIncubators": true,
    "UseLuckyEggConstantly": true,
    "UseLuckyEggsMinPokemonAmount": 0,
    "UseLuckyEggsWhileEvolving": true,
    "UseBerriesMinCp": 100,
    "UseBerriesMinIv": 90.0,
    "UseBerriesBelowCatchProbability": 0.2,
    "UseBerriesOperator": "and",
    "MaxBerriesToUsePerPokemon": 3,
    "TransferWeakPokemon": true,
    "TransferDuplicatePokemon": true,
    "TransferDuplicatePokemonOnCapture": false,
    "RenamePokemon": false,
    "RenameOnlyAboveIv": false,
    "RenameTemplate": "{0}_{1}",
    "FavoriteMinIvPercentage": 99.0,
    "AutoFavoritePokemon": true,
    "MaxPokeballsPerPokemon": 6,
    "UseGreatBallAboveCp": 750,
    "UseUltraBallAboveCp": 2500,
    "UseMasterBallAboveCp": 1500,
    "UseGreatBallAboveIv": 85.0,
    "UseUltraBallAboveIv": 95.0,
    "UseGreatBallBelowCatchProbability": 0.0,
    "UseUltraBallBelowCatchProbability": 0.0,
    "UseMasterBallBelowCatchProbability": 0.0,
    "AutomaticallyLevelUpPokemon": false,
    "OnlyUpgradeFavorites": true,
    "UseLevelUpList": false,
    "AmountOfTimesToUpgradeLoop": 5,
    "GetMinStarDustForLevelUp": 5000,
    "LevelUpByCPorIv": "iv",
    "UpgradePokemonCpMinimum": 1000.0,
    "UpgradePokemonIvMinimum": 99.0,
    "UpgradePokemonMinimumStatsOperator": "and",
    "EvolveAboveIvValue": 99.0,
    "EvolveAllPokemonAboveIv": false,
    "EvolveAllPokemonWithEnoughCandy": false,
    "EvolveKeptPokemonsAtStorageUsagePercentage": 90.0,
    "KeepPokemonsThatCanEvolve": false,
    "KeepMinCp": 2000,
    "KeepMinIvPercentage": 95.0,
    "KeepMinLvl": 6,
    "KeepMinOperator": "or",
    "UseKeepMinLvl": false,
    "PrioritizeIvOverCp": true,
    "KeepMinDuplicatePokemon": 0,
    "UsePokemonToNotCatchFilter": true,
    "UsePokemonSniperFilterOnly": false,
    "DumpPokemonStats": true
  },
  "RecycleConfig": {
    "VerboseRecycling": true,
    "RecycleInventoryAtUsagePercentage": 90.0,
    "RandomizeRecycle": false,
    "RandomRecycleValue": 5,
    "TotalAmountOfPokeballsToKeep": 270,
    "TotalAmountOfPotionsToKeep": 0,
    "TotalAmountOfRevivesToKeep": 0,
    "TotalAmountOfBerriesToKeep": 50,
    "MaxPokeballsToKeep": 50
  },
  "CustomCatchConfig": {
    "EnableHumanizedThrows": true,
    "EnableMissedThrows": true,
    "ThrowMissPercentage": 14,
    "NiceThrowChance": 40,
    "GreatThrowChance": 30,
    "ExcellentThrowChance": 10,
    "CurveThrowChance": 90,
    "ForceGreatThrowOverIv": 90.0,
    "ForceExcellentThrowOverIv": 95.0,
    "ForceGreatThrowOverCp": 1000,
    "ForceExcellentThrowOverCp": 1500
  },
  "PlayerConfig": {
    "DelayBetweenPlayerActions": 1000,
    "EvolveActionDelay": 200,
    "TransferActionDelay": 100,
    "RecycleActionDelay": 100,
    "RenamePokemonActionDelay": 200,
    "UseNearActionRandom": true,
    "AutoCompleteTutorial": false,
    "DesiredNickname": "Nickname",
    "DesiredGender": "Male",
    "DesiredStarter": "Squirtle"
  },
  "SoftBanConfig": {
    "FastSoftBanBypass": false
  },
  "GoogleWalkConfig": {
    "UseGoogleWalk": false,
    "DefaultStepLength": 1.3,
    "GoogleHeuristic": "walking",
    "GoogleAPIKey": null,
    "Cache": true
  },
  "YoursWalkConfig": {
    "UseYoursWalk": false,
    "YoursWalkHeuristic": "bicycle"
  },
  "ItemRecycleFilter": [
    {
      "Key": "itemUnknown",
      "Value": 0
    },
    {
      "Key": "itemLuckyEgg",
      "Value": 200
    },
    {
      "Key": "itemIncenseOrdinary",
      "Value": 100
    },
    {
      "Key": "itemIncenseSpicy",
      "Value": 100
    },
    {
      "Key": "itemIncenseCool",
      "Value": 100
    },
    {
      "Key": "itemIncenseFloral",
      "Value": 100
    },
    {
      "Key": "itemTroyDisk",
      "Value": 100
    },
    {
      "Key": "itemXAttack",
      "Value": 100
    },
    {
      "Key": "itemXDefense",
      "Value": 100
    },
    {
      "Key": "itemXMiracle",
      "Value": 100
    },
    {
      "Key": "itemRazzBerry",
      "Value": 200
    },
    {
      "Key": "itemBlukBerry",
      "Value": 10
    },
    {
      "Key": "itemNanabBerry",
      "Value": 10
    },
    {
      "Key": "itemWeparBerry",
      "Value": 30
    },
    {
      "Key": "itemPinapBerry",
      "Value": 30
    },
    {
      "Key": "itemSpecialCamera",
      "Value": 100
    },
    {
      "Key": "itemIncubatorBasicUnlimited",
      "Value": 100
    },
    {
      "Key": "itemIncubatorBasic",
      "Value": 100
    },
    {
      "Key": "itemPokemonStorageUpgrade",
      "Value": 999
    },
    {
      "Key": "itemItemStorageUpgrade",
      "Value": 100
    }
  ],
  "PokemonsNotToTransfer": [
    "ditto",
    "articuno",
    "zapdos",
    "moltres",
    "mewtwo",
    "mew",
    "snorlax",
    "dragonite",
    "gyarados"
  ],
  "PokemonsToEvolve": [
    "mewtwo",
    "mew"
  ],
  "PokemonsToLevelUp": [
    "mew"
  ],
  "PokemonsToIgnore": [
    "mew"
  ],
  "PokemonsTransferFilter": {
    "Mewtwo": {
      "KeepMinCp": 1500,
      "KeepMinIvPercentage": 95.0,
      "KeepMinLvl": 0,
      "UseKeepMinLvl": false,
      "KeepMinOperator": "or",
      "KeepMinDuplicatePokemon": 1,
      "Moves": [
        []
      ],
      "DeprecatedMoves": [],
      "MovesOperator": "or"
    }
  },
  "PokemonToSnipe": {
    "Locations": [
      {
        "Latitude": 38.556807486461118,
        "Longitude": -121.2383794784546
      },
      {
        "Latitude": -33.859019,
        "Longitude": 151.213098
      },
      {
        "Latitude": 47.5014969,
        "Longitude": -122.0959568
      },
      {
        "Latitude": 51.5025343,
        "Longitude": -0.2055027
      }
    ],
    "Pokemon": [
      "venusaur",
      "charizard",
      "blastoise",
      "beedrill",
      "raichu",
      "sandslash",
      "nidoking",
      "nidoqueen",
      "clefable",
      "ninetales",
      "golbat",
      "vileplume",
      "golduck",
      "primeape",
      "arcanine",
      "poliwrath",
      "alakazam",
      "machamp",
      "golem",
      "rapidash",
      "slowbro",
      "muk",
      "cloyster",
      "gengar",
      "exeggutor",
      "marowak",
      "hitmonchan",
      "lickitung",
      "rhydon",
      "chansey",
      "starmie",
      "scyther",
      "magmar",
      "electabuzz",
      "jynx",
      "gyarados",
      "lapras",
      "ditto",
      "vaporeon",
      "jolteon",
      "flareon",
      "porygon",
      "kabutops",
      "aerodactyl",
      "snorlax",
      "articuno",
      "zapdos",
      "moltres",
      "dragonite",
      "mewtwo",
      "mew"
    ]
  },
  "PokemonToUseMasterball": [
    "articuno",
    "zapdos",
    "moltres",
    "mew",
    "mewtwo"
  ],
  "HumanWalkSnipeFilters": {
    "Magikarp": {
      "MaxDistance": 300.0,
      "Priority": 10,
      "MaxWalkTimes": 200.0,
      "CatchPokemonWhileWalking": true,
      "SpinPokestopWhileWalking": true,
      "MaxSpeedUpSpeed": 60.0,
      "AllowSpeedUp": false,
      "DelayTimeAtDestination": 10
    },
    "Eevee": {
      "MaxDistance": 500.0,
      "Priority": 10,
      "MaxWalkTimes": 200.0,
      "CatchPokemonWhileWalking": true,
      "SpinPokestopWhileWalking": true,
      "MaxSpeedUpSpeed": 60.0,
      "AllowSpeedUp": false,
      "DelayTimeAtDestination": 10
    },
    "Electabuzz": {
      "MaxDistance": 1500.0,
      "Priority": 2,
      "MaxWalkTimes": 700.0,
      "CatchPokemonWhileWalking": true,
      "SpinPokestopWhileWalking": true,
      "MaxSpeedUpSpeed": 60.0,
      "AllowSpeedUp": false,
      "DelayTimeAtDestination": 10
    },
    "Dragonite": {
      "MaxDistance": 3000.0,
      "Priority": 1,
      "MaxWalkTimes": 900.0,
      "CatchPokemonWhileWalking": false,
      "SpinPokestopWhileWalking": false,
      "MaxSpeedUpSpeed": 60.0,
      "AllowSpeedUp": false,
      "DelayTimeAtDestination": 10
    },
    "Dragonair": {
      "MaxDistance": 3000.0,
      "Priority": 1,
      "MaxWalkTimes": 900.0,
      "CatchPokemonWhileWalking": false,
      "SpinPokestopWhileWalking": false,
      "MaxSpeedUpSpeed": 60.0,
      "AllowSpeedUp": false,
      "DelayTimeAtDestination": 10
    },
    "Dratini": {
      "MaxDistance": 2000.0,
      "Priority": 1,
      "MaxWalkTimes": 900.0,
      "CatchPokemonWhileWalking": false,
      "SpinPokestopWhileWalking": false,
      "MaxSpeedUpSpeed": 60.0,
      "AllowSpeedUp": false,
      "DelayTimeAtDestination": 10
    },
    "Charizard": {
      "MaxDistance": 3000.0,
      "Priority": 1,
      "MaxWalkTimes": 900.0,
      "CatchPokemonWhileWalking": false,
      "SpinPokestopWhileWalking": false,
      "MaxSpeedUpSpeed": 60.0,
      "AllowSpeedUp": false,
      "DelayTimeAtDestination": 10
    },
    "Snorlax": {
      "MaxDistance": 3000.0,
      "Priority": 1,
      "MaxWalkTimes": 900.0,
      "CatchPokemonWhileWalking": false,
      "SpinPokestopWhileWalking": false,
      "MaxSpeedUpSpeed": 60.0,
      "AllowSpeedUp": false,
      "DelayTimeAtDestination": 10
    },
    "Lapras": {
      "MaxDistance": 3000.0,
      "Priority": 1,
      "MaxWalkTimes": 900.0,
      "CatchPokemonWhileWalking": false,
      "SpinPokestopWhileWalking": false,
      "MaxSpeedUpSpeed": 60.0,
      "AllowSpeedUp": false,
      "DelayTimeAtDestination": 10
    },
    "Exeggutor": {
      "MaxDistance": 1500.0,
      "Priority": 1,
      "MaxWalkTimes": 600.0,
      "CatchPokemonWhileWalking": false,
      "SpinPokestopWhileWalking": true,
      "MaxSpeedUpSpeed": 60.0,
      "AllowSpeedUp": false,
      "DelayTimeAtDestination": 10
    },
    "Vaporeon": {
      "MaxDistance": 1800.0,
      "Priority": 2,
      "MaxWalkTimes": 800.0,
      "CatchPokemonWhileWalking": false,
      "SpinPokestopWhileWalking": false,
      "MaxSpeedUpSpeed": 60.0,
      "AllowSpeedUp": false,
      "DelayTimeAtDestination": 10
    },
    "Lickitung": {
      "MaxDistance": 1800.0,
      "Priority": 2,
      "MaxWalkTimes": 800.0,
      "CatchPokemonWhileWalking": false,
      "SpinPokestopWhileWalking": false,
      "MaxSpeedUpSpeed": 60.0,
      "AllowSpeedUp": false,
      "DelayTimeAtDestination": 10
    },
    "Flareon": {
      "MaxDistance": 1800.0,
      "Priority": 2,
      "MaxWalkTimes": 800.0,
      "CatchPokemonWhileWalking": false,
      "SpinPokestopWhileWalking": false,
      "MaxSpeedUpSpeed": 60.0,
      "AllowSpeedUp": false,
      "DelayTimeAtDestination": 10
    },
    "Scyther": {
      "MaxDistance": 1000.0,
      "Priority": 3,
      "MaxWalkTimes": 800.0,
      "CatchPokemonWhileWalking": false,
      "SpinPokestopWhileWalking": false,
      "MaxSpeedUpSpeed": 60.0,
      "AllowSpeedUp": false,
      "DelayTimeAtDestination": 10
    },
    "Beedrill": {
      "MaxDistance": 1000.0,
      "Priority": 3,
      "MaxWalkTimes": 800.0,
      "CatchPokemonWhileWalking": false,
      "SpinPokestopWhileWalking": false,
      "MaxSpeedUpSpeed": 60.0,
      "AllowSpeedUp": false,
      "DelayTimeAtDestination": 10
    },
    "Chansey": {
      "MaxDistance": 1500.0,
      "Priority": 2,
      "MaxWalkTimes": 800.0,
      "CatchPokemonWhileWalking": false,
      "SpinPokestopWhileWalking": false,
      "MaxSpeedUpSpeed": 60.0,
      "AllowSpeedUp": false,
      "DelayTimeAtDestination": 10
    },
    "Hitmonlee": {
      "MaxDistance": 1500.0,
      "Priority": 2,
      "MaxWalkTimes": 800.0,
      "CatchPokemonWhileWalking": false,
      "SpinPokestopWhileWalking": false,
      "MaxSpeedUpSpeed": 60.0,
      "AllowSpeedUp": false,
      "DelayTimeAtDestination": 10
    },
    "Machamp": {
      "MaxDistance": 1500.0,
      "Priority": 2,
      "MaxWalkTimes": 800.0,
      "CatchPokemonWhileWalking": false,
      "SpinPokestopWhileWalking": false,
      "MaxSpeedUpSpeed": 60.0,
      "AllowSpeedUp": false,
      "DelayTimeAtDestination": 10
    },
    "Ninetales": {
      "MaxDistance": 1500.0,
      "Priority": 2,
      "MaxWalkTimes": 800.0,
      "CatchPokemonWhileWalking": false,
      "SpinPokestopWhileWalking": false,
      "MaxSpeedUpSpeed": 60.0,
      "AllowSpeedUp": false,
      "DelayTimeAtDestination": 10
    },
    "Jolteon": {
      "MaxDistance": 1200.0,
      "Priority": 2,
      "MaxWalkTimes": 800.0,
      "CatchPokemonWhileWalking": false,
      "SpinPokestopWhileWalking": false,
      "MaxSpeedUpSpeed": 60.0,
      "AllowSpeedUp": false,
      "DelayTimeAtDestination": 10
    },
    "Poliwhirl": {
      "MaxDistance": 1200.0,
      "Priority": 2,
      "MaxWalkTimes": 800.0,
      "CatchPokemonWhileWalking": false,
      "SpinPokestopWhileWalking": false,
      "MaxSpeedUpSpeed": 60.0,
      "AllowSpeedUp": false,
      "DelayTimeAtDestination": 10
    },
    "Rapidash": {
      "MaxDistance": 1500.0,
      "Priority": 2,
      "MaxWalkTimes": 800.0,
      "CatchPokemonWhileWalking": false,
      "SpinPokestopWhileWalking": false,
      "MaxSpeedUpSpeed": 60.0,
      "AllowSpeedUp": false,
      "DelayTimeAtDestination": 10
    },
    "Cloyster": {
      "MaxDistance": 1200.0,
      "Priority": 2,
      "MaxWalkTimes": 800.0,
      "CatchPokemonWhileWalking": false,
      "SpinPokestopWhileWalking": false,
      "MaxSpeedUpSpeed": 60.0,
      "AllowSpeedUp": false,
      "DelayTimeAtDestination": 10
    },
    "Dodrio": {
      "MaxDistance": 1200.0,
      "Priority": 2,
      "MaxWalkTimes": 800.0,
      "CatchPokemonWhileWalking": false,
      "SpinPokestopWhileWalking": false,
      "MaxSpeedUpSpeed": 60.0,
      "AllowSpeedUp": false,
      "DelayTimeAtDestination": 10
    },
    "Clefable": {
      "MaxDistance": 1000.0,
      "Priority": 3,
      "MaxWalkTimes": 800.0,
      "CatchPokemonWhileWalking": false,
      "SpinPokestopWhileWalking": false,
      "MaxSpeedUpSpeed": 60.0,
      "AllowSpeedUp": false,
      "DelayTimeAtDestination": 10
    },
    "Golbat": {
      "MaxDistance": 200.0,
      "Priority": 6,
      "MaxWalkTimes": 800.0,
      "CatchPokemonWhileWalking": true,
      "SpinPokestopWhileWalking": true,
      "MaxSpeedUpSpeed": 60.0,
      "AllowSpeedUp": false,
      "DelayTimeAtDestination": 10
    },
    "Jynx": {
      "MaxDistance": 1200.0,
      "Priority": 4,
      "MaxWalkTimes": 800.0,
      "CatchPokemonWhileWalking": true,
      "SpinPokestopWhileWalking": true,
      "MaxSpeedUpSpeed": 60.0,
      "AllowSpeedUp": false,
      "DelayTimeAtDestination": 10
    },
    "Rhydon": {
      "MaxDistance": 1200.0,
      "Priority": 4,
      "MaxWalkTimes": 800.0,
      "CatchPokemonWhileWalking": true,
      "SpinPokestopWhileWalking": true,
      "MaxSpeedUpSpeed": 60.0,
      "AllowSpeedUp": false,
      "DelayTimeAtDestination": 10
    },
    "Kangaskhan": {
      "MaxDistance": 800.0,
      "Priority": 4,
      "MaxWalkTimes": 800.0,
      "CatchPokemonWhileWalking": true,
      "SpinPokestopWhileWalking": true,
      "MaxSpeedUpSpeed": 60.0,
      "AllowSpeedUp": false,
      "DelayTimeAtDestination": 10
    },
    "Wigglytuff": {
      "MaxDistance": 1250.0,
      "Priority": 4,
      "MaxWalkTimes": 800.0,
      "CatchPokemonWhileWalking": true,
      "SpinPokestopWhileWalking": true,
      "MaxSpeedUpSpeed": 60.0,
      "AllowSpeedUp": false,
      "DelayTimeAtDestination": 10
    },
    "Gyarados": {
      "MaxDistance": 1800.0,
      "Priority": 2,
      "MaxWalkTimes": 800.0,
      "CatchPokemonWhileWalking": false,
      "SpinPokestopWhileWalking": false,
      "MaxSpeedUpSpeed": 60.0,
      "AllowSpeedUp": false,
      "DelayTimeAtDestination": 10
    },
    "Dewgong": {
      "MaxDistance": 1800.0,
      "Priority": 2,
      "MaxWalkTimes": 800.0,
      "CatchPokemonWhileWalking": false,
      "SpinPokestopWhileWalking": false,
      "MaxSpeedUpSpeed": 60.0,
      "AllowSpeedUp": false,
      "DelayTimeAtDestination": 10
    },
    "Blastoise": {
      "MaxDistance": 3000.0,
      "Priority": 1,
      "MaxWalkTimes": 900.0,
      "CatchPokemonWhileWalking": false,
      "SpinPokestopWhileWalking": false,
      "MaxSpeedUpSpeed": 60.0,
      "AllowSpeedUp": true,
      "DelayTimeAtDestination": 10
    },
    "Venusaur": {
      "MaxDistance": 3000.0,
      "Priority": 1,
      "MaxWalkTimes": 900.0,
      "CatchPokemonWhileWalking": false,
      "SpinPokestopWhileWalking": false,
      "MaxSpeedUpSpeed": 60.0,
      "AllowSpeedUp": true,
      "DelayTimeAtDestination": 10
    },
    "Bulbasaur": {
      "MaxDistance": 500.0,
      "Priority": 3,
      "MaxWalkTimes": 300.0,
      "CatchPokemonWhileWalking": true,
      "SpinPokestopWhileWalking": true,
      "MaxSpeedUpSpeed": 60.0,
      "AllowSpeedUp": false,
      "DelayTimeAtDestination": 10
    },
    "Charmander": {
      "MaxDistance": 500.0,
      "Priority": 3,
      "MaxWalkTimes": 300.0,
      "CatchPokemonWhileWalking": true,
      "SpinPokestopWhileWalking": true,
      "MaxSpeedUpSpeed": 60.0,
      "AllowSpeedUp": false,
      "DelayTimeAtDestination": 10
    },
    "Squirtle": {
      "MaxDistance": 500.0,
      "Priority": 3,
      "MaxWalkTimes": 300.0,
      "CatchPokemonWhileWalking": true,
      "SpinPokestopWhileWalking": true,
      "MaxSpeedUpSpeed": 60.0,
      "AllowSpeedUp": false,
      "DelayTimeAtDestination": 10
    },
    "Omanyte": {
      "MaxDistance": 1500.0,
      "Priority": 3,
      "MaxWalkTimes": 300.0,
      "CatchPokemonWhileWalking": true,
      "SpinPokestopWhileWalking": true,
      "MaxSpeedUpSpeed": 60.0,
      "AllowSpeedUp": false,
      "DelayTimeAtDestination": 10
    },
    "Marowak": {
      "MaxDistance": 1500.0,
      "Priority": 3,
      "MaxWalkTimes": 300.0,
      "CatchPokemonWhileWalking": true,
      "SpinPokestopWhileWalking": true,
      "MaxSpeedUpSpeed": 60.0,
      "AllowSpeedUp": false,
      "DelayTimeAtDestination": 10
    },
    "Venomoth": {
      "MaxDistance": 1500.0,
      "Priority": 3,
      "MaxWalkTimes": 300.0,
      "CatchPokemonWhileWalking": true,
      "SpinPokestopWhileWalking": true,
      "MaxSpeedUpSpeed": 60.0,
      "AllowSpeedUp": false,
      "DelayTimeAtDestination": 10
    },
    "Vileplume": {
      "MaxDistance": 1500.0,
      "Priority": 3,
      "MaxWalkTimes": 300.0,
      "CatchPokemonWhileWalking": true,
      "SpinPokestopWhileWalking": true,
      "MaxSpeedUpSpeed": 60.0,
      "AllowSpeedUp": false,
      "DelayTimeAtDestination": 10
    }
  },
  "GymConfig": {
    "Enable": false,
    "MaxDistance": 1500.0,
    "DefaultTeam": "Yellow",
    "MaxCPToDeploy": 1000,
    "MaxLevelToDeploy": 16,
    "VisitTimeout": 60,
    "UseRandomPokemon": false,
    "NumberOfTopPokemonToBeExcluded": 10
  },
  "PokemonUpgradeFilters": {
    "Dratini": {
      "LevelUpByCPorIV": "iv",
      "UpgradePokemonCpMinimum": 600.0,
      "UpgradePokemonIvMinimum": 99.0,
      "UpgradePokemonMinimumStatsOperator": "or",
      "OnlyUpgradeFavorites": false
    }
  }
}

**Comment by ntatoo** [comment]
@petpetpetvm no , try the new config
