### ISSUE TITLE
(suggestion) select team

### ISSUE THREAD

**Issue by yohudood** [Necrobot-Private/NecroBot#84]
I did the tutorial with a new acc and he's just instinct gejoind team and I am not happy because all my other acc were I in team mystic.
Plz make an option to choose a team.

**Comment by ntatoo** [comment]
@yohudood , look at the config file
at the bottom you will see

"GymConfig": {
    "Enable": true,
    "MaxDistance": 1500.0,
    "DefaultTeam": "Yellow",<<< Change to Blue Or Red
    "MaxCPToDeploy": 1000,
    "MaxLevelToDeploy": 16,
    "VisitTimeout": 60,
    "UseRandomPokemon": false,
    "NumberOfTopPokemonToBeExcluded": 10
