### ISSUE TITLE
Bot pokestop and pokemon error

### ISSUE THREAD

**Issue by JamesLeopard** [Necrobot-Private/NecroBot#842]
Hello,

I have tried to log into the bot as usual. 

[16:36:03] (ATTENTION) No usable PokeStops found in your area. Is your maximum distance too small?
and 
[16:36:34] (PKMN) (CatchFlee) | (Normal) Weedle Lvl: 1 CP: (10/397) IV: 13.00% | Chance: 100% | 9.92m dist |  etc..

I have tried with a new alternative account..did the same thing. 
Config files are vaild, same one out of the zip file.  Maybe the API is blocked? or Niantic introduced some new bot detection mode?

Thanks in advance.

Version: v1.0.0.102

**Comment by hardknoxni69a** [comment]
please try using latest version as there has been some changes and the no usably stops just shows when map is loading but ATM bot is working amazin

**Comment by matheesan25** [comment]
happened to me again, and I'm using most updated version

**Comment by hardknoxni69a** [comment]
this happens when the bot loads to everyone no worries as bot loads as normal right after as u see u caught your weedle no worries my friend
