### ISSUE TITLE
2 steps verify snipe pokemon

### ISSUE THREAD

**Issue by samuraitruong** [Necrobot-Private/NecroBot#846]
Sometime unverified data isn't correct IV and Level, so we need add 1 option to verify 2nd step after encounter pokemon, if IV, Level, Move not match will filter, bot will ignore that pokemon 👍

**Comment by hardknoxni69a** [comment]
once its incorrect it reuploads correct data and deletes unspawned or incorrect info

**Comment by Lord-Haji** [comment]
Not applicable any more
