### ISSUE TITLE
Latest version .103 Internal Snipe Setting!?

### ISSUE THREAD

**Issue by halohalor** [Necrobot-Private/NecroBot#850]
Hello guys! How do I set the Internal Snipe setting filters?
I tried to change the sniping setting but the sniping setting keep on sniping pokemon not within my my IV range.

**Comment by hardknoxni69a** [comment]
please direct general questions to our discord but you need to set
  "SnipePokemonFilter": {
    "Lapras": {
      "SnipeIV": 85,
      "Moves": [],
      "Operator": "or",
      "VerifiedOnly": false,
      "Priority": 5,
      "AutoSnipeCandy": 200,
      "Level": 0,
      "AllowMultiAccountSnipe": false

**Comment by hardknoxni69a** [comment]
any pokemon in your snipe list will follow those rules or else it will snipe depending on your global setting of iv

**Comment by hardknoxni69a** [comment]
but a ton of snipers in our discord come on by youll love it we try to keep here for the bugs and stuff regular questions clog it up for the big devs

**Comment by halohalor** [comment]
no problem but i do not how to use discord. i am not sure I had already edit the config according to what u said. but after this update, all those common pokemon automatically skipped being catch and the INTERNALsnipe keep on sniping dragonite and etc below the IV filter I set.
