### ISSUE TITLE
Bug) Select Pokemon Now Make Entire Line White

### ISSUE THREAD

**Issue by hardknoxni69a** [Necrobot-Private/NecroBot#852]
Cant View Any Info When you click on pokemon info lines gets whited out

**Comment by jjskuld** [comment]
Confirmed new bug.. I think @samuraitruong was working on filtering code and broke something.

**Comment by jjskuld** [comment]
<img width="1011" alt="screen shot 2017-02-15 at 11 06 12 am" src="https://cloud.githubusercontent.com/assets/16908714/22990698/e3343234-f36e-11e6-9625-d8d51b2584fb.png">

**Comment by samuraitruong** [comment]
okay, the style overwrite of some WIP ticket make this issue, leave it to me

**Comment by samuraitruong** [comment]
fixed #864
