### ISSUE TITLE
Location

### ISSUE THREAD

**Issue by unknowkir** [Necrobot-Private/NecroBot#853]
i cant change my location.. always stays at central park ny

**Comment by Taweu** [comment]
Hi,

Sorry for my bad english, i'll try to make my best :)

I think you change the attribute DefaultLatitude and DefaultLongitude in Config/config.json, but when you start the bot, he saved your location (central park) in Config/LastPos.ini ...

You just have to edit your location in Config/LastPos.ini and it should be ok

**Comment by jjskuld** [comment]
Just change your location in config.json and delete LastPos.ini and restart.
