### ISSUE TITLE
Pokestops constantly out of range

### ISSUE THREAD

**Issue by jjskuld** [Necrobot-Private/NecroBot#860]
### Expected Behavior:
When traveling at higher speeds, pokestops are not spinnable, constantly getting out of range error presumably due to softban.
<img width="943" alt="screen shot 2017-02-15 at 8 08 13 pm" src="https://cloud.githubusercontent.com/assets/16908714/23007239/22325216-f3bc-11e6-91e7-0cd7143c83d3.png">

### Actual Behavior:
Regardless of travel speed, once you get to pokestop, should be able to spin pokestop after softban.

**Comment by samuraitruong** [comment]
ooh, look at this screenshoot and I think issue is
1. high sped
2. distance between 2 pokestop 2 far

combine this together, even we use poke++, we got lot of softban on poke++

solution : since reduce speed or farm at place have many pokestop

**Comment by jjskuld** [comment]
I think the latest changes i made help to resolve this.
