### ISSUE TITLE
buddy and egg problem

### ISSUE THREAD

**Issue by Riccardo75** [Necrobot-Private/NecroBot#862]
hello guys
few day,s ago a mentioned  that the egss dont count distance
the answer was  the gui doesnt count.
but when i switch back to the game in android, itss really not counting the km,s
the buddy and the eggs
i use the orriginal  config. 
im not the only one, more firends expiring this problem for the last 3 day,s

**Comment by hardknoxni69a** [comment]
the bot hatches eggs but niantic only counts distance every 4 minutes and the speed has to be under 10.5 plus the bot is stopping like every few feet for stops and catches so distance doesnt grow very much but it does count and if you adjust timers and delays and stuff u will get more distance but i hatch eggs everyday
