### ISSUE TITLE
[Request] Collect coin every 21 hours

### ISSUE THREAD

**Issue by baomx888** [Necrobot-Private/NecroBot#868]
Can we add a function to collect coin every 21 hours?   This way, I can save 3 hours every day and in seven days I will have one more collecting than collecting it manually.

**Comment by Wulfric2405** [comment]
dude is this thing gym battling for ya?

**Comment by baomx888** [comment]
No, I do not need to battle gym. I have 17 gym over level 9. so I just need to collect coin every 21 hours.

**Comment by RogueMaster** [comment]
This definitely would need to be multi-bot for it to work best... like a scheduled account switch for xyz account at a certain set date/time or as soon as it is opened after, and then it would work through taking over gyms to have X gyms before collecting if it doesn't already have that many pokemon deployed...

**Comment by hardknoxni69a** [comment]
going to merge to #1029
