### ISSUE TITLE
[Request] Favorite Pokemon base on both IV and Level

### ISSUE THREAD

**Issue by LSAC-Hao** [Necrobot-Private/NecroBot#869]
A lot of time we don't want to favorite a pokemon that is level 1.

**Comment by Danny-0815** [comment]
I agree - limiting favouring to CP, too, was a good start. But limiting it to a specific level would be even better!

**Comment by samuraitruong** [comment]
WIP

**Comment by SLASHLogin** [comment]
I think that's good idea but maybe do that with all three. Level, CP and IV. That's should work just like scrollbars in GUI "search".

**Comment by samuraitruong** [comment]
fixed in #882
