### ISSUE TITLE
BUG - Snipe not in pokedex sometime doesn't work properly

### ISSUE THREAD

**Issue by samuraitruong** [Necrobot-Private/NecroBot#871]
Maybe thread safe access make bot sometime add wrong pokemon not in dex to snipe list.

Need to fix it, or combine both pokedex & candy check

**Comment by hardknoxni69a** [comment]
was going to make a request for this YES the not in dex shows pokemon that you already have

**Comment by samuraitruong** [comment]
hope this fixed with #882, leave it open for monitoring
