### ISSUE TITLE
"bad authentication"

### ISSUE THREAD

**Issue by monti97** [Necrobot-Private/NecroBot#872]
Hi! i'm new on this forum and i have a question for you...why when I start the bot it say this? 
(username and password are correct):

Google returned an error message: 'BadAuthentication'
Google returned an error message: 'BadAuthentication'
Google returned an error message: 'BadAuthentication'
[21:39:27] (INFO) Connecting to ws://necrosocket.herokuapp.com/socket.io/?EIO=3&
transport=websocket ....
Google returned an error message: 'BadAuthentication'
Google returned an error message: 'BadAuthentication'
[21:41:14] (INFO) PokemonGo.RocketAPI.Exceptions.TokenRefreshException: Error re
freshing access token.
   in PokemonGo.RocketAPI.Rpc.Login.<Reauthenticate>d__9.MoveNext() in c:\projec
ts\necrobot2\FeroxRev\Rpc\Login.cs:riga 153
--- Fine traccia dello stack da posizione precedente dove Ã¨ stata generata l'ec
cezione ---
   in System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   in PokemonGo.RocketAPI.Rpc.Login.<GetValidAccessToken>d__6.MoveNext() in c:\p
rojects\necrobot2\FeroxRev\Rpc\Login.cs:riga 89
--- Fine traccia dello stack da posizione precedente dove Ã¨ stata generata l'ec
cezione ---
   in System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   in PokemonGo.RocketAPI.Helpers.RequestBuilder.<GetRequestEnvelope>d__14.MoveN
ext() in c:\projects\necrobot2\FeroxRev\Helpers\RequestBuilder.cs:riga 286
--- Fine traccia dello stack da posizione precedente dove Ã¨ stata generata l'ec
cezione ---
   in System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   in PokemonGo.RocketAPI.Rpc.Player.<GetPlayer>d__9.MoveNext() in c:\projects\n
ecrobot2\FeroxRev\Rpc\Player.cs:riga 140
--- Fine traccia dello stack da posizione precedente dove Ã¨ stata generata l'ec
cezione ---
   in System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   in PokemonGo.RocketAPI.Rpc.Login.<DoLogin>d__10.MoveNext() in c:\projects\nec
robot2\FeroxRev\Rpc\Login.cs:riga 170
--- Fine traccia dello stack da posizione precedente dove Ã¨ stata generata l'ec
cezione ---
   in System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   in System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   in PoGo.NecroBot.Logic.State.LoginState.<Execute>d__3.MoveNext() in c:\projec
ts\necrobot2\PoGo.NecroBot.Logic\State\LoginState.cs:riga 50
[21:41:35] (INFO) Login tramite Google
Google returned an error message: 'BadAuthentication'
Google returned an error message: 'BadAuthentication'
Google returned an error message: 'BadAuthentication'
Google returned an error message: 'BadAuthentication'
Google returned an error message: 'BadAuthentication'
[21:42:54] (INFO) PokemonGo.RocketAPI.Exceptions.TokenRefreshException: Error re
freshing access token.
   in PokemonGo.RocketAPI.Rpc.Login.<Reauthenticate>d__9.MoveNext() in c:\projec
ts\necrobot2\FeroxRev\Rpc\Login.cs:riga 153
--- Fine traccia dello stack da posizione precedente dove Ã¨ stata generata l'ec
cezione ---
   in System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   in PokemonGo.RocketAPI.Rpc.Login.<GetValidAccessToken>d__6.MoveNext() in c:\p
rojects\necrobot2\FeroxRev\Rpc\Login.cs:riga 89
--- Fine traccia dello stack da posizione precedente dove Ã¨ stata generata l'ec
cezione ---
   in System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   in PokemonGo.RocketAPI.Helpers.RequestBuilder.<GetRequestEnvelope>d__14.MoveN
ext() in c:\projects\necrobot2\FeroxRev\Helpers\RequestBuilder.cs:riga 286
--- Fine traccia dello stack da posizione precedente dove Ã¨ stata generata l'ec
cezione ---
   in System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   in PokemonGo.RocketAPI.Rpc.Player.<GetPlayer>d__9.MoveNext() in c:\projects\n
ecrobot2\FeroxRev\Rpc\Player.cs:riga 140
--- Fine traccia dello stack da posizione precedente dove Ã¨ stata generata l'ec
cezione ---
   in System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   in PokemonGo.RocketAPI.Rpc.Login.<DoLogin>d__10.MoveNext() in c:\projects\nec
robot2\FeroxRev\Rpc\Login.cs:riga 170
--- Fine traccia dello stack da posizione precedente dove Ã¨ stata generata l'ec
cezione ---
   in System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   in System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   in PoGo.NecroBot.Logic.State.LoginState.<Execute>d__3.MoveNext() in c:\projec
ts\necrobot2\PoGo.NecroBot.Logic\State\LoginState.cs:riga 50
[21:43:14] (INFO) Login tramite Google
Google returned an error message: 'BadAuthentication'
Google returned an error message: 'BadAuthentication'
Google returned an error message: 'BadAuthentication'
Google returned an error message: 'BadAuthentication'
Google returned an error message: 'BadAuthentication'

**Comment by samuraitruong** [comment]
check if you password correct, login in browser before use bot

**Comment by monti97** [comment]
I updated the comment

**Comment by elmoo568** [comment]
I got this error when I changed my google password. If that's what happened to you, you need to update your password in auth.json and also delete accounts.db file.  If you don't delete it, I think it saves your password even if you change it in auth.json.

**Comment by monti97** [comment]
I haven't changed my password recently...if i did this it was a long time ago...

**Comment by hardknoxni69a** [comment]
u probably have 2 step verification on in google

**Comment by monti97** [comment]
no it's disabled

**Comment by hmthatsweird** [comment]
I'm having the same issue and I have made sure that my login is correct... still just continues to say Bad Authentication

**Comment by RoskamiesX** [comment]
Did you delete accounts.db file? @hmthatsweird

**Comment by hardknoxni69a** [comment]
ur gonna need to set up a private password for necro access but its the way google verifies try toggling your settings make sure to allow less secure apps and should be good to go

**Comment by hardknoxni69a** [comment]
Also try changing ur Google password and then u can put it back it's on
Google's end not ours because simply changing password or adjusting 2 step
works Google like blocks it for some reason so it of people make app
specific passwords too and that always works
