### ISSUE TITLE
API Error

### ISSUE THREAD

**Issue by gatesjr** [Necrobot-Private/NecroBot#873]
is anyone getting this error as well and do i just need to wait for updated version 

[18:03:04] (ERROR) (KILLSWITCH) We have detected a Pokemon API change. The bot emulates API version 0.55.0, which is no longer supported.  Minimum API version is now 0.57.2.
[18:03:04] (INFO) The bot will now exit after hitting the enter key.

**Comment by pokkemonner** [comment]
Yes. Patience. Zennnn.

**Comment by gatesjr** [comment]
ahh ok thanks bro was just wondering if it was the APIkey i needed to change ok cool

**Comment by pokkemonner** [comment]
Update your mobile. I see a new range of Johto type pokemon to catch.

**Comment by gatesjr** [comment]
yes i did do the update

**Comment by gatesjr** [comment]
haha, the server is going crazy right now took me 2 monutes to load up the app, and the pokemon are taking forever to pull up after clicking on them

**Comment by jjskuld** [comment]
Looks like 0.57 is being forced now!

**Comment by firies1** [comment]
as we know, we have to wait. until further notice

**Comment by noelesther** [comment]
i'm waiting update, too
plz fiexd it :)
