### ISSUE TITLE
execution error

### ISSUE THREAD

**Issue by wjdaudghks** [Necrobot-Private/NecroBot#875]
12:14:16] () 
//================================================================//
                POKEMON GO 0.57.2
//================================================================//
The API is being forced to 0.57.2. Please stop botting if you care about your account!
//================================================================//
                         Updated: 2/16/2017

For support/questions:
OFFICIAL NECROBOT2 Discord: https://discord.gg/7FWyWVp

[12:14:16] () Do you want to override killswitch to bot at your own risk? Y/N

silhaeng olyuga balsaenghabnida. eotteohgehaeyahabnikka?

**Comment by hardknoxni69a** [comment]
api has been forced please wait for update and you can use your hash key again its being worked in should be set within 24 hours
