### ISSUE TITLE
when accessing Google Elevation Service API: REQUEST_DENIED

### ISSUE THREAD

**Issue by tr1p0z** [Necrobot-Private/NecroBot#88]
I'm getting this error every 10 seconds
[12:33:42] (ATTENTION) [REPLY] when accessing Google Elevation Service API: REQUEST_DENIED

**Comment by iwean** [comment]
Get the key >> https://developers.google.com/maps/documentation/elevation/start#get-a-key
Enable it
Paste the key to your config.json

**Comment by tr1p0z** [comment]
It's done

**Comment by FureszOszkar** [comment]
New Key, the problem is same...(ATTENTION) [REPLY] when accessing Google Elevation Service API: REQUEST_DENIED

**Comment by iwean** [comment]
@tr1p0z 
Go to: https://console.developers.google.com/apis/library
see "Google Maps APIs" select "Google Maps Android API " in top panel, select "ENABLE"

open tab "Library" in left panel see "Google Maps APIs" and select "More"
select "Google Maps Elevation API" in top panel, select "ENABLE" ....wait 5 - 10

seconds .. if not working, open "Credentials" in left panel select your project and make sure you only have one API key for your google account

**Comment by Pinha** [comment]
@iwean , thanks for this solution bro!

**Comment by iwean** [comment]
@Pinha You're welcome :smiley:

**Comment by tr1p0z** [comment]
@iwean Thanks for all, it's working now

**Comment by LobsterX** [comment]
![mapquest elevation error 1](https://cloud.githubusercontent.com/assets/21141430/18435775/b3cb2956-7927-11e6-9b92-f2bf35680f46.png)

**Comment by mjusuf** [comment]
@iwean thanks

**Comment by wilsondgonzales** [comment]
I have the same problem as @LobsterX . API's are enabled and with a key. The key is in the config but still stuck with the no elevation data prompt :/

**Comment by jjskuld** [comment]
It probably means that you've exceeded the Google Elevation API limits (2500 req. / day). So it falls back on the next available service, which is MapQuest.  MapQuest is not as reliable... 

Going forward we will add Mapzen Elevation, which has no limits when used with a key.

**Comment by mrsell545** [comment]
I never needed to use the Api key in noxx dev version, so even if I use it I would have a 2500 request limit? That will be lot of extra work to run 10+bots :(
