### ISSUE TITLE
Update use berries logic and config

### ISSUE THREAD

**Issue by samuraitruong** [Necrobot-Private/NecroBot#888]
Need to learn the best practice of using new berries type and make config to make bot work better with new update

**Comment by hardknoxni69a** [comment]
recycle logic should probably be done first then can work to implement use

**Comment by hardknoxni69a** [comment]
i was thinking user can set list for with pokemon uses pinap berry/ the berries that awars extra candy
\

**Comment by SLASHLogin** [comment]
"Give a Pokémon a Nanab Berry to slow its movements, making it easier to catch. Or give it a Pinap Berry to double the amount of Candy you'll receive if your next catch attempt succeeds." - pokemon.com

**Comment by samuraitruong** [comment]
thought i will come update with the master setting like this 
[
"Berry Name" : {
Pokemons : [Dragonite,xx,xx,xx]
MinIV: 100,
MinCP:400,
MinLevel: 20,
Operator: and,
CatchChance : 0.1
}
]

By this design we can have super bower config compare to the very simple now. comment here what you thinking

**Comment by samuraitruong** [comment]
move to WIP

**Comment by samuraitruong** [comment]
#906
