### ISSUE TITLE
set GymConfig...?

### ISSUE THREAD

**Issue by zsatanxz** [Necrobot-Private/NecroBot#89]
i,m team Blue set GymConfig ...?

  "GymConfig": {
    "Enable": true,
    "MaxDistance": 1500.0,
    "DefaultTeam": "Yellow",
    "MaxCPToDeploy": 1000,
    "MaxLevelToDeploy": 16,
    "VisitTimeout": 60,
    "UseRandomPokemon": false,
    "NumberOfTopPokemonToBeExcluded": 10
  },

**Comment by iwean** [comment]
Nevermind... it's only for default if you run the bot from fresh account and never set the team.
If you set it before... it's no effect.

**Comment by teos81** [comment]
If you run bot from fresh and don't change the value yuo will become a Yellow Team member!!!

But i think zsatanxz is different.. How to set the confing? Could you make a litte wiki for the new parameters?? I have set the color to "Blue" it look like to work..
