### ISSUE TITLE
how to configure this IV

### ISSUE THREAD

**Issue by saldotman** [Necrobot-Private/NecroBot#893]
"RenamePokemon": true,
    "RenameOnlyAboveIv": true,

how to set the IV for renaming purpose?

**Comment by hardknoxni69a** [comment]
whatever your keepminiv will be renamed

**Comment by hardknoxni69a** [comment]
if you have keepminiv set to 80 then all pokemon above 80 will be renamed

**Comment by saldotman** [comment]
so, the IV setting is shared with the keepminiv to keep the number of poke?
