### ISSUE TITLE
error evolve

### ISSUE THREAD

**Issue by saldotman** [Necrobot-Private/NecroBot#895]
[03:11:53] (EVOLVED) Failed Sunkern. Result was FailedPokemonCannotEvolve, stopping evolving Sunkern

not sure why.

**Comment by samuraitruong** [comment]
there some new rules change in evolve, we need to learn it and fix the bot

**Comment by saldotman** [comment]
they use special items now.
just evolve porygon to porygon 2, using special item, manually (on device)

**Comment by samuraitruong** [comment]
we added evolve setting to fix for gen2, thought it should work now, please re-open if not work for you, don't foget put more details
