### ISSUE TITLE
Display API Status & Stats on window gui

### ISSUE THREAD

**Issue by samuraitruong** [Necrobot-Private/NecroBot#896]
Best place maybe in status bar

**Comment by hardknoxni69a** [comment]
is is good idea and i mean we are already displaying api info in the console so have it updated in bar might be a little

**Comment by samuraitruong** [comment]
https://github.com/Necrobot-Private/NecroBot/pull/1131

**Comment by hardknoxni69a** [comment]
Amazing work lately banging out the updates truong omw to bank gonna send a
little something something your way
