### ISSUE TITLE
PokemonsToIgnore Not Working

### ISSUE THREAD

**Issue by pogofficial** [Necrobot-Private/NecroBot#898]
PokemonsToIgnore does not ignore pokemon, Only tested with NOT sniped. 
Using NecroBot2 v1.0.0.109 WIN version.
 
 "PokemonsToIgnore": [
    "pidgey",
    "rattata",
    "spearow"
  ],

**Comment by samuraitruong** [comment]
Do you mean that theyt are still being sniped?

**Comment by pogofficial** [comment]
No normal pokemon too still catches rattata and pidgey. 
Is there another sitting which could overwrite the ignore prehaps ?

**Comment by hardknoxni69a** [comment]
rather than using pokemonstoignore i would recommended using     "UsePokemonSniperFilterOnly": true, and set the pokemon you want to catch and it will only catch those pokemon it works amazing let me know how you like it not sure if the pokemonstoignore is still being used
