### ISSUE TITLE
Bot not collecting at pokestops.

### ISSUE THREAD

**Issue by ajns73** [Necrobot-Private/NecroBot#90]
Not really sure why this got closed. Behavior is still observable in current version (and always was) v0.9.8.7. There have been no intervening updates to my knowledge since this was last observable. Behavior is still observable on my end. 

![image](https://cloud.githubusercontent.com/assets/21206609/18435556/9d1a9318-78b9-11e6-8d62-8e888713b4bd.png)

**Comment by iwean** [comment]
It's something to avoid false softban perhaps.... so never spin if pokestop has been visited.
Got to ask to @samuraitruong....

**Comment by iwean** [comment]
Btw @ajns73 
I change my MaxDistance at Gym config to 220, and never get that issue again.

**Comment by ajns73** [comment]
@iwean Yeah, I should have posted what I have tried too.

MaxDistance at 150 and 0. Still happens.
Disable Gym logic. Still happens.
Set all SpinPokestopWhileWalking to true. Still happens.

**Comment by iwean** [comment]
Try disable HumanWalkSnipe

**Comment by ajns73** [comment]
ok. Done. We'll see in 10 minutes

**Comment by ajns73** [comment]
![image](https://cloud.githubusercontent.com/assets/21206609/18436457/0b74f7aa-78be-11e6-8626-da1139479993.png)

Say what? That's with HumanWalkSnipe set to false. You see it is already starting to skip, but how does the walk sniper engage when I set it o false?

**Comment by BoydTM** [comment]
in my case it happen just after: 'Current Operation was canceled' so it may be something on niantic side ...

**Comment by BoydTM** [comment]
2 restarts without any config changes and it works again ... weird

**Comment by iwean** [comment]
Maybe should wait till @samuraitruong see this...
He updated it with something I belive to avoid false sofban.

**Comment by ajns73** [comment]
bot off for now. Let's see what the big boys make of this.

**Comment by samuraitruong** [comment]
what pokestop? all that are gym. I have no issue , you should check your config

**Comment by ajns73** [comment]
Those are not all gyms. I know for a fact. I live there.

**Comment by samuraitruong** [comment]
Can you change to necro route. TO later tonight to check that issue. will have a look later tomorow.

**Comment by zigwyn** [comment]
try to change your location, I have the same issue and resolved by change the location.

**Comment by huynhdtanh** [comment]
"GymConfig": {
    "Enable": false,
    "MaxDistance": 1500.0,
    "DefaultTeam": "Yellow",
    "MaxCPToDeploy": 1000,
    "MaxLevelToDeploy": 16,
    "VisitTimeout": 60,
    "UseRandomPokemon": false,
    "NumberOfTopPokemonToBeExcluded": 10
  },

this's my config ...

**Comment by erickerich** [comment]
same here.
while this happen, bot atcually stuck in a small area. it seems lost direction, just round trip between this pokestop, but didn't collect anything.
 I must delete LastPos.ini and rerun the bot to make it back to normal.

![stuck](https://cloud.githubusercontent.com/assets/21130145/18440727/ce74bdde-793c-11e6-924b-c6d1e6081cb5.JPG)

**Comment by ajns73** [comment]
@erickerich Same behavior here. 
@huynhdtanh I had a similar config and the bot was still WalkSniping
@zigwyn I'd rather wait for a fix or work arourd to keep my bot where it is.
@samuraitruong No problem. I shut the bot down for now and I'll wait for something new.

**Comment by huynhdtanh** [comment]
@ajns73: mine's still good ...

![untitled453](https://cloud.githubusercontent.com/assets/22152140/18442221/2613d460-793a-11e6-8714-a5919fe01a7f.jpg)

**Comment by ajns73** [comment]
Just for clarification. Restarted the bot and it starts skipping again almost immediately. This rules out visiting stops before they "reset." Seems to confirm going to stop, not spinning it, and walking away. Also appears to now be looting stops it isn't walking to. That is, Traveling to Pokestop A.....(POKESTOP) Name: Pokestop B. Pokestop B is across town so it can't be a situation of looting an intervening stop. It never loots A is moves on to another one.

**Comment by hardknoxni69a** [comment]
Sorry what gui is that?

**Comment by wilsondgonzales** [comment]
looks like javanhawk

**Comment by huynhdtanh** [comment]
@hardknoxni69a  yes, javanhawk

**Comment by samuraitruong** [comment]
found that issue, it because you already visit that in the past > 5 min before. 

if (pokeStop.CooldownCompleteTimestampMs != 0) return;

this code need change to 

if (pokeStop.CooldownCompleteTimestampMs < datetime.UTCNow.ToUnixTime() ) return;

**Comment by ajns73** [comment]
@samuraitruong This seems logical and if the timezone offset is great enough, it would explain why this behavior persists for hours.
