### ISSUE TITLE
Allow all bot snipe on WIN GUI

### ISSUE THREAD

**Issue by samuraitruong** [Necrobot-Private/NecroBot#900]
for manual snipe only, every time user snipe 1 pokemon, that pokemon will be caught by all running bot

**Comment by hardknoxni69a** [comment]
similar to bots with same telegram command thats what i use when i want them all to have same

**Comment by samuraitruong** [comment]
it is working if you using web snipe now, just make the same feature for win gui

**Comment by samuraitruong** [comment]
#882
