### ISSUE TITLE
switch loop when switching account manually 

### ISSUE THREAD

**Issue by zuklio** [Necrobot-Private/NecroBot#908]
When switching account manually by clicking accounts tab in necrobot.win, the bot switched correctly but after catching 1 pokemon he switches in a loop and does not stop the switching request. 

### Expected Behavior:
switch to the selected account one time

### Actual Behavior:
switch in a loop like this:

[11:35:50] (ATTENTION) Switch account requested by user
[11:36:08] (ATTENTION) Switch account requested by user
[11:37:10] (ATTENTION) Switch account requested by user

And this goes on and on and does not stop. Maybe this is related with time log issue #829.

Version: 109 but also previous versions.

**Comment by samuraitruong** [comment]
https://github.com/Necrobot-Private/NecroBot/pull/909 fixed
