### ISSUE TITLE
MaxTravelDistanceInMeters bug

### ISSUE THREAD

**Issue by HokoriXIII** [Necrobot-Private/NecroBot#91]
### Expected Behavior:

Bot must go back to the starting point / not to leave a specified radius
### Actual Behavior:

Bot continues to farm pokestop farther away from the predetermined point. At the moment, more than 4km away.
### Your config.json:

```
    "MaxTravelDistanceInMeters": 2000

```
### Detailed Steps to Reproduce:

Play for several hours

**Comment by tws101** [comment]
Did you at any time close the bot, and start it again with an active last position file?

That may have altered your starting point to the new starting point....

However even if that is the case, I hope they tether the max distance to the coordinates in the config and not in the last position.

**Comment by kalamera** [comment]
imho the "MaxTravelDistanceInMeters" is distance between two pokestops.
never worked for me as described in the original wiki :)

**Comment by tws101** [comment]
kalamera,

Oh my understanding is max radius from your start point.....

**Comment by HokoriXIII** [comment]
I`m starting it and leaving for 5-6 hours. According to GUI it goes somewhere far far away from start.

**Comment by jjskuld** [comment]
I think the intention is max distance from start point.  But this setting only seems to be checked at beginning of the farming loop. Definitely looks like a bug.

Do you have sniping on (manual or human)?  These could definitely affect your position because bot instead of following farming loop goes off to do sniping.

**Comment by HokoriXIII** [comment]
Just for testing run bot for 30mins. Just using gyms and pokestops caused to walk for more than I`ve set

**Comment by kalamera** [comment]
well I have started using the GPX pathing long time ago as the "MaxTravelDistanceInMeters" never worked well for me ;)

**Comment by Aras84** [comment]
Hmmm the bot continues to wander off the longer you leave it...to the point that it missed the intended nest entirely...tried changing the maxdistance but behaving the same. Definitely a bug somewhere. I am using the latest release (fresh install)

**Comment by ComputerApp1234** [comment]
If you are using the human sniper, change "IncludeDefaultLocation" to true. This solved the problem for me.

**Comment by sheang** [comment]
I have similar problem here, my bot cannot walk back to default position after humanwalksnipe a pokemon?
"HumanWalkSnipeConfig": {
    "Enable": true,
    "DisplayPokemonList": true,
    "MaxDistance": 250.0,
    "MaxEstimateTime": 900.0,
    "CatchEmAllMinBalls": 20,
    "TryCatchEmAll": true,
    "CatchPokemonWhileWalking": true,
    "SpinWhileWalking": true,
    "AlwaysWalkback": true,
    "SnipingScanOffset": 0.025,
    "WalkbackDistanceLimit": 800.0,
    "IncludeDefaultLocation": true,
    "UseSnipePokemonList": true,
    "MaxSpeedUpSpeed": 60.0,
    "AllowSpeedUp": true,
    "DelayTimeAtDestination": 10000,
    "UsePokeRadar": true,
    "UseSkiplagged": true,
    "UsePokecrew": true,
    "UsePokesnipers": true,
    "UsePokeZZ": true,
    "UsePokeWatcher": true,
    "UseFastPokemap": true,
    "UsePogoLocationFeeder": false
I try to set   "WalkbackDistanceLimit": 9999.0, but the result still same

**Comment by sheang** [comment]
by the way,  I already set "IncludeDefaultLocation" to true

**Comment by jjskuld** [comment]
There is a danger with being tethered to your starting point.  Your bot makes patterns like this:

![unnatural](https://cloud.githubusercontent.com/assets/16908714/18809107/35c3cba2-8229-11e6-92f6-e52d922effb7.png)

Right now, although it's a bug to not be respecting the MaxTravelDistanceInMeters setting, your bot behavior is a lot more human like.

**Comment by jjskuld** [comment]
This is fixed now
