### ISSUE TITLE
softban config / multible bot config

### ISSUE THREAD

**Issue by jokki89** [Necrobot-Private/NecroBot#910]
Hello together :)

I've a question.
Is there someone who can explain how the softban config and multible bot config works?

And whats the best settings for it?
I know just when you're softabaned you have to spin 40 times a poke stop but how do I set it in my config?

This are my actually settings: (this are still the standard settings from necrobot)

"SoftBanConfig": {
    "FastSoftBanBypass": false,
    "ByPassSpinCount": 1
  },

  "MultipleBotConfig": {
    "RuntimeSwitch": 55,
    "OnLimitPauseTimes": 15,
    "OnRarePokemon": true,
    "MinIVToSwitch": 90.0,
    "EXPSwitch": 25000,
    "PokestopSwitch": 500,
    "PokemonSwitch": 200,
    "PokemonPerHourSwitch": 100,
    "StartFromDefaultLocation": true,
    "PokestopSoftbanCount": 5,
    "DisplayList": true,
    "SelectAccountOnStartUp": false,
    "CatchFleeCount": 5,
    "SwitchOnCatchLimit": true,
    "SwitchOnPokestopLimit": true
  },

**Comment by samuraitruong** [comment]
"ByPassSpinCount": 45
 is the best setting but it just wast time on multi account
check http://necrobot2.com/auth.json/2017/01/07/multi-account-config/  for multibot details
