### ISSUE TITLE
config setting description.

### ISSUE THREAD

**Issue by max6061** [Necrobot-Private/NecroBot#913]
Excuse me.
How can I find the config setting description?

**Comment by zuklio** [comment]
https://github.com/Necrobot-Private/NecroBot/wiki/config.json

**Comment by samuraitruong** [comment]
in window gui, if you hover on any config, you will see description message text 
![image](https://cloud.githubusercontent.com/assets/1183138/23096822/d002d8b6-f678-11e6-90a7-360df575b3a2.png)
necrobot2.com has few initial document there
