### ISSUE TITLE
Sniping problem.

### ISSUE THREAD

**Issue by ricardojulio** [Necrobot-Private/NecroBot#914]
Version: 1.0.0.0.111
Windows Version: Windows 10

After the version .111 my snipe list is always blank.
![poke](https://cloud.githubusercontent.com/assets/21310656/23094472/49697198-f5d8-11e6-9df4-5cae73ddb4d5.png)

**Comment by samuraitruong** [comment]
check your config, this work definitely work,  your IP maybe block to access snipe as well
