### ISSUE TITLE
Where do i find my config.json for Web GUI

### ISSUE THREAD

**Issue by CDAGaming** [Necrobot-Private/NecroBot#915]
When i use the WebGUI, there are some issues like i cant open the Bot Config. I read in PokeEase that i need to find Config/config.json but that folder doesnt exist in the zip file for newest release.

**Comment by SLASHLogin** [comment]
You have to run bot for the first time and this folder with config.json appears after first launch. You have to unpack zip first and then run exe

**Comment by CDAGaming** [comment]
WebGUI wouldnt create config.json even after multiple launches. Copying & Pasting Config directory with config.json fixed it.

**Comment by CDAGaming** [comment]
Now it seems i have infinite load screens on almost all screens, as well as blank console

**Comment by CDAGaming** [comment]
Anddddd...Now it won't load after restarting it, and a ton of new files in config folder

**Comment by SLASHLogin** [comment]
I don't know what have you done but download it again

**Comment by CDAGaming** [comment]
This has happened once a month ago and then today both from clean downloads

**Comment by CDAGaming** [comment]
Just Redownloaded and launched anew...config folder and config.json not generating

**Comment by zuklio** [comment]
Maybe try necrobot.win. This Gui is very good

**Comment by CDAGaming** [comment]
@zuklio Yup, that gui works fine for me, thanks :D

PS Some of the devs both at PokeEase & Necrobot may wanna consider either fixing their GUI or removing it. Gonna test this more then closing issue

**Comment by CDAGaming** [comment]
I should also note there hasnt been any issues using 0.45 api, and It even catches Gen 2 Pokemon on the 1st or 2nd time. I wouldnt bother with buying an api key, unless there is some big difference im missing

**Comment by hardknoxni69a** [comment]
API=Not ebing flagged by niantic i feel they let us use it get comfortable and once everyone has ranked up and invested then BAN up to you ultimately alot of people play and dont care about the accounts so free is good but if you want to keep it longterm better to be safe lets be serious its only 4$ Cash in your cans for month and itll pay for it but the webGUI is to work with you CLI installation there is no config for PokeEase GUI to load if you havent loaded necrobot2.exe or Necrobot2.Win.exe your config will be loaded in the config folder that your exe is in
