### ISSUE TITLE
Bug after some time of botting

### ISSUE THREAD

**Issue by SLASHLogin** [Necrobot-Private/NecroBot#916]
[20:16:35] (BŁĄD) Pokemon Servers might be offline / unstable. Trying again...
[20:16:35] (BŁĄD) Error: System.AggregateException: Wystąpił przynajmniej jeden błąd. ---> PokemonGo.RocketAPI.Exceptions.InvalidResponseException: Error with API request type: GetGymDetails
   w PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProtoPayload>d__0`1.MoveNext() w c:\projects\necrobot2\FeroxRev\Extensions\HttpClientExtensions.cs:wiersz 49
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w PokemonGo.RocketAPI.Rpc.BaseRpc.<PostProtoPayload>d__11`1.MoveNext() w c:\projects\necrobot2\FeroxRev\Rpc\BaseRpc.cs:wiersz 130
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w PokemonGo.RocketAPI.Rpc.BaseRpc.<PostProtoPayload>d__10`8.MoveNext() w c:\projects\necrobot2\FeroxRev\Rpc\BaseRpc.cs:wiersz 119
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w PokemonGo.RocketAPI.Rpc.Fort.<GetGymDetails>d__7.MoveNext() w c:\projects\necrobot2\FeroxRev\Rpc\Fort.cs:wiersz 266
   --- Koniec śladu stosu wyjątków wewnętrznych ---
   w System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   w System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   w PoGo.NecroBot.Logic.State.CachedGymGetails.LoadData(ISession session, FortData fort) w c:\projects\necrobot2\PoGo.NecroBot.Logic\State\GymTeamState.cs:wiersz 272
   w PoGo.NecroBot.Logic.State.GymTeamState.getGymDetails(ISession session, FortData fort, Boolean force) w c:\projects\necrobot2\PoGo.NecroBot.Logic\State\GymTeamState.cs:wiersz 92
   w PoGo.NecroBot.Logic.Tasks.UseGymBattleTask.CanDeployToGym(ISession session, FortData fort, IEnumerable`1 deployedPokemons) w c:\projects\necrobot2\PoGo.NecroBot.Logic\Tasks\UseGymBattleTask.cs:wiersz 1309
   w PoGo.NecroBot.Logic.Tasks.UseNearbyPokestopsTask.<>c__DisplayClass13_0.<GetNextPokeStop>b__2(FortData f) w c:\projects\necrobot2\PoGo.NecroBot.Logic\Tasks\UseNearbyPokestopsTask.cs:wiersz 202
   w System.Linq.Enumerable.<>c__DisplayClass6_0`1.<CombinePredicates>b__0(TSource x)
   w System.Linq.Enumerable.WhereListIterator`1.MoveNext()
   w System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   w System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   w PoGo.NecroBot.Logic.Tasks.UseNearbyPokestopsTask.<GetNextPokeStop>d__13.MoveNext() w c:\projects\necrobot2\PoGo.NecroBot.Logic\Tasks\UseNearbyPokestopsTask.cs:wiersz 200
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   w PoGo.NecroBot.Logic.Tasks.UseNearbyPokestopsTask.<Execute>d__8.MoveNext() w c:\projects\necrobot2\PoGo.NecroBot.Logic\Tasks\UseNearbyPokestopsTask.cs:wiersz 88
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w PoGo.NecroBot.Logic.Tasks.FarmPokestopsTask.<Execute>d__1.MoveNext() w c:\projects\necrobot2\PoGo.NecroBot.Logic\Tasks\FarmPokestopsTask.cs:wiersz 60
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   w PoGo.NecroBot.Logic.State.FarmState.<Execute>d__0.MoveNext() w c:\projects\necrobot2\PoGo.NecroBot.Logic\State\FarmState.cs:wiersz 54
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   w PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext() w c:\projects\necrobot2\PoGo.NecroBot.Logic\State\StateMachine.cs:wiersz 100
---> (Wyjątek wewnętrzny #0) PokemonGo.RocketAPI.Exceptions.InvalidResponseException: Error with API request type: GetGymDetails
   w PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProtoPayload>d__0`1.MoveNext() w c:\projects\necrobot2\FeroxRev\Extensions\HttpClientExtensions.cs:wiersz 49
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w PokemonGo.RocketAPI.Rpc.BaseRpc.<PostProtoPayload>d__11`1.MoveNext() w c:\projects\necrobot2\FeroxRev\Rpc\BaseRpc.cs:wiersz 130
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w PokemonGo.RocketAPI.Rpc.BaseRpc.<PostProtoPayload>d__10`8.MoveNext() w c:\projects\necrobot2\FeroxRev\Rpc\BaseRpc.cs:wiersz 119
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w PokemonGo.RocketAPI.Rpc.Fort.<GetGymDetails>d__7.MoveNext() w c:\projects\necrobot2\FeroxRev\Rpc\Fort.cs:wiersz 266<---

**Comment by hardknoxni69a** [comment]
please attach english logs for referencing as most common language ATM please

**Comment by SLASHLogin** [comment]
[16:51:38] (BŁĄD) Bad Request - If you see this message please copy error log & screenshot send back to dev asap.
[16:51:38] (BŁĄD) BAD REQUEST
{"StatusCode":2,"RequestId":1187262414,"Requests":[{"RequestType":103,"RequestMessage":[9,235,119,0,26,166,165,234,184,16,1,25,31,133,235,81,184,30,253,63,34,11,56,56,50,98,51,52,98,52,101,56,102,40,1,49,0,0,0,0,0,0,240,63,57,0,0,0,0,0,0,240,63]},{"RequestType":600,"RequestMessage":[]},{"RequestType":126,"RequestMessage":[]},{"RequestType":4,"RequestMessage":[8,206,150,227,225,165,43]},{"RequestType":129,"RequestMessage":[]},{"RequestType":5,"RequestMessage":[10,40,100,52,100,101,101,101,51,51,54,56,52,102,49,55,53,97,99,98,54,52,51,53,54,54,97,56,98,51,101,56,101,56,101,97,98,102,52,97,98,101]},{"RequestType":153,"RequestMessage":[]}],"PlatformRequests":[{"Type":6,"RequestMessage":[10,133,4,92,47,109,215,156,165,215,217,220,85,164,93,141,128,106,9,205,231,74,34,43,20,19,20,226,126,50,18,24,164,93,146,145,74,206,199,29,204,156,228,193,236,51,136,190,75,229,217,124,4,81,181,125,54,236,105,220,182,57,19,54,213,131,198,34,232,177,122,169,166,183,71,196,249,202,72,169,68,222,254,141,203,143,199,248,70,247,99,196,14,39,45,112,192,230,128,252,249,36,219,148,180,94,189,78,34,89,1,159,179,160,231,22,126,81,46,53,207,131,178,177,160,139,17,246,180,229,228,41,49,184,122,107,20,140,235,117,161,35,63,21,98,173,8,11,62,112,101,6,49,131,231,29,82,172,128,82,139,55,236,233,182,226,130,205,223,136,182,141,223,94,195,18,46,199,89,13,212,243,188,63,1,202,38,61,203,199,253,229,13,159,36,146,106,71,200,218,146,128,110,182,76,198,26,177,223,205,224,72,77,207,69,160,163,217,21,233,61,216,166,77,170,169,160,248,115,129,244,227,81,34,1,210,142,65,52,61,61,85,215,33,3,28,223,224,108,47,74,207,125,207,230,92,28,93,81,64,47,129,182,122,15,215,47,41,81,191,11,208,36,121,21,221,139,194,135,212,32,148,154,223,126,165,247,99,62,44,187,114,155,37,169,167,89,248,71,126,131,111,44,49,78,20,244,167,183,142,184,16,14,250,145,201,116,14,123,185,130,155,211,70,119,200,244,128,240,240,41,30,59,31,172,242,13,78,142,208,233,139,19,149,72,218,129,66,173,119,197,110,156,31,47,207,126,78,40,223,98,81,10,236,232,57,229,81,229,3,98,109,213,250,6,136,248,99,130,35,37,129,148,231,170,39,159,173,148,231,192,223,7,196,122,48,194,191,58,235,67,222,193,158,117,195,155,170,111,178,53,191,225,113,104,180,7,208,253,232,190,93,181,166,242,59,44,38,160,185,174,178,34,91,254,255,195,129,65,185,34,194,43,79,101,211,92,228,64,168,153,82,106,202,159,107,24,46,46,211,159,197,66,104,66,49,170,174,79,53,166,135,128,219,224,36,113,230,87,107,63,91,232,32,165,90,48,3,180,249,101,71,17,156,243,165,152,199,41,52,228,165,32,177,231,236,37,41,214,113,69,203,242,56,127,25,46,53,227,216]}],"Latitude":43.6619996770016,"Longitude":-79.381974826680988,"Accuracy":5.0,"AuthInfo":null,"AuthTicket":{"Start":[215,207,25,194,121,8,74,142,255,228,113,87,249,94,31,143,36,82,186,60,133,63,1,85,247,134,95,33,142,227,30,210,30,146,16,2,214,156,139,116,130,65,107,79,134,169,75,253,248,61,133,95,105,180,197,107,90,246,52,93,191,154,37,83],"ExpireTimestampMs":1487607089955,"End":[215,64,179,97,10,228,73,104,3,6,128,218,109,114,212,158]},"MsSinceLastLocationfix":21274}
[16:51:38] (BŁĄD)    w PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PerformRemoteProcedureCall>d__2`1.MoveNext() w c:\projects\necrobot2\FeroxRev\Extensions\HttpClientExtensions.cs:wiersz 129
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PerformThrottledRemoteProcedureCall>d__8`1.MoveNext() w c:\projects\necrobot2\FeroxRev\Extensions\HttpClientExtensions.cs:wiersz 174
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProtoPayload>d__0`1.MoveNext() w c:\projects\necrobot2\FeroxRev\Extensions\HttpClientExtensions.cs:wiersz 46
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w PokemonGo.RocketAPI.Rpc.BaseRpc.<PostProtoPayload>d__11`1.MoveNext() w c:\projects\necrobot2\FeroxRev\Rpc\BaseRpc.cs:wiersz 130
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w PokemonGo.RocketAPI.Rpc.BaseRpc.<PostProtoPayload>d__10`8.MoveNext() w c:\projects\necrobot2\FeroxRev\Rpc\BaseRpc.cs:wiersz 119
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w PokemonGo.RocketAPI.Rpc.Encounter.<CatchPokemon>d__4.MoveNext() w c:\projects\necrobot2\FeroxRev\Rpc\Encounter.cs:wiersz 145
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   w PoGo.NecroBot.Logic.Tasks.CatchPokemonTask.<Execute>d__4.MoveNext() w c:\projects\necrobot2\PoGo.NecroBot.Logic\Tasks\CatchPokemonTask.cs:wiersz 324
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   w PoGo.NecroBot.Logic.Tasks.CatchNearbyPokemonsTask.<Execute>d__0.MoveNext() w c:\projects\necrobot2\PoGo.NecroBot.Logic\Tasks\CatchNearbyPokemonsTask.cs:wiersz 133
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w PoGo.NecroBot.Logic.Tasks.UseNearbyPokestopsTask.<OnWalkingToPokeStopOrGym>d__12.MoveNext() w c:\projects\necrobot2\PoGo.NecroBot.Logic\Tasks\UseNearbyPokestopsTask.cs:wiersz 167
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w PoGo.NecroBot.Logic.Tasks.UseNearbyPokestopsTask.<>c__DisplayClass10_0.<<WalkingToPokeStop>b__0>d.MoveNext() w c:\projects\necrobot2\PoGo.NecroBot.Logic\Tasks\UseNearbyPokestopsTask.cs:wiersz 149
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w PoGo.NecroBot.Logic.Strategies.Walk.FlyStrategy.<Walk>d__3.MoveNext() w c:\projects\necrobot2\PoGo.NecroBot.Logic\Strategies\Walk\FlyStrategy.cs:wiersz 68
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w PoGo.NecroBot.Logic.Navigation.<Move>d__14.MoveNext() w c:\projects\necrobot2\PoGo.NecroBot.Logic\Navigation.cs:wiersz 101
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w PoGo.NecroBot.Logic.Tasks.UseNearbyPokestopsTask.<WalkingToPokeStop>d__10.MoveNext() w c:\projects\necrobot2\PoGo.NecroBot.Logic\Tasks\UseNearbyPokestopsTask.cs:wiersz 145
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   w PoGo.NecroBot.Logic.Tasks.UseNearbyPokestopsTask.<Execute>d__8.MoveNext() w c:\projects\necrobot2\PoGo.NecroBot.Logic\Tasks\UseNearbyPokestopsTask.cs:wiersz 66
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w PoGo.NecroBot.Logic.Tasks.FarmPokestopsTask.<Execute>d__1.MoveNext() w c:\projects\necrobot2\PoGo.NecroBot.Logic\Tasks\FarmPokestopsTask.cs:wiersz 60
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   w PoGo.NecroBot.Logic.State.FarmState.<Execute>d__0.MoveNext() w c:\projects\necrobot2\PoGo.NecroBot.Logic\State\FarmState.cs:wiersz 54
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   w PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext() w c:\projects\necrobot2\PoGo.NecroBot.Logic\State\StateMachine.cs:wiersz 100

**Comment by SLASHLogin** [comment]
![przechwytywanie](https://cloud.githubusercontent.com/assets/24846525/23132236/36eac9c0-f78d-11e6-869b-4f2ea0061b56.PNG)

I think it's more important part.

**Comment by SLASHLogin** [comment]
It's in in earlier message too

**Comment by hardknoxni69a** [comment]
pretty sure this has been fixed with latest update please delete accounds.db cache and lastpos and it will start at default location and be much more stable with saving location info please let us know if needs to be reopened
