### ISSUE TITLE
Evolution Item logic and implement

### ISSUE THREAD

**Issue by samuraitruong** [Necrobot-Private/NecroBot#918]
need to implement logic for Evolve Items
raise your idea

**Comment by samuraitruong** [comment]
Dragon Scale
Seadra evolves into Kingdra for 100 candies
King’s Rock
Poliwhirl evolves into Politoed (instead of Poliwrath) for 100 candies
Slowpoke evolves into Slowking (instead of Slowbro) for 50 candies
Metal Coat
Scyther evolves into Scizor for 50 candies
Onix evolves into Steelix for 50 candies
Sun Stone
Gloom evolves into Bellossom (instead of Vileplume) for 100 candies
Sunkern evolves into Sunflora for 50 candies
Upgrade
Porygon evolves into Porygon2 for 50 candies

**Comment by samuraitruong** [comment]
EvolutionBranch will hold the info for branhc and item. clear now, WIP

**Comment by jjskuld** [comment]
Currently I'm getting an error when upgrading from schema 15 to 16.
<img width="465" alt="screen shot 2017-02-18 at 5 18 39 pm" src="https://cloud.githubusercontent.com/assets/16908714/23098642/8f09b50c-f608-11e6-9090-3a1130b7f753.png">

**Comment by jjskuld** [comment]
Same problem as #921

**Comment by samuraitruong** [comment]
first part has been release in v114, still working on GUI support

**Comment by hardknoxni69a** [comment]
i thought the EvolveTo was for the stones so a user can put slowKing In there and it will use stone with the cnady to get slowking or on the specific pokemon when they choose transfer there can be a second pop-up asking whether to use stone if its available

**Comment by TVsIan** [comment]
The Windows version seems to have the King's Rock and Sun Stone reversed somewhere - I have 2 King's Rocks and 0 Sun Stones in inventory. The GUI is telling me I can't evolve a Slowking or Politoed, but it will let me attempt to evolve a Sunflora, which fails.

**Comment by hardknoxni69a** [comment]
completed implemenation @TVsIan if this hasnt been resolved in latest updated please open a seperate issue to fix which stone is applied to who
