### ISSUE TITLE
When all bot reach catch limit, spin pokestop still going

### ISSUE THREAD

**Issue by samuraitruong** [Necrobot-Private/NecroBot#919]
For now bot stop work if all account reach catch limit, this implement to allow bot keep work and spin pokestop only. (no snipe)

**Comment by hardknoxni69a** [comment]
definitely a must to maximize on daily allowance

**Comment by hardknoxni69a** [comment]
pretty sure a simple operator would settle this 
    "SwitchOnCatchLimit": false,
    "SwitchOnPokestopLimit": false
    "LimitSwitchOperator": "and"
