### ISSUE TITLE
about KeepMinDuplicatePokemon option

### ISSUE THREAD

**Issue by keunpoke** [Necrobot-Private/NecroBot#922]
hi! i`m a big fan of necrobot2.
i have a question about transfer below.
 
my general setting for every pokemon(in pokemonconfig) is like this
    "KeepMinCp": 2000,
    "KeepMinIvPercentage": 95.0,
    "KeepMinLvl": 6,
    "KeepMinOperator": "or",
    "UseKeepMinLvl": false,
    "PrioritizeIvOverCp": true,
    "KeepMinDuplicatePokemon": 1
 
but, i wanna set a little bit different to pupitar, so i set it at transferfilter like below
 "Pupitar": {
      "KeepMinCp": 9999,
      "KeepMinIvPercentage": 90.0,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinOperator": "or",
      "KeepMinDuplicatePokemon": 10,
      "Moves": [],
      "DeprecatedMoves": null,
      "MovesOperator": "or",
      "CatchOnlyPokemonMeetTransferCriteria": false
    },
 
here is my question
Q) if the number of my pupitars in my bag is over 10, which one will be threw away?
 11st pokemon or the smallest iv?
 
thanks,

**Comment by samuraitruong** [comment]
depend on PriorityIVOrverCP

**Comment by hardknoxni69a** [comment]
depends on your iv or cp preference you set but will either always ditch lowest cp or iv unless its lvl 6 or 90 iv if it isnt it will ditch them

**Comment by keunpoke** [comment]
but i set "snorlax" for the same way as above.
bot ditched 100%iv new snorlax instead of ditching the old one 97%iv.
the old one has higher cp, but "KeepMinOperator": "or", "PrioritizeIvOverCp": true...
why my 100 snorlax died T.T
