### ISSUE TITLE
[Feature Request] Android Emulation 

### ISSUE THREAD

**Issue by SLASHLogin** [Necrobot-Private/NecroBot#924]
I will be grateful for this option. I know it would take a lot of time but using the android make our robot more human and it's harder to see differences when I log on my phone or by the bot.

**Comment by hardknoxni69a** [comment]
unfortantely the bot runs all through windows right now but there are tools out there to convert our app to Android but we are always updating the current one so dont have time to focus on an entire new environment with new problems the good thing though is the exe does show as an iphone in the pogo server so they dont know hopefully some day in future a new dev will tackle that project

**Comment by jjskuld** [comment]
This will never be done. To crack the Android api you would also have to hack Google SafetyNet.  So not only are you taking in Niantic but also Google.  And Google would patch that security very quickly.  IOS is the only way going forward.
