### ISSUE TITLE
GUI - new pokemons

### ISSUE THREAD

**Issue by bbaronSVK** [Necrobot-Private/NecroBot#925]
Add new pokemons images to GUI.

**Comment by CDAGaming** [comment]
@bbaronSVK Hey, what gui do you use. I'm trying to pick between win & electron

**Comment by hardknoxni69a** [comment]
the pix are in the latest gui please downlad NecroBot2.Win.Exe for latest GUI. unfortunately at the the moment electron and Ease Fork are on hold as WinGui Offers alot more at the moment
