### ISSUE TITLE
Cannot set location

### ISSUE THREAD

**Issue by jgrossrieder** [Necrobot-Private/NecroBot#926]
I've gone through the configuration, set the longitude/latitude of my current position, but when I start the bot, the location is somewhere around new york. I tried to go to the default latitude and default longitude(which were not at all what I entered in the wizard, entered, my values, clicked on save, restarted the GUI.

### Expected Behavior:
The bot still start at the position I gave.

### Actual Behavior:
The bot still start at new york

### Your config.json:
```
  "LocationConfig": {
    "DisableHumanWalking": false,
    "StartFromLastPosition": true,
    "DefaultLatitude": 46.946797,
    "DefaultLongitude": 7.448151,
    "WalkingSpeedInKilometerPerHour": 7.6,
    "UseWalkingSpeedVariant": true,
    "WalkingSpeedVariant": 1.2,
    "ShowVariantWalking": true,
    "RandomlyPauseAtStops": true,
    "MaxSpawnLocationOffset": 10,
    "MaxTravelDistanceInMeters": 1000
  },

```

### (OPTIONAL) Your Log:
```
[13:04:20] (ATTENTION) Marche réaliste détectée, utilisation des paramètres par défaut dans le fichier config.json
[13:04:20] (ATTENTION) Destination : 40.7850601488563,-73.9683700700425

```

### Detailed Steps to Reproduce:
launch the wizard, set the destination, relaunch the bot.

### Other Information
Didn't found workaround. I've not any specific configuration except setting my account and setting google api keys, changing a little bit walk speed, everything else is default.

Version:1.0.0.114
Windows Version:10
What is affected (catch, transfer, favorite, GPX, evolve, recycle, snipe, human walk snipe, pokestops, powerup/levelup, other): walk

**Comment by SLASHLogin** [comment]
Delete lastpos.ini or set "startfromlastpostion" to false for one run on and then true

**Comment by hardknoxni69a** [comment]
if ur lastpos shows new york and you have loadlastpos that would be why just wait the travel time to acoid softban and delete the lastpos and it will load at default then your new lastpos around your default next time
