### ISSUE TITLE
[Request] SnipeIgnoreUnknownLvl

### ISSUE THREAD

**Issue by redking974** [Necrobot-Private/NecroBot#929]
### Expected Behavior:
Snipe Pokemon with lvl 0 (I guess we could consider it like unknown lvl since I don't think it could be lvl 0), which could be a Pokemon with lvl 1 or lvl 30
![nb](https://cloud.githubusercontent.com/assets/23528297/23102518/09e51dbe-f6ab-11e6-9b52-a5d9b48e588f.jpg)

### Actual Behavior:
Assuming that I configure each Pokemon with a lvl 20, I don't really know if atm Necrobot snipes Pokemon with lvl 0 or ignore these Pokemon because 0 is lower than 20

### Your config.json:
```
    "Tyranitar": {
      "SnipeIV": 25,
      "Moves": [],
      "Operator": "or",
      "VerifiedOnly": false,
      "Priority": 1,
      "AutoSnipeCandy": 1,
      "Level": 20,
      "AllowMultiAccountSnipe": false
    },

```

Version: 114
Windows Version: 10
What is affected (catch, transfer, favorite, GPX, evolve, recycle, snipe, human walk snipe, pokestops, powerup/levelup, other): catch

**Comment by hardknoxni69a** [comment]
if you have verifiedonly to false it will snipe 0 the level is for verified snipes only
