### ISSUE TITLE
Using API key with Google Elevation API enabled, start up seems unstable

### ISSUE THREAD

**Issue by ValorRed** [Necrobot-Private/NecroBot#93]
Many times, when I tried to start the bot, get this error,
![image](https://cloud.githubusercontent.com/assets/20829876/18443697/1c40b03a-78e4-11e6-95b2-b6905818bca4.png)

But close it and try again, it might succ.

**Comment by ajns73** [comment]
Same as #92?

**Comment by jjskuld** [comment]
This is the same as #87.  Not sure if it's the same as #92.
