### ISSUE TITLE
Socket Server Problem

### ISSUE THREAD

**Issue by damasopg** [Necrobot-Private/NecroBot#930]
Hello!

I have been experiencing some trouble with the Socket being blocked. I run the WIN console together with the Electron.GUI. The problem comes when I have to restart the console because of an unsolved captcha (example), it is working well get the captcha, not solve it, restart the console and Electron.GUI and then the console shows the following:

[15:10:49] (ERROR) Counld't start socket server at port 14251, this port maybe in use or block, please change config to other port and restart bot if you want to use web gui.

If i restart the computer it works okay again, the port seems to be blocked or something, maybe the bot doesn't unlock it befor exiting.

Thanks for your hard work guys, I'm taking courses of C# to colaborate in a close future.

**Comment by hardknoxni69a** [comment]
try manual closing the app through task manager as sometimes it keeps the socket open in background and you will be good to go

**Comment by maurolardoni** [comment]
I have more or less the same trouble: anytime (since the first launch) Necrobot doesn't work and the message Counld't start socket server at port 14251 appears... how can I fix it?

**Comment by Furtif** [comment]
"WebsocketsConfig": {
    "UseWebsocket": false,
    "WebSocketPort": 14251
  },
this bug fix https://github.com/Necrobot-Private/NecroBot/pull/1243

**Comment by hardknoxni69a** [comment]
Ya u either need the cert file which is being be readded or u have an instance open in background that is using the socket still so look through ur open processes in task manager and close it
