### ISSUE TITLE
issue about monster levelup

### ISSUE THREAD

**Issue by keunpoke** [Necrobot-Private/NecroBot#932]
![levelup](https://cloud.githubusercontent.com/assets/25818858/23114992/7e0d0c08-f785-11e6-81a2-b723d5452a3b.PNG)

as i know, trainer can make his monster level up to trainer level+1.5
but using necro bot, i can make my monster up to my level+2.
as you see my level is 31, but my monsters level is 33.

in my mobile phone, levelup is disabled at level 32.5, but by using necro it was possible.
is it a bug or something special?

**Comment by samuraitruong** [comment]
I don't think that is a bug , that is ok

**Comment by keunpoke** [comment]
how could the max level is different compare to in game??

**Comment by ziomber** [comment]
This is a double finger hidden function.
