### ISSUE TITLE
Using current API only prevent captcha?

### ISSUE THREAD

**Issue by cvbmert** [Necrobot-Private/NecroBot#933]
One thing I've never quite understood about using the current API version is does it only prevent captchas from popping up? Or does it actually prevent me from being banned completely? As long as I don't do anything stupid like teleport from Pokestop to Pokestop.

**Comment by samuraitruong** [comment]
you need use api 0.57 from pf

**Comment by samuraitruong** [comment]
and turn off snipe , because you still get captcha on official app

**Comment by zuklio** [comment]
So I get captcha on phone later, even if I use pokefarmer haskey but snipe,  I never got one before on necrobot?

**Comment by cvbmert** [comment]
Me either.

**Comment by hardknoxni69a** [comment]
the hash server prevents niantic from seeing your using outdated api making captchas so play safe and you will get no captchas using new api it doesnt just bypass captchas they see you like anyone else

**Comment by hardknoxni69a** [comment]
sniping wont give you captcha or softban unless your only sniping without doing local actions like catching locals and spinning locals
