### ISSUE TITLE
Feature request - Switch by Min Catch limit instead of runtime

### ISSUE THREAD

**Issue by samuraitruong** [Necrobot-Private/NecroBot#936]
as title, instead of check for runtime, we use min catch limit to determine account to switch

**Comment by zuklio** [comment]
This are great news.

**Comment by hardknoxni69a** [comment]
i thought thats what switchoncatch limit is

**Comment by zuklio** [comment]
At the moment you switch to account who has the lowest runtime, even if you switch by catchlimit. I think with this feature you switched to the account with lowest catchlimt, not runtime. And this is good because there is a hard to fix time log issue at the moment.

**Comment by samuraitruong** [comment]
@zuklio  could you help to re-test on v1.0.0.115, seem it fixed for me now

**Comment by hardknoxni69a** [comment]
implemented
