### ISSUE TITLE
Necrobot didn't snipe the Pokemon with the moves' restriction

### ISSUE THREAD

**Issue by redking974** [Necrobot-Private/NecroBot#937]
### Expected Behavior:
Snipe and catch Dratini with Dragon Breath (for "bubble")

### Actual Behavior:
Snipe Dratini with other moves

### Your config.json:
```
    "Dratini": {
      "SnipeIV": 0,
      "Moves": [
        [
          "dragonBreathFast"
        ]
      ],
      "Operator": "and",
      "VerifiedOnly": false,
      "Priority": 1,
      "AutoSnipeCandy": 1,
      "Level": 0,
      "AllowMultiAccountSnipe": true
```

### (OPTIONAL) Your Log:
```
[14:55:06] (SNIPER) (InternalSnipe) [Sniper] Scan d'un Minidraco avec 44.44% IV à -33.95540521,151.26129582...
[14:55:27] (INFO) (CATCH LIMIT) 1/938
[14:55:27] (POKEMON) (Capturé) | (Normal) Minidraco Lvl: 2 CP: (32/861) IV: 44.00% | Chance: 100% | dist 17343493.91m | 65 PokéBall restante(s) | 1210XP | 3 Bonbons | lat: -33.955405 long: 151.261296 | Move1: IronTailFast Move2: Wrap

```

### Detailed Steps to Reproduce:
Launch Necrobot

### Other Information
I don't know if it's related with Verified because into the GUI I see that non-verified have moveset.

Version: 114
Windows Version: 10
What is affected (catch, transfer, favorite, GPX, evolve, recycle, snipe, human walk snipe, pokestops, powerup/levelup, other): catch

**Comment by samuraitruong** [comment]
Move sets setup wrong, 

it should be paird of move1, move 2

 "Dratini": {
      "SnipeIV": 0,
      "Moves": [
        [
          "dragonBreathFast","move2 here"
        ]
      ],
