### ISSUE TITLE
Error GPU Channel

### ISSUE THREAD

**Issue by stikio** [Necrobot-Private/NecroBot#939]
[4408:12076:0220/201648.210:ERROR:browser_gpu_channel_host_factory.cc(125)] Failed to create channel.

I get this error 4 times at the beginning.

**Comment by samuraitruong** [comment]
very weird

**Comment by hardknoxni69a** [comment]
let us know if this is something on our end

**Comment by ForrealGames** [comment]
Hey was there ever a resolution for this? Am experiencing this issue currently on chrome start up. 

![screenshot_1](https://cloud.githubusercontent.com/assets/26332933/23808846/5899c6e2-0599-11e7-939d-b0e72b1128eb.png)

require "rubygems"
require "selenium-webdriver"

driver = Selenium::WebDriver.for :chrome

driver.navigate.to "https://bluetooth.com"
driver.navigate.to "https://www.bluetooth.com/membership-working-groups/membership-types-levels"

**Comment by hardknoxni69a** [comment]
@truong @jjskuld not sure about this

**Comment by Lord-Haji** [comment]
As no one else is experiencing this issue .
I am assuming the error is on your side

**Comment by dinukacgx** [comment]
Experiencing same issue when running e2e test with protractor for angular cli project, but no harm for the test tests are completed. How avoid this errors?
 
![image](https://cloud.githubusercontent.com/assets/17020695/24293589/89a2d060-10b8-11e7-9c61-ce8a6cd1c24f.png)
