### ISSUE TITLE
version 0.9.8.7 Login failed with ptc

### ISSUE THREAD

**Issue by Paulbapet** [Necrobot-Private/NecroBot#94]
Always end up with "User credentials are invalid and login failed." on version 0.9.8.7
I tried with version 0.9.8.6 it did logged in and run normally.

### Expected Behavior:
login and run bot with ptc account

### Actual Behavior:
failed login with ptc account "User credentials are invalid and login failed." only on version 0.9.8.7

### Your config.json:
not needed

### (OPTIONAL) Your Log:
Initializing NecroBot2 logger at time 9/12/2016 11:14:55 PM...
Initializing NecroBot2 logger at time 9/12/2016 11:26:55 PM...
[23:27:01] Validating config.json...
[23:27:09] Validating auth.json...
[23:27:14] Update checking is disabled. Current Version: 0.9.8
[23:27:14] Logging in using Ptc
[23:27:15] Your IP is: xxx.xxx.73.174
[23:27:22] User credentials are invalid and login failed.
Initializing NecroBot2 logger at time 9/12/2016 11:29:50 PM...
[23:29:55] Validating config.json...
[23:30:01] Validating auth.json...
[23:30:06] Update checking is disabled. Current Version: 0.9.8
[23:30:06] Logging in using Ptc
[23:30:07] Your IP is: xxx.xxx.73.174
[23:30:11] User credentials are invalid and login failed.

### Detailed Steps to Reproduce:
not needed

### Other Information
I will post auth.json and config.json if it necessary.

Version:
Windows Version: Windows 7 Ultimate 64 bit
What is affected (catch, transfer, favorite, GPX, evolve, recycle, snipe, human walk snipe, pokestops, powerup/levelup, other):
unable to run bot

Thanks

**Comment by mo0ojava** [comment]
Have you checked http://ispokemongodownornot.com/ ?
PTC login-servers aren't online atm.
Could be that.

Coincidentally they've announced a major system-update anytime soon...

**Comment by efifi** [comment]
is it a new account? have you verified the account on PTC? can you log into PTC with the credentials?

**Comment by Bkheart** [comment]
new account only

**Comment by Paulbapet** [comment]
@mo0ojava and @efifi 
the problem is when you make a new PTC account (confirmed email, accepted ToS on "https://club.pokemon.com/us/pokemon-trainer-club/go-settings") and use it for the first time with v0.9.8.7 and v0.9.8.8 you will get "User credentials are invalid and login failed."
but if you use it for the first time with v0.9.8.6 you'd be able to login normally.
and should be able to login using v0.9.8.7 and v0.9.8.8 with PTC account that already used with v0.9.8.6.
sorry with bad english, hope you understand.

**Comment by kuntau** [comment]
Confirmed, give me major headache why it failed to log in a fresh account. Finally I had to log in on my phone complete the tutorial, only then I can log in with Necrobot
