### ISSUE TITLE
Bug)Evolution Logic Needs To Check Both Lists

### ISSUE THREAD

**Issue by hardknoxni69a** [Necrobot-Private/NecroBot#940]
For All The Basics
  "PokemonsToEvolve": [
    "pidgey",
    "caterpie",
    "weedle",
    "rattata",
For The Specials
  "PokemonEvolveFilter": {
    "Onix": {
      "MinIV": 100,
      "MinLV": 28,
      "MinCP": 500,
      "Moves": [],
      "Operator": "and",
      "EvolveTo": "Steelix"
    },
    "Scyther": {
      "MinIV": 100,
      "MinLV": 28,
      "MinCP": 500,
      "Moves": [],
      "Operator": "and",
      "EvolveTo": "Scizor"
    },
    "Porygon": {
      "MinIV": 100,
      "MinLV": 28,
      "MinCP": 500,
      "Moves": [],
      "Operator": "and",
      "EvolveTo": "Porygon2"

**Comment by samuraitruong** [comment]
I removed old list

**Comment by samuraitruong** [comment]
https://github.com/Necrobot-Private/NecroBot/issues/955
new config has come to replace it,
