### ISSUE TITLE
Necrobot GUI gen 2

### ISSUE THREAD

**Issue by garette1** [Necrobot-Private/NecroBot#941]
necrobot2GUI and necrobotGUIelectron don do anything when i click a pokemon in gen 2.

**Comment by cswxin** [comment]
the same since v1.0.0.104, maybe.

**Comment by CDAGaming** [comment]
@garette1 Can you explain to me how to get the electron gui to work for me it doesnt load anything

**Comment by garette1** [comment]
@CDAGaming you must set usewebsocket : true, thats all

**Comment by CDAGaming** [comment]
@garette1 No, that can't be all it. I have set the appropriate options in config and ran Necrobot2.GUI, and still all loading. Also tried loading Necrobot.Console and then GUI

**Comment by garette1** [comment]
i dont do anything.ectract zip and run GUI and console.websocketport must be same. check it

**Comment by CDAGaming** [comment]
It sets the default port as 12342 for websocket on GUI which I set to 12341. It's only worked once and idk what I did to make it work/stop working

**Comment by garette1** [comment]
try uninstall and re-install console and GUI, dont change anything in config

**Comment by samuraitruong** [comment]
use necrobot2.win instead, We don't have time to maintain web gui for the time being

**Comment by CDAGaming** [comment]
@samuraitruong then can you at least improve THAT GUI, it's menus look cluttered and if you don't have a good PC, sniping can be slow

**Comment by hardknoxni69a** [comment]
please appreciate what we have. it is open source so good news is you can help us make the neccessary adjustments electron is a side project from another dev who is no longer doing it WIN GUI is superior in all ways besides some of the looks but definitely superior and there isnt even sniping in electron
