### ISSUE TITLE
Feature Request: Enhance PokemonsTransferFilter for legacy Moves

### ISSUE THREAD

**Issue by isveryfunny** [Necrobot-Private/NecroBot#942]
As many new Moves are coming.
Legacy Moves still probably be dropped if you indicate legacy Moves in PokemonsTransferFilter.
It is good if add a priority option for special "Moves": [],

**Comment by hardknoxni69a** [comment]
please be more specific

**Comment by hardknoxni69a** [comment]
you need to keep the legacy moves or it will transfer existing ones

**Comment by isveryfunny** [comment]
dragonBreathFast still probably be dropped if IV or CP lower than outrage.
Am I right?
I would like to keep dragonBreathFast first.

    "Dragonite": {
      "KeepMinCp": 2500,
      "KeepMinIvPercentage": 90.0,
      "KeepMinLvl": 25,
      "UseKeepMinLvl": true,
      "KeepMinOperator": "and",
      "KeepMinDuplicatePokemon": 20,
      "Moves": [
        [
          "dragonBreathFast",
          "dragonClaw"
        ],
        [
          "dragonBreathFast",
          "dragonPulse"
        ],
        [
          "dragonTailFast",
          "outrage"
        ]
      ],
      "DeprecatedMoves": null,
      "MovesOperator": "and",
      "CatchOnlyPokemonMeetTransferCriteria": false
    },

**Comment by hardknoxni69a** [comment]
old moves are still in moves list so no need to worry
