### ISSUE TITLE
Feature Request - Add option to randomize multi bot switching time

### ISSUE THREAD

**Issue by momentosnaps** [Necrobot-Private/NecroBot#943]
To add an option to randomize RuntimeSwitch to mimic closer a human behavior. A human does not play exactly XXX minutes every time.

**Comment by samuraitruong** [comment]
make you switch pokemon iv to 50%
it will definitely randome

**Comment by RoskamiesX** [comment]
I will see if i can implement this. I'm quite busy atm and will post here when progress has been made
