### ISSUE TITLE
Rate list update for gen 2 pokemons

### ISSUE THREAD

**Issue by bean0000** [Necrobot-Private/NecroBot#945]
I would like to request that these following pokemons be listed as rare:
1.Tyranitar
2.Pupitar
3.Togetic
4.Unown
5.Chansey
6.Blissey
and other pokemons with 2nd and 3rd evolve state.

please feel free to add other rare pokemons

**Comment by FureszOszkar** [comment]
Maybe it's more:
"Ho-Oh”,
"Tyranitar”,
"Lugia”,
"Entei”,
"Raikou”,
"Blissey”,
"Celebi”,
"Donphan”,
"Espeon”,
"Heracross”,
"Suicune”,
"Scizor”,
"Ursaring”,
"Feraligatr”,
"Ampharos”,
"Typhlosion”,
"Porygon2”,
"Houndoom”,

**Comment by bean0000** [comment]
those with evolutions that need special items probably wont spawn in the wild.

**Comment by samuraitruong** [comment]
hey, the list is not really rare, can you break down more to veryrare, rare, normal

**Comment by bean0000** [comment]
1.Chikorita=common
2.bayleef=uncommon
3.Meganium=rare in my opinion
4.cyndaquil=uncommon to rare
5.quilava=rare
6.typhlosion=very rare
7.totodile=common
8.croconaw=uncommon
9.Feraligator=rare
10.sentret=common
11.furret=uncommon
12.hoothoot=common
13.noctowl=rare
14.ledyba=common
15.Ledian=uncommon
16.spinarak=common
17.ariados=uncommon
18.crobat=rare*
19.chinchou=uncommon
20.lanturn=rare
21,22,23.pichu/igglybuff/cleffa=from eggs
24.sudowoodo=uncommon to rare
25.politoed=special**
26.hoppip=uncommon
27.skiploom=rare
28.jumpluff=very rare
29.aipom=uncommon
30.sunkern=common
31.sunflora=special**
32.yanma=uncommon
33.wooper=common
34.quagsire=rare
35.espeon=rare*
36.umbreaon=rare*
37.murkrow=common
38.slowking=special
39.Misdreavus=uncommon to rare
40.Unown=rare
41.Wobbuffet=uncommon
42.girafarig=rare
43.pineco=rare
44.Forretress=very rare
45.dunsparce=uncommon
46.gligar=uncommon to rare
47.steelix=special**
48.snubbul=common to uncommon
49.grandbull=uncommon to rare
50.qwilfish=uncommon to rare
51.Scizor=special**
52.shuckle=uncommon to rare
53.heracross=uncommon to rare
54.sneasel=uncommon to rare
55.teddiursa=common
56.ursaring=rare
57.slugma=common
58.magcargo=uncommon to rare
59.swinub=common
60.piloswine=uncommon to rare
61.corsola=uncommon
62.remoraid=common
63.octillery=uncommon to rare
64.delibird=rare never saw one even on sniping page
65.mantine=uncommon to rare
66.skarmory=uncommon to rare
67.houndour=common
68.houndoom=rare
69.kingdra=special**
70.phanpy=common to uncommon
71.donphan=rare
72.porygon2=special**
73.stantler=uncommon to rare
74.smeargle=rare never seen one before even on sniping site
75.tyrogue=egg
77.hitmontop=rare to very rare
78,79,80. smoochum/elekid/magby=egg
81.militank=rare to very rare
82.blissey=rare
83,84.85.raikou/entei/suicune=legendary. i dont think well even find these in the wild
86.Larvitar=uncommon
87.pupitar=rare
88.tyranitar=very rare
89,90,91.Lugia/hooh/celebi=legendary.

*i listed these as rare because the evolved forms are hard to find. but if u argue that u can get this from evolving common pokemon then yes its common
**i listed these as special because of the need for special items to evolve them and i dont think well ever see these evolved form in the wild,

as for the gen 1 pokemon. ive seen alot of old pokemon become rare because of the release of the new ones.

1.bulbasaur=uncommon*
2.invysaur=rare
3.venusaur=very rare*
4.charmander=uncommon to rare*
5.charmelon=rare
6.charizard=very rare*
7.squirtle=common to uncommon
8.wartortle=rare
9.blastoise=rare to very rare*
10.caterpie=common
11.metapod=rare
12.butterfree=rare
13.weedle=common
14.kakuna=uncommon to rare
15.beedrill=rare
16.pidgey=common
17.pidgeotto=uncommon
18.pidgeot=rare
19.ratata=common
20.raticate=uncommon to rare
21.spearow=common
22.fearow=rare
23.ekans=common
24.arbok=rare
25.pikachu=uncommon
26.raichu=very rare
27.sandshrew=uncommon
28.sandslash=rare
29.nirodanfemale=common
30.nidorina=uncommon to rare
31.nidoqueen=rare
32.nidoranmale=common
33.nidorino=uncommon to rare
34.nidoking=rare
35.clefairy=uncommon
36.clefable=rare
37.vulpix=uncommon
38.ninetails=rare
39.jigglypuff=uncommon
40.wigglytuff=rare
41.zubat=common
42.golbat=uncommon
43.oddish=common
44.gloom=uncommon
45.vileplume=rare
46.paras=common
47.parasect=uncommon to rare
48.venonat=common
49.venomoth=uncommon to rare
50. diglet=uncommon
51.dugtrio=rare to very rare
52.meowth=common to uncommon
53.persian=uncommon to rare
54.psyduck=common
55.golduck=uncommon to rare
56.mankey=uncommon*
57.primeape=rare to very rare*
58.growlithe=common to uncommon*
59.arcanine=rare to very rare
60.poliwag=common
61.poliwhirl=uncommon to rare*
62.poliwrath=rare
63.abra=uncommon
64.kadabara=rare
65.alakazam=very rare
66.machop=uncommon
67.machoke=rare
68.machamp=very rare
69.bellsprout=common
70.weepinbell=rare*
71.victreebel=rare*
72.tentacool=common
73.tentacruel=uncommon to rare
74.geodude=common to uncommon*
75.graveler=rare
76.golem=rare to very rare
77.ponyta=uncommon
78.rapidash=rare
79,slowpoke=common to uncommon*
80.slowbro=rare
81.magnemite=common to uncommon
82.magneton=rare to very rare*
83.farfetchd=rare
84.duduo=common
85,dodrio=uncommon
86.seel=uncommon to rare
87.dewgong=rare to very rare
88.grimer=uncommon*
89.muk=very rare*
90.shelder=uncommon*
91.cloyster=rare to very rare*
92.gastly=uncommon
93.haunter=rare
94.gengar=rare to very rare
95.onix=rare
96.dorwzee=uncommon
97.hypno=rare
98.krabby=common
99.kingler=uncommon to rare
100.voltorb=uncommon*
101.electrode=rare
102.exeggcute=common*
103.exeggutor=rare
104.cubone=uncommon*
105.marowak=rare
106.hitmonlee=rare*
107.hitmonchan=rare*
108.lickitung=uncommon to rare
109.koffing=common to uncommon
110.weezing=rare
111.rhyhorn=common to uncommon*
112.rhydon=rare
113.chansey=rare to very rare**
114.tangela=uncommon to rare
115.kangaskhan=rare
116,horsea=common to uncommon
117.seadra=rare
118.goldeen=common
119.seaking=uncommon to rare
120.staryu=common
121.starmie=uncommon to rare
123.mr.mime=rare
124.scyther=uncommon to rare*
125.jynx=uncommon to rare*
126.electabuz=uncommon to rare*
127.magmar=uncommon to rare*
128.pinsir=uncommon to rare*
129.tauros=rare
130.magikarp=common
131.gyarados=rare
132.lapras=rare
133.ditto=probably uncommon to rare. depends on the players playing habits.
134.eevee=common
135.vaporeon=rare
136.jolteon=rare
137.flareon=rare
138.porygon=uncommon to rare*
139.omanyte=uncommon*
140.omastar=very rare
141.kabuto=uncommon to rare*
142.kabutops=very rare
143.aerodactly=very rare
144.snorlax=rare
145,146,147.articuno/zapdos/moltress=legendary
148.dratini=uncommon
149.dragonaire=rare
150.dragonite=rare
151,152.mew/mewtwo=legendary

*saw a decrease in spawns of these following pokemons maybe due to the release of the new gen
**this pokemon are now really hard to find

all of these are just based on my personal experience from playing manually in my localation, botting/sniping, using pokemon radars/scanners and searching from the free necrobot snipe webpage. the donator's snipe page may contain more pokemons thus making some of those listed here wrong.
please feel free to correct any errors.

**Comment by bean0000** [comment]
sorry for the long post

**Comment by samuraitruong** [comment]
That is alright, I finish for gen 1 before, just need add for gen 2

**Comment by purado** [comment]
I'm running a map/scanner for a town in germany. Based on 208.802 spawns since the launch of Gen2, here are the appearances. No entry for a pokemon_id means no spawns at all:

1 	38
2 	8
4 	44
5 	1
7 	200
8 	19
9 	1
10 	2565
11 	310
12 	34
13 	5967
14 	781
15 	81
16 	16936
17 	1054
18 	137
19 	3819
20 	118
21 	5487
22 	155
23 	301
24 	6
25 	81
26 	1
27 	43
28 	1
29 	3263
30 	78
31 	9
32 	3238
33 	93
34 	6
35 	1485
36 	23
37 	269
39 	1266
40 	7
41 	3402
42 	299
43 	1723
44 	86
45 	3
46 	5034
47 	78
48 	4499
49 	71
50 	198
52 	1190
53 	4
54 	1150
55 	13
56 	512
57 	6
58 	342
59 	1
60 	1078
61 	22
62 	1
63 	697
64 	16
65 	2
66 	243
67 	6
69 	1456
70 	38
71 	3
72 	374
73 	19
74 	467
75 	12
77 	131
79 	678
80 	9
81 	125
82 	1
84 	8
86 	391
87 	10
88 	17
89 	1
90 	1351
91 	9
92 	1538
93 	90
94 	8
95 	10
96 	1242
97 	29
98 	2846
99 	38
100 	22
101 	1
102 	499
103 	2
104 	127
105 	3
106 	8
107 	12
108 	16
109 	203	 
110 	7
111 	236
112 	4
113 	3
116 	1532
117 	24
118 	1212
119 	41
120 	1140
121 	5
122 	1149
123 	33
124 	19
125 	42
126 	1
127 	8
129 	1154
130 	2
131 	6
133 	9151
134 	5
135 	2
137 	1
138 	13
140 	5
142 	7
143 	4
147 	64
148 	4
149 	4
152 	220
153 	13
154 	2
155 	191
156 	4
157 	1
158 	7
161 	5604
162 	171
163 	11781
164 	237
165 	19286
166 	823
167 	12120
168 	595
169 	149
170 	558
171 	18
176 	13
177 	11269
178 	402
179 	26
180 	2
183 	2891
184 	130
185 	348
187 	2913
188 	160
189 	8
190 	1963
191 	259
193 	26
194 	5799
195 	85
198 	13791
200 	513
202 	529
203 	59
204 	84
205 	10
206 	342
207 	486
209 	1351
210 	51
211 	53
213 	1
215 	494
216 	784
217 	25
218 	79
219 	5
220 	14268
221 	480
223 	290
224 	121
226 	72
227 	141
228 	52
229 	2
231 	257
232 	25
234 	28
237 	3
242 	1
246 	23
247 	2

**Comment by samuraitruong** [comment]
V145

**Comment by bean0000** [comment]
a

**Comment by bean0000** [comment]
i forgot to add these pokemons to the list.

togepi=egg
togetic=very rare
natu=common
xatu=uncommon to rate
mareep=uncommon to rare
flaffy=rare
ampharos=very rare
bellosom=special
maril=common
azumaril=uncommon to rare
