### ISSUE TITLE
NecroBot2.Win.exe doesnt appear WIN GUI only bot console

### ISSUE THREAD

**Issue by sarafoxy112** [Necrobot-Private/NecroBot#946]
Hello.

windows 8.1
necrobot2.win seems to dont work for me.
just downloaded fresh NecroBot2.WIN.zip then extracted it from zip.
launch NecroBot2.Win.exe then wingui interface appear and a small console to type my passwords and choose cords okay I did it all and click RUN BOT then wingui interface just close and only bot console appear. 

really tried almost everything.. was fighting with it for 2 days

**Comment by samuraitruong** [comment]
close console and run win again.

**Comment by sarafoxy112** [comment]
nothing happen when I did what you told

**Comment by hardknoxni69a** [comment]
run just the necrobot2.exe first and make sure u dont have any errors

**Comment by sarafoxy112** [comment]
did it all you said and still dont work. can record video on youtube and send to you on discord if its needed

**Comment by Koteczek123** [comment]
Same issue here it did worl till friday since then no, the win ap is starting i sett all data in then the bot window opens and win shots down. You cannot restart win  anymore.... it is not starting and I rellly iked this prog

**Comment by SLASHLogin** [comment]
It happend me when I updated Necro by WIN everything was ok but when WIN closed after downloading new version and unpacking, it closed and never open.

**Comment by SLASHLogin** [comment]
But new downloaded version works

**Comment by samuraitruong** [comment]
fix in https://github.com/Necrobot-Private/NecroBot/pull/1006
