### ISSUE TITLE
New user, Necrobot2.WIN did not use the lattitude/longitude I entered in the GUI

### ISSUE THREAD

**Issue by Hydrojw1** [Necrobot-Private/NecroBot#947]
## Stop! Before you create this issue (you can delete this section when opening the issue):
1. Have you searched to see if there are other Open/Closed issues for the same issue? If so, comment on that issue instead.
2. Have you validated that your config/auth.json and config/config.json is valid JSON? Use http://jsonlint.com/ to check.
3. If your question is referring to how to set up or use the bot, please join our discord instead of posting an issue: https://discord.gg/7FWyWVp 
4. Always confirm that your issue is reproducible, with the config you provide below.

### Your config.json:
```
replace this text with the contents of your config.json

```

### (OPTIONAL) Your Log:
```
replace this text with only the "relative" portion of your log. (Remove unnessary lines)

```

### Other Information
(Attach zip files if needed.)

Version:
Windows Version:
What is affected (catch, transfer, favorite, GPX, evolve, recycle, snipe, human walk snipe, pokestops, powerup/levelup, other):

**Comment by Hydrojw1** [comment]
Im a new user of Necrobot2, I used Necrobot2.WIN. It asked me for my account details etc, it asked me for the position I wanted to start the bot, I entered a position in the UK. It deployed my account/char into New York. How do I reposition the bot to put the char where I wanted it. Has putting the char into New Your limited my future of using this in the UK?

Also the exp per hour appears to be low compared to some I have read in various forums. I have used the default settings that come from the zipped package.

**Comment by meluckycharms** [comment]
I encountered this issue.  My workaround was simply entering my coordinates into the config.backup.json file as well.

**Comment by Hydrojw1** [comment]
When you correct this and try to reposition the trainer, are there any gotcha's that I must not do? Are there any extra risks with moving around the world map in a certain time? Can anybody answer this please.

**Comment by samuraitruong** [comment]
https://github.com/Necrobot-Private/NecroBot/issues/955 fixed
