### ISSUE TITLE
No Farfetche'd to snipe?

### ISSUE THREAD

**Issue by cvbmert** [Necrobot-Private/NecroBot#948]
It might be a bug, I've been using Necrobot2 WIN for a while now like 2 months and literally the entire time no Farfetche'd have shown up to snipe, that's the last one I need to complete my Gen1 that's available to actually catch anyway so what's up? lol

**Comment by hardknoxni69a** [comment]
there definitely there not many but ive sniped a few through

**Comment by cvbmert** [comment]
Alright I'll keep looking, thanks.

**Comment by hardknoxni69a** [comment]
farfetched is only shown over 90% in order for it to be displayed patience is a virtue my friend

**Comment by hardknoxni69a** [comment]
dude theres a 100iv right now
Farfetchd [35.0937187020081,129.096343044076] IV 100%
