### ISSUE TITLE
Stardust is not deducted from Win GUI display when upgrading pokemon

### ISSUE THREAD

**Issue by 6Vampire6** [Necrobot-Private/NecroBot#949]
When evolving pokemon using the Win GUI, the stardust in the display does not get deducted.

**Comment by nejnejxd** [comment]
Evolving, or Powering Up?

Evolves do not cost Stardust.

**Comment by 6Vampire6** [comment]
Power up

**Comment by Lord-Haji** [comment]
@samuraitruong I am having the same issue too

**Comment by Tjommel** [comment]
still a bug!
