### ISSUE TITLE
(ATTENTION) [REPLY] when accessing Google Elevation Service API: REQUEST_DENIED

### ISSUE THREAD

**Issue by Danny-0815** [Necrobot-Private/NecroBot#95]
I keep getting this error, when I run the bot with the newest version...
I didn't change my Google API, what happened? The bot works fine except from showing me this error like every 2nd second...

[19:49:09] (ATTENTION) [REPLY] when accessing Google Elevation Service API: REQUEST_DENIED

**Comment by jjskuld** [comment]
Your Google API key may not be enabled for Google Elevation API. Log into the Google API console and enable it for elevation. Or create a new key just for Elevation API.
