### ISSUE TITLE
instaling

### ISSUE THREAD

**Issue by dornzak** [Necrobot-Private/NecroBot#952]
so how do i install the bot ?

**Comment by macinmn** [comment]
it doesn't need to be 'installed' , unzip and run the executable

**Comment by dornzak** [comment]
to use the current version i need to pay for it ?

**Comment by deadmau5582** [comment]
No.

**Comment by dornzak** [comment]
wich one should i dl ? the only executable thing is on console paste and needs to pay for play the latest version

**Comment by nejnejxd** [comment]
Download the WIN GUI, enter PTC info, Youre done. No Payments.
