### ISSUE TITLE
CaptchaSolutions variable Delay

### ISSUE THREAD

**Issue by deadmau5582** [Necrobot-Private/NecroBot#953]
Hello,

i want to ask if you can build in a delay time for CaptchaSolutions.com because i have alot of misstakes.
I started a question to CaptchaSolutions.com and the Support Team told me i need a delay between the captchas because of they DDoS Protection.

Best Regards

**Comment by samuraitruong** [comment]
there is 3 or 5 sec before the each check, but captchasolution is crap, it not work 247,
