### ISSUE TITLE
Snipe List Is No Longer Removing Duplicate Entries

### ISSUE THREAD

**Issue by hardknoxni69a** [Necrobot-Private/NecroBot#957]
Once A Entry Has Been Verified It Stays In The Unverified And The Verified List So Alot Of Double Entries Causing Unneccesary Memory Slowing Down Results

**Comment by hardknoxni69a** [comment]
![capture](https://cloud.githubusercontent.com/assets/21132978/23233773/e5190430-f91d-11e6-936d-37b4d25c9157.PNG)

**Comment by hardknoxni69a** [comment]
i know this was implemented before not sure why it stopped working

**Comment by Lord-Haji** [comment]
Not applicable anymore
