### ISSUE TITLE
Disable catch Pokemon feature still autosnipe?

### ISSUE THREAD

**Issue by cvbmert** [Necrobot-Private/NecroBot#959]
If I disable the catch Pokemon feature will it still autosnipe the Pokemon I have specified in the autosnipe list? When I have both enabled it runs out of Balls to fast and I feel I miss out on some sniping targets.

**Comment by cvbmert** [comment]
Also under autosnipe when the pokemon level is set to 0 does that mean that parameter is ignored or can a Pokemon actually be level 0?

**Comment by cswxin** [comment]
I set "MinIVForAutoSnipe": 100, modify RecycleConfig and SnipePokemonFilter like this:

  "RecycleConfig": {
    "VerboseRecycling": true,
    "RecycleInventoryAtUsagePercentage": 90.0,
    "RandomizeRecycle": false,
    "RandomRecycleValue": 3,
    "TotalAmountOfPokeballsToKeep": 230,
    "TotalAmountOfPotionsToKeep": 10,
    "TotalAmountOfRevivesToKeep": 10,
    "TotalAmountOfBerriesToKeep": 50,
    "UseRecyclePercentsInsteadOfTotals": false,
    "PercentOfInventoryPokeballsToKeep": 35,
    "PercentOfInventoryPotionsToKeep": 35,
    "PercentOfInventoryRevivesToKeep": 20,
    "PercentOfInventoryBerriesToKeep": 10
  },

  "SnipePokemonFilter": {
    "Unown": {
      "SnipeIV": 0,
      "Moves": [],
      "Operator": "or",
      "VerifiedOnly": false,
      "Priority": 1,
      "AutoSnipeCandy": 5000,
      "Level": 0,
      "AllowMultiAccountSnipe": false
    },
    "Magikarp": {
      "SnipeIV": 0,
      "Moves": [],
      "Operator": "or",
      "VerifiedOnly": false,
      "Priority": 2,
      "AutoSnipeCandy": 5000,
      "Level": 0,
      "AllowMultiAccountSnipe": false
    },
    "Larvitar": {
      "SnipeIV": 0,
      "Moves": [],
      "Operator": "or",
      "VerifiedOnly": false,
      "Priority": 1,
      "AutoSnipeCandy": 5000,
      "Level": 0,
      "AllowMultiAccountSnipe": false
    },
    "Pupitar": {
      "SnipeIV": 0,
      "Moves": [],
      "Operator": "or",
      "VerifiedOnly": false,
      "Priority": 2,
      "AutoSnipeCandy": 5000,
      "Level": 0,
      "AllowMultiAccountSnipe": false
    },
    "Tyranitar": {
      "SnipeIV": 0,
      "Moves": [],
      "Operator": "or",
      "VerifiedOnly": false,
      "Priority": 2,
      "AutoSnipeCandy": 5000,
      "Level": 0,
      "AllowMultiAccountSnipe": false
    },
    "Togetic": {
      "SnipeIV": 0,
      "Moves": [],
      "Operator": "or",
      "VerifiedOnly": false,
      "Priority": 1,
      "AutoSnipeCandy": 5000,
      "Level": 20,
      "AllowMultiAccountSnipe": false
    },
    "Lapras": {
      "SnipeIV": 100,
      "Moves": [],
      "Operator": "or",
      "VerifiedOnly": false,
      "Priority": 2,
      "AutoSnipeCandy": 5000,
      "Level": 20,
      "AllowMultiAccountSnipe": false
    },
    "Dratini": {
      "SnipeIV": 100,
      "Moves": [],
      "Operator": "or",
      "VerifiedOnly": false,
      "Priority": 5,
      "AutoSnipeCandy": 5000,
      "Level": 20,
      "AllowMultiAccountSnipe": false
    },
    "Snorlax": {
      "SnipeIV": 100,
      "Moves": [],
      "Operator": "or",
      "VerifiedOnly": false,
      "Priority": 3,
      "AutoSnipeCandy": 5000,
      "Level": 20,
      "AllowMultiAccountSnipe": false
    },
    "Aerodactyl": {
      "SnipeIV": 100,
      "Moves": [],
      "Operator": "or",
      "VerifiedOnly": false,
      "Priority": 5,
      "AutoSnipeCandy": 5000,
      "Level": 20,
      "AllowMultiAccountSnipe": false
    },
  },
