### ISSUE TITLE
GUI disobedience / Gym not prioritised

### ISSUE THREAD

**Issue by organicbetty** [Necrobot-Private/NecroBot#960]
I know the gym is still in beta, but there are a few issues with the priority gym > pokestop. The client continues to collect pokestops first, instead of the nearest gym. Furthermore, the client does not follow location where clicked in the GUI.

  "GymConfig": {
    "NotUsedSkills": [
      {
        "Key": "snorlax",
        "Value": "hyperBeam"
      },
      {
        "Key": "dragonite",
        "Value": "hyperBeam"
      },
      {
        "Key": "lapras",
        "Value": "blizzard"
      },
      {
        "Key": "cloyster",
        "Value": "blizzard"
      },
      {
        "Key": "flareon",
        "Value": "fireBlast"
      }
    ],
    "Enable": true,
    "PrioritizeGymOverPokestop": true,
    "MaxDistance": 200.0,
    "DefaultTeam": "Red",
    "MaxCPToDeploy": 3000,
    "MaxLevelToDeploy": 30,
    "VisitTimeout": 60,
    "UseRandomPokemon": false,
    "NumberOfTopPokemonToBeExcluded": 1,
    "CollectCoinAfterDeployed": 5,
    "EnableAttackGym": true,
    "MaxGymLevelToAttack": 6,
    "MaxDefendersToAttack": 6,
    "HealDefendersBeforeApplyToGym": true,
    "DontAttackAfterCoinsLimitReached": false,
    "EnableGymTraining": true,
    "TrainGymWhenMissingMaxPoints": 10000,
    "MaxGymLvlToTrain": 6,
    "TrainAlreadyDefendedGym": false,
    "MinCpToUseInAttack": 1000,
    "ButNotLessThanDefenderPercent": 0.75,
    "UsePokemonToAttackOnlyByCp": true,
    "ExcludeForGyms": [
      "kangaskhan",
      "tauros",
      "mrMime",
      "farfetchd"
    ],
    "DontUseDodge": true,
    "MinRevivePotions": 5,
    "PrioritizeGymWithFreeSlot": true,
    "SaveMaxRevives": true
  },

**Comment by hardknoxni69a** [comment]
updated in latestet versions
