### ISSUE TITLE
Autosnipe exclusion method 101 not working, sniping a Ledyba with 385 IV??!!

### ISSUE THREAD

**Issue by cvbmert** [Necrobot-Private/NecroBot#961]
Hello the autosnipe method of setting the autosnipeiv to 101 to exclude all pokemon except for the ones in the filter list doesn't stop everything. It still snipes the fake info pokemon that have over 100 IV haha.

**Comment by samuraitruong** [comment]
385 >101 :)), since data wrong only, we need fix data source, snipe work fine :)

**Comment by cvbmert** [comment]
So if I set the autosnipeiv to like 999 it will still autosnipe the pokemon I have filters set up for as a temporary work around?

**Comment by GrimmHubber** [comment]
The snipe config is verry confusing. If the devs could separate it into autoInternationalSnipe and autoWalkingSnipe it would be great, I have SnipeAtPokestops: true but at the same time i have AutoSnipe at false because I don't want to mess around with international sniping.

**Comment by samuraitruong** [comment]
we already has document for that, so you need read document before you setting, walk snipe is not related to any setting you mentioned above

**Comment by GrimmHubber** [comment]
samuraitruong if you mean this documentation here https://github.com/Necrobot-Private/NecroBot/wiki/Necrobot2-config.json-descriptions, then it's outdated, incomplete and in no place it implied that internation snipe and walk snipe were handled by different on/off switches. Maaaaaybe it's obvious to the people who built the code, but it didn't read that way to the people reading the config file.

**Comment by cswxin** [comment]
maybe he meant this document.
http://necrobot2.com/config.json/2017/01/07/how-to-config-auto-snipe/

**Comment by samuraitruong** [comment]
@GrimmHubber  read a link above , necrobot2.com is the website that provide up to date config guides

**Comment by samuraitruong** [comment]
closed as fixed, I removed the invalid IV >100 from data source
