### ISSUE TITLE
Setting the Device config in Auth.

### ISSUE THREAD

**Issue by nejnejxd** [Necrobot-Private/NecroBot#964]
Would setting the Device as a Android one result in other results under the; 
"Pokemon was Caught; 
Los Angeles, Nevada, America"

To something along ;
" , , , America"

I know it Differs from iOS to Android. iOS always show full, where android show one-three specifics.
My issue being; I dont want to display Where I caught said Pokemon.

Thanks

**Comment by jjskuld** [comment]
This location is just a local cache, it doesn't have anything to do with iOS or Android.
