### ISSUE TITLE
Out of pokeballs (I'm new) how to setup my config for farming ?

### ISSUE THREAD

**Issue by KonqQ** [Necrobot-Private/NecroBot#965]
I'm new, so sorry if this was explained before. I'm out of pokeballs and it seems like he has troubles to find pokestops. can i change my config so he quickly goes through alot of pokestops ?

and also what bot is this ? it looks nice : 

![91605faa-f85f-11e6-8c48-03a11e57ba09](https://cloud.githubusercontent.com/assets/25956662/23214384/cff1af44-f90e-11e6-9e45-10d544df932a.png)

**Comment by zuklio** [comment]
this is necrobot2.win version

**Comment by viaduk** [comment]
have same issue, after 3h, im on 0 balls. is there any setup for config, so bot start  to look only for pokestops for balls ?
