### ISSUE TITLE
Evolving Chansey using the Win GUI is not possible

### ISSUE THREAD

**Issue by 6Vampire6** [Necrobot-Private/NecroBot#966]
Evolving Chansey using the Win GUI is not possible.
You only need enough candy for that but the evolve button is greyed out.
Works on the device.

**Comment by samuraitruong** [comment]
how many candies it display on GUI, seem we are having issue with display candies for some pokemons. I will check after finish the current issue that I am working on

**Comment by 6Vampire6** [comment]
Tons of candy and as I said evolving using a device/smartphone works.

![966_blissey](https://cloud.githubusercontent.com/assets/20929443/23258697/9ca8055a-f9c9-11e6-92d2-239288b6381c.png)

**Comment by samuraitruong** [comment]
WIP

**Comment by samuraitruong** [comment]
fixed in #1006
