### ISSUE TITLE
Evolving Eevee in Win GUI shows only Vaporeon as target

### ISSUE THREAD

**Issue by 6Vampire6** [Necrobot-Private/NecroBot#968]
Evolving Eevee in Win GUI shows only Vaporeon as target.
The other possible targets (Jolteon, Flareon, Espeon, Umbreon) are greyed out.

I know you can decide only once by renaming an Eevee which Pokémon it will be evolved to.
This worked by renaiming the Eevee manually in the Win GUI before,
but I wonder why now only Vaporeon is shown as possible target.

**Comment by samuraitruong** [comment]
just display image, actually we can not target evolution branch, so you click on them are same. which pokemon evolved to belong to NIantic decision

**Comment by RogueMaster** [comment]
If pokemon is not in Pokedex it should give the other options, rename eevee to X (Sakura, Tamao, Rainer, Sparky, Pyro) and evolve and then rename to the pokemon name (Espeon,Umbreon,Vaporeon,Jolteon,Flareon)...

**Comment by hardknoxni69a** [comment]
if you click on the name u can rename before evolve but that trick only works once so would only lead to people compaining they didnt get what they want afterwards but definitely rename yourself the first time and will work for you
