### ISSUE TITLE
PokemonsTransferFilter logic weird

### ISSUE THREAD

**Issue by isveryfunny** [Necrobot-Private/NecroBot#969]
I want to keep 100% Eevee.
I set  "KeepMinDuplicatePokemon": 1 as below.
After (TRANSFERRED), still has 3 Eevee.

  "PokemonsTransferFilter": {
    "Eevee": {
      "KeepMinCp": 1,
      "KeepMinIvPercentage": 99.0,
      "KeepMinLvl": 1,
      "UseKeepMinLvl": true,
      "KeepMinOperator": "and",
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "DeprecatedMoves": null,
      "MovesOperator": "and",
      "CatchOnlyPokemonMeetTransferCriteria": false
    },
![image](https://cloud.githubusercontent.com/assets/25894737/23221681/ae3de366-f960-11e6-82c9-05ab6eb3f6a2.png)

If I take off "Eevee" from "PokemonsTransferFilter", then set "KeepMinDuplicatePokemon": 1,
After (TRANSFERRED), still has 2 Eevee and IV100% is gone.
![image](https://cloud.githubusercontent.com/assets/25894737/23222563/429cd20e-f963-11e6-9649-80bd97ca186c.png)

**Comment by isveryfunny** [comment]
![image](https://cloud.githubusercontent.com/assets/25894737/23222632/8157c684-f963-11e6-9f2b-dfc15c436cf3.png)

**Comment by samuraitruong** [comment]
hum, look weird, I don't have this issue thought, would you please pm me full config

**Comment by GrimmHubber** [comment]
"KeepMinCp": 1 
-> "KeepMinIvPercentage": 99.0,
     "KeepMinLvl": 1,
     "UseKeepMinLvl": true,
     "KeepMinOperator": "and",
It will only keep Eevees that are Lv. 1 or above AND have above 99% IVs.
Either lower your KeepMinIvPercentage to 97 or change the KeepMinOperator to "or".

**Comment by isveryfunny** [comment]
so weird.
I take off "Eevee" from "PokemonsTransferFilter", then set "KeepMinDuplicatePokemon": **0**
but Eevee still has 2.

![image](https://cloud.githubusercontent.com/assets/25894737/23299360/4d853c7e-fabc-11e6-9cea-0ccbcd6d50ad.png)

![image](https://cloud.githubusercontent.com/assets/25894737/23299474/aa63b2a4-fabc-11e6-9ccf-b85f7a2a6827.png)

**Comment by isveryfunny** [comment]
and second one can't click "TRANSFER"

**Comment by isveryfunny** [comment]
I can give you the account if you want to try it. ^^

**Comment by samuraitruong** [comment]
hey, keep min is keep min now keep max, if all your pokemon above kee min condition, it will be kept

**Comment by hardknoxni69a** [comment]
those eevees are probably just being saved to be evolved

**Comment by hardknoxni69a** [comment]
keepmin is like this is what i want to keep no matter what once you add a number to keepminduplicate it will keep 1 no matter what even if it doesnt meet your requirements
