### ISSUE TITLE
Unexpected character encountered while parsing value:

### ISSUE THREAD

**Issue by deadmau5582** [Necrobot-Private/NecroBot#974]
Hello i got now the Problem:

"Unexpected character encountered while parsing value: <. Path '', line 0, position 0."

What can be the issue?

Best Regards

**Comment by stikio** [comment]
same here. problem startet while bot was running. error encounters even after restart.

**Comment by N1jada** [comment]
![necroboterror](https://cloud.githubusercontent.com/assets/25505063/23230635/a5ad0246-f93c-11e6-8ea2-ad27f78a4a79.PNG)

**Comment by garette1** [comment]
same here...

**Comment by samuraitruong** [comment]
PTC login server seem not working , retry in few hours

**Comment by deadmau5582** [comment]
Thaks for your response :)

**Comment by Ryndael** [comment]
I'm an amateur when it comes to this stuff, but I can log in with any of my PTC accounts on my phone. Yet, when I go to open the bot, I get the same error noted above. 

Seems like some sort of issue on the bot's end.

**Comment by deadmau5582** [comment]
With the same acc which you used with the bot and Phone?

**Comment by Ryndael** [comment]
Yuppers.

**Comment by twincitygamer** [comment]
I have the same issue and just created a brand new ptc account and still same error

**Comment by twincitygamer** [comment]
but a different ptc account on my phone is fine

**Comment by twincitygamer** [comment]
re downloaded bot didnt fix it

**Comment by deadmau5582** [comment]
Watch the Errors here: http://allestörungen.de/stoerung/pokemon-go

**Comment by kehrijksen** [comment]
Same error, appeared while botting. Restarting and redownloading does not fix the error.

**Comment by twincitygamer** [comment]
no fixes

**Comment by Ryndael** [comment]
It appears to be working now, yay.

**Comment by cswxin** [comment]
I have the same issue several hours ago, and it seems to be working now.

**Comment by hardknoxni69a** [comment]
sever was down good to go now guys

**Comment by DorianW96** [comment]
I am having trouble with this error since I try to use the bot. 

I started trying to use it yesterday. On my phone, everything is working just fine but the bot won´t connect. Is there anyone who might be able to help?

Thanks in advance!
