### ISSUE TITLE
Necrobot doesn't allow to not recycle

### ISSUE THREAD

**Issue by redking974** [Necrobot-Private/NecroBot#977]
### Expected Behavior:
I want to create a config for a bubblestrat account. For this, I need to gain the lower xp as possible. So I'm trying to not recycle by making value to "RecycleInventoryAtUsagePercentage": 101. With this, Necrobot won't recycling when bag is full, and won't going xp to making Pokestops after recycling. With this value 101, Necrobot will continue to make Pokestops and will fail if bag is full, but will success when bag have place after Necrobot uses Pokeballs to catch Pokemons.

### Actual Behavior:
I can't success to configure Necrobot to not recycling

### Your config.json:
```
  "RecycleConfig": {
    "VerboseRecycling": true,
    "RecycleInventoryAtUsagePercentage": 100.0,
    "RandomizeRecycle": false,
    "RandomRecycleValue": 3,
    "TotalAmountOfPokeballsToKeep": 180,
    "TotalAmountOfPotionsToKeep": 100,
    "TotalAmountOfRevivesToKeep": 35,
    "TotalAmountOfBerriesToKeep": 35,
    "UseRecyclePercentsInsteadOfTotals": true,
    "PercentOfInventoryPokeballsToKeep": 50,
    "PercentOfInventoryPotionsToKeep": 30,
    "PercentOfInventoryRevivesToKeep": 10,
    "PercentOfInventoryBerriesToKeep": 10
  },
```

### (OPTIONAL) Your Log:
```
[20:26:54] (POKESTOP) Krakatoa +0XP | 0 Gems | L'inventaire des objets est plein. Aucun objet n'a pu être récolté!
[20:26:54] (INFO) Poké Balls: 147 | Super Balls: 20 | Hyper Balls: 0 | Master Balls: 0
[20:26:54] (INFO) Potions: 2 | Super Potions: 54 | Hyper Potions: 48 | Potions Max: 0
[20:26:54] (INFO) Rappels: 31 | Rappels Max: 0
[20:26:54] (INFO) Baies: 31 | Encens: 6 | Œuf chance: 3 | Leurres: 3
[20:26:55] (RECYCLAGE) ItemPotion x2
[20:27:02] (RECYCLAGE) ItemSuperPotion x1
[20:27:07] (RECYCLAGE) ItemPokeBall x47
[20:27:13] (INFO) (POKESTOP LIMIT) 77/1715
```

### Detailed Steps to Reproduce:

Version: 115
Windows Version: W10
What is affected (catch, transfer, favorite, GPX, evolve, recycle, snipe, human walk snipe, pokestops, powerup/levelup, other): recycle

**Comment by hardknoxni69a** [comment]
all uhave to do is have minimum values above bag size

**Comment by redking974** [comment]
Hi @hardknoxni69a do you speak about "ItemRecycleFilter" ?

**Comment by hardknoxni69a** [comment]
you can use that or regular filter

but you have 350 so set minimum as 300 balls 50 berries or something
