### ISSUE TITLE
PokemonToSnipe configuration

### ISSUE THREAD

**Issue by LSAC-Hao** [Necrobot-Private/NecroBot#978]
Changing settings via NecroBot2.Win will cause PokemonToSnipe section in config.json erased to default.

  "PokemonToSnipe": {
    "Locations": [],
    "Pokemon": [
      "larvitar",
      "pupitar",
      "tyranitar",
      "porygon2",
      "ampharos",
      "typhlosion",
      "feraligatr",
      "ursaring",
      "espeon",
      "scizor",
      "heracross",
      "blissey",
      "bulbasaur",
      "ivysaur",
      "venusaur",
      "charmander",
      "charmeleon",
      "charizard",
      "squirtle",
      "wartortle",
      "blastoise",
      "sandslash",
      "nidorina",
      "nidoqueen",
      "clefairy",
      "clefable",
      "jigglypuff",
      "wigglytuff",
      "growlithe",
      "arcanine",
      "poliwag",
      "poliwhirl",
      "poliwrath",
      "abra",
      "kadabra",
      "alakazam",
      "bellsprout",
      "weepinbell",
      "victreebel",
      "slowpoke",
      "slowbro",
      "farfetchd",
      "grimer",
      "muk",
      "shellder",
      "cloyster",
      "haunter",
      "gengar",
      "hypno",
      "exeggcute",
      "exeggutor",
      "rhyhorn",
      "rhydon",
      "chansey",
      "tangela",
      "kangaskhan",
      "staryu",
      "starmie",
      "mrMime",
      "jynx",
      "magikarp",
      "gyarados",
      "lapras",
      "ditto",
      "eevee",
      "vaporeon",
      "jolteon",
      "flareon",
      "omanyte",
      "omastar",
      "aerodactyl",
      "snorlax",
      "articuno",
      "zapdos",
      "moltres",
      "dratini",
      "dragonair",
      "dragonite",
      "mewtwo",
      "mew"
    ]
  },

**Comment by samuraitruong** [comment]
this section going to be removed soon as a part of clean config file

**Comment by samuraitruong** [comment]
this section now is removed and merge to PokemonSnipeFilters which has better supports

**Comment by hardknoxni69a** [comment]
I use Pokemontosnipefilter for my local catches usepokemontosnipefilter true under catch settings do I now have to add every single Pokemon to.the not to catch filter and turn that on and off
