### ISSUE TITLE
Error with api request type: getplayer

### ISSUE THREAD

**Issue by twincitygamer** [Necrobot-Private/NecroBot#982]
https://gyazo.com/5212bd8c8a4ee9a172f8693396ecff94
I get this error when i start

**Comment by ppesky** [comment]
me too.

**Comment by DonPancake** [comment]
make that me as well

**Comment by Mafia121** [comment]
Same.

**Comment by Jitm92** [comment]
Same here.

**Comment by konhai** [comment]
ban??? app in android is working fine.

**Comment by Mafia121** [comment]
not a ban as i am able to login from my phone

**Comment by wns25678** [comment]
niantic block 0.45API

**Comment by konhai** [comment]
Can this lead to accounts getting blocked??

**Comment by wns25678** [comment]
No one can be sure.

**Comment by axpcaptainb** [comment]
Did they block it today? It worked fine yesterday.

**Comment by yayahai** [comment]
0.45 API is now obsolete. Eternal bot is also not working.

**Comment by Steve12341** [comment]
Anyone got any updates on this issue.

**Comment by Riccardo75** [comment]
me 2 api error

**Comment by RicoEdg** [comment]
I used mine up until 5pm Toronto time.

**Comment by yayahai** [comment]
The fake GPS method is also not working on Android. So major update niantic has brought.

**Comment by garette1** [comment]
anyone try with new api key ?

**Comment by samuraitruong** [comment]
API 0.45 shutdown.

**Comment by garette1** [comment]
what does it mean

**Comment by yayahai** [comment]
People using the pogodev API (the Paid one)
facing any issues??

**Comment by samuraitruong** [comment]
close since API 45 now dead

**Comment by yayahai** [comment]
Any free alternatives????

**Comment by Nigromante2004** [comment]
I have the same problem. I cant login using Google Account. I hope you can solve this problem.

Thanks for all

**Comment by hardknoxni69a** [comment]
this has been resolved in latest version 45 now works again enjoy and support necrobot by hitting that donate button or helping others in discord chat
