### ISSUE TITLE
RIP Recycle percentage ???

### ISSUE THREAD

**Issue by FaruqX** [Necrobot-Private/NecroBot#985]
![screenshot_2](https://cloud.githubusercontent.com/assets/11961119/23255031/06000fe0-f9f5-11e6-83c7-82556c5d7369.png)
![screenshot_3](https://cloud.githubusercontent.com/assets/11961119/23255032/062b770c-f9f5-11e6-9a21-9ad1a39e0e73.png)

i set in config recycle by percent, and then i set 28% for revive, so i should save 101 revives? but the bot recycle revive before i have 101 revives.

sorry for my bad english

**Comment by samuraitruong** [comment]
your title isnt friendly to me
you also need check for RecyceItemFilters settings. and many config related
