### ISSUE TITLE
Necrobot Login issue

### ISSUE THREAD

**Issue by Esodux** [Necrobot-Private/NecroBot#988]
Hey guys today I wanna start the bot but I got the following text.

[11:54:26] (INFO) PokemonGo.RocketAPI.Exceptions.InvalidResponseException: Error with API request type: GetPlayer
bei PokemonGo.RocketAPI.Extensions.HttpClientExtensions.d__12.MoveNext() in c:\projects\necrobot2\FeroxRev\Extensions\HttpClientExtensions.cs:Zeile 68. --- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde --- bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) bei PokemonGo.RocketAPI.Rpc.BaseRpc.<PostProtoPayload>d__42.MoveNext() in c:\projects\necrobot2\FeroxRev\Rpc\BaseRpc.cs:Zeile 0.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
bei PokemonGo.RocketAPI.Rpc.Player.d__9.MoveNext() in c:\projects\necrobot2\FeroxRev\Rpc\Player.cs:Zeile 141.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
bei PokemonGo.RocketAPI.Rpc.Login.d__10.MoveNext() in c:\projects\necrobot2\FeroxRev\Rpc\Login.cs:Zeile 170.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
bei System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
bei PoGo.NecroBot.Logic.State.LoginState.d__3.MoveNext() in c:\projects\necrobot2\PoGo.NecroBot.Logic\State\LoginState.cs:Zeile 50.

I'm not banned because I can play on my phone.
Did someone know what I can do?

**Comment by GrandPaB** [comment]
#982

**Comment by Esodux** [comment]
Thanks!
