### ISSUE TITLE
API 0.45 was shutdown by Niantic

### ISSUE THREAD

**Issue by GrimmHubber** [Necrobot-Private/NecroBot#992]
Error: 
() API 0.45 was shutdown by Niantic, bot no longer work with your current setup, please consider to use paid API instead.

Anyone has the link to the site selling the APIs? 
Anyone know if I can buy them w/ google credits? I'm not gonna make an international credit card and pay annuity just for this.

**Comment by macinmn** [comment]
links to buy:
https://talk.pogodev.org/d/51-api-hashing-service-by-pokefarmer

they take paypal which will convert your local currency demonination into euros for you

**Comment by GrandPaB** [comment]
@macinmn I'm reading comments at the moment on the website you've posted. Some people talking about a scam, others saying it's working just fine and received the code within minutes after payment. You wanna share you experience with it?

~GFB

**Comment by macinmn** [comment]
I've purchased the 150-class key twice.  gotten the key in my email less than 5 minutes later each time, also appears on their site when you register using the same email.  the expiration clock doesn't start until the first time you use it, so if for some reason it takes longer you don't lose any fair time.

**Comment by GrandPaB** [comment]
Allright, thanks! Could you also tell me someting about the RPM? For example; whats the difference between the smallest one and the biggest one? Everytime the bot does 'something' it counts as 1RPM? Sorry for being such a noob, I'm fairly new to this kinda stuff.

~GPB

**Comment by pakitosapo** [comment]
Hi all , I also would like to know does this package, I read that lasts a month, but you're telling me that works in time, it could be more clear about the duration of this API keyHi all , I also would like to know does this package, I read that lasts a month, but you're telling me that works in time, it could be more clear about the duration of this API key

**Comment by GrandPaB** [comment]
The key DOES last for a month, it only starts the moment you'll activate it. If I understood @macinmn correctly.

**Comment by macinmn** [comment]
@pakitosapo  the keys will expire 31 days after the initial time it is actually used.   a key bought today February 23 at 21:00 and used first at 23:30, (because February is a 28 days month, add 3 days)will expire March 26 23:30.

@GrandPaB  150Req per minute is plenty for Necrobot by itself, I seldom see it go over 40.  your requests will get 'limited' (throtled) until you drop below that RPM threshold
