### ISSUE TITLE
free necrobot was dead ??

### ISSUE THREAD

**Issue by garette1** [Necrobot-Private/NecroBot#994]
do we have to pay ??

**Comment by pakitosapo** [comment]
Already, they say that we have to buy the RPM package

**Comment by jeafke** [comment]
Change in visual studio the following:
PokemonGo.RocketAPI\Client.cs Line: 73
`Unknown25 = -1553869577012279119;`

to:
`Unknown25 = -816976800928766045;`

Works :-)

**Comment by samuraitruong** [comment]
I will try, thanks

**Comment by Riccardo75** [comment]
then itt will work agian?

**Comment by Alex0201** [comment]
I wanted to try to change the Client.cs but when I open the project with Visual Studio it says that PokemonGo.RocketAPI could not openend because the project was not found. I'm a noob in this can somebody help me... what am I doing wrong... 
Thanks

**Comment by remcoberns** [comment]
wher do i find this ?

**Comment by garette1** [comment]
@jeafke where is that line? which file?

**Comment by samuraitruong** [comment]
reate v118 re-enable 0.45 thanks @jeafke
