### ISSUE TITLE
Snipe List Update time

### ISSUE THREAD

**Issue by krishnaraovs** [Necrobot-Private/NecroBot#995]
Snipe list is updating very quickly in Snipe-Others Tab. Before I click snipe new pokemon is added to the list and the needed pokemon is moving away.

Is there anyway I can make it slow to update the list.

**Snipe Config:** 

SnipeConfig": {
    "UseSnipeLocationServer": false,
    "SnipeLocationServer": "localhost",
    "SnipeLocationServerPort": 16969,
    "GetSniperInfoFromPokezz": false,
    "GetOnlyVerifiedSniperInfoFromPokezz": false,
    "GetSniperInfoFromPokeSnipers": true,
    "GetSniperInfoFromPokeWatchers": false,
    "GetSniperInfoFromSkiplagged": false,
    "MinPokeballsToSnipe": 20,
    "MinPokeballsWhileSnipe": 0,
    "MinDelayBetweenSnipes": 60000,
    "SnipingScanOffset": 0.005,
    "SnipeAtPokestops": false,
    "SnipeIgnoreUnknownIv": false,
    "UseTransferIvForSnipe": false,
    "SnipePokemonNotInPokedex": true,
    "UseSnipeLimit": true,
    "SnipeRestSeconds": 600,
    "SnipeCountLimit": 39,
    "ActivateMSniper": true,
    "MinIVForAutoSnipe": 100,
    "MinLevelForAutoSnipe": 0,
    "AutosnipeVerifiedOnly": true,
    "DefaultAutoSnipeCandy": 0,
    "SnipePauseOnOutOfBallTime": 5,
    "AutoSnipeMaxDistance": 0.0,
    "AutoSnipeBatchSize": 10
  },
  "HumanWalkSnipeConfig": {
    "Enable": false,
    "DisplayPokemonList": true,
    "MaxDistance": 1500.0,
    "MaxEstimateTime": 900.0,
    "CatchEmAllMinBalls": 50,
    "TryCatchEmAll": true,
    "CatchPokemonWhileWalking": true,
    "SpinWhileWalking": true,
    "AlwaysWalkback": false,
    "SnipingScanOffset": 0.025,
    "WalkbackDistanceLimit": 300.0,
    "IncludeDefaultLocation": true,
    "UseSnipePokemonList": true,
    "MaxSpeedUpSpeed": 60.0,
    "AllowSpeedUp": true,
    "DelayTimeAtDestination": 10000,
    "UsePokeRadar": false,
    "UseSkiplagged": false,
    "UsePokecrew": false,
    "UsePokesnipers": false,
    "UsePokeZZ": false,
    "UsePokeWatcher": false,
    "UseFastPokemap": false,
    "UsePogoLocationFeeder": false,
    "AllowTransferWhileWalking": false
  },
  "DataSharingConfig": {
    "EnableSyncData": true,
    "AutoSnipe": true,
    "DataServiceIdentification": "",
    "SnipeDataAccessKey": "",
    "EnableFailoverDataServers": true,
    "FailoverDataServers": "ws://s1.mypogosnipers.com/socket.io/?EIO=3&transport=websocket;ws://s2.mypogosnipers.com/socket.io/?EIO=3&transport=websocket",
    "DataRecieverURL": "ws://necrosocket.herokuapp.com/socket.io/?EIO=3&transport=websocket"
  },

Version: 1.0.0.117
Windows Version: 7 64bit
What is affected (catch, transfer, favorite, GPX, evolve, recycle, snipe, human walk snipe, pokestops, powerup/levelup, other):

**Comment by samuraitruong** [comment]
going to add some setting for control this

**Comment by samuraitruong** [comment]
#804 

https://github.com/Necrobot-Private/NecroBot/pull/1134
