### ISSUE TITLE
[Request Feature] Manual collect coin and notification

### ISSUE THREAD

**Issue by FaruqRahmadani** [Necrobot-Private/NecroBot#996]
maybe if we can collect coin manually will be great. use command or telegram
and if the bot collected coin automatically or manually then we will get notification in telegram,
last, add config for notification on telegram if the bot start. true or false. thanks

**Comment by mangonzalez00783** [comment]
Has already been reported a lot about snipe, i think at the moment it is not a priority...

**Comment by FaruqRahmadani** [comment]
ok, when the snipe issue is closed, can this feature implemented? hopely :D

**Comment by hardknoxni69a** [comment]
Attaching to #1029
